### PR TITLE
fix: volatile expressions should not be target of common subexpt elimination

### LINKED ISSUE #8518: Multiple calls to the same `volatile` function do not produce different answers
### Describe the bug

When I call a function like `random()` twice I expect to get different values, but I only get a single value

### To Reproduce

```sql
❯ select random() r1, random() r2;
+--------------------+--------------------+
| r1                 | r2                 |
+--------------------+--------------------+
| 0.5798857099939392 | 0.5798857099939392 |
+--------------------+--------------------+
1 row in set. Query took 0.002 seconds.
```

### Expected behavior

I expect the values from the two different calls to `random()` to be different

### Additional context

The explain plan shows what is wrong:

```sql
❯ explain select random() r1, random() r2;
+---------------+--------------------------------------------------------------------+
| plan_type     | plan                                                               |
+---------------+--------------------------------------------------------------------+
| logical_plan  | Projection: random() AS random() AS r1, random() AS random() AS r2 |
|               |   Projection: random() AS random()                                 |
|               |     EmptyRelation                                                  |
| physical_plan | ProjectionExec: expr=[random()@0 as r1, random()@0 as r2]          |
|               |   ProjectionExec: expr=[random()]                                  |
|               |     PlaceholderRowExec                                             |
|               |                                                                    |
+---------------+--------------------------------------------------------------------+
```

And explain verbose shows the problem is introduced in logical_plan after `common_sub_expression_eliminate`:
```sql
❯ explain verbose select random() r1, random() r2;
+------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| plan_type                                                  | plan                                                                                                                          |
+------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| initial_logical_plan                                       | Projection: random() AS r1, random() AS r2                                                                                    |
|                                                            |   EmptyRelation                                                                                                               |
| logical_plan after inline_table_scan                       | SAME TEXT AS ABOVE                                                                                                            |
....
                                                                                               |
| logical_plan after eliminate_cross_join                    | SAME TEXT AS ABOVE                                                                                                            |
| logical_plan after common_sub_expression_eliminate         | Projection: random() AS random() AS r1, random() AS random() AS r2                                                            |
|                                                            |   Projection: random() AS random()                                                                                            |
|                                                            |     EmptyRelation
```

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #8518.

### CODE REVIEW

File: datafusion/expr/src/expr.rs [hunk 1]
```diff
@@ -1692,6 +1692,24 @@ fn create_names(exprs: &[Expr]) -> Result<String> {
...
+#[allow(clippy::match_like_matches_macro)]
+pub fn is_volatile(expr: &Expr) -> bool {
+    match expr {
+        Expr::ScalarFunction(func) => match func.func_def {
+            ScalarFunctionDefinition::BuiltIn(func) => match func {
+                BuiltinScalarFunction::Random => true,
+                _ => false,
+            },
+            // TODO: Add volatile flag to UDFs
+            ScalarFunctionDefinition::UDF(_) => false,
```
Comment (viirya) [inline datafusion/expr/src/expr.rs:1706]: Ideally, UDFs could have volatile variants. I defer to work on it later and focus this PR for the bug fix only.

File: datafusion/sqllogictest/test_files/functions.slt [hunk 2]
```diff
@@ -995,3 +995,8 @@ query ?
 SELECT find_in_set(NULL, NULL)
 ----
 NULL
+
+query B
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/functions.slt:999]: Providing context about what this test is doing might be helpful for the future. Something like

```suggestion
# Verify that multiple calls to volatile functions like `random()` are not combined / optimized away
query B
```

File: datafusion/expr/src/expr.rs (hunk 1 above)
Comment (alamb) [reply datafusion/expr/src/expr.rs:1706]: I think they can have volatile set as part of their signature: https://docs.rs/datafusion/latest/datafusion/logical_expr/struct.ScalarUDF.html#structfield.signature
 (and a field on Signature is `volatile`)

File: datafusion/expr/src/expr.rs [hunk 3]
```diff
@@ -1692,6 +1692,24 @@ fn create_names(exprs: &[Expr]) -> Result<String> {
         .join(", "))
 }
 
+/// Whether the given expression is volatile, i.e. whether it can return different results
```
Comment (alamb) [inline datafusion/expr/src/expr.rs:1695]: Volatility is already captured as part of the function signature. I think you can access it like `func.volatility()`:

https://github.com/apache/arrow-datafusion/blob/7f312c8a1d82b19f03c640e4a5d7d6437b2ee835/datafusion/expr/src/built_in_function.rs#L360-L363

File: datafusion/expr/src/expr.rs [hunk 4]
```diff
@@ -1692,6 +1692,24 @@ fn create_names(exprs: &[Expr]) -> Result<String> {
...
+/// when evaluated multiple times with the same input.
+#[allow(clippy::match_like_matches_macro)]
+pub fn is_volatile(expr: &Expr) -> bool {
+    match expr {
+        Expr::ScalarFunction(func) => match func.func_def {
+            ScalarFunctionDefinition::BuiltIn(func) => match func {
```
Comment (alamb) [inline datafusion/expr/src/expr.rs:1701]: I suggest moving this logic into  a method like `ScalarFunctionDefinition::volatility` directly ?

https://github.com/apache/arrow-datafusion/blob/7f312c8a1d82b19f03c640e4a5d7d6437b2ee835/datafusion/expr/src/expr.rs#L339-L348

**Review by alamb — COMMENTED** [review]
Thank you @viirya  -- this is about the fastest turnaround I have ever seen for a issue filed --> PR created 🙏 

I think we should be checking volatility slightly differently, and I left comments about why and how inline.

Thanks again for such a fast PR

File: datafusion/sqllogictest/test_files/functions.slt [hunk 5]
```diff
@@ -995,3 +995,8 @@ query ?
...
+SELECT r1 == r2 FROM (SELECT random() r1, random() r2)
+----
+false
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/functions.slt:1002]: For some reason, this query actually passes on `main` without the changes from this PR:

```
DataFusion CLI v33.0.0
❯ SELECT r1 == r2 FROM (SELECT random() r1, random() r2);
+---------+
| r1 = r2 |
+---------+
| false   |
+---------+
1 row in set. Query took 0.023 seconds.

❯ explain SELECT r1 == r2 FROM (SELECT random() r1, random() r2);
+---------------+-------------------------------------------------------+
| plan_type     | plan                                                  |
+---------------+-------------------------------------------------------+
| logical_plan  | Projection: random() = random() AS r1 = r2            |
|               |   EmptyRelation                                       |
| physical_plan | ProjectionExec: expr=[random() = random() as r1 = r2] |
|               |   PlaceholderRowExec                                  |
|               |                                                       |
+---------------+-------------------------------------------------------+
2 rows in set. Query took 0.009 seconds.

DataFusion CLI v33.0.0
❯ explain verbose SELECT r1 == r2 FROM (SELECT random() r1, random() r2);
+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
| plan_type                                                  | plan                                                                                                           |
+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
| initial_logical_plan                                       | Projection: r1 = r2                                                                                            |
|                                                            |   Projection: random() AS r1, random() AS r2                                                                   |
|                                                            |     EmptyRelation                                                                                              |
...
| logical_plan after optimize_projections                    | Projection: random() = random() AS r1 = r2                                                                     |
|                                                            |   Projection: random() AS random()                                                                             |
|                                                            |     EmptyRelation                                                                                              |
| logical_plan after eliminate_nested_union                  | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after simplify_expressions                    | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after unwrap_cast_in_comparison               | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after replace_distinct_aggregate              | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after eliminate_join                          | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after decorrelate_predicate_subquery          | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after scalar_subquery_to_join                 | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after extract_equijoin_predicate              | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after simplify_expressions                    | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after rewrite_disjunctive_predicate           | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after eliminate_duplicated_expr               | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after eliminate_filter                        | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after eliminate_cross_join                    | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after common_sub_expression_eliminate         | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after eliminate_limit                         | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after propagate_empty_relation                | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after eliminate_one_union                     | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after filter_null_join_keys                   | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after eliminate_outer_join                    | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after push_down_limit                         | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after push_down_filter                        | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after single_distinct_aggregation_to_group_by | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after simplify_expressions                    | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after unwrap_cast_in_comparison               | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after common_sub_expression_eliminate         | SAME TEXT AS ABOVE                                                                                             |
| logical_plan after optimize_projections                    | Projection: random() = random() AS r1 = r2                                                                     |
|                                                            |   EmptyRelation
```

File: datafusion/expr/src/expr.rs (hunk 3 above)
Comment (viirya) [reply datafusion/expr/src/expr.rs:1695]: Oh, cool. I tried to find one but didn't find it.

File: datafusion/expr/src/expr.rs (hunk 4 above)
Comment (viirya) [reply datafusion/expr/src/expr.rs:1701]: Okay.

**Review by waynexia — APPROVED** [review]
Looks great! I find a document from Postgres which describes the same behavior:

>Any function with side-effects must be labeled VOLATILE, so that calls to it cannot be optimized away. Even a function with no side-effects needs to be labeled VOLATILE if its value can change within a single query; some examples are random(), currval(), timeofday().

File: datafusion/expr/src/expr.rs [hunk 6]
```diff
@@ -373,6 +373,20 @@ impl ScalarFunctionDefinition {
...
+    /// when evaluated multiple times with the same input.
+    pub fn is_volatile(&self) -> bool {
+        match self {
+            ScalarFunctionDefinition::BuiltIn(fun) => {
+                fun.volatility() == crate::Volatility::Volatile
+            }
+            ScalarFunctionDefinition::UDF(udf) => {
+                udf.signature().volatility == crate::Volatility::Volatile
+            }
+            ScalarFunctionDefinition::Name(_) => false,
```
Comment (crepererum) [inline datafusion/expr/src/expr.rs:387]: Under which condition does the optimizer see an unresolved function name? And: if we don't know how the function behaves (because there's only a name) shouldn't we assume the worst case (i.e. that it is volatile)?

Comment (alamb) [reply datafusion/expr/src/expr.rs:387]: I agree  we should assume it is volatile  given lack of additional information

At this moment, I don't think the optimizer will ever see unresolved function names

The plan is to use them to implement `expr_fn`s like [`power`](https://docs.rs/datafusion/latest/datafusion/logical_expr/fn.power.html) once we remove the hard coded list of built in functions as decsribed in https://github.com/apache/arrow-datafusion/issues/8045

In fact @edmondop  is working on this as part of https://github.com/apache/arrow-datafusion/issues/8157

Comment (crepererum) [reply datafusion/expr/src/expr.rs:387]: The "resolve" pass should probably run before other optimizers then, right? So maybe it's even safe to error out if we hit an unresolved function here.

**Comment by alamb** [comment]
> The "resolve" pass should probably run before other optimizers then, right? So maybe it's even safe to error out if we hit an unresolved function here.

Yes, I agree this is a good idea. The resolution should run before the optimizers (we have it as part of the analysis pass at the moment)

**Comment by edmondop** [comment]
Should I remove the resolution from the analyser and put it outside /
before ?

File: datafusion/expr/src/expr.rs (hunk 6 above)
Comment (viirya) [reply datafusion/expr/src/expr.rs:387]: It makes sense to get error on unresolved scalar function here. Missing that it is a unresolved one. (maybe renaming it to `Unresolved` 🤔 ).

File: datafusion/sqllogictest/test_files/functions.slt [hunk 7]
```diff
@@ -995,3 +995,9 @@ query ?
 SELECT find_in_set(NULL, NULL)
 ----
 NULL
+
+# Verify that multiple calls to volatile functions like `random()` are not combined / optimized away
+query B
+SELECT r FROM (SELECT r1 == r2 r, r1, r2 FROM (SELECT random() r1, random() r2) WHERE r1 > 0 AND r2 > 0)
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/functions.slt:1001]: 👍 

This test fails on main:

```
❯ SELECT r FROM (SELECT r1 == r2 r, r1, r2 FROM (SELECT random() r1, random() r2) WHERE r1 > 0 AND r2 > 0)
;
+------+
| r    |
+------+
| true |
+------+
1 row in set. Query took 0.037 seconds.
```

**Review by alamb — APPROVED** [review]
Thank you very much @viirya  for your quick and thorough work on this PR

**Comment by viirya** [comment]
Thanks for review @alamb @crepererum @waynexia
