### PR TITLE
Ignore blank lines and comments at the end of query files for datafusion-cli

### LINKED ISSUE #7071: datafusion-clli complains if blank lines or blank lines + comments are at the end of query files
### Describe the bug

Given we have a query file which contains blank lines or blank lines + comments at the end of it.

```
select now();

```
```
select now();

-- Some comments 
```

If we use such a file with datafusion-cli, it complains like as follows.
```
$ datafusion-cli -f /path/to/sql
DataFusion CLI v27.0.0
+--------------------------------+
| now()                          |
+--------------------------------+
| 2023-07-24T18:09:50.914361513Z |
+--------------------------------+
1 row in set. Query took 0.006 seconds.
This feature is not implemented: The context requires a statement!
```

This is a minor issue but users could be surprised by what the error message means because any popular REPL tools like psql or spark-sql don't complain with such conditions.

### To Reproduce

Explained above.

### Expected behavior

No error message should be shown with such query files.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sarutak**
# Which issue does this PR close?

Close #7071 

# Rationale for this change

For better usability.

# What changes are included in this PR?

Changed `exec::exec_from_lines` to ignore blank lines and comments at the end of query files for `datafusion-cli`.

# Are these changes tested?

Manually tested with query files which contain the following queries.
```
select now();

```

```
select now();

-- Some comments
```

Then, `datafusion-cli` doesn't complain.
```
+--------------------------------+
| now()                          |
+--------------------------------+
| 2023-07-24T18:22:06.373420703Z |
+--------------------------------+
1 row in set. Query took 0.005 seconds.
```

# Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion-cli/src/exec.rs [hunk 1]
```diff
@@ -88,7 +88,8 @@ pub async fn exec_from_lines(
     }
 
     // run the left over query if the last statement doesn't contain ‘;’
-    if !query.is_empty() {
+    // ignore if it only consists of '\n'
+    if query.contains(|c| c != '\n') {
```
Comment (alamb) [inline datafusion-cli/src/exec.rs:92]: maybe we could also check for spaces?

```suggestion
    if query.contains(|c| c != '\n' && c != ' ') {
```

**Review by alamb — APPROVED** [review]
Thank you @sarutak  -- this looks great. CI is failing for some reason https://github.com/apache/arrow-datafusion/issues/7078 unrelated to your changed

File: datafusion-cli/src/exec.rs (hunk 1 above)
Comment (sarutak) [reply datafusion-cli/src/exec.rs:92]: @alamb Thank you for looking into this PR!
I don't think we need to checn `' '` here because lines are [trimmed](https://github.com/apache/arrow-datafusion/pull/7076/files#diff-00370e7628c93a0c9da5107fa0d065240ff09d0425d9559b8662fb0b2e10feebL72).
Actually, `' '` and any other whitespaces like `U+3000` are ignored even though they are at the end of a file.

**Comment by alamb** [comment]
I merged up from main to get the fix for https://github.com/apache/arrow-datafusion/issues/7078 and hope to merge this when tests pass
