### PR TITLE
Parse identifiers properly for TableReferences

### LINKED ISSUE #4532: String --> TableReference parsing does not properly handle `"` and `.`
**Describe the bug**
Some DataFusion APIs take a string and convert to a table name but do not parse the identifiers correctly (specifically they ignore case normalization and quotes

**To Reproduce**
Register a table with

https://docs.rs/datafusion/15.0.0/datafusion/execution/context/struct.SessionContext.html#method.register_table

```rust
ctx.register_table("\"foo.bar\"", t);
```
 registers a table `bar` in schema `foo`

Likewise 

```rust
ctx.register_table("\"Bar\"", t);
```
registers a table named `Bar`

In SQL
* `CREATE TABLE "foo.bar"` registers a table `foo.bar`
* `CREATE TABLE Bar...` registers a table `bar` 

**Expected behavior**
The table should be registered parsed as a name `foo.bar` 

**Additional context**
Found while working on https://github.com/apache/arrow-datafusion/pull/4530

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #4532

# Rationale for this change

Be able to parse identifiers properly for TableReference:

- normalize unquoted identifiers
- able to parse quoted identifiers with special characters (e.g. period)

# What changes are included in this PR?

Change TableReference to hold Cows of its str's since need to allocate new String due to parsing (not to mention for normalization as well)
- need to fix usages since can't derive Copy anymore

Use SQL parser to parse the possible multipart identifier, which handles quoted identifiers correctly

# Are these changes tested?

New unit test added

# Are there any user-facing changes?

TableReference public API is changed (`Cow<str>` instead of raw `&str`)

### CODE REVIEW

File: datafusion/common/src/table_reference.rs [hunk 1]
```diff
@@ -155,50 +178,110 @@ impl<'a> TableReference<'a> {
...
-                catalog: parts[0],
-                schema: parts[1],
-                table: parts[2],
+                catalog: parts.remove(0).into(),
+                schema: parts.remove(0).into(),
+                table: parts.remove(0).into(),
             },
-            _ => Self::Bare { table: s },
+            // TODO: should normalize?
+            _ => Self::Bare { table: s.into() },
```
Comment (Jefffrey) [inline datafusion/common/src/table_reference.rs:225]: parse_identifiers will return `String` anyway (wrapped in `Ident`) so only this last case could actually be `Cow::Borrowed(...)`

also unsure about how to handle this last case, i followed in footsteps of what was done before (just taking entire string), since alternative would be to panic which seems undesirable. also unsure if desirable to normalize it or not

File: datafusion/common/src/table_reference.rs [hunk 2]
```diff
@@ -155,50 +178,110 @@ impl<'a> TableReference<'a> {
...
     pub fn parse_str(s: &'a str) -> Self {
-        let parts: Vec<&str> = s.split('.').collect();
+        let mut parts = parse_identifiers(s)
+            .unwrap_or(vec![])
+            .into_iter()
+            .map(|id| match id.quote_style {
+                Some(_) => id.value,
+                // TODO: someway to be able to toggle this functionality?
+                None => id.value.to_ascii_lowercase(),
+            })
```
Comment (Jefffrey) [inline datafusion/common/src/table_reference.rs:208]: comparing with datafusion-sql package where some functionality is duplicated:

https://github.com/apache/arrow-datafusion/blob/ac876dbc9729b16e272e00496c51e53d9f649173/datafusion/sql/src/utils.rs#L540-L546

unsure if also should have a way to toggle normalization, as for datafusion-sql package it allows it:

https://github.com/apache/arrow-datafusion/blob/c323721192ba2733a56c4201b2255a36b1eaa859/datafusion/sql/src/planner.rs#L424-L430

but since this `parse_str` is meant to be used to implement `From<&str>`, there wouldn't really be a way to pass information on whether to toggle or not

File: datafusion/common/src/table_reference.rs [hunk 3]
```diff
@@ -155,50 +178,110 @@ impl<'a> TableReference<'a> {
...
             },
-            _ => Self::Bare { table: s },
+            // TODO: should normalize?
+            _ => Self::Bare { table: s.into() },
         }
     }
 }
 
-/// Parse a string into a TableReference, by splittig on `.`
+fn parse_identifiers(s: &str) -> Result<Vec<Ident>> {
```
Comment (Jefffrey) [inline datafusion/common/src/table_reference.rs:230]: could maybe upstream this whole function into sqlparser-rs instead?

**Comment by Jefffrey** [comment]
@alamb you mentioned possibility of removing `OwnedTableReference` https://github.com/apache/arrow-datafusion/issues/4532#issuecomment-1415727576

however even though using `Cow` now for `TableReference` so could own the string, it still carries lifetime requirements which would make it tedious to replace usages of `OwnedTableReference` with `TableReference` and having to ensure all the lifetime requirements, so will keep it around for now (unless theres some other solution)

**Comment by alamb** [comment]
I think CI is failing due to an issue fixed in https://github.com/apache/arrow-datafusion/pull/5177

**Comment by alamb** [comment]
> however even though using Cow now for TableReference so could own the string, it still carries lifetime requirements which would make it tedious to replace usages of OwnedTableReference with TableReference and having to ensure all the lifetime requirements, so will keep it around for now (unless theres some other solution)

I think that makes sense for this PR. Thanks @Jefffrey

File: datafusion/common/src/table_reference.rs (hunk 2 above)
Comment (alamb) [reply datafusion/common/src/table_reference.rs:208]: I agree -- if users want to normalize their identifiers I think they'll have to do it manually.

File: datafusion/common/src/table_reference.rs [hunk 4]
```diff
@@ -155,50 +178,110 @@ impl<'a> TableReference<'a> {
...
-    ///
-    /// If you need to handle such identifiers correctly, you should
-    /// use a SQL parser or form the [`OwnedTableReference`] directly.
+    /// Forms a [`TableReference`] by attempting to parse `s` as a multipart identifier,
+    /// failing that then taking the entire input as the identifier itself.
     ///
-    /// See more detail in <https://github.com/apache/arrow-datafusion/issues/4532>
+    /// Will normalize (convert to lowercase) any unquoted identifiers.
+    /// e.g. `Foo` will be parsed as `foo`, and `"Foo"".bar"` will be parsed as
+    /// `Foo".bar` (note the preserved case and requiring two double quotes to represent
```
Comment (alamb) [inline datafusion/common/src/table_reference.rs:198]:
```suggestion
    /// `Foo.bar` (note the preserved case and requiring two double quotes to represent
```

File: datafusion/common/src/table_reference.rs (hunk 1 above)
Comment (alamb) [reply datafusion/common/src/table_reference.rs:225]: I think documenting the behavior is about the best we can do in this case.

File: datafusion/common/src/table_reference.rs (hunk 3 above)
Comment (alamb) [reply datafusion/common/src/table_reference.rs:230]: That certainly seems like a good idea (at least to file a ticket to track)

**Review by alamb — APPROVED** [review]
Looks reasonable to me, thank you @Jefffrey

File: datafusion/common/src/table_reference.rs (hunk 4 above)
Comment (Jefffrey) [reply datafusion/common/src/table_reference.rs:198]: It needs to contain the single double quote since it was escaped by prepending it with another double quote in the original, unless you mean to change the example?

Comment (alamb) [reply datafusion/common/src/table_reference.rs:198]: No, I think I was confused. Sorry about that
