### PR TITLE
Fix SortExec discards field metadata on the output schema

### LINKED ISSUE #1476: SortExec discards field metadata on the output schema
**Describe the bug**

The following code in Sort skips the field level metadata when when it constructs the output batch.

```rust
    let schema = Arc::new(Schema::new(
        schema
            .fields()
            .iter()
            .zip(batch.columns().iter().map(|col| col.data_type()))
            .map(|(field, ty)| Field::new(field.name(), ty.clone(), field.is_nullable()))
            .collect::<Vec<_>>(),
    ));
```

It also seems to be unecessary (at least all the existing tests pass without it, so maybe @maxburke can comment on its), and so if any schema adjustment is needed it should have been done as part of the creation of Sort.

**To Reproduce**
Will add reproducer on ticket

**Expected behavior**
Metadata is preserverd

**Additional context**
Introduced in https://github.com/apache/arrow-datafusion/pull/1455

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Closes #1476 

 # Rationale for this change

This is a regression introduced in https://github.com/apache/arrow-datafusion/pull/1455

The following code in Sort skips the field level metadata when when it constructs the output batch.

```rust
    let schema = Arc::new(Schema::new(
        schema
            .fields()
            .iter()
            .zip(batch.columns().iter().map(|col| col.data_type()))
            .map(|(field, ty)| Field::new(field.name(), ty.clone(), field.is_nullable()))
            .collect::<Vec<_>>(),
    ));
```

Thus the output schema is not correct. 

It also seems to be unnecessary (at least all the tests pass without it, so maybe @maxburke  can comment on what problem it was solving). 

@hntd187 has also added some functions working with https://github.com/apache/arrow-rs/pull/1033 PR to add some additional functions for creating fields and I will work on this as well

# What changes are included in this PR?
1. Remove offending code
2. add a test

# Are there any user-facing changes?
Bug fix

### CODE REVIEW

File: datafusion/src/physical_plan/sort.rs [hunk 1]
```diff
@@ -201,15 +201,6 @@ fn sort_batch(
         None,
     )?;
 
-    let schema = Arc::new(Schema::new(
```
Comment (alamb) [inline datafusion/src/physical_plan/sort.rs:204]: the fix is to delete this code, the rest of the file is a test

**Comment by hntd187** [comment]
This is just to correct the bug correct? We will deal with carrying over metadata properly in another PR?

**Comment by alamb** [comment]
> This is just to correct the bug correct? We will deal with carrying over metadata properly in another PR?

Yes -- I think DataFusion does carry over metadata now in many cases and this PR corrects a case where the metadata used to be carried over but is no longer

**Review by houqp — APPROVED** [review]

**Review by Dandandan — APPROVED** [review]

File: datafusion/src/physical_plan/sort.rs (hunk 1 above)
Comment (Dandandan) [reply datafusion/src/physical_plan/sort.rs:204]: Nice and clean 🧹🧼

**Comment by maxburke** [comment]
@alamb If I recall the reason this change was made was because in our cases the schema was stripped of the timezone information but the underlying record batches preserved it.

**Comment by alamb** [comment]
> @alamb If I recall the reason this change was made was because in our cases the schema was stripped of the timezone information but the underlying record batches preserved it.

I am sorry if I broke something for you @maxburke  -- if you help me understand / write a reproducer for what want to do I am happy to help try and make it work
