### PR TITLE
Propagate error from spawned task reading spills

### LINKED ISSUE #7509: Errors cannot be propagated from spawned task reading spills
### Describe the bug

Any error happened in the spawned task reading spills cannot propagate out currently. So these errors will be ignored and it doesn't look correct as the sorted result will be incorrect.

### To Reproduce

For example, if file open limit is reduced to be less than the number of spills, when opening the spill file and getting an error, it won't cause any failure and the query will continue.

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #7509.

## Rationale for this change

Any error happened in the spawned task reading spills cannot propagate out currently. So these errors will be ignored and it doesn't look correct as the sorted result will be incorrect.

## What changes are included in this PR?

Propagating errors from spawned task reading spills.

### CODE REVIEW

File: datafusion/core/src/physical_plan/stream.rs [hunk 1]
```diff
@@ -169,7 +171,16 @@ impl RecordBatchReceiverStreamBuilder {
...
             while let Some(result) = join_set.join_next().await {
                 match result {
-                    Ok(()) => continue, // nothing to report
+                    Ok(task_result) => {
+                        match task_result {
+                            // nothing to report
+                            Ok(_) => continue,
+                            // This means a blocking task error
+                            Err(e) => {
+                                return Some(internal_err!("Spawned Task error: {e}"));
```
Comment (viirya) [inline datafusion/core/src/physical_plan/stream.rs:180]: For example, after this, if the file doesn't exist, you will get an error:

```
Error: Internal("Spawned Task error: Execution error: Spill file \"/var/folders/zq/2tdnn5955wvdcw7qfy6qhvk00000gn/T/.tmpb5EGzS/.tmptpkruZ\" does not exist")
```

File: datafusion/core/src/physical_plan/common.rs [hunk 2]
```diff
@@ -109,9 +109,13 @@ pub(crate) fn spawn_buffered(
             builder.spawn(async move {
                 while let Some(item) = input.next().await {
                     if sender.send(item).await.is_err() {
```
Comment (alamb) [inline datafusion/core/src/physical_plan/common.rs:111]: The only reason an item can't be sent via a channel I think is if the other end (the `Receiver`) was dropped. This can certainly happen if some other part of the query errors, but I also think it can happen with the plan shuts down early due to a `LIMIT` or something similar. 

Thus I am not sure we should propagate an error in this case

File: datafusion/core/src/physical_plan/stream.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/src/physical_plan/stream.rs:180]: `ExecutionError` might be more appropriate than `InternalError` given an error in a spill file is likely not a bug in DataFusion, but rather some issue in the environment.

**Review by alamb — COMMENTED** [review]
Thanks @viirya  -- this looks great. The only thing I am not quite sure about is erroring if a message can't be sent via channel.

File: datafusion/core/src/physical_plan/common.rs (hunk 2 above)
Comment (viirya) [reply datafusion/core/src/physical_plan/common.rs:111]: Makes sense. Removed the error.

**Review by alamb — APPROVED** [review]

**Comment by viirya** [comment]
Thank you @alamb
