### PR TITLE
Minor: fix: #9010 - Optimizer schema change assert error is incorrect

### LINKED ISSUE #9010: Optimizer schema change assert error has incorrect error
### Describe the bug

In datafusion/optimizer/src/optimizer.rs:271 when calling `assert_schema_is_the_same` prev_plan / new_plan are backwards. This causes an incorrect / confusing assert error, indicating the optimized plan is actually the original plan.

### To Reproduce

Any optimization error that produces a schema change will reproduce this bug.

In this particular case, the root cause of the schema change dropping timezone metadata for timestamps somewhere in  the Optimizer rule `simplify_expressions`. Fixing this bug will help find the root cause.

### Expected behavior

The `assert_schema_is_the_same` error should report prev_plan / new_plan in the correct order.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by curtisleefulton**
## Which issue does this PR close?

This is one-line fix: The assert_schema_is_the_same error will now report prev_plan / new_plan in the correct order.

Closes #9010.

## Rationale for this change

When debugging logical plan optimization change errors, it's important to know the correct values of prev_plan / new_plan so further investigation is can move quickly.

## Are there any user-facing changes?

No. This change will not affect the API.

No. This change will not affect the API.

### CODE REVIEW

File: datafusion/optimizer/src/optimizer.rs [hunk 1]
```diff
@@ -294,7 +294,7 @@ impl Optimizer {
                     self.optimize_recursively(rule, &new_plan, config)
                         .and_then(|plan| {
                             if let Some(plan) = &plan {
-                                assert_schema_is_the_same(rule.name(), &new_plan, plan)?;
+                                assert_schema_is_the_same(rule.name(), plan, &new_plan)?;
```
Comment (alamb) [inline datafusion/optimizer/src/optimizer.rs:297]: 👍  I double checked the order

https://github.com/apache/arrow-datafusion/blob/b3fe6aa68adb644d275d8914b3802c153b4a3a27/datafusion/optimizer/src/optimizer.rs#L427-L431

**Review by alamb — APPROVED** [review]
Thank you @curtisleefulton  -- nice find

**Comment by alamb** [comment]
Thanks @curtisleefulton ❤️
