### PR TITLE
fix: `generate_series` and `range` panic on edge cases

### LINKED ISSUE #9499: `generate_series` and `range` panic on edge cases
### Describe the bug

These functions will panic when the parameters are boundary values such as `i64::MIN` and `i64::MAX`.

### To Reproduce

```sh
DataFusion CLI v36.0.0
❯ select range(1, -1, -9223372036854775808);
thread 'main' panicked at datafusion/functions-array/src/kernels.rs:304:63:
attempt to negate with overflow
```

```sh
❯ select generate_series(9223372036854775807, 9223372036854775807);
thread 'main' panicked at datafusion/functions-array/src/kernels.rs:307:13:
attempt to add with overflow
```

### Expected behavior

Avoid panic.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #9499.

## Rationale for this change
Some arithmetic operations on `i64` may overflow, causing panic. For example
https://github.com/apache/arrow-datafusion/blob/fc81bf10ea7cde55c6d58a670e15bfd0581ec8c2/datafusion/functions-array/src/kernels.rs#L303
https://github.com/apache/arrow-datafusion/blob/fc81bf10ea7cde55c6d58a670e15bfd0581ec8c2/datafusion/functions-array/src/kernels.rs#L304
https://github.com/apache/arrow-datafusion/blob/fc81bf10ea7cde55c6d58a670e15bfd0581ec8c2/datafusion/functions-array/src/kernels.rs#L307

This PR tries to replace these arithmetic operations with `RangeInclusive` to avoid overflow.
## What changes are included in this PR?
fix panic

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/functions-array/src/kernels.rs [hunk 1]
```diff
@@ -306,9 +306,15 @@ pub(super) fn gen_range(args: &[ArrayRef], include_upper: bool) -> Result<ArrayR
             );
         }
         // Below, we utilize `usize` to represent steps.
-        // But on 32-bit targets, the absolute value of `i64` may fail to fit into `usize`.
+        #[cfg(target_pointer_width = "64")]
+        let step_abs = step.unsigned_abs() as usize;
+        // On 32-bit targets, the absolute value of `i64` may fail to fit into `usize`.
+        #[cfg(not(target_pointer_width = "64"))]
         let step_abs = usize::try_from(step.unsigned_abs()).map_err(|_| {
```
Comment (jayzhan211) [inline datafusion/functions-array/src/kernels.rs:313]: If `usize::try_from(step.unsigned_abs()).map_err` can handle whatever the target size is, I think we don't need to split the code for two condition

Comment (jayzhan211) [reply datafusion/functions-array/src/kernels.rs:313]: If we are running in 32 bit target machine, do we able to reach the code here and get step with i64? 🤔

Comment (jonahgao) [reply datafusion/functions-array/src/kernels.rs:313]: > If `usize::try_from(step.unsigned_abs()).map_err` can handle whatever the target size is, I think we don't need to split the code for two condition

Perhaps simpler is better. Let me merge them.

Comment (jonahgao) [reply datafusion/functions-array/src/kernels.rs:313]: > If we are running in 32-bit target machine, are we able to reach the code here and get the `step` with i64? 🤔

I think it's possible, because `step` comes from user input.

**Review by jayzhan211 — APPROVED** [review]
LGTM

**Comment by alamb** [comment]
Thank you @jonahgao and @jayzhan211
