### PR TITLE
Validate assignment target column existence for UPDATE statements

### LINKED ISSUE #5068: UPDATE statment for non existent column doesn't error out
**Describe the bug**
When the new `LogicalPlan::Dml` node for the `UPDATE` SQL statement is being generated during logical planning, the existence of the assignment target columns is never checked (unlike the existence of the assignment expression and selection expression columns).

**To Reproduce**
```bash
cd datafusion-cli
cargo run
...
```
```sql
❯ create table person (age int) as values (35);
0 rows in set. Query took 0.056 seconds.
❯ select * from person;
+-----+
| age |
+-----+
| 35  |
+-----+
1 row in set. Query took 0.017 seconds.
❯ update person set nonexistent = 36;
Internal("Unsupported logical plan: Dml")
❯ update person set age = 36 where nonexistent = true;
SchemaError(FieldNotFound { field: Column { relation: None, name: "nonexistent" }, valid_fields: [Column { relation: None, name: "age" }] })
❯ update person set age = (nonexistent + 1);
SchemaError(FieldNotFound { field: Column { relation: None, name: "nonexistent" }, valid_fields: [Column { relation: None, name: "age" }] })
```
The `Unsupported logical plan: Dml` comes from the physical planning phase. In other words the logical plane has been created successfully.

**Expected behavior**
Target column existence should be checked during logical planning and the `FieldNotFound` error should be thrown when the column is missing. Otherwise a typo will result in a valid logical plan, which when executed will not contain the changes the user intends/assumes.

**Additional context**
None

### PR DESCRIPTION
**Pull request by gruuya**
# Which issue does this PR close?

Closes #5068.

# Rationale for this change

Ensure that all assignment targets are actual columns of the target table, to prevent typos being silently swallowed up.

# What changes are included in this PR?

During logical planning of the `UPDATE` statement try to fetch each of the referenced assignment columns.

# Are these changes tested?

Yes, there is a new 3-case test now.

# Are there any user-facing changes?

Not really; Datafusion is read-only, so the only difference is what error is shown (`SchemaError(FieldNotFound` from the logical planning as opposed to `Internal("Unsupported logical plan: Dml")` from the physical planning phase). The real user-facing changes will be in the projects that use Datafusion as a framework and also [support writes](https://www.splitgraph.com/blog/seafowl-time-travel).

### CODE REVIEW

**Comment by gruuya** [comment]
@avantgardnerio on a related note, Seafowl will likely migrate to using the new `LogicalPlan::Dml` nodes internally pretty soon: https://github.com/splitgraph/seafowl/pull/281

File: datafusion/sql/src/statement.rs [hunk 1]
```diff
@@ -670,19 +670,20 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
+        let mut assign_map = assignments
             .iter()
             .map(|assign| {
                 let col_name: &Ident = assign
                     .id
                     .iter()
                     .last()
                     .ok_or(DataFusionError::Plan("Empty column id".to_string()))?;
+                // Validate that the assignment target column exists
+                table_schema.field_with_unqualified_name(&col_name.value)?;
```
Comment (avantgardnerio) [inline datafusion/sql/src/statement.rs:682]: The logic change looks good to me. I defer to @andygrove and @alamb on adding the `rstest` dependency. Personally I think it's worth it as it appears to reduce test boilerplate and I'm not too worried about `dev-dependencies`.

**Review by avantgardnerio — APPROVED** [review]

File: datafusion/sql/src/statement.rs (hunk 1 above)
Comment (alamb) [reply datafusion/sql/src/statement.rs:682]: `datafusion-core` already uses rstest https://github.com/apache/arrow-datafusion/blob/be4586858306ebbc47848243fe488dd4316e3f2f/datafusion/core/Cargo.toml#L117 so I don't view this as a new dependency

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @gruuya
