### PR TITLE
fix: `projection_push_down` don't consider VarProvider in columns.

### LINKED ISSUE #6237: `push_down_projection` optimization fails when using variables
### Describe the bug

Hello and thank you for writing+maintaining DataFusion!

When upgrading from DataFusion 18, we noticed an unexpected warning that started in #4465 by @jackwener (which shipped in DataFusion 20):

> WARN datafusion_optimizer::optimizer: Skipping optimizer rule 'push_down_projection' due to unexpected error: Error during planning: required columns can't push down

### To Reproduce

I've put together a minimal Rust repro here: https://github.com/rgwood/df-repro

In that repro, I use a [`VarProvider`](https://docs.rs/datafusion/latest/datafusion/variable/trait.VarProvider.html) to define an integer variable `@var`.

I then use that variable in the WHERE clause of a SQL query: `SELECT foo FROM csv_table WHERE bar > @var`

When evaluating the query, a warning indicates that `push_down_projection` was skipped:

> WARN datafusion_optimizer::optimizer: Skipping optimizer rule 'push_down_projection' due to unexpected error: Error during planning: required columns can't push down, columns: {Column { relation: Some(Bare { table: "csv_table" }), name: "bar" }, Column { relation: None, name: "@var" }, Column { relation: Some(Bare { table: "csv_table" }), name: "foo" }}

### Expected behavior

I expect the `push_down_projection` optimization to succeed without a warning.

### Additional context

I'm relatively new to DataFusion, but it seems like `push_down_projection` is incorrectly interpreting the variable `@var` as a column when it should not be.

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #6237.

# Rationale for this change

`projection_push_down` don't consider VarProvider in columns.

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/tests/dataframe.rs [hunk 1]
```diff
@@ -1230,3 +1232,36 @@ pub async fn register_alltypes_tiny_pages_parquet(ctx: &SessionContext) -> Resul
...
+        Ok(ScalarValue::Int64(Some(1234)))
+    }
+
+    fn get_type(&self, _: &[String]) -> Option<DataType> {
+        Some(DataType::Int64)
+    }
+}
+
+#[tokio::test]
+async fn use_var_provider() -> Result<()> {
```
Comment (jackwener) [inline datafusion/core/tests/dataframe.rs:1250]: I don't know how to set `skip_failed_rule = false` in dataframe

Comment (comphead) [reply datafusion/core/tests/dataframe.rs:1250]:
```
        let runtime = Arc::new(RuntimeEnv::default());
        let config = SessionConfig::new().with_target_partitions(4);
        let config = config.set_bool("datafusion.optimizer.skip_failed_rules", false);
        SessionState::with_config_rt(config, runtime)
        let ctx = SessionContext::with_config(config);
        let df = ctx.sql(sql) 

```
?

File: datafusion/optimizer/src/push_down_projection.rs [hunk 2]
```diff
@@ -466,7 +466,9 @@ fn get_expr(columns: &HashSet<Column>, schema: &DFSchemaRef) -> Result<Vec<Expr>
             }
         })
         .collect::<Vec<Expr>>();
-    if columns.len() != expr.len() {
+    // Because columns may contain VarProvider, so the length of expr may be less than columns
```
Comment (alamb) [inline datafusion/optimizer/src/push_down_projection.rs:469]: I wonder if there is some way to strip out the columns earlier (like for example, perhaps we could skip pulling out `ScalarVariable` here)

https://github.com/apache/arrow-datafusion/blob/cf233c855f46fad8355342c581ab55f610758b6c/datafusion/expr/src/utils.rs#L273-L275

I tried this locally:

```diff
diff --git a/datafusion/expr/src/utils.rs b/datafusion/expr/src/utils.rs
index 7babd659e..00e1d0769 100644
--- a/datafusion/expr/src/utils.rs
+++ b/datafusion/expr/src/utils.rs
@@ -270,13 +270,11 @@ pub fn expr_to_columns(expr: &Expr, accum: &mut HashSet<Column>) -> Result<()> {
             Expr::Column(qc) => {
                 accum.insert(qc.clone());
             }
-            Expr::ScalarVariable(_, var_names) => {
-                accum.insert(Column::from_name(var_names.join(".")));
-            }
             // Use explicit pattern match instead of a default
             // implementation, so that in the future if someone adds
             // new Expr types, they will check here as well
-            Expr::Alias(_, _)
+            Expr::ScalarVariable(_, _)
+            | Expr::Alias(_, _)
             | Expr::Literal(_)
             | Expr::BinaryExpr { .. }
             | Expr::Like { .. }

```

and it seems promising

File: datafusion/core/tests/dataframe.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/tests/dataframe.rs:1250]: Here is the version I got working:

```rust
#[derive(Debug)]
struct HardcodedIntProvider {}

impl VarProvider for HardcodedIntProvider {
    fn get_value(&self, _var_names: Vec<String>) -> Result<ScalarValue, DataFusionError> {
        Ok(ScalarValue::Int64(Some(1234)))
    }

    fn get_type(&self, _: &[String]) -> Option<DataType> {
        Some(DataType::Int64)
    }
}

#[tokio::test]
async fn use_var_provider() -> Result<()> {
    let schema = Arc::new(Schema::new(vec![
        Field::new("foo", DataType::Int64, false),
        Field::new("bar", DataType::Int64, false),
    ]));

    let mem_table = Arc::new(MemTable::try_new(schema, vec![])?);

    let config = SessionConfig::new()
        .with_target_partitions(4)
        .set_bool("datafusion.optimizer.skip_failed_rules", false);

    let ctx = SessionContext::with_config(config);

    ctx.register_table("csv_table", mem_table)?;
    ctx.register_variable(VarType::UserDefined, Arc::new(HardcodedIntProvider {}));

    let dataframe = ctx
        .sql("SELECT foo FROM csv_table WHERE bar > @var")
        .await?;
    dataframe.collect().await?;
    Ok(())
}
```

**Review by alamb — COMMENTED** [review]
Thanks @jackwener  --- it is great to be so responsive

**Comment by jackwener** [comment]
Thanks @comphead @alamb
