### PR TITLE
Make sure that the data types are supported in hashjoin before genera…

### LINKED ISSUE #2145: Join on path partitioned columns fails with error
**Describe the bug**
Dictionary types aren't supported by the hasher. Attempting to join on two partitioned columns panics with:
```
thread 'parquet_join_on_partition_columns' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Unsupported data type in hasher")', datafusion/src/physical_plan/hash_join.rs:628:6
```
This isn't an issue when joining partition column with another string column, I assume due to type coercion rules casting partition column to Utf8.

**To Reproduce**
I did this in using the path_partition tests using slightly modified version of register_partitioned_alltypes_parquet that allows setting the name of the registered table.
```
async fn parquet_join_on_partition_columns()->Result<()>{
    let mut ctx = ExecutionContext::new();

    register_partitioned_alltypes_parquet_with_name(
        &mut ctx,
        &[
            "year=2021/month=09/day=09/file.parquet",
            "year=2021/month=10/day=09/file.parquet",
            "year=2021/month=10/day=28/file.parquet",
        ],
        &["year", "month", "day"],
        "",
        "alltypes_plain.parquet",
        "left"
    )
    .await;
 

    register_partitioned_alltypes_parquet_with_name(
        &mut ctx,
        &[
            "year=2021/month=09/day=09/file.parquet",
            "year=2021/month=10/day=09/file.parquet",
            "year=2021/month=10/day=28/file.parquet",
        ],
        &["year", "month", "day"],
        "",
        "alltypes_plain.parquet",
        "right"
    )
    .await;

    let _results = ctx.sql("SELECT left.id as lid, right.id as rid from left inner join right on left.month = right.month")
        .await?
        .collect()
        .await?;

    Ok(())
}
```

**Expected behavior**
Query should return results without error.

I'm not sure how this should be solved. It would be pretty straightforward to add casts into either the planner or the join implementation into a string array but this would cause an increase in memory usage. Another option would be to add implementations to the hasher, but this will add a large number of additional branches if other partition column types are eventually supported. I know that a row based join format for joins was being implemented but I think that the same issue with regards to having to cast from dictionary -> concrete type will cause an increase in memory usage with the row based version as well.  This would be solvable there with a hashmap that is external to the row which globally manages a integer -> T map and encodes the value of the partitioned column as a integer in the row.

### PR DESCRIPTION
**Pull request by AssHero**
# Which issue does this PR close?

Closes #2145 

 # Rationale for this change
Before generating the hash join logical plan, make sure the data types in equal conditions are supported. Otherwise, try 
cross join instead.

# What changes are included in this PR?
1. add can_hash func in datafusion/expr/src/utils.rs 
2. use can_hash in datafusion/expr/src/logical_plan/builder.rs and datafusion/sql/src/planner.rs to check if the data type is supported in hashjoin or not

### CODE REVIEW

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -605,17 +606,52 @@ impl LogicalPlanBuilder {
...
+                && right.schema().field_from_column(l).is_ok()
+                && can_hash(self.plan.schema().field_from_column(r).unwrap().data_type())
+            {
+                join_on.push((r.clone(), l.clone()));
+            } else {
+                let expr = Expr::BinaryExpr {
+                    left: Box::new(Expr::Column(l.clone())),
+                    op: Operator::Eq,
+                    right: Box::new(Expr::Column(r.clone())),
+                };
```
Comment (andygrove) [inline datafusion/expr/src/logical_plan/builder.rs:627]: nit: we can use `binary_expr` helper here for more concise code

```
                let expr = binary_expr(
                    Expr::Column(l.clone()),
                    Operator::Eq,
                    Expr::Column(r.clone()),
                );
```

Comment (andygrove) [inline datafusion/expr/src/logical_plan/builder.rs:627]:
```suggestion
                let expr = binary_expr(
                    Expr::Column(l.clone()),
                    Operator::Eq,
                    Expr::Column(r.clone()),
                );

```

File: datafusion/expr/src/logical_plan/builder.rs [hunk 2]
```diff
@@ -605,17 +606,52 @@ impl LogicalPlanBuilder {
...
+                match filters {
+                    None => filters = Some(expr),
+                    Some(filter_expr) => {
+                        filters = Some(Expr::BinaryExpr {
+                            left: Box::new(expr),
+                            op: Operator::And,
+                            right: Box::new(filter_expr),
+                        });
+                    }
```
[the remark this answers is not in the document]
Comment (AssHero) [reply datafusion/expr/src/logical_plan/builder.rs:636]: Thank you! I'll fix this.

File: datafusion/expr/src/logical_plan/builder.rs (hunk 1 above)
Comment (AssHero) [reply datafusion/expr/src/logical_plan/builder.rs:627]: Thank you! I'll fix this.

File: datafusion/expr/src/logical_plan/builder.rs [hunk 3]
```diff
@@ -19,6 +19,7 @@
 
 use crate::expr_rewriter::{normalize_col, normalize_cols, rewrite_sort_cols_by_aggs};
 use crate::utils::{columnize_expr, exprlist_to_fields, from_plan};
+use crate::Operator;
```
[the remark this answers is not in the document]
Comment (AssHero) [reply datafusion/expr/src/logical_plan/builder.rs:22]: Thank you! I'll fix this.

File: datafusion/expr/src/utils.rs [hunk 4]
```diff
@@ -643,6 +644,35 @@ pub fn expr_as_column_expr(expr: &Expr, plan: &LogicalPlan) -> Result<Expr> {
     }
 }
 
+/// can this data type be used in hash join equal conditions??
+/// If more data types are supported in hash join, add those data types here
+/// to generate join logical plan.
+pub fn can_hash(data_type: &DataType) -> bool {
+    match data_type {
```
Comment (liukun4515) [inline datafusion/expr/src/utils.rs:651]: decimal should be supported here

Comment (AssHero) [reply datafusion/expr/src/utils.rs:651]: Data types here come from function equal_rows, decimal is not supported in equal_rows.

File: datafusion/core/tests/sql/joins.rs [hunk 5]
```diff
@@ -1204,3 +1204,141 @@ async fn join_partitioned() -> Result<()> {
...
+            Arc::new(Int64Array::from_slice(&[100, 200, 300])),
+            Arc::new(Date32Array::from(vec![Some(1), Some(2), Some(3)])),
+        ],
+    )?;
+    let table = MemTable::try_new(data.schema(), vec![vec![data]])?;
+    ctx.register_table("foo", Arc::new(table))?;
+
+    // join on hash unsupported data type (Date32), use cross join instead hash join
+    let sql = "select * from foo t1 join foo t2 on t1.c4 = t2.c4";
+    let msg = format!("Creating logical plan for '{}'", sql);
```
Comment (alamb) [inline datafusion/core/tests/sql/joins.rs:1232]: So I think CrossJoin is almost never what the user would want: as once the tables get beyond any trivial size the query will effectively never finish or will run out of memory. An error is clearer.


From the issue description https://github.com/apache/arrow-datafusion/issues/2145#issue-1191065060 I think @pjmore's idea to cast unsupported types to a supported type is a good one -- the arrow `cast` kernels are quite efficient for things like `Date32` -> `Int32` (no copies) as the representations are the same

@pjmore  what do you think?

**Review by alamb — APPROVED** [review]
Thank you @AssHero 

I believe this PR does what the description says -- and it adds nice test coverage so I am approving it.

However, I am concerned that trying to run a query using a `CrossJoin` is likely to be catastrophically bad so this approach will not work for anything except very small inputs.

File: datafusion/core/tests/sql/joins.rs (hunk 5 above)
Comment (AssHero) [reply datafusion/core/tests/sql/joins.rs:1232]: > So I think CrossJoin is almost never what the user would want: as once the tables get beyond any trivial size the query will effectively never finish or will run out of memory. An error is clearer.
> 
> From the issue description [#2145 (comment)](https://github.com/apache/arrow-datafusion/issues/2145#issue-1191065060) I think @pjmore's idea to cast unsupported types to a supported type is a good one -- the arrow `cast` kernels are quite efficient for things like `Date32` -> `Int32` (no copies) as the representations are the same
> 
> @pjmore what do you think?

this pr is only to make the hash unsupported join running in cross join instead of error/panic(I think it is not friendly in database system). 
supporting more data types in hash join is the better way to solve this issue, and i'm already working on it.

File: datafusion/expr/src/utils.rs (hunk 4 above)
Comment (AssHero) [reply datafusion/expr/src/utils.rs:651]: > I think it may help to add a comment here (or in `equal_rows`) mentioning they need to remain in sync

I'll add this comment.

**Comment by alamb** [comment]
Thank you again @AssHero
