### PR TITLE
Simplify MemoryManager

### LINKED ISSUE #2829: Memory manager triggers unnecessary spills
**Describe the bug**

currently, each requester can allocate at most `(pool_size - tracker_total) / num_requesters` memory. if an execution plan is skewed there will be a lot of memory wasted and unexpected spills.

for example, when we perform sort -> merge joining on two inputs, and one of them is very small:
```
SortMergeJoin {
    left: Sort { // bigger input
    },
    right: Sort { // smaller input
    },
    ...
}
```

the bigger sorter can use only half of the total memory, which will trigger more spills and slow down the performance.
 
**To Reproduce**

in the following case, we have 3 requesters requesting 90 of 100 memory. as the memory is not used up, there would be no spills during the execution. but the big requester actually spills every time.
```
    #[tokio::test]
    async fn multiple_skewed_requesters() {
        let config = RuntimeConfig::new()
            .with_memory_manager(MemoryManagerConfig::try_new_limit(100, 1.0).unwrap());
        let runtime = Arc::new(RuntimeEnv::new(config).unwrap());

        let big_requester1 = DummyRequester::new(0, runtime.clone());
        runtime.register_requester(&big_requester1.id);
        let small_requester2 = DummyRequester::new(0, runtime.clone());
        runtime.register_requester(&small_requester2.id);
        let small_requester3 = DummyRequester::new(0, runtime.clone());
        runtime.register_requester(&small_requester3.id);

        small_requester2.do_with_mem(5).await.unwrap();
        small_requester3.do_with_mem(5).await.unwrap();

        big_requester1.do_with_mem(40).await.unwrap();
        big_requester1.do_with_mem(40).await.unwrap();
        assert_eq!(big_requester1.get_spills(), 0); // assertion fails, actually = 2
    }
```
**Expected behavior**

spill only when all memory is used up. the spill strategy can be optimized, for example we can find out the maximum requester and let it spill.

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2829.

# Rationale for this change

The existing memory manager interface is quite tricky to use, and has resulted in the proliferation of "utility" wrappers to make it easier to work with. It also mixes the concept of limiting memory, with "memory scheduling" where it tries to distribute memory "fairly". In practice I'm not sure this would have worked, and would likely have blocked tokio worker threads #4325.

This PR proposes a drastic simplification of MemoryManager

# What changes are included in this PR?

There are a couple of major changes worth highlighting:

* MemoryManager will no longer block waiting for capacity
* MemoryManager "fairness" can be configured based on the provided `MemoryPool`
* ExternalSorter will refuse to sort batches that are larger than it can allocate from the memory pool

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/tests/memory_limit.rs [hunk 1]
```diff
@@ -66,23 +68,21 @@ async fn group_by_hash() {
...
 const MEMORY_FRACTION: f64 = 0.95;
 
 /// runs the specified query against 1000 rows with a 50
 /// byte memory limit and no disk manager enabled.
-async fn run_limit_test(query: &str, expected_error: &str) {
-    let generator = AccessLogGenerator::new().with_row_limit(Some(1000));
-
-    let batches: Vec<RecordBatch> = generator
-        // split up into more than one batch, as the size limit in sort is not enforced until the second batch
-        .flat_map(stagger_batch)
```
Comment (tustvold) [inline datafusion/core/tests/memory_limit.rs:85]: This change is necessary because a sliced batch reports the size of the underlying buffers, and so the accounting is messed up

File: datafusion/core/tests/order_spill_fuzz.rs [hunk 2]
```diff
@@ -110,12 +107,23 @@ async fn run_sort(pool_size: usize, size_spill: Vec<(usize, bool)>) {
...
     let mut rng = rand::thread_rng();
-    let mut input: Vec<i32> = vec![0; len];
-    rng.fill(&mut input[..]);
-    let input = Int32Array::from_iter_values(input.into_iter());
-
-    // split into several record batches
-    let batch =
-        RecordBatch::try_from_iter(vec![("x", Arc::new(input) as ArrayRef)]).unwrap();
-    stagger_batch_with_seed(batch, 42)
+    let max_batch = 1024;
```
Comment (tustvold) [inline datafusion/core/tests/order_spill_fuzz.rs:110]: Again, slicing batches causes the memory limiter to fail as it doesn't consider array slicing

File: test-utils/src/data_gen.rs [hunk 3]
```diff
@@ -91,6 +98,10 @@ impl BatchBuilder {
 
                 let num_entries = rng.gen_range(1024..8192);
                 for i in 0..num_entries {
+                    if self.is_finished() {
```
Comment (tustvold) [inline test-utils/src/data_gen.rs:101]: Early return to make tests run faster

File: datafusion/core/src/physical_plan/sorts/sort.rs [hunk 4]
```diff
@@ -73,17 +70,18 @@ use tokio::task;
 ///     buffer the batch in memory, go to 1.
 /// 3. when input is exhausted, merge all in memory batches and spills to get a total order.
 struct ExternalSorter {
-    id: MemoryConsumerId,
     schema: SchemaRef,
-    in_mem_batches: Mutex<Vec<BatchWithSortArray>>,
```
Comment (tustvold) [inline datafusion/core/src/physical_plan/sorts/sort.rs:78]: This Mutex aren't actually needed, took the opportunity to just remove them

File: datafusion/core/src/physical_plan/metrics/tracker.rs [hunk 5]
```diff
@@ -118,14 +103,3 @@ impl MemTrackingMetrics {
         self.metrics.record_poll(poll)
     }
 }
-
-impl Drop for MemTrackingMetrics {
-    fn drop(&mut self) {
-        self.metrics.try_done();
```
Comment (tustvold) [inline datafusion/core/src/physical_plan/metrics/tracker.rs:124]: This is redundant as the Drop of `BaselineMetrics` already calls this

File: datafusion/core/src/physical_plan/metrics/tracker.rs [hunk 6]
```diff
@@ -118,14 +103,3 @@ impl MemTrackingMetrics {
...
-        if self.mem_used() != 0 {
```
Comment (tustvold) [inline datafusion/core/src/physical_plan/metrics/tracker.rs:125]: This is no longer needed as TrackedAllocation does it automatically

**Comment by alamb** [comment]
cc @yjshen  and @richox  (Blaze-rs team) who I think contributed some/all of the original implementation; Also cc @milenkovicm who I think has expressed some interest in memory management before

File: datafusion/core/src/execution/memory_manager/mod.rs [hunk 7]
```diff
@@ -97,339 +89,154 @@ impl MemoryManagerConfig {
...
-   │               Requesting                     z          Tracking           │
-   │            Memory Consumers                  z       Memory Consumers      │
-   │                                              z                             │
-   │                                              z                             │
-   └──────────────────────────────────────────────z─────────────────────────────┘
-*/
-
-/// Manage memory usage during physical plan execution
+/// The memory manager maintains a fixed size pool of memory
+/// from which portions can be allocated
```
Comment (alamb) [inline datafusion/core/src/execution/memory_manager/mod.rs:95]: I think it would be good to expand these comments to explain the allocation strategy of the manager

```suggestion
/// from which portions can be allocated
///
/// A cooperative MemoryManager which tracks memory in a cooperative fashion. 
/// `ExectionPlan` nodes such as `SortExec`, which require large amounts of memory register their
/// memory requests with the MemoryManager which then tracks the total memory that 
/// has been allocated across all such nodes. 
///
/// The MemoryManager does not guarantee any form of "fairness" -- the operators that ask for 
/// memory first are the ones that are given memory. 
///
/// Note that more sophisticated memory polices can be created at a higher level
///  by dividing available system memory across multiple `MemoryManagers`  and assigning 
/// different MemoryManagers to diffrent pools. 
```

File: datafusion/core/src/execution/memory_manager/mod.rs [hunk 8]
```diff
@@ -97,339 +89,154 @@ impl MemoryManagerConfig {
...
+    /// Note: this can exceed the pool size as a result of [`MemoryManager::allocate`]
+    pub fn allocated(&self) -> usize {
+        self.state.used.load(Ordering::Relaxed)
     }
 
-    /// Register a new memory requester
-    pub(crate) fn register_requester(&self, requester_id: &MemoryConsumerId) {
-        self.requesters.lock().insert(requester_id.clone());
+    /// Returns a new empty allocation identified by `name`
+    pub fn new_tracked_allocation(&self, name: String) -> TrackedAllocation {
```
Comment (alamb) [inline datafusion/core/src/execution/memory_manager/mod.rs:141]: I think it is worth leaving some sort of `requester_id` as part of this API so that it is possible to extend in the future so that the first spilling operator doesn't end up with all the memory, for example.

File: datafusion/core/src/execution/memory_manager/mod.rs [hunk 9]
```diff
@@ -97,339 +89,154 @@ impl MemoryManagerConfig {
...
-                let mut total = self.requesters_total.lock();
-                assert!(*total >= mem_used);
-                *total -= mem_used;
-                self.cv.notify_all();
-                return;
-            }
-        }
-        self.shrink_tracker_usage(mem_used);
-        self.cv.notify_all();
+    /// Try to increase the size of this [`TrackedAllocation`] by `capacity` bytes
```
Comment (alamb) [inline datafusion/core/src/execution/memory_manager/mod.rs:222]:
```suggestion
    /// Try to increase the size of this [`TrackedAllocation`] by `capacity` bytes,
    /// returning an ResourcesExhausted error if such an allocation would exceed
    /// the configured pool size
```

File: datafusion/core/src/execution/memory_manager/mod.rs [hunk 10]
```diff
@@ -97,339 +89,154 @@ impl MemoryManagerConfig {
...
+    pub fn try_grow(&mut self, capacity: usize) -> Result<()> {
+        let pool_size = self.state.pool_size;
+        self.state
+            .used
+            .fetch_update(Ordering::SeqCst, Ordering::SeqCst, |used| {
```
Comment (alamb) [inline datafusion/core/src/execution/memory_manager/mod.rs:227]: ❤️

File: datafusion/core/src/execution/memory_manager/mod.rs [hunk 11]
```diff
@@ -97,339 +89,154 @@ impl MemoryManagerConfig {
...
+                let new_used = used + capacity;
+                (new_used <= pool_size).then_some(new_used)
+            })
+            .map_err(|used| DataFusionError::ResourcesExhausted(format!("Failed to allocate additional {} bytes for {} with {} bytes already allocated - maximum available is {}", capacity, self.name, self.size, used)))?;
```
Comment (alamb) [inline datafusion/core/src/execution/memory_manager/mod.rs:231]: I think the order of the parameters is incorrect but I may be misreading it

```suggestion
            .map_err(|used| DataFusionError::ResourcesExhausted(format!("Failed to allocate additional {} bytes for {} with {} bytes already allocated - maximum available is {}", capacity, self.name, used, self.size)))?;
```

File: datafusion/core/tests/memory_limit.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/tests/memory_limit.rs:85]: I originally put in `stagger_batch` as sort didn't check memory limits on the first batch. -- this change makes sense to me.

File: datafusion/core/tests/order_spill_fuzz.rs (hunk 2 above)
Comment (alamb) [reply datafusion/core/tests/order_spill_fuzz.rs:110]: I believe stagger batches also adds zero length record batches, which was an important edge case to cover as I recall

**Review by alamb — COMMENTED** [review]
Thank you @tustvold  -- I agree I found the existing manager allocation algorithm a bit of a mismatch for DataFusion's needs and this rework matches it better. I would very much like to hear @yjshen's opinion of this change prior to merging. 

I think the major downside to this new allocation approach is that that some operators that don't benefit from more memory after a point (e.g. Sort) because they will spill anyways will now consume all of the available memory in the plan at the expense of upstream operators. This may cause a plan with multiple such operators to fail (as the downstream operator will not be able to allocate any memory as it has all been given to the upstream operator). I think there are different ways around this problem, such as adjust the spilling operator strategy so that once it spills it can give back some of the memory it requested, etc. 

This situation doesn't really affect the "error if memory budget is exceeded" usecase I do think it affects what happens when operators begin to spill. 

If we can't reach consensus on the particular strategy, perhaps we can follow the traditional DataFusion approach and provide an extension point -- namely make `MemoryManager` a trait and provide a basic implementation that can be customized by other systems if need be. 


I wonder if this closes either  https://github.com/apache/arrow-datafusion/issues/4328 or https://github.com/apache/arrow-datafusion/issues/4325

Also possible related is @richox 's report that the memory manager divvys up memory like https://github.com/apache/arrow-datafusion/issues/2829 which may or may not be relevant after this PR

File: datafusion/core/src/execution/memory_manager/mod.rs (hunk 8 above)
Comment (tustvold) [reply datafusion/core/src/execution/memory_manager/mod.rs:141]: I think I would rather punt on this until we have such a system in place, I am skeptical that such a system would make use of IDs a not just an Arc

**Comment by alamb** [comment]
In the interests of moving this PR along, I have posted to the mailing list https://lists.apache.org/thread/plrq40ldy4y9l6bj3157bk54dc029b3w and slack trying to solicit comments

**Comment by alamb** [comment]
I propose if we don't get any comments in another 2 days, we merge this PR as is. We can address any comments / other features as follow ons. 

Please comment here if you need additional time to review or have other commentary

**Review by yjshen — COMMENTED** [review]
Thanks @tustvold working on this new version of the memory manager!

Yes, you are correct that the current manager contains both memory usage accounting and memory scheduling (fairness schedule as its current state). And its complexity comes with two folds:
1. how to grant memory to a set of memory consumers fairly(consumer id for identifying different consumers)
2. how to differentiate consumers requiring more memory during execution (evenly divide available memory of them all) between the ones that take an in-neglectable amount of memory which would return later.

And yes, fair scheduling is only for the simplicity of implementation, to avoid starvation of parallel executed partitions or pipelines and lots of spaces or strategies for more sophisticated scheduling.

Currently, the existing memory manager works well in the Blaze workload which we use DataFusion to run several Spark tasks in parallel inside each Spark Executor. And memory manager controls both Sort and Shuffle. No #4325 is witnessed. Perhaps @richox could correct me or provide more details on developing Blaze and operating it in Kuaishou in production since I left in May.

I would suggest we start the design of memory scheduling and pooling mechanisms and think about how these interact with the new manager and yield a complete plan for the new memory management. I am concerned that after we consider scheduling, we'll have to add code with similar functionality.

I'm also fine with merging the PR as it is if scheduling or pooling is planned and would work shortly. A short time of functionality regression @alamb pointed out doesn't hurt much.

**Comment by tustvold** [comment]
I'll add a policy component to this prior to merge in that case

**Comment by alamb** [comment]
Marking as a draft until the policy is added, so this PR is removed from my review queue

**Comment by tustvold** [comment]
I've added a `MemoryPool` abstraction allowing customisation of the allocation strategy PTAL

File: datafusion/core/src/execution/runtime_env.rs [hunk 12]
```diff
@@ -142,8 +126,10 @@ impl Default for RuntimeEnv {
 pub struct RuntimeConfig {
```
Comment (tustvold) [inline datafusion/core/src/execution/runtime_env.rs:126]: Not directly related to this PR, but the proliferation of `*Config` structs is a pet peeve of mine that I am working to fix under #4617 and #4349

File: datafusion/core/src/execution/memory_manager/mod.rs [hunk 13]
```diff
@@ -17,419 +17,187 @@
...
-use std::time::{Duration, Instant};
 
+mod pool;
 pub mod proxy;
 
-static CONSUMER_ID: AtomicUsize = AtomicUsize::new(0);
-
-#[derive(Debug, Clone)]
-/// Configuration information for memory management
-pub enum MemoryManagerConfig {
```
Comment (tustvold) [inline datafusion/core/src/execution/memory_manager/mod.rs:37]: This was a bit of a perverse API imo, I'm looking into properly addressing the `*Config` profileration in #4349 but I figured I might as well clean this up whilst I was here.

If people want to reuse the same pool, they can just use the same `Arc<dyn MemoryPool>`

File: datafusion/core/src/execution/memory_manager/mod.rs [hunk 14]
```diff
@@ -17,419 +17,187 @@
...
-    /// Ptr to MemoryManager
-    fn memory_manager(&self) -> Arc<MemoryManager>;
-
-    /// Partition that the consumer belongs to
-    fn partition_id(&self) -> usize {
-        self.id().partition_id
-    }
+/// Options associated with a [`TrackedAllocation`]
+#[derive(Debug)]
+pub struct AllocationOptions {
```
Comment (tustvold) [inline datafusion/core/src/execution/memory_manager/mod.rs:94]: This is designed to be an extension point, so we can potentially add more allocation options and correspondingly more sophisticated MemoryPool.

File: datafusion/core/src/execution/memory_manager/pool.rs [hunk 15]
```diff
@@ -0,0 +1,282 @@
...
+///    ┌───────────────────────z──────────────────────z───────────────┐
+///    │                       z                      z               │
+///    │                       z                      z               │
+///    │       Spillable       z       Unspillable    z     Free      │
+///    │        Memory         z        Memory        z    Memory     │
+///    │                       z                      z               │
+///    │                       z                      z               │
+///    └───────────────────────z──────────────────────z───────────────┘
+///
+/// Unspillable memory is allocated in a first-come, first-serve fashion
```
Comment (tustvold) [inline datafusion/core/src/execution/memory_manager/pool.rs:105]: This is equivalent to the old behaviour

File: datafusion/core/src/execution/memory_manager/mod.rs [hunk 16]
```diff
@@ -17,419 +17,187 @@
...
-    CONSUMER_ID.fetch_add(1, Ordering::SeqCst)
+/// A cooperative MemoryManager which tracks memory in a cooperative fashion.
+/// `ExecutionPlan` nodes such as `SortExec`, which require large amounts of memory
+/// register their memory requests with the MemoryManager which then tracks the total
+///  memory that has been allocated across all such nodes.
+///
+/// The associated [`MemoryPool`] determines how to respond to memory allocation
+/// requests, and any associated fairness control
+#[derive(Debug)]
+pub struct MemoryManager {
```
Comment (tustvold) [inline datafusion/core/src/execution/memory_manager/mod.rs:61]: I wonder if we even still need the `MemoryManager` :thinking:

File: datafusion/core/src/execution/context.rs [hunk 17]
```diff
@@ -2051,20 +2058,23 @@ mod tests {
...
 
-        assert!(std::ptr::eq(
-            Arc::as_ptr(&memory_manager),
-            Arc::as_ptr(&ctx1.runtime_env().memory_manager)
-        ));
-        assert!(std::ptr::eq(
-            Arc::as_ptr(&memory_manager),
-            Arc::as_ptr(&ctx2.runtime_env().memory_manager)
-        ));
+        assert_eq!(ctx1.runtime_env().memory_pool.allocated(), 100);
```
Comment (tustvold) [inline datafusion/core/src/execution/context.rs:2071]: This test had to be rewitten as pointer equality of fat pointers such as `&dyn` is funky

File: datafusion/core/src/execution/memory_manager/pool.rs [hunk 18]
```diff
@@ -0,0 +1,282 @@
...
+
+use crate::execution::memory_manager::{AllocationOptions, MemoryPool};
+use crate::execution::TrackedAllocation;
+use datafusion_common::{DataFusionError, Result};
+use parking_lot::Mutex;
+use std::sync::atomic::{AtomicUsize, Ordering};
+
+/// A [`MemoryPool`] that enforces no limit
+#[derive(Debug, Default)]
+pub struct UnboundedMemoryPool {
```
Comment (alamb) [inline datafusion/core/src/execution/memory_manager/pool.rs]: This is very nice

File: datafusion/core/src/execution/memory_pool/pool.rs [hunk 19]
```diff
@@ -0,0 +1,280 @@
...
+                num_spill: 0,
+                spillable: 0,
+                unspillable: 0,
+            }),
+        }
+    }
+}
+
+impl MemoryPool for FairSpillPool {
+    fn allocate(&self, options: &AllocationOptions) {
```
Comment (alamb) [inline datafusion/core/src/execution/memory_pool/pool.rs:140]: I spent some time convincing myself this would work correctly if there are multiple SortExecs in the plan such that one would completely run before the other (e.g. as happens when there are multiple window functions with different partition / order by clauses)

I believe it will be fine because each `ExternalSorter` creates the potentially spilling allocation allocation upon construction, though I am still not 100% sure.

What would you think about moving the construction of `TrackedAllocation` into `MemoryPool`, something like 

```rust
/// Create a new tracked allocation with the MemoryManager. Subsequent requests
/// can grow or shrink the memory allocated to this allocation.
///
/// The allocation is automatically deregistered on drop
fn register(self: &Arc<Self>, options: AllocationOptions) -> TrackedAllocation;
```

That way the intent would be clearer that all ExternalSort instances register themselves with the MemoryManager on creation, and part of registering would increase the `num_spill` count.

I think having the MemoryPool create TrackedAllocations makes more logical sense as they are so tightly bound and you need a MemoryPool for a tracked allocation anyways

**Review by alamb — APPROVED** [review]
Thank you @tustvold -- I really like where this is going. I had a suggestion about the API design (`MemoryPool::register()`) rather than creating TrackedAllocations directly. 

I also think we could merge this PR as is if you don't want to make any more changes -- I could try to update the API as part of a follow on PR.

**Comment by tustvold** [comment]
> I had a suggestion about the API design (MemoryPool::register()) rather than creating TrackedAllocations directly.

> I think having the MemoryPool create TrackedAllocations makes more logical sense as they are so tightly bound and you need a MemoryPool for a tracked allocation anyways

I originally had this prior to https://github.com/apache/arrow-datafusion/pull/4522/commits/718a94b72a0b65486d26ceb482e9b3393ee3dd5e, however, it results in passing round this `MemoryManager` struct that has no state of its own which seemed a bit pointless. In order for MemoryPool to be able to construct a `TrackedAllocation` the construction methods on `TrackedAllocation` need to be public regardless, so that they can be used downstream, it seemed simpler just to not bother?

File: datafusion/core/src/execution/memory_pool/pool.rs (hunk 19 above)
Comment (tustvold) [reply datafusion/core/src/execution/memory_pool/pool.rs:140]: > I believe it will be fine because each ExternalSorter creates the potentially spilling allocation allocation upon construction, though I am still not 100% sure.

Now that ExecutionPlan is sync I don't think this is an issue, the streams are all created prior to execution starting. Yes theoretically 

> That way the intent would be clearer that all ExternalSort instances register themselves with the MemoryManager on creation, and part of registering would increase the num_spill count.

Perhaps I'm being stupid but I don't see a tangible difference between `TrackedAllocation::new(pool, options)` and `pool.register(options)`, you're just reordering the parameters? More specifically in order for `register` to be implemented, you still need a public `TrackedAllocation::new` so you're just adding an indirection?

File: datafusion/core/src/execution/runtime_env.rs [hunk 20]
```diff
@@ -172,9 +155,9 @@ impl RuntimeConfig {
         self
     }
 
-    /// Customize memory manager
-    pub fn with_memory_manager(mut self, memory_manager: MemoryManagerConfig) -> Self {
-        self.memory_manager = memory_manager;
+    /// Customize memory policy
+    pub fn with_memory_policy(mut self, memory_pool: Arc<dyn MemoryPool>) -> Self {
```
Comment (yjshen) [inline datafusion/core/src/execution/runtime_env.rs:159]: We could eliminate the word `policy` and explain that different pool comes with different allocation policies.

File: datafusion/core/src/physical_plan/sorts/sort.rs [hunk 21]
```diff
@@ -136,94 +144,83 @@ impl ExternalSorter {
...
                 }
                 Ordering::Equal => {}
             }
-            in_mem_batches.push(partial);
+            self.in_mem_batches.push(partial);
         }
         Ok(())
     }
 
     async fn spilled_before(&self) -> bool {
```
[the remark this answers is not in the document]
Comment (yjshen) [reply datafusion/core/src/physical_plan/sorts/sort.rs:164]: And we could inline and remove this function

**Review by yjshen — APPROVED** [review]
Thanks @tustvold! I really like the new design of pools with different allocation policies, and moving `spill()` out of memory management simplifies the APIs a lot.

File: datafusion/core/src/execution/memory_pool/pool.rs (hunk 19 above)
Comment (alamb) [reply datafusion/core/src/execution/memory_pool/pool.rs:140]: I see -- I agree keeping `TrackedAllocation::new` makes sense. 

I guess I was getting confused by the fact that `allocate` doesn't actually `allocate` any memory, but instead it really registers a `TrackedAllocation` with the memory manager. Likewise `free` doesn't free any memory

Could we somehow make the relationship between `MemoryManager`,  `AllocationOptions` and `TrackedAllocation` clearer

What about changing some names:

```
MemoryManager::allocate --> MemoryManager::register
MemoryManager::free --> MemoryManager::deregister
```

File: datafusion/core/src/execution/runtime_env.rs (hunk 20 above)
Comment (tustvold) [reply datafusion/core/src/execution/runtime_env.rs:159]: Nice catch, this was the old name :+1:

File: datafusion/core/src/execution/memory_pool/pool.rs (hunk 19 above)
Comment (tustvold) [reply datafusion/core/src/execution/memory_pool/pool.rs]: I've renamed `TrackedAllocation` to `MemoryReservation` and `AllocationOptions` to `MemoryConsumer`. I also tweaked the registration API to fit with this. PTAL

File: datafusion/core/src/execution/memory_pool/mod.rs [hunk 22]
```diff
@@ -25,43 +25,43 @@ pub mod proxy;
...
     /// On error the `allocation` will not be increased in size
-    fn try_grow(&self, allocation: &TrackedAllocation, additional: usize) -> Result<()>;
+    fn try_grow(&self, reservation: &MemoryReservation, additional: usize) -> Result<()>;
 
     /// Return the total amount of memory allocated
     fn allocated(&self) -> usize;
 }
 
-/// Options associated with a [`TrackedAllocation`]
+/// A memory consumer that can be tracked by [`MemoryReservation`] in a [`MemoryPool`]
```
Comment (alamb) [inline datafusion/core/src/execution/memory_pool/mod.rs:57]: 👍

File: datafusion/core/src/execution/memory_pool/mod.rs [hunk 23]
```diff
@@ -80,47 +80,35 @@ impl AllocationOptions {
     pub fn name(&self) -> &str {
         &self.name
     }
+
+    /// Registers this [`MemoryConsumer`] with the provided [`MemoryPool`] returning
+    /// a [`MemoryReservation`] that can be used to grow or shrink the memory reservation
+    pub fn register(self, pool: &Arc<dyn MemoryPool>) -> MemoryReservation {
```
Comment (alamb) [inline datafusion/core/src/execution/memory_pool/mod.rs:90]: This is a nice interface

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @tustvold

File: datafusion/core/src/execution/memory_pool/pool.rs [hunk 24]
```diff
@@ -0,0 +1,285 @@
...
+                        additional,
+                        available,
+                    ));
+                }
+                state.spillable += additional;
+            }
+            false => {
+                let available = self
+                    .pool_size
+                    .saturating_sub(state.unspillable + state.unspillable);
```
Comment (xiaoyong-z) [inline datafusion/core/src/execution/memory_pool/pool.rs:193]: why sub state.unspillable twice here

Comment (crepererum) [reply datafusion/core/src/execution/memory_pool/pool.rs:193]: good question, @tustvold ?

Comment (tustvold) [reply datafusion/core/src/execution/memory_pool/pool.rs:193]: Looks like a mistake, good spot
