### PR TITLE
`compute_decimal_op_dyn_scalar` should not cast lhs array to decimal array

### LINKED ISSUE #5464: `compute_decimal_op_dyn_scalar` should not cast lhs array to decimal array
**Describe the bug**

Comparing decimal dictionary array with scalar value causes an error like:

```
thread 'expressions::binary::tests::comparison_dict_decimal_scalar_expr_test' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("could not cast value to arrow_array::array::primitive_array::PrimitiveArray<arrow_array::types::Decimal128Type>")', datafusion/physical-expr/src/expressions/binary.rs:1085:17                                                                                                                                
```

In `compute_decimal_op_dyn_scalar` macro, we shouldn't cast lhs array to decimal array as it invokes dyn kernel and lhs array could be dictionary array.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #5464.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/binary.rs [hunk 1]
```diff
@@ -150,9 +150,8 @@ impl std::fmt::Display for BinaryExpr {
 
 macro_rules! compute_decimal_op_dyn_scalar {
     ($LEFT:expr, $RIGHT:expr, $OP:ident, $OP_TYPE:expr) => {{
-        let ll = as_decimal128_array($LEFT).unwrap();
         if let ScalarValue::Decimal128(Some(v_i128), _, _) = $RIGHT {
-            Ok(Arc::new(paste::expr! {[<$OP _dyn_scalar>]}(ll, v_i128)?))
+            Ok(Arc::new(paste::expr! {[<$OP _dyn_scalar>]}($LEFT, v_i128)?))
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/binary.rs:154]: it makes sense to me not to cast the left hand side

In general, now that the dyn kernels are more complete, I wonder if we need the specific decimal macros at all 🤔

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thank you @viirya

**Comment by viirya** [comment]
Thanks @alamb
