### PR TITLE
fix: `common_subexpr_eliminate` and aggregates

### LINKED ISSUE #6116: `common_sub_expression_eliminate` on aggregates is wrong
### Describe the bug

`common_sub_expression_eliminate` pushes aggregate expressions into a child of the aggregate note which is wrong.

### To Reproduce

See

https://github.com/apache/arrow-datafusion/blob/0d93dede46aae547d0ac167aa3e3e502efdffb97/datafusion/optimizer/src/common_subexpr_eliminate.rs#L707-L728

### Expected behavior

```rust
let expected = "Projection: Int32(1) + AVG(test.a), Int32(1) - AVG(test.a)\
\n  Aggregate: groupBy=[[]], aggr=[[AVG(test.a) AS AVG(test.a)]]\
        \n    TableScan: test";
```

In general it should push the expression used within aggregate (and aggregate UDFs) into a child while placing the users of the aggregates into a parent. So a more complex test case may look like this:

```rust
#[test]
fn aggregate() -> Result<()> {
    let table_scan = test_table_scan()?;

    let inner = binary_expr(lit(1), Operator::Plus, avg(col("a")));
    let plan = LogicalPlanBuilder::from(table_scan)
        .aggregate(
            iter::empty::<Expr>(),
            vec![
                binary_expr(lit(1), Operator::Plus, avg(inner)),
                binary_expr(lit(1), Operator::Minus, avg(inner)),
                min(inner),
            ],
        )?
        .build()?;

    let expected = "Projection: Int32(1) + AVG(TMP), Int32(1) - AVG(TMP), MIN(TMP)\
    \n  Aggregate: groupBy=[[]], aggr=[[AVG(TMP) as AVG(TMP), MIN(TMP) as MIN(TMP)]]\
    \n    Projection: Int32(1) + test.a AS TMP, test.a, test.b, test.c\
    \n      TableScan: test";

    assert_optimized_plan_eq(expected, &plan);

    Ok(())
}
```

(I somewhat improvised the column naming here to be able to write this down quicker)

### Additional context

For SQL queries this doesn't seem to be an issue because this kind of de-duplication seems already be done during lowering, e.g. this code

```sql
SELECT AVG(c1 + 1) + 1, AVG(c1 + 1) + 2 FROM test
```

produces this initial plan:

```text
Projection: AVG(test.c1 + Int64(1)) + Int64(1), AVG(test.c1 + Int64(1)) + Int64(2)
  Aggregate: groupBy=[[]], aggr=[[AVG(test.c1 + Int64(1))]]
    TableScan: test
```

However plans created manually using the `LogicalPlanBuilder` don't necessarily share this behavior.

### PR DESCRIPTION
**Pull request by crepererum**
# Which issue does this PR close?
Fixes #6116.

# Rationale for this change
`common_subexpr_eliminate` MUST NOT push aggregate functions into the `LogicalPlan::Aggregate` child.

# What changes are included in this PR?
Fixed and improved logic for aggregates.

# Are these changes tested?
- existing tests pass (modulo `aggregate`)
- fixed and extended `aggregate` test

# Are there any user-facing changes?
Probably no changes for SQL users. This mostly affects Rust API users that manually construct logical plans (e.g. for other query languages).

### CODE REVIEW

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 1]
```diff
@@ -352,6 +462,49 @@ fn build_recover_project_plan(schema: &DFSchema, input: LogicalPlan) -> LogicalP
     )
 }
 
+/// Which type of [expressions](Expr) should be considered for rewriting?
```
Comment (crepererum) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:465]: While this resulted in more code, I've decided to pull the masking out into its own enum / config value so the code is easier to read and extend (I could imagine that we may wanna have more special treatments for other logical plan nodes at some point).

**Comment by alamb** [comment]
cc @waynexia

**Comment by alamb** [comment]
This PR seems to have some CI issues but I am not sure if they are related to changes here 🤔

**Comment by crepererum** [comment]
I'm pretty sure it's unrelated:

```text
error[E0425]: cannot find value `env_var` in crate `gix_path`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/gix-config-0.20.1/src/file/init/comfort.rs:31:54
   |
31 |                     .storage_location(&mut gix_path::env_var)
   |                                                      ^^^^^^^ not found in `gix_path`

error[E0425]: cannot find function `home_dir` in crate `gix_path`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/gix-config-0.20.1/src/file/init/comfort.rs:44:30
   |
44 |         let home = gix_path::home_dir();
   |                              ^^^^^^^^ not found in `gix_path`
   |
help: consider importing one of these items
   |
1  | use gix_path::env::home_dir;
   |
1  | use std::env::home_dir;
   |
help: if you import `home_dir`, refer to it directly
   |
44 -         let home = gix_path::home_dir();
44 +         let home = home_dir();
   |

....
```

I can debug this tomorrow if nobody beats me on that.

**Comment by alamb** [comment]
FWIW I see the `gix_config` error on a brach with no code changes . Filed https://github.com/apache/arrow-datafusion/issues/6132

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 1 above)
Comment (alamb) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:465]: Another enum also adds an excellent place for more documentation 👍

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 2]
```diff
@@ -708,22 +889,149 @@ mod test {
...
+                    udf_agg(col("a")).alias("col4"),
+                    udf_agg(col("a")).alias("col5"),
+                    // no common
+                    udf_agg(col("b")).alias("col6"),
+                    udf_agg(col("c")),
+                ],
+            )?
+            .build()?;
+
+        let expected = "Projection: AVG(test.a)test.a AS AVG(test.a) AS col1, AVG(test.a)test.a AS AVG(test.a) AS col2, col3, AVG(test.c) AS AVG(test.c), my_agg(test.a)test.a AS my_agg(test.a) AS col4, my_agg(test.a)test.a AS my_agg(test.a) AS col5, col6, my_agg(test.c) AS my_agg(test.c)\
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:932]: 👍

**Review by alamb — APPROVED** [review]
I reviewed the tests carefully and this looks great to me. Thank you @crepererum 

I plan to wait to merge this PR for a day or two more in case others (like @waynexia  who I think was the original contributor of this code) can have time to review if they like

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 3]
```diff
@@ -197,16 +223,93 @@ impl OptimizerRule for CommonSubexprEliminate {
                 let new_aggr_expr = pop_expr(&mut new_expr)?;
                 let new_group_expr = pop_expr(&mut new_expr)?;
 
-                Some(LogicalPlan::Aggregate(Aggregate::try_new_with_schema(
```
Comment (waynexia) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:200]: I need file a PR to restructure this (very) huge map as it keeps expanding...

**Review by waynexia — APPROVED** [review]
Thanks for this 🚀 It takes me seconds to realize what's wrong in #6116. I had never previously noticed that the aggr plan is special before 🤧

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 4]
```diff
@@ -708,22 +889,149 @@ mod test {
...
 
-        let expected = "Aggregate: groupBy=[[]], aggr=[[Int32(1) + AVG(test.a)test.a AS AVG(test.a), Int32(1) - AVG(test.a)test.a AS AVG(test.a)]]\
-        \n  Projection: AVG(test.a) AS AVG(test.a)test.a, test.a, test.b, test.c\
+        let expected = "Projection: Int32(1) + AVG(test.a)test.a AS AVG(test.a), Int32(1) - AVG(test.a)test.a AS AVG(test.a), Int32(1) + my_agg(test.a)test.a AS my_agg(test.a), Int32(1) - my_agg(test.a)test.a AS my_agg(test.a)\
+        \n  Aggregate: groupBy=[[]], aggr=[[AVG(test.a) AS AVG(test.a)test.a, my_agg(test.a) AS my_agg(test.a)test.a]]\
         \n    TableScan: test";
 
         assert_optimized_plan_eq(expected, &plan);
 
+        // test: trafo before aggregate
```
[the remark this answers is not in the document]
Comment (crepererum) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:957]: transformation, will fix the comment to spell it out

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 5]
```diff
@@ -708,22 +889,149 @@ mod test {
...
+
+        // test: trafo after aggregate
+        let plan = LogicalPlanBuilder::from(table_scan.clone())
             .aggregate(
                 iter::empty::<Expr>(),
                 vec![
                     binary_expr(lit(1), Operator::Plus, avg(col("a"))),
                     binary_expr(lit(1), Operator::Minus, avg(col("a"))),
+                    binary_expr(lit(1), Operator::Plus, udf_agg(col("a"))),
+                    binary_expr(lit(1), Operator::Minus, udf_agg(col("a"))),
```
[the remark this answers is not in the document]
Comment (crepererum) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs]: done (also for the other tests within this module

**Comment by alamb** [comment]
Thanks again @crepererum  and @waynexia
