### PR TITLE
Preserve `TableScan.projection` order in `push_down_projection` optimizer rule

### LINKED ISSUE #5146: Re-ordering Projections in scan are not working anymore (since DF15)
**Describe the bug**
Projections for re-ordering the columns of schemas don't work anymore in `LogicalPlanBuilder::scan` (since DF15), because the schema changes unexpectedly during Optimizer rule 'push_down_projection'.

**To Reproduce**
Minimal example:
```rust
use std::io::Cursor;
use std::sync::Arc;

use futures::TryStreamExt;
use datafusion::{
    arrow::
        record_batch::RecordBatch,
    datasource::{DefaultTableSource, MemTable},
    logical_expr::LogicalPlanBuilder,
    physical_plan::{memory::MemoryStream, SendableRecordBatchStream},
    prelude::SessionContext,
};

use itertools::Itertools;

fn main() {
}

#[tokio::test]
async fn with_projection() -> Result<(), anyhow::Error> {
    let input = create_record_batches_from_csv(
        r###"
Category,Year,Metric
Electronics,2010,10
Electronics,2011,10
Electronics,2012,10
Pharmacy,2010,20
Pharmacy,2011,30
Pharmacy,2012,40
"###,
    )
    .await?;
    let ctx = SessionContext::new();
    let mem_table = Arc::new(MemTable::try_new(
        input.schema(),
        vec![input.try_collect().await?],
    )?);
    let plan = LogicalPlanBuilder::scan(
        "some_memtable",
        Arc::new(DefaultTableSource::new(mem_table)),
        Some(vec![1, 0, 2]),
    )?
    .build()?;
    let physical_plan = ctx.state().create_physical_plan(&plan).await?;
    let _input = datafusion::physical_plan::execute_stream(physical_plan, ctx.task_ctx())?;
    
    Ok(())
}


pub async fn create_record_batches_from_csv(
    csv: &str,
) -> Result<SendableRecordBatchStream, anyhow::Error> {
    let csv_reader: Vec<RecordBatch> = datafusion::arrow::csv::ReaderBuilder::new()
        .has_header(true)
        .build(Cursor::new(csv))?
        .try_collect()?;
    let schema = csv_reader
        .get(0)
        .expect("There should be at least 1 record batch")
        .schema();

    Ok(Box::pin(MemoryStream::try_new(csv_reader, schema, None)?))
}
```
with Cargo.toml
```
[package]
name = "df-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "17"
arrow = "31"      # IMPORTANT: keep in sync with the version that `datafusion`uses

anyhow = "1.0"
futures = "0.3"
itertools = "0.10"
tokio = "1"
tokio-retry = "0.3"
tokio-stream = "0.1"
tokio-util = "0.7"
```
yields the error
```
Error: Internal error: Optimizer rule 'push_down_projection' failed, due to generate a different schema, original schema: 
DFSchema { fields: 
[
DFField { qualifier: Some("some_memtable"), field: Field { name: "Year", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some("some_memtable"), field: Field { name: "Category", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some("some_memtable"), field: Field { name: "Metric", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }
], metadata: {} }, 

new schema: DFSchema { fields:
 [
DFField { qualifier: Some("some_memtable"), field: Field { name: "Category", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some("some_memtable"), field: Field { name: "Year", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } },
 DFField { qualifier: Some("some_memtable"), field: Field { name: "Metric", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }
], metadata: {} }. 

This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

**Expected behavior**
In DF14 this code did not yield an error (and indeed should not). Instead the output schema was changed as expected.

### PR DESCRIPTION
**Pull request by korowa**
# Which issue does this PR close?

Closes #5146.

# Rationale for this change

Fixing `push_down_projection` behaviour for "TableScan-only" queries -- recreation `TableScan.projection` changes column order in output plan schema, which is unacceptable for the optimizer.

# What changes are included in this PR?

Now push down projection preserves original order of projection indices, filtering out not required fields.

# Are these changes tested?

Added tests for optimizing scan with randomly ordered projection and optimizing projection over it.

Also added test for randomly ordered projection in CsvExec, as, at first, this issue looked suspiciously similar to #4832 (not that case -- CsvExec was working in 16-17 versions)

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/optimizer/src/push_down_projection.rs [hunk 1]
```diff
@@ -523,13 +523,24 @@ fn push_down_scan(
         }
     }
 
+    // Building new projection from BTreeSet
+    // preserving source projection order if it exists
+    let projection = if let Some(original_projection) = &scan.projection {
+        original_projection
```
Comment (alamb) [inline datafusion/optimizer/src/push_down_projection.rs:529]: What about columns that are in `projection` but not in `original_projection` (as in the original projection did not contain sufficient columns for the query)?

**Review by alamb — COMMENTED** [review]
This looks like a very nice change -- thank you @korowa 

I had one small question but otherwise it looks ready to go to me

File: datafusion/optimizer/src/push_down_projection.rs (hunk 1 above)
Comment (korowa) [reply datafusion/optimizer/src/push_down_projection.rs:529]: After an attempt of writing test for this case I've realized that maybe we don't need additional plan validity checks in optimizer rules -- normally plan builder won't allow to project/filter/etc on missing column 🤔

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
I will wait for @jackwener 's review to merge

**Review by jackwener — APPROVED** [review]
A great job to me. Thanks @korowa
