### PR TITLE
fix: inconsistent scalar types in `DistinctArrayAggAccumulator` state

### LINKED ISSUE #6743: Trouble getting fancy with ARRAY_AGG (DISTINCT ARRAY_AGG)
### Describe the bug

`ARRAY_AGG` usage in SQL results in an error when used in conjunction with `DISTINCT` parameter alongside another aggregate field.

### To Reproduce

1. Establish example data:
  ```sql
  CREATE TABLE example(id INT, parent_id INT, tag VARCHAR) AS VALUES
      (1, 0, 'bob'),
      (2, 0, 'cat'),
      (3, 1, 'tom'),
      (4, 1, 'cat'),
      (5, 1, 'tom');
  ```
2. Execute query using `ARRAY_AGG` and `DISTINCT` parameter:
  ```sql
  SELECT
          parent_id,
          COUNT(id) AS count_of,
          ARRAY_AGG(DISTINCT tag) AS tags
      FROM example
      GROUP BY parent_id;
  ```

Executing the above results in the following message:
```
ArrowError(ExternalError(Internal("Inconsistent types in ScalarValue::iter_to_array. Expected Utf8, got List([tom,cat])")))
```

### Expected behavior

Desired output should be similar to the following:

| parent_id | count_of | tags            |
|-----------|----------|-----------------|
| 1         | 3        | [tom, cat] |
| 0         | 2        | [bob, cat]      |

### Additional context

Omitting either the `COUNT` field, or the `DISTINCT` clause in `ARRAY_AGG`, allows the query to complete successfully.

The above was initially discovered in v17.0.0 and verified to still be presenting in v26.0.0.

### PR DESCRIPTION
**Pull request by korowa**
## Which issue does this PR close?

Closes #6743.

## Rationale for this change

Currently `DistinctArrayAggAccumulator` stores its state as a set of scalar values and returns it as a single scalar list. The problem is that while merging state, accumulator, instead of adding list elements, simply adds the whole list to the state as a single value, which causes errors while executing `evaluate` on accumulator with merged state.

## What changes are included in this PR?

`merge_state` now unpacks scalar list input and updates state with its elements.

## Are these changes tested?

- tests for merging `DistinctArrayAggAccumulator`s have been added, 
- check for successful execution of `array_agg(distinct col)` has been added to sqllogictests

## Are there any user-facing changes?

`array_agg(distinct)` should not fail in case query execution requires merging accumulator states (e. g. aggregation over multiple partitions)

### CODE REVIEW

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs [hunk 1]
```diff
@@ -195,24 +227,34 @@ mod tests {
...
+        ));
 
-        Ok(())
+        let mut accum1 = agg.create_accumulator()?;
+        let mut accum2 = agg.create_accumulator()?;
+
+        accum1.update_batch(&[input1])?;
+        accum2.update_batch(&[input2])?;
+
+        let state = get_accum_scalar_values_as_arrays(accum2.as_ref())?;
```
Comment (metesynnada) [inline datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:252]: I think there can be more than 2 accumulators. However, the thing I do not understand is that `AggregateStream` calls `aggregate_batch` with multiple states involve, like 

```rust
let values = &expr
    .iter()
    .map(|e| e.evaluate(&batch))
    .map(|r| r.map(|v| v.into_array(batch.num_rows())))
    .collect::<Result<Vec<_>>>()?;

// 1.4
let size_pre = accum.size();
let res = match mode {
    AggregateMode::Partial
    | AggregateMode::Single
    | AggregateMode::SinglePartitioned => accum.update_batch(values),
    AggregateMode::Final | AggregateMode::FinalPartitioned => {
        accum.merge_batch(values)
    }
};
```
where `values` is a `Vec<ArrayRef>`, but this test seems to take a different approach. Can you enlighten me about the procedure?

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs [hunk 2]
```diff
@@ -147,11 +146,21 @@ impl Accumulator for DistinctArrayAggAccumulator {
             return Ok(());
         }
 
-        for array in states {
-            for j in 0..array.len() {
-                self.values.insert(ScalarValue::try_from_array(array, j)?);
+        assert!(
+            states.len() == 1,
+            "array_agg_distinct states must contain single array"
+        );
```
Comment (metesynnada) [inline datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:152]:
```suggestion
        assert_eq!(
            states.len(),
            1,
            "array_agg_distinct states must contain single array"
        );
```

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs [hunk 3]
```diff
@@ -147,11 +146,21 @@ impl Accumulator for DistinctArrayAggAccumulator {
...
+
+        let state = &states[0];
+        (0..state.len()).try_for_each(|i| {
+            let scalar = ScalarValue::try_from_array(state, i)?;
```
Comment (metesynnada) [inline datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:156]:
```suggestion
        let array = &states[0];
        (0..array.len()).try_for_each(|i| {
            let scalar = ScalarValue::try_from_array(array, i)?;
```

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 4]
```diff
@@ -1280,6 +1280,10 @@ NULL NULL 781 7.81 125 -117 100
 # ----
 # [4, 2, 3, 5, 1]
 
+# additional count(1) forces array_agg_distinct instead of array_agg over aggregated by c2 data
+statement ok
+SELECT array_agg(distinct c2), count(1) FROM aggregate_test_100
```
[the remark this answers is not in the document]
Comment (korowa) [reply datafusion/sqllogictest/test_files/aggregate.slt:1285]: Unfortunately, we don't have array_sort / list_sort function yet, and output of array_agg(distinct) is non-deterministic, so absence of failures is the best option of SQL-level check (as I can see it)

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs (hunk 1 above)
Comment (korowa) [reply datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:252]: True, but 2 is enough for `merge_batch` logic validation.

Regarding `AggregateStream` and these tests behaviour:
1) single `AggregateExec` and stream(s) originated from it can have multiple accumulators -- depending on how much aggregate expressions are used in query or subquery
2) during `aggregate_batch` all accumulators are respectively updated in a loop
3) aggregation can be performed in two stages -- at first stage (`Partial` aggregation mode) each accumulator is updated by calling `update_batch` with `AggregateExec` input data, and as a result partial aggregation there is produced stream of accumulators intermediate states -- output stream is generated by [finalize_aggregation](https://github.com/apache/arrow-datafusion/blob/3ffeb52c1c9891e63fcb17db41283d7299af6f18/datafusion/core/src/physical_plan/aggregates/mod.rs#L1075)
4) the second stage -- final aggregation updates each accumulator with `merge_batch`, using stream of states from previous step as an input, and produces stream of `accumulator.evaluate()` results (also as a result of calling finalize_aggregation with `Final` mode)

This test basically reproduces this behaviour of aggregation for the case with single accumulator in `AggregateExec` (as there is only one aggregate expression), and accum1/accum2 variables represent different input streams (not different expressions):
1) partial aggregation is emulated by `update_batch` on each of two accumulators -- as if they were aggregating different input partitions
2) then accum2 state is collected by `get_accum_scalar_values_as_arrays` (it also returns `Vec<ArrayRef>`), and emulates `finalize_aggregation` call for `Partial` mode
3) the state from step 2 merged into first accumulator using `merge_batch` -- as is would work in case of `Final` aggregation mode (there would be third accumulator, but 2 is still enough for testing purposes)
4) finally result produced by `accum1.evaluate()` over merged state compared to expected value

Hope, I got your question correct, and this coment answers it.

File: datafusion/sqllogictest/test_files/aggregate.slt (hunk 4 above)
[the remark this answers is not in the document]
Comment (Dandandan) [reply datafusion/sqllogictest/test_files/aggregate.slt:1285]: What about unnesting and then using `order by`?

[the remark this answers is not in the document]
Comment (korowa) [reply datafusion/sqllogictest/test_files/aggregate.slt:1285]: Not sure if there exists SQL-level `unnest `🤔  -- it seems to be provided only by dataframe API (also [PR](https://github.com/apache/arrow-datafusion/pull/6796) and [issue](https://github.com/apache/arrow-datafusion/issues/6555) for this still are open).

But yeah, I can manually unnest in anyway, thank you!

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs (hunk 1 above)
Comment (metesynnada) [reply datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:255]: Thank you for providing me with a detailed answer. Appreciated.

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs [hunk 5]
```diff
@@ -135,23 +134,36 @@ impl Accumulator for DistinctArrayAggAccumulator {
...
+            states.len(),
+            1,
+            "array_agg_distinct states must contain single array"
+        );
+
+        let array = &states[0];
+        (0..array.len()).try_for_each(|i| {
+            let scalar = ScalarValue::try_from_array(array, i)?;
+            if let ScalarValue::List(Some(values), _) = scalar {
+                self.values.extend(values);
```
Comment (alamb) [inline datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:161]: 👍  extend should do the deduplication. 👍

**Review by alamb — APPROVED** [review]
This change makes sense to me -- thank you @korowa

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 6]
```diff
@@ -1271,14 +1271,31 @@ NULL 4 29 1.260869565217 123 -117 23
...
+#       unnest is also not available, so manually unnesting via CROSS JOIN
+# additional count(1) forces array_agg_distinct instead of array_agg over aggregated by c2 data
 #
 # csv_query_array_agg_distinct
-# query T
-# SELECT array_agg(distinct c2) FROM aggregate_test_100
-# ----
-# [4, 2, 3, 5, 1]
+query III
+WITH indices AS (
```
[the remark this answers is not in the document]
Comment (korowa) [reply datafusion/sqllogictest/test_files/aggregate.slt:1280]: Actual aggregation input is `aggregate_test_100.c2` -- in the [subquery](https://github.com/apache/arrow-datafusion/pull/7385/files#diff-a60d69cf923e18b0532e7ba3470c4b728e6b00230b3ea242f3fbe95e899c5ffeR1289). These indices are required only to check query output -- I was't able to find better way to compare non-deterministic array -- more details in the [thread](https://github.com/apache/arrow-datafusion/pull/7385#discussion_r1303147504) above

File: datafusion/sqllogictest/test_files/aggregate.slt (hunk 4 above)
[the remark this answers is not in the document]
Comment (korowa) [reply datafusion/sqllogictest/test_files/aggregate.slt]: Done using cross-join and CTE for array indices
