### PR TITLE
Use FairSpillPool for TaskContext with spillable config

### LINKED ISSUE #8069: run_first_last_multi_partitions fails in some environments
### Describe the bug

`run_first_last_multi_partitions` fails when I run `cargo test` on my M1 Macbook Air with 16 GB RAM. It passes on my Ubuntu workstation with 128 GB RAM.

```
---- aggregates::tests::run_first_last_multi_partitions stdout ----
Error: ResourcesExhausted("Failed to allocate additional 632 bytes for GroupedHashAggregateStream[0] with 1829 bytes already allocated - maximum available is 605")
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #8069.

### CODE REVIEW

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 1]
```diff
@@ -1271,8 +1272,11 @@ mod tests {
     fn new_spill_ctx(batch_size: usize, max_memory: usize) -> Arc<TaskContext> {
         let session_config = SessionConfig::new().with_batch_size(batch_size);
         let runtime = Arc::new(
-            RuntimeEnv::new(RuntimeConfig::default().with_memory_limit(max_memory, 1.0))
-                .unwrap(),
+            RuntimeEnv::new(
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/mod.rs:1275]: Is the reason this fixes the linked issue that a fair spill pool allocates memory in some pre-determined fashion rather than based on the actual memory usage (which can vary depending on the order in which operations are executed)?

**Review by alamb — APPROVED** [review]
Thank you @viirya

**Review by andygrove — APPROVED** [review]
Fix works for me. Thanks @viirya!

File: datafusion/physical-plan/src/aggregates/mod.rs (hunk 1 above)
Comment (viirya) [reply datafusion/physical-plan/src/aggregates/mod.rs:1275]: Hmm, I guess so though I'm not very sure. I just feel that for spilling it makes more sense to use `FairSpillPool` and looks like it can fix the test issue.
