### PR TITLE
[BugFix] fix explain csv/json/avro exec can not see metrics bug

### LINKED ISSUE #5014: explain analyze can not see csvexec execution time metrics
**Describe the bug**
explain analyze can not see csvexec execution time metrics

**To Reproduce**
create a table
explain analyze select * from tables3;
image
both ProjectionExec, RepartitionExec have metrics,
but CsvExec doesn't have metrics

**Expected behavior**
CsvExec also have metrics

**Additional context**

### PR DESCRIPTION
**Pull request by xiaoyong-z**
When we executing explain analyze select * from tablexxx, csv/json/avro exev metrics is empty.
This bug is introduced by not implementing metrics traits in csv/json/avro.

Signed-off-by: xyz <a997647204@gmail.com>

# Which issue does this PR close?

Closes #5014

# Rationale for this change

Before 
image
After
image

# What changes are included in this PR?

implementing metrics traits in csv/json/avro, add csv metrics unit test

# Are these changes tested?
yes

# Are there any user-facing changes?
User can see metrics in csv exec

### CODE REVIEW

File: datafusion/core/src/physical_plan/file_format/csv.rs [hunk 1]
```diff
@@ -676,4 +687,15 @@ mod tests {
...
+
+    fn get_value(metrics: &MetricsSet, metric_name: &str) -> usize {
+        match metrics.sum_by_name(metric_name) {
+            Some(v) => v.as_usize(),
+            _ => {
+                panic!(
+                    "Expected metric not found. Looking for '{metric_name}' in\n\n{metrics:#?}"
+                );
+            }
+        }
```
Comment (jackwener) [inline datafusion/core/src/physical_plan/file_format/csv.rs:699]: Use `Option .ok_or()`?

**Review by jackwener — APPROVED** [review]
In general, looks great to me
