### PR TITLE
fix comparison of decimal array with null scalar

### LINKED ISSUE #3487: comparison operations with a scalar null and decimal array panics
**Describe the bug**

This test fails when given decimals instead of floats:'sql::expr::comparisons_with_null_lt' with error

```
 panicked at 'called `Result::unwrap()` on an `Err` value: "ArrowError(ExternalError(Internal(\"Cannot convert Decimal128(None,2,1) to i128\"))) ...
```

**To Reproduce**

You can reproduce with the following:
```sql
❯ select a < null from (values (1.1::decimal)) as t(a);
ArrowError(ExternalError(Internal("Cannot convert Decimal128(None,2,1) to i128")))
```

but interestingly, the scalar / scalar version of that work fine:
```sql
❯ select null < 1.1::decimal;
+---------------------------------+
| NULL < Decimal128(Some(11),2,1) |
+---------------------------------+
|                                 |
+---------------------------------+
1 row in set. Query took 0.002 seconds.
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by kmitchener**
# Which issue does this PR close?

Closes #3487 .

 # Rationale for this change

Prior to fix, would error (no longer panic after Arrow 23). After fix, works as expected.

```sql
❯ select a < null from (values (1.1::decimal)) as t(a);
+------------------------------+
| t.a < Decimal128(None,38,10) |
+------------------------------+
|                              |
+------------------------------+
1 row in set. Query took 0.014 seconds.
```
# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/binary.rs [hunk 1]
```diff
@@ -642,7 +662,7 @@ macro_rules! binary_array_op_dyn_scalar {
 
         let result: Result<Arc<dyn Array>> = match right {
             ScalarValue::Boolean(b) => compute_bool_op_dyn_scalar!($LEFT, b, $OP, $OP_TYPE),
-            ScalarValue::Decimal128(..) => compute_decimal_op_scalar!($LEFT, right, $OP, Decimal128Array),
+            ScalarValue::Decimal128(..) => compute_decimal_op_dyn_scalar!($LEFT, right, $OP, $OP_TYPE),
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/binary.rs:665]: ❤️  you are starting to figure out the thicket that is `binary.rs` 👍

File: datafusion/physical-expr/src/expressions/binary.rs [hunk 2]
```diff
@@ -120,13 +120,33 @@ impl std::fmt::Display for BinaryExpr {
...
-            ll,
-            $RIGHT.try_into()?,
-        )?))
+        let ll = $LEFT.as_any().downcast_ref::<Decimal128Array>().unwrap();
+        if let ScalarValue::Decimal128(Some(_), _, _) = $RIGHT {
+            Ok(Arc::new(paste::expr! {[<$OP _decimal_scalar>]}(
+                ll,
+                $RIGHT.try_into()?,
+            )?))
+        } else {
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/binary.rs:146]: Should we assert here that `$RIGHT` is still a decimal ? As written the code could convert `ScalarValue::Int8(Some(4))` into NULL, for example

But I don't know if such a `ScalarValue` could be passed

File: datafusion/physical-expr/src/expressions/binary.rs (hunk 1 above)
Comment (kmitchener) [reply datafusion/physical-expr/src/expressions/binary.rs:665]: Oh yeah :) and what a pleasure it is

File: datafusion/physical-expr/src/expressions/binary.rs (hunk 2 above)
Comment (kmitchener) [reply datafusion/physical-expr/src/expressions/binary.rs:146]: I don't think we need to. Those 2 decimal macros are used only in 1 place each and include "decimal" in the name -- it'd be a clear mistake to use it for any other datatype. This area could use some refactoring, but I wanted to get this in and the kernels moved to arrow-rs then maybe revisit this whole module (famous last words, right?).

Comment (alamb) [reply datafusion/physical-expr/src/expressions/binary.rs:146]: famous last words maybe, but a reasonable plan nonetheless ;)

**Comment by alamb** [comment]
Thanks again @kmitchener
