### PR TITLE
fix: Min/Max aggregation data type should not be dictionary

### LINKED ISSUE #1234: select min/max(string dictionary) panics
**Describe the bug**
SELECT min/max(dictionary_string_column) will panic with the following message:
`ArrowError(InvalidArgumentError("column types must match schema types, expected Dictionary(Int32, Utf8) but found Utf8 at column index 0"))'`

**To Reproduce**
Add the below test inside [query_on_string_dictionary](https://github.com/apache/arrow-datafusion/blob/dd9350607a9b4c8aaf6d7204fda8f1eab31a7ac2/datafusion/tests/sql.rs#L3935-L3993), you will hit that bug.
```
    // aggregation min
    let sql = "SELECT MIN(d1) FROM test";
    let actual = execute(&mut ctx, sql).await;
    let expected = vec![vec!["one"]];
    assert_eq!(expected, actual);
```

**Expected behavior**
Query runs and returns correct results

Refer to this https://github.com/influxdata/influxdb_iox/issues/2776 for history and analysis

### PR DESCRIPTION
**Pull request by NGA-TRAN**
# Which issue does this PR close? 

Closes #1234

 # Rationale for this change
Since Min/Max Aggregation only returns one value per group, it should not be Dictionary which is mostly used for many values

# What changes are included in this PR?
If Data Type of the input of the Min/Max aggregate is Dictionary, make data type of min/max aggregate the data type of the `value` of the Dictionary.

# Are there any user-facing changes?
The min/max(dictionary string) now no longer panics

### CODE REVIEW

**Comment by NGA-TRAN** [comment]
@alamb : can you help review this?

File: datafusion/src/physical_plan/expressions/min_max.rs [hunk 1]
```diff
@@ -72,15 +81,15 @@ impl AggregateExpr for Max {
     fn field(&self) -> Result<Field> {
         Ok(Field::new(
             &self.name,
-            self.data_type.clone(),
+            min_max_aggregate_data_type(self.data_type.clone()),
```
Comment (houqp) [inline datafusion/src/physical_plan/expressions/min_max.rs:84]: since `min_max_aggregate_data_type` is already performing clone internally, perhaps we can just pass by reference here?

Comment (alamb) [reply datafusion/src/physical_plan/expressions/min_max.rs:84]: I think it might be clearer code if this datatype transformation was done as part of the construction of `Min` and `Max` -- that way `self.data_type` would contain the correct output type for the aggregate, and future code would not have to remember to translate `self.data_type`

Perhaps  something like


```
impl Max {
    /// Create a new MAX aggregate function
    pub fn new(
        expr: Arc<dyn PhysicalExpr>,
        name: impl Into<String>,
        data_type: DataType,
    ) -> Self {
        Self {
            name: name.into(),
            expr,
            data_type: min_max_aggregate_data_type(data_type),
            nullable: true,
        }
    }
}
```

File: datafusion/src/physical_plan/planner.rs [hunk 2]
```diff
@@ -1422,6 +1422,10 @@ impl DefaultPhysicalPlanner {
             new_plan = optimizer.optimize(new_plan, &ctx_state.config)?;
             observer(new_plan.as_ref(), optimizer.as_ref())
         }
+        debug!(
+            "Optimized physical plan short version:\n{}\n",
+            displayable(new_plan.as_ref()).indent().to_string()
```
Comment (alamb) [inline datafusion/src/physical_plan/planner.rs:1427]:
```suggestion
            displayable(new_plan.as_ref()).indent()
```

I don't think the call to `to_string()` is needed here -- not that it is a huge deal

File: datafusion/src/physical_plan/expressions/min_max.rs [hunk 3]
```diff
@@ -38,6 +38,15 @@ use arrow::{
 
 use super::format_state_name;
 
+// min/max aggregation only returns a value for each group
```
Comment (alamb) [inline datafusion/src/physical_plan/expressions/min_max.rs:41]: Maybe we could modify the comment here to explain that since the `Min/Max` aggregate can handle `Dictionary` encoded inputs, but always produces "unpacked" (aka non `Dictionary`) output we need to adjust the output data type to reflect this.

File: datafusion/tests/sql.rs [hunk 4]
```diff
@@ -3976,6 +3976,12 @@ async fn query_on_string_dictionary() -> Result<()> {
     let expected = vec![vec!["2"]];
     assert_eq!(expected, actual);
 
+    // aggregation min
```
Comment (alamb) [inline datafusion/tests/sql.rs:3979]: Since the changes are needed for min and max, I suggest also adding a test here for `max` to ensure it is covered

File: datafusion/src/physical_plan/expressions/min_max.rs [hunk 5]
```diff
@@ -38,6 +38,15 @@ use arrow::{
...
+// and should not be a Dictionary data type anymore
+fn min_max_aggregate_data_type(input_type: DataType) -> DataType {
+    match input_type {
+        DataType::Dictionary(_, value_type) => (*value_type).clone(),
+        _ => input_type.clone(),
+    }
```
Comment (alamb) [inline datafusion/src/physical_plan/expressions/min_max.rs:47]: I think you can save the clone by reusing the types passed in. Something like (untested)


```suggestion
    if let DataType::Dictionary(_, value_type) = input_type {
        value_type
    } else {
        input_type
    }
```

I doubt the extra clone makes any noticeable difference, but I figured I would point it out

**Review by alamb — APPROVED** [review]
Thank you @NGA-TRAN . I think the basic idea makes sense and is good to go. There are a few comments related to code style / structure but I think this is also ok to merge as is (something works with it that did not work previously)

**Comment by NGA-TRAN** [comment]
Thanks @houqp and @alamb . I am working to address your comments

**Comment by NGA-TRAN** [comment]
@houqp and @alamb : I have addressed your comments. There are fewer changes now. Yaay!

**Review by alamb — APPROVED** [review]
Looks great. Thanks @NGA-TRAN . I'll merge this once the CI checks all pass
