### PR TITLE
Fix null comparison for Parquet pruning predicate

### LINKED ISSUE #1591: Parquet pruning predicate is not handling null comparisons correctly
**Describe the bug**

`col = null` expression evaluation throws a runtime error when getting evaluated against statistics array, which resulted in incorrect `true` result when the stats has null count set to 0.

The other problem is `col = null` expression is converted into `col_min <= NULL AND NULL <= col_max` predicate expression. I believe we should be handling null as a special case and return an expression that checks against null count column instead.

**To Reproduce**

See our test cases at: https://github.com/apache/arrow-datafusion/blob/f027e5f4d9a44ad9cc879c133abc913f78fa76f0/datafusion/src/physical_plan/file_format/parquet.rs#L722-L763

The test case asserts that results for both row groups should return `true`, while them should both be `false` instead because both row groups have null count set to 0.

**Expected behavior**

`col = null` row group should be evaluated by taking row group null count stats into account.

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1591.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @viirya  -- I will try to review this carefully, but likely won't be able to do so until tomorrow

**Comment by viirya** [comment]
Thank you @alamb

**Review by houqp — APPROVED** [review]
Thanks @viirya for the quick fix!

File: datafusion/src/physical_optimizer/pruning.rs [hunk 1]
```diff
@@ -430,6 +460,15 @@ impl<'a> PruningExpressionBuilder<'a> {
         self.required_columns
             .max_column_expr(&self.column, &self.column_expr, self.field)
     }
+
+    fn null_count_column_expr(&mut self) -> Result<Expr> {
+        let null_count_field = &Field::new(self.field.name(), DataType::Int64, false);
+        self.required_columns.null_count_column_expr(
```
Comment (alamb) [inline datafusion/src/physical_optimizer/pruning.rs:466]: 👍

File: datafusion/src/physical_optimizer/pruning.rs [hunk 2]
```diff
@@ -657,13 +696,23 @@ fn build_statistics_expr(expr_builder: &mut PruningExpressionBuilder) -> Result<
...
-                    .lt_eq(expr_builder.scalar_expr().clone())
-                    .and(expr_builder.scalar_expr().clone().lt_eq(max_column_expr))
+                if expr_builder
+                    .scalar_expr_value()
+                    .map(|s| s.is_null())
+                    .unwrap_or(false)
+                {
+                    // column = null => null_count > 0
+                    let null_count_column_expr = expr_builder.null_count_column_expr()?;
+                    null_count_column_expr.gt(lit::<i64>(0))
```
Comment (alamb) [inline datafusion/src/physical_optimizer/pruning.rs:706]: I am curious why we use a `i64` here rather than `u64`?

File: datafusion/src/physical_plan/file_format/parquet.rs [hunk 3]
```diff
@@ -757,10 +784,8 @@ mod tests {
             .enumerate()
             .map(|(i, g)| row_group_predicate(g, i))
             .collect::<Vec<_>>();
-        // no row group is filtered out because the predicate expression can't be evaluated
-        // when a null array is generated for a statistics column,
-        // because the null values propagate to the end result, making the predicate result undefined
-        assert_eq!(row_group_filter, vec![true, true]);
+        // First row group was filtered out because it contains no null value on "c2".
+        assert_eq!(row_group_filter, vec![false, true]);
```
Comment (alamb) [inline datafusion/src/physical_plan/file_format/parquet.rs:788]: I actually think this could be `vec![false, false]` as the predicate can never be true (`int > 1 AND bool = NULL` is always `NULL`)

File: datafusion/src/physical_optimizer/pruning.rs [hunk 4]
```diff
@@ -75,6 +77,10 @@ pub trait PruningStatistics {
     /// return the number of containers (e.g. row groups) being
     /// pruned with these statistics
     fn num_containers(&self) -> usize;
+
+    /// return the number of null values for the named column.
+    /// Note: the returned array must contain `num_containers()` rows.
+    fn null_counts(&self, column: &Column) -> Option<ArrayRef>;
```
Comment (alamb) [inline datafusion/src/physical_optimizer/pruning.rs:83]:
```suggestion

    /// return the number of null values for the named column as an 
    /// `Option<Int64Array>`.
    /// 
    /// Note: the returned array must contain `num_containers()` rows.
    fn null_counts(&self, column: &Column) -> Option<ArrayRef>;
```

I had to look this up to figure out what type this was required

**Review by alamb — APPROVED** [review]
Thanks @viirya  and @houqp 

BLUF: I am fairly sure this change is ok, but I am not sure why it is needed; I have outlined my confusions below.

Note I ran this change against the IOx test suite in https://github.com/influxdata/influxdb_iox/pull/3479 and it was good.

# Confusion 1: Doesn't follow definition of a pruning predicate:

As a reminder, the pruning predicate definition is


```rust
    /// A pruning predicate is one that has been rewritten in terms of
    /// the min and max values of column references and that evaluates
    /// to FALSE if the filter predicate would evaluate FALSE *for
    /// every row* whose values fell within the min / max ranges (aka
    /// could be pruned).
    ///
    /// The pruning predicate evaluates to TRUE or NULL
    /// if the filter predicate *might* evaluate to TRUE for at least
    /// one row whose vaules fell within the min/max ranges (in other
    /// words they might pass the predicate)
```

Thus, a "TRUE" or "NULL" result for a predicate means the row group must be kept. This is the safe behavior -- only if it is 100% certain that the predicate will evaluate to FALSE should the row group be removed

In this case, `x = null` doesn't seem to satisfy the stated conditions in `PruningPredicate`. `x = null` evaluates to `null` for **all** values (both null and non null) as can be seen in postgres:

```
alamb=# select x, x = null from foo;
 x | ?column?
---+----------
 1 |
   |
 2 |
(3 rows)

alamb=#
```


Thus there is something wrong. Either:
1. the pruning predicate definition should be updated to say that a pruning predicate will return false if all rows will evaluate to FALSE **OR NULL** (which seems reasonable as only rows that evaluate to `TRUE` pass a predicate, not row that return `null`)
2. this is not a correct transformation

# Confusion 2: Why are we treating `=` specially?

If we go with this PR, I don't see any reason to handle `=` specially, as same argument applies to other operators such as `!=`, `>`, etc (though it does not apply to `IS DISTINCT` / `IS NOT DISTINCT`).

File: datafusion/src/physical_plan/file_format/parquet.rs (hunk 3 above)
Comment (viirya) [reply datafusion/src/physical_plan/file_format/parquet.rs:788]: I am not sure about the expression semantics in datafusion. In Spark, the predicate should be `IsNull` that checks the null value. Here I follow the original expression `bool = NULL`.

I see there is also `IsNull` predicate expression, but I don't see `IsNull` is handled in predicate pushdown. I don't know if this is intentional or a bug.

I can fix it if you agree that `IsNull` is correct way to handle null predicate here.

File: datafusion/src/physical_optimizer/pruning.rs (hunk 2 above)
Comment (viirya) [reply datafusion/src/physical_optimizer/pruning.rs:706]: Oh, you're right. This should be `u64`.

File: datafusion/src/physical_plan/file_format/parquet.rs (hunk 3 above)
Comment (viirya) [reply datafusion/src/physical_plan/file_format/parquet.rs:788]: I think this is related to the "Confusion 1".

Comment (alamb) [reply datafusion/src/physical_plan/file_format/parquet.rs:788]: In sql `IsNull` is the correct way to test a column for null as well 👍 

It would make a lot of sense to me to rewrite `x IS NULL` --> `0 > x_null_count`

Comment (viirya) [reply datafusion/src/physical_plan/file_format/parquet.rs:788]: yea, I'm surprised when I looked at the `bool = NULL` and confused too. I guess this is how datafusion works but seems not :). Let me fix it together.

Comment (viirya) [reply datafusion/src/physical_plan/file_format/parquet.rs:788]: Would you like me to fix it here or in a following PR?

File: datafusion/src/physical_optimizer/pruning.rs (hunk 2 above)
Comment (viirya) [reply datafusion/src/physical_optimizer/pruning.rs]: Changed to `u64`.

File: datafusion/src/physical_optimizer/pruning.rs [hunk 5]
```diff
@@ -421,6 +444,13 @@ impl<'a> PruningExpressionBuilder<'a> {
         &self.scalar_expr
     }
 
+    fn scalar_expr_value(&self) -> Result<&ScalarValue> {
```
[the remark this answers is not in the document]
Comment (viirya) [reply datafusion/src/physical_optimizer/pruning.rs]: Updated.

File: datafusion/src/physical_optimizer/pruning.rs (hunk 4 above)
Comment (viirya) [reply datafusion/src/physical_optimizer/pruning.rs]: Updated.

File: datafusion/src/physical_plan/file_format/parquet.rs (hunk 3 above)
Comment (viirya) [reply datafusion/src/physical_plan/file_format/parquet.rs:790]: I've updated to use IsNull for predicate pruning.

**Review by alamb — APPROVED** [review]
Thanks @viirya  -- looks good to me. @houqp  is this what you had in mind for https://github.com/apache/arrow-datafusion/issues/1591 ?

**Comment by houqp** [comment]
Thank you @viirya for the fix and @alamb for the detailed review :+1:

**Comment by viirya** [comment]
Thank you @houqp @alamb !

**Comment by alamb** [comment]
Thanks @houqp !
