### PR TITLE
Avoid to use TempDir::into_path for temporary dirs expected to be deleted automatically

### LINKED ISSUE #7251: Temporary dirs are not deleted automatically in some tests.
### Describe the bug

In some tests, temporary directories are not deleted automatically even though they are intended to be deleted.
One example is `csv_exec_with_projection`.

### To Reproduce

If you run the `csv_exec_with_projection` on Linux, you can see directories and files generated by the test remain.
```
$ cargo test csv_exec_with_projection --package datafusion
$ ls /tmp/.tmp*
/tmp/.tmp1jDyfj:
partition-0.csv.gz

/tmp/.tmp8Iz7To:
partition-0.csv

/tmp/.tmpBXl5a4:
partition-0.csv.bz2

/tmp/.tmpGjGDEc:
partition-0.csv.xz

/tmp/.tmpbj2vH7:
partition-0.csv.zst
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sarutak**
## Which issue does this PR close?

Closes #7251 

## Rationale for this change

In `datafusion/core/src/test/mod.rs`, `TempDir` is used for a temporary directory and then `TempDir::into_path` is called.
But once `TempDir::into_path` is called, the corresponding directory is no longer deleted automatically.
It's noted in the [API doc](https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html#method.into_path).
So, it's better to use `TempDir::path` instead of `TempDir::into_path`.

## What changes are included in this PR?

Removed the usage of `TempDir::into_path` and use `TempDir::path`.

## Are these changes tested?
Existing tests passed and temporary directories no longer remain.
```
$ cargo test --package datafusion
$ ls /tmp/.tmp*
```

## Are there any user-facing changes?
No.

### CODE REVIEW

File: datafusion/core/src/test/mod.rs [hunk 1]
```diff
@@ -102,11 +105,10 @@ pub fn partitioned_file_groups(
     partitions: usize,
     file_type: FileType,
     file_compression_type: FileCompressionType,
+    work_dir: &Path,
```
Comment (sarutak) [inline datafusion/core/src/test/mod.rs:108]: are Temporary directories created by `TempDir::new` are deleted in `TempDir::drop`.
But files created in the temporary directory can be refered by callers of this method, so we can't call `TempDir::new` in this method.
The life cycle of such temporary directories should be managed by callers.

File: datafusion/core/src/datasource/physical_plan/json.rs [hunk 2]
```diff
@@ -374,17 +376,19 @@ mod tests {
     async fn test_additional_stores(
         file_compression_type: FileCompressionType,
         store: Arc<dyn ObjectStore>,
-    ) {
+    ) -> Result<()> {
         let ctx = SessionContext::new();
         let url = Url::parse("file://").unwrap();
         ctx.runtime_env().register_object_store(&url, store.clone());
         let filename = "1.json";
+        let tmp_dir = TempDir::new()?;
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/json.rs:384]: FWIW it is also fine in test code to use `unwrap()` and avoid having to return `Result`s -- either is acceptable I think.

**Review by alamb — APPROVED** [review]
Thank you @sarutak  -- this makes a lot of sense to me. Thank you for cleaning up the tests
