### PR TITLE
Safeguard against potential inexact row count being smaller than exact null count

### LINKED ISSUE #9006: Attempt to subtract with overflow panic in `max_distinct_count`
### Describe the bug

There's an edge case in the present `max_distinct_count` algorithm, whereby there can be an attempt to subtract a potentially larger number of total nulls from a inexact smaller number of total rows to get the distinct values
https://github.com/apache/arrow-datafusion/blob/bee7136a04c60a2c06caa630cf1b72f32f7dc574/datafusion/physical-plan/src/joins/utils.rs#L957-L959

This leads to a panic with `attempt to subtract with overflow`.

### To Reproduce

Extract the three parquet files from [files.zip](https://github.com/apache/arrow-datafusion/files/14064122/files.zip) needed for the repro. These were generated using DuckDB with SF=0.01 for TPC-DS benchamrks. The example below is a minimal repro for an issue observed for query 24 from that benchmark.

```rust
#[tokio::main]
async fn main() -> Result<()> {
    let ctx = SessionContext::new();

    let file_format = ParquetFormat::default().with_enable_pruning(Some(true));
    let listing_options = ListingOptions::new(Arc::new(file_format))
        .with_file_extension(FileType::PARQUET.get_ext());

    ctx.register_listing_table(
        "store",
        &format!("/path/to/store.parquet"),
        listing_options.clone(),
        None,
        None,
    )
    .await?;
    ctx.register_listing_table(
        "store_sales",
        &format!("/path/to/store_sales.parquet"),
        listing_options.clone(),
        None,
        None,
    )
        .await?;
    ctx.register_listing_table(
        "customer",
        &format!("/path/to/customer.parquet"),
        listing_options,
        None,
        None,
    )
        .await?;

    let df = ctx
        .sql(
            "SELECT c_last_name,
       c_first_name,
       s_store_name,
       s_state
FROM store_sales,
     store,
     customer
WHERE ss_customer_sk = c_customer_sk
  AND ss_store_sk = s_store_sk
  AND s_market_id=8",
        )
        .await?;

    // print the results
    df.show().await?;

    Ok(())
}
```

The above code panics with:
```bash
thread 'main' panicked at datafusion/physical-plan/src/joins/utils.rs:958:40:
attempt to subtract with overflow
```

Note that you can get a repro with the cli by appending `DATAFUSION_EXECUTION_COLLECT_STATISTICS=true DATAFUSION_EXECUTION_TARGET_PARTITIONS=1` to `cargo run`

### Expected behavior

The example shouldn't panic, but instead return an empty result.

### Additional context

As for the question how does this situation even occur in the first place, from my brief investigation I'm seeing that:

1. The `FilterExec` for the filtering on the `store` table predicate returns `Inexact(0)` as the number of rows for it's output statistics, since the predicate refutes all the input rows (in the case of `store` above there's only a single row with `s_market_id` equals to 2).
2. When joining `store` and `store_sales` the join cardinality estimate is 0 due to the above filtering, but the column statistic are nonetheless merged as is (meaning an exact null count for the `store_sales` columns is inherited)
https://github.com/apache/arrow-datafusion/blob/bee7136a04c60a2c06caa630cf1b72f32f7dc574/datafusion/physical-plan/src/joins/utils.rs#L848-L859
3. Finally during merging with `customer` the statistics from step 2 enters into play, and when it reaches `max_distinct_count` it hits the `num_rows` being `Inexact(0)` but `stats.null_count` being exact and greater than zero edge case.

### PR DESCRIPTION
**Pull request by gruuya**
## Which issue does this PR close?

Closes #9006.

## Rationale for this change

Sometimes an ineact row count can be smaller than the exact null count which leads to a panic.

## What changes are included in this PR?

Do a checked subtraction to get the max distinct count estimate, and if it over(under)flows return Inexact(0).

## Are these changes tested?

They are tested against the case presented in #9006, and there's a unit test added.

## Are there any user-facing changes?

Avoid panic during execution.

### CODE REVIEW

File: datafusion/physical-plan/src/joins/utils.rs [hunk 1]
```diff
@@ -955,7 +955,12 @@ fn max_distinct_count(
             let result = match num_rows {
                 Precision::Absent => Precision::Absent,
                 Precision::Inexact(count) => {
-                    Precision::Inexact(count - stats.null_count.get_value().unwrap_or(&0))
+                    // To safeguard against inexact number of rows (e.g. 0) being smaller than
+                    // an exact null count we need to do a checked subtraction.
+                    match count.checked_sub(*stats.null_count.get_value().unwrap_or(&0)) {
+                        None => Precision::Inexact(0),
```
Comment (gruuya) [inline datafusion/physical-plan/src/joins/utils.rs:961]: This made more sense than `Precision::Absent`.

Also, I'm not sure whether this can happen below as well, i.e. an inexact null count being larger than an exact row count.

Comment (alamb) [reply datafusion/physical-plan/src/joins/utils.rs:961]: I agree -- the use of `Statistics::get_value()` I think may also have other bugs as `get_value()` may be exact or inexact but there are some places in the code that treat it as though it were always `exact` (like here)

I have hopes to improve statistics in general (see https://github.com/apache/arrow-datafusion/issues/8227) but other higher priority things have kept me busy. I think @berkaysynnada  was also working on this item for a while -- I am not sure if they have any short term plans

File: datafusion/physical-plan/src/joins/utils.rs [hunk 2]
```diff
@@ -1670,133 +1677,156 @@ mod tests {
             //
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/utils.rs:1677]: I double checked that this code fails without the code change in this PR 👍 

```shell
attempt to subtract with overflow
thread 'joins::utils::tests::test_inner_join_cardinality_single_column' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/arith.rs:217:1:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:127:5
   3: <usize as core::ops::arith::Sub>::sub
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/arith.rs:217:1
   4: <&usize as core::ops::arith::Sub<&usize>>::sub
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/internal_macros.rs:55:17
   5: datafusion_physical_plan::joins::utils::max_distinct_count
             at ./src/joins/utils.rs:960:40
   6: datafusion_physical_plan::joins::utils::estimate_inner_join_cardinality
             at ./src/joins/utils.rs:911:33
   7: datafusion_physical_plan::joins::utils::tests::test_inner_join_cardinality_single_column
             at ./src/joins/utils.rs:1818:17
   8: datafusion_physical_plan::joins::utils::tests::test_inner_join_cardinality_single_column::{{closure}}
             at ./src/joins/utils.rs:1666:55
   9: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: test failed, to rerun pass `--lib`
error: 1 target failed:
    `--lib`
```

**Review by alamb — APPROVED** [review]
Thank you @gruuya  -- this looks good to me (and is well tested 👌 )

File: datafusion/physical-plan/src/joins/utils.rs (hunk 1 above)
Comment (berkaysynnada) [reply datafusion/physical-plan/src/joins/utils.rs:961]: This issue has been out of my focus for a while. I can help those who wish to take it on and make progress. Unfortunately, addressing this issue is not in my short-term plans.

**Comment by alamb** [comment]
Thanks again @gruuya
