### PR TITLE
removed self.all_values.len() from inside reserve

### LINKED ISSUE #6674: Excessive memory usage of `median` function
### Describe the bug

Excessive memory usage of `MedianAccumulator` due to incorrect use of the `Vec<T>::reserve` API:

https://github.com/apache/arrow-datafusion/blob/c4928b035db3c3dc20554b5abe23e4de2a322fe4/datafusion/physical-expr/src/aggregate/median.rs#L129

which is documented as:

```rust
alloc::vec impl<T, A: Allocator> Vec<T, A>
pub fn reserve(&mut self, additional: usize)
```

> Reserves capacity for at least `additional` more elements to be inserted in the given `Vec<T>`. The collection may reserve more space to speculatively avoid frequent reallocations. After calling `reserve`, capacity will be greater than or equal to `self.len() + additional`

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BryanEmond**
# Which issue does this PR close?

Closes #6674 .

# Rationale for this change

See #6674 

# What changes are included in this PR?
Removed self.all_values.len() from inside reserve().
I have also looked at the two other places where reserve() is used, and they don't use the same calculation.
https://github.com/apache/arrow-datafusion/blob/9dfaf4249e31e9a08953955fe4837eb287b089bf/datafusion/execution/src/memory_pool/proxy.rs#L41
https://github.com/apache/arrow-datafusion/blob/9dfaf4249e31e9a08953955fe4837eb287b089bf/datafusion/execution/src/memory_pool/proxy.rs#L83

# Are these changes tested?
No

# Are there any user-facing changes?
No

### CODE REVIEW

**Comment by alamb** [comment]
Thanks @BryanEmond ! I started CI

File: datafusion/physical-expr/src/aggregate/median.rs [hunk 1]
```diff
@@ -126,7 +126,7 @@ impl Accumulator for MedianAccumulator {
         let array = &values[0];
 
         assert_eq!(array.data_type(), &self.data_type);
-        self.all_values.reserve(self.all_values.len() + array.len());
+        self.all_values.reserve(array.len());
```
Comment (alamb) [inline datafusion/physical-expr/src/aggregate/median.rs:129]: Per the rust docs: https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reserve

> Reserves capacity for at least additional more elements to be inserted in the given Vec<T>. The collection may reserve more space to speculatively avoid frequent reallocations. After calling reserve, capacity will be greater than or equal to self.len() + additional. Does nothing if capacity is already sufficient.

👍

**Review by alamb — APPROVED** [review]
Thanks again @BryanEmond  -- this  PR is close to getting the "least time between ticket and PR award" 🏆

**Comment by alamb** [comment]
cc @stuartcarnie

**Review by stuartcarnie — APPROVED** [review]
Fantastic!

**Comment by alamb** [comment]
Thanks again @BryanEmond !
