### PR TITLE
Use prep_null_mask_filter to handle nulls in selection mask

### LINKED ISSUE #9179: Query Fails in MAC M1
### Describe the bug

The query
```sql
SELECT t1_id, t1_int, t2_int FROM t1 LEFT JOIN t2 ON t1_id = t2_id AND t1_int >= t2_int
```
in the `sort_merge_join.slt` file fails in my PC.
Its expected result is
```
11 1 NULL
22 2 1
33 3 NULL
44 4 3
```
However, it produces following result
```
11 1 NULL
22 2 1
44 4 3
```
It seems like CI works without failing. Hence it might be related to my PC (MAC M1). 
Exactly same query under `join.slt` file works as expected. (Where only difference is either `HashJoin` or `SortMergeJoin` is used in for join.) Hence the problem might be related to the left join implementation of `SortMergeJoin`

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Follow up of #9080.

Close #9179 

## Rationale for this change

When applying join filter, we take filter evaluation array as selection mask to filter output batch. Next, we take the reverse mask to select (streamed) rows to join null rows.

With outer join cases, if filter evaluation has null values resulted in the selection mask, their reverse values are still nulls. Which makes some rows missed in (streamed) rows joined null rows.

We should use `prep_null_mask_filter` to handle nulls in selection mask as false before taking reverse mask from it.

### CODE REVIEW

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 1]
```diff
@@ -1209,7 +1209,14 @@ impl SMJStream {
                     ) {
                         // The reverse of the selection mask. For the rows not pass join filter above,
                         // we need to join them (left or right) with null rows for outer joins.
-                        let not_mask = compute::not(mask)?;
+                        let not_mask = if mask.null_count() > 0 {
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1212]: I ran the added test by #9080 again in a new laptop and found this bug. I'm not sure why previously the test passed locally and in CI in #9080. 🤔

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 2]
```diff
@@ -1209,7 +1209,14 @@ impl SMJStream {
...
+                            // If the mask contains nulls, we need to use `prep_null_mask_filter` to
+                            // handle the nulls in the mask as false.
+                            compute::not(&compute::prep_null_mask_filter(mask))?
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1215]: Using the test in `sort_merge_join.slt` as example:

```
CREATE TABLE IF NOT EXISTS t1(t1_id INT, t1_name TEXT, t1_int INT) AS VALUES
(11, 'a', 1),
(22, 'b', 2),
(33, 'c', 3),
(44, 'd', 4);

CREATE TABLE IF NOT EXISTS t2(t2_id INT, t2_name TEXT, t2_int INT) AS VALUES
(11, 'z', 3),
(22, 'y', 1),
(44, 'x', 3),
(55, 'w', 3);
```

For the query `SELECT t1_id, t1_int, t2_int FROM t1 LEFT JOIN t2 ON t1_id = t2_id AND t1_int >= t2_int`, `33 3 NULL` is one row to output without join filter. Join filter returns null on this row, so its value in mask selection array is null and the row is not picked.

Here we take reverse mask. As it is null, its reverse mask is still false, but this row should be selected here actually. So we need to call `prep_null_mask_filter` to process the mask before taking reverse array.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 1 above)
Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1212]: I re-checked the results in `sort_merge_join.slt` and it should be correct (as it is same as `join.slt` which is produced by hash join operator).

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 3]
```diff
@@ -1209,7 +1209,14 @@ impl SMJStream {
                     ) {
                         // The reverse of the selection mask. For the rows not pass join filter above,
                         // we need to join them (left or right) with null rows for outer joins.
-                        let not_mask = compute::not(mask)?;
+                        let not_mask = if mask.null_count() > 0 {
+                            // If the mask contains nulls, we need to use `prep_null_mask_filter` to
+                            // handle the nulls in the mask as false.
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1214]:
```suggestion
                            // handle the nulls in the mask as false to produce rows where the mask
                            // was null itself.
```

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 4]
```diff
@@ -1254,6 +1261,20 @@ impl SMJStream {
 
                         // For full join, we also need to output the null joined rows from the buffered side
                         if matches!(self.join_type, JoinType::Full) {
+                            // Handle not mask for buffered side further.
+                            // For buffered side, we want to output the rows that are not null joined with
+                            // the streamed side. i.e. the rows that are not null in the `buffered_indices`.
+                            let not_mask = if buffered_indices.null_count() > 0 {
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1267]: You might be able to avoid the unwrap by using

```rust 
                            let not_mask = if let Some(nulls) = if buffered_indices.nulls() { 
                                let mask = not_mask.values() & nulls.inner();
                                BooleanArray::new(mask, None)
                            } else {
                                not_mask
                            };
```

**Review by alamb — APPROVED** [review]
The code looks good to me, but I am worried that we have no test coverage for this

I double checked and `sort_merge_join.slt` seems to be running in CI. For example https://github.com/apache/arrow-datafusion/actions/runs/7848003246/job/21418418648#step:5:5748

Maybe it is time to increase the priority of running the CI tests on a mac: https://github.com/apache/arrow-datafusion/issues/9117

**Comment by viirya** [comment]
Thank you @alamb 

> Maybe it is time to increase the priority of running the CI tests on a mac: https://github.com/apache/arrow-datafusion/issues/9117

Yea, I agreed that we should increase our test coverage to aarch64.

**Comment by alamb** [comment]
For anyone following along, @viirya  did just that in https://github.com/apache/arrow-datafusion/pull/9191
