### PR TITLE
Fix projection pushdown produces incorrect results when column names are reused

### LINKED ISSUE #2462: Projection pushdown produces incorrect results when column names are reused
**Describe the bug**
In certain situations where projections are used to overwrite a column's value, the projection pushdown optimization pass causes the incorrect column value to be produced.

**To Reproduce**
Here is a failing test that will be included in the follow-on PR

```rust
#[tokio::test]
async fn select_with_alias_overwrite() -> Result<()> {
    let schema = Schema::new(vec![Field::new("a", DataType::Int32, false)]);

    let batch = RecordBatch::try_new(
        Arc::new(schema.clone()),
        vec![Arc::new(Int32Array::from_slice(&[1, 10, 10, 100]))],
    )
    .unwrap();

    let ctx = SessionContext::new();
    let provider = MemTable::try_new(Arc::new(schema), vec![vec![batch]]).unwrap();
    ctx.register_table("t", Arc::new(provider)).unwrap();

    let df = ctx
        .table("t")
        .unwrap()
        .select(vec![col("a").alias("a")])
        .unwrap()
        .select(vec![(col("a").eq(lit(10))).alias("a")])
        .unwrap()
        .select(vec![col("a")])
        .unwrap();

    let results = df.collect().await.unwrap();

    #[rustfmt::skip]
        let expected = vec![
        "+-------+",
        "| a     |",
        "+-------+",
        "| false |",
        "| true  |",
        "| true  |",
        "| false |",
        "+-------+",
    ];
    assert_batches_eq!(expected, &results);

    Ok(())
}
```
presently, the values produced for column `a` are the original values `[1, 10, 10, 100]` rather than the expected values `[false, true, true, false]`.

PR to follow shortly

### PR DESCRIPTION
**Pull request by jonmmease**
# Which issue does this PR close?

Closes #2462.

This PR adds the initially failing test `select_with_alias_overwrite`.  The simplest fix (that I've made in f3e87d8dde2ffb1d622fc30d53a1330b335dbc9b) is to revert #747.

Let me know if you see a way to capture the optimization intended by #747 that works in the presence of overwritten column values.

Thanks for taking a look!

### CODE REVIEW

**Comment by jonmmease** [comment]
Unsurprisingly, currently the `redundunt_project` test fails.

**Comment by alamb** [comment]
The CI tests  in this PR appear to be failing -- @jonmmease are you looking into those failures? Or would you like me to give it a look?

**Comment by jonmmease** [comment]
@alamb I think the first question is whether we're OK with backing out #747.  I belive the tests that are failing are checking for this specific optimization.  I didn't want to remove those tests if what we actually need to do is change how the optimization is triggered (though it wasn't obvious to me how to do this without introducing the error described in https://github.com/apache/arrow-datafusion/issues/2462).

**Comment by alamb** [comment]
Thanks @jonmmease  -- I will look into this more carefully tomorrow

File: datafusion/core/src/optimizer/projection_push_down.rs [hunk 1]
```diff
@@ -172,16 +172,7 @@ fn optimize_plan(
...
 
-            let new_required_columns_optimized = new_input
-                .schema()
-                .fields()
-                .iter()
-                .map(|f| f.qualified_column())
-                .collect::<HashSet<Column>>();
-
-            if new_fields.is_empty()
-                || (has_projection && &new_required_columns_optimized == required_columns)
```
Comment (alamb) [inline datafusion/core/src/optimizer/projection_push_down.rs:183]: I wonder if the issue is that this code is just checking column names to detect a reorder. The real check, as exposed in your reproducer, is that the the column names are the same *AND* that the expressions are only column references or constants... In the case of expressions (like in your reproducer) equal names is not sufficient

**Review by alamb — COMMENTED** [review]
Sorry for taking so long to look at this @jonmmease 

I have a suggestion on how maybe to avoid just backing out the change (by adding an additional check)

I am happy to try and code this up if you would like (as you have graciously implemented the test)

File: datafusion/core/src/optimizer/projection_push_down.rs (hunk 1 above)
Comment (jonmmease) [reply datafusion/core/src/optimizer/projection_push_down.rs:183]: That makes sense. I'll give it a try tomorrow unless you get to it first!

**Comment by jonmmease** [comment]
@alamb I'm seeing a failure in "Run Ballista Tests" and I can't tell if they are related to this PR

**Comment by alamb** [comment]
> @alamb I'm seeing a failure in "Run Ballista Tests" and I can't tell if they are related to this PR

I don't think they are related to this PR; The issue seems to be

https://github.com/apache/arrow-datafusion/runs/6406466598?check_suite_focus=true

```
nodefaultlibs"
  = note: /usr/bin/ld: final link failed: No space left on device
          collect2: error: ld returned 1 exit status
```

I think @andygrove  was seeing something similar yesterday but it seems to have resolved itself. I will trigger the test again and see if it passes this time 🤷

**Comment by jonmmease** [comment]
Failed again, just tried rebasing on master :crossed_fingers:

**Comment by jonmmease** [comment]
@alamb all green now

File: datafusion/core/src/optimizer/projection_push_down.rs [hunk 2]
```diff
@@ -179,8 +180,12 @@ fn optimize_plan(
                 .map(|f| f.qualified_column())
                 .collect::<HashSet<Column>>();
 
+            let all_column_exprs = new_expr.iter().all(|e| matches!(e, Expr::Column(_)));
```
Comment (alamb) [inline datafusion/core/src/optimizer/projection_push_down.rs:183]: The only question I have here is "what if the column is in an `alias` or something. However since the tests pass 👍

**Review by alamb — APPROVED** [review]
Thanks @jonmmease  -- looks great
