### PR TITLE
Implement/fix Eq and Hash for Expr and LogicalPlan

### LINKED ISSUE #5400: std::cmp::Eq reflexivity assumptions are violated
**Describe the bug**

Type [datafusion::logical_expr::Subquery](https://docs.rs/datafusion-expr/18.0.0/datafusion_expr/struct.Subquery.html) is declared to implement [std::cmp::Eq](https://doc.rust-lang.org/std/cmp/trait.Eq.html).

However, it **violates** reflexivity property.

Notice, that the type **respects** [std::cmp::PartialEq](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html), which is nevertheless a **distinct** trait!

**To Reproduce**

```rust
use datafusion::logical_expr::Subquery;
use datafusion::prelude::*;

#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
    let ctx = SessionContext::new();
    let df = ctx
        .read_csv(
            "datafusion/core/tests/tpch-csv/orders.csv",
            CsvReadOptions::default(),
        )
        .await?;
    let plan = df.logical_plan().clone();

    // There starts the show...
    let a = Subquery::new(plan);
    check_eq_reflexive(&a);    // Boom! PANICS!

    Ok(())
}

fn check_eq_reflexive<T: Eq>(a: &T) {
    assert!(a.eq(a), "not reflexive!");
}
```

**Expected behavior**

Type `datafusion::logical_expr::Subquery` should have reflexive `eq(...)`.

**Additional context**

This is a blocker of #3892, which would benefit from `Eq` and `Hash`. Already in the optimizer loop we have tricks, like dumping to strings, to compare `LogicalPlan`s.

⭐️ **Subjective "How fix it?"** ⭐️

The trait [std::cmp::Eq](https://doc.rust-lang.org/std/cmp/trait.Eq.html) does NOT require to compare all fields in the structure (`dyn` objects like functions or `TableProvider`s), so simple inspection/fix of `eq(..)` should be sufficient.

Overall, I think that `Eq` should behave like comparison of stringified `LogicPlan`s (this semantics literally is used in optimizer loop).

I could do the inspection/fix of `LogicPlan` `eq(...)`. 👋

### PR DESCRIPTION
**Pull request by mslapek**
# Which issue does this PR close?

Closes #5400.

# Rationale for this change

Makes [datafusion::logical_expr::Subquery](https://docs.rs/datafusion-expr/18.0.0/datafusion_expr/struct.Subquery.html) to respect the requirements of [std::cmp::Eq](https://doc.rust-lang.org/std/cmp/trait.Eq.html).

Because `Expr` contains `Subquery`, it also fixes `Expr::eq(..)`.

# What changes are included in this PR?

Fixed `Eq` for `Expr`.

Added `PartialEq`, `Eq` and `Hash` traits to `LogicalPlan` (because `Expr` contains `LogicalPlan` through `Subquery`).

Replaced the comparison of stringified plans with `eq(...)` comparison in `optimizer.rs`.

# Are these changes tested?

No new tests - most of the PRs contents is generated by `derive(..)` macros.

Optimizer loop already has existing tests.

# Are there any user-facing changes?

Added `PartialEq`, `Eq` and `Hash` traits to `LogicalPlan` and a few other structures.

**Breaking change:** Added `dyn_eq` and `dyn_hash` to `UserDefinedLogicalNode`.

### CODE REVIEW

File: datafusion/common/src/dfschema.rs [hunk 1]
```diff
@@ -496,6 +497,15 @@ impl From<DFSchema> for SchemaRef {
     }
 }
 
+// Hashing refers to a subset of fields considered in PartialEq.
+#[allow(clippy::derive_hash_xor_eq)]
+impl Hash for DFSchema {
+    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
+        self.fields.hash(state);
+        self.metadata.len().hash(state); // HashMap is not hashable
```
Comment (alamb) [inline datafusion/common/src/dfschema.rs:505]: I agree it is ok to just use the metadata's length to hash as it satisfies the EQ constraint

https://doc.rust-lang.org/std/hash/trait.Hash.html#hash-and-eq

File: datafusion/expr/src/logical_plan/plan.rs [hunk 2]
```diff
@@ -1515,8 +1515,30 @@ pub struct TableScan {
     pub fetch: Option<usize>,
 }
 
+impl PartialEq for TableScan {
+    fn eq(&self, other: &Self) -> bool {
+        self.table_name == other.table_name
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:1520]: I think this also needs to check that the `source` is equal as well -- I think we can do so via https://doc.rust-lang.org/std/sync/struct.Arc.html#method.ptr_eq

File: datafusion/expr/src/logical_plan/plan.rs [hunk 3]
```diff
@@ -1515,8 +1515,30 @@ pub struct TableScan {
...
+            && self.fetch == other.fetch
+    }
+}
+
+impl Eq for TableScan {}
+
+impl Hash for TableScan {
+    fn hash<H: Hasher>(&self, state: &mut H) {
+        self.table_name.hash(state);
+        self.projection.hash(state);
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:1533]: Hash is ok that it doesn't also include `source` I think

File: datafusion/expr/src/logical_plan/plan.rs [hunk 4]
```diff
@@ -1685,8 +1725,33 @@ pub struct Extension {
...
+impl PartialEq for Extension {
+    fn eq(&self, other: &Self) -> bool {
+        format!("{}", ExtensionExplainDisplay { extension: self })
+            == format!("{}", ExtensionExplainDisplay { extension: other })
+    }
+}
+
+impl Eq for Extension {}
+
+impl Hash for Extension {
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:1747]: I am not sure about using the textual output for equality comparison as someone who has implemented Extension may have a constant output, for example. I think a safer (though backwards incompatible change) would be to make `UserDefinedLogicalNode` also be `Hash` and `PartialEq`

Like

```rust
trait UserDefinedLogicalNode: Hash + PartialEq {
...
}
```

File: datafusion/expr/src/logical_plan/plan.rs [hunk 5]
```diff
@@ -1846,7 +1911,7 @@ impl Join {
 }
 
 /// Subquery
-#[derive(Clone)]
+#[derive(Clone, PartialEq, Eq, Hash)]
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:1914]: 🎉

File: datafusion/optimizer/src/optimizer.rs [hunk 6]
```diff
@@ -326,13 +327,12 @@ impl Optimizer {
             // TODO this is an expensive way to see if the optimizer did anything and
             // it would be better to change the OptimizerRule trait to return an Option
             // instead
-            let new_plan_str = format!("{}", new_plan.display_indent());
-            if plan_str == new_plan_str {
+            if old_plan.as_ref() == &new_plan {
```
Comment (alamb) [inline datafusion/optimizer/src/optimizer.rs:330]: 👍  nice

**Review by alamb — COMMENTED** [review]
Thank you for the contribution @mslapek  -- this looks good except for user defined logical nodes and `PartialEq` for `TableScan`.

File: datafusion/expr/src/logical_plan/plan.rs (hunk 2 above)
Comment (mslapek) [reply datafusion/expr/src/logical_plan/plan.rs:1520]: This `Arc::ptr_eq` might be **risky**... [Arc::ptr_eq](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.ptr_eq) and [std::ptr::eq](https://doc.rust-lang.org/std/ptr/fn.eq.html) say that `dyn` trait comparisons are **unreliable**. 😕

Even clippy gives an error [vtable_address_comparisons](https://rust-lang.github.io/rust-clippy/master/index.html#vtable_address_comparisons) from **correctness** 🔞 category.

I suggest to reconsider the request about `source` comparison.

File: datafusion/expr/src/logical_plan/plan.rs (hunk 4 above)
Comment (mslapek) [reply datafusion/expr/src/logical_plan/plan.rs:1747]: Couldn't add `Hash + PartialEq`, because `UserDefinedLogicalNode` must be *object-safe*.

Instead added `dyn_eq` and `dyn_hash` methods serving the same purpose.

File: datafusion/expr/src/logical_plan/plan.rs (hunk 2 above)
Comment (alamb) [reply datafusion/expr/src/logical_plan/plan.rs:1520]: Upon consideration within a single plan, the `table_name` should be unique. I was originally worried about the case where two TableScan's that had different `source`s but all other fields are the same resulting in a false positive.

**Review by alamb — APPROVED** [review]
Thank you @mslapek

**Comment by mslapek** [comment]
@alamb Thanks for the review! 🎉
