### PR TITLE
Fixing doc of the expression

### LINKED ISSUE #4231: Doc of the expression function`log2` is incorrect
**Describe the bug**
https://github.com/apache/arrow-datafusion/blob/406c1087bc16f8d2a49e5a9b05d2a0e1b67f7aa5/datafusion/expr/src/expr_fn.rs#L370
The doc here is incorrect.

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by Creampanda**
# Which issue does this PR close?

Closes #4231 
Doc of the expression functionlog2 is incorrect 

# Rationale for this change

Incorrect docs for some functions

# What changes are included in this PR?

# Are these changes tested?

Just changed some strings.

# Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/expr/src/expr_fn.rs [hunk 1]
```diff
@@ -366,8 +366,8 @@ unary_scalar_expr!(Round, round, "round to nearest integer");
 unary_scalar_expr!(Trunc, trunc, "truncate toward zero");
 unary_scalar_expr!(Abs, abs, "absolute value");
 unary_scalar_expr!(Signum, signum, "sign of the argument (-1, 0, +1) ");
-unary_scalar_expr!(Exp, exp, "base 2 logarithm");
-unary_scalar_expr!(Log2, log2, "base 10 logarithm");
+unary_scalar_expr!(Exp, exp, "exponent");
```
Comment (isidentical) [inline datafusion/expr/src/expr_fn.rs:369]: Very minor thing (mainly for consistency), but since most of the functions here mirror the [Postgres documentation](https://www.postgresql.org/docs/7.1/functions-math.html), maybe we should use it for the `exp()` as well.

```suggestion
unary_scalar_expr!(Exp, exp, "exponential");
```

**Review by andygrove — APPROVED** [review]

**Comment by alamb** [comment]
Thank you very much @Creampanda  and @isidentical
