### PR TITLE
Percent Decode URL Paths (#8009)

### LINKED ISSUE #7877: Unable to read a single parquet file from a Delta table with `LastUpdated=2023-10-08T20%3A54%3A33.250Z` in the path
### Describe the bug

I am trying to read parquet files from a Delta table. The parquet files are snappy compressed. My Delta table has 3 partition columns, so the folder structure of the Delta table looks something like this:
```
table
-- Col1=ABC
---- Col2=123
------ Col3=abc
-------- part-0000-xxxx-asdf.c00.snappy.parquet
-- Col1=XYZ
---- Col2=789
------ Col3=xyz
-------- part-0000-xyzj-qplg.c00.snappy.parquet
```

I was originally trying to read a list of files (I need to be able to read an arbitrary list of files), but debugging my issue has brought me to trying to read a single parquet file. My code for this is as follows:
```
async fn read_parquet(path: String) -> Result<(), DataFusionError> {
    let session = SessionContext::new();
    let df = session.read_parquet("/Users/me/Downloads/table/Col1=ABC/Col2=123/Col3=abc/part-0000-xxxx-asdf.c00.snappy.parquet", ParquetReadOptions::default()).await?;
    Ok(())
}
```

When I run this, I get:
```
thread 'main' panicked at src/main.rs:7:35:
called `Result::unwrap()` on an `Err` value: ObjectStore(NotFound { path: "/Users/me/Downloads/table/Col1=ABC/Col2=123/Col3=abc/part-0000-xxxx-asdf.c00.snappy.parquet", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } })
```

**HOWEVER**, if I run this same code, but instead of passing the full path to the parquet file, I pass only the directory the file is in (`"/Users/me/Downloads/table/Col1=ABC/Col2=123/Col3=abc"`), I get no such error and I'm able to successfully read the parquet file.

I'm not sure if I'm doing something wrong, or if this is some kind of bug.

### To Reproduce

Try to read a single parquet file from a local, partitioned Delta table, using `SessionContext::read_parquet`.

### Expected behavior

I expect the file to be read into DataFusion as a DataFrame.

### Additional context

_No response_

### LINKED ISSUE #8009: ListingTableUrl Inconsistent Percent Encoding
### Describe the bug

The behaviour of ListingTableUrl with respect to paths containing percent characters is rather confusing, and I suspect not entirely intentional.

Consider a filesystem containing a file named `bar%2Ffoo`, there is actually no obvious way to address this file.

```
let url = ListingTableUrl::parse("file:///foo/bar%2Ffoo").unwrap();
assert_eq!(url.prefix.as_ref(), "foo/bar/foo");

let url = ListingTableUrl::parse("file:///foo/a%252Fb.txt").unwrap();
assert_eq!(url.prefix.as_ref(), "foo/a%252Fb.txt");

let dir = tempdir().unwrap();
let path = dir.path().join("bar%2Ffoo");
std::fs::File::create(&path).unwrap();

let url = ListingTableUrl::parse(path.to_str().unwrap()).unwrap();
assert!(url.prefix.as_ref().ends_with("bar%252Ffoo"), "{}", url.prefix);
```

### To Reproduce

_No response_

### Expected behavior

The "correct" behaviour is that a file URL should be URL-encoded. That is according to the URL specification the correct way to reference this path would be `file:///foo/a%252Fb.txt`. Similarly the non-URL version should be `foo/a%2Fb.txt`.

That being said various tools instead interpret the URL path verbatim:

```
$ touch 'a%2Fb.txt'

$ aws --endpoint-url=http://localhost:4566 s3 cp 'a%2Fb.txt' s3://tustvold/

$ aws --endpoint-url=http://localhost:4566 s3 ls s3://tustvold/
2023-10-31 15:40:13          0 a%2Fb.txt

$ aws --endpoint-url=http://localhost:4566 s3 cp 's3://tustvold/a%2Fb.txt' foo.txt
aws --endpoint-url=http://localhost:4566 s3 cp 's3://tustvold/a%2Fb.txt' foo.txt

$ gsutil cp a\%2Fb.txt gs://tustvold

$ gsutil cp gs://tustvold/a\%2Fb.txt test
```

I'm not entirely sure how to classify DataFusion's current behaviour other than confusing. I think we should probably strive to replicate tools like the aws-cli and gsutil.

### Additional context

The current behaviour was added in #3750 

_No response_

### PR DESCRIPTION
**Pull request by tustvold**
## Which issue does this PR close?

Closes #8009
Closes #7877

## Rationale for this change

See ticket, the current behaviour is inconsistent and makes it impossible to address files with percent encoded paths. This was partially addressed in https://github.com/apache/arrow-datafusion/pull/3750 and works well for paths that don't contain percent encoded sequences, however, the behaviour is problematic for those that do.

## What changes are included in this PR?

This changes ListingTableUrl to treat the provided URLs as URL-encoded. The implications of this are:

* Users relying on percent encoding of non-URL safe characters, e.g. unicode, will need to do this themselves
* URLs containing percent encoded '%' characters, i.e. `%25` will now have a different but more consistent behaviour
* Paths containing percent encoded sequences of URL-safe characters will now work correctly

The ticket alluded to an approach used by some systems whereby it just takes the URL path verbatim, however, I had difficulty finding a way to get `Url` to play ball, as it insists on hewing the URL specification which doesn't allow for this. In general I think it is probably better to follow the actual specification, especially given the current behaviour is sufficiently broken I'm confident there aren't many people relying on it.

### CODE REVIEW

File: datafusion/core/src/datasource/listing/url.rs [hunk 1]
```diff
@@ -317,8 +315,27 @@ mod tests {
         let url = ListingTableUrl::parse("file:///foo/bar?").unwrap();
         assert_eq!(url.prefix.as_ref(), "foo/bar");
 
-        let url = ListingTableUrl::parse("file:///foo/😺").unwrap();
-        assert_eq!(url.prefix.as_ref(), "foo/%F0%9F%98%BA");
```
Comment (tustvold) [inline datafusion/core/src/datasource/listing/url.rs:321]: This behaviour was pretty surprising IMO, you get back a path that is more percent encoded :exploding_head:

File: datafusion/core/src/datasource/listing/url.rs [hunk 2]
```diff
@@ -317,8 +315,27 @@ mod tests {
...
+        assert_eq!(err.to_string(), "Object Store error: Encountered object with invalid path: Error parsing Path \"/foo/😺\": Encountered illegal character sequence \"😺\" whilst parsing path segment \"😺\"");
+
+        let url = ListingTableUrl::parse("file:///foo/bar%2Efoo").unwrap();
+        assert_eq!(url.prefix.as_ref(), "foo/bar.foo");
+
+        let url = ListingTableUrl::parse("file:///foo/bar%2Efoo").unwrap();
+        assert_eq!(url.prefix.as_ref(), "foo/bar.foo");
+
+        let url = ListingTableUrl::parse("file:///foo/bar%252Ffoo").unwrap();
+        assert_eq!(url.prefix.as_ref(), "foo/bar%2Ffoo");
```
Comment (tustvold) [inline datafusion/core/src/datasource/listing/url.rs:328]: On master this would return `foo/bar%252Ffoo`

File: datafusion/core/src/datasource/listing/url.rs [hunk 3]
```diff
@@ -317,8 +315,27 @@ mod tests {
...
+
+        let url = ListingTableUrl::parse("file:///foo/a%252Fb.txt").unwrap();
+        assert_eq!(url.prefix.as_ref(), "foo/a%2Fb.txt");
```
Comment (tustvold) [inline datafusion/core/src/datasource/listing/url.rs:331]: On master this would return `foo/a%252Fb.txt`

File: datafusion/core/src/datasource/listing/url.rs [hunk 4]
```diff
@@ -317,8 +315,27 @@ mod tests {
...
+
+        let dir = tempdir().unwrap();
+        let path = dir.path().join("bar%2Ffoo");
+        std::fs::File::create(&path).unwrap();
+
+        let url = ListingTableUrl::parse(path.to_str().unwrap()).unwrap();
+        assert!(url.prefix.as_ref().ends_with("bar%2Ffoo"), "{}", url.prefix);
```
Comment (tustvold) [inline datafusion/core/src/datasource/listing/url.rs:338]: On master this would return `bar%252Ffoo`

File: datafusion/core/src/datasource/listing/url.rs [hunk 5]
```diff
@@ -138,15 +137,13 @@ impl ListingTableUrl {
...
     }
 
     /// Creates a new [`ListingTableUrl`] from a url and optional glob expression
-    fn new(url: Url, glob: Option<Pattern>) -> Self {
-        let decoded_path =
-            percent_encoding::percent_decode_str(url.path()).decode_utf8_lossy();
-        let prefix = Path::from(decoded_path.as_ref());
-        Self { url, prefix, glob }
+    fn try_new(url: Url, glob: Option<Pattern>) -> Result<Self> {
+        let prefix = Path::from_url_path(url.path())?;
```
Comment (tustvold) [inline datafusion/core/src/datasource/listing/url.rs:145]: As an added bonus this complexity is now handled for us by the object_store crate :tada:

File: datafusion/core/src/datasource/listing/url.rs [hunk 6]
```diff
@@ -317,8 +315,27 @@ mod tests {
         let url = ListingTableUrl::parse("file:///foo/bar?").unwrap();
         assert_eq!(url.prefix.as_ref(), "foo/bar");
 
-        let url = ListingTableUrl::parse("file:///foo/😺").unwrap();
-        assert_eq!(url.prefix.as_ref(), "foo/%F0%9F%98%BA");
+        let err = ListingTableUrl::parse("file:///foo/😺").unwrap_err();
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/url.rs:318]: It seems very reasonable to treat urls like `file://foo`, as urls (rather than paths with a `file://` prefix)

File: datafusion/core/src/datasource/listing/url.rs (hunk 5 above)
Comment (alamb) [reply datafusion/core/src/datasource/listing/url.rs:145]: Would it be possible to update the documentation on `fn parse` to explain the percent escaping behavior (you could simply copy the very nice description from this PR perhaps)

**Review by alamb — APPROVED** [review]
Thank you @tustvold  -- this looks like a nice change to me. 

cc @unvalley  who contributed the original implementation

File: datafusion/core/src/datasource/listing/url.rs [hunk 7]
```diff
@@ -46,6 +45,16 @@ pub struct ListingTableUrl {
 impl ListingTableUrl {
     /// Parse a provided string as a `ListingTableUrl`
     ///
+    /// # URL Encoding
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/url.rs:48]: ❤️
