### PR TITLE
fix: find the right wider decimal datatype for comparison operation

### LINKED ISSUE #2232: Error precision and scale for decimal coercion in logic comparison
Is it worth checking somewhere what happens with different decimal scales?

Something like
```sql 
select * from decimal_simple where c1 >= CAST(0.00002 as Decimal(10,8))
```

I am not sure if the coercion to an appropriate decimal type is covered elsewhere

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/2200#discussion_r849775586_

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

Closes #2232 

For decimal with the comparison operation, we use the error algorithm to calculate the precision/scale.

Before: max(p1,p2),max(s1,s2)

Now: max(38,max(s1, s2) + max(p1-s1, p2-s2)), max(s1, s2, 38)

 # Rationale for this change

# What changes are included in this PR?

schema
```
CREATE EXTERNAL TABLE food (a DECIMAL(10,6), b double, c boolean) STORED AS CSV LOCATION 'aggregate_simple.csv';
```
Before this fix, we got the plan https://github.com/apache/arrow-datafusion/pull/2200#discussion_r850030108

After this fix, we got the right converted type in the filter expr
```
❯ explain select * from food where a >= CAST(0.00002 as Decimal(10,8));
+---------------+----------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                     |
+---------------+----------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: #food.a, #food.b, #food.c                                                                    |
|               |   Filter: #food.a >= Decimal128(Some(2000),10,8)                                                         |
|               |     TableScan: food projection=Some([0, 1, 2]), partial_filters=[#food.a >= Decimal128(Some(2000),10,8)] |
| physical_plan | ProjectionExec: expr=[a@0 as a, b@1 as b, c@2 as c]                                                      |
|               |   CoalesceBatchesExec: target_batch_size=4096                                                            |
|               |     FilterExec: CAST(a@0 AS Decimal(12, 8)) >= CAST(Some(2000),10,8 AS Decimal(12, 8))                   |
|               |       RepartitionExec: partitioning=RoundRobinBatch(16)                                                  |
|               |         CsvExec: files=[aggregate_simple.csv], has_header=false, limit=None, projection=[a, b, c]        |
|               |                                                                                                          |
+---------------+----------------------------------------------------------------------------------------------------------+

```

# Are there any user-facing changes?

cc @alamb

### CODE REVIEW

File: datafusion/physical-expr/src/coercion_rule/binary_rule.rs [hunk 1]
```diff
@@ -178,15 +178,30 @@ fn get_comparison_common_decimal_type(
...
-            let new_scale = s1.max(s2);
-            Some(DataType::Decimal(*new_precision, *new_scale))
+        (d1 @ DataType::Decimal(_, _), d2 @ DataType::Decimal(_, _)) => {
+            get_wider_decimal_type(d1, d2)
         }
         _ => None,
     }
 }
 
+// Find the winder decimal type when both types are decimal.
```
Comment (alamb) [inline datafusion/physical-expr/src/coercion_rule/binary_rule.rs:188]:
```suggestion
// Returns a `DataType::Decimal` that can store any value from either 
// `lhs_decimal_type` and `rhs_decimal_type`
```

File: datafusion/physical-expr/src/coercion_rule/binary_rule.rs [hunk 2]
```diff
@@ -178,15 +178,30 @@ fn get_comparison_common_decimal_type(
...
+// The result decimal type is (max(s1, s2) + max(p1-s1, p2-s2), max(s1, s2)).
+fn get_wider_decimal_type(
+    lhs_decimal_type: &DataType,
+    rhs_type: &DataType,
+) -> Option<DataType> {
+    match (lhs_decimal_type, rhs_type) {
+        (DataType::Decimal(p1, s1), DataType::Decimal(p2, s2)) => {
+            // max(s1, s2) + max(p1-s1, p2-s2), max(s1, s2)
+            let s = *s1.max(s2);
+            let range = (p1 - s1).max(p2 - s2);
```
Comment (alamb) [inline datafusion/physical-expr/src/coercion_rule/binary_rule.rs:198]: 👍  I see that the precision includes the scale 👍

File: datafusion/physical-expr/src/coercion_rule/binary_rule.rs [hunk 3]
```diff
@@ -557,15 +571,17 @@ mod tests {
...
             DataType::Decimal(20, 3),
             DataType::Decimal(20, 3),
-            DataType::Decimal(20, 3),
-            DataType::Decimal(20, 7),
-            DataType::Decimal(30, 15),
+            DataType::Decimal(23, 3),
+            DataType::Decimal(24, 7),
+            DataType::Decimal(32, 15),
             DataType::Decimal(38, 10),
+            DataType::Decimal(25, 8),
```
Comment (alamb) [inline datafusion/physical-expr/src/coercion_rule/binary_rule.rs:584]: 👍

**Review by alamb — APPROVED** [review]
Thanks @liukun4515

File: datafusion/physical-expr/src/coercion_rule/binary_rule.rs (hunk 3 above)
Comment (liukun4515) [reply datafusion/physical-expr/src/coercion_rule/binary_rule.rs:585]: This is inspired by your comments https://github.com/apache/arrow-datafusion/pull/2200#discussion_r850030108
Thanks
