### PR TITLE
Fix multicolumn parquet predicate pushdown (#4046)

### LINKED ISSUE #4046: Another Internal error when parquet predicate pushdown is enabled "Error evaluating filter predicate:
**Describe the bug**
DataFusion generates an error for some predicates when predicate pushdown is enabled. 

NOTE This is the same symptom as reported on https://github.com/apache/arrow-datafusion/issues/4006 but with a different predicate

NOTE that pushdown filtering is not enabled by default (as we are still working on it) so this issue will not likely affect users:

**To Reproduce**
1. Download data from [repro.zip](https://github.com/apache/arrow-datafusion/files/9902718/repro.zip)
2. Run datafusion CLI

The query run is
```sql
select count(*) from foo where request_method != 'GET' OR response_status = 400 OR service = 'backend';
```

I tested is using master at https://github.com/apache/arrow-datafusion/commit/35f786bb6ce33cbd58db3e16a46958b58f7676f4, which includes the fix for #4006 in https://github.com/apache/arrow-datafusion/commit/5cf090a13391501c0ce7707ac7a1e50e18517b79

```shell
$ git status
Your branch is up to date with 'apache/master'.

nothing to commit, working tree clean
$ git rev-parse HEAD
5cf090a13391501c0ce7707ac7a1e50e18517b79
```

**Expected behavior**
Same answer should be produced with and without row  filtering enabled. However, with row filtering an error is produced

```shell
datafusion-cli -f script.sql
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 53819           |
+-----------------+
1 row in set. Query took 0.006 seconds.
```

With it enabled:

```shell
DATAFUSION_EXECUTION_PARQUET_PUSHDOWN_FILTERS=true datafusion-cli -f script.sql
...
1 row in set. Query took 0.021 seconds.
ArrowError(ExternalError(Execution("Arrow error: External error: Arrow: underlying Arrow error: Compute error: Error evaluating filter predicate: Internal(\"Cannot evaluate binary expression NotEq with types UInt16 and Utf8\")")))
```

**Additional context**
Found by the test here https://github.com/apache/arrow-datafusion/pull/3976

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4046

# Rationale for this change

The first incarnation of this in #4021 computed the mapping from the projected schema to the file schema and not the other way round. For the case of two columns these are always the same thing and so it worked for the two column case, but more columns requires additional shenanigans.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/physical_plan/file_format/row_filter.rs [hunk 1]
```diff
@@ -278,6 +274,32 @@ impl<'a> ExprRewriter for FilterCandidateBuilder<'a> {
     }
 }
 
+/// Computes the projection required to go from the file's schema order to the projected
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/row_filter.rs:277]: Thank you for these comments

**Review by alamb — APPROVED** [review]
Thank you @tustvold 

This is all so familiar -- we have very similar logic in IOx in https://github.com/influxdata/influxdb_iox/blob/main/schema/src/sort.rs (though I don't see any obvious way to reuse it)

**Comment by alamb** [comment]
I verified this fixes the issue in my test harness in https://github.com/apache/arrow-datafusion/pull/3976 --  given this is a non controversial bug fix I am merging it in now to keep that project chugging along
