### PR TITLE
Custom window frame support extended to built-in window functions

### LINKED ISSUE #4076: Wrong result for FIRST_VALUE AND LAST_VALUE window functions
**Describe the bug**

Window functions `FIRST_VALUE` AND `LAST_VALUE` give wrong results when run with the query below 

```sql
SELECT
 FIRST_VALUE(c4) OVER(ORDER BY c9 ASC ROWS BETWEEN 10 PRECEDING AND 1 FOLLOWING) as first_value1,
 FIRST_VALUE(c4) OVER(ORDER BY c9 ASC ROWS BETWEEN 2 PRECEDING AND 3 FOLLOWING) as first_value2,
 LAST_VALUE(c4) OVER(ORDER BY c9 ASC ROWS BETWEEN 10 PRECEDING AND 1 FOLLOWING) as last_value1,
 LAST_VALUE(c4) OVER(ORDER BY c9 ASC ROWS BETWEEN 2 PRECEDING AND 3 FOLLOWING) as last_value2
 FROM aggregate_test_100
 ORDER BY c9
 LIMIT 5
```

**To Reproduce**

The test below reproduces the error 

```sql
#[tokio::test]
async fn test_window_frame_first_value_last_value_aggregate() -> Result<()> {
    let config = SessionConfig::new();
    let ctx = SessionContext::with_config(config);
    register_aggregate_csv(&ctx).await?;

    let sql = "SELECT
           FIRST_VALUE(c4) OVER(ORDER BY c9 ASC ROWS BETWEEN 10 PRECEDING AND 1 FOLLOWING) as first_value1,
           FIRST_VALUE(c4) OVER(ORDER BY c9 ASC ROWS BETWEEN 2 PRECEDING AND 3 FOLLOWING) as first_value2,
           LAST_VALUE(c4) OVER(ORDER BY c9 ASC ROWS BETWEEN 10 PRECEDING AND 1 FOLLOWING) as last_value1,
           LAST_VALUE(c4) OVER(ORDER BY c9 ASC ROWS BETWEEN 2 PRECEDING AND 3 FOLLOWING) as last_value2
           FROM aggregate_test_100
           ORDER BY c9
           LIMIT 5";

    let actual = execute_to_batches(&ctx, sql).await;
    let expected = vec![
        "+--------------+--------------+-------------+-------------+",
        "| first_value1 | first_value2 | last_value1 | last_value2 |",
        "+--------------+--------------+-------------+-------------+",
        "| -16110       | -16110       | 3917        | -1114       |",
        "| -16110       | -16110       | -16974      | 15673       |",
        "| -16110       | -16110       | -1114       | 13630       |",
        "| -16110       | 3917         | 15673       | -13217      |",
        "| -16110       | -16974       | 13630       | 20690       |",
        "+--------------+--------------+-------------+-------------+",
    ];
    assert_batches_eq!(expected, &actual);
    Ok(())
}
```

**Expected behavior**

I expect to get true result or get an error showing functionality is not supported

**Additional context**

N.A

### PR DESCRIPTION
**Pull request by mustafasrepo**
# Which issue does this PR close?

Closes #4076.

# Rationale for this change

With this change, we can now run built-in window functions with custom window frames such as queries in the form 

```sql
SELECT
     FIRST_VALUE(c4) OVER(ORDER BY c9) as first_value1,
     FIRST_VALUE(c4) OVER(ORDER BY c9) as first_value2,
     LAST_VALUE(c4) OVER(ORDER BY c9) as last_value1,
     LAST_VALUE(c4) OVER(ORDER BY c9) as last_value2
     FROM aggregate_test_100
     ORDER BY c9
     LIMIT 5
```

# What changes are included in this PR?

- We added range calculation support for Builtin-window functions FIRST_VALUE, LAST_VALUE, NTH_VALUE (For other window functions what is inside window frame isn’t important [https://www.postgresql.org/docs/current/functions-window.html](https://www.postgresql.org/docs/current/functions-window.html)). To be able to use range calculation code for both window functions and aggregate functions, range calculation code is moved from [aggregate.rs](https://github.com/synnada-ai/arrow-datafusion/blob/feature/builtin_window_running/datafusion/physical-expr/src/window/aggregate.rs) to [window_expr.rs](https://github.com/synnada-ai/arrow-datafusion/blob/feature/builtin_window_running/datafusion/physical-expr/src/window/window_expr.rs).
- Added tests for Built-in Window Functions

# Are there any user-facing changes?

N.A

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thanks @mustafasrepo  -- I don't have time to review this one today but I will put it on my queue for tomorrow

cc @Jimexist

**Comment by alamb** [comment]
I again ran out of time today but it is on my list for first thing tomorrow

File: datafusion/physical-expr/src/window/window_expr.rs [hunk 1]
```diff
@@ -110,4 +115,208 @@ pub trait WindowExpr: Send + Sync + Debug {
         sort_columns.extend(order_by_columns);
         Ok(sort_columns)
     }
+
+    /// We use start and end bounds to calculate current row's starting and ending range.
+    /// This function supports different modes, but we currently do not support window calculation for GROUPS inside window frames.
+    fn calculate_range(
```
Comment (alamb) [inline datafusion/physical-expr/src/window/window_expr.rs:121]: I find this logic to be very straightforward and easy to follow 👍

File: datafusion/physical-expr/src/window/window_expr.rs [hunk 2]
```diff
@@ -110,4 +115,208 @@ pub trait WindowExpr: Send + Sync + Debug {
...
+                        WindowFrameBound::Following(_) => {
+                            return Err(DataFusionError::Internal(
+                                "Rows should be Uint".to_string(),
+                            ))
+                        }
+                    };
+                    Ok((start, end))
+                }
+                WindowFrameUnits::Groups => Err(DataFusionError::NotImplemented(
+                    "Window frame for groups is not implemented".to_string(),
```
Comment (alamb) [inline datafusion/physical-expr/src/window/window_expr.rs:272]: 👍

**Review by alamb — APPROVED** [review]
Nice work @mustafasrepo  and @ozankabak 

I went through this code quite carefully and it is really nice and easy to follow 🏅 

In case it is not obvious to others reading this PR, this PR adds support for the ` ROWS BETWEEN 1 PRECEDING and 2 FOLLOWING` window clauses.

I tried it out using some simple data and postgres:

```sql
postgres=# create table foo as values (1,2), (3,4), (3,2), (2,1), (null, 0);
SELECT 5
postgres=# select first_value(column1) over (order by column2), last_value(column1) over (order by column2) from foo;
 first_value | last_value 
-------------+------------
             |           
             |          2
             |          3
             |          3
             |          3
(5 rows)
```

Before this change:
```sql
❯ select first_value(column1) over (order by column2 ROWS BETWEEN 1 PRECEDING and 2 FOLLOWING) from foo;
+--------------------------+
| FIRST_VALUE(foo.column1) |
+--------------------------+
|                          |
|                          |
|                          |
|                          |
|                          |
+--------------------------+
5 rows in set. Query took 0.003 seconds.
```

After this PR it gets the same answer as postgres 👍 

```sql
❯ select first_value(column1) over (order by column2 ROWS BETWEEN 1 PRECEDING and 2 FOLLOWING) from foo;
+--------------------------+
| FIRST_VALUE(foo.column1) |
+--------------------------+
|                          |
|                          |
| 2                        |
| 1                        |
| 3                        |
+--------------------------+
```

**Comment by alamb** [comment]
I'll plan to merge this PR tomorrow unless there are other comments raised.

**Comment by alamb** [comment]
Again, really nice work @mustafasrepo  and @ozankabak -- thank you very much
