### PR TITLE
Fix flaky `test_sort_fetch_memory_calculation` test

### LINKED ISSUE #7523: Intermittent Windows CI failure in "physical_plan::sorts::sort::tests::test_sort_fetch_memory_calculation"
### Describe the bug

CI tests begin failing like this on windows

https://github.com/apache/arrow-datafusion/actions/runs/6142807589/job/16665135902

```
---- physical_plan::sorts::sort::tests::test_sort_fetch_memory_calculation stdout ----
Error: Execution("Spawned Task error: IO error: The system cannot find the file specified. (os error 2)")
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

It appears to be intermittent

Here is a failure:
https://github.com/apache/arrow-datafusion/actions/runs/6136441131/job/16651296580

But then it passed on the following run 
https://github.com/apache/arrow-datafusion/actions/runs/6137534894/job/16653912130

An then it failed again on the next run
https://github.com/apache/arrow-datafusion/actions/runs/6142807589/job/16665135902

My suspicion is it is related to https://github.com/apache/arrow-datafusion/pull/7510 from @viirya  that started reporting spill file errors

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/7537,
Closes https://github.com/apache/arrow-datafusion/issues/7523

### CODE REVIEW

File: datafusion/core/src/physical_plan/sorts/sort.rs [hunk 1]
```diff
@@ -1097,7 +1097,7 @@ mod tests {
                 .with_fetch(fetch),
             );
 
-            let result = collect(sort_exec.clone(), task_ctx).await?;
+            let result = collect(sort_exec.clone(), task_ctx.clone()).await?;
```
Comment (viirya) [inline datafusion/core/src/physical_plan/sorts/sort.rs:1100]: `task_ctx` is simply moved `task_ctx`. Before the stream future is resolved, it is dropped early.

**Comment by viirya** [comment]
cc @alamb

**Review by alamb — APPROVED** [review]
Thanks @viirya  -- I agree this solves the problem for this test. Thank you 🙏 

However, it does seem like a real problem that the `ExternalSorter` can have its temporary files deleted out from under it. I filed https://github.com/apache/arrow-datafusion/issues/7546 to track that. 

See also https://github.com/apache/arrow-datafusion/pull/7538#issuecomment-1717480660 for more discussion
