### PR TITLE
minor: change some plan_err to exec_err

### LINKED ISSUE #7879: Maybe a misuse of `plan_err`
### Describe the bug

https://github.com/apache/arrow-datafusion/blob/37d6bf08c948418fe6c72d072d988c2875d81e02/datafusion/physical-expr/src/sort_expr.rs#L64-L73

This function (`PhysicalSortExpr::evaluate_to_sort_column()`) is in the execution phase. Errors at this stage should be `exec_err!` rather than `plan_err!`, right?

I also see other places have similar behavior and open this ticket to confirm. I'll submit a patch to change them if so.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by waynexia**
## Which issue does this PR close?

Closes #7879.

## Rationale for this change

I checked all `plan_err` occurrences under `physical-expr`. Some `plan_err` are preserved as I think they are not an execution phase error, though they are generated in this phase...

The `plan_err`'s meaning is not clear to me. I believe those occurrences under `physical-expr` are used to express the plan is incorrect. While other places may use it to throw an error generated in the planning phase.

## What changes are included in this PR?

change some `plan_err` to `exec_err`

## Are there any user-facing changes?

It's?

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/column.rs [hunk 1]
```diff
@@ -176,7 +176,7 @@ impl PhysicalExpr for UnKnownColumn {
 
     /// Evaluate the expression
     fn evaluate(&self, _batch: &RecordBatch) -> Result<ColumnarValue> {
-        plan_err!("UnKnownColumn::evaluate() should not be called")
+        exec_err!("UnKnownColumn::evaluate() should not be called")
```
Comment (2010YOUY01) [inline datafusion/physical-expr/src/expressions/column.rs:179]: If it means this line is unreachable, it should be Internal Error: if it's reached then there must be a bug in Datafusion (I remember it will print an error message to let the user file a GitHub issue for such error type)

File: datafusion/physical-expr/src/expressions/no_op.rs [hunk 2]
```diff
@@ -65,7 +65,7 @@ impl PhysicalExpr for NoOp {
     }
 
     fn evaluate(&self, _batch: &RecordBatch) -> Result<ColumnarValue> {
-        plan_err!("NoOp::evaluate() should not be called")
+        exec_err!("NoOp::evaluate() should not be called")
```
Comment (2010YOUY01) [inline datafusion/physical-expr/src/expressions/no_op.rs:68]: Seems also Internal Error 🤔

**Review by 2010YOUY01 — COMMENTED** [review]
Nice catch! 
In my understanding planning error is like a compile time error: it can't convert SQL into a logical plan during planning. It's possible to only be caught during execution (in `phys-expr` crate) due to implementation limitations.
It's a bit confusing and sometimes misused, we can add more comments near the error macros to make it clear.

File: datafusion/physical-expr/src/expressions/column.rs (hunk 1 above)
Comment (waynexia) [reply datafusion/physical-expr/src/expressions/column.rs:179]: Makes sense 👍

**Review by 2010YOUY01 — APPROVED** [review]
Looks good, thank you!

**Review by alamb — APPROVED** [review]
Thanks @waynexia  and @2010YOUY01
