### PR TITLE
Improve ApproxPercentileAccumulator merge api and fix bug

### LINKED ISSUE #10055: Fix approx_percentile_cont_with_weight update_batch bug
https://github.com/apache/arrow-datafusion/blob/5d70c32a9a4accf21e9f27ff5ed62666cbbcbe54/datafusion/physical-expr/src/aggregate/approx_percentile_cont_with_weight.rs#L137-L155

each call `self.approx_percentile_cont_accumulator.merge_digests(&digests); ` in `update_batch` will lose accumulator  own inner status by

https://github.com/apache/arrow-datafusion/blob/118eecdc8384805cae752dac0c4ccc768cc9629b/datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs#L286-L289

### PR DESCRIPTION
**Pull request by Ted-Jiang**
## Which issue does this PR close?

Closes #10055.

### CODE REVIEW

File: datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs [hunk 1]
```diff
@@ -284,7 +284,9 @@ impl ApproxPercentileAccumulator {
     }
 
     pub(crate) fn merge_digests(&mut self, digests: &[TDigest]) {
-        self.digest = TDigest::merge_digests(digests);
+        let mut input_digests = digests.to_vec();
```
Comment (Ted-Jiang) [inline datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs:287]: As one Accumulator call  merge() should not lose it inner status, this is not a good API desgion.

**Comment by Ted-Jiang** [comment]
@alamb @jychen7 PTAL

File: datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs (hunk 1 above)
Comment (andygrove) [reply datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs:287]: The change makes sense to me, but it is hard to review without a test that demonstrates the incorrect behavior. Would it be possible to add a unit test as part of this PR?

Comment (alamb) [reply datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs:287]: 100% agree we should add a test for this fix (otherwise we may break the behavior again in a subsequent refactoring, for example)

**Comment by alamb** [comment]
Marking as draft as I think this PR is waiting on a test

**Comment by Ted-Jiang** [comment]
add a test on digest merge [add test for accumulator merge_digests](https://github.com/apache/arrow-datafusion/pull/10056/commits/ac7dbd60997e52bc47e519886827cbdbaaf54c13)

File: datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs [hunk 2]
```diff
@@ -284,7 +284,9 @@ impl ApproxPercentileAccumulator {
...
+        input_digests.push(self.digest.clone());
```
Comment (alamb) [inline datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs:288]: I think it is possible to avoid these clones -- here is a proposal that targets this PR https://github.com/Ted-Jiang/arrow-datafusion/pull/118 to do so

**Review by alamb — APPROVED** [review]
Looks good to me -- thanks @Ted-Jiang 

I ran the test without the changes in this PR and verified it failed:

```

---- aggregate::approx_percentile_cont::tests::test_combine_approx_percentile_accumulator stdout ----
thread 'aggregate::approx_percentile_cont::tests::test_combine_approx_percentile_accumulator' panicked at datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs:471:9:
assertion `left == right` failed
  left: 50000.0
 right: 100000.0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    aggregate::approx_percentile_cont::tests::test_combine_approx_percentile_accumulator

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1574 filtered out; finished in 0.01s
```

I think this code introduces some unecessary cloning, but that can be removed using something like https://github.com/Ted-Jiang/arrow-datafusion/pull/118

**Review by andygrove — APPROVED** [review]
Thanks @Ted-Jiang
