### PR TITLE
fix `not(null)` with constant `null`

### LINKED ISSUE #1191: `not()` with NULL literals does not work: can't be evaluated because the expression's type is Utf8, not boolean
Reproducer:

```sql
> select not null;
Internal("NOT 'Literal { value: Utf8(NULL) }' can't be evaluated because the expression's type is Utf8, not boolean")

> select not(null);
Internal("NOT 'Literal { value: Utf8(NULL) }' can't be evaluated because the expression's type is Utf8, not boolean")

```

The correct output is `null`

I think the solution will likely be to teach `Expr::Not` about type coercion (as is done in `BinaryExpr` and function calls) once coercion knows about the null type (and that it can be cast to any other type). See https://github.com/apache/arrow-datafusion/issues/1184 for more details

### PR DESCRIPTION
**Pull request by WinkerDu**
# Which issue does this PR close?

Closes #1191.

 # Rationale for this change

df `not` expression can not take `NULL` like
```
> select not(null);
Internal("NOT 'Literal { value: Utf8(NULL) }' can't be evaluated because the expression's type is Utf8, not boolean")
```
the correct output should be `NULL`

# What changes are included in this PR?

`NotExpr` accepts  `NULL` input presented as `ScalarValue::Utf8(None)` 

# Are there any user-facing changes?

NO.

### CODE REVIEW

**Comment by WinkerDu** [comment]
cc @alamb @Dandandan @yjshen 
plz have a review, thank you.

**Comment by Ted-Jiang** [comment]
Is there any `Null` transform rule (doc) in datafusion?

**Comment by WinkerDu** [comment]
> rule

@Ted-Jiang I'm afraid there is not.
Maybe most of expressions (except for string expressions like `concat`, `concat_ws`, etc) should  return `NULL` when accept `NULL` IMO

File: datafusion/physical-expr/src/expressions/not.rs [hunk 1]
```diff
@@ -86,10 +86,29 @@ impl PhysicalExpr for NotExpr {
...
             ColumnarValue::Scalar(scalar) => {
-                let bool_value: bool = scalar.try_into()?;
-                Ok(ColumnarValue::Scalar(ScalarValue::Boolean(Some(
-                    !bool_value,
-                ))))
+                match scalar {
+                    ScalarValue::Utf8(utf8_val) => {
+                        // NOT op supports `NOT(NULL)` usage that returns `NULL` directly
+                        if utf8_val.is_none() {
+                            Ok(ColumnarValue::Scalar(ScalarValue::Utf8(None)))
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/not.rs:93]: I think this may be problematic as the output type of `not()` is supposed to be `Boolean`. Does returning

```suggestion
                            Ok(ColumnarValue::Scalar(ScalarValue::Boolean(None)))
```

work?

File: datafusion/physical-expr/src/expressions/not.rs [hunk 2]
```diff
@@ -104,14 +123,14 @@ pub fn not(
...
     input_schema: &Schema,
 ) -> Result<Arc<dyn PhysicalExpr>> {
-    let data_type = arg.data_type(input_schema)?;
-    if data_type != DataType::Boolean {
-        Err(DataFusionError::Internal(format!(
-            "NOT '{:?}' can't be evaluated because the expression's type is {:?}, not boolean",
+    match arg.data_type(input_schema)? {
+        // NULL is present as literal `ScalarValue::Utf8(None)` in logical expresion,
+        // to support `NOT(NULL)`, Utf8 arg is passed to `NotExpr` for further evaluate.
+        DataType::Boolean | DataType::Utf8 => Ok(Arc::new(NotExpr::new(arg))),
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/not.rs:129]: What about detecting if the input is a `ScalarValue` and if that `ScalarValue::is_null()` returns true (rather than checking for utf8`?

**Review by alamb — COMMENTED** [review]
Thank you for starting to take this on @WinkerDu ❤️ 

While the general purpose handling of null literals will likely be a more substantial change, I think this is a good step forward. If we can tighten up the checks a little I think we could merge this and improve things incrementally in follow on PRs.

**Review by alamb — COMMENTED** [review]
I wonder if it  would be helpful to add a test in `datafusion/core/tests/sql` somewhere to show a query like `SELECT null, not(null)` working?

File: datafusion/physical-expr/src/expressions/not.rs (hunk 1 above)
Comment (WinkerDu) [reply datafusion/physical-expr/src/expressions/not.rs:93]: @alamb OK, will fix it in follow on commit

File: datafusion/physical-expr/src/expressions/not.rs (hunk 2 above)
Comment (WinkerDu) [reply datafusion/physical-expr/src/expressions/not.rs]: @alamb OK, will fix it.

**Comment by WinkerDu** [comment]
> I wonder if it would be helpful to add a test in `datafusion/core/tests/sql` somewhere to show a query like `SELECT null, not(null)` working?

@alamb OK, will add more tests:
1. `SELECT not(true), not(false)` = `false, true`
2. `SELECT null, not(null)` = `NULL, NULL`
3. `SELECT NOT('hi')`, type check error would raise.

**Comment by WinkerDu** [comment]
@alamb PTAL, thank you.

File: datafusion/physical-expr/src/expressions/not.rs [hunk 3]
```diff
@@ -86,6 +86,16 @@ impl PhysicalExpr for NotExpr {
                 )))
             }
             ColumnarValue::Scalar(scalar) => {
+                if scalar.is_null() {
+                    return Ok(ColumnarValue::Scalar(ScalarValue::Boolean(None)));
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/not.rs:90]: 👍

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @WinkerDu

**Comment by WinkerDu** [comment]
@Dandandan @yjshen @xudong963 PTAL, thank you!

**Comment by WinkerDu** [comment]
cc @yjshen @xudong963 @liukun4515 @Dandandan  PTAL, thank you!

**Review by xudong963 — APPROVED** [review]
```sql
❯ select not null;
+----------------+
| NOT Utf8(NULL) |
+----------------+
|                |
+----------------+
1 row in set. Query took 0.003 seconds.
❯ select not(null);
+----------------+
| NOT Utf8(NULL) |
+----------------+
|                |
+----------------+
1 row in set. Query took 0.003 seconds.
```
I tested in my local, very good! @WinkerDu
