### PR TITLE
Remove allow unused imports from ballista-core, then fix all warnings

### LINKED ISSUE #1852: ballista-core allows unused imports
**Describe the bug**

The `ballista-core` crate [is allowing unused imports in the whole crate](https://github.com/apache/arrow-datafusion/blob/67fe623bd5882d0ce567e3aa3145a96fdf563443/ballista/rust/core/src/lib.rs#L19), so there are many `use` statements throughout that aren't actually needed and are showing dependencies where none exist.

I think people working on the crate since that annotation was added have been under the impression that they'd get warnings if there were unused imports, so there's a bunch of cleanup that hasn't happened.

**To Reproduce**

- Remove the use of an import from some code in the `ballista-core` crate, but not the `use` statement itself
- Run `cargo check`
- Observe no warnings about unused imports

**Expected behavior**

- I expected to get a warning when removing all uses of an imported item so that I know it can be cleaned up

### PR DESCRIPTION
**Pull request by carols10cents**
# Which issue does this PR close?

Closes #1852.

 # Rationale for this change

I think most Rust developers expect this lint to let them know when imports are no longer needed.

# What changes are included in this PR?

- I removed the `allow`
- I fixed all the warnings
- I ran rustfmt

# Are there any user-facing changes?

Nope!

### CODE REVIEW

File: ballista/rust/core/src/lib.rs [hunk 1]
```diff
@@ -16,7 +16,6 @@
 // under the License.
 
 #![doc = include_str!("../README.md")]
-#![allow(unused_imports)]
```
Comment (alamb) [inline ballista/rust/core/src/lib.rs:19]: 👍

**Review by houqp — APPROVED** [review]

**Review by Jimexist — APPROVED** [review]
