### PR TITLE
fix: add `ArrayAndElementAndOptionalIndex` for proper casting in `array_position`

### LINKED ISSUE #9093: Potentially Overly-Stringent Type Checking for `array_position`
### Describe the bug

This query: `SELECT array_position(a, 1) FROM test` will fail if `a` is a list of int32s, due to `Error: Plan("array_position received incompatible types: '[Int32, Int64]'.")`.

I understand that the value to find couldn't be found if `1` was actually a number bigger than an i32 could hold, but it seems to me this should try to work, then fail in that case.

### To Reproduce

This script should repro:

```rust
use std::sync::Arc;

use datafusion::{
    arrow::{
        array::{Array, Int32Builder, ListBuilder},
        datatypes::{Field, Fields, Schema},
    },
    datasource::MemTable,
    execution::context::SessionContext,
};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut list_builder = ListBuilder::new(Int32Builder::new());

    list_builder.append_value([Some(1), Some(2), Some(3)]);
    list_builder.append(true);

    let list_array = list_builder.finish();

    let data_type = list_array.data_type();

    let fields = Fields::from(vec![Field::new("a", data_type.clone(), true)]);
    let schema = Arc::new(Schema::new(fields));

    let record_batch = datafusion::arrow::record_batch::RecordBatch::try_new(
        schema.clone(),
        vec![Arc::new(list_array)],
    )?;

    let table = MemTable::try_new(schema, vec![vec![record_batch]])?;

    let ctx = SessionContext::new();
    ctx.register_table("test", Arc::new(table))?;

    let sql = "SELECT array_position(a, 1) FROM test";

    let plan = ctx.sql(sql).await?.collect().await?;

    Ok(())
}
```

### Expected behavior

I'd expect `array_position` to give a best effort to find the query value and fail if the passed value is incompatible due to its magnitude not immediately by its type.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tshauck**
## Which issue does this PR close?

Closes #9093

## Rationale for this change

Currently throws an error when doing `SELECT array_position(arrow_cast([1, 2, 3, 4, 5], 'List(Int32)'), 5)`, and after this PR it won't.

## What changes are included in this PR?

Change recommended in https://github.com/apache/arrow-datafusion/issues/9093#issuecomment-1920673541

## Are these changes tested?

Added an additional sql logic test that failed w/o the change, and doesn't fail w/ the change.

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by tshauck** [comment]
Ah, actually seeing that won't work in the case of the optional 3rd arg. Not sure if there's something built-in, but will look around.

**Comment by jayzhan211** [comment]
> Ah, actually seeing that won't work in the case of the optional 3rd arg for array position. Not sure if there's something built-in, but will look around. Or maybe add a `ArrayAndElementPlusArgs`? 🤔

No built-in signature, maybe we need `ArrayAndElementAndOptionalIndex` 😢

**Comment by tshauck** [comment]
That'd definitely be a better name... I'll let this PR sit for a couple of days in case there's a better idea or compelling reason not to do this in the first place, then'll see what `ArrayAndElementAndOptionalIndex` looks like.

**Comment by tshauck** [comment]
I think this is ready for a review. It adds `ArrayAndElementAndOptionalIndex` and associated code -- thanks!

File: datafusion/expr/src/type_coercion/functions.rs [hunk 1]
```diff
@@ -130,6 +130,31 @@ fn get_valid_types(
...
+    ) -> Result<Vec<Vec<DataType>>> {
+        // make sure there's at least 2 arguments
+        if !(current_types.len() == 2 || current_types.len() == 3) {
+            return Ok(vec![vec![]]);
+        }
+
+        let first_two_types = &current_types[0..2];
+        let valid_types = array_append_or_prepend_valid_types(first_two_types, true)?;
+
+        let valid_types_with_index = valid_types
```
Comment (jayzhan211) [inline datafusion/expr/src/type_coercion/functions.rs:144]: I think we can optionally append valid_types_with_index if the len is 3, otherwise just return here.

File: datafusion/expr/src/type_coercion/functions.rs [hunk 2]
```diff
@@ -130,6 +130,31 @@ fn get_valid_types(
             _ => Ok(vec![vec![]]),
         }
     }
+    fn array_append_and_optional_index(
```
Comment (jayzhan211) [inline datafusion/expr/src/type_coercion/functions.rs:133]: `array_element_and_optional_index` seems a better name

File: datafusion/sqllogictest/test_files/array.slt [hunk 3]
```diff
@@ -2603,6 +2603,16 @@ select array_position(arrow_cast(make_array([1, 2, 3], [4, 5, 6], [5, 5, 5], [4,
 ----
 2 2
 
+query I
+SELECT array_position(arrow_cast([5, 2, 3, 4, 5], 'List(Int32)'), 5)
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/array.slt:2607]: For the record, this test fails on main like this:

```
Error during planning: array_position received incompatible types: '[Int32, Int64]'.
```

File: datafusion/sqllogictest/test_files/array.slt [hunk 4]
```diff
@@ -2603,6 +2603,16 @@ select array_position(arrow_cast(make_array([1, 2, 3], [4, 5, 6], [5, 5, 5], [4,
...
+----
+1
+
+query I
+SELECT array_position(arrow_cast([5, 2, 3, 4, 5], 'List(Int32)'), 5, 2)
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/array.slt:2612]: Can we please add a few more tests:
1. For `LargeList`
2. Error cases (e.g. for types that are still not compatible like `array_position(arrow_cast([5, 2, 3, 4, 5], 'List(Int32)'), 'foo')`

**Review by alamb — COMMENTED** [review]
Thanks @tshauck  and @jayzhan211  -- this PR is looking very close

File: datafusion/sqllogictest/test_files/array.slt (hunk 4 above)
Comment (tshauck) [reply datafusion/sqllogictest/test_files/array.slt:2612]: Thanks for the feedback... `LargeList` is added and works as expected. For `array_position(arrow_cast([5, 2, 3, 4, 5], 'List(Int32)'), 'foo')`, this actually doesn't fail right now on this branch and returns NULL:

```
❯ SELECT array_position(arrow_cast([5, 2, 3, 4, 5], 'List(Int32)'), 'foo') IS NULL;
+----------------------------------------------------------------------------------------------+
| array_position(make_array(Int64(5),Int64(2),Int64(3),Int64(4),Int64(5)),Utf8("foo")) IS NULL |
+----------------------------------------------------------------------------------------------+
| true                                                                                         |
+----------------------------------------------------------------------------------------------+
1 row in set. Query took 0.004 seconds.
```

Because this PR is leveraging the append's casting functionality, this seems to be the current behavior on main for append:

```
arrow-datafusion/datafusion-cli main ➜ ./target/debug/datafusion-cli 
DataFusion CLI v35.0.0
❯ SELECT array_append(arrow_cast([5, 2, 3, 4, 5], 'List(Int32)'), 'foo');
+------------------------------------------------------------------------------------+
| array_append(make_array(Int64(5),Int64(2),Int64(3),Int64(4),Int64(5)),Utf8("foo")) |
+------------------------------------------------------------------------------------+
| [5, 2, 3, 4, 5, foo]                                                               |
+------------------------------------------------------------------------------------+
1 row in set. Query took 0.028 seconds.
```

I guess as I user I'd think if the array_append case would work, I'd also expect array_position to work like that. FWIW duckdb works for both array_append and `array_position([1,2,3], 'foo')` it just returns 0 rather than NULL.

File: datafusion/expr/src/type_coercion/functions.rs (hunk 1 above)
Comment (tshauck) [reply datafusion/expr/src/type_coercion/functions.rs:149]: Thanks! Addressed in [5086f31](https://github.com/apache/arrow-datafusion/pull/9233/commits/5086f3150b3533f7bc7bb3e60d8561a24b5f6797).

File: datafusion/expr/src/type_coercion/functions.rs (hunk 2 above)
Comment (tshauck) [reply datafusion/expr/src/type_coercion/functions.rs]: Also in [5086f31](https://github.com/apache/arrow-datafusion/pull/9233/commits/5086f3150b3533f7bc7bb3e60d8561a24b5f6797)

File: datafusion/sqllogictest/test_files/array.slt (hunk 4 above)
Comment (jayzhan211) [reply datafusion/sqllogictest/test_files/array.slt:2612]: For the second case, we return NULL which is compatible with Postgres behavior, so I think it is acceptable. You can just add the test case.

```
query I
select array_position(arrow_cast([5, 2, 3, 4, 5], 'List(Int32)'), 'foo')
----
NULL
```

Comment (tshauck) [reply datafusion/sqllogictest/test_files/array.slt:2612]: Sounds good... added in https://github.com/apache/arrow-datafusion/pull/9233/commits/4ec62896c0a87b1c20149832b68bb9757a605c77

**Review by jayzhan211 — APPROVED** [review]
LGTM

File: datafusion/sqllogictest/test_files/array.slt (hunk 4 above)
Comment (alamb) [reply datafusion/sqllogictest/test_files/array.slt:2612]: Thanks for adding the tests and doing the background research

**Review by alamb — APPROVED** [review]
Thanks @tshauck  and @jayzhan211  for the reviews 🙏
