### PR TITLE
Execute LogicalPlans after building for TPCH Benchmarks

### LINKED ISSUE #3273: Execute LogicalPlans after building for TPCH Benchmarks
**Describe the bug**
Currently, running Q15 fails when attempting to build the second (SELECT) portion of the overall query.

The error is similar to the following:

``` 
called `Result::unwrap()` on an `Err` value: Plan("'datafusion.public.revenue0' not found")
thread 'tests::run_q15' panicked at 'called `Result::unwrap()` on an `Err` value: Plan("'datafusion.public.revenue0' not found")', /home/dalto/projects/arrow-datafusion/datafusion/sql/src/planner.rs:161:31
```

**To Reproduce**
Run test run_q15 in `benchmarks/src/bin/tpch.rs`

**Expected behavior**
I expect the test to fail due to either #3266 or #3267

**Additional context**
The table names just before failure are:
```
schema table names: [
    "customer",
    "supplier",
    "region",
    "part",
    "orders",
    "nation",
    "lineitem",
    "partsupp",
]
```
I'm unsure of where views populate this table, if anyone else has knowledge here that would be great.

### PR DESCRIPTION
**Pull request by DaltonModlin**
- tpch.rs::benchmark_datafusion now executes LogicalPlan immediately after building
- tpch.rs::run_query now executes LogicalPlan immediately after building

Resolves #3273

# Which issue does this PR close?

Closes #3273

 # Rationale for this change
In the case of TPCH Query 15, a LogicalPlan is created for the first part of the query (creating the view), but a LogicalPlan for the second part of the query cannot be constructed before executing the first LogicalPlan. This is because the view cannot be found in the session context until its LogicalPlan is executed.

# What changes are included in this PR?
Update tpch.rs to generate a LogicalPlan, and then immediately execute it before generating the next LogicalPlan for both `tpch.rs::benchmark_datafusion` and `tpch.rs::run_query`

# Are there any user-facing changes?
No.

### CODE REVIEW

**Comment by DaltonModlin** [comment]
@andygrove @mingmwang Would one of you mind giving this a quick look? If we want to keep the output defined in the execute_query method, I could also rewrite the logic defined in create_logical_plans to create plans one at a time. Otherwise, I 
believe the create_logical_plans method and execute_query methods can both be removed.

File: benchmarks/src/bin/tpch.rs [hunk 1]
```diff
@@ -1022,9 +1024,10 @@ mod tests {
             ctx.register_table(table, Arc::new(provider))?;
         }
 
-        let plans = create_logical_plans(&ctx, n)?;
-        for plan in plans {
-            execute_query(&ctx, &plan, false).await?;
```
Comment (andygrove) [inline benchmarks/src/bin/tpch.rs:1027]: Why not just pass `sql` into this method instead of `plan`. Inside the method you can add a couple lines to get the plan from the SQL. This will retain the existing debug logging.

```
    let plan = ctx.sql(sql).await?;
    let plan = plan.to_logical_plan()?;
```

Comment (DaltonModlin) [reply benchmarks/src/bin/tpch.rs:1027]: I didn't realize how easily a DataFrame can provide a LogicalPlan - this looks great to me. Thanks!

**Review by andygrove — APPROVED** [review]
LGTM! Thanks @DaltonModlin

**Comment by alamb** [comment]
This is a nice solution -- thanks @DaltonModlin
