### PR TITLE
Always wrapping OnceAsync for the inner table side in NestedLoopJoinExec

### LINKED ISSUE #5022: NestedLoopJoin will panic when right child contains RepartitionExec
**Describe the bug**
When I work on #4866, I find some `NestedLoopJoin`s will panic.
```sql
# create tables -- t.csv is an empty file.
❯ CREATE EXTERNAL TABLE t1 (t1_id INT, t1_name text, t1_int INT) STORED AS CSV LOCATION 't.csv';
❯ CREATE EXTERNAL TABLE t2 (t2_id INT, t2_name text, t2_int INT) STORED AS CSV LOCATION 't.csv';
# target_partitions
> set datafusion.execution.target_partitions = 4;
```

```sql
❯ explain select * from t1 inner join t2 on t1.t1_id > t2.t2_id where t1.t1_id > 10 and t2.t2_int > 10;
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                  |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: t1.t1_id, t1.t1_name, t1.t1_int, t2.t2_id, t2.t2_name, t2.t2_int                                                                                          |
|               |   Inner Join:  Filter: t1.t1_id > t2.t2_id                                                                                                                            |
|               |     Filter: t1.t1_id > Int32(10)                                                                                                                                      |
|               |       TableScan: t1 projection=[t1_id, t1_name, t1_int], partial_filters=[t1.t1_id > Int32(10)]                                                                       |
|               |     Filter: t2.t2_int > Int32(10)                                                                                                                                     |
|               |       TableScan: t2 projection=[t2_id, t2_name, t2_int], partial_filters=[t2.t2_int > Int32(10)]                                                                      |
| physical_plan | ProjectionExec: expr=[t1_id@0 as t1_id, t1_name@1 as t1_name, t1_int@2 as t1_int, t2_id@3 as t2_id, t2_name@4 as t2_name, t2_int@5 as t2_int]                         |
|               |   NestedLoopJoinExec: join_type=Inner, filter=BinaryExpr { left: Column { name: "t1_id", index: 0 }, op: Gt, right: Column { name: "t2_id", index: 1 } }              |
|               |     CoalesceBatchesExec: target_batch_size=8192                                                                                                                       |
|               |       FilterExec: t1_id@0 > 10                                                                                                                                        |
|               |         RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1                                                                                          |
|               |           CsvExec: files={1 group: [[home/work/tools/datafusion-test-data/join-context/t1.csv]]}, has_header=false, limit=None, projection=[t1_id, t1_name, t1_int]   |
|               |     CoalescePartitionsExec                                                                                                                                            |
|               |       CoalesceBatchesExec: target_batch_size=8192                                                                                                                     |
|               |         FilterExec: t2_int@2 > 10                                                                                                                                     |
|               |           RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1 -- panic in RepartitionExec                                                                                          |
|               |             CsvExec: files={1 group: [[home/work/tools/datafusion-test-data/join-context/t1.csv]]}, has_header=false, limit=None, projection=[t2_id, t2_name, t2_int] |
|               |                                                                                                                                                                       |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

This sql will panic:
```sql
❯ select * from t1 inner join t2 on t1.t1_id > t2.t2_id where t1.t1_id > 10 and t2.t2_int > 10;
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
0 rows in set. Query took 0.015 seconds.
```

**To Reproduce**
See above.

**Expected behavior**
The join should work.

It seems the partition of right child may execute one more time in `NestedLoopJoin`, if it has multiple output partitions. It is ok in most time, but when meets `RepartitionExec` it will panic. 

  
**Additional context**

### PR DESCRIPTION
**Pull request by ygf11**
# Which issue does this PR close?

Closes #5022.

# Rationale for this change

For the nested loop join, the algorithm will be like:
```
  for out-row in outer-table
    for inner-row in inner-table
       check-join
```
We can see, the inner table will be visited many time.
In the current implemetion of `NestedLoopJoin`, the relationship between `inner/outer table` and `left/right table` is not fixed, it is decided by the required distribution:
* For (UnspecifiedDistribution, SinglePartition), right is the inner table side.
* For (SinglePartition, UnspecifiedDistribution), left table is the inner table side.

If the table is the inner side, we should wrap `OnceAsync` for it. There are two reasons:
* It is better to cache the result of a physical plan that has to be executed many times.
* Some physical plan can not be executed many time, like `RepartitionExec`.

The `NestedLoopJoinExec` always only load/cache(`OnceAsync`) the left table now, it is not correct(right table may be the inner table side), some queries(#5022) will panic for this reason. we should always load/cache the inner table data. 

# What changes are included in this PR?
1. Always load/cache(`OnceAsync`) the inner table data of nested loop join.
2. Use the separated logic to handle difference distributions(build-left and build-right). 
3. Remove redundant usage of `bitmap`, Left/LeftAnti/LeftSemi joins do not need it now.

# Are these changes tested?
Yes.

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 1]
```diff
@@ -479,6 +404,185 @@ impl NestedLoopJoinStream {
...
+            // the right_indices will not be used later for the `left semi` join
+            (left_indices, right_indices)
+        }
+        JoinType::LeftAnti => {
+            // need to remove the duplicated record in the left side
+            // get the anti index for the left side
+            let left_indices = get_anti_u64_indices(count_left_batch, &left_indices);
+            // the right_indices will not be used later for the `left anti` join
+            (left_indices, right_indices)
+        }
```
Comment (ygf11) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:535]: Left/LeftSemi/LeftAnti joins do not need on bitmap because the right is single partition.

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 2]
```diff
@@ -479,6 +404,185 @@ impl NestedLoopJoinStream {
...
+    filter: Option<&JoinFilter>,
+    column_indices: &[ColumnIndex],
+    schema: &Schema,
+    visited_left_side: &mut BooleanBufferBuilder,
+) -> Result<RecordBatch> {
+    let indices_result = (0..left_batch.num_rows())
+        .map(|left_row_index| {
+            build_join_indices(left_row_index, right_batch, left_batch, filter)
+        })
+        .collect::<Result<Vec<(UInt64Array, UInt32Array)>>>();
```
Comment (ygf11) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:454]: The type of join_indices is always (UInt64Array, UInt32Array) now no matter which side is single partition.


We can do better here: 
* Always use `UInt64Array` for the single partition side, and the other side is `UInt32Array`.

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 3]
```diff
@@ -186,37 +171,28 @@ impl ExecutionPlan for NestedLoopJoinExec {
...
-                // just one partition for the left side, and the first partition is all of data for left
-                load_left_specified_partition(0, self.left.clone(), context.clone())
-            })
+        let (outer_table, inner_table) = if left_is_build_side(self.join_type) {
+            // left must be single partition
+            let inner_table = self.inner_table.once(|| {
+                load_specified_partition_of_input(0, self.left.clone(), context.clone())
+            });
+            let outer_table = self.right.execute(partition, context)?;
+            (outer_table, inner_table)
```
Comment (ygf11) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:180]: The fix is here, always load/cache the build-side(inner table) data.

**Comment by alamb** [comment]
@liukun4515  as the author of NestedLookJoinExec do you have time to review this PR? 

also cc @mingmwang  and @jackwener as reviewers

**Comment by liukun4515** [comment]
> @liukun4515 as the author of NestedLookJoinExec do you have time to review this PR?
> 
> also cc @mingmwang and @jackwener as reviewers

I will take a look this PR today

File: datafusion/core/tests/sql/joins.rs [hunk 4]
```diff
@@ -3298,3 +3298,105 @@ async fn two_in_subquery_to_join_with_outer_filter() -> Result<()> {
 
     Ok(())
 }
+
+#[tokio::test]
+async fn right_as_inner_table_nested_loop_join() -> Result<()> {
+    let ctx = create_nested_loop_join_context()?;
+
+    let sql = "SELECT t1.t1_id, t2.t2_id
```
Comment (liukun4515) [inline datafusion/core/tests/sql/joins.rs:3306]: can we add comments to display the distribution required by the join type, like below

```
// Distribution: left is `UnspecifiedDistribution`, right is `SinglePartition`
```

File: datafusion/core/tests/sql/joins.rs [hunk 5]
```diff
@@ -3298,3 +3298,105 @@ async fn two_in_subquery_to_join_with_outer_filter() -> Result<()> {
...
+    assert_batches_sorted_eq!(expected, &results);
+
+    Ok(())
+}
+
+#[tokio::test]
+async fn left_as_inner_table_nested_loop_join1() -> Result<()> {
+    let ctx = create_nested_loop_join_context()?;
+
+    let sql = "SELECT t1.t1_id,t2.t2_id FROM (select t1_id from t1 where t1.t1_id > 22) as t1
```
Comment (liukun4515) [inline datafusion/core/tests/sql/joins.rs:3355]: same comment like: https://github.com/apache/arrow-datafusion/pull/5156/files#r1098307031

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 6]
```diff
@@ -304,6 +280,14 @@ async fn load_left_specified_partition(
     Ok(merged_batch)
 }
 
+// BuildLeft means the left relation is the single patrition side.
+// For full join, both side are single partition, so it is BuildLeft and BuildRight, treat it as BuildLeft.
+pub fn left_is_build_side(join_type: JoinType) -> bool {
```
Comment (liukun4515) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:285]: if I‘m right, this part is the most important insight for your fix.
If the left can be the single partition, we will iter the right table/partition
If the right is the single partition, we will iter the left table/partition

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 7]
```diff
@@ -352,24 +337,22 @@ fn build_join_indices(
 }
 
 impl NestedLoopJoinStream {
-    fn poll_next_impl(
+    // For Inner/Left/LeftSemi/LeftAnti joins, left is the single partition side.
```
Comment (liukun4515) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:340]: maybe we should add `full` join type.

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 8]
```diff
@@ -312,11 +296,11 @@ struct NestedLoopJoinStream {
     filter: Option<JoinFilter>,
     /// type of the join
     join_type: JoinType,
-    /// future for data from left side
-    left_fut: OnceFut<JoinLeftData>,
-    /// right
-    right: SendableRecordBatchStream,
-    /// There is nothing to process anymore and left side is processed in case of left/left semi/left anti/full join
+    // the outer table data of the nested loop join
```
Comment (liukun4515) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:299]: can we add more comments to indicate which side belonged to the outer table for the different `join type`.

Comment (ygf11) [reply datafusion/core/src/physical_plan/joins/nested_loop_join.rs:318]: Added the comments in the description of `NestedLoopJoinExec`.

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs (hunk 6 above)
Comment (ygf11) [reply datafusion/core/src/physical_plan/joins/nested_loop_join.rs:304]: Yes, the iter way is start from outer-table now. I think:
* It is more suitable for the meaning of nested loop join.
* We can optimize the data type of join_indices(not do in this pr). (using `UInt64Array` for inner-table data, and using `UInt32Array` for the outer-table data)

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs (hunk 7 above)
Comment (ygf11) [reply datafusion/core/src/physical_plan/joins/nested_loop_join.rs]: The meaning of the comment is opposite :rofl:.

When left is collected to a single partition, the join type should be `Right/RightSemi/RightAnti/Full`.

Fixed it.

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 9]
```diff
@@ -50,8 +50,27 @@ use crate::error::Result;
 use crate::execution::context::TaskContext;
 use crate::physical_plan::coalesce_batches::concat_batches;
 
-/// Data of the left side
+/// Data of the inner table side
 type JoinLeftData = RecordBatch;
+
+/// NestedLoopJoinExec executes partitions in parallel.
```
Comment (liukun4515) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:56]: 👍

**Review by liukun4515 — APPROVED** [review]
LGTM
@ygf11 thanks for you time to discuss this issue and fix it.

**Comment by liukun4515** [comment]
I want to left this pr for about one day, waiting for the opinions from other reviewer.

cc @jackwener

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs (hunk 6 above)
Comment (liukun4515) [reply datafusion/core/src/physical_plan/joins/nested_loop_join.rs:304]: > * We can optimize the data type of join_indices(not do in this pr). The indices type of inner-table should be `UInt64Array`, and  `UInt32Array` for the outer-table. Currently left table is `UInt64Array`, and right table is `UInt32Array`.

Hash join has the same issue.

Before this PR, the NLJ and hash join share some methods in the `utils`, such as `need_produce_result_in_final`.
But this PR breaks this, I want to refactor them, Do you have any ideas about that?

In the hash-join, we always build left table and cache the left table(single partition or multi partition), and the right data will be visited iteratively with the `INT32 ARRAY` as the index.

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs (hunk 7 above)
Comment (liukun4515) [reply datafusion/core/src/physical_plan/joins/nested_loop_join.rs]: > The meaning of the comment is opposite 🤣.
> 

yes, I also ignore this and just remember the missing type of `Full`.

Thanks for your remind and point out the mistake of the comments.

👍

> When left is collected to a single partition, the join type should be `Right/RightSemi/RightAnti/Full`.
> 
> Fixed it.

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 10]
```diff
@@ -50,9 +50,27 @@ use crate::error::Result;
...
+/// ```
+///
+/// One of the inputs will become inner table, and it is decided by the join type.
+/// Following is the relation table:
+///
+/// ```text
+///       JoinType                            Distribution                         Inner-table
+/// Inner/Left/LeftSemi/LeftAnti    (UnspecifiedDistribution, SinglePartition)       right
+/// Right/RightSemi/RightAnti/Full  (SinglePartition, UnspecifiedDistribution)       left
+/// ```
```
Comment (jackwener) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:73]: Good summary👍. May we use the `table` format.
```suggestion
/// | JoinType                       | Distribution (left, right)                 | Inner-table |
/// |--------------------------------|--------------------------------------------|-------------|
/// | Inner/Left/LeftSemi/LeftAnti   | (UnspecifiedDistribution, SinglePartition) | right       |
/// | Right/RightSemi/RightAnti/Full | (SinglePartition, UnspecifiedDistribution) | left        |
```

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 11]
```diff
@@ -312,11 +315,11 @@ struct NestedLoopJoinStream {
...
     /// type of the join
     join_type: JoinType,
-    /// future for data from left side
-    left_fut: OnceFut<JoinLeftData>,
-    /// right
-    right: SendableRecordBatchStream,
-    /// There is nothing to process anymore and left side is processed in case of left/left semi/left anti/full join
+    // the outer table data of the nested loop join
+    outer_table: SendableRecordBatchStream,
+    // the inner table data of the nested loop join
```
Comment (jackwener) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:320]: Small problem, should keep same format with other comments
```suggestion
    /// the inner table data of the nested loop join
```

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs [hunk 12]
```diff
@@ -312,11 +315,11 @@ struct NestedLoopJoinStream {
     filter: Option<JoinFilter>,
     /// type of the join
     join_type: JoinType,
-    /// future for data from left side
-    left_fut: OnceFut<JoinLeftData>,
-    /// right
-    right: SendableRecordBatchStream,
-    /// There is nothing to process anymore and left side is processed in case of left/left semi/left anti/full join
+    // the outer table data of the nested loop join
```
Comment (jackwener) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:318]:
```suggestion
    /// the outer table data of the nested loop join
```

Comment (jackwener) [inline datafusion/core/src/physical_plan/joins/nested_loop_join.rs:318]:
```suggestion
    /// the outer table data of the nested loop join
```

File: datafusion/core/src/physical_plan/joins/utils.rs [hunk 13]
```diff
@@ -917,6 +917,23 @@ pub(crate) fn get_anti_indices(
         .collect::<UInt32Array>()
 }
 
+/// Get unmatched and deduplicated indices
+pub(crate) fn get_anti_u64_indices(
```
Comment (jackwener) [inline datafusion/core/src/physical_plan/joins/utils.rs:921]: Could we merge `get_anti_u64_indices/get_semi_u64_indices` into one function?
Because they are almost the same except `(!bitmap.get_bit(idx))`

**Review by jackwener — APPROVED** [review]
LGTM, Thanks @ygf11.
I just leave some trivial review.

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs (hunk 6 above)
Comment (ygf11) [reply datafusion/core/src/physical_plan/joins/nested_loop_join.rs:303]: Current the indices type are fixed in the following functions, it is not enough, so we should make them more generic first.
```text
apply_join_filter_to_indices
build_batch_from_indices
adjust_indices_by_join_type
get_semi_indices
get_anti_indices
```

Then we can choose array corresponding the distribution(left and right), like:
* (Single, Unspecified) -> (UInt64Array, UInt32Array)
* (Unspecified, Single) -> (UInt32Array, UInt64Array)
* (UInt32Array, UInt32Array) --- `PartitionMode::Partitioned` for HashJoin 
* (UInt64Array, UInt64Array) --- Full join in NestedLoopJoin

File: datafusion/core/src/physical_plan/joins/utils.rs (hunk 13 above)
Comment (ygf11) [reply datafusion/core/src/physical_plan/joins/utils.rs:921]: Yes, we can merge these two.

Further more, `get_semi_indices` and `get_semi_u64_indices`(anti) can also be merged to one function with generic.

I think it is relative to comment https://github.com/apache/arrow-datafusion/pull/5156#discussion_r1100068420, and @liukun4515 plans to refactor them.

File: datafusion/core/src/physical_plan/joins/nested_loop_join.rs (hunk 10 above)
Comment (ygf11) [reply datafusion/core/src/physical_plan/joins/nested_loop_join.rs]: 👍

**Comment by jackwener** [comment]
Thanks @ygf11 @liukun4515
