### PR TITLE
fix divide by zero not throwing proper error for decimal

### LINKED ISSUE #3498: Dividing decimal type gives wrong error: "170141183460469231731687303715884105727 is too large to store in a Decimal128
**Describe the bug**
Dividing by Decimal value by zero results in 

```shell
cd datafusion-cli
cargo run
```

```
DataFusion CLI v12.0.0
❯ select cast(1 as int) / cast (0 as int);

ArrowError(DivideByZero)
❯ select cast(1 as double) / cast (0 as double);

ArrowError(DivideByZero)
❯ select cast(1 as decimal(10, 1)) / cast (0 as decimal(10, 1));

ArrowError(InvalidArgumentError("170141183460469231731687303715884105727 is too large to store in a Decimal128 of precision 10. Max is 9999999999"))
❯ 
```
**To Reproduce**
See above (divide a decimal number by zero)

**Expected behavior**
I expect an `DivideByZero` error:

```sql
❯ select cast(1 as decimal(10, 1)) / cast (0 as decimal(10, 1));

ArrowError(DivideByZero)
```

**Additional context**
Found while working on https://github.com/apache/arrow-datafusion/pull/3483

I am pretty sure the problem is in 

```rust
pub(crate) fn divide_decimal(
    left: &Decimal128Array,
    right: &Decimal128Array,
) -> Result<Decimal128Array> {
    let mul = 10_f64.powi(left.scale() as i32);
    let array = arith_decimal(left, right, |left, right| {
        let l_value = left as f64;
        let r_value = right as f64;
        let result = ((l_value / r_value) * mul) as i128;
        Ok(result)
    })?
```

Specifically, using floating point math to divide two floats and then casting to an int128 is where the `170141183460469231731687303715884105727` value comes from

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b5949eb324d9828a802aa11b4fa9d029

FYI @liukun4515

### PR DESCRIPTION
**Pull request by kmitchener**
# Which issue does this PR close?

Closes #3498 .

 # Rationale for this change

# What changes are included in this PR?

* Fixes the problem detailed in #3498
* Fixes the scalar version of same function
* Adds tests for both of those functions + coverage for modulus as well.

# Are there any user-facing changes?

Proper error

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs [hunk 1]
```diff
@@ -615,34 +621,66 @@ mod tests {
...
+        let right_decimal_array = create_decimal_array(&[Some(0)], 10, 1);
+
+        let _result = divide_decimal(&left_decimal_array, &right_decimal_array)
+            .expect_err("expecting DivideByZero error");
+        let _result = divide_decimal_scalar(&left_decimal_array, 0)
+            .expect_err("expecting DivideByZero error");
+        let _result = modulus_decimal(&left_decimal_array, &right_decimal_array)
+            .expect_err("expecting DivideByZero error");
+        let _result = modulus_decimal_scalar(&left_decimal_array, 0)
+            .expect_err("expecting DivideByZero error");
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs:684]: I think these tests would pass even on master without your code change


Perhaps we could add a check for the actual error ? With code similar to https://github.com/apache/arrow-datafusion/blob/331922036a23265084ab091fa2ab5c57da42c841/datafusion/core/tests/sql/information_schema.rs#L35-L42 ?

Comment (kmitchener) [reply datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs]: Hah, excellent! Thanks for the review, as always. Have updated with these changes.

**Review by alamb — APPROVED** [review]
I think it looks great. Thanks @kmitchener
