### PR TITLE
If statistics of column Max/Min value does not exists in parquet file, sent Min/Max to None

### LINKED ISSUE #2176: Ignored alias for columns with aggregate function and incorrect results when collecting statistics is enabled
**Describe the bug**
For parquet files, when `collect_stat` is set to `true`, alias for columns with aggregate function is ignored and for some data types null is returned. Current master (f0200b0a963bb817a6dad96a0b1fe0d06576004b).

**To Reproduce**

```rust
use std::{sync::Arc, thread};

use anyhow::Result;
use datafusion::{
    datasource::{
        file_format::parquet::{ParquetFormat, DEFAULT_PARQUET_EXTENSION},
        listing::ListingOptions,
    },
    logical_plan::{col, max},
    prelude::SessionContext,
};

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt::init();

    let threads = thread::available_parallelism()?.get();
    let options = ListingOptions {
        file_extension: DEFAULT_PARQUET_EXTENSION.to_owned(),
        format: Arc::new(ParquetFormat::default()),
        table_partition_cols: vec![],
        collect_stat: true,
        target_partitions: threads,
    };
    let path = "data.parquet";

    let ctx = SessionContext::new();
    ctx.register_listing_table("data", path, options, None)
        .await?;

    let data = ctx.table("data")?;

    data.show().await?;

    data.aggregate(vec![], vec![max(col("day")).alias("max_day")])?
        .show()
        .await?;

    data.aggregate(vec![], vec![max(col("txt")).alias("max_txt")])?
        .show()
        .await?;

    data.aggregate(vec![], vec![max(col("int")).alias("max_int")])?
        .show()
        .await?;

    Ok(())
}
```

```
+------------+-----+-----+
| day        | txt | int |
+------------+-----+-----+
| 2022-01-02 | abc | 11  |
| 2022-01-03 | abb | 10  |
| 2022-01-01 | bbb | 12  |
+------------+-----+-----+
+----------+
| MAX(day) |
+----------+
|          |
+----------+
+----------+
| MAX(txt) |
+----------+
|          |
+----------+
+----------+
| MAX(int) |
+----------+
| 12       |
+----------+
```

**Expected behavior**

Queries should return:

```
+------------+
| max_day    |
+------------+
| 2022-01-03 |
+------------+
+---------+
| max_txt |
+---------+
| bbb     |
+---------+
+---------+
| max_int |
+---------+
| 12      |
+---------+
```

[reproduction.zip](https://github.com/apache/arrow-datafusion/files/8441367/reproduction.zip)

### PR DESCRIPTION
**Pull request by AssHero**
# Which issue does this PR close?

Closes #2176 

 # Rationale for this change
If statistics of column Max/Min value does not exists in parquet file, set the Max/Min Accumulator to None.

# What changes are included in this PR?
set Max/Min Accumulator to None in parquet.rs and datasource/mod.rs

### CODE REVIEW

**Comment by Ted-Jiang** [comment]
@AssHero Thanks for your work! 👍  I will review this later today seems it's related to parquet static.

File: datafusion/core/src/datasource/file_format/parquet.rs [hunk 1]
```diff
@@ -344,6 +362,10 @@ fn fetch_statistics(
                             table_idx,
                             stats,
                         )
+                    } else {
+                        // If none statistics of current column exists, set the Max/Min Accumulator to None.
```
Comment (Ted-Jiang) [inline datafusion/core/src/datasource/file_format/parquet.rs:366]: https://github.com/apache/arrow-datafusion/blob/807b7a5f7eb858e9f7162e1f00ffeeedd0bf2050/datafusion/core/src/datasource/file_format/parquet.rs#L312
Here both `max_values` and `min_values ` are accumulator for all row_groups

Set  `max_values[i] = None` in loop `for row_group_meta in meta_data.row_groups() {}` assume that  we will no longer need this col static. So we need a short cut (No need read next row_group metadata for this col avoid set another value)

Comment (Ted-Jiang) [reply datafusion/core/src/datasource/file_format/parquet.rs:366]: If i miss something, plz tell me

Comment (AssHero) [reply datafusion/core/src/datasource/file_format/parquet.rs:366]: > If i miss something, plz tell me

Once max_values and min_values are set to none, even if the column statistics exists in next row_group, summarize_min_max will do nothing because the max_values and min_values are none.

File: datafusion/core/tests/sql/parquet.rs [hunk 2]
```diff
@@ -219,13 +219,76 @@ async fn schema_merge_ignores_metadata() {
...
+        let filename = "foo.parquet";
+        let path = table_path.join(&filename);
+        let file = fs::File::create(path).unwrap();
+        let mut writer =
+            ArrowWriter::try_new(file.try_clone().unwrap(), schema.clone(), None)
+                .unwrap();
+
+        // create mock record batch
+        let c1s = Arc::new(Int32Array::from_slice(&[1, 2, 3]));
+        let c2s = Arc::new(StringArray::from_slice(&["aaa", "bbb", "ccc"]));
```
Comment (alamb) [inline datafusion/core/tests/sql/parquet.rs:253]: Since there is code for other data types (e.g. int64) can you please also add such columns to this test?

**Review by alamb — COMMENTED** [review]
Thank you @AssHero 

To be honest, like @Ted-Jiang  I am puzzled about how the code in your PR works -- however my testing seems to show it does. 🦾 

If you could add tests for the other data types in the parquet format, I think this PR would basically ready to go. 


cc @Arvamer

File: datafusion/core/src/datasource/file_format/parquet.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/src/datasource/file_format/parquet.rs:366]: If there are no statistics in one of the row groups, I wonder if it is correct to keep going 🤔

Comment (AssHero) [reply datafusion/core/src/datasource/file_format/parquet.rs:366]: > If there are no statistics in one of the row groups, I wonder if it is correct to keep going 🤔

Are there any statistics for other columns in current row groups?

File: datafusion/core/tests/sql/parquet.rs (hunk 2 above)
Comment (AssHero) [reply datafusion/core/tests/sql/parquet.rs:253]: > Since there is code for other data types (e.g. int64) can you please also add such columns to this test?

Yes, i can add such columns in this test.

**Review by alamb — APPROVED** [review]
Thanks @AssHero

**Comment by alamb** [comment]
I retriggered the CI checks that were failing -- they appeared due to some network glitch

File: datafusion/core/src/datasource/file_format/parquet.rs (hunk 1 above)
Comment (Ted-Jiang) [reply datafusion/core/src/datasource/file_format/parquet.rs:366]: > > If i miss something, plz tell me
> 
> Once max_values and min_values are set to none, even if the column statistics exists in next row_group, summarize_min_max will do nothing because the max_values and min_values are none.
Ohh, thanks i will check later.

**Review by tustvold — APPROVED** [review]
This looks good to me, to check my understanding:

* We populate the accumulators regardless of types initially
* If the parquet statistics are not present or a different type from expected we need to clear them
* Otherwise the optimizer thinks the aggregated value is `NULL` and not lacking compatible statistics
