### PR TITLE
fix: build_timestamp_list data type mismatch

### LINKED ISSUE #7266: failed to convert millisecond timestamp scalar array to arrow array
### Describe the bug

As the title

### To Reproduce

```rust
    #[test]
    fn test_build_timestamp_millisecond_list() {
        let values = vec![ScalarValue::TimestampMillisecond(Some(1), None)];
        let ts_list = ScalarValue::new_list(
            Some(values),
            DataType::Timestamp(TimeUnit::Millisecond, None),
        );
        let list = ts_list.to_array_of_size(1);
        assert_eq!(1, list.len());
    }
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yukkit**
## Which issue does this PR close?

Closes #7266 .

### CODE REVIEW

**Review by waynexia — APPROVED** [review]
Looking good, thanks

File: datafusion/common/src/scalar.rs [hunk 1]
```diff
@@ -1663,13 +1663,13 @@ macro_rules! build_timestamp_list {
                         $SIZE
                     )
                 }
-                TimeUnit::Microsecond => build_values_list_tz!(
+                TimeUnit::Millisecond => build_values_list_tz!(
```
Comment (alamb) [inline datafusion/common/src/scalar.rs:1666]: nice find 👍
