### PR TITLE
[Minor] Update TCPDS tests, remove some #[ignore]d tests

### LINKED ISSUE #4794: Schema error creating logical/physical plan for TPC-DS q10, q35
**Describe the bug**

Creating a physical plan for q10 fails with:

```
Error: SchemaError(FieldNotFound { field: Column { relation: Some("web_sales"), name: "ws_bill_customer_sk" }, valid_fields: Some([Column { relation: Some("customer"), name: "c_customer_sk" }, Column { relation: Some("customer"), name: "c_current_cdemo_sk" }, Column { relation: Some("customer"), name: "c_current_addr_sk" }]) })
```

Here is the part of the logical plan that failed in `create_intial_plan`:

```
FAILED ON SubqueryAlias: c [c_customer_sk:Int32, c_current_cdemo_sk:Int32, c_current_addr_sk:Int32]
  LeftSemi Join: web_sales.ws_bill_customer_sk = c.c_customer_sk [c_customer_sk:Int32, c_current_cdemo_sk:Int32, c_current_addr_sk:Int32]
    TableScan: customer projection=[c_customer_sk, c_current_cdemo_sk, c_current_addr_sk] [c_customer_sk:Int32, c_current_cdemo_sk:Int32, c_current_addr_sk:Int32]
    Projection: web_sales.ws_bill_customer_sk [ws_bill_customer_sk:Int32]
      Inner Join: web_sales.ws_sold_date_sk = date_dim.d_date_sk [ws_sold_date_sk:Int32, ws_bill_customer_sk:Int32, d_date_sk:Int32]
        TableScan: web_sales projection=[ws_sold_date_sk, ws_bill_customer_sk] [ws_sold_date_sk:Int32, ws_bill_customer_sk:Int32]
        Projection: date_dim.d_date_sk [d_date_sk:Int32]
          Filter: CAST(date_dim.d_year AS Int64) = Int64(2002) AND CAST(date_dim.d_moy AS Int64)date_dim.d_moy >= Int64(4) AND CAST(date_dim.d_moy AS Int64)date_dim.d_moy <= Int64(7) [CAST(date_dim.d_moy AS Int64)date_dim.d_moy:Int64, d_date_sk:Int32, d_year:Int32]
            Projection: CAST(date_dim.d_moy AS Int64) AS CAST(date_dim.d_moy AS Int64)date_dim.d_moy, date_dim.d_date_sk, date_dim.d_year [CAST(date_dim.d_moy AS Int64)date_dim.d_moy:Int64, d_date_sk:Int32, d_year:Int32]
              TableScan: date_dim projection=[d_date_sk, d_year, d_moy] [d_date_sk:Int32, d_year:Int32, d_moy:Int32]

```

**To Reproduce**
Unigore test `tpcds_physical_q10`.

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by Dandandan**
## Which issue does this PR close?

Closes #4794

### CODE REVIEW

File: datafusion/core/tests/tpcds_planning.rs [hunk 1]
```diff
@@ -73,9 +73,6 @@ async fn tpcds_logical_q9() -> Result<()> {
     create_logical_plan(9).await
 }
 
-#[ignore]
```
Comment (Dandandan) [inline datafusion/core/tests/tpcds_planning.rs:76]: Q41 is the remaining failing logical plan test

**Review by alamb — APPROVED** [review]
👨‍🍳 👌
