### PR TITLE
Replace placeholders in ScalarSubqueries

### LINKED ISSUE #5215: Placeholder values are not replaced in ScalarSubqueries
**Describe the bug**

In a query such as:

```
SELECT id, age FROM person WHERE age = (select max(age) from person where id = $1)
```

The parameter `$1` will not be replaced even if a parameter is specified. 

**To Reproduce**

Run the query.

**Expected behavior**

The parameter is replaced with a value.

### PR DESCRIPTION
**Pull request by avantgardnerio**
# Which issue does this PR close?

Closes #5215.

# Rationale for this change

Described in issue.

# What changes are included in this PR?

Replace parameters in scalar subqueries.

# Are these changes tested?

With an integration test, yes.

# Are there any user-facing changes?

Scalar subqueries with parameters should work.

### CODE REVIEW

**Comment by avantgardnerio** [comment]
@NGA-TRAN PTAL as well.

File: datafusion/expr/src/logical_plan/plan.rs [hunk 1]
```diff
@@ -710,31 +711,39 @@ impl LogicalPlan {
...
+                        )));
+                    }
+                    // Replace the placeholder with the value
+                    Ok(Expr::Literal(value.clone()))
                 }
-                // Replace the placeholder with the value
-                Ok(Expr::Literal(value.clone()))
-            } else {
-                Ok(expr)
+                Expr::ScalarSubquery(qry) => {
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:739]: 👍 

I double checked this recursion doesn't happen automatically during the walk

https://github.com/apache/arrow-datafusion/blob/e222bd627b6e7974133364fed4600d74b4da6811/datafusion/expr/src/expr_rewriter.rs#L132


Though now that I write that, perhaps it should 🤔

**Review by alamb — APPROVED** [review]
LGTM -- thanks @avantgardnerio !
