### PR TITLE
refine decimal multiply, avoid cast to wider type

### LINKED ISSUE #6278: Significant performance downgrade to tpch-q1
### Describe the bug

Main branch:

Running benchmarks with the following options: DataFusionBenchmarkOpt { query: Some(1), debug: false, iterations: 3, partitions: 1, batch_size: 8192, path: "./parquet_data", file_format: "parquet", mem_table: false, output_path: None, disable_statistics: true }
Query 1 iteration 0 took 1716.3 ms and returned 4 rows
Query 1 iteration 1 took 1697.0 ms and returned 4 rows
Query 1 iteration 2 took 1694.3 ms and returned 4 rows
Query 1 avg time: 1702.52 ms

Branch 23 (Tag 23.0.0):

Running benchmarks with the following options: DataFusionBenchmarkOpt { query: Some(1), debug: false, iterations: 3, partitions: 1, batch_size: 8192, path: "./parquet_data", file_format: "parquet", mem_table: false, output_path: None, disable_statistics: true, enable_scheduler: false }
Query 1 iteration 0 took 864.2 ms and returned 4 rows
Query 1 iteration 1 took 842.0 ms and returned 4 rows
Query 1 iteration 2 took 838.7 ms and returned 4 rows
Query 1 avg time: 848.29 ms

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mingmwang**
# Which issue does this PR close?

Closes #6278, bring the performance back.

# Rationale for this change

For decimal multiply,  avoid casting to the wider type, decimals can multiply decimals directly.

# What changes are included in this PR?

# Are these changes tested?

Main branch:

Running benchmarks with the following options: DataFusionBenchmarkOpt { query: Some(1), debug: false, iterations: 3, partitions: 1, batch_size: 8192, path: "./parquet_data", file_format: "parquet", mem_table: false, output_path: None, disable_statistics: true }
Query 1 iteration 0 took 1716.3 ms and returned 4 rows
Query 1 iteration 1 took 1697.0 ms and returned 4 rows
Query 1 iteration 2 took 1694.3 ms and returned 4 rows
Query 1 avg time: 1702.52 ms

Branch 23 (Tag 23.0.0):

Running benchmarks with the following options: DataFusionBenchmarkOpt { query: Some(1), debug: false, iterations: 3, partitions: 1, batch_size: 8192, path: "./parquet_data", file_format: "parquet", mem_table: false, output_path: None, disable_statistics: true, enable_scheduler: false }
Query 1 iteration 0 took 864.2 ms and returned 4 rows
Query 1 iteration 1 took 842.0 ms and returned 4 rows
Query 1 iteration 2 took 838.7 ms and returned 4 rows
Query 1 avg time: 848.29 ms

This PR:

Running benchmarks with the following options: DataFusionBenchmarkOpt { query: Some(1), debug: false, iterations: 3, partitions: 1, batch_size: 8192, path: "./parquet_data", file_format: "parquet", mem_table: false, output_path: None, disable_statistics: true }
Query 1 iteration 0 took 539.1 ms and returned 4 rows
Query 1 iteration 1 took 514.7 ms and returned 4 rows
Query 1 iteration 2 took 511.1 ms and returned 4 rows
Query 1 avg time: 521.61 ms

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/expr/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -514,7 +514,7 @@ pub fn coercion_decimal_mathematics_type(
                 left_decimal_type,
                 right_decimal_type,
             ),
-            Operator::Multiply | Operator::Divide | Operator::Modulo => {
+            Operator::Divide | Operator::Modulo => {
                 get_wider_decimal_type(left_decimal_type, right_decimal_type)
             }
```
Comment (viirya) [inline datafusion/expr/src/type_coercion/binary.rs:519]: Huh? This is not correct...

Comment (mingmwang) [reply datafusion/expr/src/type_coercion/binary.rs:519]: Why decimal multiply decimal need to cast to a common wider type ? I do not change the get result type logic.
I think in the latest SparkSQL,  for decimal multiply, they do not cast to common wider type either.

**Comment by mingmwang** [comment]
```scala  
override def checkInputDataTypes(): TypeCheckResult = (left.dataType, right.dataType) match {
    case (l: DecimalType, r: DecimalType) if inputType.acceptsType(l) && inputType.acceptsType(r) =>
      // We allow decimal type inputs with different precision and scale, and use special formulas
      // to calculate the result precision and scale.
      TypeCheckResult.TypeCheckSuccess
    case _ => super.checkInputDataTypes()
  }
```

File: datafusion/expr/src/type_coercion/binary.rs (hunk 1 above)
Comment (mingmwang) [reply datafusion/expr/src/type_coercion/binary.rs:519]: My understanding is it just need to multiply the internal i128 integers, and cast the result back to the required result 
precision and scale.

**Comment by mingmwang** [comment]
And existing UTs show the result is correct.


```
query T
select arrow_typeof(c1*c5) from decimal_simple limit 1;
----
Decimal128(23, 13)


query R rowsort
select c1*c5 from decimal_simple;
----
0.00000000014
0.00000000033
0.00000000038
0.0000000005
0.00000000096
0.00000000105
0.0000000016
0.0000000016
0.00000000165
0.00000000176
0.00000000176
0.0000000026
0.0000000034
0.0000000039
0.000000005

```

File: datafusion/expr/src/type_coercion/binary.rs (hunk 1 above)
Comment (viirya) [reply datafusion/expr/src/type_coercion/binary.rs:519]: Hm, I remember this follows Spark decimal coercion rule to cast lhs/rhs to wider decimal type. I don't see Spark does this now for multiply.

Yea, you should be correct. We don't need to cast lhs/rhs to wider decimal type for multiply.

It's too late. Let me think it again tomorrow morning. 😄

Comment (viirya) [reply datafusion/expr/src/type_coercion/binary.rs:519]: Rethink about it. The issue is not to follow Spark or not in this. But for multiply, we don't need to align two integers.

**Review by viirya — APPROVED** [review]

**Comment by mingmwang** [comment]
> Good catch. This fixed the tpch-q1 performance. But for the root cause, we still need to improve the i256 operations. Otherwise for queries containing decimal array to array multiplying, it still suffers performance issue.

Yes, you are right. We still need to address the i256 operations performance, otherwise when it runs into the related logic, the performance is still not good.

**Review by liukun4515 — APPROVED** [review]

**Review by alamb — COMMENTED** [review]
Fixing a bug by deleting code ❤️ 
Screenshot 2023-05-12 at 7 16 23 AM

**Comment by viirya** [comment]
FYI, I'm going to improve the i256 operations at the upstream: https://github.com/apache/arrow-rs/pull/4303.
