### PR TITLE
fix: sql planner creates cross join instead of inner join from select predicates

### LINKED ISSUE #1293: sql planner creates cross join instead of inner join from select predicates
**Describe the bug**

tpch query 8 is taking a long time to execute in ballista because one of its table joins in the subquery is planned as a cross join.

**To Reproduce**

```
❯ create table part as select 1 as p_partkey;                                                                                                                                                
0 rows in set. Query took 0.003 seconds.                                                      
❯ create table lineitem as select 1 as l_partkey, 2 as l_suppkey;                             
0 rows in set. Query took 0.005 seconds.                                                      
❯ create table supplier as select 1 as s_suppkey;                                             
0 rows in set. Query took 0.002 seconds.                                                                                                
❯ explain select * from part, supplier, lineitem where p_partkey = l_partkey and s_suppkey = l_suppkey;                                                                                      
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------+                       
| plan_type     | plan                                                                                                                                                                                                                         |               
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------+  
| logical_plan  | Projection: #part.p_partkey, #supplier.s_suppkey, #lineitem.l_partkey, #lineitem.l_suppkey                                                                                 
                                                  | 
|               |   Join: #part.p_partkey = #lineitem.l_partkey, #supplier.s_suppkey = #lineitem.l_suppkey                                                                                   
                                                  |                                           
|               |     CrossJoin:                                                                                                                                                                                                               |                          
|               |       TableScan: part projection=Some([0])                                  
                                                  |                                                                                                                                          
|               |       TableScan: supplier projection=Some([0])                                                                                                                             
                                                  |                                                                                                                                          
|               |     TableScan: lineitem projection=Some([0, 1])      
```

**Expected behavior**

The query should be planned into the following join statements:

```
❯ explain select * from part join lineitem on l_partkey = p_partkey join supplier on s_suppkey = l_suppkey;
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                               |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: #part.p_partkey, #lineitem.l_partkey, #lineitem.l_suppkey, #supplier.s_suppkey                                                         |
|               |   Join: #lineitem.l_suppkey = #supplier.s_suppkey                                                                                                  |
|               |     Join: #part.p_partkey = #lineitem.l_partkey                                                                                                    |
|               |       TableScan: part projection=Some([0])                                                                                                         |
|               |       TableScan: lineitem projection=Some([0, 1])                                                                                                  |
|               |     TableScan: supplier projection=Some([0])      
```

**Additional context**

Recreated from https://github.com/apache/arrow-datafusion/issues/892

### PR DESCRIPTION
**Pull request by xudong963**
# Which issue does this PR close?

Closes #1293 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by xudong963** [comment]
```
❯ create table part as select 1 as p_partkey;                                                                                                                                                
0 rows in set. Query took 0.003 seconds.                                                      
❯ create table lineitem as select 1 as l_partkey, 2 as l_suppkey;                             
0 rows in set. Query took 0.005 seconds.                                                      
❯ create table supplier as select 1 as s_suppkey;                                             
0 rows in set. Query took 0.002 seconds.                                                                                                
❯ explain select * from part, supplier, lineitem where p_partkey = l_partkey and s_suppkey = l_suppkey; 

+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                               |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: #part.p_partkey, #lineitem.l_partkey, #lineitem.l_suppkey, #supplier.s_suppkey                                                         |
|               |   Join: #lineitem.l_suppkey = #supplier.s_suppkey                                                                                                  |
|               |     Join: #part.p_partkey = #lineitem.l_partkey                                                                                                    |
|               |       TableScan: part projection=Some([0])                                                                                                         |
|               |       TableScan: lineitem projection=Some([0, 1])                                                                                                  |
|               |     TableScan: supplier projection=Some([0])                                                                                                       |
```

**Comment by xudong963** [comment]
cc @houqp

**Comment by xudong963** [comment]
Currently, query 8 can't seem to pass due to `case ... when ... then ... else`, so I delete it to run the bench
```sql
select
    o_year,
from
    (
        select
            extract(year from o_orderdate) as o_year,
            l_extendedprice * (1 - l_discount) as volume,
            n2.n_name as nation
        from
            part,
            supplier,
            lineitem,
            orders,
            customer,
            nation n1,
            nation n2,
            region
        where
                p_partkey = l_partkey
          and s_suppkey = l_suppkey
          and l_orderkey = o_orderkey
          and o_custkey = c_custkey
          and c_nationkey = n1.n_nationkey
          and n1.n_regionkey = r_regionkey
          and r_name = 'AMERICA'
          and s_nationkey = n2.n_nationkey
          and o_orderdate between date '1995-01-01' and date '1996-12-31'
          and p_type = 'ECONOMY ANODIZED STEEL'
    ) as all_nations
group by
    o_year
order by
    o_year;
```

### master
```
➜  benchmarks git:(master) cargo run --release --bin tpch -- benchmark datafusion --iterations 3 --path ./data --format tbl --query 8 --batch-size 4096
  
Query 8 iteration 0 took 5047.0 ms
Query 8 iteration 1 took 4540.6 ms
Query 8 iteration 2 took 4552.0 ms
Query 8 avg time: 4713.19 ms
```
### xudong963:fix_cross_join
```
➜  benchmarks git:(fix_cross_join) ✗ cargo run --release --bin tpch -- benchmark datafusion --iterations 3 --path ./data -
Query 8 iteration 0 took 2823.8 ms
Query 8 iteration 1 took 2543.9 ms
Query 8 iteration 2 took 2442.7 ms
Query 8 avg time: 2603.48 ms
```

**Comment by alamb** [comment]
Thank you @xudong963  -- this looks very cool. I'll try and review it carefully tomorrow 👍

**Review by alamb — COMMENTED** [review]
Could you possibly provide some tests @xudong963 ? 

I don't fully understand how this works -- I was expecting to see code that basically applied an algebraic transformation on  predicates like:

```
(A AND X) OR (A and Y) OR (A and Z)
```

And rewrote them to 

```
A AND (X OR Y OR Z)
```

**Comment by xudong963** [comment]
> Could you possibly provide some tests @xudong963 ?

Sure.


> I was expecting to see code that basically applied an algebraic transformation on predicates like:

The ticket doesn't do the transformation.  It does the following thing.

First of all, let's see the example:
```
❯ create table part as select 1 as p_partkey;                                                                                                                                                
0 rows in set. Query took 0.003 seconds.                                                      
❯ create table lineitem as select 1 as l_partkey, 2 as l_suppkey;                             
0 rows in set. Query took 0.005 seconds.                                                      
❯ create table supplier as select 1 as s_suppkey;                                             
0 rows in set. Query took 0.002 seconds.                                                                                                
❯ explain select * from part, supplier, lineitem where p_partkey = l_partkey and s_suppkey = l_suppkey;                                                                                      
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------+                       
| plan_type     | plan                                                                                                                                                                                                                         |               
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------+  
| logical_plan  | Projection: #part.p_partkey, #supplier.s_suppkey, #lineitem.l_partkey, #lineitem.l_suppkey                                                                                 
                                                  | 
|               |   Join: #part.p_partkey = #lineitem.l_partkey, #supplier.s_suppkey = #lineitem.l_suppkey                                                                                   
                                                  |                                           
|               |     CrossJoin:                                                                                                                                                                                                               |                          
|               |       TableScan: part projection=Some([0])                                  
                                                  |                                                                                                                                          
|               |       TableScan: supplier projection=Some([0])                                                                                                                             
                                                  |                                                                                                                                          
|               |     TableScan: lineitem projection=Some([0, 1])      
```
https://github.com/apache/arrow-datafusion/blob/6f7b2d25fb75c843efed67fbd72d09b2c2d6c2eb/datafusion/src/sql/planner.rs#L718
In the `for` loop, at first, `left` is `part`, `right` is `supplier`, there is no `join key` between `part` and `right`, so result in `cross join` between `part` and `right`. It's heavy.

In the ticket, we can push `supplier` to `mut_plans`, after inner join `part` and `lineitem`, `supplier` can inner join with them.
```
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                               |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: #part.p_partkey, #lineitem.l_partkey, #lineitem.l_suppkey, #supplier.s_suppkey                                                         |
|               |   Join: #lineitem.l_suppkey = #supplier.s_suppkey                                                                                                  |
|               |     Join: #part.p_partkey = #lineitem.l_partkey                                                                                                    |
|               |       TableScan: part projection=Some([0])                                                                                                         |
|               |       TableScan: lineitem projection=Some([0, 1])                                                                                                  |
|               |     TableScan: supplier projection=Some([0])   
```

**Comment by pjmore** [comment]
@xudong963 This might be a bit nitpicky but this will enter an infinite loop if multiple cross joins are required for a plan. As an example, the following explain select will never finish:
```DataFusion CLI v5.1.0

❯ create table part as select 1 as p_partkey, 2 as p_partprice, 3 as p_partprice
_taxadded;
0 rows in set. Query took 0.036 seconds.
❯ create table lineitem as select 1 as l_itemkey;
0 rows in set. Query took 0.001 seconds.
❯ create table supplier as select 1 as s_suppkey;
0 rows in set.0 rows in set. Query took 0.001 seconds. Query took 0.001 seconds.
❯ explain select * from part,supplier,lineitem where p_partprice=p_partprice_tax
added;
```
In practice I'm not sure how much of a deal this is as it requires multiple cross joins with a filter that operates solely on a single table.

**Comment by xudong963** [comment]
> @xudong963 This might be a bit nitpicky but this will enter an infinite loop if multiple cross joins are required for a plan. As an example, the following explain select will never finish:
> 
> ```
> 
> ❯ create table part as select 1 as p_partkey, 2 as p_partprice, 3 as p_partprice
> _taxadded;
> 0 rows in set. Query took 0.036 seconds.
> ❯ create table lineitem as select 1 as l_itemkey;
> 0 rows in set. Query took 0.001 seconds.
> ❯ create table supplier as select 1 as s_suppkey;
> 0 rows in set.0 rows in set. Query took 0.001 seconds. Query took 0.001 seconds.
> ❯ explain select * from part,supplier,lineitem where p_partprice=p_partprice_tax
> added;
> ```
> 
> In practice I'm not sure how much of a deal this is as it requires multiple cross joins with a filter that operates solely on a single table.

Good catch, I think we should process the case because we can't guarantee what kind of queries the user will write 😁

**Comment by xudong963** [comment]
add tests and fix the extreme case. cc @alamb @pjmore

File: datafusion/src/sql/planner.rs [hunk 1]
```diff
@@ -3818,6 +3832,31 @@ mod tests {
...
+                                 \n    Join: #person.id = #lineitem.l_item_id\
+                                 \n      TableScan: person projection=None\
+                                 \n      TableScan: lineitem projection=None\
+                                 \n    TableScan: orders projection=None";
+        quick_test(sql, expected);
+    }
+
+    #[test]
+    fn cross_join_not_to_inner_join() {
+        let sql = "select person.id from person, orders, lineitem where person.id = person.age;";
```
Comment (xudong963) [inline datafusion/src/sql/planner.rs:3850]: here @pjmore

File: datafusion/src/logical_plan/plan.rs [hunk 2]
```diff
@@ -214,8 +220,14 @@ pub struct Extension {
     pub node: Arc<dyn UserDefinedLogicalNode + Send + Sync>,
 }
 
+impl PartialEq for Extension {
+    fn eq(&self, _other: &Self) -> bool {
+        todo!()
```
Comment (xudong963) [inline datafusion/src/logical_plan/plan.rs:225]: I'm not sure if need to do something.

File: datafusion/src/sql/planner.rs [hunk 3]
```diff
@@ -731,20 +732,33 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
                         }
                     }
                     if join_keys.is_empty() {
-                        left =
-                            LogicalPlanBuilder::from(left).cross_join(right)?.build()?;
+                        /// check [1..idx] if contains current plan to avoid infinite loop
```
Comment (xudong963) [inline datafusion/src/sql/planner.rs:735]:
```suggestion
                        // check [1..idx] if contains current plan to avoid infinite loop
```

File: datafusion/src/sql/planner.rs [hunk 4]
```diff
@@ -731,20 +732,33 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
-                            LogicalPlanBuilder::from(left).cross_join(right)?.build()?;
+                        // check [1..idx] if contains current plan to avoid infinite loop
+                        if mut_plans[1..idx].contains(&mut_plans[idx])
+                            || idx == mut_plans.len() - 1
+                        {
+                            left = LogicalPlanBuilder::from(left)
+                                .cross_join(&mut_plans[idx])?
+                                .build()?;
+                        } else {
+                            mut_plans.push(mut_plans[idx].clone());
```
Comment (houqp) [inline datafusion/src/sql/planner.rs:743]: could be helpful to add a simple comment here to explain why pushing the same plan to the end helps. my understanding is we want to retry the join key matching after we go through all the plan once just in case this plan can be indirectly joined with left through other plans.

**Review by houqp — APPROVED** [review]
LGTM, nice performance gain @xudong963 :+1:

**Comment by houqp** [comment]
As a future follow up task, I think there is value in handling this plan rewrite in our optimizer layer so dataframe users can benefit from it as well.

File: datafusion/src/sql/planner.rs (hunk 4 above)
Comment (xudong963) [reply datafusion/src/sql/planner.rs:743]: Yes, you understand exactly right 👍

File: datafusion/src/sql/planner.rs [hunk 5]
```diff
@@ -731,20 +732,33 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
                         }
                     }
                     if join_keys.is_empty() {
-                        left =
-                            LogicalPlanBuilder::from(left).cross_join(right)?.build()?;
+                        // check [1..idx] if contains current plan to avoid infinite loop
+                        if mut_plans[1..idx].contains(&mut_plans[idx])
```
Comment (xudong963) [inline datafusion/src/sql/planner.rs:736]: Here, we use `contains()` which requests `Logical Plan` implement `PartialEq` trait  @houqp

**Comment by alamb** [comment]
> As a future follow up task, I think there is value in handling this plan rewrite in our optimizer layer so dataframe API users can benefit from it as well.

@houqp  what do you have in mind? 

With the `dataframe` API users can't create implicit joins the way you can with a sql query like `SELECT .. FROM foo, bar`;

The only thing I can think of would be to extend `FilterPushdown` in a way that would try and push down `column = column` type expressions from `Filter` nodes into `Join` nodes? 

So like

```
Filter(a = b)
  Join (Cross)
    TableScan A
    TableScan B
```

To 
```
  Join (Inner) exprs: {a = b}
    TableScan A
    TableScan B
```

And 

```
Filter(a = b)
  Join (Inner) exprs: {a2 = b2}
    TableScan A
    TableScan B
```

```
Filter(a = b)
  Join (Inner) exprs: {a2 = b2 AND a = b}
    TableScan A
    TableScan B
```

**Review by alamb — COMMENTED** [review]
Thank you @xudong963  -- this is looking much better. 

I am a little worried about having to implement `PartialEq` for all nodes -- I think we might be able to avoid doing so with a worklist type algorithm. 

Here is a sketch of doing so https://github.com/xudong963/arrow-datafusion/pull/2 as perhaps some inspiration

File: datafusion/src/sql/planner.rs (hunk 5 above)
Comment (houqp) [reply datafusion/src/sql/planner.rs:736]: Got it, I am thinking that we might be able to avoid this extra PartialEq and contains check overhead by breaking this up into two loops:

1. extract the loop logic into its own function
2. first loop through `plans` once, for each plan that doesn't have join key matches, we push its index in `plans` into a retry vector
3. second loop to go through the retry vector

This way, we can guarantee every plan in the original `plans` vector is evaluated at most twice without getting into an infinite loop while avoiding particleq compare and clones. What do you think?

Comment (houqp) [reply datafusion/src/sql/planner.rs:736]: Oh never mind, just noticed @alamb already implemented a similar approach at https://github.com/xudong963/arrow-datafusion/pull/2 :D nice!

**Comment by houqp** [comment]
> The only thing I can think of would be to extend FilterPushdown in a way that would try and push down column = column type expressions from Filter nodes into Join nodes?

Yes, this is exactly what I have in mind. With this optimizer rule, the sql planner can just naively plan these types of queries as cross joins and let the optimizer rewrite them into inner joins whenever applicable.

File: datafusion/src/sql/planner.rs (hunk 5 above)
Comment (xudong963) [reply datafusion/src/sql/planner.rs:736]: Yeah, I'll look it carefully! 👍

File: datafusion/src/logical_plan/plan.rs (hunk 2 above)
Comment (xudong963) [reply datafusion/src/logical_plan/plan.rs:225]: > For the future, I think you can change
`PartialEq` isn't auto-trait,  so it can't be used as additional trait in a trait object

**Comment by xudong963** [comment]
Thanks, @alamb ❤️. I look at https://github.com/xudong963/arrow-datafusion/pull/2 carefully and I think the implementation is very elegant, so I directly use it with only minor fixes.

File: datafusion/src/sql/planner.rs [hunk 6]
```diff
@@ -714,33 +713,79 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
-                            join_keys.push((l.clone(), r.clone()));
-                        } else if left_schema.field_from_column(r).is_ok()
-                            && right_schema.field_from_column(l).is_ok()
-                        {
-                            join_keys.push((r.clone(), l.clone()));
+
+                    // Search all remaining plans for the next to
+                    // join. Prefer the first one that has a join
+                    // predicate in the predicate lists
+                    let plan_with_idx = remaining_plans.iter().enumerate().find(|(_idx, plan)| {
```
Comment (xudong963) [inline datafusion/src/sql/planner.rs:731]: Here, I use `plan_with_idx` to replace `idx`

File: datafusion/src/sql/planner.rs [hunk 7]
```diff
@@ -714,33 +713,79 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
+                        !join_keys.is_empty()
+                    });
+
+                    // If we did not find join keys, either there are
+                    // no more plans, or we can't find any plans that
+                    // can be joined with predicates
                     if join_keys.is_empty() {
-                        left =
-                            LogicalPlanBuilder::from(left).cross_join(right)?.build()?;
+                        assert!(plan_with_idx.is_none());
```
Comment (xudong963) [inline datafusion/src/sql/planner.rs:761]: Very tight！

**Review by xudong963 — COMMENTED** [review]
Thanks again, @alamb PTAL. BTW, the annotation is very nice, taking you as the model!

**Review by alamb — APPROVED** [review]
Looks good to me (though I am somewhat biased :)) @houqp  would you like to take another look / review ?

**Comment by houqp** [comment]
Nice work @xudong963 @alamb !
