### PR TITLE
Move subquery alias assignment onto rules

### LINKED ISSUE #3437: panic at `attempt to multiply with overflow` when doing math on Decimal128 columns
**Describe the bug**

When changing the TPC-H tests to use Decimals, getting panics with this error:
```
thread 'sql::subqueries::tpch_q17_correlated' panicked at 'attempt to multiply with overflow', datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs:359:61
```
**To Reproduce**

**Expected behavior**

**Additional context**

See #3393 for additional examples where the overflow happens on benchmark queries.

### LINKED ISSUE #3791: Optimizer casts decimals to different values on different platforms
**Describe the bug**

See ignored test in https://github.com/apache/arrow-datafusion/pull/3790

**To Reproduce**

````
    /// This query produces different plans depending on operating system
    /// Linux:   Decimal128(Some(7000000000000000195487369212723200),38,33)
    /// Windows: Decimal128(Some(6999999999999999042565864605876224),38,33)
    #[tokio::test]
    #[ignore]
    async fn q17_expected_plan() -> Result<()> {
        expected_plan(17).await
    }
```

**Expected behavior**
Is this expected?

**Additional context**
None

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3437
Closes #3791

(although these were actually fixed by https://github.com/apache/arrow-datafusion/pull/4038)

# Rationale for this change

Having mutable state associated with `OptimizerConfig` complicates implementing it for `SessionState`. I originally hoped to implement `OptimizerConfig` for `DataFrame`, but this would have required churning all the planning machinery and so I decided against this.  

There is one implication potentially worth highlighting with this change, as the state is now associated with the `OptimizerRule` and not an `OptimizerContext` created for the call to `SessionState::optimize`, state will now bleed across calls whereas it previously wouldn't. In some ways this is better, as previously calling `optimize` twice could theoretically result in an alias collision, but I thought it worth highlighting.

# What changes are included in this PR?

Move alias state from `OptimizerConfig` onto the individual rules

# Are these changes tested?

# Are there any user-facing changes?

Yes, queries will get potentially different aliases assigned to them by the optimizer.

### CODE REVIEW

File: benchmarks/src/bin/tpch.rs [hunk 1]
```diff
@@ -596,17 +596,7 @@ mod tests {
...
-    ///
-    /// `sum(l_extendedprice) / 7.0 as avg_yearly`
-    ///
-    /// Linux:   Decimal128(Some(7000000000000000195487369212723200),38,33)
-    /// Windows: Decimal128(Some(6999999999999999042565864605876224),38,33)
-    ///
-    /// See https://github.com/apache/arrow-datafusion/issues/3791
-    #[tokio::test]
-    #[ignore]
+    #[tokio::test]
```
Comment (tustvold) [inline benchmarks/src/bin/tpch.rs:599]: This was fixed by #4038

File: datafusion/optimizer/src/scalar_subquery_to_join.rs [hunk 2]
```diff
@@ -242,7 +245,7 @@ fn optimize_scalar(
     }
 
     // Only operate if one column is present and the other closed upon from outside scope
-    let subqry_alias = format!("__sq_{}", config.next_id());
+    let subqry_alias = alias.next("__scalar_sq");
```
Comment (tustvold) [inline datafusion/optimizer/src/scalar_subquery_to_join.rs:248]: I debated passing an `Arc<AliasGenerator>` into each of the rules, this created a fair amount of churn, and it is easier for the rules to just assign a unique prefix. As an added bonus it highlights where the alias came from, which is nice I guess

File: datafusion/core/tests/sql/subqueries.rs [hunk 3]
```diff
@@ -230,7 +230,6 @@ async fn tpch_q4_correlated() -> Result<()> {
     Ok(())
 }
 
-#[ignore] // https://github.com/apache/arrow-datafusion/issues/3437
```
Comment (tustvold) [inline datafusion/core/tests/sql/subqueries.rs:233]: This query was also fixed by #4038

File: datafusion/core/tests/sql/subqueries.rs [hunk 4]
```diff
@@ -255,17 +254,18 @@ async fn tpch_q17_correlated() -> Result<()> {
     let dataframe = ctx.sql(sql).await.unwrap();
     let plan = dataframe.into_optimized_plan().unwrap();
     let actual = format!("{}", plan.display_indent());
-    let expected = r#"Projection: CAST(SUM(lineitem.l_extendedprice) AS Decimal128(38, 33)) / CAST(Float64(7) AS Decimal128(38, 33)) AS avg_yearly
+    let expected = r#"Projection: CAST(SUM(lineitem.l_extendedprice) AS Float64) / Float64(7) AS avg_yearly
```
Comment (tustvold) [inline datafusion/core/tests/sql/subqueries.rs:257]: This is the fix from #4038

File: datafusion/core/tests/sql/subqueries.rs [hunk 5]
```diff
@@ -275,7 +275,7 @@ async fn tpch_q17_correlated() -> Result<()> {
         "+--------------------+",
         "| avg_yearly         |",
         "+--------------------+",
-        "| 1901.3714285714286 |",
+        "| 190.13714285714286 |",
```
Comment (tustvold) [inline datafusion/core/tests/sql/subqueries.rs:278]: I've not independently verified this result, but I believe @andygrove added CI to check the TPCH queries are returning the correct results, so I think this was just out of date

File: benchmarks/src/bin/tpch.rs (hunk 1 above)
Comment (alamb) [reply benchmarks/src/bin/tpch.rs:599]: cc @liukun4515

**Review by alamb — COMMENTED** [review]
I like the basic idea in this PR

One thing I wonder about is what happens if the same rule is run multiple times? Won't the subsequent runs potentially reuse the same aliases?

**Review by xudong963 — APPROVED** [review]
The change makes sense to me.

**Comment by tustvold** [comment]
Closing in favour of #4771

File: benchmarks/src/bin/tpch.rs (hunk 1 above)
Comment (liukun4515) [reply benchmarks/src/bin/tpch.rs:599]: make sense to me

**Comment by tustvold** [comment]
> One thing I wonder about is what happens if the same rule is run multiple times?

This will be fine, there is a potential collision if the same rule appears multiple times in the same list of optimizers, i.e. something like


```
let rules: Vec<Arc<dyn OptimizerRule + Sync + Send>> = vec![
    Arc::new(DecorrelateWhereIn::new()),
    Arc::new(ScalarSubqueryToJoin::new()),
    Arc::new(ScalarSubqueryToJoin::new()),
    ...
];
```

However, this doesn't occur in practice and could easily be worked around by using

```
let subquery = Arc::new(ScalarSubqueryToJoin::new());
let rules: Vec<Arc<dyn OptimizerRule + Sync + Send>> = vec![
    Arc::new(DecorrelateWhereIn::new()),
    subquery.clone(),
    subquery,
    ...
];
```

**Comment by mingmwang** [comment]
One question regarding the Subquery Alias generation logic:

Why does the `InSubquery` generate a Subquery Alias, but the  `Exists`  Subquery does not ?

**Comment by mingmwang** [comment]
@jackwener 
Do you have some idea ?

**Comment by jackwener** [comment]
```sql
#[test]
fn exists_subquery() {
    let sql = "SELECT id FROM person p WHERE EXISTS \
            (SELECT first_name FROM person \
            WHERE last_name = p.last_name \
            AND state = p.state)";

    let expected = "Projection: p.id\
        \n  Filter: EXISTS (<subquery>)\
        \n    Subquery:\
        \n      Projection: person.first_name\
        \n        Filter: person.last_name = p.last_name AND person.state = p.state\
        \n          TableScan: person\
        \n    SubqueryAlias: p\
        \n      TableScan: person";
    quick_test(sql, expected);
}
```

looks like `exists` subquery also can  generate a Subquery Alias. @mingmwang

**Comment by mingmwang** [comment]
Yes, but after the logical optimization, the `SubqueryAlias` is gone.

**Comment by jackwener** [comment]
> Yes, but after the logical optimization, the `SubqueryAlias` is gone.

Because `optimize_where_in` have param `AliasGenerator` but `optimize_exists` don't.

**Comment by jackwener** [comment]
@ygf11 In fact, `subquery alias` doesn't actually work, we can eliminate it, and I'm getting ready to do it.

You shouldn't see `Optimized Logical Plan`, which have eliminated `subquery alias`.

`subquery alias` exist both in `exist-subquery` (Existential Test subquery) and `in-subquery` (Quantified Comparision subquery)

```sql
spark-sql> explain extended select * from hudi_test where uuid in (select uuid from hudi_test);

== Analyzed Logical Plan ==
_hoodie_commit_time: string, _hoodie_commit_seqno: string, _hoodie_record_key: string, _hoodie_partition_path: string, _hoodie_file_name: string, uuid: int, name: string, price: double
Project [_hoodie_commit_time#37, _hoodie_commit_seqno#38, _hoodie_record_key#39, _hoodie_partition_path#40, _hoodie_file_name#41, uuid#42, name#43, price#44]
+- Filter uuid#42 IN (list#93 [])
   :  +- Project [uuid#104]
   :     +- SubqueryAlias spark_catalog.default.hudi_test
   :        +- Relation default.hudi_test[_hoodie_commit_time#99,_hoodie_commit_seqno#100,_hoodie_record_key#101,_hoodie_partition_path#102,_hoodie_file_name#103,uuid#104,name#105,price#106] parquet
   +- SubqueryAlias spark_catalog.default.hudi_test
      +- Relation default.hudi_test[_hoodie_commit_time#37,_hoodie_commit_seqno#38,_hoodie_record_key#39,_hoodie_partition_path#40,_hoodie_file_name#41,uuid#42,name#43,price#44] parquet
```

```sql
spark-sql> explain extended select * from hudi_test where exists (select uuid from hudi_test);

== Analyzed Logical Plan ==
_hoodie_commit_time: string, _hoodie_commit_seqno: string, _hoodie_record_key: string, _hoodie_partition_path: string, _hoodie_file_name: string, uuid: int, name: string, price: double
Project [_hoodie_commit_time#37, _hoodie_commit_seqno#38, _hoodie_record_key#39, _hoodie_partition_path#40, _hoodie_file_name#41, uuid#42, name#43, price#44]
+- Filter exists#107 []
   :  +- Project [uuid#118]
   :     +- SubqueryAlias spark_catalog.default.hudi_test
   :        +- Relation default.hudi_test[_hoodie_commit_time#113,_hoodie_commit_seqno#114,_hoodie_record_key#115,_hoodie_partition_path#116,_hoodie_file_name#117,uuid#118,name#119,price#120] parquet
   +- SubqueryAlias spark_catalog.default.hudi_test
      +- Relation default.hudi_test[_hoodie_commit_time#37,_hoodie_commit_seqno#38,_hoodie_record_key#39,_hoodie_partition_path#40,_hoodie_file_name#41,uuid#42,name#43,price#44] parquet
```

**Comment by ygf11** [comment]
> > In fact, subquery alias doesn't actually work, we can eliminate it, and I'm getting ready to do it.

Thanks for explaining @jackwener. It helps a lot.

I find the behavior of `subquery alias` is different from it in spark:
* DataFusion doesn't add subquery alias in Bind/Analyze stage.
* If the in-subquery can be optimized to join, it adds a `subquery alias` to the plan.

Following are examples:
```sql
> explain select * from t1 where t1_id in (select t2_id from t2);
# optimized plan
Projection: t1.t1_id, t1.t1_name, t1.t1_int                                                                                                                     
  LeftSemi Join: t1.t1_id = __correlated_sq_3.t2_id                                                                                                                
    TableScan: t1 projection=[t1_id, t1_name, t1_int]                                                                                                               
    SubqueryAlias: __correlated_sq_3 # Added in DecorrelateWhereIn rule                                                                                                                               
      Projection: t2.t2_id                                                                                                                                       
          TableScan: t2 projection=[t2_id]

> explain select * from t1 where t1_id in (select t2_id from t2 as x);
# optimized plan
Projection: t1.t1_id, t1.t1_name, t1.t1_int                                                                                                                     
  LeftSemi Join: t1.t1_id = __correlated_sq_3.t2_id                                                                                                                
    TableScan: t1 projection=[t1_id, t1_name, t1_int]                                                                                                               
    SubqueryAlias: __correlated_sq_3   # Added in DecorrelateWhereIn rule                                                                                                                                   
      Projection: x.t2_id AS t2_id                                                                                                                                      
        SubqueryAlias: x     # Introduced by `AS` keyword                                                                                                                                             
          TableScan: t2 projection=[t2_id]
```

As you plan to eliminate `subquery alias`, I think maybe we should add `subquery alias` in Bind/Analyze stage not in optimization stage.

BTW, `DecorrelateWhereExists` doesn't add `subquery alias`, so alias seems gone after optimization.

How do you think? @jackwener @mingmwang

**Comment by jackwener** [comment]
> As you plan to eliminate subquery alias, I think maybe we should add subquery alias in Bind/Analyze stage not in optimization stage.

Current, There isn't a `binder/analyzer` in `Datafusion`, I have tried to implemented it, but it's a difficult and huge work.

I think add `subquery alias` in optimization also is reasonable.

> DecorrelateWhereExists doesn't add subquery alias

I think it's an oversight, and if anyone want to unify `DecorrelateWhereExists` and `DecorrelateWhereIn`, I think this problem will be fixed.

I also suspect that this problem may be caused by out-of-sync modifications (`DecorrelateWhereIn` was fixed but `DecorrelateWhereExists` not)
