### PR TITLE
NOT operator not return internal error when args are not boolean value

### LINKED ISSUE #8965: NOT operator should not return internal error when args are not boolean value
### Describe the bug

```
❯ select not('hi');
Internal error: NOT 'Literal { value: Utf8("hi") }' can't be evaluated because the expression's type is Utf8, not boolean or NULL.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
❯ select 1 and 2;
Error during planning: Cannot infer common argument type for logical boolean operation Int64 AND Int64
```
I think the return error message of NOT should like `And` operator, they both only work for boolean value.

_Originally posted by @haohuaijin in https://github.com/apache/arrow-datafusion/pull/8957#discussion_r1463345264_

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by guojidan**
## Which issue does this PR close?

Closes #8965.

## What changes are included in this PR?

in `TypeCoercionRewriter` return an error if the argument to not can't be coerced to Boolean

### CODE REVIEW

**Review by haohuaijin — APPROVED** [review]
Thank you @guojidan look great to me! I think you can merge main to resolve the conflicts.

File: datafusion/optimizer/src/analyzer/type_coercion.rs [hunk 1]
```diff
@@ -176,6 +176,10 @@ impl TreeNodeRewriter for TypeCoercionRewriter {
                     negated,
                 )))
             }
+            Expr::Not(expr) => {
+                let expr = not(get_casted_expr_for_bool_op(&expr, &self.schema)?);
+                Ok(expr)
+            }
             Expr::IsTrue(expr) => {
```
Comment (alamb) [inline datafusion/optimizer/src/analyzer/type_coercion.rs:183]: It might make sense to remove the catch all  from this `match` expression

https://github.com/apache/arrow-datafusion/blob/bc0ba6a724aaaf312b770451718cbce696de6640/datafusion/optimizer/src/analyzer/type_coercion.rs#L413

And explicitly list out all Expr types so that we don't accidentally another Expr type in the future

Is that something you might be willing to do in another PR @guojidan  ?

**Review by alamb — APPROVED** [review]
I agree with @haohuaijin  -- very nice @guojidan . Thank you 🙏 

I think this PR just needs to merge up from main and resolve the conflict and it will be good to go.

Thank you for the string of excellent PRs @guojidan

File: datafusion/optimizer/src/analyzer/type_coercion.rs (hunk 1 above)
Comment (guojidan) [reply datafusion/optimizer/src/analyzer/type_coercion.rs:183]: i will do soon

**Comment by guojidan** [comment]
cc @alamb  need rerun test case, look like network error

**Comment by alamb** [comment]
> cc @alamb need rerun test case, look like network error

restarted!

BTW another trick I think works is closing and the reopening the PR

**Comment by alamb** [comment]
Thanks again @guojidan !
