### PR TITLE
fix: unambiguously truncate time in date_trunc function

### LINKED ISSUE #8899: date_trunc panicked with message: called `Option::unwrap()` on a `None` value
### Describe the bug

`date_trunc()` panicked for some timestamps that are casted to a timezone other than UTC

For example, this query causes a panic:

```sql
SELECT date_trunc('week', arrow_cast(arrow_cast('2023-10-29T00:00:00Z', 'Timestamp(Nanosecond, Some("UTC"))'), 'Timestamp(Nanosecond, Some("Europe/Berlin"))'));
```

Even though a different timestamp works fine, e.g. `2023-10-29T02:00:00Z`

### To Reproduce

Run the above query in DataFusion CLI v34.0.0

❌`2023-10-29T00:00:00Z` panicked 

```sql
$ datafusion-cli

DataFusion CLI v34.0.0
❯ SELECT date_trunc('week', arrow_cast(arrow_cast('2023-10-29T00:00:00Z', 'Timestamp(Nanosecond, Some("UTC"))'), 'Timestamp(Nanosecond, Some("Europe/Berlin"))'));
thread 'main' panicked at /private/tmp/datafusion-20231217-5103-4z8blm/arrow-datafusion-34.0.0/datafusion/physical-expr/src/datetime_expressions.rs:335:14:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

✅ `2023-10-29T02:00:00Z` works 

```sql
$ datafusion-cli

DataFusion CLI v34.0.0
❯ SELECT date_trunc('week', arrow_cast(arrow_cast('2023-10-29T02:00:00Z', 'Timestamp(Nanosecond, Some("UTC"))'), 'Timestamp(Nanosecond, Some("Europe/Berlin"))'));
+-------------------------------------------------------+
| date_trunc(Utf8("week"),Utf8("2023-10-29T02:00:00Z")) |
+-------------------------------------------------------+
| 2023-10-23T00:00:00+02:00                             |
+-------------------------------------------------------+
1 row in set. Query took 0.005 seconds.
```

### Expected behavior

Handle the result correctly or return an error instead of panicking

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mhilton**
## Which issue does this PR close?

Closes #8899

## Rationale for this change

When date_trunc is truncating a timestamp with a geographic timezone it would previously get stuck if the local reprentation of the time could be ambiguously interpreted. This happens when the clocks "go back". The update here is to use the original timestamp offset as the tie-breaker when the local representation of the truncated time could be ambiguous.

## Are these changes tested?

Yes, additional unit tests

### CODE REVIEW

File: datafusion/physical-expr/src/datetime_expressions.rs [hunk 1]
```diff
@@ -564,8 +564,34 @@ fn _date_trunc_coarse_with_tz(
...
     value: Option<DateTime<Tz>>,
 ) -> Result<Option<i64>> {
-    let value = _date_trunc_coarse::<DateTime<Tz>>(granularity, value)?;
-    Ok(value.and_then(|value| value.timestamp_nanos_opt()))
+    if let Some(value) = value {
+        let timezone = value.timezone();
+        let offset = value.offset().fix();
+        let local = value.naive_local();
+        let value = _date_trunc_coarse::<NaiveDateTime>(granularity, Some(local))?;
+        let value = value.map(|value| match value.and_local_timezone(timezone) {
```
Comment (tustvold) [inline datafusion/physical-expr/src/datetime_expressions.rs:572]: If the intention is to effectively preserve the fixed offset of the original timestamp, I think there should be a way to take the `NaiveDateTime` and convert it back with the same offset?

File: datafusion/physical-expr/src/datetime_expressions.rs [hunk 2]
```diff
@@ -564,8 +564,34 @@ fn _date_trunc_coarse_with_tz(
...
+                // period. Therefore the offset of one of these times should match the
+                // offset of the original time.
+                if datetime1.offset().fix() == offset {
+                    datetime1
+                } else {
+                    datetime2
+                }
+            }
+        });
+        Ok(value.and_then(|value| value.timestamp_nanos_opt()))
```
Comment (tustvold) [inline datafusion/physical-expr/src/datetime_expressions.rs:590]:
```suggestion
        let timezone = value.timezone();
        let offset = value.offset().fix();
        Ok(value.and_then(|value|{
            let local = value.naive_utc().checked_add_offset(offset)?;
            let local_trunc = _date_trunc_coarse::<NaiveDateTime>(granularity, Some(local))?;
            let trunc = local_trunc.checked_sub_offset(offset)?;
            trunc.timestamp_nanos_opt()
        }))
```

Perhaps something like this, not tested at all

Comment (tustvold) [reply datafusion/physical-expr/src/datetime_expressions.rs:590]: This doesn't work, as it will preserve the source timezone offset when it shouldn't, e.g. when truncating by day

**Review by tustvold — APPROVED** [review]
This looks sensible to me

File: datafusion/physical-expr/src/datetime_expressions.rs [hunk 3]
```diff
@@ -564,8 +564,34 @@ fn _date_trunc_coarse_with_tz(
...
+                // It is impossible to truncate from a time that does exist into one that doesn't.
+                panic!("date_trunc produced impossible time")
+            }
+            LocalResult::Single(datetime) => datetime,
+            LocalResult::Ambiguous(datetime1, datetime2) => {
+                // Because we are truncating from an equally or more specific time
+                // the original time must have been within the ambiguous local time
+                // period. Therefore the offset of one of these times should match the
+                // offset of the original time.
+                if datetime1.offset().fix() == offset {
```
Comment (tustvold) [inline datafusion/physical-expr/src/datetime_expressions.rs:583]:
```suggestion
                if datetime1.offset().fix() == value.offset().fix() {
```

You could defer this computation to here

**Review by alamb — APPROVED** [review]
Thank you @mhilton -- I also pushed a `.slt` test to this code for SQL level verification (it panic's on main, and passes on this branch).

Thank you very much ❤️

File: datafusion/sqllogictest/test_files/timestamps.slt [hunk 4]
```diff
@@ -1262,6 +1262,89 @@ SELECT DATE_TRUNC('day', arrow_cast(TIMESTAMP '2023-08-03 14:38:50Z', 'Timestamp
...
+  arrow_cast(ts, 'Timestamp(Nanosecond, Some("UTC"))') as ts
+from timestamp_strings;
+
+statement ok
+create view timestamp_berlin as
+select
+  arrow_cast(ts, 'Timestamp(Nanosecond, Some("Europe/Berlin"))') as ts
+from timestamp_utc; -- have to convert to utc prior to converting to berlin
+
+query PT
```
Comment (appletreeisyellow) [inline datafusion/sqllogictest/test_files/timestamps.slt:1290]: @alamb What does `query PT` mean? Same question for `query PPPP`

File: datafusion/physical-expr/src/datetime_expressions.rs [hunk 5]
```diff
@@ -564,8 +564,34 @@ fn _date_trunc_coarse_with_tz(
...
+                LocalResult::Ambiguous(datetime1, datetime2) => {
+                    // Because we are truncating from an equally or more specific time
+                    // the original time must have been within the ambiguous local time
+                    // period. Therefore the offset of one of these times should match the
+                    // offset of the original time.
+                    if datetime1.offset().fix() == value.offset().fix() {
+                        datetime1
+                    } else {
+                        datetime2
+                    }
```
Comment (appletreeisyellow) [inline datafusion/physical-expr/src/datetime_expressions.rs:586]: Nice!

**Review by appletreeisyellow — APPROVED** [review]
Thanks for fixing it @mhilton!

File: datafusion/sqllogictest/test_files/timestamps.slt (hunk 4 above)
Comment (mhilton) [reply datafusion/sqllogictest/test_files/timestamps.slt:1290]: https://github.com/apache/arrow-datafusion/tree/main/datafusion/sqllogictest#slt-file-format has the full details. It describes how the query output should be compared with the expected output.

**Comment by alamb** [comment]
I merged up from main to resolve conflicts after https://github.com/apache/arrow-datafusion/pull/9040 was mergerd

**Comment by alamb** [comment]
FYI @Omega359  as you have been working in this part of the code recently

File: datafusion/physical-expr/src/datetime_expressions.rs [hunk 6]
```diff
@@ -662,8 +662,34 @@ fn _date_trunc_coarse_with_tz(
...
-    let value = _date_trunc_coarse::<DateTime<Tz>>(granularity, value)?;
-    Ok(value.and_then(|value| value.timestamp_nanos_opt()))
+    if let Some(value) = value {
+        let local = value.naive_local();
+        let truncated = _date_trunc_coarse::<NaiveDateTime>(granularity, Some(local))?;
+        let truncated = truncated.map(|truncated| {
+            match truncated.and_local_timezone(value.timezone()) {
+                LocalResult::None => {
+                    // It is impossible to truncate from a time that does exist into one that doesn't.
+                    panic!("date_trunc produced impossible time")
```
Comment (Omega359) [inline datafusion/physical-expr/src/datetime_expressions.rs:672]: Panic! seems rather severe for this - exec_err! I think would be a better option as it will bubble up the error back to the caller.

File: datafusion/physical-expr/src/datetime_expressions.rs [hunk 7]
```diff
@@ -662,8 +663,42 @@ fn _date_trunc_coarse_with_tz(
...
+        let local = value.naive_local();
+        let truncated = _date_trunc_coarse::<NaiveDateTime>(granularity, Some(local))?;
+        let truncated = truncated.and_then(|truncated| {
+            match truncated.and_local_timezone(value.timezone()) {
+                LocalResult::None => {
+                    // This can happen if the date_trunc operation moves the time into
+                    // an hour that doesn't exist due to daylight savings. On known example where
+                    // this can happen is with historic dates in the America/Sao_Paulo time zone.
+                    // To account for this adjust the time by a few hours, convert to local time,
+                    // and then adjust the time back.
```
Comment (alamb) [inline datafusion/physical-expr/src/datetime_expressions.rs:676]: Timezones continue to blow my mind

**Comment by alamb** [comment]
Thank you everyone involved. Amazing
