### PR TITLE
Reserve the literal expression of `Count` function

### LINKED ISSUE #3891: `count(Literal)` gives wrong column name
**Describe the bug**

**To Reproduce**
Tested on the latest datafusion-cli
```sql
❯ select count(2.2);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
```
**Expected behavior**
I'd like the column name to be
```
COUNT(Float64(2.2))
```

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>

# Which issue does this PR close?

Closes #3891.

# Rationale for this change
## master
``` sql
❯ select count(*);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
❯ select count(1);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
❯ select count(2);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
❯ select count(2.2);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
```

## this patch
```sql
❯ select count(*), count(1), count(2), count(2.2);
+-----------------+-----------------+-----------------+---------------------+
| COUNT(UInt8(1)) | COUNT(Int64(1)) | COUNT(Int64(2)) | COUNT(Float64(2.2)) |
+-----------------+-----------------+-----------------+---------------------+
| 1               | 1               | 1               | 1                   |
+-----------------+-----------------+-----------------+---------------------+
```

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/sql/src/planner.rs [hunk 1]
```diff
@@ -2344,25 +2344,21 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
         schema: &DFSchema,
     ) -> Result<(AggregateFunction, Vec<Expr>)> {
         let args = match fun {
             // Special case rewrite COUNT(*) to COUNT(constant)
-            AggregateFunction::Count => function
-                .args
+            AggregateFunction::Count => args
                 .into_iter()
                 .map(|a| match a {
-                    FunctionArg::Unnamed(FunctionArgExpr::Expr(SQLExpr::Value(
```
Comment (alamb) [inline datafusion/sql/src/planner.rs:2356]: 🧹 

Not sure why that was in there

Nice work @HaoYang670  fixing bugs by deleting code 🏅

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
cc @andygrove
