### PR TITLE
Ensure the row count is preserved when coalescing over empty records

### LINKED ISSUE #3283: `project_column_with_filters_that_cant_pushed_down_always_true` only passes if plan is optimized twice
**Describe the bug**
In `execute_to_batches`, we create the physical plan from an optimized logical plan. This results in the plan being optimized twice. Fixing this causes a regression in `project_column_with_filters_that_cant_pushed_down_always_true`.

```
ArrowError(InvalidArgumentError(\"must either specify a row count or at least one column\")) at Executing physical plan for 'select * from (select 1 as a) f where f.a=1;'
```

**To Reproduce**
Modify `execute_to_batches` to pass the unoptimized logical plan to `create_physical_plan`.

**Expected behavior**
Test should pass

**Additional context**
None

### PR DESCRIPTION
**Pull request by isidentical**
# Which issue does this PR close?

Closes #3283.

 # Rationale for this change

The row count information is required for the validation happening during the `RecordBatch` construction. Luckily we already calculate it and propagate it in the stream handler code, but just don't preserve it when creating the final record. 

This PR also changes the SQL test code to never double-optimize logical plans (as it used to) since that would hide this problem (and maybe different ones in the future).

# What changes are included in this PR?

This PR now creates the final record with the propagated `row_count` for the cases like #3283 where the schema might not contain any fields at all and the validation logic in arrow-rs would fail.

# Are there any user-facing changes?

This is a bug fix in general. It also includes a change in our internal tooling to never double-optimize logical plans, which the reasoning is provided inn #3283.

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]

File: datafusion/core/tests/sql/mod.rs [hunk 1]
```diff
@@ -766,13 +766,16 @@ async fn execute_to_batches(ctx: &SessionContext, sql: &str) -> Vec<RecordBatch>
...
         .unwrap();
-    let optimized_logical_schema = plan.schema();
+    let optimized_logical_schema = optimized_logical_plan.schema();
 
-    let msg = format!("Creating physical plan for '{}': {:?}", sql, plan);
+    let msg = format!(
+        "Creating physical plan for '{}': {:?}",
+        sql, optimized_logical_plan
+    );
     let plan = ctx
```
Comment (alamb) [inline datafusion/core/tests/sql/mod.rs:779]: It is a very subtle point here that the optimized logical plan is no longer actually run. 👍 It took me a few reads to see that. 

A comment might help future readers.

File: datafusion/core/src/physical_plan/coalesce_batches.rs [hunk 2]
```diff
@@ -291,7 +291,11 @@ pub fn concat_batches(
         batches.len(),
         row_count
     );
-    RecordBatch::try_new(schema.clone(), arrays)
+
+    let mut options = RecordBatchOptions::default();
+    options.row_count = Some(row_count);
```
Comment (alamb) [inline datafusion/core/src/physical_plan/coalesce_batches.rs:296]: As an FYI (not important) you can write this same pattern in what is likely more idiomatic rust (avoid `mut`) like:

```suggestion
    let options = RecordBatchOptions{
      row_count:Some(row_count),
      ..Default::default()
    };
```

**Review by alamb — APPROVED** [review]
Thanks @isidentical  -- this looks great. I left some small suggestions but they are not required -- let me know if you want to address them in this PR or a follow on

Thanks again 🏅

File: datafusion/core/tests/sql/mod.rs (hunk 1 above)
Comment (isidentical) [reply datafusion/core/tests/sql/mod.rs:779]: Definietly!

File: datafusion/core/src/physical_plan/coalesce_batches.rs (hunk 2 above)
Comment (isidentical) [reply datafusion/core/src/physical_plan/coalesce_batches.rs:296]: This seems to fail since `RecordBatchOptions` is non-exhaustive and comes directly from arrow-rs. I am not really familiar with this part of Rust semantics, but there seems to be an [existing issue](https://internals.rust-lang.org/t/allow-constructing-non-exhaustive-structs-using-default-default/13868) about it.
```
error[E0639]: cannot create non-exhaustive struct using struct expression
   --> /home/isidentical/projects/arrow-datafusion/datafusion/core/src/physical_plan/coalesce_batches.rs:295:19
    |
295 |       let options = RecordBatchOptions {
    |  ___________________^
296 | |         row_count: Some(row_count),
297 | |         ..Default::default()
298 | |     };
    | |_____^

For more information about this error, try `rustc --explain E0639`.
```

Is there any way to achieve it? The only other example of `RecordBatchOptions` construction present in DF is the following which uses the same pattern as the code present in this PR but I'd be happy to refactor both if there is a more idiomatic way.
https://github.com/apache/arrow-datafusion/blob/9956f80f197550051db7debae15d5c706afc22a3/datafusion/core/src/physical_plan/file_format/mod.rs#L286-L288

**Review by andygrove — APPROVED** [review]

File: datafusion/core/src/physical_plan/coalesce_batches.rs (hunk 2 above)
Comment (alamb) [reply datafusion/core/src/physical_plan/coalesce_batches.rs:296]: Thanks for trying @isidentical  -- I will file a follow on in arrow-rs to make this API more ergonomic

Comment (alamb) [reply datafusion/core/src/physical_plan/coalesce_batches.rs:296]: Filed https://github.com/apache/arrow-rs/issues/2728 as a follow on (I also hit the same thing in https://github.com/apache/arrow-datafusion/pull/3454 FWIW)

Comment (alamb) [reply datafusion/core/src/physical_plan/coalesce_batches.rs:296]: FYI https://github.com/apache/arrow-rs/pull/2729 fixed this issue  and https://github.com/apache/arrow-datafusion/pull/3483 includes using the new API.
