### PR TITLE
Fix page index pruning fail on complex_expr

### LINKED ISSUE #4317: Page index pruning fail on  complex_expr
All test case with expr fail 😭

_Originally posted by @Ted-Jiang in https://github.com/apache/arrow-datafusion/pull/4255#discussion_r1026585801_

### PR DESCRIPTION
**Pull request by Ted-Jiang**
Signed-off-by: yangjiang <yangjiang@ebay.com>

# Which issue does this PR close?

Closes #4317.

# Rationale for this change

After fix all the ignore issue, I think now page pruning has the same amount test case like row group pruning✌️.
# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/tests/parquet/page_pruning.rs [hunk 1]
```diff
@@ -495,22 +491,20 @@ async fn prune_f64_lt() {
...
-#[ignore]
 async fn prune_f64_scalar_fun_and_gt() {
     // result of sql "SELECT * FROM t where abs(f - 1) <= 0.000001  and f >= 0.1"
     // only use "f >= 0" to prune
     test_prune(
         Scenario::Float64,
         "SELECT * FROM t where abs(f - 1) <= 0.000001  and f >= 0.1",
         Some(0),
-        Some(2),
+        Some(10),
```
Comment (Ted-Jiang) [inline datafusion/core/tests/parquet/page_pruning.rs:501]: only use "f >= 0" to prune it will prune two pages (each 5 rows), so make it 10 make sense

File: datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs [hunk 2]
```diff
@@ -126,46 +126,50 @@ pub(crate) fn build_page_filter(
...
-                        .map_err(|e| {
-                            ArrowError::ParquetError(format!(
-                                "Fail in prune_pages_in_one_row_group: {}",
-                                e
-                            ))
-                        }),
-                    );
-                } else {
-                    trace!(
+            //  when building `PruningPredicate`, some single column filter like `abs(i) = 1`
```
Comment (Ted-Jiang) [inline datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs:129]: I think we can support rewrite `abs(i) = 1` to `i = 1 or i = -1`🤔 further.

Comment (Ted-Jiang) [reply datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs:129]: File #4388

**Comment by Ted-Jiang** [comment]
@alamb I think now page pruning has the same amount of test case as row group pruning, do we need any more test case so that we can enable Page Filtering by default 🤔

File: datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs [hunk 3]
```diff
@@ -126,46 +126,50 @@ pub(crate) fn build_page_filter(
...
+            //  will be rewrite to `lit(true)`, so may have an empty required_columns.
```
Comment (Ted-Jiang) [inline datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs:130]: this is the why it fails.

**Review by alamb — APPROVED** [review]
Makes sense to me -- thanks @Ted-Jiang  👍 

Looking at this PR with whitespace blind diff helped me: https://github.com/apache/arrow-datafusion/pull/4387/files?w=1

File: datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs (hunk 3 above)
Comment (alamb) [reply datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs:130]: Thank you for these comments, BTW -- they help both to review the code as well as read it in the future 👍
