### PR TITLE
fix: don't extract common sub expr in `CASE WHEN` clause

### LINKED ISSUE #8814: throw Divide by zero error when use case when
### Describe the bug

When i use the 
```
case value1 > 0 then value/value1 else 0 end as result
```
and got the divide by zero

### To Reproduce

create table users as values (1,1),(2,2),(3,3),(0,0),(4,0);

When run
```
select 
case when B.column1 > 0 and B.column2 > 0 then (A.column1/B.column1 - A.column2/B.column2) else 0 end as value3
from (select column1, column2 from users) as A ,  (select column1, column2 from users where column1 = 0) as B;
```
there is no issue.

But when run
```
select 
case when B.column1 > 0 then A.column1/B.column1 else 0 end as value1,
case when B.column1 > 0 and B.column2 > 0 then A.column1/B.column1 else 0 end as value3
from (select column1, column2 from users) as A ,  (select column1, column2 from users where column1 = 0) as B;
```
there is the issue: divide by zero

### Expected behavior

no exception and get the result

### Additional context

I am try to find the root cause, maybe it is caused by optimizer or the execution of the physical expr.

### PR DESCRIPTION
**Pull request by haohuaijin**
## Which issue does this PR close?

Closes #8814 

## Rationale for this change

as shown in #8814, in `CASE WHEN A THEN B ELSE C END` expr, the B and C only have one can run, 
so for query
```
select 
case when B.column1 > 0 then A.column1/B.column1 else 0 end as value1,
case when B.column1 > 0 and B.column2 > 0 then A.column1/B.column1 else 0 end as value3
from (select column1, column2 from users) as A ,  (select column1, column2 from users where column1 = 0) as B;
```
the `A.column1/B.column1` actually should not run, but we extract it as a common sub expr(see below plan), which results in `A.column1/B.column1` running and getting a divide zero error.
```
| initial_logical_plan                                       | Projection: CASE WHEN b.column1 > Int64(0) THEN a.column1 / b.column1 ELSE Int64(0) END AS value1, CASE WHEN b.column2 > Int64(0) THEN a.column1 / b.column1 ELSE Int64(0) END AS value3                                                                                                                                                        |
|                                                            |   CrossJoin:                                                                                                                                                                                                                                                                                                                                    |
|                                                            |     SubqueryAlias: a                                                                                                                                                                                                                                                                                                                            |
|                                                            |       Projection: users.column1, users.column2                                                                                                                                                                                                                                                                                                  |
|                                                            |         TableScan: users                                                                                                                                                                                                                                                                                                                        |
|                                                            |     SubqueryAlias: b                                                                                                                                                                                                                                                                                                                            |
|                                                            |       Projection: users.column1, users.column2                                                                                                                                                                                                                                                                                                  |
|                                                            |         Filter: users.column1 = Int64(0)                                                                                                                                                                                                                                                                                                        |
|                                                            |           TableScan: users                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| logical_plan after common_sub_expression_eliminate         | Projection: CASE WHEN b.column1 > Int64(0) THEN a.column1 / b.column1b.column1a.column1 AS a.column1 / b.column1 ELSE Int64(0) END AS value1, CASE WHEN b.column2 > Int64(0) THEN a.column1 / b.column1b.column1a.column1 AS a.column1 / b.column1 ELSE Int64(0) END AS value3                                                                  |
|                                                            |   Projection: a.column1 / b.column1 AS a.column1 / b.column1b.column1a.column1, a.column1, a.column2, b.column1, b.column2                                                                                                                                                                                                                      |
|                                                            |     CrossJoin:                                                                                                                                                                                                                                                                                                                                  |
|                                                            |       SubqueryAlias: a                                                                                                                                                                                                                                                                                                                          |
|                                                            |         Projection: users.column1, users.column2                                                                                                                                                                                                                                                                                                |
|                                                            |           TableScan: users                                                                                                                                                                                                                                                                                                                      |
|                                                            |       SubqueryAlias: b                                                                                                                                                                                                                                                                                                                          |
|                                                            |         Projection: users.column1, users.column2                                                                                                                                                                                                                                                                                                |
|                                                            |           Filter: users.column1 = Int64(0)                                                                                                                                                                                                                                                                                                      |
|                                                            |             TableScan: users 
```

## What changes are included in this PR?



## Are these changes tested?

yes, add a test.

## Are there any user-facing changes?

### CODE REVIEW

**Comment by haohuaijin** [comment]
cc @liukun4515

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 1]
```diff
@@ -614,7 +613,12 @@ impl ExprIdentifierVisitor<'_> {
 impl TreeNodeVisitor for ExprIdentifierVisitor<'_> {
     type N = Expr;
 
-    fn pre_visit(&mut self, _expr: &Expr) -> Result<VisitRecursion> {
+    fn pre_visit(&mut self, expr: &Expr) -> Result<VisitRecursion> {
+        // related to https://github.com/apache/arrow-datafusion/issues/8814
+        // If the expr contain volatile expression or is a case expression, skip it.
+        if matches!(expr, Expr::Case(..)) || is_volatile_expression(expr)? {
```
Comment (haohuaijin) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:619]: Check volatile expression is this place is because the previous method only can deal with a single `random()` function, the below function wil return true in main branch
```
SELECT r FROM (SELECT r1 == r2 r, r1, r2 FROM (SELECT random()+1 r1, random()+1 r2) WHERE r1 > 0 AND r2 > 0)
```

File: datafusion/optimizer/src/utils.rs [hunk 2]
```diff
@@ -92,6 +94,21 @@ pub fn log_plan(description: &str, plan: &LogicalPlan) {
     trace!("{description}::\n{}\n", plan.display_indent_schema());
 }
 
+/// check whether the expression is volatile predicates
+pub(crate) fn is_volatile_expression(e: &Expr) -> Result<bool> {
```
Comment (haohuaijin) [inline datafusion/optimizer/src/utils.rs:98]: move `is_volatile_expression` to utils for reuse.

**Comment by liukun4515** [comment]
> cc @liukun4515

thanks @haohuaijin  I will help to review this pr this week.

File: datafusion/optimizer/src/utils.rs [hunk 3]
```diff
@@ -92,6 +94,21 @@ pub fn log_plan(description: &str, plan: &LogicalPlan) {
...
+    let mut is_volatile_expr = false;
+    e.apply(&mut |expr| {
+        Ok(if is_volatile(expr)? {
+            is_volatile_expr = true;
+            VisitRecursion::Stop
+        } else {
+            VisitRecursion::Continue
+        })
+    })
+    .unwrap();
```
Comment (liukun4515) [inline datafusion/optimizer/src/utils.rs:108]: should we use the `unwrap`? or the `?`

Comment (liukun4515) [reply datafusion/optimizer/src/utils.rs:108]: because the result of `is_volatile_expression` is `result`

File: datafusion/sqllogictest/test_files/select.slt [hunk 4]
```diff
@@ -1112,3 +1112,22 @@ SELECT abs(x), abs(x) + abs(y) FROM t;
 
 statement ok
 DROP TABLE t;
+
+# related to https://github.com/apache/arrow-datafusion/issues/8814
```
Comment (liukun4515) [inline datafusion/sqllogictest/test_files/select.slt:1116]: 👍🏻

**Comment by liukun4515** [comment]
@jackwener could you please help to take a look this issue?

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 1 above)
Comment (jackwener) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:619]: I think this problem could exist in other function/expression like `COALESCE` | `OR`

It can be tracked as a future ticket.

Comment (jackwener) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:619]: The inner expressions in these expressions may be short-circuited.

**Review by jackwener — APPROVED** [review]
In general, look great to me, but some details need improve.

Thanks @haohuaijin & @liukun4515

File: datafusion/optimizer/src/push_down_filter.rs [hunk 5]
```diff
@@ -739,7 +740,9 @@ impl OptimizerRule for PushDownFilter {
 
                             (field.qualified_name(), expr)
                         })
-                        .partition(|(_, value)| is_volatile_expression(value));
+                        .partition(|(_, value)| {
+                            is_volatile_expression(value).unwrap_or(true)
```
Comment (jackwener) [inline datafusion/optimizer/src/push_down_filter.rs:744]: why use `unwrap_or(true)`?

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 1 above)
Comment (haohuaijin) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:619]: track in #8874

File: datafusion/optimizer/src/push_down_filter.rs (hunk 5 above)
Comment (haohuaijin) [reply datafusion/optimizer/src/push_down_filter.rs:744]: If we don't know whether the scalar function is volatile, default set it to a volatile function.

File: datafusion/optimizer/src/utils.rs (hunk 3 above)
Comment (haohuaijin) [reply datafusion/optimizer/src/utils.rs]: Thanks for pointing this out. I forgot to change it when I moved the code.

**Review by liukun4515 — APPROVED** [review]

**Comment by liukun4515** [comment]
Thanks for @haohuaijin to fix this issue.
Thanks for @jackwener to help review this and point out other cases/issues.

**Comment by liukun4515** [comment]
@alamb i will merge this pr.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 1 above)
Comment (liukun4515) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:619]: I comment in the #8874, Do  we have any method for this rule to make sure the new function/expr or other cases we can't find will not bring the same bug
