### PR TITLE
Fix data type calculation for `CaseExpr` s with `NULLs`

### LINKED ISSUE #2798: panic when case statement returns null
**Describe the bug**

I've boiled this down to a small test case which panics with this error:
thread 'main' panicked at 'NullArray data should not contain a null buffer, as no buffers are required'

**To Reproduce**

run this SQL from cli:
select case when b is null then null else b end from (select a,b from (values (1,null),(2,3)) as t (a,b)) a;

**Expected behavior**

In Postgres, it returns "null" and 3, as expected.

**Additional context**

Also, this query returns wrong results, as compared to PG:
select case when b is null then null else b end from (select a,b from (values (1,1),(2,3)) as t (a,b)) a;

in PG, that returns 2 rows: 1 and 3. In Datafusion, it returns 2 nulls.

### PR DESCRIPTION
**Pull request by AssHero**
# Which issue does this PR close?

Closes #2798 

# Rationale for this change
use non-null then/else expr 's data type as return data type for CaseExpr.

For this query:  select case when b is null then null else b end from (select a,b from (values (1,null),(2,3)) as t (a,b)) a;

We use data type of else expr(b) as return data type.

For this query:  select case when b is null then null when b >= 3 then b + 1 else b end from (select a,b from (values (1,null),(2,3)) as t (a,b)) a;

We use data type of then expr(b + 1 ) as return data type.

# What changes are included in this PR?
modify data_type function of CaseExpr in datafusion/physical-expr/src/expressions/case.rs

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @AssHero

**Review by alamb — APPROVED** [review]
Thanks @AssHero  -- see also https://github.com/apache/arrow-datafusion/pull/2814 which is also related to CASE and NULL

File: datafusion/physical-expr/src/expressions/case.rs [hunk 1]
```diff
@@ -117,7 +117,7 @@ impl CaseExpr {
     ///     [ELSE result]
     /// END
     fn case_when_with_expr(&self, batch: &RecordBatch) -> Result<ColumnarValue> {
-        let return_type = self.when_then_expr[0].1.data_type(&batch.schema())?;
+        let return_type = self.data_type(&*batch.schema())?;
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:120]: 👍

File: datafusion/physical-expr/src/expressions/case.rs [hunk 2]
```diff
@@ -138,7 +138,12 @@ impl CaseExpr {
             let then_value = self.when_then_expr[i]
                 .1
                 .evaluate_selection(batch, &when_match)?;
-            let then_value = then_value.into_array(batch.num_rows());
+            let then_value = match then_value {
+                ColumnarValue::Scalar(value) if value.is_null() => {
+                    new_null_array(&return_type, batch.num_rows())
+                }
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:144]: I don't understand why this code is needed -- I would have expected that `then_value.into_array()` would have worked

File: datafusion/physical-expr/src/expressions/case.rs [hunk 3]
```diff
@@ -228,7 +238,23 @@ impl PhysicalExpr for CaseExpr {
...
+        // since all then results have the same data type, we can choose any one as the
+        // return data type except for the null.
+        let mut data_type = DataType::Null;
+        for i in 0..self.when_then_expr.len() {
+            data_type = self.when_then_expr[i].1.data_type(input_schema)?;
+            if !data_type.equals_datatype(&DataType::Null) {
+                break;
+            }
+        }
+        // if all then results are null, we use data type of else expr instead if possible.
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:250]: if they are all null, the output type is also null I would think.

File: datafusion/physical-expr/src/expressions/case.rs (hunk 2 above)
Comment (alamb) [reply datafusion/physical-expr/src/expressions/case.rs:144]: Update: I removed it and the tests errored 🤣 

```
---- sql::expr::case_expr_with_null stdout ----
thread 'sql::expr::case_expr_with_null' panicked at 'called `Result::unwrap()` on an `Err` value: "ArrowError(InvalidArgumentError(\"arguments need to have the same data type\")) at Executing physical plan for 'select case when b is null then null else b end from (select a,b from (values (1,null),(2,3)) as t (a,b)) a;': ProjectionExec { expr: [(CaseExpr { expr: None, when_then_expr: [(IsNullExpr { arg: Column { name: \"b\", index: 0 } }, Literal { value: NULL })], else_expr: Some(Column { name: \"b\", index: 0 }) }, \"CASE WHEN #a.b IS NULL THEN NULL ELSE #a.b END\")], schema: Schema { fields: [Field { name: \"CASE WHEN #a.b IS NULL THEN NULL ELSE #a.b END\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }, input: ProjectionExec { expr: [(Column { name: \"b\", index: 0 }, \"b\")], schema: Schema { fields: [Field { name: \"b\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }, input: ProjectionExec { expr: [(Column { name: \"b\", index: 0 }, \"b\")], schema: Schema { fields: [Field { name: \"b\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }, input: ProjectionExec { expr: [(Column { name: \"column2\", index: 0 }, \"b\")], schema: Schema { fields: [Field { name: \"b\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }, input: ProjectionExec { expr: [(Column { name: \"column2\", index: 1 }, \"column2\")], schema: Schema { fields: [Field { name: \"column2\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }, input: ValuesExec { schema: Schema { fields: [Field { name: \"column1\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }, Field { name: \"column2\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }, data: [RecordBatch { schema: Schema { fields: [Field { name: \"column1\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }, Field { name: \"column2\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }, columns: [PrimitiveArray<Int64>\n[\n  1,\n  2,\n], PrimitiveArray<Int64>\n[\n  null,\n  3,\n]], row_count: 2 }] }, metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] } } } }, metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] } } } }, metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] } } } }, metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] } } } }, metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] } } } }"', datafusion/core/tests/sql/mod.rs:641:10
```

**Comment by alamb** [comment]
Thanks again @AssHero  -- keep the PRs rolling 🚋
