### PR TITLE
Use `BufReader` for LocalFileReader to revert performance regression in parquet reading

### LINKED ISSUE #1363: Major performance regression in reading partitioned Parquet data on master
Reading (partitioned) Parquet data got slower, when executing parquet data.

It seems to have started with #1010 - the commit before doesn't have the performance regression.

This is visible when running TPCH benchmarks, for example, executing query 6 became much slower.

I am not sure what the cause is - it would help to find the commit where the "slowness" was introduced. 

> Looking back at the earlier results I posted - it looks the main difference is that the original `arrow` / `parquet` got slower. I am not sure what the cause is.

_Originally posted by @Dandandan in https://github.com/apache/arrow-datafusion/issues/68#issuecomment-979077578_

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #1363

 # Rationale for this change

Parquet reading was slow. This recovers the performance regression in the TPC-H benchmark.

There is still a slowdown in query 10 - and other queries, but this is unrelated to Parquet reading https://github.com/apache/arrow-datafusion/issues/1367 (and performance still improves from roughly 10 to 7s on that query).

# What changes are included in this PR?

`Use the `BufRead` trait instead of `Read`.

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/src/datasource/object_store/local.rs [hunk 1]
```diff
@@ -18,7 +18,7 @@
 //! Object store that represents the Local File System.
 
 use std::fs::{self, File, Metadata};
-use std::io::{Read, Seek, SeekFrom};
+use std::io::{BufRead, BufReader, Read, Seek, SeekFrom};
```
Comment (alamb) [inline datafusion/src/datasource/object_store/local.rs:21]: TIL `BufRead` trait

File: datafusion/src/datasource/object_store/local.rs [hunk 2]
```diff
@@ -82,12 +82,15 @@ impl ObjectReader for LocalFileReader {
...
         length: usize,
-    ) -> Result<Box<dyn Read + Send + Sync>> {
+    ) -> Result<Box<dyn BufRead + Send + Sync>> {
         // A new file descriptor is opened for each chunk reader.
         // This okay because chunks are usually fairly large.
         let mut file = File::open(&self.file.path)?;
         file.seek(SeekFrom::Start(start))?;
-        Ok(Box::new(file.take(length as u64)))
+
+        let file = BufReader::new(file.take(length as u64));
```
Comment (alamb) [inline datafusion/src/datasource/object_store/local.rs:91]: It seems like this is the actual fix, right? Is the change to require the `BufRead` trait needed?

**Review by alamb — APPROVED** [review]
Thank you @Dandandan  -- I am not sure about the need for the `BufRead` trait, but otherwise looks good to me.

Very nice 🕵️  work

File: datafusion/src/datasource/object_store/local.rs (hunk 2 above)
Comment (Dandandan) [reply datafusion/src/datasource/object_store/local.rs:91]: Not sure. Rerunning some benchmarks now without the trait.

Comment (Dandandan) [reply datafusion/src/datasource/object_store/local.rs:91]: Yes - looks like `BufRead` wasn't needed :tada:

**Comment by xudong963** [comment]
🎉

**Comment by rdettai** [comment]
Thanks @Dandandan ! Can you quickly explain what the reason for the slowdown was exactly?

**Comment by Dandandan** [comment]
> Thanks @Dandandan ! Can you quickly explain what the reason for the slowdown was exactly?

As far as I can explain:

The earlier code used the `parquet`-based API to read from a file, which uses a `BufReader` internally, which is crucial for the performance.

By introducing the object storage abstraction, we were directly reading from a `File` instance without any buffering in between, i.e. having lot's of extra calls to the OS (as you also hinted at in #1363).
This leads to both slowdown in loading the data but also was very expensive in the part that reads metadata /statistics (which normally takes something like <1ms locally). Probably that part does many small `read` calls.

By wrapping the `File` instance in the `BufReader` we avoid those calls to the OS.

Maybe a potential improvement would be having a bit more control, such as setting the capacity of the buffer.
