### PR TITLE
[BugFix] abort plan if order by column not in select list

### LINKED ISSUE #5065: Incorrect results on queries with `distinct` and orderby
**Describe the bug**
Distinct is being applied incorrectly when the query has an order by

**To Reproduce**
```shell
cd datafusion-cli
cargo run
...
```
```sql
❯ create table foo as values (1, 2), (3, 4), (5, 6);
0 rows in set. Query took 0.000 seconds.
❯ select distinct '1' from foo;
+-----------+
| Utf8("1") |
+-----------+
| 1         |
+-----------+
1 row in set. Query took 0.001 seconds.
❯ select distinct '1' from foo order by column1;
+-----------+
| Utf8("1") |
+-----------+
| 1         |
| 1         |
| 1         |
+-----------+
```

**Expected behavior**
I expect `select distinct '1' from foo order by column1;` to produce an error, or posibly a single row

Here is postgres output:

```sql
postgres=# create table foo as values (1, 2), (3, 4), (5, 6);
SELECT 3
postgres=# select distinct '1' from foo;
 ?column? 
----------
 1
(1 row)

postgres=# select distinct '1' from foo order by column1;
ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: select distinct '1' from foo order by column1;
                                              ^
postgres=# 
```

**Additional context**
Found while looking into https://github.com/apache/arrow-datafusion/issues/4854

FWIW the logical order of operations is like this (from https://learnsql.com/blog/sql-order-of-operation)

image

### PR DESCRIPTION
**Pull request by xiaoyong-z**
# Which issue does this PR close?

Closes #5065

# Rationale for this change

Currently, if the order by column is not in select list, we will add_missing_columns to the select list.  This will lead to the bug in issue #5065.

# What changes are included in this PR?

In this pr, we modify the behaviour, for select distinct, we will throw error msg if order by expressions are not int select list.

# Are these changes tested?

yes 
# Are there any user-facing changes?

no

### CODE REVIEW

**Comment by xiaoyong-z** [comment]
image

**Comment by xiaoyong-z** [comment]
There are a few CI tests can not pass, in these tests, there will be order by columns not in select lists. For these tests, we will add the missing columns(in order by, but not in select).
In this pr, we disable the behaviour. 
Which behaviour do we want? @alamb

**Comment by alamb** [comment]
Thank you very much @xiaoyong-z -- this is looking great

> There are a few CI tests can not pass, in these tests, there will be order by columns not in select lists. For these tests, we will add the missing columns(in order by, but not in select).
> In this pr, we disable the behaviour.

I recommend following the postgres behavior which is to add the missing columns to the select list *UNLESS* there is a `DISTINCT` clause

Like this:


```sql
postgres=# create table foo as values (1, 'X'), (2, 'Y'), (3, 'Z'), (1, 'Y');
SELECT 4
postgres=# select column1 from foo order by column2;
 column1
---------
       1
       2
       1
       3
(4 rows)

postgres=# select distinct column1 from foo order by column2;
ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: select distinct column1 from foo order by column2;

postgres=# select distinct column1 from foo;
 column1
---------
       3
       2
       1
(3 rows)
```

**Comment by alamb** [comment]
Marking as draft as I think this code has been reviewed and will get updates prior to it being reviewed again

**Comment by xiaoyong-z** [comment]
image

**Comment by xiaoyong-z** [comment]
@alamb PTAL

**Review by alamb — APPROVED** [review]
LGTM -- thank you @xiaoyong-z

**Comment by alamb** [comment]
It looks like @jackwener  plans to review this PR as well. I'll wait another day to merge it to give him enough time to do so

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -403,6 +403,28 @@ impl LogicalPlanBuilder {
...
+        // then this plan is a select distinct plan
+        let is_select_distinct = match self.plan {
+            LogicalPlan::Distinct(_) => true,
+            LogicalPlan::Repartition(Repartition { ref input, .. }) => {
+                matches!(input.as_ref(), &LogicalPlan::Distinct(_))
+            }
+            _ => false,
+        };
+
+        // for select distinct, order by expressions must appear in select list
```
Comment (jackwener) [inline datafusion/expr/src/logical_plan/builder.rs:416]:
```suggestion
        // for select distinct, order by expressions must exist in select list
```

File: datafusion/core/tests/dataframe.rs [hunk 2]
```diff
@@ -124,6 +125,39 @@ async fn sort_on_unprojected_columns() -> Result<()> {
     Ok(())
 }
 
+#[tokio::test]
```
Comment (jackwener) [inline datafusion/core/tests/dataframe.rs:128]: I suggest to add those sql in comment into `sqllogicaltest`.
In this test, we can `data-derive-test`

Comment (jackwener) [reply datafusion/core/tests/dataframe.rs:128]: I also suggest add test in `datafusion/sql/tests/integration_test.rs`.
In this test, we can see the `Plantree` of plan to check those sql

**Review by jackwener — COMMENTED** [review]
A good job, Thanks @xiaoyong-z.
I think we can more test.

File: datafusion/core/tests/dataframe.rs (hunk 2 above)
Comment (liukun4515) [reply datafusion/core/tests/dataframe.rs:128]: same comments with @jackwener . It is better to add e2e test for this case in the `distinct` test or the `order by` test.

File: datafusion/expr/src/logical_plan/builder.rs [hunk 3]
```diff
@@ -403,6 +403,28 @@ impl LogicalPlanBuilder {
...
             })?;
 
+        // if current plan is distinct or current plan is repartition and its child plan is distinct,
+        // then this plan is a select distinct plan
+        let is_select_distinct = match self.plan {
+            LogicalPlan::Distinct(_) => true,
+            LogicalPlan::Repartition(Repartition { ref input, .. }) => {
+                matches!(input.as_ref(), &LogicalPlan::Distinct(_))
+            }
+            _ => false,
```
Comment (liukun4515) [inline datafusion/expr/src/logical_plan/builder.rs:413]: is there no other pattern to fit this case?
just below cases?
```
   sort column1
      repartition
         distinct
```

```
   sort column1
     distinct 
```

cc @alamb

Comment (alamb) [reply datafusion/expr/src/logical_plan/builder.rs:413]: So in my opinion this PR is better than the code on master, though I think it could be improved with the suggestions from @liukun4515 and @jackwener 

@xiaoyong-z  please let us know what you want to do -- we can merge and improve in a follow on or we can implement the suggestions in this PR

Comment (xiaoyong-z) [reply datafusion/expr/src/logical_plan/builder.rs:413]: I have added the sqllogictest and integration_test in this pr.

As you said, there may be some problems if you use DataFrame and LogicalPlanBuilder to build the plan.
>  if it is built directly (via a DataFrame or someone using LogicalPlanBuilder directly) it is probably incorrect to throw an error here (as they may have meant to to run the distinct before the sort for some reason

How about merge this pr currently, and i will improve it in a follow on pr.

File: datafusion/core/tests/sqllogictests/test_files/select.slt [hunk 4]
```diff
@@ -55,4 +55,29 @@ query IC rowsort
...
+
+# foo order by
+query I
+select '1' from foo order by column1;
+----
+1
+1
+1
+
+# foo distinct order by
```
Comment (alamb) [inline datafusion/core/tests/sqllogictests/test_files/select.slt:81]: 👍

**Review by alamb — APPROVED** [review]
Thanks again @liukun4515  and @xiaoyong-z 

I have filed https://github.com/apache/arrow-datafusion/issues/5255 to track the follow on work
