### PR TITLE
Proper resolution for old name in with_column_renamed

### LINKED ISSUE #4428: with_column_renamed is always a NO OP when table name is ?table?
```
let test_df = ctx.read_csv("test.csv",  CsvReadOptions::new()).await?;
let test_df = test_df.with_column_renamed("id", "renamedID")?;
println!("{:#?}", test_df.explain(true, true)?);
```

```
+---------------+-----------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                            |
+---------------+-----------------------------------------------------------------------------------------------------------------+
| logical_plan  | TableScan: ?table? projection=[id, name]                                                                        |
| physical_plan | CsvExec: files=[<>/test.csv], has_header=true, limit=None, projection=[id, name] |
|               |                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------+
```
This time using `?table?` as a qualifier
```
let test_df = ctx.read_csv("test.csv",  CsvReadOptions::new()).await?;
let test_df = test_df.with_column_renamed("?table?.id", "renamedID")?;
test_df.explain(false, false)?.show().await?;
```

```
Error: SchemaError(FieldNotFound { field: Column { relation: None, name: "?table?.id" }, valid_fields: Some([Column { relation: Some("?table?"), name: "id" }, Column { relation: Some("?table?"), name: "name" }]) })
```
This time registering table so it has a set table name
```
let test_df = ctx.read_csv("test.csv",  CsvReadOptions::new()).await?;
ctx.register_table("t1", test_df)?;
let test_df = ctx.table("t1")?;
let test_df = test_df.with_column_renamed("id", "renamedID")?;
test_df.explain(false, false)?.show().await?;
```

```
+---------------+-------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                              |
+---------------+-------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: ?table?.id, ?table?.name, alias=t1                                                                    |
|               |   TableScan: ?table? projection=[id, name]                                                                        |
| physical_plan | ProjectionExec: expr=[id@0 as id, name@1 as name]                                                                 |
|               |   CsvExec: files=[<>/test.csv], has_header=true, limit=None, projection=[id, name] |
|               |                                                                                                                   |
+---------------+-------------------------------------------------------------------------------------------------------------------+
```
This time registering table so it has a set table name and using that table name as a qualifier
```
let test_df = ctx.read_csv("test.csv",  CsvReadOptions::new()).await?;
ctx.register_table("t1", test_df)?;
let test_df = ctx.table("t1")?;
let test_df = test_df.with_column_renamed("t1.id", "renamedID")?;
test_df.explain(false, false)?.show().await?;
```

```
+---------------+---------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                |
+---------------+---------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: t1.id AS renamedId, t1.name                                                                             |
|               |   Projection: ?table?.id, ?table?.name, alias=t1                                                                    |
|               |     TableScan: ?table? projection=[id, name]                                                                        |
| physical_plan | ProjectionExec: expr=[id@0 as renamedId, name@1 as name]                                                            |
|               |   ProjectionExec: expr=[id@0 as id, name@1 as name]                                                                 |
|               |     CsvExec: files=[<>/test.csv], has_header=true, limit=None, projection=[id, name] |
|               |                                                                                                                     |
+---------------+---------------------------------------------------------------------------------------------------------------------+
```
I have two lines of thinking on this
1. `with_column_renamed` seems to be the only function in the DataFrame API that always requires the use of the fully qualified column name, this should be changed to use the unqualified column name.
2. Why are tables being set to `?table?` ? I assume this was chosen because it isn't valid sql but why not always generate a valid table name from functions like `ctx.read_csv()`. The current implementation is awkward because using `?table?` as a qualifier returns an error.

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #4428

# Rationale for this change

When calling `with_column_renamed("old", "new")` in DataFrame API, it should be able to look up `"old"` column name even if it is not qualified, for ease of use. 

# What changes are included in this PR?

If in plan there is column named `t1.c1` (where `t1` is the table name and `c1` is the column name) then allow "c1" for old_name to be able to refer to this column without needing to explicitly state the full qualified name

Also ensure do an ambiguity check when looking up the old column name

# Are these changes tested?

New unit tests added

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/dataframe.rs [hunk 1]
```diff
@@ -1681,22 +1689,59 @@ mod tests {
             ])?
             .with_column("sum", col("c2") + col("c3"))?;
 
-        let df_sum_renamed = df.with_column_renamed("sum", "total")?.collect().await?;
+        let df_sum_renamed = df
+            .with_column_renamed("sum", "total")?
+            // table qualifier optional
+            .with_column_renamed("c1", "one")?
+            // accepts table qualifier
+            .with_column_renamed("aggregate_test_100.c2", "two")?
```
Comment (alamb) [inline datafusion/core/src/dataframe.rs:1697]: 👍

**Review by alamb — APPROVED** [review]
makes sense to me -- thank you @Jefffrey
