### PR TITLE
Planner: normalize_ident only when enable_ident_normalization is enabled

### LINKED ISSUE #5626: SqltoRel doesn't honor enable_ident_normalization some cases
**Describe the bug**

When creating a logical plan using `SqlToRel` with options that do not `enable_ident_normalization`, identifiers still end up getting normalized in some cases.

**To Reproduce**

```rust
let sql = "SELECT UPPERCASE from test";
let dialect = GenericDialect {};
let ast = Parser::parse_sql(&dialect, sql).unwrap();
let statement = &ast[0];
let schema_provider = MySchemaProvider::new();
let options = ParserOptions {
    parse_float_as_decimal: false,
    enable_ident_normalization: false,
};
let sql_to_rel = SqlToRel::new_with_options(&schema_provider, options);
let plan = sql_to_rel.sql_statement_to_plan(statement.clone()).unwrap();
println!("{plan:?}");
```

Where `MySchemaProvider` has the following
```rust
tables.insert(
    "test".to_string(),
    create_table_source(vec![Field::new("UPPERCASE", DataType::Int32, false)]),
);
```

Leads to: 
```
SchemaError(FieldNotFound { field: Column { relation: None, name: "uppercase" }, valid_fields: [Column { relation: Some(Bare { table: "test" }), name: "UPPERCASE" }] })'
```
Definition of everything else is taken from this [example](https://github.com/apache/arrow-datafusion/blob/36fe9745407351277649ce07a12f036a2bb653a5/datafusion/sql/examples/sql.rs).

**Expected behavior**

When `enable_ident_normalization` is false, the identified `UPPERCASE` shouldn't be normalized to `uppercase`.

**Additional context**
Looks like this particular case stems from https://github.com/apache/arrow-datafusion/blob/36fe9745407351277649ce07a12f036a2bb653a5/datafusion/sql/src/expr/identifier.rs#L46-L48

but generally a few places use `utils::normalize_ident` instead of `planner::normalize_ident`.

### PR DESCRIPTION
**Pull request by ayushdg**
# Which issue does this PR close?

Closes #5626 

# Rationale for this change
Some part of the codebase use `sqlToRel`'s options for `enable_ident_normalization` to decide whether to normalize identifiers or not, but it isn't enforced consistently throughout the codebase.

# What changes are included in this PR?
Make planner:normalize_ident public.
All methods implementing `SqlToRel` use `enable_ident_normalization` while normalizing. 

# Are these changes tested?
- [x] Add tests

# Are there any user-facing changes?
No.

### CODE REVIEW

**Comment by ayushdg** [comment]
While working on this PR, I also noticed that there are places not related to the planner which also normalize names such as column. I wonder if it's valuable to also make these method configurable to enable ident normalization?

https://github.com/apache/arrow-datafusion/blob/c09edade14d456f1d2161c5ebb8c1e51e592a8ef/datafusion/common/src/column.rs#L73

**Comment by Jefffrey** [comment]
> While working on this PR, I also noticed that there are places not related to the planner which also normalize names such as column. I wonder if it's valuable to also make these method configurable to enable ident normalization?
> 
> https://github.com/apache/arrow-datafusion/blob/c09edade14d456f1d2161c5ebb8c1e51e592a8ef/datafusion/common/src/column.rs#L73

I had some thoughts about this previously (not this specific function, but still applicable): https://github.com/apache/arrow-datafusion/pull/5183#discussion_r1096603578

Generally I'm not sure how exactly to be able to toggle normalization at that level (the common crate) without API changes to dependent functions, like `from_qualified_name(...)` in `Column` as you've highlighted

File: datafusion/sql/src/planner.rs [hunk 1]
```diff
@@ -424,7 +424,7 @@ pub fn object_name_to_qualifier(
         .join(" AND ")
 }
 
-fn normalize_ident(id: Ident, enable_normalization: bool) -> String {
+pub fn normalize_ident(id: Ident, enable_normalization: bool) -> String {
```
Comment (alamb) [inline datafusion/sql/src/planner.rs:427]: What would you think about making `crate::utils::normalize_ident` pub instead? making something public that only does something if `true` is passed in seems somewhat strange to me

File: datafusion/sql/src/expr/identifier.rs [hunk 2]
```diff
@@ -47,7 +46,8 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
             // interpret names with '.' as if they were
             // compound identifiers, but this is not a compound
             // identifier. (e.g. it is "foo.bar" not foo.bar)
-            let normalize_ident = normalize_ident(id);
+            let normalize_ident =
```
Comment (alamb) [inline datafusion/sql/src/expr/identifier.rs:49]: It would be really nice to refactor the code to make it harder to miss such functions. Maybe we could add a struct like

```rust
struct IdentNormalizer {
  bool normalize;
}

impl IdentNormalizer {
  fn normalize(id: Ident) -> String {
  ...
   }
}
```

And then we could change `SqlToRel` so it had a normalizer field, and remove the `fn normalize_ident` entirely -- that way the compiler could help make sure there are no more missing `normalize_ident` callsites (b/c they would all have to be changed to `self.normalizer.normalize(...)`

**Review by alamb — APPROVED** [review]
Thank you @ayushdg 

I have some suggestions on how maybe to make this code better, but I also think what is here is better than what is on master so it could be merged as is.

**Comment by alamb** [comment]
@ayushdg  please let me know if you would to make changes to this PR or if we should merge it as is

File: datafusion/sql/src/expr/identifier.rs (hunk 2 above)
Comment (ayushdg) [reply datafusion/sql/src/expr/identifier.rs:49]: I agree that a refactor here to make normalize ident a part of the SqlToRel planner itself makes more sense that constantly getting this info from the options.

Comment (ayushdg) [reply datafusion/sql/src/expr/identifier.rs:49]: Do you have a preference for whether a new struct should be created to normalize ident or if we could just add the `normalize` method as an implementation for `SqlToRel`

File: datafusion/sql/src/statement.rs
Comment (ayushdg) [inline datafusion/sql/src/statement.rs:1]: In cases like this with helper methods that get called from `SqlToRel` impl methods is there a better approach than adding a normalizer argument to each of these methods?
https://github.com/apache/arrow-datafusion/blob/c5e935a15f22d16d8ca244e68b128f7c5ff28375/datafusion/sql/src/statement.rs#L54-L65

Comment (alamb) [reply datafusion/sql/src/statement.rs:1]: I can't think of any at the moment

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @ayushdg

**Comment by ayushdg** [comment]
Thanks @alamb let me know if anything else is needed, or if the pr is good to merge as is.
