### PR TITLE
Don't treat Null as UTF8(None) and change error info.

### LINKED ISSUE #2782: InList: Don't treat Null as UTF8(None)
Is it worth filing a follow on ticket to address? I am not 100% sure I understand what the end user facing bug would be (is it null is the wrong type?)

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/2764#discussion_r905386562_

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

Closes #2782 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/in_list.rs [hunk 1]
```diff
@@ -111,8 +111,7 @@ macro_rules! make_contains {
                 ColumnarValue::Scalar(s) => match s {
                     ScalarValue::$SCALAR_VALUE(Some(v)) => Some(*v),
                     ScalarValue::$SCALAR_VALUE(None) => None,
-                    ScalarValue::Utf8(None) => None,
-                    datatype => unimplemented!("Unexpected type {} for InList", datatype),
+                    datatype => unreachable!("InList can't reach other data type {} for {}.", datatype, s),
```
Comment (liukun4515) [inline datafusion/physical-expr/src/expressions/in_list.rs:114]: the expr and  list_expr has the same data type, the code can't reach this point

**Review by xudong963 — APPROVED** [review]

**Review by viirya — APPROVED** [review]
