### PR TITLE
Serialize timezone in timestamp scalar values

### LINKED ISSUE #2116: ScalarValue serialization loses timezone
**Describe the bug**

In `datafusion-proto`, `ScalarValue::TimestampX` disregards the optional timezone:
```rust
            datafusion::scalar::ScalarValue::TimestampNanosecond(val, _) => {
                create_proto_scalar(val, PrimitiveScalarType::TimeNanosecond, |s| {
                    Value::TimeNanosecondValue(*s)
                })
            }
```
As a result, the value will be deserialized to a `ScalarValue::TimestampX(<timestamp>,None)`. 

This will, for one thing, cause binary expression evaluation to fail if one operand is a timestamp literal and the other is a column expression for a column that has a timezone.  

**To Reproduce**

**Expected behavior**

The timestamp should be serialized in the proto message and preserved on deserialization. 

**Additional context**

### PR DESCRIPTION
**Pull request by thinkharderdev**
# Which issue does this PR close?

Closes #2116 

 # Rationale for this change

Optional timezone was not being serialized in the standard protobuf serialization of `ScalarValue`

# What changes are included in this PR?

Add timezone to the protobuf definitions and handle serialization/deserialization

# Are there any user-facing changes?

No

No

### CODE REVIEW

File: datafusion/proto/src/from_proto.rs [hunk 1]
```diff
@@ -581,12 +575,30 @@ impl TryFrom<&protobuf::scalar_value::Value> for ScalarValue {
...
-            }
             Value::IntervalYearmonthValue(v) => ScalarValue::IntervalYearMonth(Some(*v)),
             Value::IntervalDaytimeValue(v) => ScalarValue::IntervalDayTime(Some(*v)),
+            Value::TimestampValue(v) => {
+                let ts_value = v.value.as_ref().ok_or(Error::required("value"))?;
+                let timezone = if v.timezone.is_empty() {
+                    None
+                } else {
+                    Some(v.timezone.clone())
+                };
```
Comment (alamb) [inline datafusion/proto/src/from_proto.rs:586]: Maybe it could be written like this:
```suggestion
                let timezone = v.timezone.map(|v| Some(v.clone()))?
```

File: datafusion/proto/src/from_proto.rs [hunk 2]
```diff
@@ -829,10 +839,32 @@ impl TryFrom<&protobuf::ScalarValue> for ScalarValue {
                 )
             }
             Value::Date64Value(v) => Self::Date64(Some(*v)),
-            Value::TimeSecondValue(v) => Self::TimestampSecond(Some(*v), None),
-            Value::TimeMillisecondValue(v) => Self::TimestampMillisecond(Some(*v), None),
             Value::IntervalYearmonthValue(v) => Self::IntervalYearMonth(Some(*v)),
             Value::IntervalDaytimeValue(v) => Self::IntervalDayTime(Some(*v)),
+            Value::TimestampValue(v) => {
```
Comment (alamb) [inline datafusion/proto/src/from_proto.rs:844]: the replication is unfortunate but I see it is not something that got introduced with this PR

**Review by alamb — APPROVED** [review]
LGTM

**Review by yjshen — APPROVED** [review]
