### PR TITLE
fix: support decimal statistic for row group prune

### LINKED ISSUE #2962: Can't filter rowgroup for parquet prune for some data type
**Describe the bug**
In the `RowGroupPruningStatistics`, we use the statistics to prune the row group for parquet file.

In the below logical: 
https://github.com/apache/arrow-datafusion/blob/f386f7a7344d54455fe04d92248e373fac990e6d/datafusion/core/src/physical_plan/file_format/parquet.rs#L392
to get the min and max for a column.

But the logic has bug for the data type.

In the parquet, we can use `INT32`、`INT64` or `BINARY` to store decimal value, but in the below logical, we can't get the right type of the `ArrayRef`. 
**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

Closes #2962

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 1]
```diff
@@ -388,28 +391,82 @@ struct RowGroupPruningStatistics<'a> {
...
-    ($column_statistics:expr, $func:ident, $bytes_func:ident) => {{
+    ($column_statistics:expr, $func:ident, $bytes_func:ident, $target_arrow_type:expr) => {{
         if !$column_statistics.has_min_max_set() {
             return None;
         }
         match $column_statistics {
             ParquetStatistics::Boolean(s) => Some(ScalarValue::Boolean(Some(*s.$func()))),
-            ParquetStatistics::Int32(s) => Some(ScalarValue::Int32(Some(*s.$func()))),
-            ParquetStatistics::Int64(s) => Some(ScalarValue::Int64(Some(*s.$func()))),
+            ParquetStatistics::Int32(s) => {
```
Comment (liukun4515) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:419]: The value stored in the parquet file is unscaled number.
For example parquet decimal(9,2), the value of 1.23 will stored as 123 in the parquet file.

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 2]
```diff
@@ -462,6 +523,28 @@ macro_rules! get_null_count_values {
...
 
+/// Convert parquet column schema to arrow field.
+/// copy from arrow-rs
+/// TODO: consolidate code with arrow-rs
+/// TODO: change this API public in the arrow-rs
+/// crate::schema::parquet_to_arrow_field
+fn parquet_to_arrow_field(parquet_column: &ColumnDescriptor) -> Option<DataType> {
+    let type_ptr = parquet_column.self_type_ptr();
+    match type_ptr.get_basic_info().logical_type() {
+        // just handle the decimal type
```
Comment (liukun4515) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:534]: In this case, I just handle the decimal case, and don't change the logic for other data types.
Maybe there are bugs for other data types, I will add tests to check them.

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 3]
```diff
@@ -388,28 +391,82 @@ struct RowGroupPruningStatistics<'a> {
     parquet_schema: &'a Schema,
 }
 
+// TODO: consolidate code with arrow-rs
+// Convert the bytes array to i128.
+// The endian of the input bytes array must be big-endian.
+// Copy from the arrow-rs
+fn from_bytes_to_i128(b: &[u8]) -> i128 {
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:398]: Would it be possible to simply call `Decimal128::new()` here? https://docs.rs/arrow/19.0.0/arrow/util/decimal/struct.Decimal128.html#method.new

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 4]
```diff
@@ -388,28 +391,82 @@ struct RowGroupPruningStatistics<'a> {
...
+                    }
+                    _ => Some(ScalarValue::Int64(Some(*s.$func()))),
+                }
+            }
             // 96 bit ints not supported
             ParquetStatistics::Int96(_) => None,
             ParquetStatistics::Float(s) => Some(ScalarValue::Float32(Some(*s.$func()))),
             ParquetStatistics::Double(s) => Some(ScalarValue::Float64(Some(*s.$func()))),
             ParquetStatistics::ByteArray(s) => {
+                // TODO support decimal type for byte array type
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:450]: Should we track this in a ticket? Or maybe even implement it in this PR?

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 5]
```diff
@@ -462,6 +523,28 @@ macro_rules! get_null_count_values {
     }};
 }
 
+/// Convert parquet column schema to arrow field.
+/// Copy from arrow-rs
+/// TODO: consolidate code with arrow-rs
+/// TODO: change this API public in the arrow-rs
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:529]: Can you please file a ticket in arrow-rs describing the change needed and add a reference to the new ticket here?

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 2 above)
Comment (alamb) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:534]: Maybe we could rename the function to `parquet_to_arrow_decimal_field` or something to make it more clear that this only applies to decimal types

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 6]
```diff
@@ -1367,6 +1465,202 @@ mod tests {
...
+            // c1 > 5, this row group will not be included in the results.
+            vec![ParquetStatistics::int32(Some(10), Some(20), None, 0, false)],
+        );
+        let metrics = parquet_file_metrics();
+        assert_eq!(
+            prune_row_groups(&[rgm1, rgm2], None, Some(pruning_predicate), &metrics),
+            vec![0]
+        );
+
+        // INT32: c1 > 5, but parquet decimal type has different precision or scale to arrow decimal
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:1514]: 👍 this is a good case to test

Though I suggest you use something like `decimal(5,0)` where the difference in decimal types will result in significant errors rather than simply truncation

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 7]
```diff
@@ -1367,6 +1465,202 @@ mod tests {
...
+            }),
+            Some(9),
+            Some(0),
+            None,
+        )]);
+        let pruning_predicate =
+            PruningPredicate::try_new(expr, Arc::new(schema)).unwrap();
+        let rgm1 = get_row_group_meta_data(
+            &schema_descr,
+            // [100, 600]
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:1534]: Shouldn't `100` in the parquet file mean `100` (rather than `1.00`) if the type is `Decimal(9, 0)`?

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 3 above)
Comment (liukun4515) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:398]: `Decimal128::new()` can't be apply to this, because the length of [u8] must be 16 and with default little-endian.
The array of [u8] decoded from parquet may be not align with 16 bytes, and the endian of it is big-endian.
About the definition of parquet decimal data, you can read the [format spec](https://github.com/apache/parquet-format/blob/54e53e5d7794d383529dd30746378f19a12afd58/src/main/thrift/parquet.thrift#L66)

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 4 above)
Comment (liukun4515) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:450]: tracked by https://github.com/apache/arrow-datafusion/issues/2970

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 7 above)
Comment (liukun4515) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:1534]: But the schema of this parquet column  is decimal(9,0), so the actual value of `Some(100)` is 100.

The parquet just store the unscaled number, this is define by the parquet spec format.

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 5 above)
Comment (liukun4515) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:529]: After go through the codebase, In the datafusion we just need to consider the decimal data type.

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 2 above)
Comment (liukun4515) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:534]: change the function name to `parquet_to_arrow_decimal_type`

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 5 above)
Comment (liukun4515) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:529]: I remove the `TODO` and don't need a ticket to track it.

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 6 above)
Comment (liukun4515) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:1514]: I will change the arrow data type from `decimal(9,2)` to `decimal(5,2)`.
This changes will bring a different precision and scale when compare/filter data.

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 4 above)
Comment (alamb) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:450]:
```suggestion
                // TODO support decimal type for byte array type
                // https://github.com/apache/arrow-datafusion/issues/2970
```

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 7 above)
Comment (alamb) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:1530]: >  the schema of this parquet column is decimal(9,0), so the actual value of Some(100) is 100.

Got it -- thank you

**Review by alamb — APPROVED** [review]
Thanks @liukun4515
