### PR TITLE
bugfix: fix eval `nullalbe()` in `simplify_exprs`

### LINKED ISSUE #5191: simplify_expr() invoke nullable() exist bug
**Describe the bug**
When invoke nullable(), if plan is semi/anti join, all_schema() only just contain one side child output.
If we want to compute expr, it will fail.
like:
```sql
t1 semi join t2 on t1.id = t2.id
```
due to schema just is `[t1.id] (join), [t1.id](left) , [t2.id] (right)`.

so  `t1.id = t2.id` can't invoke `nullable()`

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #5191.

# Rationale for this change

# What changes are included in this PR?

Remove use `all_schemas()`  but use the plan schema + children_merge_schema().

set `pub skip_failed_rules: bool, default = false`

Before this PR, `right_anti_filter_push_down` and `right_semi_with_alias_filter` will fail.
After this PR, they will success.

# Are these changes tested?

Current test can cover it (we just need to disable skip_fail)

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs [hunk 1]
```diff
@@ -59,13 +60,12 @@ impl SimplifyExpressions {
...
-        // to evaluate expression types. For example, a projection plan's schema will only include
-        // projected columns. With just the projected schema, it's not possible to infer types for
-        // expressions that references non-projected columns within the same project plan or its
-        // children plans.
-        let info = plan
-            .all_schemas()
+        // Pass down the `children merge schema` and `plan schema` to evaluate expression types.
+        // pass all `child schema` and `plan schema` isn't enough, because like `t1 semi join t2 on
+        // on t1.id = t2.id`, each individual schema can't contain all the columns in it.
+        let children_merge_schema = DFSchemaRef::new(merge_schema(plan.inputs()));
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs:66]: In some ways, it seems to me that we should *only* be using the children's schemas as the expressions *within* he `LogicalPlan` should be in terms of the plan's inputs (the children's schemas) not the plan's output (`plan.schema()`)

**Review by alamb — COMMENTED** [review]
Thank you @jackwener  

Is there some test we could write that would show the effect of this change?

**Comment by jackwener** [comment]
> Is there some test we could write that would show the effect of this change?

current tests can cover this problem, but it was hidden by `skip_failed_rules`.

set `pub skip_failed_rules: bool, default = false`

Before this PR, `right_anti_filter_push_down` and `right_semi_with_alias_filter` will fail.
After this PR, they will success.

File: datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs (hunk 1 above)
Comment (jackwener) [reply datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs:66]: > it seems to me that we should only be using the children's schemas.

I can't agree with it more.

But current code get attribution of some Expression by get it from `plan.schema()` instead of inferring/computing them from children ouput.

For example, some test will fail like `csv_query_group_by_and_having_and_where`.

Comment (alamb) [reply datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs:66]: Something else to work on over time, perhaps

**Review by alamb — APPROVED** [review]
> current tests can cover this problem, but it was hidden by skip_failed_rules.

👍 
Sounds good. Thank you @jackwener
