### PR TITLE
fix: correct expected error in test

### LINKED ISSUE #5217: The test `in_list_types_struct_literal` fails when setting `skip_failed_rules` as `false`
**Describe the bug**
```
---- physical_plan::planner::tests::in_list_types_struct_literal stdout ----
thread 'physical_plan::planner::tests::in_list_types_struct_literal' panicked at 'Can not find expected in actual.

Expected:
The data type inlist should be same, the value type is Boolean, one of list expr type is Struct([Field { name: "foo", data_type: Boolean, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }])

Actual:
type_coercion
caused by
Internal error: Optimizer rule 'type_coercion' failed due to unexpected error: Error during planning: Can not find compatible types to compare Boolean with [Struct([Field { name: "foo", data_type: Boolean, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }]), Utf8]. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker', datafusion/core/src/physical_plan/planner.rs:2194:9
```

**To Reproduce**
1. set `skip_failed_rules` to `false`
2. run `cargo test --all`

**Expected behavior**
The test should pass.

**Additional context**

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #5217.
Part of #4685

# Rationale for this change

# What changes are included in this PR?

No need, current tests can cover this problem, but it was hidden by skip_failed_rules.

set `pub skip_failed_rules: bool, default = false`

Before this PR, `cast_string_to_time` and `in_list_types_struct_literal` will fail.
After this PR, they will success.

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by jackwener** [comment]
cc @HaoYang670

**Comment by jackwener** [comment]
This PR must be with disable skip config

**Comment by HaoYang670** [comment]
@jackwener If the error returned from `type_coercion` is the expected behavior, we can fix these when fixing #4615

**Comment by jackwener** [comment]
> ~@jackwener If the error returned from `type_coercion` is the expected behavior, we can fix these when fixing #4615~ @jackwener, could you try something like this to set `skip_failed_rules` to `false` in the test? I tested it on my desktop and it can work.
> 
> ```rust
> async fn cast_string_to_time() {
>     let config = SessionConfig::new().set("datafusion.optimizer.skip_failed_rules", ScalarValue::Boolean(Some(false)));
>     let ctx = SessionContext::with_config(config);
> ```

It's great idea. thanks you! @HaoYang670

File: datafusion/core/src/physical_plan/planner.rs [hunk 1]
```diff
@@ -2191,7 +2190,12 @@ mod tests {
             .build()?;
         let e = plan(&logical_plan).await.unwrap_err().to_string();
 
-        assert_contains!(&e, "The data type inlist should be same, the value type is Boolean, one of list expr type is Struct([Field { name: \"foo\", data_type: Boolean, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }])");
+        assert_contains!(
+            &e,
+            r#"type_coercion
+caused by
+Internal error: Optimizer rule 'type_coercion' failed due to unexpected error: Error during planning: Can not find compatible types to compare Boolean with [Struct([Field { name: "foo", data_type: Boolean, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }]), Utf8]. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker"#
+        );
```
Comment (HaoYang670) [inline datafusion/core/src/physical_plan/planner.rs:2198]: We should update this error message somehow, because it is a type error, not a bug in Datafusion. 
We could do this in the following PRs.

File: datafusion/core/tests/sql/timestamp.rs [hunk 2]
```diff
@@ -1070,15 +1075,19 @@ async fn cast_string_to_time() {
     let result = try_execute_to_batches(&ctx, sql).await;
     assert_eq!(
         result.err().unwrap().to_string(),
-        "Arrow error: Cast error: Cannot cast string 'not a time' to value of Time64(Nanosecond) type"
+        "simplify_expressions\ncaused by\nInternal error: Optimizer rule 'simplify_expressions' failed due to unexpected error: \
+        Arrow error: Cast error: Cannot cast string 'not a time' to value of Time64(Nanosecond) type. \
+        This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker"
```
Comment (HaoYang670) [inline datafusion/core/tests/sql/timestamp.rs:1080]: Ditto. We should find a way to update the error message when the error is expected. However, this is not a big deal now, because the default value of `skip_failed_rules` is `false` and customers won't see this error message.

File: datafusion/core/tests/sql/timestamp.rs [hunk 3]
```diff
@@ -1070,15 +1075,19 @@ async fn cast_string_to_time() {
...
     );
 
     // An invalid time
     let sql = "SELECT TIME '24:01:02' as time;";
     let result = try_execute_to_batches(&ctx, sql).await;
     assert_eq!(
         result.err().unwrap().to_string(),
-        "Arrow error: Cast error: Cannot cast string '24:01:02' to value of Time64(Nanosecond) type"
+        "simplify_expressions\ncaused by\nInternal error: Optimizer rule 'simplify_expressions' failed due to unexpected error: \
```
Comment (HaoYang670) [inline datafusion/core/tests/sql/timestamp.rs:1088]: Ditto.

**Review by HaoYang670 — COMMENTED** [review]
LGTM.

**Review by HaoYang670 — APPROVED** [review]

File: datafusion/core/src/physical_plan/planner.rs (hunk 1 above)
Comment (jackwener) [reply datafusion/core/src/physical_plan/planner.rs:2198]: Agree with you.
I should we can do it in next PR.
