### PR TITLE
Take the top level `schema` into account when creating `UnionExec`

### LINKED ISSUE #4677: Create physical plan bug: got Arrow schema with 1  and DataFusion schema with 0
**Describe the bug**

Create a table and insert some values:

```sql
CREATE TABLE integers(i INTEGER);

INSERT INTO integers VALUES (0), (1), (2), (3), (4);
```

Execute following SQL:

```sql
SELECT COUNT(*) FROM (SELECT * FROM integers UNION ALL SELECT * FROM integers LIMIT 7) tbl;
```

Report error from datafusion:

```
create_physical_expr expected same number of fields, got got Arrow schema with 1  and DataFusion schema with 0. 
This was likely caused by a bug in DataFusion’s code and we would welcome that you file an bug report
 in our issue tracker
```

The subquery works:

```sql
SELECT * FROM integers UNION ALL SELECT * FROM integers LIMIT 7;

+-----------------------+
| i |
+-----------------------+
| 0                     |
| 1                     |
| 2                     |
| 3                     |
| 4                     |
| 0                     |
| 1                     |
+-----------------------+
```

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>

# Which issue does this PR close?

Closes #4677.

# Rationale for this change

When creating `UnionExec` from `LogicalPlan::Union`, the schema of the top plan is ignored. This could cause errors when the top level schema doesn't match the child schema. (see the example in #4677)

## Before
```sql
❯ create table t as select 1 as a;
0 rows in set. Query took 0.014 seconds.
❯ select count(*) from (select a from t union all select a from t);
Internal("create_physical_expr expected same number of fields, got got Arrow schema with 1  and DataFusion schema with 0")
```

## After
```sql
❯ create table t as select 1 as a;
0 rows in set. Query took 0.014 seconds.
❯ select count(*) from (select a from t union all select a from t);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 2               |
+-----------------+
1 row in set. Query took 0.010 seconds.
```

# What changes are included in this PR?
1.  a new function `try_new_with_schema` for creating `UnionExec`
2. When building physical plans, if the top level schema is a subset of the child schema, then use `try_new_schema`, else use `new`

# Are these changes tested?
Yes.

# Are there any user-facing changes?
No.

### CODE REVIEW

File: datafusion/core/tests/sql/union.rs [hunk 1]
```diff
@@ -80,6 +80,23 @@ async fn union_all_with_aggregate() -> Result<()> {
     Ok(())
 }
 
+#[tokio::test]
+async fn union_all_with_count() -> Result<()> {
+    let ctx = SessionContext::new();
+    execute_to_batches(&ctx, "CREATE table t as SELECT 1 as a").await;
+    let sql = "SELECT COUNT(*) FROM (SELECT a from t UNION ALL SELECT a from t)";
```
Comment (alamb) [inline datafusion/core/tests/sql/union.rs:87]: 👍  agrees with postgres:

```sql
postgres=# CREATE table t as SELECT 1 as a;
SELECT 1
postgres=# SELECT COUNT(*) FROM (SELECT a from t UNION ALL SELECT a from t);
ERROR:  subquery in FROM must have an alias
LINE 1: SELECT COUNT(*) FROM (SELECT a from t UNION ALL SELECT a fro...
                             ^
HINT:  For example, FROM (SELECT ...) [AS] foo.
postgres=# SELECT COUNT(*) FROM (SELECT a from t UNION ALL SELECT a from t) as sq;
 count 
-------
     2
(1 row)
```

File: datafusion/core/src/physical_plan/planner.rs [hunk 2]
```diff
@@ -773,12 +773,19 @@ impl DefaultPhysicalPlanner {
...
                     Ok(Arc::new(FilterExec::try_new(runtime_expr, physical_input)?))
                 }
-                LogicalPlan::Union(Union { inputs, .. }) => {
+                LogicalPlan::Union(Union { inputs, schema }) => {
                     let physical_plans = futures::stream::iter(inputs)
                         .then(|lp| self.create_initial_plan(lp, session_state))
                         .try_collect::<Vec<_>>()
                         .await?;
-                    Ok(Arc::new(UnionExec::new(physical_plans)))
+                    if schema.fields().len() < physical_plans[0].schema().fields().len() {
```
Comment (alamb) [inline datafusion/core/src/physical_plan/planner.rs:781]: I wonder what is the reason to not always run `UnionExec::try_new_with_schema`?

**Review by alamb — APPROVED** [review]
Thank you @HaoYang670  -- looks good to me

I tried this on main and it fails:

```sql
DataFusion CLI v15.0.0
❯ CREATE table t as SELECT 1 as a;
0 rows in set. Query took 0.022 seconds.
❯ SELECT COUNT(*) FROM (SELECT a from t UNION ALL SELECT a from t);
Internal("create_physical_expr expected same number of fields, got got Arrow schema with 1  and DataFusion schema with 0")
❯ 
```

And it passes after this PR 👍

File: datafusion/core/src/physical_plan/planner.rs (hunk 2 above)
Comment (HaoYang670) [reply datafusion/core/src/physical_plan/planner.rs:781]: The original implementation ignores the top level schema, but I don't know why. (Maybe @gandronchik knows more about it). So I try to minimize the scope of this change to avoid introducing new bugs.

File: datafusion/core/tests/sql/union.rs (hunk 1 above)
Comment (HaoYang670) [reply datafusion/core/tests/sql/union.rs:87]: BTW, I'm not sure if it was a bug, but the `PushDownProjection` doesn't push down the empty projection to the child plans of `Union` in this example. Maybe @jackwener knows more about it.

File: datafusion/core/src/physical_plan/planner.rs (hunk 2 above)
Comment (alamb) [reply datafusion/core/src/physical_plan/planner.rs:781]: Sounds good -- maybe I'll try to simply the code once we have merged this PR

File: datafusion/core/tests/sql/union.rs (hunk 1 above)
Comment (jackwener) [reply datafusion/core/tests/sql/union.rs:87]: > BTW, I'm not sure if it was a bug, but the `PushDownProjection` doesn't push down the empty projection to the child plans of `Union` in this example. Maybe @jackwener knows more about it.

we need an issue to track this problem, I think there are some different ways of dealing with this problem.

**Review by jackwener — APPROVED** [review]
A great job to me.

But I am a little confusing about this PR. Why we can't correct the LogicalPlan but fix them in PhysicalPlan?
Current problem is cause by `schema`, maybe we fix `schema` in LogicalPlan?

File: datafusion/core/tests/sql/union.rs (hunk 1 above)
Comment (HaoYang670) [reply datafusion/core/tests/sql/union.rs:87]: Could you please file an issue @jackwener ?

File: datafusion/core/src/physical_plan/planner.rs (hunk 2 above)
Comment (HaoYang670) [reply datafusion/core/src/physical_plan/planner.rs:781]: Hmm, after double thinking, I am uncertain whether it is correct to ignore the top level schema when generating physical plans. It would lose the information about type coercion and metadata.

**Comment by alamb** [comment]
I feel like this PR is good enough to merge in the sense that a query that used to fail now runs correctly and there is additional test coverage. It sounds like there are likely more improvements possible as well

Thanks for the comments and review @jackwener  and @HaoYang670

**Comment by HaoYang670** [comment]
> A great job to me.
> 
> But I am a little confusing about this PR. Why we can't correct the LogicalPlan but fix them in PhysicalPlan? Current problem is cause by `schema`, maybe we fix `schema` in LogicalPlan?

We could revert this PR if the bug in logical optimizer could be solved. This PR is just a quick fix.
