### PR TITLE
fix: coalesce function should return correct data type

### LINKED ISSUE #9458: `coalesce` function returns incorrect result
### Describe the bug

Currently `coalesce` function's return type is determined by a fixed list of `SUPPORTED_COALESCE_TYPES`. If the data type of input arguments are not in the list, DataFusion will coerce input arguments. It produces some weird results.

For example, if the input arguments are `[Data32, Date32]`, because `SUPPORTED_COALESCE_TYPES ` doesn't include `Date32`, the return type of `coalesce` function will be `Utf8`.

This doesn't look like correct based on the definition of `coalesce` function which should return first non-null value from the arguments. As the input arguments are same type, there is no need to apply a coerced type on them (`Utf8`).

`coalesce` function simply checks null bits from input arrays,  and zip input arrays accordingly. DataFusion doesn't manipulate the arrays but relies on arrow-rs kernels like `and`, `zip`, etc. Looks like we don't need to limit the input types of `coalesce` to `SUPPORTED_COALESCE_TYPES`.

The current approach is strange especially it determines the return type before coercing the input arguments. So we can construct a `coalesce` function with `[Data32, Date32]` inputs and its return type is `Utf8`. It is especially an issue for projects like Comet which only uses DataFusion physical plans, so we don't pass through the type coercion phrase of logical plan in DataFusion. So in Comet, when we construct a `coalesce` function with `[Data32, Date32]` inputs, the function will actually produce a `Date32` array but the schema is `Utf8`.

I believe when we construct `coalesce` function, we should make sure its return type match its input types.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #9458.

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]

**Comment by viirya** [comment]
Some remaining test failures are unrelated. But some seem related. I'll keep looking into them.

File: datafusion/expr/src/type_coercion/functions.rs [hunk 1]
```diff
@@ -408,8 +412,19 @@ fn coerced_from<'a>(
...
-        _ => None,
+        // More coerce rules.
+        // Note that not all rules in `comparison_coercion` can be reused here.
+        // For example, all numeric types can be coerced into Utf8 for comparison,
+        // but not for function arguments.
+        _ => comparison_binary_numeric_coercion(type_into, type_from).and_then(
+            |coerced_type| {
+                if *type_into == coerced_type {
+                    Some(coerced_type)
+                } else {
```
Comment (viirya) [inline datafusion/expr/src/type_coercion/functions.rs:423]: For function argument, we want to coerce to exact the type (valid type) instead of third type.

File: datafusion/physical-expr/src/math_expressions.rs [hunk 2]
```diff
@@ -92,8 +93,9 @@ macro_rules! downcast_arg {
     ($ARG:expr, $NAME:expr, $ARRAY_TYPE:ident) => {{
         $ARG.as_any().downcast_ref::<$ARRAY_TYPE>().ok_or_else(|| {
             DataFusionError::Internal(format!(
-                "could not cast {} to {}",
+                "could not cast {} from {} to {}",
                 $NAME,
+                $ARG.data_type(),
                 type_name::<$ARRAY_TYPE>()
             ))
```
Comment (viirya) [inline datafusion/physical-expr/src/math_expressions.rs:100]: When I debug, I found that it is a more useful error message to show the source data type too.

**Comment by viirya** [comment]
Thanks @Dandandan
