### PR TITLE
Check placeholder  __timeTo and return Datafusion::Plan error

### LINKED ISSUE #5005: Invalid Placeholders return internal error (rather than Plan error)
**Describe the bug**
DataFusion supports numeric `$1` type placeholders not `$__timeTo` which is fine

However, when a invalid placeholder is specified an Internal error results which in many systems results in the message being masked from the user. 

**To Reproduce**
in DataFusion CL
```sql
❯ select $__timeTo;
Internal("Invalid placeholder, not a number: $__timeTo")
```

**Expected behavior**
I expect a planning error (DataFusionError::Plan)` rather than internal

**Additional context**

### PR DESCRIPTION
**Pull request by matthias-Q**
# Which issue does this PR close?

Closes #5005 .

# Rationale for this change

As suggested by  @alamb in #5005, we are catching the parameter `$__timeTo` and returning `DatafusionError::Plan` error

# What changes are included in this PR?

* check the param to match `__timeTo` 
* created a test in 

# Are these changes tested?

yes

# Are there any user-facing changes?

Specific error message when this parameter is used.

----
P.S.: This is my first commit to Datafusion. I hope this is ok. Tell me, if I misunderstood the issue. Thanks for the great project!

### CODE REVIEW

File: datafusion/sql/src/expr/value.rs [hunk 1]
```diff
@@ -96,13 +96,20 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
-                )));
+                if &param[1..] == "__timeTo" {
+                    return Err(DataFusionError::Plan(format!(
+                        "Placeholder not supported: {param}"
+                    )));
+                } else {
+                    return Err(DataFusionError::Internal(format!(
+                        "Invalid placeholder, not a number: {param}"
+                    )));
+                }
```
Comment (alamb) [inline datafusion/sql/src/expr/value.rs:112]: I think in general, parameters like `$__foo` are not valid and should cause an error. I don't think there is anything special about `$__timeTo` other than it happened to be the example I had. 

What would you think about

```suggestion
                return Err(DataFusionError::Plan(format!(
                    "Invalid placeholder, not a number: {param}"
                )));
```

File: datafusion/sql/tests/integration_test.rs [hunk 2]
```diff
@@ -3112,6 +3112,15 @@ fn test_prepare_statement_to_plan_panic_param_format() {
     logical_plan(sql).unwrap();
```
Comment (alamb) [inline datafusion/sql/tests/integration_test.rs:3112]: We could probably update this previous test to change Internal / Plan rather than adding a new test

**Review by alamb — COMMENTED** [review]
Thank you for the contribution @matthias-Q  -- I am sorry if I was unclear in the ticket and implied that `__timeTo` needed special handling. I think *all* parameter parse errors should be planning errors rather than just `$__timeTo`

File: datafusion/sql/src/expr/value.rs (hunk 1 above)
Comment (matthias-Q) [reply datafusion/sql/src/expr/value.rs:112]: Ah, this was actually my first attempt, but it sounded too easy.

I will implement it this way. Thanks for clarification

File: datafusion/sql/tests/integration_test.rs (hunk 2 above)
Comment (matthias-Q) [reply datafusion/sql/tests/integration_test.rs]: Sure, no problem. This test is not needed then.

**Review by alamb — APPROVED** [review]
Looks good -- thank you @matthias-Q

**Comment by alamb** [comment]
Thanks again @matthias-Q
