### PR TITLE
Fix pruning on not equal predicate

### LINKED ISSUE #560: Pruning on `!=` predicate results in incorrect results
**Describe the bug**
The logic for pruning on `!=` predicates introduced in https://github.com/apache/arrow-datafusion/pull/544  is incorrect

**To Reproduce**
Use the pruning logic with a `!=` predicate where the range covers the expression

So like `s != M` where the min/max is `A` -> `Z`. 

**Expected behavior**
Must check all values in block (as s!=M might be true for every one)

Actual behavior: Pruning logic says we must look at it. 

**Additional context**
I found this issue when integrating / testing DataFusion into IOx here: https://github.com/influxdata/influxdb_iox/pull/1721#issuecomment-860858033

### PR DESCRIPTION
**Pull request by alamb**
Closes #560 

# Rationale for this change
Logic is incorrect. The only way we can tell for sure that a predicate of `col != literal` is always false, is if both the min and max are `literal` (aka there is a single value in the column)

# What changes are included in this PR?
1. Fix up  https://github.com/apache/arrow-datafusion/commit/2568323dbd85e05f2bf3e6e484f7cc39983ff26c / #544
2. Add a test with expected results

### CODE REVIEW

File: datafusion/src/physical_optimizer/pruning.rs [hunk 1]
```diff
@@ -1190,6 +1162,34 @@ mod tests {
...
+
+        // s1 [A, Z] ==> might have values that pass predicate
+        // s1 [A, L] ==> all rows pass the predicate
+        // s1 [N, Z] ==> all rows pass the predicate
+        // No stats for s2 ==> some rows could pass
+        // s2 [3, None] (null max) ==> some rows could pass
+
+        let p = PruningPredicate::try_new(&expr, schema).unwrap();
+        let result = p.prune(&statistics).unwrap();
+        let expected = vec![true, true, true, true, true];
```
Comment (alamb) [inline datafusion/src/physical_optimizer/pruning.rs:1188]: On master this test fails thusly:


```
---- physical_optimizer::pruning::tests::prune_not_eq_data stdout ----
thread 'physical_optimizer::pruning::tests::prune_not_eq_data' panicked at 'assertion failed: `(left == right)`
  left: `[false, true, true, true, true]`,
 right: `[true, true, true, true, true]`', datafusion/src/physical_optimizer/pruning.rs:1220:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Comment (alamb) [reply datafusion/src/physical_optimizer/pruning.rs]: (aka it incorrectly prunes out the range of `A -> Z`)

**Comment by alamb** [comment]
I actually think I can still support not equals, I just need to make it a bit more restricted

**Comment by alamb** [comment]
fyi @jgoday

**Review by Dandandan — APPROVED** [review]
Great that this was caught by InfluxDB tests, seems correct now to me.

**Comment by jgoday** [comment]
> fyi @jgoday

@alamb, Sorry for introducing the bug, prune_not_eq_data test is much clearer to me now. Thank you!

**Comment by alamb** [comment]
> @alamb, Sorry for introducing the bug, prune_not_eq_data test is much clearer to me now. Thank you!

No worries @jgoday  -- both @Dandandan  and I missed it on the review as well! This is tricky stuff

File: datafusion/src/physical_optimizer/pruning.rs [hunk 2]
```diff
@@ -1190,6 +1192,34 @@ mod tests {
...
+    fn prune_not_eq_data() {
+        let schema = Arc::new(Schema::new(vec![Field::new("s1", DataType::Utf8, true)]));
+
+        // Prune using s2 != 'M'
+        let expr = col("s1").not_eq(lit("M"));
+
+        let statistics = TestStatistics::new().with(
+            "s1",
+            ContainerStats::new_utf8(
+                vec![Some("A"), Some("A"), Some("N"), Some("M"), None, Some("A")], // min
```
Comment (Dandandan) [inline datafusion/src/physical_optimizer/pruning.rs:1205]: What about M / N ?

File: datafusion/src/physical_optimizer/pruning.rs [hunk 3]
```diff
@@ -553,12 +553,14 @@ fn build_predicate_expression(
...
+            // column != literal => (min, max) = literal =>
+            // !(min != literal && max != literal) ==>
+            // min != literal || literal != max
             let min_column_expr = expr_builder.min_column_expr()?;
             let max_column_expr = expr_builder.max_column_expr()?;
             min_column_expr
-                .gt(expr_builder.scalar_expr().clone())
-                .or(expr_builder.scalar_expr().clone().gt(max_column_expr))
+                .not_eq(expr_builder.scalar_expr().clone())
+                .or(expr_builder.scalar_expr().clone().not_eq(max_column_expr))
```
Comment (Dandandan) [inline datafusion/src/physical_optimizer/pruning.rs:563]: Shouldn't this be `and`?

Comment (Dandandan) [reply datafusion/src/physical_optimizer/pruning.rs:563]: No - did some extra check - this seems the right thing.

File: datafusion/src/physical_optimizer/pruning.rs (hunk 2 above)
Comment (Dandandan) [reply datafusion/src/physical_optimizer/pruning.rs:1205]: This will also do the right thing 👍

File: datafusion/src/physical_optimizer/pruning.rs (hunk 3 above)
Comment (alamb) [reply datafusion/src/physical_optimizer/pruning.rs:563]: The way I think about it = predicate is effectively `!(col == min && col == max)` which when you apply Demorgan's law you get `(col != min) || (col != max)`
