### PR TITLE
fix(4981): incorrect error wrapping in `OnceFut`

### LINKED ISSUE #4981: Incorrect nested error wrapped to `ArrowError:External` variant for joins
**Describe the bug**
[This line of code](https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/physical_plan/joins/utils.rs#L695) makes impossible to get real reason of error.
```rs
.map_err(|e| ArrowError::ExternalError(e.to_string().into())),
```

It could produce such error: `External error: Arrow error: External error: Arrow error: External error: Arrow error: External error: Arrow error: Csv error: ...` as a **string-message**, not a type

That's actually really bad, because under `Csv error` it could be useful info. But instead of this I receive text error with too many nested `External` variants.

**To Reproduce**
Occurrence depends on execution plan and my data that caused this is rather large.
I believe it should be possible to cover with simple test of error type:
```rs
    #[tokio::test]
    async fn check_error_nesting() {
        let once_fut = OnceFut::<()>::new(async {
            Err(DataFusionError::ArrowError(ArrowError::CsvError("some error".to_string())))
        });

        struct TestFut(OnceFut<()>);
        impl Future for TestFut {
            type Output = ArrowResult<()>;

            fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
                match ready!((&mut self.0).get(cx)) {
                    Ok(()) => Poll::Ready(Ok(())),
                    Err(e) => Poll::Ready(Err(e)),
                }
            }
        }

        let res = TestFut(once_fut).await;
        let err = res.expect_err("future always return err");
        // ... some checks of error type

    }
```

**Expected behavior**
I expect to be able to take error type instead of message in string format.
However, I see that it's reference and need to figure out right way to handle this case. But current one breaks error handling system for datafustion.

**Additional context**
I would like to fix this behavior

And it probably make sense to request implementing `find_root` for `arrow` (like exists for datafusion error) - but that's out of scope

### PR DESCRIPTION
**Pull request by DDtKey**
# Which issue does this PR close?

Closes #4981

# Rationale for this change

I used approach with errors wrapped to `Arc` (I see it's common pattern in arrow & datafusion), because it should be shareable. 
I also created separate type alias for that

# What changes are included in this PR?

# Are these changes tested?

I've added test which failed before these changes. 

# Are there any user-facing changes?

### CODE REVIEW

**Comment by avantgardnerio** [comment]
@DDtKey does https://github.com/apache/arrow-datafusion/pull/4992 accomplish the same desired outcome?

**Comment by DDtKey** [comment]
> @DDtKey does https://github.com/apache/arrow-datafusion/pull/4992 accomplish the same desired outcome?

Don't think so, it was literally string instead of error. Take a look at code before these changes. It had `e.to_string()`

File: datafusion/core/src/physical_plan/joins/utils.rs [hunk 1]
```diff
@@ -438,7 +438,7 @@ impl<T: 'static> OnceAsync<T> {
 }
 
 /// The shared future type used internally within [`OnceAsync`]
-type OnceFutPending<T> = Shared<BoxFuture<'static, Arc<Result<T>>>>;
+type OnceFutPending<T> = Shared<BoxFuture<'static, Arc<SharedResult<T>>>>;
```
Comment (avantgardnerio) [inline datafusion/core/src/physical_plan/joins/utils.rs:441]: Now that `SharedResult` has an `Arc`, can we avoid the double-arc here?

File: datafusion/core/src/physical_plan/joins/utils.rs [hunk 2]
```diff
@@ -653,7 +653,7 @@ fn get_int_range(min: ScalarValue, max: ScalarValue) -> Option<usize> {
 
 enum OnceFutState<T> {
     Pending(OnceFutPending<T>),
-    Ready(Arc<Result<T>>),
+    Ready(Arc<SharedResult<T>>),
```
Comment (avantgardnerio) [inline datafusion/core/src/physical_plan/joins/utils.rs:656]: Same

**Review by avantgardnerio — APPROVED** [review]
I like it, I think the string hack was a clear shortcut, and removing it LGTM.

If it is possible to remove the double-arc, I'd like to do that before merging.

File: datafusion/core/src/physical_plan/joins/utils.rs (hunk 1 above)
Comment (DDtKey) [reply datafusion/core/src/physical_plan/joins/utils.rs]: `OnceFut` is cloneable, while `SharedResult` wraps only `Err` into `Arc` to allow cloning the error itself 🤔 

I decided to declare it as `SharedResult<Arc<T>>` instead, so it won't be `Arc` inside `Arc`. It will be either result or error wrapped into `Arc`.

Take a look at the last commit.

File: datafusion/common/src/error.rs [hunk 3]
```diff
@@ -36,6 +36,9 @@ use sqlparser::parser::ParserError;
 /// Result type for operations that could result in an [DataFusionError]
 pub type Result<T> = result::Result<T, DataFusionError>;
 
+/// Result type for operations that could result in an [DataFusionError] and needs to be shared (wrapped into `Arc`).
+pub type SharedResult<T> = result::Result<T, Arc<DataFusionError>>;
```
Comment (tustvold) [inline datafusion/common/src/error.rs:40]: Given this PR never actually returns this type, do we need to declare it here?

File: datafusion/core/src/physical_plan/joins/utils.rs [hunk 4]
```diff
@@ -653,7 +653,7 @@ fn get_int_range(min: ScalarValue, max: ScalarValue) -> Option<usize> {
 
 enum OnceFutState<T> {
     Pending(OnceFutPending<T>),
-    Ready(Arc<Result<T>>),
+    Ready(SharedResult<Arc<T>>),
```
Comment (tustvold) [inline datafusion/core/src/physical_plan/joins/utils.rs:656]:
```suggestion
    Ready(Arc<Result<T>>),
```
Perhaps?

File: datafusion/common/src/error.rs (hunk 3 above)
Comment (DDtKey) [reply datafusion/common/src/error.rs:40]: Well, I observed that `Result<T, Arc<Error>` is quite common approach to allow clonning errors in datafustion & arrow.

And not to miss such kind of errors, I think it would be nice to have it as general type. 
Take a look at #4992 and even current `find_root` impl, it's easy to forget that error could be wrapped into `Arc` actually (IMO)

I believe this type should be used when it's needed to explicitly declare that error is wrapped into `Arc`. And could be used in other places later.

File: datafusion/core/src/physical_plan/joins/utils.rs [hunk 5]
```diff
@@ -691,8 +695,8 @@ impl<T: 'static> OnceFut<T> {
             OnceFutState::Pending(_) => unreachable!(),
             OnceFutState::Ready(r) => Poll::Ready(
                 r.as_ref()
-                    .as_ref()
-                    .map_err(|e| ArrowError::ExternalError(e.to_string().into())),
+                    .map(|r| r.as_ref())
+                    .map_err(|e| ArrowError::ExternalError(Box::new(e.clone()))),
```
Comment (tustvold) [inline datafusion/core/src/physical_plan/joins/utils.rs:699]:
```suggestion
                    .map_err(|e| ArrowError::ExternalError(Box::new(e.clone()))),
```

**Review by tustvold — APPROVED** [review]
LGTM, I would suggest keeping SharedResult as an implementation detail, i.e. within utils have something like

```
type SharedResult<T> = std::result::Result<Arc<T>,Arc<DataFusionError>>;
```

File: datafusion/common/src/error.rs (hunk 3 above)
Comment (tustvold) [reply datafusion/common/src/error.rs:40]: > allow clonning errors in datafustion & arrow.

I don't see any other examples of this pattern?

Comment (alamb) [reply datafusion/common/src/error.rs:40]: See https://github.com/apache/arrow-datafusion/pull/4992 for the code (that does indeed walk over Arcs). It was non ideal however. Figuring out some way to avoid Arc'ing errors would be better in my opinion (not for this PR)

**Comment by alamb** [comment]
Thanks @DDtKey
