### PR TITLE
Ambiguity check for where selection

### LINKED ISSUE #4196: Add ambiguous check when generate selection plan
**Describe the bug**
Datafusion will try to generate inner join plan for selection, but it does not do ambiguous check.  
For example:
```sql
❯ explain select * from test0, test1 where c0 = c0 + 1;
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                    |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: test0.c0, test0.c1, test0.c2, test0.c3, test0.c4, test0.c5, test1.c0, test1.c1, test1.c2, test1.c3, test1.c4, test1.c5                                      |
|               |   CrossJoin:                                                                                                                                                            |
|               |     Projection: test0.c0, test0.c1, test0.c2, test0.c3, test0.c4, test0.c5                                                                                              |
|               |       Filter: CAST(test0.c0 AS Int64)test0.c0 = CAST(test0.c0 AS Int64)test0.c0 + Int64(1)                                                                              |
|               |         Projection: CAST(test0.c0 AS Int64) AS CAST(test0.c0 AS Int64)test0.c0, test0.c0, test0.c1, test0.c2, test0.c3, test0.c4, test0.c5                              |
|               |           TableScan: test0 projection=[c0, c1, c2, c3, c4, c5], partial_filters=[CAST(test0.c0 AS Int64) = CAST(test0.c0 AS Int64) + Int64(1)]                          |
|               |     TableScan: test1 projection=[c0, c1, c2, c3, c4, c5]        
```

In `PostgreSQL`, this will throw an error:
```sql
psql -d "$POSTGRES_DB" -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -c "explain select * from test0 as t0 inner join test0 as t1 on c0 = c0;"
ERROR:  column reference "c0" is ambiguous
LINE 1: ...select * from test0 as t0 inner join test0 as t1 on c0 = c0;
                                                               ^
```

The semantics of this sql is not clear, we need throw exception like `PostgreSQL` do.

**To Reproduce**
Create two tables -- test0 and test1, which has same schema.

run sql `explain select * from test0, test1 where c0 = c0 + 1`.

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #4196

# Rationale for this change

# What changes are included in this PR?

Check during sql where selection planning that columns aren't ambiguous. Also account for allowing outer query fields (if in an inner subquery)

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/sql/tests/integration_test.rs [hunk 1]
```diff
@@ -527,6 +527,16 @@ fn join_with_ambiguous_column() {
     quick_test(sql, expected);
 }
 
+#[test]
+fn where_selection_with_ambiguous_column() {
+    let sql = "SELECT * FROM person a, person b WHERE id = id + 1";
+    let err = logical_plan(sql).expect_err("query should have failed");
+    assert_eq!(
+        "Internal(\"column reference id is ambiguous\")",
```
Comment (alamb) [inline datafusion/sql/tests/integration_test.rs:535]: I think this error should be Plan (not Internal) as it was due to some bad input from the user rather than some bug in datafusion

We can fix that as a follow on PR as well

**Review by alamb — APPROVED** [review]
LGTM -- thank you @Jefffrey

File: datafusion/sql/tests/integration_test.rs (hunk 1 above)
Comment (Jefffrey) [reply datafusion/sql/tests/integration_test.rs]: no problem, fixed

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @Jefffrey !
