### PR TITLE
Fix the test failure of `size_of_scalar` failure on M1/M2 Mac

### LINKED ISSUE #3383: `scalar::tests::size_of_scalar` failed on M1 Mac
**Describe the bug**
Tested on M1 Mac:
```
failures:

---- scalar::tests::size_of_scalar stdout ----
thread 'scalar::tests::size_of_scalar' panicked at 'assertion failed: `(left == right)`
  left: `48`,
 right: `64`', datafusion/common/src/scalar.rs:2583:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>

# Which issue does this PR close?

Closes #3383.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by andygrove — CHANGES_REQUESTED** [review]
This fails for me on my AMD desktop:

```
---- scalar::tests::size_of_scalar stdout ----
thread 'scalar::tests::size_of_scalar' panicked at 'assertion failed: `(left == right)`
  left: `48`,
 right: `64`', datafusion/common/src/scalar.rs:2583:9
```

File: datafusion/common/src/scalar.rs [hunk 1]
```diff
@@ -2575,7 +2575,7 @@ mod tests {
         // The alignment requirements differ across architectures and
         // thus the size of the enum appears to as as well
 
-        let expected = match cfg!(target_arch = "aarch64") {
+        let expected = match cfg!(target_arch = "x86_64") {
             true => 64,
             false => 48,
```
Comment (Dandandan) [inline datafusion/common/src/scalar.rs:2580]: Shouldn't they both be `64`?

Comment (HaoYang670) [reply datafusion/common/src/scalar.rs:2580]: Actually, I am curious about how are `64` and `48` calculated here.

Comment (HaoYang670) [reply datafusion/common/src/scalar.rs:2580]: I find a doc about the layout of `Enum` (https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html#enum-layout-rules), and will learn it carefully

Comment (HaoYang670) [reply datafusion/common/src/scalar.rs:2580]: These 4 values seem to occupy largest memory
```rust
    TimestampSecond(Option<i64>, Option<String>), // 8 + 16 + 24
    /// Timestamp Milliseconds
    TimestampMillisecond(Option<i64>, Option<String>),
    /// Timestamp Microseconds
    TimestampMicrosecond(Option<i64>, Option<String>),
    /// Timestamp Nanoseconds
    TimestampNanosecond(Option<i64>, Option<String>),
```
The payload occupies 48 bytes and the tag occupies 1 byte (but this could be represented by niche?). So the overall size of the Enum if 48 I guess.

Comment (HaoYang670) [reply datafusion/common/src/scalar.rs]: > Shouldn't they both be `64`?

Maybe the both should be 48?

**Review by andygrove — APPROVED** [review]
This works for me on my M1 mac and AMD desktop

**Comment by andygrove** [comment]
I think we need to merge this before releasing 12.0.0.

@alamb @Dandandan any objection to merging this?

**Comment by Dandandan** [comment]
Go ahead :+1:

File: datafusion/common/src/scalar.rs [hunk 2]
```diff
@@ -2575,12 +2575,7 @@ mod tests {
         // The alignment requirements differ across architectures and
         // thus the size of the enum appears to as as well
 
-        let expected = match cfg!(target_arch = "aarch64") {
-            true => 64,
-            false => 48,
-        };
-
-        assert_eq!(std::mem::size_of::<ScalarValue>(), expected);
+        assert_eq!(std::mem::size_of::<ScalarValue>(), 48);
```
Comment (alamb) [inline datafusion/common/src/scalar.rs:2578]: fascinating -- perhaps rust has improved it support for aarch64
