### PR TITLE
fix: ignore panics if racing against catalog/schema changes

### LINKED ISSUE #6450: Panics if racing against catalog/schema changes
### Describe the bug

InformationSchemaConfig assumes every schema in list returned from `schema_names` is still present when it gets to them, but if the schema can change e.g. due to concurrent action by a second user, this will panic:

https://github.com/apache/arrow-datafusion/blob/444f0c42c4f37103c51eb8e0e92ad140727ca16f/datafusion/core/src/catalog/information_schema.rs#L79-L84

My recommendation would be to either change the trait to add a method iterating (name, schema) tuples, or in this case just `if let Some(schema) = catalog.schema(&schema_name) { ...` would be enough.

There's probably a similar race-induced panic on the other levels too, for catalog/schema/table.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Weijun-H**
# Which issue does this PR close?

Closes #6450

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/catalog/information_schema.rs [hunk 1]
```diff
@@ -81,15 +81,17 @@ impl InformationSchemaConfig {
...
-                            &catalog_name,
-                            &schema_name,
-                            &table_name,
-                            table.table_type(),
-                        );
+                    // schema name may not exist in the catalog, so we need to check
+                    if let Some(schema) = catalog.schema(&schema_name) {
+                        for table_name in schema.table_names() {
+                            let table = schema.table(&table_name).await.unwrap();
+                            builder.add_table(
```
Comment (alamb) [inline datafusion/core/src/catalog/information_schema.rs:88]: What do you think about applying the same change to `table(..).unwrap()` here and the other places below? 

I think as written the code will still be subject to race conditions (if tables are removed from `Schema`s)

Comment (Weijun-H) [reply datafusion/core/src/catalog/information_schema.rs]: Yes, it makes sense

**Review by alamb — APPROVED** [review]
Looks great -- thanks @Weijun-H
