### PR TITLE
Fix Display for List

### LINKED ISSUE #8259: Explain on a plan containing a list literal is very verbose in v33
### Describe the bug

The array within `ScalarValue::List` is printed as-is when explaining a plan containing a list literal. It makes the plan difficult to read.

### To Reproduce

``` sql
DataFusion CLI v33.0.0

❯ explain select make_array(1, 2, 3);
+---------------+----------------------------------------------------------+
| plan_type     | plan                                                     |
+---------------+----------------------------------------------------------+
| logical_plan  | Projection: List([ListArray                              |
|               | [                                                        |
|               |   PrimitiveArray<Int64>                                  |
|               | [                                                        |
|               |   1,                                                     |
|               |   2,                                                     |
|               |   3,                                                     |
|               | ],                                                       |
|               | ]]) AS make_array(Int64(1),Int64(2),Int64(3))            |
|               |   EmptyRelation                                          |
| physical_plan | ProjectionExec: expr=[+-----------+                      |
|               | | col       |                                            |
|               | +-----------+                                            |
|               | | [1, 2, 3] |                                            |
|               | +-----------+ as make_array(Int64(1),Int64(2),Int64(3))] |
|               |   EmptyExec: produce_one_row=true                        |
|               |                                                          |
+---------------+----------------------------------------------------------+
```

### Expected behavior

Something similar to the previous release. Here's the output from DataFusion v32.0.0

```sql
DataFusion CLI v32.0.0
❯ explain select make_array(1, 2, 3);
+---------------+------------------------------------------------------------------------+
| plan_type     | plan                                                                   |
+---------------+------------------------------------------------------------------------+
| logical_plan  | Projection: List([1,2,3]) AS make_array(Int64(1),Int64(2),Int64(3))    |
|               |   EmptyRelation                                                        |
| physical_plan | ProjectionExec: expr=[1,2,3 as make_array(Int64(1),Int64(2),Int64(3))] |
|               |   EmptyExec: produce_one_row=true                                      |
|               |                                                                        |
+---------------+------------------------------------------------------------------------+
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jayzhan211**
## Which issue does this PR close?

Closes #8259.

### CODE REVIEW

File: datafusion/common/src/scalar.rs [hunk 1]
```diff
@@ -2889,12 +2890,21 @@ impl fmt::Display for ScalarValue {
...
             },
-            ScalarValue::List(arr) | ScalarValue::FixedSizeList(arr) => write!(
-                f,
-                "{}",
-                arrow::util::pretty::pretty_format_columns("col", &[arr.to_owned()])
-                    .unwrap()
-            )?,
+            ScalarValue::List(arr) | ScalarValue::FixedSizeList(arr) => {
+                // TODO: Remove NullArray
+                // There are NullArray(0) currently, so we need to check the length
```
Comment (jayzhan211) [inline datafusion/common/src/scalar.rs:2895]: We may file an ticket to track it

File: datafusion/common/src/scalar.rs [hunk 2]
```diff
@@ -2889,12 +2890,21 @@ impl fmt::Display for ScalarValue {
...
+                if arr.len() == 0 {
+                    write!(f, "[]")?
+                } else {
+                    let options = FormatOptions::default().with_display_error(true);
+                    // TODO: No way to map to fmt::Error yet
```
Comment (alamb) [inline datafusion/common/src/scalar.rs:2900]: https://docs.rs/arrow/latest/arrow/util/display/struct.ArrayFormatter.html#method.try_new says it returns an error if the type can't be formatted. Since this code knows that it is always a ListArray I think it would be ok to simply unwrap the error (`ArrayFormatter::try_new(...).unwrap()`)

File: datafusion/sqllogictest/test_files/explain.slt [hunk 3]
```diff
@@ -362,3 +362,18 @@ GlobalLimitExec: skip=0, fetch=10, statistics=[Rows=Exact(8), Bytes=Absent, [(Co
...
 statement ok
 set datafusion.execution.collect_statistics = false;
+
+# Explain ArrayFuncions
+
+statement ok
+set datafusion.explain.physical_plan_only = false
+
+query TT
+explain select make_array(make_array(1, 2, 3), make_array(4, 5, 6));
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/explain.slt:372]: Given there is a special case for `[]` can we also please add a test for that as well?

**Comment by jayzhan211** [comment]
Continue on this after `sql_array_literal` fix from https://github.com/apache/arrow-datafusion/pull/8269

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @jayzhan211
