### PR TITLE
Don't add projection for semi joins in HashBuildProbeOrder

### LINKED ISSUE #4001: Output schema of semi join has invalid projection added after HashBuildProbeOrder
**Describe the bug**
Output schema of semi join has invalid projection added after HashBuildProbeOrder.
The code in HashBuildProbeOrder assumes that we use both left and right side, this is however not the case.
For semi joins, we can just keep the original schema instead.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #4001

# Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/physical_optimizer/hash_build_probe_order.rs [hunk 1]
```diff
@@ -174,6 +174,13 @@ impl PhysicalOptimizerRule for HashBuildProbeOrder {
                     *hash_join.partition_mode(),
                     hash_join.null_equals_null(),
                 )?;
+                if matches!(
```
Comment (alamb) [inline datafusion/core/src/physical_optimizer/hash_build_probe_order.rs:177]: I think the same test should apply to `Anti` joins as well, should it not?

**Review by alamb — APPROVED** [review]

File: datafusion/core/src/physical_optimizer/hash_build_probe_order.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/src/physical_optimizer/hash_build_probe_order.rs:177]: Although maybe Anti joins don't have their inputs swapped so it can't happen 🤔

Comment (Dandandan) [reply datafusion/core/src/physical_optimizer/hash_build_probe_order.rs:177]: Indeed. I figured it could be added later when RightAnti is implemented. I will add a note to the ticket.

One thing I also observed is that adding the projection for other types wouldn't be needed if we would update the join columns itself instead of fixing it afterwards, but that requires some more plumbing to get right.
