### PR TITLE
Apply workaround for #5444 to `DataFrame::describe`

### LINKED ISSUE #5444: Expr.alias function not work with count aggregation
**Describe the bug**
Expr.alias function not work with count aggregation,it's should be alias column name with origin column name
`datafusion_expr::count(col(f.name())).alias(f.name())
`image

physical_plan
```
ProjectionExec: expr=[7300 as COUNT(id), 7300 as COUNT(tinyint_col), 7300 as COUNT(smallint_col), 7300 as COUNT(int_col), 7300 as COUNT(bigint_col), 7300 as COUNT(float_col), 7300 as COUNT(double_col), 7300 as COUNT(date_string_col), 7300 as COUNT(string_col), 7300 as COUNT(timestamp_col), 7300 as COUNT(year), 7300 as COUNT(month)]
  EmptyExec: produce_one_row=true

```

**To Reproduce**

```

use arrow::datatypes::{DataType, Field};
use arrow::util::pretty::print_batches;
use datafusion::error::Result;
use datafusion::physical_plan::displayable;
use datafusion::prelude::{ParquetReadOptions, SessionContext};
use datafusion_expr::col;

#[tokio::test]
async fn count_test() -> Result<()> {
    let ctx = SessionContext::new();
    let testdata = datafusion::test_util::parquet_test_data();
    let filename = &format!("{testdata}/alltypes_plain.parquet");
    let df = ctx
        .read_parquet(filename, ParquetReadOptions::default())
        .await?;
    let cnt = df
        .clone()
        .aggregate(
            vec![],
            df.schema()
                .fields()
                .iter()
                .clone()
                .filter(|f| !matches!(f.data_type(), DataType::Boolean))
                // wrong result,alias column with count like "count(id)"
                .map(|f| datafusion_expr::count(col(f.name())).alias(f.name()))
                // right result,alias column with origin table name
                // .map(|f| datafusion_expr::max(col(f.name())).alias(f.name()))
                // right result,alias column with origin table name
                // .map(|f| datafusion_expr::count_distinct(col(f.name())).alias(f.name()))
                .collect::<Vec<_>>(),
        )
        .unwrap();
    print_batches(&cnt.clone().collect().await.unwrap()).expect("panic message");
    let plan = cnt.create_physical_plan().await.unwrap();
    let displayable_plan = displayable(plan.as_ref());
    let plan_string = format!("{}", displayable_plan.indent());
    println!("{}", plan_string);

    Ok(())
}


```

**Additional context**

### PR DESCRIPTION
**Pull request by jiangzhx**
# Which issue does this PR close?

- [Apply a patch while](https://github.com/jiangzhx/arrow-datafusion/commit/db13c1285ffe932a64e0c23a53b409836b387102) https://github.com/apache/arrow-datafusion/issues/5444 is not fixed
- use the alltypes_tiny_pages.parquet file as a data test set.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/dataframe.rs [hunk 1]
```diff
@@ -344,24 +344,30 @@ impl DataFrame {
...
+        let cnt = self.clone().count().await?;
+
         //collect recordBatch
         let describe_record_batch = vec![
             // count aggregation
-            self.clone()
-                .aggregate(
-                    vec![],
-                    fields_iter
+            vec![RecordBatch::try_new(
```
Comment (alamb) [inline datafusion/core/src/dataframe.rs:353]: I don't fully understand this change, but it seems ok.

**Review by alamb — COMMENTED** [review]
Thank you @jiangzhx  -- looks like an improvement to me. Maybe @Jefffrey also has some time to review this PR as they were commenting on https://github.com/apache/arrow-datafusion/issues/5444

**Comment by Jefffrey** [comment]
I don't fully understand these changes either, will need to take a closer look as I'm not yet familiar with `describe(...)`, but it seems this PR is a workaround to the actual issue of #5444 and wouldn't resolve it

File: datafusion/core/src/dataframe.rs (hunk 1 above)
Comment (jiangzhx) [reply datafusion/core/src/dataframe.rs:353]: This doesn't fix the issue [5444](https://github.com/apache/arrow-datafusion/issues/5444), but it did lead me to discover a better way to speed up the operation of describe.

**Comment by jiangzhx** [comment]
> 

yes,#5444 need find other way to fix. it's should not to close #5444 .
juse lead me to discover a better way to speed up the operation of describe.

**Comment by jiangzhx** [comment]
> I don't fully understand these changes either, will need to take a closer look as I'm not yet familiar with `describe(...)`, but it seems this PR is a workaround to the actual issue of #5444 and wouldn't resolve it

yes,#5444 need find other way to fix. it's should not to close .
but #5444 lead me to discover a better way to speed up the operation of describe.

**Comment by Jefffrey** [comment]
Is the method of speeding up referring to being able to leverage `aggregate_statistics` physical optimizer if possible to be able to get the stats faster? Then you hit the issue in #5444 due to these lines in `describe(...)`:

https://github.com/apache/arrow-datafusion/blob/e9852074bacd8c891d84eba38b3417aa16a2d18c/datafusion/core/src/dataframe.rs#L441-L454

Where can't find the column by name since the name of the `count(...)` column is wrong hence goes to the `None` case. So this is a workaround to make it work?

Is my understanding correct @jiangzhx ?

**Comment by jiangzhx** [comment]
> Is the method of speeding up referring to being able to leverage `aggregate_statistics` physical optimizer if possible to be able to get the stats faster? Then you hit the issue in #5444 due to these lines in `describe(...)`:
> 
> https://github.com/apache/arrow-datafusion/blob/e9852074bacd8c891d84eba38b3417aa16a2d18c/datafusion/core/src/dataframe.rs#L441-L454
> 
> Where can't find the column by name since the name of the `count(...)` column is wrong hence goes to the `None` case. So this is a workaround to make it work?
> 
> Is my understanding correct @jiangzhx ?

yes, you are right.

the problem was caused by this function
`called `Result::unwrap()` on an `Err` value: ArrowError(InvalidArgumentError("It is not possible to concatenate arrays of different data types."))`

https://github.com/apache/arrow-datafusion/blob/e9852074bacd8c891d84eba38b3417aa16a2d18c/datafusion/core/src/dataframe.rs#L457-L463

**Comment by Jefffrey** [comment]
Ok I understand now, thanks.

My opinion is to not have this workaround unless its urgently needed (since this would fix a bug in `describe(...)` which otherwise can't be avoided at the moment I think), as it adds a bit of complexity to the `describe(...)` method which would become redundant when the core issue #5444 is resolved (in which case this workaround wouldn't be needed anymore), if things work out right.

But if can be diligent to remove this workaround when #5444 is fixed (and confirmed to also fix this without workaround) then it seems fine.

**Comment by jiangzhx** [comment]
> Ok I understand now, thanks.
> 
> My opinion is to not have this workaround unless its urgently needed (since this would fix a bug in `describe(...)` which otherwise can't be avoided at the moment I think), as it adds a bit of complexity to the `describe(...)` method which would become redundant when the core issue #5444 is resolved (in which case this workaround wouldn't be needed anymore), if things work out right.
> 
> But if can be diligent to remove this workaround when #5444 is fixed (and confirmed to also fix this without workaround) then it seems fine.

Thanks for your suggestion. How about this solution? It might be easier to understand.
 ```
//count aggregation
 let cnt = self.clone().aggregate(
     vec![],
     original_schema_fields
         .clone()
         .map(|f| count(col(f.name())))
         .collect::<Vec<_>>(),
 )?;
 let cnt = cnt
     .clone()
     .select(
         cnt.schema()
             .fields()
             .iter()
             .zip(original_schema_fields.clone())
             .map(|(count_field, orgin_field)| {
                 col(count_field.name()).alias(orgin_field.name())
             })
             .collect::<Vec<_>>(),
     )
     .unwrap();
 let count_record_batch = cnt.collect().await.unwrap()；
```

also I'm keep working on #5444.  before #5444 fixed, we need a solution to fixed the bug.

**Comment by Jefffrey** [comment]
@jiangzhx That certainly is a more straightforward workaround, if you decide to go with it then having a comment explaining why the workaround is there would be helpful too

**Comment by jiangzhx** [comment]
> @jiangzhx That certainly is a more straightforward workaround, if you decide to go with it then having a comment explaining why the workaround is there would be helpful too

The issue has been resolved and the fix implemented was based on your suggestion. 
thank you @Jefffrey .

File: datafusion/core/src/dataframe.rs [hunk 2]
```diff
@@ -344,24 +344,55 @@ impl DataFrame {
...
+            vec![],
+            original_schema_fields
+                .clone()
+                .map(|f| count(col(f.name())))
+                .collect::<Vec<_>>(),
+        )?;
+        // The optimization of AggregateStatistics will rewrite the physical plan
+        // for the count function and ignore alias functions,
+        // as shown in https://github.com/apache/arrow-datafusion/issues/5444.
+        // This logic should be removed when #5444 is fixed.
```
Comment (alamb) [inline datafusion/core/src/dataframe.rs:358]: 👍  -- thank you this comment makes it much clearer what is going on

File: datafusion/core/src/dataframe.rs [hunk 3]
```diff
@@ -344,24 +344,55 @@ impl DataFrame {
...
-                    vec![],
-                    fields_iter
-                        .clone()
-                        .map(|f| count(col(f.name())).alias(f.name()))
-                        .collect::<Vec<_>>(),
-                )?
-                .collect()
-                .await?,
+            cnt.collect().await.unwrap(),
+            // vec![RecordBatch::try_new(
```
Comment (alamb) [inline datafusion/core/src/dataframe.rs:378]: I wonder if this commented code still needs to be there

Comment (jiangzhx) [reply datafusion/core/src/dataframe.rs]: fixed

**Review by alamb — APPROVED** [review]
LGTM -- thank you @jiangzhx

File: datafusion/core/src/dataframe.rs [hunk 4]
```diff
@@ -344,24 +344,42 @@ impl DataFrame {
             .collect::<Vec<_>>();
         describe_schemas.insert(0, Field::new("describe", DataType::Utf8, false));
 
+        //count aggregation
+        let cnt = self.clone().aggregate(
+            vec![],
+            original_schema_fields
+                .clone()
+                .map(|f| count(col(f.name())))
```
Comment (Jefffrey) [inline datafusion/core/src/dataframe.rs:352]:
```suggestion
                .map(|f| count(col(f.name())).alias(f.name()))
```

Maybe keep old way to make reverting easier? Since workaround should still work with this

File: datafusion/core/src/dataframe.rs [hunk 5]
```diff
@@ -344,24 +344,42 @@ impl DataFrame {
...
+                cnt.schema()
+                    .fields()
+                    .iter()
+                    .zip(original_schema_fields.clone())
+                    .map(|(count_field, orgin_field)| {
+                        col(count_field.name()).alias(orgin_field.name())
+                    })
+                    .collect::<Vec<_>>(),
+            )
+            .unwrap();
```
Comment (Jefffrey) [inline datafusion/core/src/dataframe.rs:371]:
```suggestion
            )?;
```

Instead of unwrap

File: datafusion/core/src/dataframe.rs [hunk 6]
```diff
@@ -344,24 +344,42 @@ impl DataFrame {
...
-                .aggregate(
-                    vec![],
-                    fields_iter
-                        .clone()
-                        .map(|f| count(col(f.name())).alias(f.name()))
-                        .collect::<Vec<_>>(),
-                )?
-                .collect()
-                .await?,
+            cnt.collect().await.unwrap(),
```
Comment (Jefffrey) [inline datafusion/core/src/dataframe.rs:377]:
```suggestion
            cnt.collect().await?,
```

Instead of unwrap

**Review by Jefffrey — APPROVED** [review]
Looks good, just some minor nitpicks

File: datafusion/core/src/dataframe.rs (hunk 4 above)
Comment (jiangzhx) [reply datafusion/core/src/dataframe.rs:352]: **.map(|f| count(col(f.name())).alias(f.name()))   not work, missing select projection.** 
```
ProjectionExec: expr=[7300 as COUNT(id), 7300 as COUNT(bool_col), 7300 as COUNT(tinyint_col), 7300 as COUNT(smallint_col), 7300 as COUNT(int_col), 7300 as COUNT(bigint_col), 7300 as COUNT(float_col), 7300 as COUNT(double_col), 7300 as COUNT(date_string_col), 7300 as COUNT(string_col), 7300 as COUNT(timestamp_col), 7300 as COUNT(year), 7300 as COUNT(month)]         
    EmptyExec: produce_one_row=true
```


| COUNT(id) | COUNT(bool_col) | COUNT(tinyint_col) | COUNT(smallint_col) | COUNT(int_col) | COUNT(bigint_col) | COUNT(float_col) | COUNT(double_col) | COUNT(date_string_col) | COUNT(string_col) | COUNT(timestamp_col) | COUNT(year) | COUNT(month) |
|-----------|-----------------|--------------------|---------------------|----------------|-------------------|------------------|-------------------|------------------------|-------------------|----------------------|-------------|--------------|
| 7300      | 7300            | 7300               | 7300                | 7300           | 7300              | 7300             | 7300              | 7300                   | 7300              | 7300                 | 7300        | 7300         |




**.map(|f| count(col(f.name())))  work,aggregation with projection** 
```
ProjectionExec: expr=[COUNT(?table?.id)@0 as id, COUNT(?table?.bool_col)@1 as bool_col, COUNT(?table?.tinyint_col)@2 as tinyint_col, COUNT(?table?.smallint_col)@3 as smallint_col, COUNT(?table?.int_col)@4 as int_col, COUNT(?table?.bigint_col)@5 as bigint_col, COUNT(?table?.float_col)@6 as float_col, COUNT(?table?.double_col)@7 as double_col, COUNT(?table?.date_string_col)@8 as date_string_col, COUNT(?table?.string_col)@9 as string_col, COUNT(?table?.timestamp_col)@10 as timestamp_col, COUNT(?table?.year)@11 as year, COUNT(?table?.month)@12 as month] 
        ProjectionExec: expr=[7300 as COUNT(id), 7300 as COUNT(bool_col), 7300 as COUNT(tinyint_col), 7300 as COUNT(smallint_col), 7300 as COUNT(int_col), 7300 as COUNT(bigint_col), 7300 as COUNT(float_col), 7300 as COUNT(double_col), 7300 as COUNT(date_string_col), 7300 as COUNT(string_col), 7300 as COUNT(timestamp_col), 7300 as COUNT(year), 7300 as COUNT(month)]                                                                                                                                                                                                    
            EmptyExec: produce_one_row=true                     
```                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
| id   | bool_col | tinyint_col | smallint_col | int_col | bigint_col | float_col | double_col | date_string_col | string_col | timestamp_col | year | month |
|------|----------|-------------|--------------|---------|------------|-----------|------------|-----------------|------------|---------------|------|-------|
| 7300 | 7300     | 7300        | 7300         | 7300    | 7300       | 7300      | 7300       | 7300            | 7300       | 7300          | 7300 | 7300  |

File: datafusion/core/src/dataframe.rs (hunk 5 above)
Comment (jiangzhx) [reply datafusion/core/src/dataframe.rs:371]: fixed

File: datafusion/core/src/dataframe.rs (hunk 6 above)
Comment (jiangzhx) [reply datafusion/core/src/dataframe.rs:377]: fixed

File: datafusion/core/src/dataframe.rs (hunk 4 above)
Comment (Jefffrey) [reply datafusion/core/src/dataframe.rs:352]: Ah ok, thanks for checking

**Comment by alamb** [comment]
Thanks @jiangzhx  and thanks @Jefffrey  for the review 🙏
