### PR TITLE
remove Operator::{Like,NotLike,ILike,NotILike}

### LINKED ISSUE #4765: Multiple ways to express `like` / `ilike` / `not like` / `not ilike`
**Describe the bug**
There  are two ways to express pattern matching in datafusion Exprs.

```rust
Expr::Like(Like)
..
```

https://github.com/apache/arrow-datafusion/blob/3abbffb5c83395e8e6e68e5529835e72e7769d0d/datafusion/expr/src/operator.rs#L55-L61

As well as
```rust
BinaryExpr {
 left: ..
 op: Operator::Like,
 right: ..
}
```

This causes issues such as the simplification in https://github.com/apache/arrow-datafusion/pull/4646 only affects the BinaryExpr form, not the Expr::Like form

The `Expr::Like` form is more full featured (can have pattern substitution)

**Expected behavior**
I would like to have a single way to represent these operators. I believe it should be `Expr::Like`, `Expr::ILike`, `Expr::NotLike` and `Expr::NotILike` as they have more features. 

Thus, I would like to remove `Operator::Like`, `Operator::ILike`, `Operator::NotLike`, and `Operator::NotILike` and update all tests / code to use Expr::Like

**Additional context**
Noticed while reviewing  https://github.com/apache/arrow-datafusion/pull/4646  from @crepererum 

I am marking this as "good first issue" as it is mostly a software engineering exercise and would be guided by the compiler -- it would be a good exercise to get familiar with DataFusion's codebase

### PR DESCRIPTION
**Pull request by unconsolable**
# Which issue does this PR close?

Closes #4765 .

# Rationale for this change

See issue.

# What changes are included in this PR?

- Remove `Operator::{Like,NotLike,ILike,NotILike}`
- For `datafusion_expr::expr::Expr::{like, not_like, ilike, not_ilike}`, return `Expr::{Like, ILike}` version.
- In `TypeCoercionRewriter` use `like_coercion` directly, bypass `Operator::Like` etc.
- Add a new `LikeExpr` in `datafusion_physical_expr::expressions`, bypass `Operator::Like` etc. Also convert `Expr::{like, not_like, ilike, not_ilike}` to this `LikeExpr`
- Add new type in `PhysicalExprNode` proto, make corresponding change in `from_proto` & `to_proto`

# Are these changes tested?

- `TypeCoercionRewriter` and `LikeExpr` are tested correspondingly.
- In `datafusion::physical_plan::planner::tests::errors()`, tests for `like/ilike/not like/not ilike` are removed, as for `Expr::Like` and `Expr::ILike`, `coerce_types` are not performed in `Expr::get_type` 

https://github.com/apache/arrow-datafusion/blob/54ae4323a730a4a34c6b5f638e2083f0c3fe5dcc/datafusion/expr/src/expr_schema.rs#L128-L130

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you 🙏  @unconsolable  -- I plan to review this one carefully tomorrow

File: datafusion/expr/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -858,6 +850,13 @@ mod tests {
         }};
     }
 
+    macro_rules! test_coercion_like_rule {
```
Comment (alamb) [inline datafusion/expr/src/type_coercion/binary.rs:853]: I wonder why this use a macro? It looks like this macro is only used in one place. Maybe it can be inlined?

File: datafusion/optimizer/src/simplify_expressions/utils.rs [hunk 2]
```diff
@@ -232,6 +232,20 @@ pub fn negate_clause(expr: Expr) -> Expr {
...
             between.high,
         )),
+        // not (A like B) ===> A not like B
+        Expr::Like(like) => Expr::Like(Like::new(
+            !like.negated,
+            like.expr,
+            like.pattern,
+            like.escape_char,
+        )),
+        // not (A ilike B) ===> A not ilike B
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/utils.rs:242]: 👍

File: datafusion/optimizer/src/type_coercion.rs [hunk 3]
```diff
@@ -175,8 +177,11 @@ impl ExprRewriter for TypeCoercionRewriter {
             }) => {
                 let left_type = expr.get_type(&self.schema)?;
                 let right_type = pattern.get_type(&self.schema)?;
-                let coerced_type =
-                    coerce_types(&left_type, &Operator::Like, &right_type)?;
+                let coerced_type = like_coercion(&left_type,  &right_type).ok_or_else(|| {
+                    DataFusionError::Plan(format!(
+                        "There isn't a common type to concrete {left_type} and {right_type} in LIKE expression"
```
Comment (alamb) [inline datafusion/optimizer/src/type_coercion.rs:182]:
```suggestion
                        "There isn't a common type to coerce {left_type} and {right_type} in LIKE expression"
```

File: datafusion/optimizer/src/type_coercion.rs [hunk 4]
```diff
@@ -190,8 +195,11 @@ impl ExprRewriter for TypeCoercionRewriter {
             }) => {
                 let left_type = expr.get_type(&self.schema)?;
                 let right_type = pattern.get_type(&self.schema)?;
-                let coerced_type =
-                    coerce_types(&left_type, &Operator::ILike, &right_type)?;
+                let coerced_type = like_coercion(&left_type,  &right_type).ok_or_else(|| {
+                    DataFusionError::Plan(format!(
+                        "There isn't a common type to concrete {left_type} and {right_type} in ILIKE expression"
```
Comment (alamb) [inline datafusion/optimizer/src/type_coercion.rs:200]:
```suggestion
                        "There isn't a common type to coerce {left_type} and {right_type} in ILIKE expression"
```

File: datafusion/optimizer/src/type_coercion.rs [hunk 5]
```diff
@@ -932,7 +940,9 @@ mod test {
         let plan = LogicalPlan::Projection(Projection::try_new(vec![like_expr], empty)?);
         let err = assert_optimized_plan_eq(&plan, expected);
         assert!(err.is_err());
-        assert!(err.unwrap_err().to_string().contains("'Int64 LIKE Utf8' can't be evaluated because there isn't a common type to coerce the types to"));
+        assert!(err.unwrap_err().to_string().contains(
+            "There isn't a common type to concrete Int64 and Utf8 in LIKE expression"
```
Comment (alamb) [inline datafusion/optimizer/src/type_coercion.rs:944]:
```suggestion
            "There isn't a common type to coerce Int64 and Utf8 in LIKE expression"
```

File: datafusion/physical-expr/src/expressions/like.rs [hunk 6]
```diff
@@ -0,0 +1,365 @@
...
+                "Data type {:?} not supported for scalar operation '{}' on string array",
+                other, stringify!($OP)
+            ))),
+        };
+        Some(result)
+    }};
+}
+
+impl LikeExpr {
+    /// Evaluate the expression of the input is an array and
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/like.rs:219]:
```suggestion
    /// Evaluate the expression if the input is an array and
```

File: datafusion/physical-expr/src/expressions/like.rs [hunk 7]
```diff
@@ -0,0 +1,365 @@
...
+            (true, false) => binary_string_array_op!(left, right, nlike),
+            (false, true) => binary_string_array_op!(left, right, ilike),
+            (true, true) => binary_string_array_op!(left, right, nilike),
+        }
+    }
+}
+
+/// Create a like expression whose arguments are correctly coerced.
+/// This function errors if it is not possible to coerce the arguments
+/// to computational types supported by the operator.
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/like.rs:271]: I don't think this function does any coercion

Maybe something like this would be most appropriate:

```suggestion
/// Create a like expression, erroring if the argument types are not compatible
```

File: datafusion/physical-expr/src/expressions/like.rs [hunk 8]
```diff
@@ -0,0 +1,365 @@
...
+                as_boolean_array(&result).expect("failed to downcast to BooleanArray");
+            let expected = &BooleanArray::from($VEC);
+            assert_eq!(expected, result);
+        }};
+    }
+
+    #[test]
+    fn like_op() -> Result<()> {
+        test_like!(
+            vec!["hello world", "world"],
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/like.rs:335]: It would be great to add `NULL` to these cases as well -- e.g.

```suggestion
            vec![Some("hello world"), None, Some("world")],
```

To verify that the operator correctly handles nulls

File: datafusion/proto/src/physical_plan/to_proto.rs [hunk 9]
```diff
@@ -330,6 +332,17 @@ impl TryFrom<Arc<dyn PhysicalExpr>> for protobuf::PhysicalExprNode {
                     ),
                 ),
             })
+        } else if let Some(expr) = expr.downcast_ref::<LikeExpr>() {
```
Comment (alamb) [inline datafusion/proto/src/physical_plan/to_proto.rs:335]: I wonder if there is any test coverage for round tripping a physical `LikeExpr`?

**Review by alamb — COMMENTED** [review]
Thank you @unconsolable  -- this is a very beautiful first PR 🏆 

I had a few minor suggestions but overall this looks very close to mergable. 

Thank you so much 🙏

File: datafusion/core/src/physical_plan/planner.rs [hunk 10]
```diff
@@ -2016,14 +2016,6 @@ mod tests {
...
             // u32 AND bool
             col("c2").and(bool_expr),
-            // utf8 LIKE u32
-            col("c1").like(col("c2")),
-            // utf8 NOT LIKE u32
-            col("c1").not_like(col("c2")),
-            // utf8 ILIKE u32
-            col("c1").ilike(col("c2")),
-            // utf8 NOT ILIKE u32
-            col("c1").not_ilike(col("c2")),
```
Comment (crepererum) [inline datafusion/core/src/physical_plan/planner.rs:2026]: why do these no longer error?

Comment (unconsolable) [reply datafusion/core/src/physical_plan/planner.rs:2026]: > In datafusion::physical_plan::planner::tests::errors(), tests for like/ilike/not like/not ilike are removed, as for Expr::Like and Expr::ILike, coerce_types are not performed in Expr::get_type

Comment (unconsolable) [reply datafusion/core/src/physical_plan/planner.rs:2026]: > - In `datafusion::physical_plan::planner::tests::errors()`, tests for `like/ilike/not like/not ilike` are removed, as for `Expr::Like` and `Expr::ILike`, `coerce_types` are not performed in `Expr::get_type` 
>
> https://github.com/apache/arrow-datafusion/blob/54ae4323a730a4a34c6b5f638e2083f0c3fe5dcc/datafusion/expr/src/expr_schema.rs#L128-L130

**Review by alamb — APPROVED** [review]
Thank you @unconsolable  and @crepererum

**Comment by alamb** [comment]
🚀
