### PR TITLE
fix: check recursion limit in `Expr::to_bytes`

### LINKED ISSUE #3968: `Expr::to_bytes` can produce output that hits `Expr::from_bytes` recursion limit
**Describe the bug**
`Expr::to_bytes` with deeply nested expressions can produce a byte sequence that cannot be read by `Expr::from_bytes` because the prost recursion limit is hit. This is suboptimal in distributed application because it would be good if a client can decide if an expression is wire/roundtrip-safe and potentially adjust its predicate pushdown accordingly.

**To Reproduce**

```rust
#[test]
fn roundtrip_deeply_nested() {
// we need more stack space so this doesn't overflow in dev builds
std::thread::Builder::new().stack_size(10_000_000).spawn(|| {
	// don't know what "too much" is, so let's slowly try to increase complexity
	let n_max = 100;

	for n in 1..n_max {
	println!("testing: {n}");

	let expr_base = col("a").lt(lit(5i32));
	let expr = (0..n).fold(expr_base.clone(), |expr, _| expr.and(expr_base.clone()));

	// Convert it to an opaque form
	let bytes = match expr.to_bytes() {
		Ok(bytes) => bytes,
		Err(_) => {
		// found expression that is too deeply nested
		return;
		}
	};

	// Decode bytes from somewhere (over network, etc.
	let decoded_expr = Expr::from_bytes(&bytes).expect("serialization worked, so deserialization should work as well");
	assert_eq!(expr, decoded_expr);
	}

	panic!("did not find a 'too deeply nested' expression, tested up to a depth of {n_max}")
}).expect("spawning thread").join().expect("joining thread");
}
```

**Expected behavior**
Above test passes.

**Additional context**
Above test fails with:

`thread '<unnamed>' panicked at 'serialization worked, so deserialization should work as well: Plan("Error decoding expr as protobuf: failed to decode Protobuf message: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: .....recursion limit reached")'`

### PR DESCRIPTION
**Pull request by crepererum**
# Which issue does this PR close?

Closes #3968.

# Rationale for this change
`Expr::to_bytes` can create outputs that `Expr::from_bytes` can no longer read.

# What changes are included in this PR?
Try to deserialize the data in `Expr::to_bytes` to catch invalid data early. This is a workaround until https://github.com/tokio-rs/prost/issues/736 is implemented.

# Are there any user-facing changes?
Expressions that are nested too deeply are now rejected to serialization already.

### CODE REVIEW

File: datafusion/proto/src/bytes/mod.rs [hunk 1]
```diff
@@ -84,7 +87,45 @@ impl Serializeable for Expr {
...
+
+        // the produced byte stream may lead to "recursion limit" errors, see
+        // https://github.com/apache/arrow-datafusion/issues/3968
+        // Until the underlying prost issue ( https://github.com/tokio-rs/prost/issues/736 ) is fixed, we try to
+        // deserialize the data here and check for errors.
+        //
+        // Need to provide some placeholder registry because the stream may contain UDFs
+        struct PlaceHolderRegistry;
+
+        impl FunctionRegistry for PlaceHolderRegistry {
```
Comment (crepererum) [inline datafusion/proto/src/bytes/mod.rs:100]: :see_no_evil:

Comment (alamb) [reply datafusion/proto/src/bytes/mod.rs:100]: I think the comments explain what is going on 👍

**Review by alamb — APPROVED** [review]
As always, well tested @crepererum -- thank you
