### PR TITLE
fix: build union schema with child has same column name but qualifier…

### LINKED ISSUE #5410: Join two tables with the same schema, then union throws `SchemaError(DuplicateUnqualifiedField )`
**Describe the bug**
Join two tables with the same schema, then union throws `SchemaError(DuplicateUnqualifiedField )`

**To Reproduce**
```sql
create table ta(a bigint) as values(1);
create table tb(a bigint) as values(2);
select * from ta join tb on true
    union all
select * from ta join tb on true;
```
SchemaError(DuplicateUnqualifiedField { name: "a" })

**Expected behavior**
query sucess.

**Additional context**
datafusion v18.0.0

### PR DESCRIPTION
**Pull request by yukkit**
… is different

# Which issue does this PR close?

Closes #5410 .

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -1101,7 +1101,7 @@ pub fn union(left_plan: LogicalPlan, right_plan: LogicalPlan) -> Result<LogicalP
                     })?;
 
             Ok(DFField::new(
-                None,
+                left_field.qualifier().map(|x| &**x),
```
Comment (jackwener) [inline datafusion/expr/src/logical_plan/builder.rs:1104]:
```suggestion
                left_field.qualifier().map(|x| x.as_ref()),
```

**Review by jackwener — APPROVED** [review]
This PR use left-side qualifier instead of discard qualifier when build `union`.
Make sense to me
