### PR TITLE
fix df union all bug

### LINKED ISSUE #1818: A corner bug in union
**Describe the bug**
When union some `select constant1, contant2, ...` similar queries, union can't produce the result.

**To Reproduce**
```sql
❯ SELECT 1 as col1, 'one' as col2
UNION ALL
SELECT 2, 'two'
UNION ALL
SELECT 3, 'three';

Plan("UNION ALL schemas are expected to be the same")

❯ SELECT 1 , 'one'
UNION ALL
SELECT 2, 'two'
UNION ALL
SELECT 3, 'three';

Plan("UNION ALL schemas are expected to be the same")
```

**Expected behavior**
Let' see results from postgres:
```sql
postgres=# SELECT 1 AS column1, 'one' AS column2
UNION ALL
SELECT 2, 'two'
UNION ALL
SELECT 3, 'three';
 column1 | column2
---------+---------
       1 | one
       2 | two
       3 | three
(3 rows)

postgres=# SELECT 1 , 'one'
UNION ALL
SELECT 2, 'two'
UNION ALL
SELECT 3, 'three';
 ?column? | ?column?
----------+----------
        1 | one
        2 | two
        3 | three
(3 rows)
```

**Additional context**
I have done an easy analysis, the followings are my thought to solve the issue:
1. We should fix the default name when the expr in projection doesn't have a name. Let's see an example. `select a from table1`, `a` is the column from `table1`, so it naturally has a name `a`, but for `select 1`, `1` isn't a column, it's a `Value` expr, so its name will be `Int64(1)` in current datatfusion's implementation, the related code is https://github.com/apache/arrow-datafusion/blob/7be0e268a69ffecbf06823c98ca572733dddb29e/datafusion/src/physical_plan/planner.rs#L91. So the first thing to solve the issue is to rethink how to create default name. I think we can keep consistent with postgres, such as `?column?`.
2. Currently, DF judges if the logical plans in `union` have the same schema by arrow schema's field name https://github.com/apache/arrow-datafusion/blob/7be0e268a69ffecbf06823c98ca572733dddb29e/datafusion-common/src/dfschema.rs#L251. After finishing 1, we can add a condition, if the col name is `?column?`, we decide if logical plans have the same schema by arrow schema's filed datatype.

cc @alamb @houqp

### PR DESCRIPTION
**Pull request by WinkerDu**
# Which issue does this PR close?

Closes #1818.

 # Rationale for this change

when union different some constants, `UNION ALL schemas are expected to be the same` would raise, like
```
❯ select 1,2
union all
select 3,4;
Plan("UNION ALL schemas are expected to be the same")
```
This pr fix it.

# What changes are included in this PR?

1. except for expression `Alias` and `Column` in `Projection` under `Union`, other expressions should be aliased with column index like `column0`
2. change field names match check to field type compatible check.

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by WinkerDu** [comment]
cc @xudong963 @alamb PTAL

**Comment by WinkerDu** [comment]
> Thanks @WinkerDu ❤️! would you mind fix the conflicts?

OK, ASAP

File: datafusion-common/src/dfschema.rs [hunk 1]
```diff
@@ -281,6 +281,14 @@ impl DFSchema {
             .all(|(dffield, arrowfield)| dffield.name() == arrowfield.name())
     }
 
+    /// Check to see if df field data types in df schema matches with input df schema
+    pub fn matches_arrow_schema_with_type(&self, df_schema: &DFSchema) -> bool {
+        self.fields
+            .iter()
```
Comment (Ted-Jiang) [inline datafusion-common/src/dfschema.rs:287]: in postgresql union support  type cast like below
```
postgres=# select '1.2' as a union select 2.3 as b union select 3 as b ;
  a
-----
 2.3
   3
 1.2
(3 rows)

postgres=# \gdesc
 Column |  Type
--------+---------
 a      | numeric
(1 row)
```

Maybe we can open a ticket support this ?

Comment (WinkerDu) [reply datafusion-common/src/dfschema.rs:287]: @Ted-Jiang Agree with that.
Maybe we can solve `Alias` issue first, than open a new issue to fully discuss data type compatible cast?

**Comment by WinkerDu** [comment]
cc @xudong963  @Ted-Jiang 
PTAL, thanks.

File: datafusion/common/src/dfschema.rs [hunk 2]
```diff
@@ -281,6 +282,18 @@ impl DFSchema {
...
 
+    /// Check to see if fields in 2 Arrow schemas are compatible
+    pub fn check_arrow_schema_type_compatible(&self, arrow_schema: &Schema) -> bool {
+        let self_arrow_schema: Schema = self.into();
+        self_arrow_schema
+            .fields()
+            .iter()
+            .zip(arrow_schema.fields().iter())
+            .all(|(l_field, r_field)| {
+                can_cast_types(r_field.data_type(), l_field.data_type())
```
Comment (Dandandan) [inline datafusion/common/src/dfschema.rs:293]: If this would return a Result<()> we could return a more specific error of the type mismatch here (and pass it to the user).

Comment (WinkerDu) [reply datafusion/common/src/dfschema.rs:293]: @Dandandan OK, I'll fix it.

**Comment by WinkerDu** [comment]
@Dandandan PTAL, thanks

**Comment by WinkerDu** [comment]
cc @alamb @yjshen @xudong963 
PTAL, thanks

**Review by Dandandan — APPROVED** [review]

**Review by yjshen — APPROVED** [review]
I'm a little bit conservative on the general auto alias columns behavior. But since this work limits such aliases to only the union case, I think it's cool to go.

Thanks again @WinkerDu!

**Comment by alamb** [comment]
Thank you for sticking with this @WinkerDu  -- 👍

**Comment by xudong963** [comment]
@WinkerDu  Thank you! Sorry for not checking in time. I had some personal affairs recently.
