### PR TITLE
`PrimitiveGroupsAccumulator` should propagate timestamp timezone information properly

### LINKED ISSUE #7493: Min/Max new group accumulator doesn't handle timestamp with timezone info correctly
### Describe the bug

In the `PrimitiveGroupsAccumulator` implementation, currently the `evaluate` method is implemented as following:
```rust
    fn evaluate(&mut self, emit_to: EmitTo) -> Result<ArrayRef> {
        let values = emit_to.take_needed(&mut self.values);
        let nulls = self.null_state.build(emit_to);
        let values = PrimitiveArray::<T>::new(values.into(), Some(nulls)); // no copy

        adjust_output_array(&self.data_type, Arc::new(values))
    }
```

Note that the `values` array is initialized with the generic parameter `T`, which, for timestamp types like `TimestampMicrosecondType`, will not have timezone info. There is a `adjust_output_array` method later to fix a similar issue for decimal type, but currently it doesn't handle other cases like timestamp.

This would potentially cause a mismatch between the data type of the Arrow array and the data type in the required schema.

### To Reproduce

Added a test to reproduce the issue.

### Expected behavior

Timezone information should be properly passed to the result Arrow array in `PrimitiveGroupsAccumulator.evaluate`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sunchao**
## Which issue does this PR close?

Closes #7493.

## Rationale for this change

Currently `PrimitiveGroupsAccumulator#evaluate` method initialize the result Arrow array using its generic type parameter `T` which is a `ArrowPrimitiveType`, converted from enum `DataType`. This, however, doesn't have complete information comparing to the original `DataType` it converted from. For instance, `TimestampMicrosecondType` always have `None` as timezone while in the `DataType` it could be set to some specific timezone.

## What changes are included in this PR?

I noticed that we already have `adjust_output_array` that handles a similar case for decimal type. One straightforward solution is to add another case for `Timestamp` in the method. However, I feel the logic would become simpler if we just call `with_data_type` after creating the Arrow array. This would also allow us to prevent more potential issues in the future. Therefore, in this PR I replaced all usage of `adjust_output_array` with `with_data_type` and removed the method itself.

## Are these changes tested?

Added some new tests for this.

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by sunchao** [comment]
cc @alamb @viirya @tustvold

File: datafusion/physical-expr/src/aggregate/average.rs [hunk 1]
```diff
@@ -505,8 +503,8 @@ where
         let counts = UInt64Array::new(counts.into(), nulls.clone()); // zero copy
 
         let sums = emit_to.take_needed(&mut self.sums);
-        let sums = PrimitiveArray::<T>::new(sums.into(), nulls); // zero copy
-        let sums = adjust_output_array(&self.sum_data_type, Arc::new(sums))?;
+        let sums = PrimitiveArray::<T>::new(sums.into(), nulls) // zero copy
+            .with_data_type(self.sum_data_type.clone());
```
Comment (alamb) [inline datafusion/physical-expr/src/aggregate/average.rs:507]: 👍  this is a very nice improvement

**Review by alamb — APPROVED** [review]
The code change looks good to me -- thank you @sunchao 

I didn't fully understand the need for the modified `generic_test_op_new` macro but it could be cleaned up later

File: datafusion/physical-expr/src/expressions/mod.rs [hunk 2]
```diff
@@ -136,6 +137,35 @@ pub(crate) mod tests {
         }};
     }
 
+    /// macro to perform an aggregation using [`GroupsAccumulator`] and verify the result.
```
[the remark this answers is not in the document]
Comment (sunchao) [reply datafusion/physical-expr/src/expressions/mod.rs:140]: Let me add some comments here. I don't really like the name `generic_test_op_new` too.

The current `generic_test_op` only test the old slow-path `Accumulator`. In order to test this change which happens to the new `GroupsAccumulator`, I have to create a new similar macro that calls `GroupsAccumulator`'s `update_batch` and `evaluate` method.

File: datafusion/physical-expr/src/aggregate/average.rs [hunk 3]
```diff
@@ -488,12 +488,10 @@ where
                 .map(|(sum, count)| (self.avg_fn)(sum, count))
                 .collect::<Result<Vec<_>>>()?;
             PrimitiveArray::new(averages.into(), Some(nulls)) // no copy
+                .with_data_type(self.return_data_type.clone())
         };
 
-        // fix up decimal precision and scale for decimals
-        let array = adjust_output_array(&self.return_data_type, Arc::new(array))?;
```
Comment (viirya) [inline datafusion/physical-expr/src/aggregate/average.rs:494]: I guess this was add before `with_data_type` is introduced as API.

**Review by viirya — APPROVED** [review]

File: datafusion/physical-expr/src/aggregate/average.rs (hunk 3 above)
Comment (sunchao) [reply datafusion/physical-expr/src/aggregate/average.rs:494]: Oh yea, just realized this was added recently.

**Comment by sunchao** [comment]
Thanks! merged.
