### PR TITLE
Fix right, full join handling when having multiple non-matching rows at the left side

### LINKED ISSUE #843: Incorrect results for joins on hash collisions
**Describe the bug**
DataFusion joins seem to produce incorrect results when there is a collision in the hash function. This is *very* rare, but it can happen.

**To Reproduce**
After https://github.com/apache/arrow-datafusion/pull/842 is merged, remove the `#[cfg(not(feature = "force_hash_collisions"))]` gate from the join tests, and run 

```shell
cd datafusion
cargo test --features=force_hash_collisions
```

Here is a diff that does so:
```diff
diff --git a/datafusion/src/physical_plan/hash_join.rs b/datafusion/src/physical_plan/hash_join.rs
index fa75437e3..1a57c404e 100644
--- a/datafusion/src/physical_plan/hash_join.rs
+++ b/datafusion/src/physical_plan/hash_join.rs
@@ -1372,8 +1372,6 @@ mod tests {
     }
 
     #[tokio::test]
-    // Disable until https://github.com/apache/arrow-datafusion/issues/843 fixed
-    #[cfg(not(feature = "force_hash_collisions"))]
     async fn join_full_multi_batch() {
         let left = build_table(
             ("a1", &vec![1, 2, 3]),
@@ -1639,8 +1637,6 @@ mod tests {
     }
 
     #[tokio::test]
-    // Disable until https://github.com/apache/arrow-datafusion/issues/843 fixed
-    #[cfg(not(feature = "force_hash_collisions"))]
     async fn join_right_one() -> Result<()> {
         let left = build_table(
             ("a1", &vec![1, 2, 3]),
@@ -1677,8 +1673,6 @@ mod tests {
     }
 
     #[tokio::test]
-    // Disable until https://github.com/apache/arrow-datafusion/issues/843 fixed
-    #[cfg(not(feature = "force_hash_collisions"))]
     async fn partitioned_join_right_one() -> Result<()> {
         let left = build_table(
             ("a1", &vec![1, 2, 3]),
@@ -1716,8 +1710,6 @@ mod tests {
     }
 
     #[tokio::test]
-    // Disable until https://github.com/apache/arrow-datafusion/issues/843 fixed
-    #[cfg(not(feature = "force_hash_collisions"))]
     async fn join_full_one() -> Result<()> {
         let left = build_table(
             ("a1", &vec![1, 2, 3]),
diff --git a/datafusion/tests/sql.rs b/datafusion/tests/sql.rs
index 046e4f28e..0c33bd477 100644
--- a/datafusion/tests/sql.rs
+++ b/datafusion/tests/sql.rs
@@ -1797,8 +1797,6 @@ async fn equijoin_left_and_condition_from_right() -> Result<()> {
 }
 
 #[tokio::test]
-// Disable until https://github.com/apache/arrow-datafusion/issues/843 fixed
-#[cfg(not(feature = "force_hash_collisions"))]
 async fn equijoin_right_and_condition_from_left() -> Result<()> {
     let mut ctx = create_join_context("t1_id", "t2_id")?;
     let sql =
@@ -1852,8 +1850,6 @@ async fn left_join() -> Result<()> {
 }
 
 #[tokio::test]
-// Disable until https://github.com/apache/arrow-datafusion/issues/843 fixed
-#[cfg(not(feature = "force_hash_collisions"))]
 async fn right_join() -> Result<()> {
     let mut ctx = create_join_context("t1_id", "t2_id")?;
     let equivalent_sql = [
@@ -1874,8 +1870,6 @@ async fn right_join() -> Result<()> {
 }
 
 #[tokio::test]
-// Disable until https://github.com/apache/arrow-datafusion/issues/843 fixed
-#[cfg(not(feature = "force_hash_collisions"))]
 async fn full_join() -> Result<()> {
     let mut ctx = create_join_context("t1_id", "t2_id")?;
     let equivalent_sql = [
```

This results in the following failures:
```shell
failures:

---- physical_plan::hash_join::tests::join_full_one stdout ----
thread 'physical_plan::hash_join::tests::join_full_one' panicked at 'assertion failed: `(left == right)`
  left: `["+----+----+----+----+----+----+", "| a1 | b1 | c1 | a2 | b2 | c2 |", "+----+----+----+----+----+----+", "|    |    |    | 30 | 6  | 90 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "| 3  | 7  | 9  |    |    |    |", "+----+----+----+----+----+----+"]`,
 right: `["+----+----+----+----+----+----+", "| a1 | b1 | c1 | a2 | b2 | c2 |", "+----+----+----+----+----+----+", "|    |    |    | 10 | 4  | 70 |", "|    |    |    | 10 | 4  | 70 |", "|    |    |    | 20 | 5  | 80 |", "|    |    |    | 20 | 5  | 80 |", "|    |    |    | 30 | 6  | 90 |", "|    |    |    | 30 | 6  | 90 |", "|    |    |    | 30 | 6  | 90 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "| 3  | 7  | 9  |    |    |    |", "+----+----+----+----+----+----+"]`: 

expected:

[
    "+----+----+----+----+----+----+",
    "| a1 | b1 | c1 | a2 | b2 | c2 |",
    "+----+----+----+----+----+----+",
    "|    |    |    | 30 | 6  | 90 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "| 3  | 7  | 9  |    |    |    |",
    "+----+----+----+----+----+----+",
]
actual:

[
    "+----+----+----+----+----+----+",
    "| a1 | b1 | c1 | a2 | b2 | c2 |",
    "+----+----+----+----+----+----+",
    "|    |    |    | 10 | 4  | 70 |",
    "|    |    |    | 10 | 4  | 70 |",
    "|    |    |    | 20 | 5  | 80 |",
    "|    |    |    | 20 | 5  | 80 |",
    "|    |    |    | 30 | 6  | 90 |",
    "|    |    |    | 30 | 6  | 90 |",
    "|    |    |    | 30 | 6  | 90 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "| 3  | 7  | 9  |    |    |    |",
    "+----+----+----+----+----+----+",
]

', datafusion/src/physical_plan/hash_join.rs:1747:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- physical_plan::hash_join::tests::join_right_one stdout ----
thread 'physical_plan::hash_join::tests::join_right_one' panicked at 'assertion failed: `(left == right)`
  left: `["+----+----+----+----+----+----+", "| a1 | b1 | c1 | a2 | b1 | c2 |", "+----+----+----+----+----+----+", "|    | 6  |    | 30 | 6  | 90 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "+----+----+----+----+----+----+"]`,
 right: `["+----+----+----+----+----+----+", "| a1 | b1 | c1 | a2 | b1 | c2 |", "+----+----+----+----+----+----+", "|    | 4  |    | 10 | 4  | 70 |", "|    | 4  |    | 10 | 4  | 70 |", "|    | 5  |    | 20 | 5  | 80 |", "|    | 5  |    | 20 | 5  | 80 |", "|    | 6  |    | 30 | 6  | 90 |", "|    | 6  |    | 30 | 6  | 90 |", "|    | 6  |    | 30 | 6  | 90 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "+----+----+----+----+----+----+"]`: 

expected:

[
    "+----+----+----+----+----+----+",
    "| a1 | b1 | c1 | a2 | b1 | c2 |",
    "+----+----+----+----+----+----+",
    "|    | 6  |    | 30 | 6  | 90 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "+----+----+----+----+----+----+",
]
actual:

[
    "+----+----+----+----+----+----+",
    "| a1 | b1 | c1 | a2 | b1 | c2 |",
    "+----+----+----+----+----+----+",
    "|    | 4  |    | 10 | 4  | 70 |",
    "|    | 4  |    | 10 | 4  | 70 |",
    "|    | 5  |    | 20 | 5  | 80 |",
    "|    | 5  |    | 20 | 5  | 80 |",
    "|    | 6  |    | 30 | 6  | 90 |",
    "|    | 6  |    | 30 | 6  | 90 |",
    "|    | 6  |    | 30 | 6  | 90 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "+----+----+----+----+----+----+",
]

', datafusion/src/physical_plan/hash_join.rs:1670:9

---- physical_plan::hash_join::tests::join_full_multi_batch stdout ----
thread 'physical_plan::hash_join::tests::join_full_multi_batch' panicked at 'assertion failed: `(left == right)`
  left: `["+----+----+----+----+----+----+", "| a1 | b1 | c1 | a2 | b2 | c2 |", "+----+----+----+----+----+----+", "|    |    |    | 30 | 6  | 90 |", "|    |    |    | 30 | 6  | 90 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "| 3  | 7  | 9  |    |    |    |", "+----+----+----+----+----+----+"]`,
 right: `["+----+----+----+----+----+----+", "| a1 | b1 | c1 | a2 | b2 | c2 |", "+----+----+----+----+----+----+", "|    |    |    | 10 | 4  | 70 |", "|    |    |    | 10 | 4  | 70 |", "|    |    |    | 10 | 4  | 70 |", "|    |    |    | 10 | 4  | 70 |", "|    |    |    | 20 | 5  | 80 |", "|    |    |    | 20 | 5  | 80 |", "|    |    |    | 20 | 5  | 80 |", "|    |    |    | 20 | 5  | 80 |", "|    |    |    | 30 | 6  | 90 |", "|    |    |    | 30 | 6  | 90 |", "|    |    |    | 30 | 6  | 90 |", "|    |    |    | 30 | 6  | 90 |", "|    |    |    | 30 | 6  | 90 |", "|    |    |    | 30 | 6  | 90 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "| 3  | 7  | 9  |    |    |    |", "+----+----+----+----+----+----+"]`: 

expected:

[
    "+----+----+----+----+----+----+",
    "| a1 | b1 | c1 | a2 | b2 | c2 |",
    "+----+----+----+----+----+----+",
    "|    |    |    | 30 | 6  | 90 |",
    "|    |    |    | 30 | 6  | 90 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "| 3  | 7  | 9  |    |    |    |",
    "+----+----+----+----+----+----+",
]
actual:

[
    "+----+----+----+----+----+----+",
    "| a1 | b1 | c1 | a2 | b2 | c2 |",
    "+----+----+----+----+----+----+",
    "|    |    |    | 10 | 4  | 70 |",
    "|    |    |    | 10 | 4  | 70 |",
    "|    |    |    | 10 | 4  | 70 |",
    "|    |    |    | 10 | 4  | 70 |",
    "|    |    |    | 20 | 5  | 80 |",
    "|    |    |    | 20 | 5  | 80 |",
    "|    |    |    | 20 | 5  | 80 |",
    "|    |    |    | 20 | 5  | 80 |",
    "|    |    |    | 30 | 6  | 90 |",
    "|    |    |    | 30 | 6  | 90 |",
    "|    |    |    | 30 | 6  | 90 |",
    "|    |    |    | 30 | 6  | 90 |",
    "|    |    |    | 30 | 6  | 90 |",
    "|    |    |    | 30 | 6  | 90 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "| 3  | 7  | 9  |    |    |    |",
    "+----+----+----+----+----+----+",
]

', datafusion/src/physical_plan/hash_join.rs:1414:9

---- physical_plan::hash_join::tests::partitioned_join_right_one stdout ----
thread 'physical_plan::hash_join::tests::partitioned_join_right_one' panicked at 'assertion failed: `(left == right)`
  left: `["+----+----+----+----+----+----+", "| a1 | b1 | c1 | a2 | b1 | c2 |", "+----+----+----+----+----+----+", "|    | 6  |    | 30 | 6  | 90 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "+----+----+----+----+----+----+"]`,
 right: `["+----+----+----+----+----+----+", "| a1 | b1 | c1 | a2 | b1 | c2 |", "+----+----+----+----+----+----+", "|    | 4  |    | 10 | 4  | 70 |", "|    | 4  |    | 10 | 4  | 70 |", "|    | 5  |    | 20 | 5  | 80 |", "|    | 5  |    | 20 | 5  | 80 |", "|    | 6  |    | 30 | 6  | 90 |", "|    | 6  |    | 30 | 6  | 90 |", "|    | 6  |    | 30 | 6  | 90 |", "| 1  | 4  | 7  | 10 | 4  | 70 |", "| 2  | 5  | 8  | 20 | 5  | 80 |", "+----+----+----+----+----+----+"]`: 

expected:

[
    "+----+----+----+----+----+----+",
    "| a1 | b1 | c1 | a2 | b1 | c2 |",
    "+----+----+----+----+----+----+",
    "|    | 6  |    | 30 | 6  | 90 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "+----+----+----+----+----+----+",
]
actual:

[
    "+----+----+----+----+----+----+",
    "| a1 | b1 | c1 | a2 | b1 | c2 |",
    "+----+----+----+----+----+----+",
    "|    | 4  |    | 10 | 4  | 70 |",
    "|    | 4  |    | 10 | 4  | 70 |",
    "|    | 5  |    | 20 | 5  | 80 |",
    "|    | 5  |    | 20 | 5  | 80 |",
    "|    | 6  |    | 30 | 6  | 90 |",
    "|    | 6  |    | 30 | 6  | 90 |",
    "|    | 6  |    | 30 | 6  | 90 |",
    "| 1  | 4  | 7  | 10 | 4  | 70 |",
    "| 2  | 5  | 8  | 20 | 5  | 80 |",
    "+----+----+----+----+----+----+",
]

', datafusion/src/physical_plan/hash_join.rs:1707:9


failures:
    physical_plan::hash_join::tests::join_full_multi_batch
    physical_plan::hash_join::tests::join_full_one
    physical_plan::hash_join::tests::join_right_one
    physical_plan::hash_join::tests::partitioned_join_right_one

test result: FAILED. 640 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.65s

error: test failed, to rerun pass '--lib'

Compilation exited abnormally with code 101 at Mon Aug  9 11:02:00
```

**Expected behavior**
Tests should pass

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #843

 # Rationale for this change

Right and hull join had an error where if they wouldn't match multiple left side values, for each value it didn't match it would add a row. This is triggered by the change to https://github.com/apache/arrow-datafusion/pull/842 which maps any value to a 0 hash. Normally values and null values have different hashes, so they wouldn't have this problem.
Instead the correct behavior is to add a single row if it doesn't match any. 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/src/physical_plan/hash_join.rs [hunk 1]
```diff
@@ -745,9 +747,12 @@ fn build_join_indexes(
                                 &keys_values,
                             )? {
                                 left_indices.append_value(i)?;
-                            } else {
-                                left_indices.append_null()?;
+                                right_indices.append_value(row as u32)?;
```
Comment (Dandandan) [inline datafusion/src/physical_plan/hash_join.rs:750]: This is the fix, instead of adding the (left=null, right) to every non-match, it does it only once at the end if there wasn't a single match.

File: datafusion/src/physical_plan/hash_join.rs [hunk 2]
```diff
@@ -745,9 +747,12 @@ fn build_join_indexes(
...
+                                no_match = false;
                             }
+                        }
+                        if no_match {
```
Comment (alamb) [inline datafusion/src/physical_plan/hash_join.rs:753]:
```suggestion
                       // If no rows matched left, still must keep the right
                       // with all nulls for left
                        if no_match {
```

**Review by alamb — APPROVED** [review]
Talk about a speedy bugfix 🐎 ! I barely filed the ticket and there is a fix ready :)

One thing that might help readability would be to rename from double negative (no_match false) to `has_match` or something 

Nice work @Dandandan

**Review by houqp — APPROVED** [review]
good catch :+1:
