### PR TITLE
Fix bug in `SimplifyExpressions`

### LINKED ISSUE #7700: Bug in SimplifyExpressions
### Describe the bug

SimplifyExpressions doesn't have access to the entire schema, resulting in planning errors when the filter can be pushed down entirely to the tablescan.

```
        let fields = vec![
            Field::new("a", DataType::UInt32, false),
            Field::new("b", DataType::UInt32, false),
            Field::new("c", DataType::UInt32, false),
        ];

        let schema = Schema::new(fields);

        let table_scan = table_scan_with_filters(
            Some("test"),
            &schema,
            Some(vec![0]),
            vec![col("b").is_not_null()],
        )?
        .build()?;
        assert_eq!(1, table_scan.schema().fields().len());
        assert_fields_eq(&table_scan, vec!["a"]);

        let expected = "TableScan: test projection=[a], full_filters=[Boolean(true) AS b IS NOT NULL]";

        assert_optimized_plan_eq(&table_scan, expected)
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Dandandan**
## Which issue does this PR close?

Closes #7700

## Rationale for this change

Fix issue in `SimplifyExpressions` optimizer which fails to simplify the TableScan filter expressions.
This became visible in our testing after #7670 was merged.

### CODE REVIEW

**Review by thinkharderdev — APPROVED** [review]

File: datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs [hunk 1]
```diff
@@ -65,10 +65,13 @@ impl SimplifyExpressions {
     ) -> Result<LogicalPlan> {
         let schema = if !plan.inputs().is_empty() {
             DFSchemaRef::new(merge_schema(plan.inputs()))
-        } else if let LogicalPlan::TableScan(_) = plan {
+        } else if let LogicalPlan::TableScan(scan) = plan {
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs:68]: nice
