### PR TITLE
fix: casting Int64 to Float64 unsuccessfully caused tpch8 to fail

### LINKED ISSUE #1576: casting `Int64` to `Float64` unsuccessfully caused tpch8 to fail
**Describe the bug**
During running tpch8, I got the following error:
```
➜  benchmarks git:(fix_cross_join) cargo run --release --bin tpch -- benchmark datafusion --iterations 3 --path ./data --format tbl --query 8 --batch-size 4096
    Finished release [optimized] target(s) in 0.71s
     Running benchmarks with the following options: DataFusionBenchmarkOpt { query: 8, debug: false, iterations: 3, partitions: 2, batch_size: 4096, path: "./data", file_format: "tbl", mem_table: false }
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'false_values downcast failedfalse_values downcast failed', ', datafusion/src/physical_plan/expressions/case.rsdatafusion/src/physical_plan/expressions/case.rs::218218::3030

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: ArrowError(ExternalError(ArrowError(ExternalError(Execution("Arrow error: External error: oneshot canceled")))))
```

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by xudong963**
# Which issue does this PR close?

Closes #1576   #165

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by xudong963** [comment]
```
➜  benchmarks git:(fix_cast) ✗ cargo run --release --bin tpch -- benchmark datafusion --iterations 3 --path ./data --format tbl --query 8 --batch-size 4096
 
Running benchmarks with the following options: DataFusionBenchmarkOpt { query: 8, debug: false, iterations: 3, partitions: 2, batch_size: 4096, path: "./data", file_format: "tbl", mem_table: false }
Query 8 iteration 0 took 6401.8 ms
Query 8 iteration 1 took 5731.4 ms
Query 8 iteration 2 took 5830.1 ms
Query 8 avg time: 5987.78 ms
```

**Comment by xudong963** [comment]
One problem with this modification is that `float64` to `int` causes a loss of accuracy.  I think `return_type` decided by `then` data type is unreasonable. 

I checked Postgres' behavior, it can process reasonably.
```sql
postgres=# SELECT * FROM test;
 a
---
 1
 2
 3
(3 rows)


postgres=# SELECT a,
       CASE WHEN a=1 THEN 1.2
            ELSE 0
       END
    FROM test;
 a | case
---+------
 1 |  1.2
 2 |    0
 3 |    0
(3 rows)


postgres=# SELECT a,
       CASE WHEN a=1 THEN 12
            ELSE 5.4
       END
    FROM test;
 a | case
---+------
 1 |   12
 2 |  5.4
 3 |  5.4
(3 rows)
```

**Comment by houqp** [comment]
>  I think return_type decided by then data type is unreasonable.

I agree, better to take both branches into account.

**Review by houqp — APPROVED** [review]
Good job unlocking more TPCH queries!

File: datafusion/src/physical_plan/expressions/case.rs [hunk 1]
```diff
@@ -324,7 +325,10 @@ impl CaseExpr {
 
         // start with the else condition, or nulls
         let mut current_value: Option<ArrayRef> = if let Some(e) = &self.else_expr {
-            Some(e.evaluate(batch)?.into_array(batch.num_rows()))
+            // keep `else_expr`'s data type and return type consistent
```
Comment (alamb) [inline datafusion/src/physical_plan/expressions/case.rs:328]: Eventually it would be great to separate out the `coercion` logic into the `

```rust

/// Create a CASE expression
pub fn case(
    expr: Option<Arc<dyn PhysicalExpr>>,
    when_thens: &[WhenThen],
    else_expr: Option<Arc<dyn PhysicalExpr>>,
) -> Result<Arc<dyn PhysicalExpr>> {
    Ok(Arc::new(CaseExpr::try_new(expr, when_thens, else_expr)?))
}

```

function the way it is done with `BinaryExpr` and `binary_cast`

https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/expressions/binary.rs#L1106-L1114

But this is better than master so 👍

**Review by alamb — APPROVED** [review]
Thanks @xudong963  !

**Comment by xudong963** [comment]
> > I think return_type decided by then data type is unreasonable.
> 
> I agree, better to take both branches into account.

Next PR I'll do the thing and keep consistent with Postgres. cc @alamb

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/1609 to track
