### PR TITLE
fix: fix joins on Float32/Float64 columns bug

### LINKED ISSUE #1053: [Datafusion] - Support joins on Float32/Float64 columns
**Describe the bug**

When I joins on Float32/Float64 columns, there is a issue:

```sql
> select * from public.simple as a join (select * from public.simple as b) on a.c1=b.c1;
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Unsupported data type in hasher")', datafusion/src/physical_plan/hash_join.rs:583:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Unsupported data type in hasher")', datafusion/src/physical_plan/hash_join.rs:583:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Unsupported data type in hasher")', datafusion/src/physical_plan/hash_join.rs:583:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Unsupported data type in hasher")', datafusion/src/physical_plan/hash_join.rs:583:14
0 rows in set. Query took 0.034 seconds.
```

table info:

```sql
> show columns from public.simple;
+---------------+--------------+------------+-------------+-----------+-------------+
| table_catalog | table_schema | table_name | column_name | data_type | is_nullable |
+---------------+--------------+------------+-------------+-----------+-------------+
| datafusion    | public       | simple     | c1          | Float64   | NO          |
| datafusion    | public       | simple     | c2          | Float64   | NO          |
| datafusion    | public       | simple     | c3          | Boolean   | NO          |
+---------------+--------------+------------+-------------+-----------+-------------+
```

There is also this similar issue #187, These issues is caused by hash join `equal rows` not support Float32/Float64 datatypes. I will fix this.

https://github.com/apache/arrow-datafusion/blob/26399ed2405dcacd505f4af73c5ecf608cb6aa9d/datafusion/src/physical_plan/hash_join.rs#L759-L796

### PR DESCRIPTION
**Pull request by francis-du**
# Which issue does this PR close?

Close #1053 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/tests/sql.rs [hunk 1]
```diff
@@ -2124,6 +2124,118 @@ async fn cross_join_unbalanced() {
...
+            Arc::new(Float32Array::from(vec![164.159, 143.352, 264.366])),
+        ],
+    )?;
+    let area_table = MemTable::try_new(area_schema, vec![vec![area_data]])?;
+    ctx.register_table("area", Arc::new(area_table))?;
+
+    let sql = "SELECT population.city, population.population, area.area \
+                     FROM population \
+                     JOIN (SELECT * FROM area) \
+                     ON population.city = area.city \
```
Comment (Dandandan) [inline datafusion/tests/sql.rs:2165]: For testing the feature, don't we want to join on the float columns?

Comment (francis-du) [reply datafusion/tests/sql.rs:2165]: Thank you for your reminder, I am going to modify it.

**Review by Dandandan — APPROVED** [review]

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
Thanks @francis-du !
