### PR TITLE
Fix logical plan serialization 

### LINKED ISSUE #3555: Broken logical plan serialization for aggregation queries
**Describe the bug**

Some aggregation plans will fail to deserialize. This is caused by a rewrite done by the `TypeCoercion` optimizer. 

**To Reproduce**

```
    #[tokio::test]
    async fn roundtrip_logical_plan_aggregation() -> Result<(), DataFusionError> {
        let ctx = SessionContext::new();

        let schema = Schema::new(vec![
            Field::new("a", DataType::Int64, true),
            Field::new("b", DataType::Decimal128(15,2), true)
        ]);

        ctx.register_csv("t1", "testdata/test.csv", CsvReadOptions::default().schema(&schema)).await?;

        let query = "SELECT a, SUM(b + 1) FROM t1 GROUP BY a";
        let plan = ctx.sql(query).await?.to_logical_plan()?;

        let bytes =
            logical_plan_to_bytes(&plan)?;
        let logical_round_trip =
            logical_plan_from_bytes(&bytes, &ctx)?;
        assert_eq!(
            format!("{:?}", plan),
            format!("{:?}", logical_round_trip)
        );
        Ok(())
```

This fails with
```
Error: SchemaError(FieldNotFound { qualifier: None, name: "SUM(t1.b + Int64(1))", valid_fields: Some(["t1.a", "SUM(t1.b + Decimal128(Some(100),23,2))", "t1.a", "t1.b"]) })
```

The problem is there is a projection after this which projects the original expression name. Typically this doesn't matter since the schema is unchanged and everything still aligns. But when we deserialize we have to build the plan again and it will fail to validate. 

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by thinkharderdev**
# Which issue does this PR close?

Closes #3555 

 # Rationale for this change

Currently round-trip logical plan serialization is broken for some aggregation queries. This happens when the `TypeCoercion` optimizer casts literal values in aggregate function expressions and then the const evaluator optimizes out the cast (replacing with a literal for the casted value). This effectively changes the expression name and causes a mismatch when rebuilding the plan after deserialization. 

# What changes are included in this PR?

In `TypeCoercion` special-case the handling of aggregation function expressions to make sure we alias back to the original expression name if it has changed. This should ensure the schema is still valid and the plan can be rebuilt from its serialized representation. 

# Are there any user-facing changes?

no

no

### CODE REVIEW

**Comment by thinkharderdev** [comment]
@alamb @andygrove This feels like a bit of hacky special casing but seemed like the least insrusive way to deal with this. If optimizers can change expression names in general though this could come up in other places w/r/t serde of aggregation plans where we rely explicitly on the expression name.

File: datafusion/optimizer/src/type_coercion.rs [hunk 1]
```diff
@@ -79,10 +79,29 @@ impl OptimizerRule for TypeCoercion {
...
+
         let new_expr = plan
             .expressions()
             .into_iter()
-            .map(|expr| expr.rewrite(&mut expr_rewrite))
+            .zip(original_expr_names)
+            .map(|(expr, original_name)| {
+                let expr = expr.rewrite(&mut expr_rewrite)?;
+
+                if matches!(expr, Expr::AggregateFunction { .. }) {
```
Comment (alamb) [inline datafusion/optimizer/src/type_coercion.rs:95]:
```suggestion
                // ensure aggregate names don't change:
                // https://github.com/apache/arrow-datafusion/issues/3555
                if matches!(expr, Expr::AggregateFunction { .. }) {
```

**Review by alamb — APPROVED** [review]
I agree this seems a little icky (like it is treating the symptom rather than the root cause) but I think it is tested and seems reasonable to me

**Comment by alamb** [comment]
I wish I had a better story for you

**Comment by alamb** [comment]
I believe this PR is going to fail its checks until is it merged to include https://github.com/apache/arrow-datafusion/pull/3576

File: datafusion/optimizer/src/type_coercion.rs (hunk 1 above)
Comment (liukun4515) [reply datafusion/optimizer/src/type_coercion.rs:97]: I think this is just a workround for this issue. We should split the type coercion from the optimizer

Comment (thinkharderdev) [reply datafusion/optimizer/src/type_coercion.rs:97]: Yeah, I agree

**Comment by alamb** [comment]
I wonder if https://github.com/apache/arrow-datafusion/issues/3568 could be related

**Comment by thinkharderdev** [comment]
> I wonder if #3568 could be related

Yeah, if I understand that ticket correctly then it's the same underlying issue
