### PR TITLE
fix:  incorrect memory usage track for sort

### LINKED ISSUE #2155: Inconsistent memory tracking for SortExec
**Describe the bug**

We have moved requesters' memory tracking method in #1691:

> Consumers push their memory usage to MemoryManager. No more pull from MemoryManagers for usage updates.

Inconsistency memory tracking exists for SortExec, which may cause incorrect total memory accounting in the memory manager, and potentially block other requesters' running when we have more than one requester.

### PR DESCRIPTION
**Pull request by yjshen**
# Which issue does this PR close?

Closes #2155.

 # Rationale for this change

1. Since we've changed Memory Requesters' memory tracking behavior in https://github.com/apache/arrow-datafusion/pull/1691:
  > Consumers push their memory usage to MemoryManager. No more pull from MemoryManagers for usage updates.
 
The sort memory is not correctly tracked anymore.

2. The debug log for "sleep on memory insufficient" introduced a deadlock by holding a lock and asking for the lock again.

# What changes are included in this PR?

- Correct sort memory track by manually update usage after sort.
- Stop trying to acquire the lock while already holding it.

# Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/core/src/physical_plan/sorts/sort.rs [hunk 1]
```diff
@@ -169,13 +169,19 @@ impl ExternalSorter {
...
+            self.free_all_memory();
             result
         } else {
             Ok(Box::pin(EmptyRecordBatchStream::new(self.schema.clone())))
         }
     }
 
+    fn free_all_memory(&self) -> usize {
+        let used = self.metrics.mem_used().set(0);
+        self.shrink(used);
```
Comment (yjshen) [inline datafusion/core/src/physical_plan/sorts/sort.rs:181]: The first fix, return all memory to the manager.

File: datafusion/core/src/execution/memory_manager.rs [hunk 2]
```diff
@@ -342,8 +349,8 @@ impl MemoryManager {
                 // if we cannot acquire at lease 1/2n memory, just wait for others
                 // to spill instead spill self frequently with limited total mem
                 debug!(
-                    "Cannot acquire minimum amount of memory {} on memory manager {}, waiting for others to spill ...",
-                    human_readable_size(min_per_rqt), self);
+                    "Cannot acquire a minimum amount of {} memory from the manager of total {}, waiting for others to spill ...",
```
Comment (yjshen) [inline datafusion/core/src/execution/memory_manager.rs:352]: The second fix: stop calling std::fmt::Display on memory manager since it's acquiring a lock we are already holding.

File: datafusion/core/src/execution/memory_manager.rs [hunk 3]
```diff
@@ -378,6 +403,8 @@ impl MemoryManager {
                 let mut total = self.requesters_total.lock();
                 assert!(*total >= mem_used);
                 *total -= mem_used;
+                self.cv.notify_all();
+                return;
```
Comment (yjshen) [inline datafusion/core/src/execution/memory_manager.rs:407]: The third fix: stop releasing memory twice for requesters.

**Review by alamb — APPROVED** [review]
Looks good to me -- thanks @yjshen
