### PR TITLE
fix: add one more projection to recover output schema

### LINKED ISSUE #4575: `common_sub_expression_eliminate`  exists bug
**Describe the bug**

It will make some strange problem.

```
Error: Internal("Optimizer rule 'common_sub_expression_eliminate' failed, due to generate a different schema, original schema: 

DFSchema { fields: [
DFField { qualifier: Some(\"t1\"), field: Field { name: \"t1_id\", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t1\"), field: Field { name: \"t1_name\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t1\"), field: Field { name: \"t1_int\", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t2\"), field: Field { name: \"t2_id\", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t2\"), field: Field { name: \"t2_name\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t2\"), field: Field { name: \"t2_int\", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }], metadata: {} }, new schema: 

DFSchema { fields: [
DFField { qualifier: None, field: Field { name: \"t2.t2_int < UInt32(10)UInt32(10)t2.t2_int\", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t1\"), field: Field { name: \"t1_id\", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t1\"), field: Field { name: \"t1_name\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t1\"), field: Field { name: \"t1_int\", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t2\"), field: Field { name: \"t2_id\", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t2\"), field: Field { name: \"t2_name\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }, 
DFField { qualifier: Some(\"t2\"), field: Field { name: \"t2_int\", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }], metadata: {} }")

original:
"Filter: t2.t2_int < Int64(10) OR t1.t1_int > Int64(2) AND t2.t2_name != Utf8("w")
  Left Join: t1.t1_id = t2.t2_id
    TableScan: t1
    TableScan: t2"

after:
"Filter: (t2.t2_int < UInt32(10)UInt32(10)t2.t2_int AS t2.t2_int < UInt32(10) OR t1.t1_int > UInt32(2)) AND (t2.t2_int < UInt32(10)UInt32(10)t2.t2_int AS t2.t2_int < UInt32(10) OR t2.t2_name != Utf8("w"))
  Projection: t2.t2_int < UInt32(10) AS t2.t2_int < UInt32(10)UInt32(10)t2.t2_int, t1.t1_id, t1.t1_name, t1.t1_int, t2.t2_id, t2.t2_name, t2.t2_int
    Inner Join: t1.t1_id = t2.t2_id
      TableScan: t1 projection=[t1_id, t1_name, t1_int]
      TableScan: t2 projection=[t2_id, t2_name, t2_int]"
```

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by waynexia**
# Which issue does this PR close?

Closes #4575 .

# Rationale for this change

`common_subexpression_eliminate` optimizer doesn't consider the situation that some plans (like `Sort` or `Filter`) rely on the input's schema. When introducing an intermediate projection schema that evaluates the common expressions, it also changes the "input schema" for those optimized plans. This patch will check if the output schema changed, and add another projection to recover the output schema if so.

# What changes are included in this PR?

Except the extra projection described above, this patch also fixes the problem that the optimizer used to build `Projection` plan manually, rather than through `Projection::try_new()` constructor. This will bypass the schema check process and may produce a wrong projection plan, whose schema doesn't match its exprs.
 

# Are these changes tested?

Yes, add a new case `filter_schema_changed` to cover

# Are there any user-facing changes?

no

### CODE REVIEW

File: datafusion/core/tests/sql/predicates.rs [hunk 1]
```diff
@@ -591,8 +591,8 @@ async fn multiple_or_predicates() -> Result<()> {
...
...quantity:Boolean, lineitem.l_quantity <= Decimal128(Some(2000),15,2)Decimal128(Some(2000),15,2)lineitem.l_quantity:Boolean, lineitem.l_quantity <= Decimal128(Some(3000),15,2)Decimal128(Some(3000),15,2)lineitem.l_quantity:Boolean, lineitem.l_quantity >= Decimal128(Some(100),15,2) OR lineitem.l_quantity <= Decimal128(Some(2000),15,2)lineitem.l_quantity <= Decimal128(Some(2000),15,2)Decimal128(Some(2000),15,2)lineitem.l_quantitylineitem.l_quantity >= Decimal128(Some(100),15,2)Decimal128(Some(100),15,2)lineitem.l_quantity:Boolean, lineitem.l_quantity >= Decimal128(Some(100),15,2) OR lineitem.l_quantity >= Decimal128(Some(1000),15,2)lineitem.l_quantity >= Decimal128(Some(1000),15,2)Decimal128(Some(1000),15,2)lineitem.l_quantitylineitem.l_quantity >= Decimal128(Some(100),15,2)Decimal128(Some(100),15,2)lineitem.l_quantity:Boolean, lineitem.l_quantity >= Decimal128(Some(100),15,2)Decimal128(Some(100),15,2)lineitem.l_quantity:Boolean, lineitem.l_quantity >= Decimal128(Some(1000),15,2)Decimal128(Some(1000),15,2)lineitem.l_quantity:Boolean, lineitem.l_quantity >= Decimal128(Some(2000),15,2)Decimal128(Some(2000),15,2)lineitem.l_quantity:Boolean, l_partkey:Int64, l_quantity:Decimal128(15, 2)]",
```
Comment (waynexia) [inline datafusion/core/tests/sql/predicates.rs:595]: This diff says schema's nullability has changed (`;N`). It's because the field used to be hardcoded to "nullable".

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 2]
```diff
@@ -754,24 +775,37 @@ mod test {
...
         Ok(())
     }
 
     #[test]
     fn redundant_project_fields() {
         let table_scan = test_table_scan().unwrap();
         let affected_id: BTreeSet<Identifier> =
-            ["c+a".to_string(), "d+a".to_string()].into_iter().collect();
-        let expr_set = [
+            ["c+a".to_string(), "b+a".to_string()].into_iter().collect();
```
Comment (waynexia) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:785]: Some notes for this and the next test case's changes:

The mock table scan doesn't have a column named "`d`", so I changed it to "`b`". And "a", "b" are ambiguous when join, thus I add qualifiers to them.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 3]
```diff
@@ -143,10 +143,15 @@ impl OptimizerRule for CommonSubexprEliminate {
                 )?;
 
                 if let Some(predicate) = pop_expr(&mut new_expr)?.pop() {
-                    Ok(Some(LogicalPlan::Filter(Filter::try_new(
+                    let filter = LogicalPlan::Filter(Filter::try_new(
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:146]: 💯  for using `try_new`

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 4]
```diff
@@ -209,16 +214,21 @@ impl OptimizerRule for CommonSubexprEliminate {
...
+                let sort = LogicalPlan::Sort(Sort {
                     expr: pop_expr(&mut new_expr)?,
                     input: Arc::new(new_input),
                     fetch: *fetch,
-                })))
+                });
+                if sort.schema() == &input_schema {
+                    Ok(Some(sort))
+                } else {
+                    Ok(Some(build_recover_project_plan(&input_schema, sort)))
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:230]: I wonder if it would be possible to reduce the replication as well as be slightly more "defensive" coding style if instead of `build_recover_project_plan` on each path, it could be called  once to ensure the schema was always the same

Something like

```rust
impl OptimizerRule for CommonSubexprEliminate {
    fn try_optimize(
        &self,
        plan: &LogicalPlan,
        config: &dyn OptimizerConfig,
    ) -> Result<Option<LogicalPlan>> {
        let mut expr_set = ExprSet::new();
        let input_schema = Arc::clone(&plan.schema());
 
        let new_plan =  match plan {
          ...
         }?;

         if new_plan.schema() == &input_schema {
           Ok(Some(new_plan))
         } else {
           Ok(Some(build_recover_project_plan(&input_schema, new_plan)))
        }
  }
```

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 5]
```diff
@@ -858,4 +911,26 @@ mod test {
...
+
+    #[test]
+    fn filter_schema_changed() -> Result<()> {
+        let table_scan = test_table_scan()?;
+
+        let plan = LogicalPlanBuilder::from(table_scan)
+            .filter(binary_expr(
+                binary_expr(lit(1), Operator::Gt, col("a")),
+                Operator::And,
+                binary_expr(lit(1), Operator::Gt, col("a")),
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:923]: You might be able to write this in a more "fluent" style if you wanted

```suggestion
            .filter(lit(1).gt(col("a"))).and(
                      lit(1).gt(col("a"))),
```

**Review by alamb — APPROVED** [review]
Thank you @waynexia 

cc @liukun4515  and @jackwener

File: datafusion/core/tests/sql/predicates.rs (hunk 1 above)
Comment (waynexia) [reply datafusion/core/tests/sql/predicates.rs:595]: Collapse this, it's toooo long

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 4 above)
Comment (waynexia) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs]: Thanks for this! It's really a good practice 👍

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 6]
```diff
@@ -254,9 +238,16 @@ impl OptimizerRule for CommonSubexprEliminate {
             | LogicalPlan::Extension(_)
             | LogicalPlan::Prepare(_) => {
                 // apply the optimization to all inputs of the plan
-                Ok(Some(utils::optimize_children(self, plan, config)?))
+                utils::optimize_children(self, plan, config)?
             }
+        };
+
+        // add an additional projection if the output schema changed.
+        if optimized_plan.schema() != &original_schema {
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:246]: 👍

**Review by alamb — APPROVED** [review]
