### PR TITLE
Fix datatype of case expression

### LINKED ISSUE #5733: Case statement with one branch being null gives "Mismatch between schema and batches"
### Describe the bug

Case statement, where the first branch is `NULL` and another one is a number causes  "Mismatch between schema and batches" error.

In batch schema, such column has `Int32` datatype (or some similar).

In plan schema, such columns have an invalid datatype `Null`.

### To Reproduce

Add this to the middle of `pg_compat_union.slt`:

```
statement ok
CREATE TABLE aggregate_test_100_nullable_by_sql AS
SELECT
    *,
    CASE
        WHEN c4 % 3 = 0 THEN NULL
        ELSE c5
    END AS n5,
    CASE
        WHEN c3 % 3 != 0 THEN c9
        ELSE NULL
    END AS n9
FROM aggregate_test_100_by_sql
```

Under Postgres this statement succeeds.

### Expected behavior

To have the same behavior as Postgres: success.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mslapek**
# Which issue does this PR close?

Fixes #5733

# Rationale for this change

Fixes the issue.

# What changes are included in this PR?

Make `Expr::schema` return coerced `DataType` for `Expr::Case`.

# Are these changes tested?

Added `pg_compat_null.slt` reproducing the issue.

# Are there any user-facing changes?

No, except the bug fix.

### CODE REVIEW

File: datafusion/expr/src/expr_schema.rs [hunk 1]
```diff
@@ -68,7 +69,26 @@ impl ExprSchemable for Expr {
             Expr::OuterReferenceColumn(ty, _) => Ok(ty.clone()),
             Expr::ScalarVariable(ty, _) => Ok(ty.clone()),
             Expr::Literal(l) => Ok(l.get_datatype()),
-            Expr::Case(case) => case.when_then_expr[0].1.get_type(schema),
+            Expr::Case(case) => {
+                // when #5681 will be fixed, this code can be reverted to:
```
Comment (yjshen) [inline datafusion/expr/src/expr_schema.rs:73]: How about moving TypeCoersion to `analyzer` to fix #5733 instead of making a temporary workaround?

Comment (mslapek) [reply datafusion/expr/src/expr_schema.rs:73]: I agree that it's a duck-taping.

I'm afraid the mentioned issue **won't be resolved quickly** by cut'n'paste... (see https://github.com/apache/arrow-datafusion/issues/5681#issuecomment-1483780310 )

So the question is - **should we expose our users to the bug** 🧐 until #5681 is fixed? (putting Datafusion's **reputation** at risk?)

What is more, this PR features **sqlogictest** ⭐️, so we won't have a regression caused by the fix #5681.

File: datafusion/core/tests/sqllogictests/test_files/pg_compat/pg_compat_null.slt [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+        ELSE c5
+    END AS n5,
+    CASE
+        WHEN c3 % 3 != 0 THEN c9
+        ELSE NULL
+    END AS n9
+FROM aggregate_test_100_by_sql
+
+
+query III
```
Comment (comphead) [inline datafusion/core/tests/sqllogictests/test_files/pg_compat/pg_compat_null.slt:88]: Slightly concerned if this test is actually needed, the PR is to fix schema mismatch on case statement

Comment (mslapek) [reply datafusion/core/tests/sqllogictests/test_files/pg_compat/pg_compat_null.slt:88]: The test involves CASE statement, and it was crashing before the fix (the CREATE TABLE one).

The file itself might be useful for other null-related bugfixes.

File: datafusion/expr/src/expr_schema.rs (hunk 1 above)
Comment (mslapek) [reply datafusion/expr/src/expr_schema.rs:73]: The type coercion is implemented as an optimizer - and it changes schemas of particular `Expr`essions.
And it **takes care** of `Expr::Case`.

But `Expr::Projection` caches the schema in itself - so it is not updated! Therefore we get a mismatch between declared schema vs batch schema.

Essentially this PR makes `Expr::Case` to **not** change a schema during the coercion optimizer.

**Comment by alamb** [comment]
Sorry for the delay -- what I have been (secretly) hoping is that we can move the type coercion into an analyzer pass and avoid the need for this workaround.

**Comment by alamb** [comment]
Here is what I think we should do to move this PR forward: I will file a ticket to remove this code from here (and into the analysis phase), and then we'll merge it in and we can do the cleanup with the analysis phase as a follow on

File: datafusion/expr/src/expr_schema.rs (hunk 1 above)
Comment (alamb) [reply datafusion/expr/src/expr_schema.rs:73]: Filed https://github.com/apache/arrow-datafusion/issues/5821

**Comment by alamb** [comment]
FYI I tried the test case with the fix from @Jefffrey  in https://github.com/apache/arrow-datafusion/pull/5820 and sadly it still fails

I am merging this PR even though the code is non ideal -- my rationale is that it fixes a real bug, and has test coverage (with postgres verification). I have filed https://github.com/apache/arrow-datafusion/issues/5821 to fix it for real and will add that as a comment as a follow on PR
