### PR TITLE
Fix CREATE SCHEMA schema name double quoting issue.

### LINKED ISSUE #5058: Quoted schema and table names result in double-quoted names in logical plan.
# Description
Quoted schema and table names appear double-quoted in the query plan.

# Reproduction
My types of SQL statements are affected, `CREATE SCHEMA` is just one example:
```rust
let sql = "CREATE SCHEMA \"quoted_schema_name\"";
let plan = logical_plan(sql).unwrap();
assert_eq!(format!("{plan:?}"), "CREATE SCHEMA \"\"quoted_schema_name\"\"");
```

# Expected behavior
Quoted identifiers should remain single-quoted (or possibly unquoted if they contain no special characters).

# Root cause
The `sqlparser` create uses `ast::Ident` (often packaged as `ast::ObjectName`'s) to store identifiers such as table, schema, and column names. `Ident` stores the actualy identifier in its `value` field, plus an optional quote character in `quoting_style`. `Ident::to_string()` applies the quotes when `quoteing_style` is not `None`. The result of `Ident::to_string()` is once-again quoted by datafusion. For non-quoted identifiers only the second quoting is applied, masking the bug.

Since datafusion does it's own quoting, `Ident::to_string()` calls should be replaced by `ident.value`.

Example occurance: [`Ident::toString()` usage for `CREATE SCHEMA`](
https://github.com/apache/arrow-datafusion/blob/2aa14900e23d2eb97e950f1758cdbe0f8a27e55b/datafusion/sql/src/statement.rs#L173)

### PR DESCRIPTION
**Pull request by neumark**
# Which issue does this PR close?
Closes #5058

# Rationale for this change
The changes fix a bug resulting in double-quoted identifiers in SQL query plans.

# What changes are included in this PR?
The changes affect logical plan creation in `datafusion/sql/src/statement.rs`

# Are these changes tested?
The PR includes an integration test for the `CREATE SCHEMA` SQL statement.

# Are there any user-facing changes?
User queries with quoted identifiers will work as expected due to this change.

### CODE REVIEW

File: datafusion/sql/src/statement.rs [hunk 1]
```diff
@@ -40,14 +40,39 @@ use datafusion_expr::{
...
+        .join(".")
+}
+
+fn get_schema_name(schema_name: &SchemaName) -> String {
+    match schema_name {
+        SchemaName::Simple(schema_name) => object_name_to_string(schema_name),
+        SchemaName::UnnamedAuthorization(auth) => ident_to_string(auth),
+        SchemaName::NamedAuthorization(schema_name, auth) => format!(
+            "{}.{}",
+            object_name_to_string(schema_name),
```
Comment (alamb) [inline datafusion/sql/src/statement.rs:70]: I wonder if this name needs to be normalized too

like `CREATE SCHEMA Foo` should create the schema `foo` (not `Foo`)

**Review by alamb — APPROVED** [review]
Thank you @neumark  -- this is looking great. I had a question about some other corner cases but I think this PR is an improvement on master so it could be merged

File: datafusion/sql/src/statement.rs (hunk 1 above)
Comment (neumark) [reply datafusion/sql/src/statement.rs:70]: Hey, thank you so much for the quick and positive response!
Honestly, I have no idea if `Foo` should become `foo`, but I'm happy to update the code to call `utils::normalize_ident()` on `ident.value` if necessary!

Comment (alamb) [reply datafusion/sql/src/statement.rs:70]: Yes I think it should be lowercase, here is a demonstration of how that works in postgres:

```sql
postgres=# drop schema foo;
DROP SCHEMA
postgres=# create schema foo;
CREATE SCHEMA
postgres=# drop schema foo;
DROP SCHEMA
postgres=# create schema FoO;
CREATE SCHEMA
postgres=# create schema foo;
ERROR:  schema "foo" already exists
```

**Review by alamb — APPROVED** [review]

File: datafusion/sql/src/statement.rs (hunk 1 above)
Comment (neumark) [reply datafusion/sql/src/statement.rs:71]: Thanks for the input! The code in the PR now calls `normalize_ident` and includes an integration test asserting this behavior.

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @neumark
