### PR TITLE
First and Last Accumulators should update with state row excluding is_set flag

### LINKED ISSUE #7567: First and Last Accumulators should update with state row excluding is_set flag
### Describe the bug

First and Last Accumulators would update itself from first/last row during merging state batches (e.g., merge_batch). However, currently it takes the whole state row (which includes is_set flag) into update_with_new_row which in turn takes all columns except for first one into orderings (so existing is_set is put there) and adds is_set flag. This ends with double is_set flags if state is called on the accumulators which have merged state batches.

Normally this is not an issue because state is not called once aggregation enters the stage of merging state batches. But in https://github.com/apache/arrow-datafusion/pull/7400, where spilling happens to call state on such accumulators to get its states and spill into disk. This leads to a hacky fix there and we should fix these two accumulators accordingly to avoid the hacky way.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #7567.

Closes https://github.com/apache/arrow-datafusion/pull/7559

## Rationale for this change

First and Last Accumulators would update itself from first/last row during merging state batches (e.g., `merge_batch`). However, currently it takes the whole state row (which includes `is_set` flag) into `update_with_new_row` which in turn takes all columns except for first one into `orderings` (so existing `is_set` is put there) and adds `is_set` flag. This ends with double `is_set` flags if `state` is called on the accumulators which have merged state batches.

Normally this is not an issue because `state` is not called once aggregation enters the stage of merging state batches. But in #7400, where spilling happens to call `state` on such accumulators to get its states and spill into disk. This leads to a hacky fix there and we should fix these two accumulators accordingly to avoid the hacky way.

### CODE REVIEW

**Comment by viirya** [comment]
cc @kazuyukitanimura @alamb

File: datafusion/physical-expr/src/aggregate/first_last.rs [hunk 1]
```diff
@@ -550,4 +559,72 @@ mod tests {
...
     }
+
+    #[test]
+    fn test_first_last_state_after_merge() -> Result<()> {
+        let ranges: Vec<(i64, i64)> = vec![(0, 10), (1, 11), (2, 13)];
+        // create 3 ArrayRefs between each interval e.g from 0 to 9, 1 to 10, 2 to 12
+        let arrs = ranges
+            .into_iter()
+            .map(|(start, end)| {
+                Arc::new(Int64Array::from((start..end).collect::<Vec<_>>())) as ArrayRef
```
Comment (alamb) [inline datafusion/physical-expr/src/aggregate/first_last.rs:570]: I think you can collect the array directly

```suggestion
                Arc::new((start..end).collect::<Int64Array>())) as ArrayRef
```

**Review by alamb — APPROVED** [review]
This makes sense to me -- thank you @viirya ❤️

File: datafusion/physical-expr/src/aggregate/first_last.rs [hunk 2]
```diff
@@ -550,4 +559,72 @@ mod tests {
...
+        }
+
+        let mut first_accumulator =
+            FirstValueAccumulator::try_new(&DataType::Int64, &[], vec![])?;
+        first_accumulator.merge_batch(&states)?;
+
+        let merged_state = first_accumulator.state()?;
+        assert_eq!(merged_state.len(), state1.len());
+
+        // LastValueAccumulator
```
Comment (sunchao) [inline datafusion/physical-expr/src/aggregate/first_last.rs:601]: we probably can remove some common code here but not a blocker

**Review by sunchao — APPROVED** [review]

File: datafusion/physical-expr/src/aggregate/first_last.rs [hunk 3]
```diff
@@ -550,4 +559,72 @@ mod tests {
...
     }
+
+    #[test]
+    fn test_first_last_state_after_merge() -> Result<()> {
+        let ranges: Vec<(i64, i64)> = vec![(0, 10), (1, 11), (2, 13)];
+        // create 3 ArrayRefs between each interval e.g from 0 to 9, 1 to 10, 2 to 12
+        let arrs = ranges
+            .into_iter()
+            .map(|(start, end)| {
+                Arc::new((start..end).collect::<Int64Array>())) as ArrayRef
```
Comment (viirya) [inline datafusion/physical-expr/src/aggregate/first_last.rs:570]:
```suggestion
                Arc::new((start..end).collect::<Int64Array>()) as ArrayRef
```

File: datafusion/physical-expr/src/aggregate/first_last.rs [hunk 4]
```diff
@@ -237,13 +231,17 @@ impl Accumulator for FirstValueAccumulator {
         };
         if !ordered_states[0].is_empty() {
             let first_row = get_row_at_idx(&ordered_states, 0)?;
-            let first_ordering = &first_row[1..];
+            // When collecting orderings, we exclude the is_set flag from the state.
+            let first_ordering = &first_row[1..is_set_idx];
             let sort_options = get_sort_options(&self.ordering_req);
             // Either there is no existing value, or there is an earlier version in new data.
             if !self.is_set
                 || compare_rows(first_ordering, &self.orderings, &sort_options)?.is_lt()
```
Comment (kazuyukitanimura) [inline datafusion/physical-expr/src/aggregate/first_last.rs:239]: I am wondering if we need to do anything about `compare_rows(first_ordering, &self.orderings, &sort_options)` since now `first_ordering` is shorter?

**Review by kazuyukitanimura — COMMENTED** [review]
This looks a better solution. One question that I am still trying to understand...

File: datafusion/physical-expr/src/aggregate/first_last.rs [hunk 5]
```diff
@@ -237,13 +231,17 @@ impl Accumulator for FirstValueAccumulator {
         };
         if !ordered_states[0].is_empty() {
             let first_row = get_row_at_idx(&ordered_states, 0)?;
-            let first_ordering = &first_row[1..];
+            // When collecting orderings, we exclude the is_set flag from the state.
+            let first_ordering = &first_row[1..is_set_idx];
```
Comment (kazuyukitanimura) [inline datafusion/physical-expr/src/aggregate/first_last.rs:235]: `is_set_idx` is an index for `states` but does `first_row` have the same index? Can they be different because `filtered_states` may have filtered rows?

File: datafusion/physical-expr/src/aggregate/first_last.rs (hunk 4 above)
Comment (viirya) [reply datafusion/physical-expr/src/aggregate/first_last.rs:239]: It is not shorter. Actually, this fix makes them same length. Previously `first_ordering` has more one element (`is_set`).

File: datafusion/physical-expr/src/aggregate/first_last.rs (hunk 5 above)
Comment (kazuyukitanimura) [reply datafusion/physical-expr/src/aggregate/first_last.rs:235]: Please never mind, this should be the same

Comment (viirya) [reply datafusion/physical-expr/src/aggregate/first_last.rs:235]: Doesn't filtered_states come from `states`? Why they have different index?? They are simply partial aggregation inputs. Do you think there are different rows in partial aggregation inputs?

File: datafusion/physical-expr/src/aggregate/first_last.rs (hunk 4 above)
Comment (kazuyukitanimura) [reply datafusion/physical-expr/src/aggregate/first_last.rs:239]: Actually I found the only time `self.orderings` can be longer is right after the creation by `try_new()`. But at the time it is `self.is_set = false`, so it will not hit `compare_rows`. Then `self.orderings` is updated by `first_ordering`

**Review by kazuyukitanimura — APPROVED** [review]

**Comment by viirya** [comment]
Thank you @alamb @sunchao @kazuyukitanimura
