### PR TITLE
make format prefix optional for format options in COPY

### LINKED ISSUE #9716: All formatting options in COPY commands require `format.` prefix
### Describe the bug

https://github.com/apache/arrow-datafusion/pull/9604 from @metesynnada rationalized the COPY syntax to match CREATE EXTERNAL TABLE syntax which is great. However, now all options require a replicated `format.` string:

```diff
COPY source_table
to 'test_files/scratch/copy/table_csv_with_options'
-(format csv,
-'csv.has_header' false,
-'csv.compression' uncompressed,
-'csv.datetime_format' '%FT%H:%M:%S.%9f',
-'csv.delimiter' ';',
-'csv.null_value' 'NULLVAL');
+'format.has_header' false,
+'format.compression' uncompressed,
+'format.datetime_format' '%FT%H:%M:%S.%9f',
+'format.delimiter' ';',
+'format.null_value' 'NULLVAL');
```

### To Reproduce

```
❯ COPY (select * from (values (1))) to '/tmp/foo.parquet' STORED AS PARQUET OPTIONS ('format.compression' snappy);
+-------+
| count |
+-------+
| 1     |
+-------+
1 row in set. Query took 0.037 seconds.

❯ COPY (select * from (values (1))) to '/tmp/foo.parquet' STORED AS PARQUET OPTIONS ('compression' snappy);
Invalid or Unsupported Configuration: could not find config namespace for key "compression"
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tinfoil-knight**
## Which issue does this PR close?

Closes #9716 .

## Rationale for this change

**Before this PR**
User has to prefix all format options they pass to the `COPY` command with `format`. For eg:

```
COPY source_table
to 'test_files/scratch/copy/table_csv_with_options'
STORED AS CSV OPTIONS (
	'format.has_header' false,
	'format.compression' uncompressed,
	'format.datetime_format' '%FT%H:%M:%S.%9f',
	'format.delimiter' ';',
	'format.null_value' 'NULLVAL'
);
```

This is repetitive & different from what Datafusion 36.0.0 offered. (See issue description for more details)

**After this PR**

User can use the format options for the `COPY` command without prefixing them with `format`:

```
COPY source_table to 'test_files/scratch/copy/format_table.csv'
OPTIONS (
    has_header false,
    compression xz,
    datetime_format '%FT%H:%M:%S.%9f',
    delimiter ';',
    null_value 'NULLVAL'
);
```

## What changes are included in this PR?

We're prefixing keys passed in options with `format` if they don't contain a namespace (signified by presence of `.`).

## Are these changes tested?

Yes. New tests are added to verify that options not prefixed by `format` work.

## Are there any user-facing changes?

Current docs have the legacy format so updates aren't needed.

### CODE REVIEW

**Comment by tinfoil-knight** [comment]
1 test is failing on CI for multiple test suites. Wasn't able to reproduce the failure locally.

**Comment by alamb** [comment]
> 1 test is failing on CI for multiple test suites. Wasn't able to reproduce the failure locally.

I think it is due to the new Rust release,  https://github.com/apache/arrow-datafusion/issues/9724 (which has since been fixed)

**Comment by alamb** [comment]
I merged up to main to get the CI passing

**Review by alamb — APPROVED** [review]
Thank you @tinfoil-knight  -- this PR is most appreciated and seems to do exactly what it says.

I pushed one additional commit to verify that the error message for unknown cases is reasonable  and another to change the comments in the test that avoiding the `.format` is desired

cc @devinjdangelo @ozankabak @metesynnada  -- I think this PR is quite nice and elegantly supports a nicer UX while retaining the unified configuration support

**Comment by alamb** [comment]
I plan to merge this PR later today unless anyone would like additional time to review

**Comment by alamb** [comment]
Thanks again @tinfoil-knight

File: datafusion/sql/src/statement.rs [hunk 1]
```diff
@@ -850,7 +850,16 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
                 }
             };
-            options.insert(key.to_lowercase(), value_string.to_lowercase());
+            if !(&key.contains('.')) {
+                // If config does not belong to any namespace, assume it is
+                // a format option and apply the format prefix for backwards
+                // compatibility.
+
+                let renamed_key = format!("format.{}", key);
+                options.insert(renamed_key.to_lowercase(), value_string.to_lowercase());
```
Comment (xinlifoobar) [inline datafusion/sql/src/statement.rs:859]: Hi @tinfoil-knight @alamb, just would like to know the history of why we would make the value string lower case, I am encountering this case issue in another PR as described https://github.com/apache/datafusion/pull/10792/files#r1632877093. Thanks :)

Comment (tinfoil-knight) [reply datafusion/sql/src/statement.rs:859]: The change was originally added in this PR: https://github.com/apache/datafusion/pull/9382

It seems like the author of that PR was trying to consolidate case changes (using `to_lowercase`) in multiple places to just a single place. 

For now, you could add an exclusion for the access token option that is case sensitive in your PR so you can continue your work.

Ideally, we should probably stop lower-casing the options and handle case-sensitivity in the specific reader.

Comment (ozankabak) [reply datafusion/sql/src/statement.rs:859]: Having keys lowercased makes sense for standardization purposes, but I'm not sure why we are also lowercasing option values. It may either be because (1) of the same standardization concerns, or (2) by mistake.

The most flexible way would be to make value (not key) standardization logic customizable, with the default being lowercase. If we had that, users like @xinlifoobar would be able to avoid standardization modifications. Other users who want other kinds of standardizations would be able to override it etc.

@tinfoil-knight, would you be interested in thinking about how we can do this?

Comment (tinfoil-knight) [reply datafusion/sql/src/statement.rs:859]: I've opened an issue here: https://github.com/apache/datafusion/issues/10853

Making the value standardization logic customizable makes sense. Integrations should receive the original value and be able to decide what to do with it. 

I'll attempt a fix for the issue this weekend if it hasn't already been picked up by then.
