### PR TITLE
Validate partitions columns in `CREATE EXTERNAL TABLE` if table already exists.

### LINKED ISSUE #9785: [BUG] Panic when querying table with wrong partition columns order
### Describe the bug

Assume a table `test` that is partitioned on columns `a` then `b`, creating an external table and setting wrong order for the partition columns (`b` then `a`) doesn't raise an error, but querying it causes a panic.

### To Reproduce

copy these queries into panic.sql

```sql
CREATE EXTERNAL TABLE test(name string, year string, month string) PARTITIONED BY (year, month) STORED AS csv LOCATION 'tmp/';
INSERT INTO test VALUES('name', '2024', '03');

-- notice the different ordering in the PARTITIONED BY clause
CREATE EXTERNAL TABLE test2(name string, year string, month string) PARTITIONED BY (month, year) STORED AS csv LOCATION 'tmp/';
SELECT * FROM test2;
```

And run 
```console
$ datafusion-cli -f panic.sql
DataFusion CLI v36.0.0
0 rows in set. Query took 0.002 seconds.

+-------+
| count |
+-------+
| 1     |
+-------+
1 row in set. Query took 0.004 seconds.

0 rows in set. Query took 0.001 seconds.

thread 'main' panicked at /home/user/dev/arrow-datafusion/datafusion/core/src/datasource/physical_plan/file_scan_config.rs:261:54:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

Should never panic. Instead, return an error on table creation or at least on the queries after.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MohamedAbdeen21**
## Which issue does this PR close?

Closes #9785 .

## Rationale for this change

Prevent specifying wrong partitions when creating external tables that already exist on disk. This stops a whole suite of problems with other statements (check the issue for examples) that expect the table partitions to match the path partitions.

## What changes are included in this PR?

`CREATE EXTERNAL TABLE` now infers the partition columns provided in `LOCATION` and compares it with the columns provided in `PARTITIONED BY` clause. Partial partitions are allowed, and does nothing if path is empty.

## Are these changes tested?

Only through slt tests, no unit tests.

## Are there any user-facing changes?

Better errors and safeguards when dealing with partitioned external tables.

### CODE REVIEW

File: datafusion/core/src/datasource/listing/table.rs [hunk 1]
```diff
@@ -438,6 +439,111 @@ impl ListingOptions {
...
+                    table_partition_names
+                );
+            }
+        }
+
+        Ok(())
+    }
+
+    /// Infer the partitioning at the given path on the provided object store.
+    /// For performance reasons, it doesn't read all the files on disk
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/table.rs:501]: 💯

File: datafusion/core/src/datasource/listing/table.rs [hunk 2]
```diff
@@ -438,6 +439,111 @@ impl ListingOptions {
...
+                    .map(|s| s.split('=').take(1).collect())
+                    .collect_vec()
+            })
+            .collect_vec();
+
+        match partition_keys.into_iter().all_equal_value() {
+            Ok(v) => Ok(v),
+            Err(None) => Ok(vec![]),
+            Err(Some(diff)) => {
+                plan_err!("Found mixed partition values on disk {:?}", diff)
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/table.rs:543]: Can you please add test coverage for this error condition as well (like maybe it is looking for directories like `x=1` and `y=1`? Or maybe the other directory should be ignored if it is not the specified partitioning (aka maybe we shouldn't have this check)?

**Review by alamb — COMMENTED** [review]
Thank you @MohamedAbdeen21  -- this looks really nice and will be a better user experience.

I think there are a few more tests to write but otherwise this is looking quite good.

cc @devinjdangelo  and @metesynnada  FYI

File: datafusion/core/src/datasource/listing/table.rs (hunk 2 above)
Comment (MohamedAbdeen21) [reply datafusion/core/src/datasource/listing/table.rs:543]: That's a behavior we briefly discussed in the issue, I generally dislike the idea of having two identical tables under the same path but with different partitions, as it can lead to confusion.

I think the only case this error is triggered is either:

1. Partitions are manually created

2. Something like this

```sql
-- an empty/new directory
CREATE EXTERNAL TABLE test(name string) PARTITIONED BY (year string, month string) STORED AS parquet LOCATION 'tmp/';

-- passes the check since the previous create table doesn't write to disk
CREATE EXTERNAL TABLE test2(name string) PARTITIONED BY (month string, year string) STORED AS parquet LOCATION 'tmp/';

-- creates year -> month partitions
INSERT INTO test VALUES('name', '2024', '03');

-- now table have both partitions (year -> month and month -> year)
INSERT INTO test2 VALUES('name', '2024', '03');

-- fails to infer as partitions are not consistent
CREATE EXTERNAL TABLE test3(name string) PARTITIONED BY (month string, year string) STORED AS parquet LOCATION 'tmp/';
```

I can add the sql as a test, but I just found the query pattern very abnormal and unlikely to happen.

Comment (alamb) [reply datafusion/core/src/datasource/listing/table.rs:542]: I was thinking about it from the code coverage perspective -- specifically to make sure that all the code in the PR were covered with tests, so that if we broke the code accidentally in some future refactor we would know it was broken

Comment (alamb) [reply datafusion/core/src/datasource/listing/table.rs:542]: To be clear, I think we need to add test coverage or should remove the check

**Comment by alamb** [comment]
Marking this as a draft as I think we are just waiting on some more tests. @MohamedAbdeen21  please let me know if that was not correct or if you need some help finishing this PR up.

**Comment by MohamedAbdeen21** [comment]
Hi @alamb, I've implemented the check we discussed. Apart from adding unit tests for the two new functions, I believe the PR is now adequately covered.

I'm curious to see if anyone can come up with additional queries that should be tested.

**Review by alamb — APPROVED** [review]
Thank you so much @MohamedAbdeen21  -- this looks awesome

File: datafusion/core/src/datasource/listing/table.rs [hunk 3]
```diff
@@ -438,6 +439,112 @@ impl ListingOptions {
...
+        // no partitioned files found on disk
+        if inferred.is_empty() {
+            return Ok(());
+        }
+
+        let table_partition_names = self
+            .table_partition_cols
+            .iter()
+            .map(|(col_name, _)| col_name.clone())
+            .collect_vec();
```
Comment (Jefffrey) [inline datafusion/core/src/datasource/listing/table.rs:475]: nit: probably can avoid a collect here, since used for checking len (which can just use original `self.table_partition_cols`) and for iterating through, so could just iterate through directly where needed

File: datafusion/core/src/datasource/listing/table.rs [hunk 4]
```diff
@@ -438,6 +439,112 @@ impl ListingOptions {
...
+        });
+
+        let partition_keys = stripped_path_parts
+            .map(|path_parts| {
+                path_parts
+                    .into_iter()
+                    .rev()
+                    .skip(1) // get parents only; skip the file itself
+                    .rev()
+                    .map(|s| s.split('=').take(1).collect())
```
Comment (Jefffrey) [inline datafusion/core/src/datasource/listing/table.rs:533]: Is the partition column name containing a `=` a cheeky edge case we need to consider here?

**Comment by alamb** [comment]
Thanks for the review @Jefffrey  -- @MohamedAbdeen21  let me know if you would like to address @Jefffrey 's comments i this PR or a follow on one.

File: datafusion/core/src/datasource/listing/table.rs (hunk 3 above)
Comment (MohamedAbdeen21) [reply datafusion/core/src/datasource/listing/table.rs:475]: Makes sense, but then we'll have to iterate on a clone because it's used in the error message. I prefer having the collect over the clone.

File: datafusion/core/src/datasource/listing/table.rs (hunk 4 above)
Comment (MohamedAbdeen21) [reply datafusion/core/src/datasource/listing/table.rs:533]: We do need to consider this. Now that you mention it, I realize that I never actually thought about how these column names are written to disk. I'll have to take a look on how other systems do it before suggesting anything.

After looking at the linked issue, I think this should be addressed in a follow-up since it may requiring changing other parts of DF first.

**Comment by MohamedAbdeen21** [comment]
I'm not 100% sure.

I've never thought about the cases mentioned in #9269 before to be honest, so I'm not sure what the best approach is.

**Comment by Jefffrey** [comment]
> I'm not 100% sure.
> 
> I've never thought about the cases mentioned in #9269 before to be honest. Maybe do follow-ups since it looks like we may need other changes around sqlparser and DF first.

Yes this sounds good :+1:

**Review by Jefffrey — APPROVED** [review]
