### PR TITLE
Maintain time zone in `ScalarValue::new_list`

### LINKED ISSUE #7900: ScalarValue::new_list loses timestamp timezone info
### Describe the bug

ScalarValue::new_list loses timestamp timezone info

### To Reproduce

_No response_

### Expected behavior

Keep timezone during creation of list

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Dandandan**
## Which issue does this PR close?

Closes #7900

## Rationale for this change

This causes some bugs in Coralogix for `count distinct` (I couldn't reproduce with sql e2e tests in DataFusion)

### CODE REVIEW

**Review by Weijun-H — APPROVED** [review]

**Review by jayzhan211 — APPROVED** [review]
LGTM!

File: datafusion/common/src/scalar.rs [hunk 1]
```diff
@@ -5185,6 +5190,25 @@ mod tests {
         assert_eq!(1, arr.len());
     }
 
+    #[test]
+    fn test_newlist_timestamp_zone() {
+        let s: &'static str = "UTC";
+        let values = vec![ScalarValue::TimestampMillisecond(Some(1), Some(s.into()))];
+        let arr = ScalarValue::new_list(
+            &values,
```
Comment (crepererum) [inline datafusion/common/src/scalar.rs:5198]: Does this fail if the timezone provided by one of the values is different than the one provided by the datatype argument?

Comment (Dandandan) [reply datafusion/common/src/scalar.rs:5198]: Yes, the test fails (and test as is fails on master).

**Review by crepererum — APPROVED** [review]
