### PR TITLE
Fix issue in filter pushdown with overloaded projection index

### LINKED ISSUE #4282: Some valid filters are not pushed down to parquet scan
**Describe the bug**

Certain filter predicates cause an error when building the parquet predicate so the predicate does not get pushed down to the parquet scan. Since the pushdown is currently inexact, the results are still correct but we can potentially lose the performance benefit of pushing the filter down to the scan

**To Reproduce**

Add a filter predicate that uses the same column expression more than once in a single predicate, for example `SELECT * FROM table WHERE a = 1 OR a = 2`

**Expected behavior**

The predicate `a = 1 OR a = 2` should be pushed down to the parquet scan. 

**Additional context**

### PR DESCRIPTION
**Pull request by thinkharderdev**
# Which issue does this PR close?

Closes #4282 

# Rationale for this change

Currently parquet filter pushdown fails when we have predicate that uses the same column expression more than once (eg `a = 1 OR a = 2`). Since we silently ignore these failure the query results are still correct due to inexact pushdown but we do not actually push the filter down to the scan. 

# What changes are included in this PR?

When building the `FilterCandidate` make sure we only track unique projections for each expr. 

# Are these changes tested?

Yes

# Are there any user-facing changes?

No

No

### CODE REVIEW

File: datafusion/core/src/physical_plan/file_format/parquet/row_filter.rs [hunk 1]
```diff
@@ -219,7 +219,9 @@ impl<'a> ExprRewriter for FilterCandidateBuilder<'a> {
     fn pre_visit(&mut self, expr: &Expr) -> Result<RewriteRecursion> {
         if let Expr::Column(column) = expr {
             if let Ok(idx) = self.file_schema.index_of(&column.name) {
-                self.required_column_indices.push(idx);
+                if !self.required_column_indices.contains(&idx) {
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet/row_filter.rs:222]: 🤔  maybe using a Set for the indices would make the intent clearer (and ensure a duplicated column doesn't sneak back in). I don't think it is a huge deal however.

**Review by alamb — APPROVED** [review]
Thanks @thinkharderdev
