### PR TITLE
Deprecate make_scalar_function

### LINKED ISSUE #8866: UDFs marked as volatile do not appear to evaluate multiple times for each output row.
### Describe the bug

It seems a UDF with no arguments are only called once, even if signature is defined with `Volatility::Volatile` and also queried in the context of a table with multiple rows.

By this I mean, for example: `select random_udf() from many_rows_table`

There is a minimal repro here https://github.com/dadepo/df-repro

When ran, the output could be:

```
+-------+------+-----+-------+
| index | uint | int | float |
+-------+------+-----+-------+
| 1     | 2    | -2  | 1.0   |
| 2     | 3    | 3   | 3.3   |
| 3     |      |     |       |
+-------+------+-----+-------+
+---------------+
| random_normal |
+---------------+
| 25.0          |
| 25.0          |
| 25.0          |
+---------------+
```

In the run above, the `25.0` is the result of the udf and it is repeated.

### To Reproduce

A minimal reproduction can be found here https://github.com/dadepo/df-repro

### Expected behavior

The UDF to be evaluated per each row output.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #8866.

## Rationale for this change

`make_scalar_function` is easily to be misused and causing unexpected behavior (e.g., #8866) if users don't understand its underlying logic. Actually this function looks more like a crate private utility function we should not expose.

### CODE REVIEW

File: datafusion/physical-expr/src/functions.rs [hunk 1]
```diff
@@ -191,9 +191,11 @@ pub(crate) enum Hint {
     AcceptsSingular,
 }
 
-/// decorates a function to handle [`ScalarValue`]s by converting them to arrays before calling the function
+/// Decorates a function to handle [`ScalarValue`]s by converting them to arrays before calling the function
 /// and vice-versa after evaluation.
-pub fn make_scalar_function<F>(inner: F) -> ScalarFunctionImplementation
+/// Note that this function makes a scalar function with no arguments or all scalar inputs return a scalar.
+/// That's said its output will be same for all input rows in a batch.
+pub(crate) fn make_scalar_function<F>(inner: F) -> ScalarFunctionImplementation
```
Comment (viirya) [inline datafusion/physical-expr/src/functions.rs:198]: Except for the usage in same crate, its other usages are in tests.

Comment (viirya) [inline datafusion/physical-expr/src/functions.rs:198]: Or we should deprecate it.

Comment (jackwener) [reply datafusion/physical-expr/src/functions.rs:198]: I think it's a `behavior change`, so I add a label for it

**Review by jackwener — DISMISSED** [review]
Make sense to me, thanks @viirya

File: datafusion/physical-expr/src/functions.rs (hunk 1 above)
Comment (alamb) [reply datafusion/physical-expr/src/functions.rs:198]: For better or worse, since this function is in the `example_udf.rs` file, I think it is likely to be widely used when people followed the example model.

Thus I think this change is likely to be disruptive to exising users.

To help soften the blow, I agree that deprecating it for a release or two would be the best

Perhaps we could do something like

```suggestion
#[deprecated(since = "35.0.0", note = "Implement your function directly in terms of ColumnarValue or use `ScalarUDF` instead")]
pub fn make_scalar_function<F>(inner: F) -> ScalarFunctionImplementation
  make_scaler_function_inner(inner)
}

/// Internal implementation, see comments on `make_scalar_function` for caveats
pub(crate) fn make_scalar_function_inner<F>(inner: F) -> ScalarFunctionImplementation 

```

File: datafusion/proto/tests/cases/roundtrip_logical_plan.rs [hunk 2]
```diff
@@ -1592,9 +1591,12 @@ fn roundtrip_aggregate_udf() {
...
 #[test]
 fn roundtrip_scalar_udf() {
-    let fn_impl = |args: &[ArrayRef]| Ok(Arc::new(args[0].clone()) as ArrayRef);
-
-    let scalar_fn = make_scalar_function(fn_impl);
+    let scalar_fn = Arc::new(|args: &[ColumnarValue]| {
+        let ColumnarValue::Array(array) = &args[0] else {
+            panic!()
+        };
+        Ok(ColumnarValue::Array(Arc::new(array.clone()) as ArrayRef))
```
Comment (alamb) [inline datafusion/proto/tests/cases/roundtrip_logical_plan.rs:1598]: I wonder if we could make this code easier to work with using `From` impls, like

```suggestion
        Ok(ColumnarValue::from(Arc::new(array.clone()) as ArrayRef))
```

Maybe it doesn't matter 🤔

File: datafusion-examples/examples/simple_udf.rs [hunk 3]
```diff
@@ -61,17 +62,24 @@ async fn main() -> Result<()> {
...
-    let pow = |args: &[ArrayRef]| {
+    let pow = Arc::new(|args: &[ColumnarValue]| {
         // in DataFusion, all `args` and output are dynamically-typed arrays, which means that we need to:
         // 1. cast the values to the type we want
         // 2. perform the computation for every element in the array (using a loop or SIMD) and construct the result
 
         // this is guaranteed by DataFusion based on the function's signature.
         assert_eq!(args.len(), 2);
 
+        let ColumnarValue::Array(arg0) = &args[0] else {
```
Comment (alamb) [inline datafusion-examples/examples/simple_udf.rs:73]: I think the more correct pattern is to create an array with [`into_array`](https://docs.rs/datafusion/latest/datafusion/physical_plan/enum.ColumnarValue.html#method.into_array) 

```suggestion
        let arg0 = args[0].into_array(num_rows)
```

Though now I wrote that it is not super clear to me where the num_rows should come from 🤔 

Also, maybe this is more of the fix for https://github.com/apache/arrow-datafusion/issues/8866 -- that for a volatile function, it shouldn't be passed a scalar but unstead the array should be expanded prior to invocation

**Review by alamb — COMMENTED** [review]
Thanks @viirya  -- I now understand the issue in https://github.com/apache/arrow-datafusion/issues/8866 better.

I think `make_scalar_function` is quite a nice function that lowered the cognative barrier to making udfs and it would be great if we could keep it. I think @jorgecarleitao or @andygrove  originally added it when we introduced `ColumnarValue` so that new users didn't have to understand ColumnarValue to begin working on it. 

That being said, perhaps encouraging people to use the trait `ScalarUDFImpl` is ok,

File: datafusion-examples/examples/simple_udf.rs (hunk 3 above)
Comment (jackwener) [reply datafusion-examples/examples/simple_udf.rs:73]: In what situations would 'arg' be a Scalar? If we can provide an example to reproduce it, our case/test can cover more condition?

Comment (alamb) [reply datafusion-examples/examples/simple_udf.rs:73]: I think something like `pow(1.0, 2.0)` (pass in literal values)

File: datafusion/proto/tests/cases/roundtrip_logical_plan.rs (hunk 2 above)
Comment (viirya) [reply datafusion/proto/tests/cases/roundtrip_logical_plan.rs:1598]: Okay, I added two `From` impls for `ColumnarValue`.

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 4]
```diff
@@ -1438,9 +1436,31 @@ mod tests {
         let input_types = vec![DataType::Int32, DataType::Int32];
         let return_type = Arc::new(DataType::Int32);
 
-        let fun = |args: &[ArrayRef]| {
-            let arg0 = as_int32_array(&args[0])?;
-            let arg1 = as_int32_array(&args[1])?;
+        let fun = Arc::new(|args: &[ColumnarValue]| {
+            let len = args
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1440]: Maybe as a follow on PR we can make a function that does this length inference and conversion to array (mostly so it can be documented) to make the ideas easier to find 🤔

**Review by alamb — APPROVED** [review]
Thanks @viirya  --- I think it would be nice to avoid some of the repetition of converting `[ColumnarValue]` into `[ArrayRef]` by encapsulating it into a function but I also think we can do so as a follow on PR.

I also think we might want to consieer wait for DataFusion 35.0.0 to be released  #8863 before merging this PR

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 4 above)
Comment (viirya) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1440]: Yea, have the same thought too. It will be still useful for `ScalarUDFImpl` as `invoke` takes `args: &[ColumnarValue]` and users might need length inference too.

**Comment by viirya** [comment]
> I also think we might want to consieer wait for DataFusion 35.0.0 to be released https://github.com/apache/arrow-datafusion/issues/8863 before merging this PR

Thanks @alamb. This currently marks `make_scalar_function` as deprecated since 35.0.0 (`#[deprecated(since = "35.0.0"`...), if we want to merge this after DataFusion 35.0.0 releases, should we change the deprecation message to `since = "36.0.0")?

**Comment by alamb** [comment]
I am going to merge this PR on the assumption that the `35.0.0` release is in the final stages of voting and we won't need a new RC. 

Thanks again @viirya

**Comment by alamb** [comment]
I took the liberty of merging up from `main` just to ensure there are no logical conflicts and plan to merge this PR when the CI checks pass

**Comment by viirya** [comment]
Thank you @alamb @jackwener

**Comment by viirya** [comment]
Thanks. I will update the document together in a follow up with other stuffs (https://github.com/apache/arrow-datafusion/pull/8878#discussion_r1456452737).
