### PR TITLE
revert accidently deleted size code in count_distinct

### LINKED ISSUE #5534: Revert accidently deleted size code in count_distinct
**Describe the bug**

The `.size` logic was accidently corrupted during https://github.com/apache/arrow-datafusion/pull/5408
Need to rollback the code to prev behaviuor

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by comphead**
# Which issue does this PR close?

Closes #5534.

# Rationale for this change

The `.size` was accidently corrupted during #5408
# What changes are included in this PR?
Put the size logic back

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-expr/src/aggregate/count_distinct.rs [hunk 1]
```diff
@@ -172,7 +185,11 @@ impl Accumulator for DistinctCountAccumulator {
     }
 
     fn size(&self) -> usize {
-        self.fixed_size()
+        match &self.state_data_type {
```
Comment (alamb) [inline datafusion/physical-expr/src/aggregate/count_distinct.rs:188]: 👍 thank you @comphead

**Comment by alamb** [comment]
I plan to merge this PR as soon as the CI checks have passed, as I would like to ensure it makes it into the release if possible

**Comment by alamb** [comment]
The clippy CI check https://github.com/apache/arrow-datafusion/actions/runs/4376721582/jobs/7659390110 was failing due to clippy being updated. 

I merged up from main (to get  @jackwener 's https://github.com/apache/arrow-datafusion/pull/5532 ❤️ ) and pushed to your branch
