### PR TITLE
Handle merged schemas in parquet pruning

### LINKED ISSUE #2161: Query execution fails with index out of bounds err
**Describe the bug**
Simply I get index out of bounds when parquet pruning is enabled.

file: metadata.rs:212:10
struct: RowGroupMetaData, 
accessed field: columns
error: thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 1 but the index is 1'

**To Reproduce**
Create two parquet files with different fields in schema, I put 4 numbers into each file.

```
file: sample1.parquet
message schema {
    REQUIRED INT32 a;
}

file: sample2.parquet
message schema {
    REQUIRED INT32 b;
}
```

code:
```
#[tokio::main]
async fn main() -> Result<()> {
    // create local execution context
    let mut ctx = ExecutionContext::new();

    // Configure listing options
    let file_format = ParquetFormat::default().with_enable_pruning(true);
    let listing_options = ListingOptions {
        file_extension: DEFAULT_PARQUET_EXTENSION.to_owned(),
        format: Arc::new(file_format),
        table_partition_cols: vec![],
        collect_stat: false,
        target_partitions: 1,
    };

    ctx.register_listing_table(
        "FANCY_TABLE",
        "file:///absolute-path/table/",
        listing_options,
        None,
    ).await.unwrap();

    let df = ctx
        .sql("SELECT * FROM FANCY_TABLE where a > 2 or b > 2")
        .await?;

    df.show().await?;

    Ok(())
}
```

**Expected behavior**
Query executes without any issues.

When pruning is disabled, everything is fine and I receive such result.
```
+---+---+
| a | b |
+---+---+
|   | 3 |
|   | 4 |
| 3 |   |
| 4 |   |
+---+---+
```

### PR DESCRIPTION
**Pull request by thinkharderdev**
# Which issue does this PR close?

Closes #2161 

 # Rationale for this change

Adding schema merging to `ParquetFormat` broke pruning since the existing implementation assumes that each file in the `ListingTable` has the merged schema. In the best case this just prevents pruning row groups, but in certain cases (such as #2161) it can cause runtime errors and possibly incorrect query results. 

# What changes are included in this PR?

Two changes:

1. When gathering column statistics during pruning, we need to find row group columns by name instead of the index in the merged schema.  2. 
2. When collecting statistics during a `ListingTable` scan, we need to map file-level statistics to the expected schema of the tables merged schema.

# Are there any user-facing changes?

No

Yes, in order to map the statistics to the merged schema, we need to pass the merged schema to `FileFormat::infer_stats`.

### CODE REVIEW

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 1]
```diff
@@ -379,8 +379,10 @@ macro_rules! get_min_max_values {
         let null_scalar: ScalarValue = data_type.try_into().ok()?;
 
         $self.row_group_metadata
-            .column(column_index)
-            .statistics()
+            .columns()
+            .iter()
+            .find(|c| c.column_descr().name() == &$column.name)
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:384]: 👍

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 2]
```diff
@@ -878,6 +880,39 @@ mod tests {
...
+            Arc::new(StringArray::from(vec![Some("Foo"), None, Some("bar")]));
+
+        let c2: ArrayRef = Arc::new(Int64Array::from(vec![Some(1), Some(2), None]));
+
+        let c3: ArrayRef = Arc::new(Int8Array::from(vec![Some(10), Some(20), None]));
+
+        // batch1: c1(string), c2(int64), c3(int8)
+        let batch1 = create_batch(vec![("c1", c1), ("c3", c3.clone())]);
+
+        // batch2: c3(int8), c2(int64), c1(string)
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:895]:
```suggestion
        // batch2: c3(int8), c2(int64)
```

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 3]
```diff
@@ -878,6 +880,39 @@ mod tests {
...
+    #[tokio::test]
+    async fn evolved_schema_intersection_filter() {
+        let c1: ArrayRef =
+            Arc::new(StringArray::from(vec![Some("Foo"), None, Some("bar")]));
+
+        let c2: ArrayRef = Arc::new(Int64Array::from(vec![Some(1), Some(2), None]));
+
+        let c3: ArrayRef = Arc::new(Int8Array::from(vec![Some(10), Some(20), None]));
+
+        // batch1: c1(string), c2(int64), c3(int8)
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:892]:
```suggestion
        // batch1: c1(string), c3(int8)
```

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 4]
```diff
@@ -878,6 +880,39 @@ mod tests {
...
+
+        let filter = col("c2").eq(lit(0_i64));
+
+        // read/write them files:
+        let read = round_trip_to_parquet(vec![batch1, batch2], None, None, Some(filter))
+            .await
+            .unwrap();
+        let expected = vec![
+            "+-----+----+----+",
+            "| c1  | c3 | c2 |",
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:906]: 🤔  if the filter is `c2 = 0` then none of these rows should pass.... so something doesn't look quite right

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 5]
```diff
@@ -919,6 +955,70 @@ mod tests {
...
+    #[tokio::test]
+    async fn evolved_schema_disjoint_schema_filter() {
+        let c1: ArrayRef =
+            Arc::new(StringArray::from(vec![Some("Foo"), None, Some("bar")]));
+
+        let c2: ArrayRef = Arc::new(Int64Array::from(vec![Some(1), Some(2), None]));
+
+        // let c3: ArrayRef = Arc::new(Int8Array::from(vec![Some(10), Some(20), None]));
+
+        // batch1: c1(string), c2(int64), c3(int8)
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:997]:
```suggestion
        // batch1: c1(string)
```

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 6]
```diff
@@ -919,6 +955,70 @@ mod tests {
...
+        let batch1 = create_batch(vec![("c1", c1.clone())]);
+
+        // batch2: c3(int8), c2(int64), c1(string)
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:1000]:
```suggestion
        // batch2: c2(int64)
```

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 7]
```diff
@@ -919,6 +955,70 @@ mod tests {
...
+
+        let filter = col("c2").eq(lit(0_i64));
+
+        // read/write them files:
+        let read = round_trip_to_parquet(vec![batch1, batch2], None, None, Some(filter))
+            .await
+            .unwrap();
+
+        let expected = vec![
+            "+-----+----+",
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:1011]: same thing here -- I wouldn't expect `null` values in `c2` to be returned...

**Review by alamb — COMMENTED** [review]
Thank you @thinkharderdev  - I think this looks quite good.

The only thing I am not sure about is some rows that appear to show `null` passing a `c2 = 0` filter. Otherwise good to go from my perspective

**Comment by alamb** [comment]
FYI @Cheappie

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 4 above)
Comment (thinkharderdev) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:906]: Yeah, this looked wrong to me as well. What I think is happening is that the min/max aren't set the pruning predicates aren't applied. In a "real" query where this predicate was pushed down from a filter stage this would still get piped into a `FilerExec`. I think we would have to special case the scenario where we fill in a null column to conform to a merged schema which may be worth doing. I can double check though and make sure there's not a bug here.

Comment (alamb) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:906]: Makes sense -- a  comment in the test to explain why it is ok would be helpful for future readers

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks agian @thinkharderdev

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 8]
```diff
@@ -1005,6 +1005,11 @@ mod tests {
             .await
             .unwrap();
 
+        // This does not look correct since the "c2" values in the result do not in fact match the predicate `c2 == 0`
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:1008]: 👍

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 9]
```diff
@@ -919,6 +955,73 @@ mod tests {
...
+        // Predicate should prune all row groups
+        assert_eq!(read.len(), 0);
+    }
+
+    #[tokio::test]
+    async fn evolved_schema_disjoint_schema_filter() {
+        let c1: ArrayRef =
+            Arc::new(StringArray::from(vec![Some("Foo"), None, Some("bar")]));
+
+        let c2: ArrayRef = Arc::new(Int64Array::from(vec![Some(1), Some(2), None]));
```
Comment (Cheappie) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:993]: I might miss some point, but why values in c2 are not materialized if we weren't able to _prune_ them ? I wonder how filter like `c2 eq 1_i64` can be satisfied against null array ?

```
            "+-----+----+",
            "| c1  | c2 |",
            "+-----+----+",
            "| Foo |    |",
            "|     |    |",
            "| bar |    |",
            "+-----+----+",
```

Comment (alamb) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:993]: I think the key point is that filtering is *also* applied after the initial parquet scan / pruning -- the pruning is just a first pass to try and reduce additional work.

So subsequent `Filter` operations will actually handle filtering out the columns with `c2 = null`
