### PR TITLE
fix: remove wrong comment about `having`

### LINKED ISSUE #4554: wrong comment about having
**Describe the bug**
having must work on output of groupby.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #4554 .

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]

File: datafusion/sql/src/planner.rs [hunk 1]
```diff
@@ -1151,12 +1151,10 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
                 //
                 // For example:
                 //
-                //   SELECT c1 AS m FROM t HAVING m > 10;
```
Comment (liukun4515) [inline datafusion/sql/src/planner.rs:1154]: is there any bug for the implementation?

Comment (jackwener) [reply datafusion/sql/src/planner.rs:1154]: currently this sql can't work

Comment (alamb) [reply datafusion/sql/src/planner.rs:1154]: Postgres agrees:

```sql
postgres=# create table t (c1 int);
CREATE TABLE
postgres=# insert into t  values (1), (2);
INSERT 0 2
postgres=# SELECT c1 AS m FROM t HAVING m > 10;
ERROR:  column "m" does not exist
LINE 1: SELECT c1 AS m FROM t HAVING m > 10;
                                     ^
postgres=# 
```

**Review by alamb — APPROVED** [review]
