### PR TITLE
fix: issue #9130 substitute redundant columns when doing cross join

### LINKED ISSUE #9130: Projections require unique expression names error
### Describe the bug

Datafusion failed to execute `select * from (t1 cross join t2) as t cross join t3` with error message
```
Error during planning: Projections require unique expression names but the expression "t.a" at position 0 and "t.a" at position 2 have the same name. Consider aliasing ("AS") one of them.
```
I tested on sqlite3 and it return expected result.
latest commit: 840499fbd3c25bf82a6ee0641ef6888079e096da

### To Reproduce

create table t1 (a int, b int);
create table t2 (a int, b int);
create table t3 (a int, b int);
insert into t1 values (1, 2);
insert into t2 values (3, 4);
insert into t3 values (5, 6);
select * from (t1 cross join t2) as t cross join t3;

### Expected behavior

Return result like sqlite3
```
1|2|3|4|5|6
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Lordworms**
## Which issue does this PR close?

Closes #9130 

## Rationale for this change
In cross-join, Since we have to validate the uniqueness of the name, we would throw an error when failed to do it. as what sqlite did, they just substituted the name of the redundant column(supposed to be a) into a:1, and we followed the strategy.

### CODE REVIEW

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -1360,6 +1385,7 @@ pub fn project(
     let mut projected_expr = vec![];
     for e in expr {
         let e = e.into();
+        //println!("cur_expression is {:?}", e);
```
Comment (jackwener) [inline datafusion/expr/src/logical_plan/builder.rs:1388]:
```suggestion
```

File: datafusion/expr/src/logical_plan/builder.rs [hunk 2]
```diff
@@ -1124,7 +1124,28 @@ impl LogicalPlanBuilder {
...
+                let cur_cnt = &name_map.get(field.name());
+                let name = field.name().to_string() + ":" + &cur_cnt.unwrap().to_string();
+                name_map.insert(field.name().to_string(), cur_cnt.unwrap() + 1);
+                DFField::new(
+                    field.qualifier().cloned(),
+                    &name,
+                    field.data_type().clone(),
+                    field.is_nullable(),
+                )
+            }
```
Comment (jackwener) [inline datafusion/expr/src/logical_plan/builder.rs:1145]:
```suggestion
            let counter = name_map.entry(field.name().to_string()).or_insert(0);
            *counter += 1;
            if *counter > 1 {
                let new_name = format!("{}:{}", field.name(), counter);
                DFField::new(
                    field.qualifier().cloned(),
                    &new_name,
                    field.data_type().clone(),
                    field.is_nullable(),
                )
            } else {
                field
            }
```

File: datafusion/expr/src/logical_plan/builder.rs (hunk 1 above)
Comment (Lordworms) [reply datafusion/expr/src/logical_plan/builder.rs:1388]: got it

File: datafusion/expr/src/logical_plan/builder.rs [hunk 3]
```diff
@@ -1184,13 +1204,15 @@ pub fn build_join_schema(
...
     };
+    //println!("total fields is {:?}", fields);
     let func_dependencies = left.functional_dependencies().join(
         right.functional_dependencies(),
         join_type,
         left_fields.len(),
     );
     let mut metadata = left.metadata().clone();
     metadata.extend(right.metadata().clone());
+    // let schema = DFSchema::new_with_metadata(change_redundant_column(fields), metadata)?;
```
Comment (jackwener) [inline datafusion/expr/src/logical_plan/builder.rs:1215]:
```suggestion
```

File: datafusion/core/src/datasource/memory.rs [hunk 4]
```diff
@@ -65,6 +65,10 @@ impl MemTable {
     pub fn try_new(schema: SchemaRef, partitions: Vec<Vec<RecordBatch>>) -> Result<Self> {
         for batches in partitions.iter().flatten() {
             let batches_schema = batches.schema();
+            println!(
+                "the new schema is {:?}, schema set is {:?}",
+                batches_schema, schema
+            );
```
Comment (jackwener) [inline datafusion/core/src/datasource/memory.rs:71]:
```suggestion
```

File: datafusion/expr/src/logical_plan/builder.rs [hunk 5]
```diff
@@ -1184,13 +1204,15 @@ pub fn build_join_schema(
             right_fields.clone()
         }
     };
+    //println!("total fields is {:?}", fields);
```
Comment (jackwener) [inline datafusion/expr/src/logical_plan/builder.rs:1207]:
```suggestion
```

File: datafusion/expr/src/logical_plan/builder.rs [hunk 6]
```diff
@@ -1245,6 +1268,7 @@ pub(crate) fn validate_unique_names<'a>(
                 Ok(())
             },
             Some((existing_position, existing_expr)) => {
+                //println!("node_name is {}, existing expr is {:?}", node_name, existing_expr);
```
Comment (jackwener) [inline datafusion/expr/src/logical_plan/builder.rs:1271]:
```suggestion
```

File: datafusion/sqllogictest/test_files/same_column_name_cross_join.slt [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+
+# Unless required by applicable law or agreed to in writing,
+# software distributed under the License is distributed on an
+# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+# KIND, either express or implied.  See the License for the
+# specific language governing permissions and limitations
+# under the License.
+
+
+# prepare the tables
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/same_column_name_cross_join.slt:19]: I ran this test without the code in this PR and it fails like this, so I think the test covers the changes in the PR

```
External error: query failed: DataFusion error: Error during planning: Projections require unique expression names but the expression "t.a" at position 0 and "t.a" at position 2 have the same name. Consider aliasing ("AS") one of them.
[SQL] select * from (t1 cross join t2) as t cross join t3;
-------
at test_files/./join.slt:733
at test_files/join_disable_repartition_joins.slt:26

Error: Execution("1 failures")
error: test failed, to rerun pass `-p datafusion-sqllogictest --test sqllogictests`

Caused by:
  process didn't exit successfully: `/Users/andrewlamb/Software/arrow-datafusion/target/debug/deps/sqllogictests-6e501f6e871dacfc joins` (exit status: 1)
```

File: datafusion/expr/src/logical_plan/builder.rs [hunk 8]
```diff
@@ -1124,7 +1124,27 @@ impl LogicalPlanBuilder {
...
-
+pub fn change_redundant_column(fields: Vec<DFField>) -> Vec<DFField> {
+    let mut name_map = HashMap::new();
+    fields
+        .into_iter()
+        .map(|field| {
+            let counter = name_map.entry(field.name().to_string()).or_insert(0);
+            *counter += 1;
+            if *counter > 1 {
+                let new_name = format!("{}:{}", field.name(), *counter - 1);
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/builder.rs:1135]: This effectively renames some of the columns to something else (like `a:1`) I think

How do we:
1. know that name is unique? (couldn't there be another table in the query that has a column named `a:1`?
2. know we should resolve the namespace conflict with the first column with the name?

File: datafusion/expr/src/logical_plan/builder.rs [hunk 9]
```diff
@@ -2076,4 +2098,25 @@ mod tests {
 
         Ok(())
     }
+    #[test]
+    fn test_change_redundant_column() -> Result<()> {
+        let t1_field_1 = DFField::new_unqualified("a", DataType::Int32, false);
+        let t2_field_1 = DFField::new_unqualified("a", DataType::Int32, false);
+        let t1_field_2 = DFField::new_unqualified("b", DataType::Int32, false);
+        let t2_field_2 = DFField::new_unqualified("b", DataType::Int32, false);
+
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/builder.rs:2107]: Would it be possible to add one more field named "a" here (to show a counter other than `:1`)?

**Review by alamb — APPROVED** [review]
Thank you @Lordworms  for this contribution and I apologize for the delay in review

@jackwener  any final thoughts on this PR? From my perspective it is ready to go.

I double checked with `sqlite` and indeed it does appear to append `:1` to such column names 🤯 


```sql
sqlite> create table t1 (a int, b int);
sqlite> create table t2 (a int, b int);
sqlite> create table t3 (a int, b int);
sqlite> insert into t1 values (1, 2);
sqlite> insert into t2 values (3, 4);
sqlite> insert into t3 values (5, 6);
sqlite> select * from (t1 cross join t2) as t cross join t3;
1|2|3|4|5|6
sqlite> .header on
sqlite> select * from (t1 cross join t2) as t cross join t3;
a|b|a:1|b:1|a|b
1|2|3|4|5|6
sqlite>

```

cc @lewiszlw as you filed the issue

File: datafusion/expr/src/logical_plan/plan.rs [hunk 10]
```diff
@@ -1891,7 +1892,11 @@ impl SubqueryAlias {
         alias: impl Into<OwnedTableReference>,
     ) -> Result<Self> {
         let alias = alias.into();
-        let schema: Schema = plan.schema().as_ref().clone().into();
+        let fields = change_redundant_column(plan.schema().fields().clone());
+        let meta_data = plan.schema().as_ref().metadata().clone();
+        let schema: Schema = DFSchema::new_with_metadata(fields, meta_data)
+            .unwrap()
+            .into();
```
Comment (jackwener) [inline datafusion/expr/src/logical_plan/plan.rs:1899]: `new_with_metadata(fields, meta_data)?` to avoid `.unwrap()`

File: datafusion/expr/src/logical_plan/builder.rs [hunk 11]
```diff
@@ -2076,4 +2098,27 @@ mod tests {
...
+        let remove_redundant = change_redundant_column(field_vec);
+
+        assert_eq!(
+            remove_redundant,
+            vec![
+                DFField::new_unqualified("a", DataType::Int32, false),
+                DFField::new_unqualified("a:1", DataType::Int32, false),
+                DFField::new_unqualified("b", DataType::Int32, false),
+                DFField::new_unqualified("b:1", DataType::Int32, false),
+                DFField::new_unqualified("a:2", DataType::Int32, false),
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/builder.rs:2119]: 👍

**Review by alamb — APPROVED** [review]
Thanks again @Lordworms
