### PR TITLE
fix 592, support alias in window functions

### LINKED ISSUE #592: fix an issue where aliases are not respected in generating downstream schemas in window expr
> looks like integration test is failing due to mismatch between logical schema and physical schema for window queries, i will dig into this.

thanks, it might be because of some edge cases that i did miss. i didn't find time to fix it but so far this query will fail:

```sql
> select max(c1) over () max_c1, max(c1) over (partition by c2) max_c1_by_c2 from test;
Plan("Schema contains duplicate unqualified field name 'MAX(c1)'")
```

_Originally posted by @Jimexist in https://github.com/apache/arrow-datafusion/pull/55#issuecomment-864556916_

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #592 

 # Rationale for this change

turns out there's no need to rebase any `expr`s, removing the rebase would resolve the issue

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/src/sql/planner.rs [hunk 1]
```diff
@@ -2826,6 +2818,16 @@ mod tests {
         quick_test(sql, expected);
     }
 
+    #[test]
+    fn empty_over_dup_with_alias() {
+        let sql = "SELECT order_id oid, MAX(order_id) OVER () max_oid, MAX(order_id) OVER () max_oid_dup from orders";
+        let expected = "\
+        Projection: #orders.order_id AS oid, #MAX(orders.order_id) AS max_oid, #MAX(orders.order_id) AS max_oid_dup\
+        \n  WindowAggr: windowExpr=[[MAX(#orders.order_id)]]\
```
Comment (alamb) [inline datafusion/src/sql/planner.rs:2826]: this is pretty cool that the planner has identified the redundancy and only computes `MAX` once 👍

**Review by alamb — APPROVED** [review]

File: datafusion/src/sql/planner.rs (hunk 1 above)
Comment (houqp) [reply datafusion/src/sql/planner.rs:2826]: not only the planner, the builder also does this for those who use the dataframe apis directly ;)

**Review by houqp — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @Jimexist
