### PR TITLE
fix: not do boolean folding on NULL and/or expr

### LINKED ISSUE #1244: Should not fold a non-constant expression when it is not clear to do so
**Describe the bug**
This expression `col < 10 and boolean(NULL)` can either be NULL or false depending on the result of `col < 10`. Hence it should not be rewritten to a constant but it is current can.

**To Reproduce**
Add the following test in [optimize_expr_bool_and](https://github.com/apache/arrow-datafusion/blob/8f1d533f16e50c309163d2ef7121e2201c80176c/datafusion/src/optimizer/constant_folding.rs#L968), you will see it was rewritten to `c1 BETWEEN Int32(0) AND Int32(10)` which is wrong.

 ```
       // c1 BETWEEN Int32(0) AND Int32(10) AND Boolean(NULL)
       // it can be either NULL or false depending on the value of `c1 BETWEEN Int32(0) AND Int32(10`
        let expr = Expr::Between{ expr: Box::new(col("c1")), negated: false, low: Box::new(lit(0)), high: Box::new(lit(10))};
        let expr = expr.and(Expr::Literal(ScalarValue::Boolean(None)));
        let result = expr.clone().rewrite(&mut rewriter)?;
        println!("expr: {:#?} \n result: {:#?}", expr, result);
        assert_eq!(expr, result);
```

**Expected behavior**
Do not rewritten expression that does not have deterministic result yet

### PR DESCRIPTION
**Pull request by NGA-TRAN**
# Which issue does this PR close?
Closes #1244 

 # Rationale for this change
Do not fold `Boolean(NULL) and/or expr` because it depends on the value of the `expr`

# What changes are included in this PR?
`Boolean(NULL) and/or expr` is key as-is (aka not rewrite)

# Are there any user-facing changes?
This bug was hit by [IOx's storage_api::test](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/12405/workflows/59a98d12-d79b-4410-867a-d4a49f16acc2/jobs/89410)

### CODE REVIEW

**Comment by NGA-TRAN** [comment]
@alamb and @matthewmturner Can you help review this?

**Comment by xudong963** [comment]
Thanks for your nice work 🎉@NGA-TRAN 

FYI
```shell
case1
postgres=# select 11 BETWEEN 0 AND 10 and NULL as c;
 c
---
 f
(1 row)

case2
postgres=# select 1 BETWEEN 0 AND 10 and NULL as c;
 c
---

(1 row)

case3
postgres=# select 1 BETWEEN 0 AND 10 or NULL as c;
 c
---
 t
(1 row)

case4
postgres=# select 11 BETWEEN 0 AND 10 or NULL as c;
 c
---

(1 row)
```
So I think we can add two tests about case1 and case4. @NGA-TRAN

File: datafusion/src/optimizer/constant_folding.rs [hunk 1]
```diff
@@ -135,6 +135,98 @@ impl<'a> Simplifier<'a> {
...
+                // NULL or expr can be either NULL or TRUE
+                // So let us not rewrite it
+                _ => {
+                    let mut left =
+                        Box::new(Expr::Literal(ScalarValue::Boolean(*const_bool)));
+                    let mut right = bool_expr;
+                    if !left_right_order {
+                        left = right;
+                        right =
+                            Box::new(Expr::Literal(ScalarValue::Boolean(*const_bool)));
```
Comment (alamb) [inline datafusion/src/optimizer/constant_folding.rs:172]: I think you might be able to use `swap` here if you wanted: https://doc.rust-lang.org/stable/std/mem/fn.swap.html

so something like `std::mem::swap(&mut left, &mut right)`

File: datafusion/src/optimizer/constant_folding.rs [hunk 2]
```diff
@@ -135,6 +135,98 @@ impl<'a> Simplifier<'a> {
...
+        left_right_order: bool,
+    ) -> Expr {
+        // See if we can fold 'const_bool AND bool_expr' to a constant boolean
+        match const_bool {
+            // TRUE and expr (including NULL) = expr
+            Some(true) => *bool_expr,
+            // FALSE and expr (including NULL) = FALSE
+            Some(false) => Expr::Literal(ScalarValue::Boolean(Some(false))),
+            None => match *bool_expr {
+                // NULL and TRUE = NULL
```
Comment (alamb) [inline datafusion/src/optimizer/constant_folding.rs:197]: FWIW I am working on getting these constant cases to work with the `ConstEvaluator` (so they wouldn't be strictly necessary) but it turns out these types of expressions don't actually work in the general evaluator

I am working on it in https://github.com/apache/arrow-datafusion/pull/1163

But in any event I think this code is good 👍

**Review by alamb — APPROVED** [review]
Thank you @NGA-TRAN  -- I find the new structure and comments much easier to follow.

**Comment by NGA-TRAN** [comment]
@xudong963 Those are great queries. I have tried to add them in the test but I think we have not done constant folding for `Between` yet (or at least not for the queries in your examples) so they are not folded at this time. Hence, I do not commit them in because they are the same as the current between query.

I can open a new ticket for improving these cases though. What do you think @alamb ?

**Comment by NGA-TRAN** [comment]
@alamb I have addressed the comments. It should be ready for merge when all checks pass

**Comment by alamb** [comment]
> @xudong963 Those are great queries. I have tried to add them in the test but I think we have not done constant folding for Between yet (or at least not for the queries in your examples) so they are not folded at this time. Hence, I do not commit them in because they are the same as the current between query.
>
> I can open a new ticket for improving these cases though. What do you think @alamb ?


I think the constant folding is handled by `ConstEvaluator` (in a different module). The `Simplifier` is supposed to be focused on items that can't be folded (like `TRUE OR <expr>` --> `<expr>`). 

The fact we have some boolean constant evaluation in here is a historical artifact and due to the fact we don't have full expression evaluation support for all boolean operations (yet).

Thus I don't think a separate ticket is needed

**Review by alamb — APPROVED** [review]
Thanks @NGA-TRAN
