### PR TITLE
fix `push_down_projection` push redundant columns.

### LINKED ISSUE #3635: after type coercion `CommonSubexprEliminate` will produce invalid projection
**Describe the bug**

after do this pr with moving the type coercion to the beginning for the optimizer, the `CommonSubexprEliminate` will generate the invalid projection

maybe like https://github.com/apache/arrow-datafusion/issues/2907

I think many of the optimizer rule didn't take care of the `cast/try_cast` for the type coercion.

**To Reproduce**

**Expected behavior**

**Additional context**

### LINKED ISSUE #4174: `ProjectionPushDown` rule don't consider the alias in projection.
**Describe the bug**
> It's from #4141 

pushdown project rule don't handle alias. In fact, when handle projection with alias, we need replace the alias column in new_required_columns, but if we see the code of this rule, we can find that it didn't consider alias.

For example:

project c1 as c2
    tablescan c1.
when we meet project c1 as c2, if new_required_columns include c2, we need replace it with c1.

**To Reproduce**

**Expected behavior**

**Additional context**

### LINKED ISSUE #4486: `Push_down_projection` push extra column.
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #4486
Closes #4174 
Closes #3635.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by jackwener** [comment]
cc @liukun4515 
This may be related to some bugs you mentioned before.

File: datafusion/core/tests/sql/predicates.rs [hunk 1]
```diff
@@ -549,8 +549,7 @@ async fn in_set_string_dictionaries() -> Result<()> {
 }
 
 #[tokio::test]
-#[ignore]
-// https://github.com/apache/arrow-datafusion/issues/3635
+// Test issue: https://github.com/apache/arrow-datafusion/issues/3635
 async fn multiple_or_predicates() -> Result<()> {
```
Comment (jackwener) [inline datafusion/core/tests/sql/predicates.rs:553]: Please notice this `Test`

File: datafusion/core/tests/sql/explain_analyze.rs [hunk 2]
```diff
@@ -744,7 +744,7 @@ async fn test_physical_plan_display_indent_multi_children() {
         "        RepartitionExec: partitioning=Hash([Column { name: \"c2\", index: 0 }], 9000)",
         "          ProjectionExec: expr=[c1@0 as c2]",
         "            RepartitionExec: partitioning=RoundRobinBatch(9000)",
-        "              CsvExec: files={1 group: [[ARROW_TEST_DATA/csv/aggregate_test_100.csv]]}, has_header=true, limit=None, projection=[c1, c2]",
+        "              CsvExec: files={1 group: [[ARROW_TEST_DATA/csv/aggregate_test_100.csv]]}, has_header=true, limit=None, projection=[c1]",
```
Comment (alamb) [inline datafusion/core/tests/sql/explain_analyze.rs:747]: 👍

File: datafusion/optimizer/src/push_down_projection.rs [hunk 3]
```diff
@@ -94,23 +94,19 @@ fn optimize_plan(
 
             let mut new_expr = Vec::new();
             let mut new_fields = Vec::new();
+            let mut new_required_columns = HashSet::new();
```
Comment (alamb) [inline datafusion/optimizer/src/push_down_projection.rs:97]: Since this is shadowing a variable in the outer scope, I wonder if it would make sense to comment why we are starting with an empty set in this case rather than the pushed down columns?

File: datafusion/core/tests/sql/predicates.rs [hunk 4]
```diff
@@ -589,19 +588,15 @@ async fn multiple_or_predicates() -> Result<()> {
...
...;N, lineitem.l_quantity <= Decimal128(Some(2000),15,2)Decimal128(Some(2000),15,2)lineitem.l_quantity:Boolean;N, lineitem.l_quantity <= Decimal128(Some(3000),15,2)Decimal128(Some(3000),15,2)lineitem.l_quantity:Boolean;N, lineitem.l_quantity >= Decimal128(Some(100),15,2) OR lineitem.l_quantity <= Decimal128(Some(2000),15,2)lineitem.l_quantity <= Decimal128(Some(2000),15,2)Decimal128(Some(2000),15,2)lineitem.l_quantitylineitem.l_quantity >= Decimal128(Some(100),15,2)Decimal128(Some(100),15,2)lineitem.l_quantity:Boolean;N, lineitem.l_quantity >= Decimal128(Some(100),15,2) OR lineitem.l_quantity >= Decimal128(Some(1000),15,2)lineitem.l_quantity >= Decimal128(Some(1000),15,2)Decimal128(Some(1000),15,2)lineitem.l_quantitylineitem.l_quantity >= Decimal128(Some(100),15,2)Decimal128(Some(100),15,2)lineitem.l_quantity:Boolean;N, lineitem.l_quantity >= Decimal128(Some(100),15,2)Decimal128(Some(100),15,2)lineitem.l_quantity:Boolean;N, lineitem.l_quantity >= Decimal128(Some(1000),15,2)Decimal128(Some(1000),15,2)lineitem.l_quantity:Boolean;N, lineitem.l_quantity >= Decimal128(Some(2000),15,2)Decimal128(Some(2000),15,2)lineitem.l_quantity:Boolean;N, l_partkey:Int64, l_quantity:Decimal128(15, 2)]",
```
Comment (alamb) [inline datafusion/core/tests/sql/predicates.rs:595]: this filter looks pretty nasty -- perhaps it is related to https://github.com/apache/arrow-datafusion/pull/3903 🤔 

On the other hand, there is a lot of pushed down filtering now 👍 
cc @Ted-Jiang

**Review by alamb — APPROVED** [review]
Thank you @jackwener  -- this is epically beautiful -- 3 tickets closed with a very small number of lines changed ❤️

**Comment by alamb** [comment]
(there are several conflicts in this PR that need to be solved prior to merge)

File: datafusion/optimizer/src/push_down_projection.rs (hunk 3 above)
Comment (jackwener) [reply datafusion/optimizer/src/push_down_projection.rs:97]: 👍Yes, I have added comment to explain it.

**Comment by jackwener** [comment]
Resolved conflict and added comment. Thanks @alamb review

File: datafusion/core/tests/sql/predicates.rs (hunk 4 above)
Comment (Ted-Jiang) [reply datafusion/core/tests/sql/predicates.rs:595]: yes, seems not readable, maybe we can try to keep both input and result only show the input one 🤔

**Comment by alamb** [comment]
> Resolved conflict and added comment. Thanks @alamb review


Sorry for the delay in reviewing -- the PRs are flying fast and furious these days

**Review by alamb — APPROVED** [review]

File: datafusion/core/tests/sql/predicates.rs (hunk 4 above)
Comment (jackwener) [reply datafusion/core/tests/sql/predicates.rs:595]: it should be cause by #4575
