### PR TITLE
`case when` supports `NULL`  constant

### LINKED ISSUE #1189: CASE expr with NULL literals panics `'WHEN expression did not return a BooleanArray'`
Reproducer:

```sql
> select CASE WHEN NULL THEN 'foo' ELSE 'bar' END;
thread 'main' panicked at 'WHEN expression did not return a BooleanArray', datafusion/src/physical_plan/expressions/case.rs:381:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The correct output is `'bar'`

I think the solution will likely be to teach `CaseExpr` about type coercion (as is done in `BinaryExpr` and function calls) once coercion knows about the null type (and that it can be cast to any other type). See https://github.com/apache/arrow-datafusion/issues/1184 for more details

### PR DESCRIPTION
**Pull request by WinkerDu**
# Which issue does this PR close?

Closes #1189.

 # Rationale for this change

df `case when` expression cannot take `NULL` constant, like
```
> select CASE WHEN NULL THEN 'foo' ELSE 'bar' END;
thread 'main' panicked at 'WHEN expression did not return a BooleanArray', datafusion/src/physical_plan/expressions/case.rs:381:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Postgres:
```
# select case null when null then 'foo' else 'bar' end;
 case 
------
 bar
(1 row)
```

# What changes are included in this PR?

For `when expression` without `case expression`, treat `NULL` as `false` before down cast to `BooleanArray`

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by WinkerDu** [comment]
cc @yjshen @Dandandan @alamb

File: datafusion/physical-expr/src/expressions/case.rs [hunk 1]
```diff
@@ -178,6 +178,17 @@ impl CaseExpr {
...
+            let when_value = match when_value {
+                ColumnarValue::Scalar(value) => {
+                    if value.is_null() {
+                        ColumnarValue::Scalar(ScalarValue::Boolean(Some(false)))
+                    } else {
+                        ColumnarValue::Scalar(value)
+                    }
+                }
+                _ => when_value,
+            };
```
Comment (yjshen) [inline datafusion/physical-expr/src/expressions/case.rs:191]:
```suggestion
            let when_value = match when_value {
                ColumnarValue::Scalar(value) if value.is_null() => {
                    continue;
                }
                _ => when_value,
            };
```

**Review by yjshen — COMMENTED** [review]
It seems the type-coercion suggested in the issue is not used. Cc @alamb.

File: datafusion/physical-expr/src/expressions/case.rs [hunk 2]
```diff
@@ -24,7 +24,7 @@ use arrow::compute::kernels::zip::zip;
 use arrow::compute::{and, eq_dyn, is_null, not, or, or_kleene};
 use arrow::datatypes::{DataType, Schema};
 use arrow::record_batch::RecordBatch;
-use datafusion_common::{DataFusionError, Result};
+use datafusion_common::{DataFusionError, Result, ScalarValue};
```
Comment (yjshen) [inline datafusion/physical-expr/src/expressions/case.rs:27]:
```suggestion
use datafusion_common::{DataFusionError, Result};
```

**Comment by WinkerDu** [comment]
cc @yjshen @alamb  another commit pushed, PTAL, thank you.

File: datafusion/physical-expr/src/expressions/case.rs [hunk 3]
```diff
@@ -178,6 +178,13 @@ impl CaseExpr {
             let when_value = self.when_then_expr[i]
                 .0
                 .evaluate_selection(batch, &remainder)?;
+            // Treat 'NULL' as false value
+            let when_value = match when_value {
+                ColumnarValue::Scalar(value) if value.is_null() => {
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:183]: This is a reasonable solution I think -- ideally we would have been able to coerce this value into a `ColumnarValue::Scalar(ScalarValue::Boolean(None))` at some earlier point.

However, I think this special case is reasonable (and the test coverage is nice) so 👍  from me

**Review by alamb — APPROVED** [review]
Thank you @WinkerDu

**Comment by WinkerDu** [comment]
@alamb @yjshen thank you both!

**Comment by alamb** [comment]
Thank you @WinkerDu
