### PR TITLE
Remove FileWriterMode and ListingTableInsertMode (#7994)

### LINKED ISSUE #7991: AsyncPutWriter::poll_shutdown_inner Incorrect
### Describe the bug

`AsyncPutWriter` has the following code

```
AsyncPutState::Put { bytes } => {
    // Send the bytes to the object store's put method
    return Poll::Ready(
        ready!(self
            .store
            .put(&self.object_meta.location, bytes.clone())
            .poll_unpin(cx))
        .map_err(Error::from),
    );
}
```

This will only work if store.put doesn't return Poll::Pending, in such a case the future will get dropped, cancelling the operation and never rescheduling the waker.

FYI @devinjdangelo 

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tustvold**
## Which issue does this PR close?

Relates to #7994
Closes #7991 

## Rationale for this change

Following #8021 append semantics are handled by a separate TableProvider, this allows removing the corresponding logic from ListingTable.

Further cleanups will likely follow, but this is all that is necessary to unblock #8029

### CODE REVIEW

File: datafusion/core/src/datasource/file_format/write/mod.rs [hunk 1]
```diff
@@ -19,128 +19,32 @@
...
 
 use tokio::io::AsyncWrite;
 
 pub(crate) mod demux;
 pub(crate) mod orchestration;
 
-/// `AsyncPutWriter` is an object that facilitates asynchronous writing to object stores.
-/// It is specifically designed for the `object_store` crate's `put` method and sends
-/// whole bytes at once when the buffer is flushed.
-pub struct AsyncPutWriter {
```
Comment (tustvold) [inline datafusion/core/src/datasource/file_format/write/mod.rs:53]: This wasn't actually hooked up anywhere (and was actually incorrect and wouldn't have worked anyway #7991)

File: datafusion/core/src/datasource/file_format/write/mod.rs [hunk 2]
```diff
@@ -229,16 +116,6 @@ impl<W: AsyncWrite + Unpin + Send> AsyncWrite for AbortableWrite<W> {
     }
 }
 
-/// An enum that defines different file writer modes.
-#[derive(Debug, Clone, Copy)]
-pub enum FileWriterMode {
```
Comment (tustvold) [inline datafusion/core/src/datasource/file_format/write/mod.rs:234]: Given FileWriterMode::Put is not implemented by anything, and we are removing FileWriterMode::Append, it seemed simplest to just remove this. This also frees up implementations to choose an adaptive IO strategy, where they can determine if `Put` is appropriate

File: datafusion/sqllogictest/test_files/insert_to_external.slt [hunk 3]
```diff
@@ -267,8 +267,6 @@ INSERT INTO single_file_test values (4, 5), (6, 7);
 query II
 select * from single_file_test;
 ----
-1 2
```
Comment (tustvold) [inline datafusion/sqllogictest/test_files/insert_to_external.slt:270]: This is a change worth highlighting, inserting into a ListingTable backed by a single CSV or JSON file now overwrites

**Comment by tustvold** [comment]
FYI @devinjdangelo @alamb @ozankabak @metesynnada

File: datafusion/core/src/datasource/listing/table.rs [hunk 4]
```diff
@@ -214,33 +214,6 @@ impl ListingTableConfig {
...
 
-#[derive(Debug, Clone)]
-///controls how new data should be inserted to a ListingTable
-pub enum ListingTableInsertMode {
-    ///Data should be appended to an existing file
-    AppendToFile,
-    ///Data is appended as new files in existing TablePaths
-    AppendNewFiles,
-    ///Throw an error if insert into is attempted on this table
-    Error,
```
Comment (tustvold) [inline datafusion/core/src/datasource/listing/table.rs:225]: It is worth highlighting this also removes ListingTableInsertMode::Error, I wasn't sure that this was important to preserve but happy to restore if people feel strongly. @devinjdangelo

Comment (devinjdangelo) [reply datafusion/core/src/datasource/listing/table.rs:225]: Removing error is fine by me. A formal access control mechanism would be better than the error mode option.

I do think there is some value to append mode for ListingTable. Specifically it enables tables backed by a single file where inserts append to that file.

This is a relatively niche usecase so I'm not bothered if it is removed.

Comment (tustvold) [reply datafusion/core/src/datasource/listing/table.rs:225]: > Specifically it enables tables backed by a single file where inserts append to that file.

I believe this use-case is now covered by StreamTable unless I am missing something here?

Comment (devinjdangelo) [reply datafusion/core/src/datasource/listing/table.rs:225]: That could be (I haven't dug into StreamTable yet). The usecase for append I'm thinking of isn't really streaming related. More like a batch job that appends to one file or a fixed set of files on disk.

Comment (tustvold) [reply datafusion/core/src/datasource/listing/table.rs:225]: StreamTable will do the former, but cannot, yet, handle multiple files. We could add this but I would rather scream test if anyone is actually doing this

File: datafusion/core/src/datasource/file_format/write/mod.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/src/datasource/file_format/write/mod.rs:53]: Indeed I double checked  and it appears to be dead code (unused and untested):

https://github.com/search?q=repo%3Aapache%2Farrow-datafusion%20AsyncPutWriter&type=code

Screenshot 2023-11-16 at 8 40 03 AM

File: datafusion/core/src/datasource/file_format/write/mod.rs [hunk 5]
```diff
@@ -163,45 +67,28 @@ impl MultiPart {
...
-
 /// A wrapper struct with abort method and writer
 pub(crate) struct AbortableWrite<W: AsyncWrite + Unpin + Send> {
     writer: W,
-    mode: AbortMode,
+    multipart: MultiPart,
 }
 
 impl<W: AsyncWrite + Unpin + Send> AbortableWrite<W> {
     /// Create a new `AbortableWrite` instance with the given writer, and write mode.
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/write/mod.rs:77]: the doc comments may also need updating

File: datafusion/core/src/datasource/listing/table.rs (hunk 4 above)
Comment (alamb) [reply datafusion/core/src/datasource/listing/table.rs:225]: It would be good to hear about a usecase of appending to a set of existing files -- it is not a usecase I am familiar with but also my background is in analytic database where it is more common to make new files (and then "compact/rewrite" them as subsequent step) rather than modifying existing files

File: datafusion/sqllogictest/test_files/insert_to_external.slt (hunk 3 above)
Comment (alamb) [reply datafusion/sqllogictest/test_files/insert_to_external.slt:270]: I think it should be an error. It would also be really good to call out how to get "append" semantics (which I believe requires using `CREATE UNBOUNDED TABLE ...`)?

**Review by alamb — COMMENTED** [review]
Thank you for this (and https://github.com/apache/arrow-datafusion/pull/8021) @tustvold  -- I think this looks like a nice alighnment to separate object_store backed `ListingTable`s and the more flexible `StreamingTable`. 

I do think we should make writing into an existing file error (rather than change the behavior from append to overwrite) as it is a significant change that I think could result in dataloss for existing users who expected the old behavior.

I also don't think we should merge it until @ozankabak  and @metegenez  have a chance to weigh in and approve, given the potential overlap between what I believe they are working on and the changes in this PR.

**Comment by ozankabak** [comment]
Thank you, we will take a look tomorrow

**Review by alamb — APPROVED** [review]
Thanks @tustvold  -- this PR is good to go from my perspective, but just to be over communicative I do not think we should merge it until review and approval from @ozankabak  / @metesynnada

**Comment by ozankabak** [comment]
> Thanks @tustvold -- this PR is good to go from my perspective, but just to be over communicative I do not think we should merge it until review and approval from @ozankabak / @metesynnada

Thanks, we will circle back tomorrow morning. I took a quick look and it looks good to me, but I want to consult with @metesynnada just to be sure.

**Comment by tustvold** [comment]
Do you require further time? Happy to wait, just checking where we stand

**Review by ozankabak — APPROVED** [review]
Thank you @tustvold, AFAICT this is good to go from our perspective. In case we are overlooking anything, we can send a quick follow-on PR. But all seems good now 🚀
