### PR TITLE
Disable parallel reading for gziped ndjson file

### LINKED ISSUE #9564: Parallel read for json compressed files when it should not
### Describe the bug

When reading a compressed json file, with `repartition_file_scans = true` (default value), datafusion try to uncompress the file with parallel read. This will cause `ArrowError(IoError("invalid gzip header", Custom { kind: InvalidInput, error: "invalid gzip header" }), None)` because there is no gzip header in the middle. 

### To Reproduce

```rust
let df = ctx.read_json(
        "C:/path/to/file.gz", 
        NdJsonReadOptions::default()
        .file_compression_type(FileCompressionType::GZIP)
        .file_extension("gz")
        .schema(&s3_user_schema())
    ).await.unwrap();
```

### Expected behavior

the data should read correctly without errors

### Additional context

by put a print statement before the `JsonOpener`, we can see
```
GetResult { payload: GetResultPayload(File), meta: ObjectMeta { location: Path { raw: "C:/some/path/foo.gz" }, last_modified: 2024-03-06T00:01:02Z, size: 149873338, e_tag: Some("0-612f2a7828b80-8eee2ba"), version: None }, range: 0..4685075 }
GetResult { payload: GetResultPayload(File), meta: ObjectMeta { location: Path { raw: "C:/some/path/foo.gz" }, last_modified: 2024-03-06T00:01:02Z, size: 149873338, e_tag: Some("0-612f2a7828b80-8eee2ba"), version: None }, range: 37468620..42151887 }
GetResult { payload: GetResultPayload(File), meta: ObjectMeta { location: Path { raw: "C:/some/path/foo.gz" }, last_modified: 2024-03-06T00:01:02Z, size: 149873338, e_tag: Some("0-6.......
```
which suggest it's indeed reading a compressed json file in parallel.

### PR DESCRIPTION
**Pull request by Lordworms**
## Which issue does this PR close?

Closes #9564

### CODE REVIEW

File: datafusion/core/src/datasource/physical_plan/json.rs [hunk 1]
```diff
@@ -884,4 +898,48 @@ mod tests {
...
+        io::copy(&mut reader, &mut encoder)?;
+
+        encoder.finish()?;
+        Ok(())
+    }
+    #[tokio::test]
+    async fn test_disable_parallel_for_json_gz() -> Result<()> {
+        let config = SessionConfig::new()
+            .with_repartition_file_scans(true)
+            .with_repartition_file_min_size(0)
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/json.rs:918]: 👍

File: datafusion/core/src/datasource/physical_plan/json.rs [hunk 2]
```diff
@@ -150,12 +151,22 @@ impl ExecutionPlan for NdJsonExec {
         target_partitions: usize,
         config: &datafusion_common::config::ConfigOptions,
     ) -> Result<Option<Arc<dyn ExecutionPlan>>> {
-        let repartition_file_min_size = config.optimizer.repartition_file_min_size;
+        let repartition_file_min_size =
+            if self.file_compression_type == FileCompressionType::GZIP {
+                OptimizerOptions::default().repartition_file_min_size
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/json.rs:156]: I wonder it it would be simpler code to return `None` here
```suggestion
                None
```

That way the rest of the code could be left alone.

**Review by alamb — APPROVED** [review]
Thank you for the contribution @Lordworms  🙏 

I left a suggestion on how to clean up the code but I don't think it is required to merge this PR.

File: datafusion/core/src/datasource/physical_plan/json.rs (hunk 2 above)
Comment (Lordworms) [reply datafusion/core/src/datasource/physical_plan/json.rs:156]: Sure

File: datafusion/core/src/datasource/physical_plan/json.rs [hunk 3]
```diff
@@ -150,6 +151,9 @@ impl ExecutionPlan for NdJsonExec {
         target_partitions: usize,
         config: &datafusion_common::config::ConfigOptions,
     ) -> Result<Option<Arc<dyn ExecutionPlan>>> {
+        if self.file_compression_type == FileCompressionType::GZIP {
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/json.rs:154]: ❤️

**Review by alamb — APPROVED** [review]
Thank you @Lordworms 🙏 

Looks like there is a small CI failure otherwise this PR is ready to go

**Review by Dandandan — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @Lordworms  and @Dandandan 🙏
