### PR TITLE
#723 Datafusion add option in ExecutionConfig to enable/disable parquet pruning

### LINKED ISSUE #723: ABS() function in WHERE clause gives unexpected results
**Describe the bug**
ABS(col - x) in WHERE clause of query sometimes does not filter results correctly. The test file has a float column with high-precision values. We want to use `ABS(col - x) < y` to do equality comparisons for high-precision float columns.

**To Reproduce**
datafusion cli example using test parquet file attached:

```
➜  arrow-datafusion git:(master) ✗ cargo run --bin datafusion-cli
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/datafusion-cli`
> CREATE EXTERNAL TABLE foo STORED AS PARQUET LOCATION 'test.parquet';
0 rows in set. Query took 0.001 seconds.
> select * from foo;
+--------------------+
| c0                 |
+--------------------+
| 107.0090813093981  |
| 125.51519138755981 |
| 141.83342587451415 |
| 113.65534481251639 |
| 251.10794896957802 |
| 112.08361695028363 |
+--------------------+
6 rows in set. Query took 0.006 seconds.
> select c0, ABS(c0 - 251.10794896957802) from foo;
+--------------------+-------------------------------------------+
| c0                 | abs(c0 Minus Float64(251.10794896957802)) |
+--------------------+-------------------------------------------+
| 107.0090813093981  | 144.0988676601799                         |
| 125.51519138755981 | 125.59275758201821                        |
| 141.83342587451415 | 109.27452309506387                        |
| 113.65534481251639 | 137.45260415706161                        |
| 251.10794896957802 | 0                                         |
| 112.08361695028363 | 139.02433201929438                        |
+--------------------+-------------------------------------------+
6 rows in set. Query took 0.006 seconds.
> select c0, ABS(c0 - 251.10794896957802) from foo where ABS(c0 - 251.10794896957802) < 1;
0 rows in set. Query took 0.005 seconds.
> select c0, ABS(c0 - 251.10794896957802) from foo where ABS(c0 - 251.10794896957802) < 111;
0 rows in set. Query took 0.003 seconds.
> select c0, ABS(c0 - 251.10794896957802) from foo where ABS(c0 - 251.10794896957802) < 150;
+--------------------+-------------------------------------------+
| c0                 | abs(c0 Minus Float64(251.10794896957802)) |
+--------------------+-------------------------------------------+
| 107.0090813093981  | 144.0988676601799                         |
| 125.51519138755981 | 125.59275758201821                        |
| 141.83342587451415 | 109.27452309506387                        |
| 113.65534481251639 | 137.45260415706161                        |
| 251.10794896957802 | 0                                         |
| 112.08361695028363 | 139.02433201929438                        |
+--------------------+-------------------------------------------+
6 rows in set. Query took 0.007 seconds.
```

**Expected behavior**
The query
```
> select c0, ABS(c0 - 251.10794896957802) from foo where ABS(c0 - 251.10794896957802) < 1;
```
was expected to give the following 1 row:
```
+--------------------+-------------------------------------------+
| c0                 | abs(c0 Minus Float64(251.10794896957802)) |
+--------------------+-------------------------------------------+
| 251.10794896957802 | 0                                         |
```

And the query 

```
> select c0, ABS(c0 - 251.10794896957802) from foo where ABS(c0 - 251.10794896957802) < 111;
```
was expected to give the following 2 rows:
```
+--------------------+-------------------------------------------+
| c0                 | abs(c0 Minus Float64(251.10794896957802)) |
+--------------------+-------------------------------------------+
| 251.10794896957802 | 0                                         |
| 141.83342587451415 | 109.27452309506387                        |
```

**Additional context**
Test parquet: [test.parquet.zip](https://github.com/apache/arrow-datafusion/files/6812957/test.parquet.zip)

### PR DESCRIPTION
**Pull request by lvheyang**
# Which issue does this PR close?

RE #723.

but it is just the first step, we need another pr to close the issue.

 # Rationale for this change

Add an option in ExecutionConfig, to help users disable/enable parquet pruning to work around the features' bug

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/src/datasource/parquet.rs [hunk 1]
```diff
@@ -38,11 +38,22 @@ pub struct ParquetTable {
...
 
 impl ParquetTable {
     /// Attempt to initialize a new `ParquetTable` from a file path.
     pub fn try_new(path: impl Into<String>, max_concurrency: usize) -> Result<Self> {
+        ParquetTable::try_new_with_pruning_config(path, max_concurrency, true)
+    }
+
+    /// Attempt to initialize a new `ParquetTable` from a file path. And enable or
+    /// disable the parquet pruning features.
+    pub fn try_new_with_pruning_config(
```
Comment (lvheyang) [inline datafusion/src/datasource/parquet.rs:52]: Here I'm not sure if adding the function is a good choice. 

My concern is, it is a public function, there may be many users who rely on it. But the `enable_pruning` in the signature is somehow temporal, we don't want it to last for a long time.

So I have another thought, replace this function with `try_new_with_config(path: impl Into<String>,, execution_config: ExecutionConfig)`. I think it's a better option, but it will introduce the dependency of `execution::context` module which I think is the top-level module. It seems a little weird. 

I'm not sure if the second method is acceptable?

Comment (houqp) [reply datafusion/src/datasource/parquet.rs:52]: how about adopting the same builder design you went with `pub fn with_parquet_pruning`? then you can initialize it as:

```rust
            ParquetTable::try_new(
                filename,
                m.config.concurrency,
            )?.with_enable_pruning(m.config.parquet_pruning)
```

Comment (lvheyang) [reply datafusion/src/datasource/parquet.rs]: @houqp Thank you for your advice. I think it is more elegant than my first version, and I've modified it to this style.

**Review by houqp — APPROVED** [review]

**Review by alamb — APPROVED** [review]
Thank you @lvheyang  - I am writing a test for this code which we can add as a follow on PR
