### PR TITLE
Fix Predicate Pushdown: split_members should be able to split aliased predicate

### LINKED ISSUE #1367: TPC-H q10 performance regression (expression for filter with added alias is not pushed down)
**Describe the bug**
Fastest I get on master is 10s. After https://github.com/apache/arrow-datafusion/pull/1366 it's around 7s,
This used to be <2s.
Looking at the plan it looks like some filters are not pushed down successfully `(o_orderdate@9 >= 8674 AND o_orderdate@9 < 8766 AND l_returnflag@13 = R`)

After #1319 we added some alias to constant folding. Might be good to only do this for `Projection` (at least, not in `Filter`).

As you can see the filter has an `AS` - which makes the filter push down to not work.

```
[2021-11-26T17:12:17Z DEBUG datafusion::execution::context] Optimized logical plan:
     Sort: #revenue DESC NULLS FIRST
      Projection: #customer.c_custkey, #customer.c_name, #SUM(lineitem.l_extendedprice * Int64(1) - lineitem.l_discount) AS revenue, #customer.c_acctbal, #nation.n_name, #customer.c_address, #customer.c_phone, #customer.c_comment
        Aggregate: groupBy=[[#customer.c_custkey, #customer.c_name, #customer.c_acctbal, #customer.c_phone, #nation.n_name, #customer.c_address, #customer.c_comment]], aggr=[[SUM(#lineitem.l_extendedprice * Int64(1) - #lineitem.l_discount)]]
          Join: #customer.c_nationkey = #nation.n_nationkey
            Filter: #orders.o_orderdate >= Date32("8674") AND #orders.o_orderdate < Date32("8766") AND #lineitem.l_returnflag = Utf8("R") AS orders.o_orderdate >= CAST(Utf8("1993-10-01") AS Date32) AND orders.o_orderdate < CAST(Utf8("1994-01-01") AS Date32) AND lineitem.l_returnflag = Utf8("R")
              Join: #orders.o_orderkey = #lineitem.l_orderkey
                Join: #customer.c_custkey = #orders.o_custkey
                  TableScan: customer projection=Some([0, 1, 2, 3, 4, 5, 7])
                  TableScan: orders projection=Some([0, 1, 4])
                TableScan: lineitem projection=Some([0, 5, 6, 8])
            TableScan: nation projection=Some([0, 1])

```

**To Reproduce**
Use latest master to run q10 against some parquet data. Use an older version (to be found out how old).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1367.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by viirya** [comment]
cc @Dandandan

File: datafusion/src/optimizer/constant_folding.rs [hunk 1]
```diff
@@ -641,8 +648,8 @@ mod tests {
 
         let expected = "\
         Projection: #test.a\
-        \n  Filter: NOT #test.c AS test.c = Boolean(false)\
-        \n    Filter: #test.b AS test.b = Boolean(true)\
+        \n  Filter: NOT #test.c\
```
Comment (Dandandan) [inline datafusion/src/optimizer/constant_folding.rs:651]: 👍

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
thanks @viirya for the quick change / PR! I think this is a good change.

I am wondering if there's more places where we don't want to add an alias. 

Also we probably need some more tests to cover filter pushdown in combination with other optimization passes like this one.

Another thing to consider might be for the filter operation to ignore the alias.

FYI @alamb WDYT

File: datafusion/src/optimizer/constant_folding.rs [hunk 2]
```diff
@@ -106,16 +106,23 @@ impl OptimizerRule for ConstantFolding {
...
 
-                        let new_name = &new_e.name(plan.schema());
-
-                        if let (Ok(expr_name), Ok(new_expr_name)) = (name, new_name) {
-                            if expr_name != new_expr_name {
-                                Ok(new_e.alias(expr_name))
-                            } else {
-                                Ok(new_e)
+                        match plan {
+                            LogicalPlan::Filter { .. } => Ok(new_e),
```
Comment (alamb) [inline datafusion/src/optimizer/constant_folding.rs:110]: I would like to recommend adding a comment here about why we don't add aliases for filter.

**Review by alamb — COMMENTED** [review]
I don't really understand how aliases can mess up filter push down (perhaps filter pushdown should be stripping off the aliases)?

**Comment by alamb** [comment]
Yeah, I suggest:

1. Adding a test with the TPCH explain plans (so we can detect such errors earlier in the future)
2. Looking into what is going on with Filter pushdown that aliases disabled them.

I "feel" like there should be nothing wrong with aliasing the output of a `Filter`

**Comment by viirya** [comment]
Thanks. I'm adding a test for TPCH plans. I will take a look on Filter pushdown with aliases later.

**Comment by viirya** [comment]
Currently the filter_push_down rule fails on TPCH q10 with aliased on Filter because `split_members` method doesn't address `Alias` so a predicate like `#orders.o_orderdate >= Date32("8674") AND #orders.o_orderdate < Date32("8766") AND #lineitem.l_returnflag = Utf8("R") AS ...` will not be split so it won't be pushed down.

By adding `Alias` into `split_members`, the rule can push down aliased predicate.

File: datafusion/tests/sql.rs [hunk 3]
```diff
@@ -3543,6 +3543,135 @@ async fn explain_analyze_runs_optimizers() {
     assert_contains!(actual, expected);
 }
 
+#[tokio::test]
+async fn tpch_explain_q10() -> Result<()> {
```
Comment (Dandandan) [inline datafusion/tests/sql.rs:3547]: Nice :+1: 
Maybe it would be good to have those in the tpch crate instead?
In that case we could include some / all other queries as well.

File: datafusion/src/optimizer/filter_push_down.rs [hunk 4]
```diff
@@ -245,6 +245,9 @@ fn split_members<'a>(predicate: &'a Expr, predicates: &mut Vec<&'a Expr>) {
             split_members(left, predicates);
             split_members(right, predicates);
         }
+        Expr::Alias(expr, _) => {
```
Comment (alamb) [inline datafusion/src/optimizer/filter_push_down.rs:248]: 💯  excellent

File: datafusion/tests/sql.rs (hunk 3 above)
Comment (alamb) [reply datafusion/tests/sql.rs:3547]: I agree -- filed https://github.com/apache/arrow-datafusion/issues/1377 to track this

File: datafusion/tests/sql.rs [hunk 5]
```diff
@@ -3543,6 +3543,135 @@ async fn explain_analyze_runs_optimizers() {
...
+    let expected = "\
+    Sort: #revenue DESC NULLS FIRST\
+    \n  Projection: #customer.c_custkey, #customer.c_name, #SUM(lineitem.l_extendedprice * Int64(1) - lineitem.l_discount) AS revenue, #customer.c_acctbal, #nation.n_name, #customer.c_address, #customer.c_phone, #customer.c_comment\
+    \n    Aggregate: groupBy=[[#customer.c_custkey, #customer.c_name, #customer.c_acctbal, #customer.c_phone, #nation.n_name, #customer.c_address, #customer.c_comment]], aggr=[[SUM(#lineitem.l_extendedprice * Int64(1) - #lineitem.l_discount)]]\
+    \n      Join: #customer.c_nationkey = #nation.n_nationkey\
+    \n        Join: #orders.o_orderkey = #lineitem.l_orderkey\
+    \n          Join: #customer.c_custkey = #orders.o_custkey\
+    \n            TableScan: customer projection=Some([0, 1, 2, 3, 4, 5, 7])\
+    \n            Filter: #orders.o_orderdate >= Date32(\"8674\") AND #orders.o_orderdate < Date32(\"8766\")\
+    \n              TableScan: orders projection=Some([0, 1, 4]), filters=[#orders.o_orderdate >= Date32(\"8674\"), #orders.o_orderdate < Date32(\"8766\")]\
```
Comment (alamb) [inline datafusion/tests/sql.rs:3599]: so lovely to see those filters pushed down ❤️

**Review by alamb — APPROVED** [review]
Thank you @viirya !

Would it be possible to move the tpch tests into the tpch crate, as suggested by @Dandandan as part of this PR?

Someone can add explain plans for the other TPCH queries as part of https://github.com/apache/arrow-datafusion/issues/1377 so I don't think that is necessary.

Thanks for sticking with this one and finding the elegant solution

**Comment by viirya** [comment]
Thanks @alamb @Dandandan ! Yeah, I will take some time later to move the test to the tpch crate and add tests for the other TPCH queries.

**Comment by viirya** [comment]
BTW, does the tpch crate mean the benchmarks? Otherwise I don't find a tpch crate here.

**Review by Dandandan — APPROVED** [review]
