### PR TITLE
Short-circuit evaluation for `CaseWhen`

### LINKED ISSUE #2064: DivideByZero for CaseWhen
`CASE WHEN a > 0 THEN 25.0 / cast(a, float64) ELSE float64(null) END` will fail with error: `ArrowError(DivideByZero)`, since we are computing `25 div a` without checking the `when` condition.

To reproduce
```rust
#[test]
    fn case_without_expr1() -> Result<()> {
        let batch = case_test_batch1()?;
        let schema = batch.schema();

        // CASE WHEN a > 0 THEN 25.0 / cast(a, float64) ELSE float64(null) END
        let when1 = binary(
            col("a", &schema)?,
            Operator::Gt,
            lit(ScalarValue::Int32(Some(0))),
            &batch.schema(),
        )?;
        let then1 = binary(
            lit(ScalarValue::Float64(Some(25.0))),
            Operator::Divide,
            cast(col("a", &schema)?, &batch.schema(), Float64)?,
            &batch.schema(),
        )?;
        let x = lit(ScalarValue::Float64(None));

        let expr = case(None, &[(when1, then1)], Some(x))?;
        let result = expr.evaluate(&batch)?.into_array(batch.num_rows());
        let result = result
            .as_any()
            .downcast_ref::<Float64Array>()
            .expect("failed to downcast to Int32Array");

        let expected = &Float64Array::from(vec![Some(25.0), None, None, Some(5.0)]);

        assert_eq!(expected, result);

        Ok(())
    }

    fn case_test_batch1() -> Result<RecordBatch> {
        let schema = Schema::new(vec![Field::new("a", DataType::Int32, true)]);
        let a = Int32Array::from(vec![Some(1), Some(0), None, Some(5)]);
        let batch = RecordBatch::try_new(Arc::new(schema), vec![Arc::new(a)])?;
        Ok(batch)
    }
```

The [cause](https://github.com/apache/arrow-datafusion/blob/master/datafusion-physical-expr/src/expressions/case.rs#L344) of the problem:

```rust
for i in (0..self.when_then_expr.len()).rev() {
            let i = i as usize;

            let when_value = self.when_then_expr[i].0.evaluate(batch)?;
            let when_value = when_value.into_array(batch.num_rows());

            let then_value = self.when_then_expr[i].1.evaluate(batch)?;     // <------------
            let then_value = then_value.into_array(batch.num_rows());
```

We are not checking the "selection vector" generated by the `when clause` to evaluate `then clause`.

A possible solution with minimum changes from arrow kernel computations might be:
```rust
pub trait PhysicalExpr: Send + Sync + Display + Debug {
......
.....
    /// Evaluate an expression against a RecordBatch with validity array
    fn evaluate_selection(&self, batch: &RecordBatch, selection: &BooleanArray) -> Result<ColumnarValue> {
        let valid_batch = take_all_valid(batch, &selection);
        let tmp = self.evaluate(&valid_batch)?;
        Ok(scatter(tmp, &selection))
    }
}
```

### PR DESCRIPTION
**Pull request by yjshen**
# Which issue does this PR close?

Closes #2064.

 # Rationale for this change

As reported by #2064, we are currently evaluating `then expr` and `else expr` for all tuples, regardless a tuple might already fail the `when expr` already.

# What changes are included in this PR?

Evaluate expressions sequentially as they appear in CaseWhen, short-circuit when possible.

# Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion-physical-expr/src/expressions/case.rs [hunk 1]
```diff
@@ -523,6 +528,39 @@ mod tests {
         Ok(())
     }
 
+    #[test]
+    fn case_with_expr_divide_by_zero() -> Result<()> {
+        let batch = case_test_batch1()?;
+        let schema = batch.schema();
+
+        // CASE a when 0 THEN float64(null) ELSE 25.0 / cast(a, float64)  END
+        let when1 = lit(ScalarValue::Int32(Some(0)));
```
Comment (yjshen) [inline datafusion-physical-expr/src/expressions/case.rs:537]: This test would fail since we are currently evaluating `else` first for `CASE expr WHEN value THEN result ELSE result END`, regardless of whether the when branches are entered.

Comment (yjshen) [reply datafusion-physical-expr/src/expressions/case.rs:537]: Currently, we are evaluating `case_when` from the end to the beginning. This is problematic since **short-circuit evaluation** is adopted by most engines, including PostgreSQL, Oracle, and SQL Server. Therefore, chances are users would express computation logic that would fail in later `when_thens` for tuples that **should have been** computed and bypassed.

Comment (doki23) [reply datafusion-physical-expr/src/expressions/case.rs:537]: We can evaluate `case_when` from beginning to the end and use evaluate_selection for the when_expr so that we can omit the following computation of when expr of the record which when_expr is already true.

File: datafusion-physical-expr/src/expressions/case.rs [hunk 2]
```diff
@@ -323,24 +323,19 @@ impl CaseExpr {
...
+        let mut current_value = new_null_array(&return_type, batch.num_rows());
+        // We only consider non-null values while comparing with whens
+        let mut remainder = not(&base_nulls)?;
+        for i in 0..self.when_then_expr.len() {
             let i = i as usize;
 
-            let when_value = self.when_then_expr[i].0.evaluate(batch)?;
+            let when_value = self.when_then_expr[i]
+                .0
+                .evaluate_selection(batch, &remainder)?;
```
Comment (doki23) [inline datafusion-physical-expr/src/expressions/case.rs:337]: 👍 Great! It's short-circuit now.

File: datafusion-physical-expr/src/physical_expr.rs [hunk 3]
```diff
@@ -38,4 +43,74 @@ pub trait PhysicalExpr: Send + Sync + Display + Debug {
     fn nullable(&self, input_schema: &Schema) -> Result<bool>;
     /// Evaluate an expression against a RecordBatch
     fn evaluate(&self, batch: &RecordBatch) -> Result<ColumnarValue>;
+    /// Evaluate an expression against a RecordBatch with validity array
```
Comment (alamb) [inline datafusion-physical-expr/src/physical_expr.rs:46]:
```suggestion
    /// Evaluate an expression against a RecordBatch after first applying a
    /// validity array
```

File: datafusion-physical-expr/src/physical_expr.rs [hunk 4]
```diff
@@ -38,4 +43,74 @@ pub trait PhysicalExpr: Send + Sync + Display + Debug {
...
+/// Scatter `truthy` array by boolean mask. When the mask evaluates `true`, next values of `truthy`
+/// are taken, when the mask evaluates `false` values null values are filled.
+///
+/// # Arguments
+/// * `mask` - Boolean values used to determine where to put the `truthy` values
+/// * `truthy` - All values of this array are to scatter according to `mask` into final result.
+fn scatter(mask: &BooleanArray, truthy: &dyn Array) -> Result<ArrayRef> {
+    let truthy = truthy.data();
+
+    let mut mutable = MutableArrayData::new(vec![&*truthy], true, mask.len());
```
Comment (alamb) [inline datafusion-physical-expr/src/physical_expr.rs:88]: I am probably missing something here but this code looks like it always creates `BooleanArrays` even when `truthy` is some other type -- in the case examples you have, the resulting expression is always boolean, but I wonder if this is always the case

Perhaps it is worth an `assert!` that `truthy.data_type() == DataType::Boolean`?

Even better would be some unit tests showing how scatter worked (for boolean and non boolean arrays)

**Review by alamb — APPROVED** [review]
Looks good to me -- I had some questions about `scatter` but otherwise looks great

**Review by doki23 — APPROVED** [review]
LGTM

File: datafusion-physical-expr/src/physical_expr.rs (hunk 4 above)
Comment (yjshen) [reply datafusion-physical-expr/src/physical_expr.rs:89]: It's extending with `mutable.extend(0, true_pos, true_pos + len);` array from index 0 (the only truthy array), so the result is of the same type with truthy.

File: datafusion-physical-expr/src/physical_expr.rs [hunk 5]
```diff
@@ -38,4 +43,74 @@ pub trait PhysicalExpr: Send + Sync + Display + Debug {
...
+        batch: &RecordBatch,
+        selection: &BooleanArray,
+    ) -> Result<ColumnarValue> {
+        let mut indices = vec![];
+        for (i, b) in selection.iter().enumerate() {
+            if let Some(true) = b {
+                indices.push(i as u64);
+            }
+        }
+        let indices = UInt64Array::from_iter_values(indices);
```
[the remark this answers is not in the document]
Comment (yjshen) [reply datafusion-physical-expr/src/physical_expr.rs:59]: No, I think divide kernel works correctly to deal with only valid indices. 
Are you suggesting I should create new RecordBatch by masking the current batch instead of the take-then-scatter way? Should I create bitmaps from existing ones for each array with the help of `arrow::bit_util`, or do I miss something handy?

[the remark this answers is not in the document]
Comment (alamb) [reply datafusion-physical-expr/src/physical_expr.rs:63]: I was just thinking it might be possible to do something like the following psuedo code:

```rust
let mask = and(old_array.null_mask(), selection);
let new_array = old_array.replace_null_mask(mask);
let result = compute_expr(new_array);
```

And skip having to scatter / gather

However, given this code works and is covered  by tests maybe we cn revisit the approach if there is some performance or correctness issue in the future

**Review by alamb — APPROVED** [review]
Thanks again @yjshen

**Comment by alamb** [comment]
Thanks @doki23 for the review
