### PR TITLE
fix: from_plan shouldn't use original schema

### LINKED ISSUE #6613: `from_plan` shouldn't create projection by using original schema
### Describe the bug

#5821 #6596 is caused by this problem.

In original code, project call `from_plan`, it will keep original schema even if expression are different.
It's wrong! Because different expression will have different schema.

code is wrong
```rust
        LogicalPlan::Projection(Projection { schema, .. }) => {
            Ok(LogicalPlan::Projection(Projection::try_new_with_schema(
                expr.to_vec(),
                Arc::new(inputs[0].clone()),
                schema. Clone(),
            )?))
        }
```
should be
```rust
        LogicalPlan::Projection(_) => Ok(LogicalPlan::Projection(Projection::try_new(
            expr.to_vec(),
            Arc::new(inputs[0].clone()),
        )?)),
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

part of #6596.
Closes #6613 

# Rationale for this change

# What changes are included in this PR?

In original code, `project` call `from_plan`, it will keep original schema even if expression are different.
It's wrong! Because different expression will have different schema. So I correct it.

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/expr/src/utils.rs [hunk 1]
```diff
@@ -730,13 +730,10 @@ pub fn from_plan(
     inputs: &[LogicalPlan],
 ) -> Result<LogicalPlan> {
     match plan {
-        LogicalPlan::Projection(Projection { schema, .. }) => {
-            Ok(LogicalPlan::Projection(Projection::try_new_with_schema(
-                expr.to_vec(),
-                Arc::new(inputs[0].clone()),
-                schema.clone(),
-            )?))
-        }
```
Comment (jackwener) [inline datafusion/expr/src/utils.rs:739]: Here exist a bug, we shouldn't use original `schema`, because it can be changed.
Original code hidden some BUG.

**Comment by jackwener** [comment]
this PR wait #6599

File: datafusion/core/tests/sql/group_by.rs [hunk 2]
```diff
@@ -18,6 +18,8 @@
 use super::*;
 
 #[tokio::test]
+#[ignore]
+// TODO: issue: https://github.com/apache/arrow-datafusion/issues/6623
```
Comment (alamb) [inline datafusion/core/tests/sql/group_by.rs:22]: Here is a proposed fix: https://github.com/apache/arrow-datafusion/pull/6632

File: datafusion/core/tests/sqllogictests/test_files/array.slt [hunk 3]
```diff
@@ -110,10 +111,10 @@ select array_position(['h', 'e', 'l', 'l', 'o'], 'l', 4), array_position([1, 2,
 4 5 2
 
 # array_positions scalar function
-query III
+query error DataFusion error: SQL error: ParserError\("Expected an SQL statement, found: caused"\)
```
Comment (alamb) [inline datafusion/core/tests/sqllogictests/test_files/array.slt:114]: these errors look not quite right -- I think there is something wrong with sqllogictest `--complete` with multi-line errors 🤔

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 4]
```diff
@@ -206,7 +206,16 @@ impl<'a> TreeNodeRewriter for ConstEvaluator<'a> {
 
     fn mutate(&mut self, expr: Expr) -> Result<Expr> {
         match self.can_evaluate.pop() {
-            Some(true) => Ok(Expr::Literal(self.evaluate_to_scalar(expr)?)),
+            Some(true) => {
+                // After simplifying the expression, data_type may change, so we need to cast it.
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:210]: This seems wrong to me -- the type of the expression should always be the same before/after simplification. If it isn't the same that is a bug (perhaps we could raise an internal error here?)

**Review by alamb — COMMENTED** [review]
Thank you @jackwener  -- this PR is definitely heading in the right direction. Fixing the projection schema is definitely exposing a bunch of bugs.

There are a few things that don't look right in the PR that I commented on.

Thanks again for trying to make things better. It is really apprecaited

File: datafusion/common/src/dfschema.rs [hunk 5]
```diff
@@ -384,8 +384,7 @@ impl DFSchema {
         let self_fields = self.fields().iter();
         let other_fields = other.fields().iter();
         self_fields.zip(other_fields).all(|(f1, f2)| {
-            f1.qualifier() == f2.qualifier()
-                && f1.name() == f2.name()
+            f1.qualified_name() == f2.qualified_name()
```
[the remark this answers is not in the document]
Comment (jackwener) [reply datafusion/common/src/dfschema.rs:387]: About this, I have a new idea on weekend. we may need an `alias_with_schema()` function that allows us to not only add alias, but also specify the schema.

Because `alias('t1.a')`, `field` is `qualifier: none, name: t1.a`, we hope `field` is `qualifier: t1, name: a`.

I think `alias_with_schema()` can achieve this goal.

File: datafusion/core/tests/sql/group_by.rs (hunk 2 above)
Comment (alamb) [reply datafusion/core/tests/sql/group_by.rs:22]: I think we have fixed the date_trunc issues now, so these workarounds should no longer be necessary

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 4 above)
Comment (jackwener) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs]: Correct it

**Review by alamb — APPROVED** [review]
Thank you @jackwener  this looks like a nice improvement to me

However, it does seem to introduce a regression in some of the array functions recently introduced by @izveigor  . The https://github.com/apache/arrow-datafusion/issues/6596#issuecomment-1582166278 comment suggests to me we need to support NULL in array, so it is a known issue but it might be good to get @izveigor 's opinion

File: datafusion/core/tests/sql/expr.rs [hunk 6]
```diff
@@ -512,15 +512,22 @@ async fn test_regex_expressions() -> Result<()> {
 
 #[tokio::test]
 async fn test_cast_expressions() -> Result<()> {
+    test_expression!("CAST('0' AS INT)", "0");
```
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/core/tests/sql/expr.rs:515]: Maybe a good follow on PR

Seems like the hope to was to move it to slt as part of https://github.com/apache/arrow-datafusion/issues/6210 but wasn't completed 🤔

**Comment by jackwener** [comment]
I prepare to merge this PR in tomorrow. I will continue doing more job.

File: datafusion/common/src/dfschema.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (jackwener) [reply datafusion/common/src/dfschema.rs:392]: related issue #6681
