### PR TITLE
Fix bug in optimizing a nested count

### LINKED ISSUE #8450: Nested count fails
### Describe the bug

Queries with a nested count (`select count(*) from (select count(*) from (select 1));`)

fail with

```
Optimizer rule 'optimize_projections' failed
caused by
Error during planning: Aggregate requires at least one grouping or aggregate expression
```

### To Reproduce

_No response_

### Expected behavior

Should return the number of rows (1)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Dandandan**
## Which issue does this PR close?

Closes #8450

### CODE REVIEW

File: datafusion/optimizer/src/optimize_projections.rs [hunk 1]
```diff
@@ -213,6 +213,16 @@ fn optimize_projections(
...
                 add_projection_on_top_if_helpful(aggregate_input, necessary_exprs, true)?;
 
+            // Aggregate always needs at least one aggregate expression.
+            // With a nested count we don't require any column as input, but still need to create a correct aggregate
+            // The aggregate may be optimized out later (select count(*) from (select count(*) from [...]) always returns 1
+            if new_aggr_expr.is_empty()
+                && new_group_bys.is_empty()
+                && !aggregate.aggr_expr.is_empty()
+            {
+                new_aggr_expr = vec![aggregate.aggr_expr[0].clone()];
```
Comment (viirya) [inline datafusion/optimizer/src/optimize_projections.rs:223]: Hmm, why only taking the agg expr at index 0? If there are multiple agg expr? Is because they are not necessary by the parent query?

**Review by viirya — APPROVED** [review]
Maybe also add one test to `sqllogictest` too?

**Review by viirya — APPROVED** [review]
