### PR TITLE
fix: `substr_index` not handling negative occurrence correctly

### LINKED ISSUE #9472: substr_index doesn't behave correctly with a negative delimiter position
### Describe the bug

The `substr_index` function only returns the expected response for the first row in a table and an incorrect result for all subsequent rows when using a negative delimiter count. It seems to use the position of the specified delimiter in the first row to process all subsequent rows. It also includes the delimiter in the returned substring, when I don't believe that it should.

### To Reproduce

Run the following query:

```sql
SELECT
  url,
  substr_index(url, '.', 1) AS subdomain,
  substr_index(url, '.', -1) AS tld
FROM
  (values ('docs.apache.com'),
          ('community.influxdata.com'),
          ('arrow.apache.org')
  ) data(url)
```

| url                      | subdomain | tld       |
|--------------------------|-----------|-----------|
| docs.influxdata.com      | docs      | .com      |
| community.influxdata.com | community | xdata.com |
| arrow.apache.org         | arrow     | e.org     |

### Expected behavior

I would expect the above query to return the following:

| url                      | subdomain | tld |
| :----------------------- | :-------- | :-- |
| docs.influxdata.com      | docs      | com |
| community.influxdata.com | community | com |
| arrow.apache.org         | arrow     | org |

### Additional context

I tested this in InfluxDB v3's implementation of DataFusion, but I believe these changes were just pulled from upstream.

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #9472.

## Rationale for this change
Example query: `select substr_index('arrow.apache.org', '.', -1)`.
Expected result is `org`, but the current result of main branch is `e.org`.
```sh
DataFusion CLI v36.0.0
❯ select substr_index('arrow.apache.org', '.', -1);
+------------------------------------------------------------+
| substr_index(Utf8("arrow.apache.org"),Utf8("."),Int64(-1)) |
+------------------------------------------------------------+
| e.org                                                      |
+------------------------------------------------------------+
1 row in set. Query took 0.006 seconds.
```

The previous test input was "www.apache.org", where "www" and "org" have the same length, which coincidentally led to the tests on negative occurrences being passed.

Background: Since this function originates from [MySQL](https://github.com/apache/arrow-datafusion/pull/8272), its behavior should remain consistent with MySQL.

## What changes are included in this PR?
Refactor the implementation of `substr_index` and fix bug.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/physical-expr/src/unicode_expressions.rs [hunk 1]
```diff
@@ -481,40 +481,28 @@ pub fn substr_index<T: OffsetSizeTrait>(args: &[ArrayRef]) -> Result<ArrayRef> {
...
-                            ) + delimiter.len() as isize)
-                                as usize;
-                            res.push_str(if idx >= string.len() {
-                                string
-                            } else {
-                                &string[idx..]
-                            });
-                        }
-                    }
+                // In MySQL, these cases will return an empty string.
```
Comment (comphead) [inline datafusion/physical-expr/src/unicode_expressions.rs:484]: I like new implementation which looks more concise to me and easier to read. 
About the MySQL comments, does that mean some cases are not the same between MySQL and Postgres?

Comment (jonahgao) [reply datafusion/physical-expr/src/unicode_expressions.rs:484]: > About the MySQL comments, does that mean some cases are not the same between MySQL and Postgres?

No, actually there is no such function in PostgreSQL. The closest one is [split_part](https://www.postgresql.org/docs/current/functions-string.html), but their functionalities are different.

File: datafusion/sqllogictest/test_files/functions.slt [hunk 2]
```diff
@@ -933,80 +933,130 @@ SELECT levenshtein(NULL, NULL)
...
+. -2 .
+. -1 (empty)
+. 1 (empty)
+. 2 .
+. 3 .
+. 100 .
+
+# Test substring_index using 'ac' as delimiter
+query TIT
+SELECT str, n, substring_index(str, 'ac', n) AS c FROM
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/functions.slt:984]: the CTE style of these tests is very nice 👌

File: datafusion/physical-expr/src/unicode_expressions.rs (hunk 1 above)
Comment (alamb) [reply datafusion/physical-expr/src/unicode_expressions.rs:484]: I tried it out here too https://www.w3schools.com/mysql/trymysql.asp?filename=trysql_func_mysql_substring_index2

And this behavior is consistent with what I observed

**Review by alamb — APPROVED** [review]
Thanks @jonahgao  -- I agree with @comphead  the code in this PR is much nicer than what is on main and the tests are very nice 

Thank you for the contribution
