### PR TITLE
Disallow SORT BY in SQL

### LINKED ISSUE #5247: SQL allows SORT BY keyword
**Describe the bug**

When using SQL, can use SORT BY keyword though it has no effect

**To Reproduce**

```sql
❯ select * from test1 sort by a;
+---+---+---+
| a | b | c |
+---+---+---+
| 1 | 2 | 3 |
| 4 | 5 | 6 |
+---+---+---+
2 rows in set. Query took 0.007 seconds.
❯ explain select * from test1 sort by a;
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                            |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: test1.a, test1.b, test1.c                                                                                                           |
|               |   TableScan: test1 projection=[a, b, c]                                                                                                         |
| physical_plan | ProjectionExec: expr=[a@0 as a, b@1 as b, c@2 as c]                                                                                             |
|               |   RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                                                                         |
|               |     CsvExec: files={1 group: [[home/jeffrey/Code/arrow-datafusion/datafusion-cli/test.csv]]}, has_header=true, limit=None, projection=[a, b, c] |
|               |                                                                                                                                                 |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set. Query took 0.004 seconds.
```

**Expected behavior**

Should raise error as invalid SQL, even though it does not affect the generated plan

**Additional context**

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #5247

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

No tests added. Adding tests for invalid SQL might not be desirable (considering potential surface area of invalid SQL)

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/sql/src/select.rs [hunk 1]
```diff
@@ -59,6 +59,9 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
         if select.top.is_some() {
             return Err(DataFusionError::NotImplemented("TOP".to_string()));
         }
+        if !select.sort_by.is_empty() {
```
Comment (alamb) [inline datafusion/sql/src/select.rs:62]: 👍 

It would be nice to add a .slt test for this case, but I also think it is ok not to

**Comment by alamb** [comment]
Here is a proposed test: https://github.com/apache/arrow-datafusion/pull/5254
