### PR TITLE
fix: Scheduler panic routing errors

### LINKED ISSUE #4096: Panic when the number of partitions of the pipeline that throws the exception is inconsistent with the number of partitions output by the query
**Describe the bug**

I am the developer of CnosDB, when we are doing integration testing, some SQL causes panic.

such as:
```sql
WITH gp AS (SELECT id FROM table1 GROUP BY id) 
SELECT
    COUNT(CAST(CAST(gp.id || '' AS TIMESTAMP) AS BIGINT)) 
FROM 
    gp;
```

**To Reproduce**

1. physical plan

```
Plan: ProjectionExec: expr=[COUNT(gp.id || Utf8(""))@0 as COUNT(gp.id || Utf8(""))]
  AggregateExec: mode=Final, gby=[], aggr=[COUNT(gp.id || Utf8(""))]
    CoalescePartitionsExec
      AggregateExec: mode=Partial, gby=[], aggr=[COUNT(gp.id || Utf8(""))]
        ProjectionExec: expr=[id@0 as id]
          AggregateExec: mode=FinalPartitioned, gby=[id@0 as id], aggr=[]
            CoalesceBatchesExec: target_batch_size=4096
              RepartitionExec: partitioning=Hash([Column { name: "id", index: 0 }], 4)
                AggregateExec: mode=Partial, gby=[id@0 as id], aggr=[]
                  RepartitionExec: partitioning=RoundRobinBatch(4)
                    MemoryExec: partitions=2, partition_sizes=[20, 20]
```

2. result

```
thread 'df-worker-1' panicked at 'index out of bounds: the len is 1 but the index is 2', datafusion/core/src/scheduler/task.rs:306:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'df-worker-2' panicked at 'index out of bounds: the len is 1 but the index is 1', datafusion/core/src/scheduler/task.rs:306:17
thread 'df-worker-3' panicked at 'index out of bounds: the len is 1 but the index is 3', datafusion/core/src/scheduler/task.rs:306:17
thread 'scheduler::tests::test_runtime_err' panicked at 'called `Result::unwrap()` on an `Err` value: ExternalError(ArrowError(ExternalError(ArrowError(CastError("Error parsing '2' as timestamp")))))', datafusion/core/src/scheduler/mod.rs:480:64
[2022-11-03T08:53:53Z ERROR datafusion::scheduler] worker 3 panicked with: index out of bounds: the len is 1 but the index is 3
[2022-11-03T08:53:53Z ERROR datafusion::scheduler] worker 2 panicked with: index out of bounds: the len is 1 but the index is 1
```

**Expected behavior**
no panic

**Additional context**

I am trying to fix this

### PR DESCRIPTION
**Pull request by yukkit**
# Which issue does this PR close?

Closes #4096 .

# Rationale for this change

The query output partition number may not equal current pipeline's output partition number, so send error to the partition of the query output will cause panic.

# What changes are included in this PR?

Because the query output has at least one partition，so we send error that thrown by non-output pipelines to the first partition of the query output.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
Until the fix for https://github.com/apache/arrow-datafusion/issues/4100 is merged, clippy will likely fail on this PR as well

File: datafusion/core/src/scheduler/task.rs [hunk 1]
```diff
@@ -108,17 +108,24 @@ impl Task {
...
-            );
-
-            self.context.pipelines[link.pipeline]
-                .pipeline
-                .close(link.child, self.waker.partition);
+        match routable.output {
+            Some(link) => {
+                // The query output partition number may not equal current pipeline's output partition number,
+                // but the query output has at least one partition，
+                // so send error to the first partition of the query output.
```
Comment (tustvold) [inline datafusion/core/src/scheduler/task.rs:115]:
```suggestion
                // The query output partitioning may not match the current pipeline's
                // but the query output has at least one partition
                // so send error to the first partition of the query output.
```

File: datafusion/core/src/scheduler/mod.rs [hunk 2]
```diff
@@ -353,8 +358,8 @@ mod tests {
             info!("Plan: {}", displayable(plan.as_ref()).indent());
 
             let stream = scheduler.schedule(plan, task).unwrap().stream();
-            let scheduled: Vec<_> = stream.try_collect().await.unwrap();
-            let expected = query.collect().await.unwrap();
+            let scheduled: Vec<_> = stream.try_collect().await.unwrap_or(vec![]);
+            let expected = query.collect().await.unwrap_or(vec![]);
```
Comment (tustvold) [inline datafusion/core/src/scheduler/mod.rs:362]:
```suggestion
            let scheduled: Vec<_> = stream.try_collect().await.unwrap_or_default();
            let expected = query.collect().await.unwrap_or_default();
```

**Review by tustvold — APPROVED** [review]
Looks good to me, thank you. Nicely done tracking this down :sweat_smile:

**Comment by tustvold** [comment]
I took the liberty of fixing the clippy lints and making a minor change to the docs so that we can get this in quickly for you, thanks again :+1:

**Comment by yukkit** [comment]
> I took the liberty of fixing the clippy lints and making a minor change to the docs so that we can get this in quickly for you, thanks again 👍

Thank you, sorry, I didn't see your reply, I just resubmitted

**Comment by tustvold** [comment]
No worries at all :+1:

FWIW it can help reviewers if you avoid rebasing reviewed PRs as reviewers can then easily see what has changed, everything then gets squashed on merge. It makes no difference on a PR this size, but thought I would mention it for future contributions :smile:

**Comment by yukkit** [comment]
> No worries at all 👍
> 
> FWIW it can help reviewers if you avoid rebasing reviewed PRs as reviewers can then easily see what has changed, everything then gets squashed on merge. It makes no difference on a PR this size, but thought I would mention it for future contributions 😄

Thanks for your pointing👍
