### PR TITLE
make AggregateStatistics return the same result whether optimizer disabled or enabled

### LINKED ISSUE #5444: Expr.alias function not work with count aggregation
**Describe the bug**
Expr.alias function not work with count aggregation,it's should be alias column name with origin column name
`datafusion_expr::count(col(f.name())).alias(f.name())
`image

physical_plan
```
ProjectionExec: expr=[7300 as COUNT(id), 7300 as COUNT(tinyint_col), 7300 as COUNT(smallint_col), 7300 as COUNT(int_col), 7300 as COUNT(bigint_col), 7300 as COUNT(float_col), 7300 as COUNT(double_col), 7300 as COUNT(date_string_col), 7300 as COUNT(string_col), 7300 as COUNT(timestamp_col), 7300 as COUNT(year), 7300 as COUNT(month)]
  EmptyExec: produce_one_row=true

```

**To Reproduce**

```

use arrow::datatypes::{DataType, Field};
use arrow::util::pretty::print_batches;
use datafusion::error::Result;
use datafusion::physical_plan::displayable;
use datafusion::prelude::{ParquetReadOptions, SessionContext};
use datafusion_expr::col;

#[tokio::test]
async fn count_test() -> Result<()> {
    let ctx = SessionContext::new();
    let testdata = datafusion::test_util::parquet_test_data();
    let filename = &format!("{testdata}/alltypes_plain.parquet");
    let df = ctx
        .read_parquet(filename, ParquetReadOptions::default())
        .await?;
    let cnt = df
        .clone()
        .aggregate(
            vec![],
            df.schema()
                .fields()
                .iter()
                .clone()
                .filter(|f| !matches!(f.data_type(), DataType::Boolean))
                // wrong result,alias column with count like "count(id)"
                .map(|f| datafusion_expr::count(col(f.name())).alias(f.name()))
                // right result,alias column with origin table name
                // .map(|f| datafusion_expr::max(col(f.name())).alias(f.name()))
                // right result,alias column with origin table name
                // .map(|f| datafusion_expr::count_distinct(col(f.name())).alias(f.name()))
                .collect::<Vec<_>>(),
        )
        .unwrap();
    print_batches(&cnt.clone().collect().await.unwrap()).expect("panic message");
    let plan = cnt.create_physical_plan().await.unwrap();
    let displayable_plan = displayable(plan.as_ref());
    let plan_string = format!("{}", displayable_plan.indent());
    println!("{}", plan_string);

    Ok(())
}


```

**Additional context**

### PR DESCRIPTION
**Pull request by jiangzhx**
# Which issue does this PR close?
Closes #5444

https://github.com/apache/arrow-datafusion/blob/eb9541380964a5fd5aa92302a82ec189c3be792e/datafusion/core/src/physical_optimizer/aggregate_statistics.rs#L191-L197

Replace col_expr name with casted_expr name. 
```
return Some((
    ScalarValue::Int64(Some((num_rows - val) as i64)),
    casted_expr.name().to_string(),
));
```

thanks for @Jefffrey suggestion.

### CODE REVIEW

**Comment by jiangzhx** [comment]
@Jefffrey hope you have time to review the code. if it's the correct way to solve the issue #5444?

**Comment by jiangzhx** [comment]
If this PR is fine, then the following test case needs to be modified.

https://github.com/apache/arrow-datafusion/blob/eb9541380964a5fd5aa92302a82ec189c3be792e/datafusion/core/tests/sql/explain_analyze.rs#L558-L582)

However, I'm not quite sure whether this test case is to test AggregateStatistics count optimize right.
or just to prove that the explain command is correct.

File: datafusion/core/tests/sql/aggregates.rs [hunk 1]
```diff
@@ -99,11 +99,11 @@ async fn aggregate_timestamps_count() -> Result<()> {
...
-        "+--------------+---------------+---------------+-------------+",
-        "| COUNT(nanos) | COUNT(micros) | COUNT(millis) | COUNT(secs) |",
-        "+--------------+---------------+---------------+-------------+",
-        "| 3            | 3             | 3             | 3           |",
-        "+--------------+---------------+---------------+-------------+",
+        "+----------------+-----------------+-----------------+---------------+",
+        "| COUNT(t.nanos) | COUNT(t.micros) | COUNT(t.millis) | COUNT(t.secs) |",
+        "+----------------+-----------------+-----------------+---------------+",
+        "| 3              | 3               | 3               | 3             |",
+        "+----------------+-----------------+-----------------+---------------+",
```
Comment (Jefffrey) [inline datafusion/core/tests/sql/aggregates.rs:106]: i feel this might be an unwanted change, since it doesn't seem intuitive to do a `select count(nanos)` and have the result be `COUNT(t.nanos)` in my opinion 🤔

especially as i believe this might be only for counts which utilize aggregate statistics rule? so regular counts would still output `COUNT(nanos)` i believe?

**Review by Jefffrey — COMMENTED** [review]
i would ask if `count(*)` is also affected, but dataframe api doesnt seem like itll support it at the moment due to https://github.com/apache/arrow-datafusion/issues/5473

but you could try apply fix to `take_optimizable_table_count` as well for future proofing?

File: datafusion/core/src/physical_optimizer/aggregate_statistics.rs [hunk 2]
```diff
@@ -189,10 +189,9 @@ fn take_optimizable_column_count(
                     ..
                 } = &col_stats[col_expr.index()]
                 {
-                    let expr = format!("COUNT({})", col_expr.name());
                     return Some((
                         ScalarValue::Int64(Some((num_rows - val) as i64)),
-                        expr,
+                        casted_expr.name().to_string(),
```
Comment (alamb) [inline datafusion/core/src/physical_optimizer/aggregate_statistics.rs:194]: I wonder if we could use https://docs.rs/datafusion/19.0.0/datafusion/prelude/enum.Expr.html#method.display_name instead of `name` here (which might also resolve any discrepancies) 🤔

Comment (jiangzhx) [reply datafusion/core/src/physical_optimizer/aggregate_statistics.rs:194]: sorry,i did not get a point.

[display_name](https://docs.rs/datafusion/19.0.0/datafusion/prelude/enum.Expr.html#method.display_name) method was define at  Expr::Column(Column) , The Column type is datafusion_common::Column

but casted_expr type is datafusion::physical_plan::expressions::Column, there is not a method call display_name

File: datafusion/core/tests/sql/aggregates.rs (hunk 1 above)
Comment (jiangzhx) [reply datafusion/core/tests/sql/aggregates.rs:106]: yes,i agree with you ,  regular counts output COUNT(nanos) will feel more intuitive.

but in the current situation, we need to ensure the output remains consistent, regardless of whether the AggregateStatistics optimizer is used or not.

at main branch, disable aggregate_statistics or enable will retrun difference resutl.
```
#[tokio::test]
async fn count_test() -> Result<()> {
    let mut ctx = SessionContext::new();
    let disable_aggregate_statistics = true;

    //disable or not,this test case should be passed
    if (disable_aggregate_statistics) {
        let with_out_aggregate_statistics = ctx
            .state()
            .physical_optimizers()
            .iter()
            .filter(|optimizer| optimizer.as_ref().name().ne("aggregate_statistics"))
            .map(|optimizer| optimizer.clone())
            .collect();
        let state = ctx
            .state()
            .with_physical_optimizer_rules(with_out_aggregate_statistics);
        ctx = SessionContext::with_state(state);
    }

    let testdata = datafusion::test_util::parquet_test_data();
    ctx.register_parquet(
        "alltypes_tiny_pages",
        &format!("{testdata}/alltypes_tiny_pages.parquet"),
        ParquetReadOptions::default(),
    )
    .await?;
    let results = ctx
        .sql("SELECT count(id), max(id), min(id) FROM alltypes_tiny_pages")
        .await?
        .collect()
        .await?;
    let expected = vec![
        "+-------------------------------+-----------------------------+-----------------------------+",
        "| COUNT(alltypes_tiny_pages.id) | MAX(alltypes_tiny_pages.id) | MIN(alltypes_tiny_pages.id) |",
        "+-------------------------------+-----------------------------+-----------------------------+",
        "| 7300                          | 7299                        | 0                           |",
        "+-------------------------------+-----------------------------+-----------------------------+",
    ];
    assert_batches_sorted_eq!(expected, &results);

    Ok(())
}

```

**Comment by jiangzhx** [comment]
> i would ask if `count(*)` is also affected, but dataframe api doesnt seem like itll support it at the moment due to #5473
> 
> but you could try apply fix to `take_optimizable_table_count` as well for future proofing?

Okay, I will try to create another PR to fix the issue #5473.

File: datafusion/core/tests/sql/aggregates.rs (hunk 1 above)
Comment (Jefffrey) [reply datafusion/core/tests/sql/aggregates.rs:106]: Ok, if they're consistent then that's good

**Comment by alamb** [comment]
I will try and review this over the next day or two

File: datafusion/core/tests/sql/aggregates.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/tests/sql/aggregates.rs:106]: I double checked that the query plan shows `t.col` if there are no statistics by using datafusion-cli not from this branch 👍 

```sql
❯ select count(a) from './datafusion/core/tests/data/example.csv' as t limit 1;
+------------+
| COUNT(t.a) |
+------------+
| 1          |
+------------+
```

**Review by alamb — APPROVED** [review]
Thank you @jiangzhx  and @Jefffrey  for the review. I double checked and everything here makes sense to me
