### PR TITLE
fix: wrong result of range function

### LINKED ISSUE #8311: The range function results in an error when step is a negative number
### Describe the bug
In the range function, if step is a negative number, since the parameter is specified as usize, step=-1 is converted to 18446744073709551614, which leads to incorrect results.
https://github.com/apache/arrow-datafusion/blob/9619f02db79c794212437415b1e6a53b44eef4c9/datafusion/physical-expr/src/array_expressions.rs#L749C50-L749C51
Therefore, we need to specially handle the case where step is a negative number.

### To Reproduce

run :

`select range(1, 10, -2)` result is `[1]`

As a comparison:
duckdb 
image{width=40px height=30px}

clickhouse
image

### Expected behavior

result is `[]`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by smallzhongfeng**
## Which issue does this PR close?

Closes #8311.

## Rationale for this change
When step is a negative number, the decrement calculation is performed from front to back instead of using the `step_by` method under iterator, because `step_by` stipulates that the parameter type is usize

### CODE REVIEW

**Comment by Veeupup** [comment]
thank you for fixing it!

File: datafusion/physical-expr/src/array_expressions.rs [hunk 1]
```diff
@@ -741,13 +741,22 @@ pub fn gen_range(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+        if step < 0 {
+            while stop < start {
+                values.push(start);
+                start += step;
+            }
+        } else {
+            value = (start..stop).step_by(step as usize);
+            values.extend(value.clone());
+        }
+
```
Comment (Weijun-H) [inline datafusion/physical-expr/src/array_expressions.rs:759]:
```suggestion
        if step < 0 {
            // Decreasing range
            values.extend((stop..start).rev().step_by((-step) as usize));
        } else {
            // Increasing range
            values.extend((start..stop).step_by(step as usize));
        }
```

File: datafusion/physical-expr/src/array_expressions.rs [hunk 2]
```diff
@@ -741,13 +741,22 @@ pub fn gen_range(args: &[ArrayRef]) -> Result<ArrayRef> {
     let mut offsets = vec![0];
     for (idx, stop) in stop_array.iter().enumerate() {
         let stop = stop.unwrap_or(0);
-        let start = start_array.as_ref().map(|arr| arr.value(idx)).unwrap_or(0);
+        let mut start = start_array.as_ref().map(|arr| arr.value(idx)).unwrap_or(0);
```
Comment (Weijun-H) [inline datafusion/physical-expr/src/array_expressions.rs:744]:
```suggestion
        let start = start_array.as_ref().map(|arr| arr.value(idx)).unwrap_or(0);
```

**Review by Weijun-H — COMMENTED** [review]
Thanks @smallzhongfeng  👍

File: datafusion/physical-expr/src/array_expressions.rs (hunk 1 above)
Comment (Weijun-H) [reply datafusion/physical-expr/src/array_expressions.rs:759]: Yes, and I think we should add a test case for it 👍

Comment (smallzhongfeng) [reply datafusion/physical-expr/src/array_expressions.rs]: OK, I added ut for this

Comment (Weijun-H) [reply datafusion/physical-expr/src/array_expressions.rs]: Would you mind putting the test in sqllogoictest?

Comment (smallzhongfeng) [reply datafusion/physical-expr/src/array_expressions.rs]: https://github.com/apache/arrow-datafusion/blob/b648d4e22e82989c65523e62312e1995a1543888/datafusion/sqllogictest/test_files/array.slt#L2748C1-L2752C23
I think there is currently this test, but the results were wrong before, and I have corrected them.

File: datafusion/sqllogictest/test_files/array.slt [hunk 3]
```diff
@@ -2752,7 +2752,7 @@ select range(5),
        range(1, -5, 1)
 ;
```
Comment (Weijun-H) [inline datafusion/sqllogictest/test_files/array.slt:2753]:
```suggestion
       range(1, -5, -1)
;
```

Comment (Weijun-H) [reply datafusion/sqllogictest/test_files/array.slt:2753]: move the test to the sqllogistest, overall LGTM 👍

Comment (smallzhongfeng) [reply datafusion/sqllogictest/test_files/array.slt:2754]: Updated~

File: datafusion/physical-expr/src/array_expressions.rs [hunk 4]
```diff
@@ -2514,6 +2520,67 @@ mod tests {
             .is_null(0));
     }
 
+    #[test]
+    fn test_array_range() {
```
Comment (jayzhan211) [inline datafusion/physical-expr/src/array_expressions.rs:2524]: remove test here

Comment (alamb) [reply datafusion/physical-expr/src/array_expressions.rs:2524]: @jayzhan211  and @Weijun-H  I think what is happening is that people follow the model of the existing code -- so as long as there are tests in array_expressions (rather than .slt) that is what people will model.

What do you think about migrating (as part of another PR) all the existing tests to sqllogictests -- this would likely result in all subsequent PRs following the sqllogictests model

**Review by alamb — APPROVED** [review]
Thank you @smallzhongfeng  and @Weijun-H  and @jayzhan211  for the reviews

File: datafusion/physical-expr/src/array_expressions.rs (hunk 4 above)
Comment (Weijun-H) [reply datafusion/physical-expr/src/array_expressions.rs:2524]: I endorse this proposal as it promises to enhance convenience in directing individuals to incorporate new tests, thereby minimizing potential misunderstandings.

Comment (jayzhan211) [reply datafusion/physical-expr/src/array_expressions.rs:2524]: @alamb @Weijun-H 
There is one problem actually, function like `align_array_dimensions` we have a unit test for it but it is not possible to port to slt file. We should either not test it directly but rely on array function test that call it or port it to datafusion::common::utils, and test it there. I think the latter is better so we can check the coverage more easily.

btw, should we introduce array_utils in common. I think it will grow larger and larger quickly.
