### PR TITLE
fix: reading from partitioned `json` & `arrow` tables

### LINKED ISSUE #7686: NDJsonExec doesn't properly apply predicates on partitioned tables.
### Describe the bug

Performing a SQL query against a NDJson with partition columns will fail when filtering on any of the partition columns with the following error. In this case my partition column is a timestamp but it holds for other types as well.

> ArrowError(JsonError("Encountered unmasked nulls in non-nullable StructArray child: Field { name: \"hourly_timestamp\", data_type: Timestamp(Second, None), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }"))

It correctly prunes the files however, it doesn't populate the partition predicate correctly. This is in contrast to the ParquetExec which adds an extra predicate to populate the partition column.

> JsonExec: file_groups={1 group: [[Users/taylorbeever/git/theelderbeever/df-test/data/ndjson/hourly_timestamp=2023-09-25T20:00:00/data.ndjson]]}, projection=[id, timestamp, value, hourly_timestamp]

> ParquetExec: file_groups={1 group: [[Users/taylorbeever/git/theelderbeever/df-test/data/parquet/hourly_timestamp=2023-09-25T20:00:00/data.zstd.parquet]]}, projection=[id, timestamp, value, hourly_timestamp], predicate=hourly_timestamp@3 = 1695672000

Attempted solutions - all fail:
- Add partition columns to each json file.
- Define the Schema for the table
- Other datatypes for partition

### To Reproduce

I created an example repo [here](https://github.com/theelderbeever/datafusion-ndjson-issue).

Example data is included in the repo. All code is contained in `src/main.rs`. The parquet files are identical data to ndjson files.  They do not contain a column for the partition column as written.

To run:

First the parquet one which will succeed.
```console
RUST_LOG=debug cargo run -- parquet
```

Then the ndjson which will fail.
```console
RUST_LOG=debug cargo run -- ndjson
```

### Expected behavior

Partitioned table reads shouldn't fail when filtering on a partition column.

Additionally, the default file_extension for `NDJsonReadOptions` is `.json` which is a little misleading. Its should be one of `.ndjson` or `.jsonl`.

### Additional context

_No response_

### LINKED ISSUE #7816: Error When Querying Partitioned JSON Table
### Describe the bug

I am seeing the following error when attempting to query a table of hive style partitioned JSON files via `datafusion-cli`:

`Arrow error: Json error: Encountered unmasked nulls in non-nullable StructArray child: Field { name: "a", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }`

### To Reproduce

I have a table with the following directory structure:

```bash
dev@dev:~/arrow-datafusion/test_table$ ls -lhR
.:
total 12K
drwxrwxr-x 2 dev dev 4.0K Oct 12 17:35 'a=2'
drwxrwxr-x 2 dev dev 4.0K Oct 12 17:35 'a=4'
drwxrwxr-x 2 dev dev 4.0K Oct 12 17:35 'a=6'

'./a=2':
total 4.0K
-rw-rw-r-- 1 dev dev 20 Oct 12 17:35 tn0Sfag4abaDm6i2.json

'./a=4':
total 4.0K
-rw-rw-r-- 1 dev dev 20 Oct 12 17:35 tn0Sfag4abaDm6i2.json

'./a=6':
total 4.0K
-rw-rw-r-- 1 dev dev 20 Oct 12 17:35 tn0Sfag4abaDm6i2.json
```

And the JSON files look like:
```bash
dev@dev:~/arrow-datafusion/test_table$ cat a\=2/tn0Sfag4abaDm6i2.json 
{"b":"1"}
{"b":"1"}
```

Attempting to query like the following fails:
```bash
dev@dev:~/arrow-datafusion$ datafusion-cli
DataFusion CLI v32.0.0
❯ CREATE EXTERNAL TABLE
json_test(a string, b string)
STORED AS json
LOCATION './test_table'
PARTITIONED BY (a);
0 rows in set. Query took 0.001 seconds.

❯ select * from json_test;
Arrow error: Json error: Encountered unmasked nulls in non-nullable StructArray child: Field { name: "a", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }
❯ 
```

Querying without the partitions defined works as expected:
```bash
dev@dev:~/arrow-datafusion$ datafusion-cli
DataFusion CLI v32.0.0
❯ CREATE EXTERNAL TABLE
json_test(b string)
STORED AS json
LOCATION './test_table';
0 rows in set. Query took 0.001 seconds.

❯ select * from json_test;
+---+
| b |
+---+
| 3 |
| 3 |
| 1 |
| 1 |
| 5 |
| 5 |
+---+
6 rows in set. Query took 0.002 seconds.
```

The exact same table structure DDL works for CSV and parquet files, but not JSON.

### Expected behavior

The above json query should work.

### Additional context

I discovered this while working on https://github.com/apache/arrow-datafusion/pull/7801/files#diff-0580d65ff5db0c78c1fa4cf693f2567e7d2394923412687560614836401c223f, and there are additional relevant tests in this PR.

### PR DESCRIPTION
**Pull request by korowa**
## Which issue does this PR close?

Closes #7686.
Closes #7816.

## Rationale for this change

Fix failures on reading partition column from partitioned JSON table, caused by passing `FileScanConfig::project()` result schema to `JsonOpener` -- this function returns union of file columns and partition columns (which are not present in JSON, so they can be read as NULLs)

Similar for ARROW format -- partition columns passed to file reader, which attempts to read them.

## What changes are included in this PR?

- `FileScanConfig::projected_file_schema` -- returns schema containing intersection of fields from `file_schema` and `projection`, and acts like `project` function with partition columns filtering
- `NdJsonExec` uses `FileScanConfig::projected_file_schema` result for creating file reader.
- `ArrowExec` now uses `file_column_projection_indices` result for building file reader (intersection of file columns and scan projection columns)

## Are these changes tested?

Unit tests for `FileScanConfig` & sqllogictests

## Are there any user-facing changes?

Should fix reading from partitioned JSON  & ARROW tables.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @korowa . Looks very nice 🙏 

@devinjdangelo  any chance you have some time to look at this one?

File: datafusion/core/src/datasource/physical_plan/file_scan_config.rs [hunk 1]
```diff
@@ -157,6 +157,22 @@ impl FileScanConfig {
         })
     }
 
+    /// Projects only file schema, ignoring partition columns
+    pub(crate) fn projected_file_schema(&self) -> SchemaRef {
```
Comment (devinjdangelo) [inline datafusion/core/src/datasource/physical_plan/file_scan_config.rs:161]: This method looks good, but it would be nice if we could leverage `file_column_projection_indices` (which CsvOpener uses) so we aren't duplicating the logic to exclude the partition columns. 

I think in general we could make Csv, Json, and Arrow file opening / configuring more consistent. We can cut follow on tickets for this.

File: datafusion/sqllogictest/test_files/ddl.slt [hunk 2]
```diff
@@ -490,20 +490,28 @@ DROP TABLE csv_with_timestamps
 
 statement ok
 CREATE EXTERNAL TABLE csv_with_timestamps (
-  name VARCHAR,
-  ts TIMESTAMP,
   c_date DATE,
+  name VARCHAR,
```
Comment (devinjdangelo) [inline datafusion/sqllogictest/test_files/ddl.slt:494]: Are the changes to this test related / required? I think it would be better to leave this test as-is and add a new one if required so we can validate that we haven't inadvertently changed how CSV partitioned tables are read.

File: datafusion/sqllogictest/test_files/insert_to_external.slt [hunk 3]
```diff
@@ -195,9 +195,15 @@ INSERT INTO partitioned_insert_test_json values (1, 2), (3, 4), (5, 6), (1, 2),
 ----
 6
 
-# Issue open for this error: https://github.com/apache/arrow-datafusion/issues/7816
-query error DataFusion error: Arrow error: Json error: Encountered unmasked nulls in non\-nullable StructArray child: Field \{ name: "a", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: \{\} \}
+query TT
 select * from partitioned_insert_test_json order by a,b
```
Comment (devinjdangelo) [inline datafusion/sqllogictest/test_files/insert_to_external.slt:199]: :partying_face:

**Review by devinjdangelo — APPROVED** [review]
Thank you for digging into this @korowa! The changes are clear, well tested, and fixed the issue with reading partitioned JSON files.

A quick test locally verifies this as well:

```bash
DataFusion CLI v36.0.0
❯ COPY (values (1, 'a', 'x'), (2, 'b', 'y'), (3, 'c', 'z')) TO 'test_files/scratch/copy/partitioned_table2/' 
(format json, partition_by 'column2, column3');
+-------+
| count |
+-------+
| 3     |
+-------+
1 row in set. Query took 0.030 seconds.

❯ CREATE EXTERNAL TABLE validate_partitioned STORED AS JSON 
LOCATION 'test_files/scratch/copy/partitioned_table2/' PARTITIONED BY (column2, column3);
0 rows in set. Query took 0.001 seconds.

❯ select * from validate_partitioned;
+---------+---------+---------+
| column1 | column2 | column3 |
+---------+---------+---------+
| 1       | a       | x       |
| 3       | c       | z       |
| 2       | b       | y       |
+---------+---------+---------+
3 rows in set. Query took 0.002 seconds.
```
I noticed some inconsistencies between how schema projection information is passed into `JsonOpener`, `CsvOpener`, and `ArrowOpener` which I think would be good to clean up so we aren't duplicating logic unnecessarily. I also think we will be able to fix the errors when trying read partitioned Arrow IPC file tables very similarly to the fix for JSON in this PR. I can cut a follow on issue or two for this after we merge this PR.

Thanks again :pray:

File: datafusion/core/src/datasource/physical_plan/file_scan_config.rs (hunk 1 above)
Comment (korowa) [reply datafusion/core/src/datasource/physical_plan/file_scan_config.rs:161]: Fixed -- now this method returns schema with fields collected from iteration over `file_column_projection_indices` result

File: datafusion/sqllogictest/test_files/ddl.slt (hunk 2 above)
Comment (korowa) [reply datafusion/sqllogictest/test_files/ddl.slt]: I've just got a bit confusing result for JSON table and decided to also pin it in a test for CSV -- you're correct it's unrelated, and I'll better check for / file an issue regarding it. For now I've removed modifications for this file.

**Comment by korowa** [comment]
> I also think we will be able to fix the errors when trying read partitioned Arrow IPC file tables very similarly to the fix for JSON in this PR.

@devinjdangelo , thank you for pointing it out -- it's the same issue (even .arrow tests in `insert_to_external.slt` references same issue). I've added another commit with fix for .arrow format and sqllogictests coverage for it.

File: datafusion/sqllogictest/test_files/ddl.slt (hunk 2 above)
Comment (devinjdangelo) [reply datafusion/sqllogictest/test_files/ddl.slt]: Definitely feel free to file an issue if you came across an unrelated problem or something confusing where we could improve documentation.

File: datafusion/sqllogictest/test_files/insert_to_external.slt [hunk 4]
```diff
@@ -99,9 +99,11 @@ select * from dictionary_encoded_arrow_test_readback;
 ----
 b
 
-# https://github.com/apache/arrow-datafusion/issues/7816
-query error DataFusion error: Arrow error: Schema error: project index 1 out of bounds, max field 1
```
Comment (devinjdangelo) [inline datafusion/sqllogictest/test_files/insert_to_external.slt:103]: Very nice! Glad to see the fix was essentially the same for arrow files.

**Review by devinjdangelo — COMMENTED** [review]
Thanks again @korowa! Glad to see both JSON and arrow partitioned table reads working correctly now :rocket: 

```bash
DataFusion CLI v36.0.0
❯ COPY (values (1, 'a', 'x'), (2, 'b', 'y'), (3, 'c', 'z')) TO 'test_files/scratch/copy/partitioned_table/' 
(format arrow, partition_by 'column2, column3');
+-------+
| count |
+-------+
| 3     |
+-------+
1 row in set. Query took 0.022 seconds.
❯ CREATE EXTERNAL TABLE validate_partitioned_arrow STORED AS arrow 
LOCATION 'test_files/scratch/copy/partitioned_table/' PARTITIONED BY (column2, column3);
0 rows in set. Query took 0.001 seconds.
❯ select * from validate_partitioned_arrow;
+---------+---------+---------+
| column1 | column2 | column3 |
+---------+---------+---------+
| 1       | a       | x       |
| 2       | b       | y       |
| 3       | c       | z       |
+---------+---------+---------+
3 rows in set. Query took 0.001 seconds.
```

**Review by alamb — APPROVED** [review]
Thank you @korowa  and @devinjdangelo  for the review. A very nice improvement. 🏆
