### PR TITLE
Return plan error when adding utf8 and timestamp

### LINKED ISSUE #5650: `timestamp` - interval results in `The type of Timestamp(Nanosecond, Some("+00:00")) Minus Utf8 of binary physical should be same`
**Describe the bug**
I ran a query and got an internal error

**To Reproduce**
Using `datafusion-cli`:

```sql
❯ create table foo(x timestamp) as select '2023-03-01'::timestamp;
0 rows in set. Query took 0.002 seconds.
❯ select * from foo;
+---------------------+
| x                   |
+---------------------+
| 2023-03-01T00:00:00 |
+---------------------+
1 row in set. Query took 0.001 seconds.
❯ select * from foo where x < now() - '1 day';
The type of Timestamp(Nanosecond, Some("+00:00")) Minus Utf8 of binary physical should be same. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

Note it is possible to use the `interval` syntax things work out correctly

```
❯ select * from foo where x < now() - interval '1 day';
+---------------------+
| x                   |
+---------------------+
| 2023-03-01T00:00:00 |
+---------------------+
```

Note if you try to use the same predicate outside of the where clause, we get a planning error (correctly):
```
❯ select now()  - '1 day';
Error during planning: 'Timestamp(Nanosecond, Some("+00:00")) - Utf8' can't be evaluated because there isn't a common type to coerce the types to
```

**Expected behavior**
1. (minimum) `select * from foo where x < now() - '1 day';` should produce a planning error (rather than an internal error)
2. (ideal) Make the query work

**Additional context**

### PR DESCRIPTION
**Pull request by Weijun-H**
# Which issue does this PR close?

Closes #5650

# Rationale for this change

# What changes are included in this PR?
Return plan error when performing binary operations between timestamp and utf8

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/binary.rs [hunk 1]
```diff
@@ -1213,6 +1214,13 @@ pub fn binary(
 ) -> Result<Arc<dyn PhysicalExpr>> {
     let lhs_type = &lhs.data_type(input_schema)?;
     let rhs_type = &rhs.data_type(input_schema)?;
+    if (is_utf8_or_large_utf8(lhs_type) && is_timestamp(rhs_type))
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/binary.rs:1217]: Thanks @Weijun-H  -- this does indeed fix the bug as stated. 

 I was trying to figure out how this code even executes (and was not caught earlier)

It seems like maybe this could be related to

https://github.com/apache/arrow-datafusion/blob/d8925bebc1f5382b044ce80f78bc465a9145e425/datafusion/expr/src/type_coercion/binary.rs#L80-L85

🤔 

Maybe it is time to figure out a better coercion story

**Review by alamb — APPROVED** [review]
Thanks for the quick fix @Weijun-H  -- while the behavior is still not ideal I think this PR is an improvement (as the error is no longer internal) 👍 

Longer term I think we will need to improve interval arithmetic but that will be a larger project (one I hope to sketch out more later today)

File: datafusion/physical-expr/src/expressions/binary.rs (hunk 1 above)
Comment (comphead) [reply datafusion/physical-expr/src/expressions/binary.rs:1217]: +1 sometime ago we agreed to that logical planner will be a better place for coercions and coercion checks
