### PR TITLE
Convert more cross joins to inner joins (Address performance/execution plan of TPCH query 19)

### LINKED ISSUE #78: Address performance/execution plan of TPCH query 19
**Describe the bug**
TPC-H Query 19 consumes a lot of memory and takes forever in memory on a 8 core machine on SF=1 in memory (with 100%cpu usage across cores) to execute. That likely has to do with the plan misses a equi-join and turns it into a cross join.

**To Reproduce**
Run query 19, check plan and execution time.

**Expected behavior**
The query is expected to finish faster (<1s) and shouldn't need a cross join.

**Additional context**
@alamb :

In order to get Q19 to work, the optimizer needs to be clever enough to recognize that p_partkey = l_partkey which appears in each of the three clauses is a join predicate. The query shouldn't be doing a CROSS JOIN, it should be doing an INNER JOIN on p_partkey = l_partkey

Note this is Q19:

```sql
select
sum(l_extendedprice * (1 - l_discount) ) as revenue
from
lineitem,
part
where
(
p_partkey = l_partkey
and p_brand = ‘[BRAND1]’
and p_container in ( ‘SM CASE’, ‘SM BOX’, ‘SM PACK’, ‘SM PKG’)
and l_quantity >= [QUANTITY1] and l_quantity <= [QUANTITY1] + 10
and p_size between 1 and 5
and l_shipmode in (‘AIR’, ‘AIR REG’)
and l_shipinstruct = ‘DELIVER IN PERSON’
)
or
(
p_partkey = l_partkey
and p_brand = ‘[BRAND2]’
and p_container in (‘MED BAG’, ‘MED BOX’, ‘MED PKG’, ‘MED PACK’)
and l_quantity >= [QUANTITY2] and l_quantity <= [QUANTITY2] + 10
and p_size between 1 and 10
and l_shipmode in (‘AIR’, ‘AIR REG’)
and l_shipinstruct = ‘DELIVER IN PERSON’
)
or
(
p_partkey = l_partkey
and p_brand = ‘[BRAND3]’
and p_container in ( ‘LG CASE’, ‘LG BOX’, ‘LG PACK’, ‘LG PKG’)
and l_quantity >= [QUANTITY3] and l_quantity <= [QUANTITY3] + 10
and p_size between 1 and 15
and l_shipmode in (‘AIR’, ‘AIR REG’)
and l_shipinstruct = ‘DELIVER IN PERSON’
);
```

### PR DESCRIPTION
**Pull request by DhamoPS**
* Added the new optimizer rule reduce_cross_join which would convert cross joins to inner joins if the filter has the join predicates for the corresponding tables.
    * Join Predicates which are part of OR expressions of FILTER PREDICATES, were not pulled properly. Due to that, CROSS JOINs are chosen for those joins instead of innerjoin and causes query to run longer. Actually TPCH Q19 was taking more than 2000 sec in my laptop. With Fix, TPCH Q19 is taking ~3 sec.
    
# Which issue does this PR close?

-- reduce_cross_join.rs is the new optimizer rule added to pull the 
Joined predicates from Filters and convert cross_join into inner_join
-- tests/sql/subqueries.rs::added testcases for the above fix

Closes #78 
Closes https://github.com/apache/arrow-datafusion/issues/2859

 # Rationale for this change
In `[PR#3334`](https://github.com/apache/arrow-datafusion/pull/3334), I have tried to fix this issue in planner.rs. But to handle DataFrameAPI queries, we have decided to move this rule to optimizer. 

# What changes are included in this PR?
* new optimizer rule reduce_cross_join
* unit test cases for the optimizer rule
* test cases by running SQL stmts

Logs of TPCH Q19:
arrow-datafusion/target/release/tpch benchmark datafusion --iterations 3 --path ./data --format tbl --query 19 --batch-size 4096`

Running benchmarks with the following options: DataFusionBenchmarkOpt { query: 19, debug: false, iterations: 3, partitions: 2, batch_size: 4096, path: "./data", file_format: "tbl", mem_table: false, output_path: None }
Query 19 iteration 0 took 2640.2 ms and returned 1 rows
Query 19 iteration 1 took 2099.2 ms and returned 1 rows
Query 19 iteration 2 took 2199.9 ms and returned 1 rows
Query 19 avg time: 2313.08 ms

# Are there any user-facing changes?
No

### CODE REVIEW

**Comment by DhamoPS** [comment]
@andygrove or @alamb can you kick off CI please?

**Comment by avantgardnerio** [comment]
Thanks @DhamoPS ! It looks great and I appreciate the tests. I'll review in more detail tonight or tomorrow.

**Comment by avantgardnerio** [comment]
It might be important to note that master regressed in functionality: all the queries used to pass. Some were slow and only accurate to 4 decimals, but now several actually fail. Hopefully q19 isn't one of them.

**Comment by Dandandan** [comment]
> It might be important to note that master regressed in functionality: all the queries used to pass. Some were slow and only accurate to 4 decimals, but now several actually fail. Hopefully q19 isn't one of them.

I think we should think of ways of adding the tpch queries to the CI?

**Comment by alamb** [comment]
>  It might be important to note that master regressed in functionality: all the queries used to pass. Some were slow and only accurate to 4 decimals, but now several actually fail. Hopefully q19 isn't one of them.

🤔  this sounds bad -- I thought we had tests in place to catch this. Clearly we didn't have enough.

I also plan to review this PR more carefully tomorrow

**Comment by avantgardnerio** [comment]
> this sounds bad

Ah, my bad - this may be behind a flag: https://github.com/apache/arrow-datafusion/pull/3393#issue-1364925083

One man's regression is another's more strict acceptance criteria.

**Comment by avantgardnerio** [comment]
> I think we should think of ways of adding the tpch queries to the CI?

There are tests for several of them here: https://github.com/apache/arrow-datafusion/blob/5f029cc73755b6800217e370ebe0a7b5e8a6a224/datafusion/core/tests/sql/subqueries.rs#L119

**Comment by kmitchener** [comment]
@Dandandan adding verification of TPCH results to the CI would be nice. I was thinking of suggesting that once all the tests pass and we can verify results against the answers. Fixing q19 is one of the last major blockers, besides some decimal issues.

File: datafusion/core/tests/sql/subqueries.rs [hunk 1]
```diff
@@ -289,6 +289,139 @@ async fn tpch_q17_correlated() -> Result<()> {
     Ok(())
 }
 
+// Fix for issue#78 join predicates from inside of OR expr also pulled up properly.
+#[tokio::test]
+async fn tpch_q19_pull_predicates_to_innerjoin() -> Result<()> {
```
Comment (xudong963) [inline datafusion/core/tests/sql/subqueries.rs:294]: Why add the test in the `tests/sql/subqueries.rs` file?

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 2]
```diff
@@ -0,0 +1,442 @@
...
+        reduce_cross_join(self, plan, &mut possible_join_keys, &mut all_join_keys, optimizer_config)
+    }
+
+    fn name(&self) -> &str {
+        "reduce_cross_join"
+    }
+}
+
+/// Attempt to reduce cross joins to inner joins.
+/// for queries: select ... from a, b where a.x = b.y and b.xx = 100;
```
Comment (xudong963) [inline datafusion/optimizer/src/reduce_cross_join.rs:61]: It'll be clearer to highlight those sqls by ``.

**Review by xudong963 — COMMENTED** [review]
If we have the rule in the optimizer, I think the logic of `cross join -> inner join` in planner can be deleted https://github.com/apache/arrow-datafusion/blob/master/datafusion/sql/src/planner.rs#L631. (It's ok to do it in the next ticket).

File: datafusion/core/tests/sql/subqueries.rs (hunk 1 above)
Comment (DhamoPS) [reply datafusion/core/tests/sql/subqueries.rs:294]: Other TPCH Queries related testcases are in subqueries.rs and so I have added this test also here.

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 2 above)
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:61]: ok

File: datafusion/core/tests/sql/subqueries.rs (hunk 1 above)
Comment (xudong963) [reply datafusion/core/tests/sql/subqueries.rs:294]: In fact, tests in `subqueries.rs` are correlated subqueries(you can know by the file name directly), not all tpch queries. 

So you need to find a proper place for the test.

Comment (DhamoPS) [reply datafusion/core/tests/sql/subqueries.rs:294]: Ok, I move the tests to different file

File: datafusion/core/tests/sql/subqueries.rs [hunk 3]
```diff
@@ -289,6 +289,139 @@ async fn tpch_q17_correlated() -> Result<()> {
...
+    let ctx = SessionContext::new();
+
+    register_tpch_csv(&ctx, "part").await?;
+    register_tpch_csv(&ctx, "lineitem").await?;
+
+    let sql = r#"
```
Comment (avantgardnerio) [inline datafusion/core/tests/sql/subqueries.rs:300]: +1 for `r##` strings!

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 4]
```diff
@@ -0,0 +1,442 @@
...
+        assert_eq!(formatted_plan, expected);
+        assert_eq!(plan.schema(), optimized_plan.schema());
+    }
+
+    #[test]
+    fn reduce_cross_with_simple_and() -> Result<()> {
+        let t1 = test_table_scan_with_name("t1")?;
+        let t2 = test_table_scan_with_name("t2")?;
+
+        // could not reduce to inner join
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:318]: I don't understand this comment. It implies that this query cannot be optimized, but then the test goes on to assert that it has been converted to an `inner join` (which seems correct BTW).

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 5]
```diff
@@ -0,0 +1,442 @@
...
+impl OptimizerRule for ReduceCrossJoin {
+    fn optimize(
+        &self,
+        plan: &LogicalPlan,
+        optimizer_config: &mut OptimizerConfig,
+    ) -> Result<LogicalPlan> {
+        let mut possible_join_keys : Vec<(Column, Column)> = vec![];
+        let mut all_join_keys = HashSet::new();
+
+        reduce_cross_join(self, plan, &mut possible_join_keys, &mut all_join_keys, optimizer_config)
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:52]: It seems weird to pass `&self` to a non-member function when this should be able to be made a member of the struct impl itself? (I realize this is just following an existing pattern from other optimizer rules)

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 6]
```diff
@@ -0,0 +1,442 @@
...
+/// For above queries, the join predicate is available in filters and they are moved to
+/// join nodes appropriately
+/// This fix helps to improve the performance of TPCH Q19. issue#78
+///
+fn reduce_cross_join(
+    _optimizer: &ReduceCrossJoin,
+    plan: &LogicalPlan,
+    possible_join_keys: &mut Vec<(Column, Column)>,
+    all_join_keys: &mut HashSet<(Column, Column)>,
+    _optimizer_config: &OptimizerConfig,
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:74]: If this parameter is not needed, let's just remove it. This isn't part of the trait, so there is no contractual need to keep it around.

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 7]
```diff
@@ -0,0 +1,442 @@
...
+                from_plan(plan, &expr, &new_inputs)
+            }
+    }
+}
+
+fn intersect(
+    accum: &mut Vec<(Column, Column)>,
+    vec1: &[(Column, Column)],
+    vec2: &[(Column, Column)],
+) -> Result<()>  {
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:193]:
```suggestion
) -> ()  {
```

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 8]
```diff
@@ -0,0 +1,442 @@
...
+                )?;
+                // can we find a match?
+                let left_schema = left_plan.schema();
+                let right_schema = right_plan.schema();
+                let mut join_keys = vec![];
+
+                for (l, r) in possible_join_keys {
+                    if left_schema.field_from_column(l).is_ok()
+                        && right_schema.field_from_column(r).is_ok()
+                        && can_hash(
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:121]: Nice! I had no idea this function existed, and would have used it if I knew it did :)

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 9]
```diff
@@ -0,0 +1,442 @@
...
+            }
+            _ => {
+                let expr = plan.expressions();
+
+                // apply the optimization to all inputs of the plan
+                let inputs = plan.inputs();
+                let new_inputs = inputs
+                    .iter()
+                    .map(|plan| {
+                        reduce_cross_join(
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:174]: Nice work tracking down all the parts that needed to be recursive :)

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 10]
```diff
@@ -0,0 +1,442 @@
...
+
+                intersect( accum, &left_join_keys, &right_join_keys)
+            }
+            _ => Ok(()),
+        },
+        _ => Ok(()),
+    }
+}
+
+/// Remove join expressions from a filter expression
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:246]: Additional documentation about return values would help here, e.g. what do `Some()` and `None` mean in context?

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 11]
```diff
@@ -0,0 +1,442 @@
...
+            .cross_join(
+                &t2)?
+            .filter(binary_expr(
+                    col("t1.a").eq(col("t2.a")),
+                    And,
+                    col("t2.c").lt(lit(20u32)),
+                ))?
+            .build()?;
+
+        let expected = "\
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:329]: `r##` strings would be nice here.

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 12]
```diff
@@ -0,0 +1,442 @@
...
+    _optimizer: &ReduceCrossJoin,
+    plan: &LogicalPlan,
+    possible_join_keys: &mut Vec<(Column, Column)>,
+    all_join_keys: &mut HashSet<(Column, Column)>,
+    _optimizer_config: &OptimizerConfig,
+) -> Result<LogicalPlan> {
+        match plan {
+            LogicalPlan::Filter(Filter { input, predicate }) => {
+                extract_possible_join_keys(predicate, possible_join_keys)?;
+                let left = reduce_cross_join(_optimizer, input, possible_join_keys, all_join_keys, _optimizer_config)?;
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:79]: Unless I'm missing something, `left` is misleading name for this variable - this is just the resultant plan after children have been optimized? There is no right?

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 13]
```diff
@@ -0,0 +1,442 @@
...
+}
+
+impl OptimizerRule for ReduceCrossJoin {
+    fn optimize(
+        &self,
+        plan: &LogicalPlan,
+        optimizer_config: &mut OptimizerConfig,
+    ) -> Result<LogicalPlan> {
+        let mut possible_join_keys : Vec<(Column, Column)> = vec![];
+        let mut all_join_keys = HashSet::new();
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:50]: It's a little odd that these are "global", not scoped with the recursion itself, but I think due to the way they are canonicalized, this is fine? I tried to break it in a few tests and couldn't. I think it would maybe break if there are multiple joins to the same tables aliased?

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 14]
```diff
@@ -0,0 +1,442 @@
...
+                            _optimizer,
+                            plan,
+                            possible_join_keys,
+                            all_join_keys,
+                            _optimizer_config,
+                        )
+                    })
+                    .collect::<Result<Vec<_>>>()?;
+
+                from_plan(plan, &expr, &new_inputs)
```
Comment (avantgardnerio) [inline datafusion/optimizer/src/reduce_cross_join.rs:184]: Again, nice work finding these utility functions!

**Review by avantgardnerio — CHANGES_REQUESTED** [review]
@DhamoPS , nice work! I spent a few hours looking it over and trying to break it with some tests. The logic looks solid.

I gave lots of feedback, but I think the only things preventing merge (IMO) are:
- the unwraps should be replaced with proper error handling
- the functions that return a Result that is always Ok should be simplified to reduce cognitive load

File: datafusion/core/tests/sql/subqueries.rs [hunk 15]
```diff
@@ -289,6 +289,139 @@ async fn tpch_q17_correlated() -> Result<()> {
...
+            and p_brand = 'Brand#34'
+            and p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
+            and l_quantity >= 20 and l_quantity <= 20 + 10
+            and p_size between 1 and 15
+            and l_shipmode in ('AIR', 'AIR REG')
+            and l_shipinstruct = 'DELIVER IN PERSON'
+        );"#;
+
+    // assert plan
+    let plan = ctx.create_logical_plan(sql).unwrap();
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/core/tests/sql/subqueries.rs:338]: I'd suggest something like:

```
                for (l, r) in possible_join_keys {
                    let dt = match left_schema.field_from_column(l) {
                        Ok(f) => f.data_type(),
                        Err(e) => e.map_err(|e| context!("Field not found!", e))?,
                    };
                    if right_schema.field_from_column(r).is_ok() && can_hash(dt) {
                        join_keys.push((l.clone(), r.clone()));
                    } else if right_schema.field_from_column(l).is_ok() && can_hash(dt) {
                        join_keys.push((r.clone(), l.clone()));
                    }
                }
```

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 4 above)
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:318]: It was a typo. I have corrected it now.

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 5 above)
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:52]: yes, I just followed existing pattern. I hope it is fine.

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 6 above)
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:74]: Ok. removed the _optimizer_config

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 16]
```diff
@@ -0,0 +1,442 @@
...
+    }
+
+    Ok(())
+}
+
+/// Extract join keys from a WHERE clause
+fn extract_possible_join_keys(
+    expr: &Expr,
+    accum: &mut Vec<(Column, Column)>,
+) -> Result<()> {
```
[the remark this answers is not in the document]
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:212]: ok removed.

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 10 above)
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:246]: ok

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 11 above)
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:329]: ok

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 12 above)
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:79]: ok, renamed it to new_plan

File: datafusion/core/tests/sql/subqueries.rs (hunk 1 above)
Comment (avantgardnerio) [reply datafusion/core/tests/sql/subqueries.rs:294]: Perhaps we pull all the `tpch_*` queries out into a `tcph.rs` so they are easier to track.

**Review by avantgardnerio — APPROVED** [review]

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 17]
```diff
@@ -190,7 +187,7 @@ fn intersect(
     accum: &mut Vec<(Column, Column)>,
     vec1: &[(Column, Column)],
     vec2: &[(Column, Column)],
-) -> Result<()>  {
+) -> ()  {
```
Comment (alamb) [inline datafusion/optimizer/src/reduce_cross_join.rs:190]:
```suggestion
)  {
```

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 13 above)
Comment (alamb) [reply datafusion/optimizer/src/reduce_cross_join.rs:50]: I recommend adding some tests with three tables (not just 2)

**Review by alamb — COMMENTED** [review]
Thank you @DhamoPS -- I reviewed the tests carefully and they look very good 👌 I think if we add a few more showing this PR works with some more complicated `OR` predicates and with more than 2 tables it would be ready to merge. 

Thank you @avantgardnerio  for your thorough review

I went over the code a bit, and it also looks quite reasonable. I left a few comments but they are all stylistic. 

 I can't help feeling after this there are three somewhat redundant overlapping areas of the code

1. This one
2. the planner logic identified by @xudong963  in https://github.com/apache/arrow-datafusion/blob/master/datafusion/sql/src/planner.rs#L630-L681
3. The rewrite in RewriteDisjunctivePredicate

Maybe we can work as a follow on to consolidate / remove the redundancy.

All in all very nice work 👍

File: datafusion/core/src/execution/context.rs [hunk 18]
```diff
@@ -1437,6 +1438,7 @@ impl SessionState {
             Arc::new(ScalarSubqueryToJoin::new()),
             Arc::new(SubqueryFilterToJoin::new()),
             Arc::new(EliminateFilter::new()),
+            Arc::new(ReduceCrossJoin::new()),
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/core/src/execution/context.rs:1441]: @alamb having dealt with fickle ordering of optimizer rules before, I'm worried that the implementations could become quite brittle if they are reliant on ordering at all. Do you think it could eventually be a good idea to run them in a loop until no more optimization can be accomplished?

Just throwing a crazy idea out there...

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 19]
```diff
@@ -0,0 +1,452 @@
...
+                    ()
+                }
+                _ => (),
+            },
+            Operator::And => {
+                extract_possible_join_keys(left, accum);
+                extract_possible_join_keys(right, accum)
+            },
+            // Fix for issue#78 join predicates from inside of OR expr also pulled up properly.
+            Operator::Or => {
```
[the remark this answers is not in the document]
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:228]: @alamb In case of OR predicates, first we get the list of predicates from left and right child of OR. And then we do intersect() of left and right. In case of` A1=B1 OR A2=B2 `-> left would have `A1=B1` and right would have `A2=B2` and so intersect() of these two would be `{} empty`. **These predicates will not be moved up.** 
Let` (A1=B1 and A2=30) OR (A1=B1 and A2=B2 and A2=40) `-> In this example, left and right of OR predicate have common predicate `(A1=B1)` and so `A1=B1` **would be considered as Join predicate.**

[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/reduce_cross_join.rs:228]: @DhamoPS , when I reviewed your PR, I actually wrote several tests to determine what you're saying was true. But claims in English are difficult to verify, and don't leave automated artifacts for others to understand in the future. For these reasons, I think it would be good to add tests for these conditions in addition to the PR feedback.

File: datafusion/optimizer/src/reduce_cross_join.rs [hunk 20]
```diff
@@ -0,0 +1,452 @@
...
+                    col("t2.c").lt(lit(15u32)),
+                ),
+                Or,
+                binary_expr(
+                    col("t1.a").eq(col("t2.a")),
+                    Or,
+                    col("t2.c").eq(lit(688u32)),
+                )
+            ))?
+            .build()?;
```
[the remark this answers is not in the document]
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:440]: ok, I add more tests

**Comment by DhamoPS** [comment]
In predicates.rs, tpch_q19_pull_predicates_to_innerjoin_simplified() is having 3 tables test. I add one more test here as well.

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 13 above)
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:50]: Yes, these variables need not be "Global", I am changing it to scope of the filter_expr.

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/optimizer/src/reduce_cross_join.rs:228]: Yes, I agree with @avantgardnerio  -- I am fairly sure you are correct, but I would like to see a test that both removes any doubt as well as serves as protection against regression when / if this code is refactored in the future

**Comment by alamb** [comment]
To be clear, I think this PR just needs a few more tests, as discussed (and the clippy / fmt tests to be cleaned up) and it will be ready to merge

Thank you so much for your help @DhamoPS

File: datafusion/core/src/execution/context.rs (hunk 18 above)
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/core/src/execution/context.rs:1441]: I agree that a static ordering is likely to produce non optimal plans in some cases. Running in a loop until a "fixed point" is a reasonable however, then there is a danger of optimizer ping-pong (aka one optimizer pass makes a change and then the other undoes it)

File: datafusion/optimizer/tests/integration-test.rs [hunk 21]
```diff
@@ -115,6 +116,7 @@ fn test_sql(sql: &str) -> Result<LogicalPlan> {
         Arc::new(EliminateFilter::new()),
         Arc::new(CommonSubexprEliminate::new()),
         Arc::new(EliminateLimit::new()),
+        Arc::new(ReduceCrossJoin::new()),
         Arc::new(ProjectionPushDown::new()),
         Arc::new(RewriteDisjunctivePredicate::new()),
```
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/optimizer/tests/integration-test.rs:121]: https://github.com/apache/arrow-datafusion/issues/3524

File: datafusion/core/src/execution/context.rs (hunk 18 above)
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/core/src/execution/context.rs:1441]: Yes, I was struggling with that part. It would be nice if we could measure gradient descent somehow, but maybe that's not possible until we add cost functions everywhere.

[the remark this answers is not in the document]
Comment (Dandandan) [reply datafusion/core/src/execution/context.rs:1441]: Gradient descent itself is not directly possible - as that needs differentiable functions / cost functions.

But other (black box) optimization algorithms are possible given some cost function. I think the art of writing good cost functions for queries however can be quite an art 🎨

[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/core/src/execution/context.rs:1441]: > other (black box) optimization algorithms are possible

Yes, this is what I was trying to say, thank you.

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:220]: I have added more test cases which would cover more scenarios. Please review the latest changes.

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 20 above)
[the remark this answers is not in the document]
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs]: I have added this test and I have added 4 table joins with multiple Filter expr. 
With new testcases, I have found few bugs and I have fixed them now. 
The testcases are working as expected and as explained.

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 13 above)
Comment (alamb) [reply datafusion/optimizer/src/reduce_cross_join.rs:53]: It seems like this particular comment is not addressed (they are still global). However, given the test coverage I think this PR can be merged as is

**Review by alamb — APPROVED** [review]
Looks great -- thank you @DhamoPS . This is a pretty epic first contribution. 

🏅  for the tests -- I think they will pay off in avoiding tricky join bugs later on, .

**Comment by alamb** [comment]
@DhamoPS  it looks like there is a clippy failure on this PR -- once that is resolved I think we can merge this PR in

**Comment by DhamoPS** [comment]
> @DhamoPS it looks like there is a clippy failure on this PR -- once that is resolved I think we can merge this PR in

yes, I am resolving the clippy failure and Lint failure. I would commit it in couple of hours. Thanks @alamb

File: datafusion/optimizer/src/reduce_cross_join.rs (hunk 13 above)
Comment (DhamoPS) [reply datafusion/optimizer/src/reduce_cross_join.rs:53]: @alamb This is addressed inside the reduce_cross_join(). New possible_join_keys are created for each Filter expression. This would be used only on it's child. 

```
fn reduce_cross_join(
    _optimizer: &ReduceCrossJoin,
    plan: &LogicalPlan,
    possible_join_keys: &mut Vec<(Column, Column)>,
    all_join_keys: &mut HashSet<(Column, Column)>,
) -> Result<LogicalPlan> {
    match plan {
        LogicalPlan::Filter(Filter { input, predicate }) => {
            // join keys are handled locally
            let mut new_possible_join_keys: Vec<(Column, Column)> = vec![];
            let mut new_all_join_keys = HashSet::new();
            extract_possible_join_keys(predicate, &mut new_possible_join_keys);
```

**Comment by DhamoPS** [comment]
@alamb I have resolved the last clippy failure. I didn't know that I could run the clippy and lint tests locally. 
I am sorry for multiple commits. I will ensure that these tests are successful on my next PR.
Thanks a lot for your help!

**Comment by alamb** [comment]
> Thanks a lot for your help!

No problem -- thanks for sticking with it!

Your next PRs will be easier as after we have merged one, the CI checks start automatically on subsequent PRs

**Comment by DhamoPS** [comment]
@alamb Please merge this pull request to master.

**Comment by alamb** [comment]
🚀  really nice first PR -- thanks @DhamoPS !

**Comment by kmitchener** [comment]
This is great @DhamoPS! Congrats on your first merged PR :) Will you be following up with a separate PR to remove the similar code from sql/planner.rs?

**Comment by DhamoPS** [comment]
@kmitchener Thanks. Yes, I will be following up with separate PR for cleanup in sql/planner.rs.
Could you create the git issue to track it?

**Comment by kmitchener** [comment]
> @kmitchener Thanks. Yes, I will be following up with separate PR for cleanup in sql/planner.rs. Could you create the git issue to track it?

You should feel free to create an issue yourself when you're ready. I'm interested in the cleanup but I don't have any special ownership here.
