### PR TITLE
Fix output schema generated by CommonSubExprEliminate

### LINKED ISSUE #3635: after type coercion `CommonSubexprEliminate` will produce invalid projection
**Describe the bug**

after do this pr with moving the type coercion to the beginning for the optimizer, the `CommonSubexprEliminate` will generate the invalid projection

maybe like https://github.com/apache/arrow-datafusion/issues/2907

I think many of the optimizer rule didn't take care of the `cast/try_cast` for the type coercion.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by alex-natzka**
# Which issue does this PR close?
Closes #3635.

 # Rationale for this change

The optimization rule `CommonSubexprEliminate` produces a wrong output schema in many situations. If a logical plan depends on the output schema, it will simply be broken.

# What changes are included in this PR?

* In the `ExprIdentifierVisitor`, which is used to determine the datatype of every sub-expression, the datatype is now determined based on the schema of the logical plan _for every sub-expression individually_ instead of determining the datatype of the _overall expression_ and wrongly assigning it to every sub-expression.
* The `ExprIdentifierVisitor` now, accordingly, does not have a `datatype` attribute but, instead, `input_schema` and `all_schemas`.
  The latter is necessary for a fall-back logic, where if the datatype of a sub-expression cannot be determined using the input schema, we merge the schemas from all nodes of the overall logical plan and try again.
* A test is added to verify the correct datatype of the schema post optimization in the case of optimizing a `Filter` logical plan.

# Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 1]
```diff
@@ -448,7 +474,21 @@ impl ExpressionVisitor for ExprIdentifierVisitor<'_> {
...
+            // expression type could not be resolved in schema, fall back to all schemas
+            let merged_schema =
+                self.all_schemas
+                    .iter()
+                    .fold(DFSchema::empty(), |mut lhs, rhs| {
+                        lhs.merge(rhs);
+                        lhs
+                    });
+            expr.get_type(&merged_schema)?
+        };
```
Comment (alex-natzka) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:490]: I am honestly unsure if this fall-back logic is necessary at all since the (sub-expression) data types should be resolvable just from the input schema to the respective logical plan node.

However, I did not want to break anything since this fall-back logic was already in place.

All tests pass with and without the fall-back logic.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 2]
```diff
@@ -796,4 +853,55 @@ mod test {
...
+        let fields_with_datatypes: Vec<_> = schema
+            .fields()
+            .iter()
+            .map(|field| (field.name(), field.data_type()))
+            .collect();
+        let formatted_fields_with_datatype = format!("{fields_with_datatypes:#?}");
+        let expected = r###"[
+    (
+        "CAST(table.a AS Int64)table.a",
+        Int64,
```
Comment (alex-natzka) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:890]: This used to be just `Boolean` before the fix.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 3]
```diff
@@ -370,7 +391,12 @@ struct ExprIdentifierVisitor<'a> {
     expr_set: &'a mut ExprSet,
     /// series number (usize) and identifier.
     id_array: &'a mut Vec<(usize, Identifier)>,
-    data_type: DataType,
+    /// input schema for the node that we're optimizing, so we can determine the correct datatype
+    /// for each subexpression
+    input_schema: DFSchemaRef,
+    /// all schemas in the logical plan, as a fall back if we cannot resolve an expression type
+    /// from the input schema alone
+    all_schemas: Vec<DFSchemaRef>,
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:399]: I don't understand in what cases we wouldn't be able to resolve an expr type from the input schema alone.

The only case I can think of is when the plan node has more than one input (e.g. a Join or a Union) -- but thus I would expect that we always resolve the type of the expressions using the input schema

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 4]
```diff
@@ -448,7 +474,21 @@ impl ExpressionVisitor for ExprIdentifierVisitor<'_> {
...
+            data_type
+        } else {
+            // expression type could not be resolved in schema, fall back to all schemas
+            let merged_schema =
+                self.all_schemas
+                    .iter()
+                    .fold(DFSchema::empty(), |mut lhs, rhs| {
+                        lhs.merge(rhs);
+                        lhs
+                    });
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:488]: I wonder if we could use `reduce` here (I realize you just refactored this code)
```suggestion
            let merged_schema =
                self.all_schemas
                    .iter()
                    .reduce(|mut lhs, rhs| {
                        lhs.merge(rhs);
                        lhs
                    });
```

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 1 above)
Comment (alamb) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:490]: I think all exprs should be resolvable with the unified schemas, as explained above -- but maybe it is a performance optimization 🤔.

Perhaps you could leave a comment explaining that we are not sure if it is necessary

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 5]
```diff
@@ -597,22 +640,36 @@ mod test {
     fn id_array_visitor() -> Result<()> {
         let expr = binary_expr(
             binary_expr(
-                sum(binary_expr(col("a"), Operator::Plus, lit("1"))),
+                sum(binary_expr(col("a"), Operator::Plus, lit(1))),
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:643]: I agree this test doesn't make sense as coercion should have happened before this pass

**Review by alamb — COMMENTED** [review]
Looks good to me -- thank you @alex-natzka 

cc @waynexia -- do you have time to review this PR as well?

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 1 above)
Comment (alamb) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:490]: This code may be a workaround from some issue we have since fixed 🤔

**Review by alamb — APPROVED** [review]
I ran all the tests without the fallback of the plan's schemas and they worked. Thus I think it is not necessary.

However, I like your incremental approach to development of keeping the old code there as it is no worse than master. I would be fine with merging this PR as is and I will create a PR that removes a workaround as a follow on.

I will wait until tomorrow to see if @waynexia  would like to comment too.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 1 above)
Comment (alamb) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:490]: https://github.com/apache/arrow-datafusion/pull/3730 <-- pr to remove the fallback

**Comment by liukun4515** [comment]
I will review it tomorrow

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 3 above)
Comment (alex-natzka) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:399]: While Joins and Unions are not (yet?) handled by this optimization rule, I think that even in these cases we should be able to construct one consolidated schema that is used to resolve the expression type - otherwise the expression probably is invalid in the first place.

Right now the fall-back logic just randomly merges all possible schemas into one - there's no guarantee the resulting, merged schema will be any good for resolving the expression at hand. That's especially the case if the logical plan involves lots of aliasing - there may be many fields from different nodes that have the same name, e.g. `a`, but different data types; the merged schema will have only one `a` column, though, the first that we encounter while merging schemas.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 4 above)
Comment (alex-natzka) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:488]: This doesn't work so well because we iterate over `Arc<DFSchema>` but `merge` has the signature `fn merge(&mut self, other_schema: &DFSchema)`. We need a df schema that we can mutate to begin with, so reducing won't work easily unless we transform the iterator's item type to `&mut DFSchema` first, which likely means a lot of cloning.

I`d leave this code as-is, personally, since it's likely going to be removed anyway.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 1 above)
Comment (alex-natzka) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs]: Added comments that explain that the fall-back logic can likely be removed.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 3 above)
Comment (alamb) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs]: I am glad I was not the only one confused :)

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 4 above)
Comment (alamb) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:495]: agree

**Comment by alamb** [comment]
Github actions is having issues I think -- the CI failures are not related to changes in this PR

**Comment by andygrove** [comment]
I plan on reviewing this today

**Comment by waynexia** [comment]
Sorry for the late reply, I plan to review it later this day.

**Comment by alamb** [comment]
I would like to merge this PR -- I'll plan on doing so tomorrow if @waynexia and/or @andygrove  haven't had a chance by then

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 3 above)
Comment (waynexia) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs]: This random merge used to only exist in the `Filter` plan and was fixed once in https://github.com/apache/arrow-datafusion/pull/1925 . Ashamedly, I cannot recall why `Filter` is unique :disappointed_relieved: I would like to explain it as my mistake, sorry for that >_<

I think it is doable to remove the else branch as it already takes no effect after #1925

**Review by waynexia — APPROVED** [review]
I've reviewed this fix and it looks reasonable to me. Thanks @alex-natzka @alamb

**Comment by alamb** [comment]
Thanks again @alex-natzka and @waynexia

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 3 above)
Comment (alamb) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs]: I wouldn't worry -- there have been many changes in DataFusion and it was (and still is) a fast changing codebase -- the day I write perfect code without any errors will be the day I hold other people to the same standard 😆
