### PR TITLE
fix: incorrect simplification of case expr

### LINKED ISSUE #7004: CASE expression simplification and type coercion error
### Describe the bug

The `simplify_expressions` optimizer incorrectly optimizes case expressions with a base expression and returns a boolean value. 

https://github.com/apache/arrow-datafusion/blob/b0d24912acd9d86ca6ce3af26b4d845ec250048d/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L1061-L1075

### To Reproduce

```sql
select case c1 
    when 'foo' then TRUE
    when 'bar' then FALSE
  end
```

Example test case can be added to `datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs`

```rust 
    #[test]
    fn case_should_not_simplify() {
        simplify(simplify(Expr::Case(Case::new(
            Some(Box::new(col("c1"))),
            vec![
                (Box::new(lit("foo")), Box::new(lit(true))),
                (Box::new(lit("bar")), Box::new(lit(false))),
            ],
            Some(Box::new(lit(true))),
        ))));
    }
```

Currently the test case panics on error `Internal("The type of Utf8 And Boolean of binary physical should be same")`

### Expected behavior

The optimizer should not try to optimize this.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
# Which issue does this PR close?

Closes #7004.

# Rationale for this change
This rule should only be applied if the base subexpression is not present.

# What changes are included in this PR?

# Are these changes tested?
Yes

# Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 1]
```diff
@@ -1069,17 +1069,20 @@ impl<'a, S: SimplifyInfo> TreeNodeRewriter for Simplifier<'a, S> {
...
             // Note: the rationale for this rewrite is that the expr can then be further
             // simplified using the existing rules for AND/OR
-            Expr::Case(case)
-                if !case.when_then_expr.is_empty()
-                && case.when_then_expr.len() < 3 // The rewrite is O(n!) so limit to small number
-                && info.is_boolean_type(&case.when_then_expr[0].1)? =>
+            Expr::Case(Case {
+                expr: None,
+                when_then_expr,
+                else_expr,
```
Comment (jackwener) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1075]: 👍

**Review by jackwener — APPROVED** [review]
Thank you @jonahgao
