### PR TITLE
Fix handling of nested leaf columns in parallel parquet writer

### LINKED ISSUE #8851: Cannot write a column of type `DataType::List` containing a `DataType::Struct` to parquet with parallel writing
### Describe the bug

When trying to write a column that is of type List that contains a Struct, the parquet writer throws an error `Error: ParquetError(General("Incorrect number of rows, expected 4 != 0 rows"))`. This seems to be a regression as this works fine in datafusion v32.0.0 but not in v33 or v34. It also works using `write_json` instead of `write_parquet`

Example dataframe:
```
+------------------------------------+
| filters                            |
+------------------------------------+
| [{filterTypeId: 3, label: LABEL3}] |
| [{filterTypeId: 2, label: LABEL2}] |
+------------------------------------+
```

### To Reproduce

dependencies (working):
```toml
[dependencies]
tokio = { version = "1.35.1", features = ["macros"] }
datafusion = { version = "32.0.0", features = ["backtrace"] }

```

dependencies (broken):
```toml
[dependencies]
tokio = { version = "1.35.1", features = ["macros"] }
datafusion = { version = "33.0.0", features = ["backtrace"] }

```

example.json
```json
{"filters":[{"filterTypeId":3,"label":"LABEL3"}]}
{"filters":[{"filterTypeId":2,"label":"LABEL2"}]}
```

main.rs
```rust
use datafusion::{dataframe::DataFrameWriteOptions, error::DataFusionError, prelude::*};

#[tokio::main]
async fn main() -> Result<(), DataFusionError> {
    let ctx = SessionContext::new();

    let df = ctx
        .read_json("example.json", NdJsonReadOptions::default())
        .await?;

    df.write_parquet("result", DataFrameWriteOptions::default(), None)
        .await?;
    Ok(())
}

```

### Expected behavior

The parquet writer supports writing this kind of datatype as in v32

### Additional context

Maybe related to: https://github.com/apache/arrow-rs/issues/1744

I found this issue trying to debug a different one that came up while trying to upgrade from v32 to v34. If the struct contains a timestamp the error instead becomes a `Error: Internal("Unable to send array to writer!")` with a source error `internal error: entered unreachable code: cannot downcast Int64 to byte array`.

An example of such a df:
```
+---------------------------------------------------------------------------------+
| filters                                                                         |
+---------------------------------------------------------------------------------+
| [{assignmentStartTs: 2023-11-11T11:11:11.000Z, filterTypeId: 3, label: LABEL1}] |
| [{assignmentStartTs: 2023-11-11T11:11:11.000Z, filterTypeId: 2, label: LABEL2}] |
+--------------------------------------------------------------------------------+
```

I tried to debug this issue myself looking into the `arrow-rs` implementation however I didn't manage to find the relevant commit that could have changed this behavior. Also I wasn't sure if I should open the bug in this project or in the `arrow-rs` project so I hope this is ok 😃.

### LINKED ISSUE #8853: Error writing `STRUCT` to parquet in parallel: internal error: entered unreachable code: cannot downcast Int64 to byte array
### Describe the bug

I can't write a struct to parquet when trying to write in parallel, instead I get the following error

> internal error: entered unreachable code: cannot downcast Int64 to byte array

### To Reproduce

```shell
$ datafusion-cli
DataFusion CLI v34.0.0
❯ create table t as values (struct ('foo', 1)), (struct('bar', 2));
0 rows in set. Query took 0.004 seconds.

❯ select * from t;
+------------------+
| column1          |
+------------------+
| {c0: foo, c1: 1} |
| {c0: bar, c1: 2} |
+------------------+
2 rows in set. Query took 0.001 seconds.

❯ copy (select * from t) to '/tmp/foo.parquet';
thread 'tokio-runtime-worker' panicked at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parquet-49.0.0/src/arrow/arrow_writer/byte_array.rs:441:9:
internal error: entered unreachable code: cannot downcast Int64 to byte array
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

I expect the parquet file to be written successfully. This works fine with JSON:

```shell
$ datafusion-cli
DataFusion CLI v34.0.0
❯ create table t as values (struct ('foo', 1)), (struct('bar', 2));
0 rows in set. Query took 0.003 seconds.

❯ select * from t;
+------------------+
| column1          |
+------------------+
| {c0: foo, c1: 1} |
| {c0: bar, c1: 2} |
+------------------+
2 rows in set. Query took 0.001 seconds.

❯ copy (select * from t) to '/tmp/foo.json';
+-------+
| count |
+-------+
| 2     |
+-------+
1 row in set. Query took 0.010 seconds.

❯
\q
$ cat /tmp/foo.json
{"column1":{"c0":"foo","c1":1}}
{"column1":{"c0":"bar","c1":2}}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devinjdangelo**
## Which issue does this PR close?

Closes #8851
Closes #8853 

## Rationale for this change

See issues above. Parallel parquet writer causes various errors/panics when used with nested columns.

## What changes are included in this PR?

I identified the issue in this function which is supposed to send the appropriate arrow arrays to the correct column serialization workers:

https://github.com/apache/arrow-datafusion/blob/95e739cb605307d3337c54ef3f0ab8c72cca5717/datafusion/core/src/datasource/file_format/parquet.rs#L883-L902

The **outer** loop iterates over the "col_array_channels". This works when there are no nested columns (i.e. the inner loop only ever iterates once), but it is incorrect when there are nested columns. 

The varying errors reported are explained by this bug since a few different things can go wrong here:

- The wrong array of the wrong type is sent to a column serializer 
- The same column serializer is sent too many rows
- A given column serializer is sent zero rows

This PR fixes this function so that it properly sends nested columns to the correct column serializer.

## Are these changes tested?

Yes, copy.slt now includes tests with various column types at various levels of nesting with structs and arrays

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by devinjdangelo** [comment]
cc @alamb @tustvold 

Are there any additional tests which we should add to improve coverage for the parallel writer?

File: datafusion/common/src/config.rs [hunk 1]
```diff
@@ -408,7 +408,7 @@ config_namespace! {
         /// parquet files by serializing them in parallel. Each column
         /// in each row group in each output file are serialized in parallel
         /// leveraging a maximum possible core count of n_files*n_row_groups*n_columns.
-        pub allow_single_file_parallelism: bool, default = false
+        pub allow_single_file_parallelism: bool, default = true
```
Comment (devinjdangelo) [inline datafusion/common/src/config.rs:411]: We could choose to leave this feature disabled by default if we wish to merge this before the next release. That would give us more time to ensure there are no other issues and improve test coverage further.

Comment (alamb) [reply datafusion/common/src/config.rs:411]: We are about to release 35.0.0 which would not include this change. See voting thread here: https://lists.apache.org/thread/onbs8l0w5s7693fchpyvwwgh61gf1jf8

Thus I think it would actually be best to turn this default to true so the code gets maximum "bake time" from people working off `main` before a release

**Comment by alamb** [comment]
> Are there any additional tests which we should add to improve coverage for the parallel writer?

I think if we could including tests that write lists of structs and structs of lists that would also be good 

Perhaps like
```sql

❯ select [struct('foo', 1), struct('bar', 2)];
+-----------------------------------------------------------------------+
| make_array(struct(Utf8("foo"),Int64(1)),struct(Utf8("bar"),Int64(2))) |
+-----------------------------------------------------------------------+
| [{c0: foo, c1: 1}, {c0: bar, c1: 2}]                                  |
+-----------------------------------------------------------------------+
1 row in set. Query took 0.002 seconds.
```

```sql
❯ select struct('foo', [1,2,3], struct('bar', [2,3,4]));
+-----------------------------------------------------------------------------------------------------------------------+
| struct(Utf8("foo"),make_array(Int64(1),Int64(2),Int64(3)),struct(Utf8("bar"),make_array(Int64(2),Int64(3),Int64(4)))) |
+-----------------------------------------------------------------------------------------------------------------------+
| {c0: foo, c1: [1, 2, 3], c2: {c0: bar, c1: [2, 3, 4]}}                                                                |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set. Query took 0.003 seconds.
```

File: datafusion/core/src/datasource/file_format/parquet.rs [hunk 2]
```diff
@@ -885,24 +885,25 @@ async fn send_arrays_to_col_writers(
...
-            tx.send(c).await.map_err(|_| {
-                DataFusionError::Internal("Unable to send array to writer!".into())
-            })?;
+            col_array_channels[next_channel]
+                .send(c)
+                .await
+                .map_err(|_| {
+                    DataFusionError::Internal("Unable to send array to writer!".into())
+                })?;
+            next_channel += 1;
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/parquet.rs:898]: is the idea that there can be more than one array can be sent per field ?

**Review by alamb — APPROVED** [review]
Thank you @devinjdangelo  -- this looks great to me.

I have a suggestion for some additional tests, which we can add to this PR or we can also add it as a follow on PRs

File: datafusion/core/src/datasource/file_format/parquet.rs (hunk 2 above)
Comment (devinjdangelo) [reply datafusion/core/src/datasource/file_format/parquet.rs:898]: Per top level field, yes. The "Field" referenced in the outer loop is only top level, non-nested fields. The `compute_leaves` function does the recursive iteration of all nested fields for each top level field. 

There is actually an independent channel / parallel serializer for every nested (not only top level) field. So, we must advance the channel we are sending to on every iteration of `compute_leaves`  not just on every iteration of a new top level field.

**Comment by alamb** [comment]
Thanks again @devinjdangelo
