### PR TITLE
Fix join without constraints

### LINKED ISSUE #2230: Panic while running inner join with predicate only on single relation
**Describe the bug**
The following error would occur when join condition is only filtered on single realtion:
`thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/momo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-7.0.0/src/physical_plan/repartition.rs:354:39`

**To Reproduce**
```rust
fn main() {
    let id_array = Int32Array::from(vec![1, 2, 3, 4, 5]);
    let str_array = StringArray::from(vec!["1", "2", "3", "4", "5"]);
    let schema = Schema::new(vec![
        Field::new("id", DataType::Int32, false),
        Field::new("str", DataType::Utf8, false),
    ]);
    let batch = RecordBatch::try_new(
        Arc::new(schema),
        vec![
            Arc::new(id_array),
            Arc::new(str_array),
        ],
    )
    .unwrap();

    let mut ctx = ExecutionContext::new();
    let sql = "select * from tmp t1 inner join tmp t2 on t1.str = '1' and t2.str = '2'";
    let db1 = MemTable::try_new(batch.schema(), vec![vec![batch]]).unwrap();
    ctx.register_table("tmp", Arc::new(db1)).unwrap();

    let rt = Arc::new(tokio::runtime::Runtime::new().expect("Failed to create runtime"));
    let df = rt.block_on(ctx.sql(sql)).unwrap();
    rt.block_on(df.limit(5).unwrap().show()).unwrap();
    let num_rows = rt
        .block_on(df.collect())
        .unwrap()
        .into_iter()
        .map(|rb| rb.num_rows())
        .sum::<usize>();
    println!("Final # rows: {}", num_rows);
}
```

**Expected behavior**
The following queries should have same result:
q1: `select * from tmp t1 inner join tmp t2 on t1.str = '1' and t2.str = '2'`
q2: `select * from tmp t1 cross join tmp t2 where t1.str = '1' and t2.str = '2'`
q3: `select * from tmp t1, tmp t2 where t1.str = '1' and t2.str = '2'`

q2 and q3 works fine in datafusion.

**Additional context**

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #2230

 # Rationale for this change

Allows to use join syntax, even if no actual join constraint can be used to use an equi-join. 

# What changes are included in this PR?

Fixes join without on constraint.
Also adds explicit check for non-empty constraint list in HashJoinExec

# Are there any user-facing changes?

No

### CODE REVIEW

**Review by yjshen — APPROVED** [review]

**Review by andygrove — APPROVED** [review]

File: datafusion/core/src/sql/planner.rs [hunk 1]
```diff
@@ -524,7 +524,18 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
                     keys.into_iter().unzip();
 
                 // return the logical plan representing the join
-                if filter.is_empty() {
+                if left_keys.is_empty() {
+                    // When we don't have join keys, use cross join
```
Comment (alamb) [inline datafusion/core/src/sql/planner.rs:528]: yeah, that is the classic implementation, infortunately

File: datafusion/core/src/sql/planner.rs [hunk 2]
```diff
@@ -524,7 +524,18 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
+                    let join = LogicalPlanBuilder::from(left).cross_join(&right)?;
+
+                    let join_filter_init = filter.remove(0);
+                    join.filter(
+                        filter
+                            .into_iter()
+                            .fold(join_filter_init, |acc, e| acc.and(e)),
+                    )?
+                    .build()
```
Comment (alamb) [inline datafusion/core/src/sql/planner.rs:537]: I wonder if you can use `reduce` here rather than fold: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.reduce

Something like (untested):

```suggestion
                    join.filter(
                        filter
                            .reduce(|acc, e| acc.and(e)),
                    )?
                    .build()
```

**Review by alamb — APPROVED** [review]

File: datafusion/core/src/sql/planner.rs [hunk 3]
```diff
@@ -537,13 +543,8 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
                         (left_keys, right_keys),
                     )?;
-                    let join_filter_init = filter.remove(0);
-                    join.filter(
-                        filter
-                            .into_iter()
-                            .fold(join_filter_init, |acc, e| acc.and(e)),
-                    )?
-                    .build()
+                    join.filter(filter.into_iter().reduce(Expr::and).unwrap())?
```
Comment (alamb) [inline datafusion/core/src/sql/planner.rs:546]: ❤️
