### PR TITLE
fix: issue #8922 make row group test more readable

### LINKED ISSUE #8922: Make test_row_group_prune test more readable
There are so many parameters here it is getting hard to read the tests I think (as you have three different constants that need to be remembered)

Maybe we can (as a follow on PR) make a more self documenting, something like

```suggestion
    RowGroupPruningTest::new()
        .with_scenario(Scenario::Timestamps)
        .with_query("SELECT * FROM t where nanos < to_timestamp('2020-01-02 01:01:11Z')"),
        .with_expected_errors(Some(0)),
        .with_pruned_by_stats(Some(1)),
        .with_pruned_by_bloom_filter(Some(0)),
        .with_expected_rows(10)
    )
    .await;
```

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/8921#discussion_r1460358000_

### PR DESCRIPTION
**Pull request by Lordworms**
## Which issue does this PR close?

Closes #8922.

## Rationale for this change

Since the original test in datafusion/core/tests/parquet/row_group_pruning.rs is hard to read, I use a test structure mentioned by lamb in [comment](https://github.com/apache/arrow-datafusion/pull/8921#discussion_r1460358000) to refracture the test
## Are these changes tested?
yes

### CODE REVIEW

File: datafusion/core/tests/parquet/row_group_pruning.rs [hunk 1]
```diff
@@ -215,369 +242,364 @@ async fn prune_disabled() {
...
         )
-        .as_str(),
-        Some(0),
-        Some(1),
-        // we don't support pruning by statistics for in_list with more than 20 elements currently
-        Some(0),
-        0,
-    )
-    .await;
+        .with_expected_errors(Some(0))
```
Comment (alamb) [inline datafusion/core/tests/parquet/row_group_pruning.rs:452]: This seems like the test is different -- the results are 0, 0, 1 rather than 0,1,0

Perhaps there is a difference between `test_row_group_prune` and `test_prune_verbose`

File: datafusion/core/tests/parquet/row_group_pruning.rs [hunk 2]
```diff
@@ -586,32 +608,31 @@ async fn prune_periods_in_column_names() {
...
-        Some(2), // prune out middle and last row group
-        Some(0),
-        2,
-    )
-    .await;
+    RowGroupPruningTest::new()
+        .with_scenario(Scenario::PeriodsInColumnNames)
+        .with_query(  "SELECT \"name\", \"service.name\" FROM t WHERE \"service.name\" = 'frontend'")
+        .with_expected_errors(Some(0))
+        .with_pruned_by_stats(Some(1))
```
Comment (alamb) [inline datafusion/core/tests/parquet/row_group_pruning.rs:615]:
```suggestion
        // prune out first and last row group
        .with_pruned_by_stats(Some(1))
```

File: datafusion/core/tests/parquet/row_group_pruning.rs [hunk 3]
```diff
@@ -586,32 +608,31 @@ async fn prune_periods_in_column_names() {
...
+        .with_pruned_by_bloom_filter(Some(0))
+        .with_expected_rows(7)
+        .test_row_group_prune()
+        .await;
+    RowGroupPruningTest::new()
+        .with_scenario(Scenario::PeriodsInColumnNames)
+        .with_query(  "SELECT \"name\", \"service.name\" FROM t WHERE \"name\" != 'HTTP GET / DISPATCH'")
+        .with_expected_errors(Some(0))
+        .with_pruned_by_stats(Some(2))
```
Comment (alamb) [inline datafusion/core/tests/parquet/row_group_pruning.rs:624]:
```suggestion
        // prune out first and last row group
        .with_pruned_by_stats(Some(2))
```

File: datafusion/core/tests/parquet/row_group_pruning.rs [hunk 4]
```diff
@@ -586,32 +608,31 @@ async fn prune_periods_in_column_names() {
...
+        .with_pruned_by_bloom_filter(Some(0))
+        .with_expected_rows(5)
+        .test_row_group_prune()
+        .await;
+    RowGroupPruningTest::new()
+        .with_scenario(Scenario::PeriodsInColumnNames)
+        .with_query(  "SELECT \"name\", \"service.name\" FROM t WHERE \"service.name\" = 'frontend' AND \"name\" != 'HTTP GET / DISPATCH'")
+        .with_expected_errors(Some(0))
+        .with_pruned_by_stats(Some(2))
```
Comment (alamb) [inline datafusion/core/tests/parquet/row_group_pruning.rs:633]:
```suggestion
        // prune out first and last row group
        .with_pruned_by_stats(Some(2))
```

**Review by alamb — COMMENTED** [review]
Thank you so much @Lordworms  -- this is looking really good

There seems to be one difference in `prune_int32_eq_large_in_list` but otherwise I think this PR is ready to go. 

cc @Ted-Jiang  as this will likely conflict with https://github.com/apache/arrow-datafusion/pull/8930

File: datafusion/core/tests/parquet/row_group_pruning.rs (hunk 1 above)
Comment (Lordworms) [reply datafusion/core/tests/parquet/row_group_pruning.rs:452]: OK, I am confused about these two functions since they look and execute the same logic. I hope to get an answer about the differences

Comment (alamb) [reply datafusion/core/tests/parquet/row_group_pruning.rs:452]: Actually, I just double checked and the difference appears to be that the argument order was different to the two functions 🤦 

So therefore I think this change makes sense

**Review by alamb — APPROVED** [review]
Thanks again @Lordworms

**Comment by Lordworms** [comment]
an unused variable that I used to debug has not been deleted, I'll fix it soon

**Comment by alamb** [comment]
FYI @Ted-Jiang
