### PR TITLE
Don't error in simplify_expressions rule

### LINKED ISSUE #8909: Evaluates CASE branches even if their WHEN clause is false
### Describe the bug

Datafusion evaluates `CASE ... WHEN ... THEN` expressions even for non-true branches, and bubbles up runtime errors from them.

This is wrong because the `CASE` could be explicitly protecting against the divide-by-zero case, and differs from other sql engines.

### To Reproduce

```console
❯ SELECT CASE 1 WHEN 2 THEN 42/0 END;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Divide by zero error
```

### Expected behavior

I expected the `CASE` to evaluate to `NULL`, as none of its `WHEN` branches were true and it did not have an `ELSE`.

Compare to SQLite:

```console
sqlite> .nullvalue NULL
sqlite> SELECT CASE 1 WHEN 2 THEN 42/0 END;
NULL
```

Compare to Postgres:

```console
postgres=# \pset null 'NULL'
Null display is "NULL".
postgres=# SELECT CASE 1 WHEN 2 THEN 42/0 END;
 case
------
 NULL
(1 row)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by haohuaijin**
## Which issue does this PR close?

Closes #8909

## Rationale for this change

see #8910 and #8909 ,

## What changes are included in this PR?

before this pr, in simplify_espression we try to fold the expression, but this can result some error, for example 
```sql
select case 1 when 2 then 4/0 end;
```
`4/0` never reach in runtime.

so in this PR, if we encounter an error during fold expression, return the origin expression, and the error will occur in runtime if it is a real error(not the short-circuit problem).

Note: this pr doesn't solve #8910 , due to #8927

## Are these changes tested?

test by existing tests

### CODE REVIEW

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 1]
```diff
@@ -281,7 +280,13 @@ impl<'a> TreeNodeRewriter for ConstEvaluator<'a> {
...
     fn mutate(&mut self, expr: Expr) -> Result<Expr> {
         match self.can_evaluate.pop() {
-            Some(true) => Ok(Expr::Literal(self.evaluate_to_scalar(expr)?)),
+            Some(true) => {
+                let lit = self.evaluate_to_scalar(expr.clone());
+                match lit {
+                    Ok(lit) => Ok(Expr::Literal(lit)),
+                    Err(_) => Ok(expr),
+                }
+            }
```
Comment (haohuaijin) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:289]: This is the main change

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 2]
```diff
@@ -796,18 +801,6 @@ impl<'a, S: SimplifyInfo> TreeNodeRewriter for Simplifier<'a, S> {
                 op: Divide,
                 right,
             }) if is_null(&right) => *right,
-            // A / 0 -> Divide by zero error if A is not null and not floating
-            // (float / 0 -> inf | -inf | NAN)
-            Expr::BinaryExpr(BinaryExpr {
```
Comment (haohuaijin) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:801]: Remove this because `A / 0` can occur in short-circuit expression. And we can throw such an error in runtime.

File: datafusion/physical-expr/src/expressions/case.rs [hunk 3]
```diff
@@ -148,6 +148,11 @@ impl CaseExpr {
             // Make sure we only consider rows that have not been matched yet
             let when_match = and(&when_match, &remainder)?;
 
+            // When no rows available for when clause, skip then clause
+            if when_match.true_count() == 0 {
+                continue;
+            }
+
```
Comment (haohuaijin) [inline datafusion/physical-expr/src/expressions/case.rs:155]: Because even though `when_match` is all false, the `evaluate_selection` still evaluates the expression one time.
https://github.com/apache/arrow-datafusion/blob/827668ab3d4659329ff30e6672f398c934b803be/datafusion/physical-expr/src/expressions/case.rs#L148-L153
so the query like below, will get divide by zero error.
```
select case 1 when 2 the 4/0 end;
```
------
The root cause is that even though `BinaryExpr` receives a `RecordBatch` with 0 rows, it also evaluates once. And, it only appears in `scalar op scalar`.
https://github.com/apache/arrow-datafusion/blob/827668ab3d4659329ff30e6672f398c934b803be/datafusion/physical-expr/src/expressions/binary.rs#L259-L268

**Comment by haohuaijin** [comment]
cc @jackwener @alamb. This is the first step to solving #8910; the main change in this PR is that it throws an error in runtime, not in simplify_expression.
before this pr
```
❯ select 1/0;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Divide by zero error
```
after this pr
```
❯ select 1/0;
Arrow error: Divide by zero error
```

File: datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs [hunk 4]
```diff
@@ -138,28 +138,6 @@ mod tests {
         ExprSchemable, JoinType,
     };
 
-    /// A macro to assert that one string is contained within another with
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs:141]: 💯  for reusing the existing one

File: datafusion/sqllogictest/test_files/arrow_typeof.slt [hunk 5]
```diff
@@ -405,7 +405,7 @@ select arrow_cast([1], 'FixedSizeList(1, Int64)');
 ----
 [1]
 
-query error DataFusion error: Optimizer rule 'simplify_expressions' failed
+query error
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/arrow_typeof.slt:408]: would it be possible to update the slt files with the new error message ? It would be easier to validate the test still makes sense

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 1 above)
Comment (alamb) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:289]: This change makes sense to me. Can we please add some rationale / explanation here about *why* the error is ignored so future people who read this code understand 

Perhaps something like
```rust
// Certain expressions such as `CASE` and `COALESCE` are short circuiting
// and may not evalute all their sub expressions. Thus if
// if any error is countered during simplification, return the original 
// so that normal evaluation can occur
```

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 6]
```diff
@@ -1792,27 +1768,6 @@ mod tests {
         assert_eq!(simplify(expr), expected);
     }
 
-    #[test]
-    fn test_simplify_divide_zero_by_zero() {
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1796]: Can we please ensure this new ignore error behavior is covered in these unit tests?

Perhaps you could update `test_simplify_divide_by_zero` and instead expect that no rewrite occurs rather than deleting the entire test. 

Also, I think it is important to have a test that shows partial simplification occurs even when part of the expression errors

For example, perhaps we can add a test like:
```
(1 + 2) + (4/0) --> 3 + (4/0)
```

File: datafusion/physical-expr/src/expressions/case.rs (hunk 3 above)
Comment (alamb) [reply datafusion/physical-expr/src/expressions/case.rs:155]: > so the query like below, will get divide by zero error.
>
> `select case 1 when 2 the 4/0 end;`

Is that case covered by existing tests? If not, can you please add a test?

Comment (alamb) [reply datafusion/physical-expr/src/expressions/case.rs:155]:
```rust
            // When no rows available for when clause, skip then clause
            if when_match.true_count() == 0 {
                continue;
            }
```
I souble checked that this method accounts for nulls 👍 

https://docs.rs/arrow/latest/arrow/array/struct.BooleanArray.html#method.true_count

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 7]
```diff
@@ -281,7 +280,13 @@ impl<'a> TreeNodeRewriter for ConstEvaluator<'a> {
 
     fn mutate(&mut self, expr: Expr) -> Result<Expr> {
         match self.can_evaluate.pop() {
-            Some(true) => Ok(Expr::Literal(self.evaluate_to_scalar(expr)?)),
+            Some(true) => {
+                let lit = self.evaluate_to_scalar(expr.clone());
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:284]: It seems a real shame that this has to clone the expression even for the common case where there is no error

 maybe we could use something like the following:
```rust
enum SimplifyResult {
   // expr was simplifed and contains the new expression
  Simplified(Expr),
  // Evalaution encountered an error, contains the original expression
  SimplifyRuntimeError(DataFusionError, Expr), 
}
```

**Review by alamb — COMMENTED** [review]
Thank you @haohuaijin  -- I think this is looking really good to me. 

I think we should avoid the clone if possible, add a few more tests, and update the expected error messages, but all in all this PR is looking really close.

cc @jackwener

File: datafusion/sqllogictest/test_files/arrow_typeof.slt (hunk 5 above)
Comment (haohuaijin) [reply datafusion/sqllogictest/test_files/arrow_typeof.slt]: Done.

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 6 above)
Comment (haohuaijin) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1796]: Done. add such tests.

File: datafusion/physical-expr/src/expressions/case.rs (hunk 3 above)
Comment (haohuaijin) [reply datafusion/physical-expr/src/expressions/case.rs:155]: > Is that case covered by existing tests? If not, can you please add a test?

yes，add this one

**Comment by haohuaijin** [comment]
Thanks @alamb for the great reviews; I apply your suggestions, re-added the deleted tests and add some new tests.

File: datafusion/sqllogictest/test_files/scalar.slt [hunk 8]
```diff
@@ -1527,15 +1527,15 @@ SELECT not(true), not(false)
...
+query error
 SELECT not(1), not(0)
 
 query ?B
 SELECT null, not(null)
 ----
 NULL NULL
 
-query error DataFusion error: Optimizer rule 'simplify_expressions' failed\ncaused by\nInternal error: NOT 'Literal \{ value: Utf8\("hi"\) \}' can't be evaluated because the expression's type is Utf8, not boolean or NULL
+query error
```
Comment (haohuaijin) [inline datafusion/sqllogictest/test_files/scalar.slt:1538]: remove the detailed error message because this query return internal error, that make ci failed
```
❯ select not('hi');
Internal error: NOT 'Literal { value: Utf8("hi") }' can't be evaluated because the expression's type is Utf8, not boolean or NULL.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
❯ select 1 and 2;
Error during planning: Cannot infer common argument type for logical boolean operation Int64 AND Int64
```
I think the return error message should like `And` operator, they both only work for boolean value.

Comment (haohuaijin) [reply datafusion/sqllogictest/test_files/scalar.slt:1538]: track in #8965

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 9]
```diff
@@ -1837,6 +1815,26 @@ mod tests {
         assert_eq!(simplify(expr), expected);
     }
 
+    #[test]
+    fn test_simplify_divide_zero_by_zero() {
+        // because divide by 0 maybe occur in short-circuit expression
+        // so we should not simplify this, and throw error in runtime
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1821]: 👍

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 10]
```diff
@@ -3385,4 +3384,22 @@ mod tests {
...
+        // (1 + 2) + (4 / 0) -> 3 + (4 / 0)
+        let expr = (lit(1) + lit(2)) + (lit(4) / lit(0));
+        let expected = (lit(3)) + (lit(4) / lit(0));
+
+        assert_eq!(simplify(expr), expected);
+    }
+
+    #[test]
+    fn test_expression_partial_simplify_2() {
+        // (1 > 2) and (4 / 0) -> false
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:3399]: nice

**Review by alamb — APPROVED** [review]
Thank you @haohuaijin  -- this PR looks great to me. Thank you

FYI @jackwener

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 11]
```diff
@@ -281,7 +288,17 @@ impl<'a> TreeNodeRewriter for ConstEvaluator<'a> {
 
     fn mutate(&mut self, expr: Expr) -> Result<Expr> {
         match self.can_evaluate.pop() {
-            Some(true) => Ok(Expr::Literal(self.evaluate_to_scalar(expr)?)),
+            // Certain expressions such as `CASE` and `COALESCE` are short circuiting
+            // and may not evalute all their sub expressions. Thus if
+            // if any error is countered during simplification, return the original
+            // so that normal evaluation can occur
```
Comment (jackwener) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:294]: 👍

**Review by jackwener — APPROVED** [review]
A very nice job! Thanks @haohuaijin @alamb ❤️
