### PR TITLE
Replace usages of internal_err with exec_err where appropriate

### LINKED ISSUE #9164: Internal_err! is over used in core code and should be replaced with exec_err! or plan_err! in many places
### Describe the bug

internal_err! is used as a general error macro in many spots in the code where in fact the problem the error is propagating is not caused by an oversight, bug, etc in the code but rather by user error. A good example of this can be seen in PR #9137  [comment](https://github.com/apache/arrow-datafusion/pull/9137#discussion_r1480303798) where it's being used to let the user know they provided a datatype as an argument to a function that it doesn't support. This in fact should be an exec_err! in this example.

### To Reproduce

_No response_

### Expected behavior

In most cases where the error is caused by incorrect data types or invalid argument counts exec_err! should be used.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Omega359**
## Which issue does this PR close?

Closes #9164

## Rationale for this change

Code cleanup.

## What changes are included in this PR?

Only internal_err! for incorrect arg count or data type was migrated to exec_err, all other cases were left alone.

## Are these changes tested?

Yes,

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/physical-expr/src/functions.rs [hunk 1]
```diff
@@ -436,7 +437,7 @@ pub fn create_physical_fun(
             DataType::LargeUtf8 => {
                 make_scalar_function_inner(string_expressions::ascii::<i64>)(args)
             }
-            other => internal_err!("Unsupported data type {other:?} for function ascii"),
+            other => exec_err!("Unsupported data type {other:?} for function ascii"),
```
Comment (comphead) [inline datafusion/physical-expr/src/functions.rs:440]: I'm thinking if its good to use `not_impl_err!` for unsupported errors

Comment (Omega359) [reply datafusion/physical-expr/src/functions.rs:440]: I could do that. It's unfortunate that this type of error can't be validated and caught at compile time.

File: datafusion/physical-expr/src/array_expressions.rs [hunk 2]
```diff
@@ -433,7 +433,7 @@ pub fn array_element(args: &[ArrayRef]) -> Result<ArrayRef> {
             let indexes = as_int64_array(&args[1])?;
             general_array_element::<i64>(array, indexes)
         }
-        _ => exec_err!(
+        _ => not_impl_err!(
```
Comment (Weijun-H) [inline datafusion/physical-expr/src/array_expressions.rs:436]: Most array functions only accept `List`, `LargeList`, and `FixedSizeList`. So it should not be  `not_impl_err`.

Comment (Omega359) [reply datafusion/physical-expr/src/array_expressions.rs:436]: So ... in your opinion what should the error be? All I can think of what I had previously (exec_err), what @comphead suggested (not_impl_err) or a brand new error (say invalid_type_err)? 

Essentially every single one of the changes I made was for this pattern, arrays are not special in this regard.

Comment (Weijun-H) [reply datafusion/physical-expr/src/array_expressions.rs:436]: Because most of them are related to unsupported type errors, a new brand error `invalid_type_err` could be more accurate and readable.

Comment (alamb) [reply datafusion/physical-expr/src/array_expressions.rs:436]: I think exec_err is a good choice. THe value of a new structured error is that some program could react specially to it, but I can't think of a good reason that the reaction to a "invalid_type_err" would be different than a exec_err. Thus I don't think a new type is a good idea in this case

Comment (Omega359) [reply datafusion/physical-expr/src/array_expressions.rs]: I reverted the not_impl_err commit, it just doesn't feel correct to me.

File: datafusion/functions/src/core/nullif.rs [hunk 3]
```diff
@@ -58,7 +58,7 @@ impl NullIfFunc {
         Self {
             signature:
             Signature::uniform(2, SUPPORTED_NULLIF_TYPES.to_vec(),
-                Volatility::Immutable,
+                               Volatility::Immutable,
```
Comment (alamb) [inline datafusion/functions/src/core/nullif.rs:61]: This is a strange change -- I wonder if cargo fmt doesn't see this file for some reason 🤔

**Review by alamb — APPROVED** [review]
Thank you @Omega359  -- this looks great and I think we should get this asap as it will conflict with many of the function extraction PRs. 

I took the liberty of merging up from main and resolving one such conflict and plan to merge this when the CI checks have passed

File: datafusion/functions/src/core/nullif.rs (hunk 3 above)
Comment (alamb) [reply datafusion/functions/src/core/nullif.rs:61]: Ah, I see now https://github.com/apache/arrow-datafusion/issues/9281
