### PR TITLE
fix: improve `unnest_generic_list` handling of null list

### LINKED ISSUE #9932: unnest doesn't take into account null values
### Describe the bug

The code [here](https://github.com/apache/arrow-datafusion/blob/main/datafusion/physical-plan/src/unnest.rs#L372) assumes that null lists will be represented as a zero-length offset.  The structure described [in the documentation](https://docs.rs/datafusion/latest/datafusion/common/arrow/array/struct.GenericListArray.html) would break this code if it was used to encode NULL values.

### To Reproduce

Unnesting the example linked in the description should be sufficient.

### Expected behavior

It's expected that the offset will be adjusted for NULL values.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #9932.

## Rationale for this change
In a `GenericListArray`, the data in the `values` corresponding to a null list may not be empty; it can be any data.
```rust
pub struct GenericListArray<OffsetSize: OffsetSizeTrait> {
    data_type: DataType,
    nulls: Option<NullBuffer>,
    values: ArrayRef,
    value_offsets: OffsetBuffer<OffsetSize>,
}
```
For example, in the description of [this document](https://docs.rs/datafusion/latest/datafusion/common/arrow/array/struct.GenericListArray.html#representation), the value of the null list is `?`, it's not empty.

In this situation, merely checking the `values` is unsafe, we must obtain valid values based on the `value_offsets`.

## What changes are included in this PR?
- Fix bug in `unnest_generic_list`.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/physical-plan/src/unnest.rs [hunk 1]
```diff
@@ -364,32 +364,31 @@ fn unnest_generic_list<T: OffsetSizeTrait, P: ArrowPrimitiveType<Native = T>>(
...
-                }
-                take_offset += array.len();
-            }
-            None => {
+    let mut take_indicies_builder =
+        PrimitiveArray::<P>::builder(values.len() + list_array.null_count());
+    let offsets = list_array.value_offsets();
+    for row in 0..list_array.len() {
+        if list_array.is_null(row) {
+            if options.preserve_nulls {
```
Comment (Jefffrey) [inline datafusion/physical-plan/src/unnest.rs:376]: Bit surprised that clippy didn't suggest collapsing these together? Either way, would it be slightly more efficient to put the `options.preserve_nulls` check first since this would never change per iteration?

File: datafusion/physical-plan/src/unnest.rs [hunk 2]
```diff
@@ -596,3 +595,99 @@ where
...
+    use super::*;
+    use arrow::{
+        array::AsArray,
+        datatypes::{DataType, Field},
+    };
+    use arrow_array::StringArray;
+    use arrow_buffer::{BooleanBufferBuilder, NullBuffer, OffsetBuffer};
+
+    // Create a ListArray with the following list values:
+    //  [A, B, C], [], NULL, [D], NULL, [NULL, F]
```
Comment (Jefffrey) [inline datafusion/physical-plan/src/unnest.rs:610]: Nice tests :+1:

**Review by Jefffrey — APPROVED** [review]
Looks correct to me :+1:

**Review by jayzhan211 — APPROVED** [review]
👍

**Comment by jayzhan211** [comment]
Nice fix! Thanks @jonahgao and @Jefffrey
