### PR TITLE
Fix stuck issue for the load testing of Push-based task scheduling

### LINKED ISSUE #2005: [Ballista] Load testing for Push-based task scheduling get stuck
**Describe the bug**

There are two bugs.
- Losing the event SchedulerServerEvent::JobSubmitted results in job no longer to be scheduled
- Concurrency issue of updating ExecutorData simultaneously.

1. For the first bug:
In the method of SchedulerServerEventAction::offer_resources, the returned available_executors may be all with 0 available_task_slots. In this case, there'll be no tasks to be scheduled for the job and no SchedulerServerEvent::JobSubmitted will be resent to the channel. As a result, the job will get stuck.

2. For the second bug:
The operations of get_executor_data and save_executor_data are not atomic, which may result in concurrency issue.

**To Reproduce**

Run loading test with Push-based task scheduling policy as described in #1983.

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #2005 .

 # Rationale for this change

# What changes are included in this PR?

1. For the first bug:
We should make sure the returned available_executors should be all with available_task_slots > 0.

2. For the second bug:
We should use update_executor_data rather than save_executor_data to update executors' available_task_slots.

# Are there any user-facing changes?

### CODE REVIEW

File: ballista/rust/scheduler/src/scheduler_server/event_loop.rs [hunk 1]
```diff
@@ -70,12 +70,28 @@ impl<T: 'static + AsLogicalPlan, U: 'static + AsExecutionPlan>
             return Ok(Some(SchedulerServerEvent::JobSubmitted(job_id)));
         }
 
+        let mut executors_delta_data: Vec<ExecutorDeltaData> = available_executors
```
Comment (liukun4515) [inline ballista/rust/scheduler/src/scheduler_server/event_loop.rs:73]: `executors_delta_data` is confused for me, because this just clone/copy some attributes from `available_executors`

**Review by liukun4515 — APPROVED** [review]
LTGM
except for some naming

File: ballista/rust/scheduler/src/scheduler_server/event_loop.rs (hunk 1 above)
Comment (yjshen) [reply ballista/rust/scheduler/src/scheduler_server/event_loop.rs:73]: `ResourceChange` or `SlotsChange` probably?

Comment (yahoNanJing) [reply ballista/rust/scheduler/src/scheduler_server/event_loop.rs]: fixed

**Comment by yjshen** [comment]
Thanks @yahoNanJing @liukun4515
