### PR TITLE
Fix `compute_record_batch_statistics` wrong with `projection`

### LINKED ISSUE #8406: `compute_record_batch_statistics` wrong with `projection`
### Describe the bug

`total_byte_size` for `MemoryExec` doesn't take into account `projection` when calculating statistics.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Asura7969**
## Which issue does this PR close?

Closes #8406.

## Rationale for this change

Projection size is not calculated correctly
## What changes are included in this PR?

Select the correct columns, not all

## Are these changes tested?
`test_compute_record_batch_statistics`

## Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-plan/src/common.rs [hunk 1]
```diff
@@ -139,17 +140,24 @@ pub fn compute_record_batch_statistics(
...
     let projection = match projection {
         Some(p) => p,
         None => (0..schema.fields().len()).collect(),
     };
 
+    let total_byte_size = batches
+        .iter()
+        .flatten()
+        .map(|b| {
+            b.columns()
```
Comment (Asura7969) [inline datafusion/physical-plan/src/common.rs:152]: The `RecordBatch.project` method is not used, because there is a `clone` internally, so there is no need to generate a new RecordBatch here.

File: datafusion/physical-plan/src/common.rs [hunk 2]
```diff
@@ -685,20 +694,30 @@ mod tests {
...
+
         let actual =
-            compute_record_batch_statistics(&[vec![batch]], &schema, Some(vec![0, 1]));
+            compute_record_batch_statistics(&[vec![batch]], &schema, select_projection);
 
-        let mut expected = Statistics {
+        let expected = Statistics {
             num_rows: Precision::Exact(3),
-            total_byte_size: Precision::Exact(464), // this might change a bit if the way we compute the size changes
+            total_byte_size: Precision::Exact(byte_size),
```
Comment (Asura7969) [inline datafusion/physical-plan/src/common.rs:720]: I'm not sure if this is appropriate, if you have any good suggestions please leave a message

File: datafusion/physical-plan/src/common.rs [hunk 3]
```diff
@@ -139,17 +140,24 @@ pub fn compute_record_batch_statistics(
...
     };
 
+    let total_byte_size = batches
+        .iter()
+        .flatten()
+        .map(|b| {
+            b.columns()
+                .iter()
+                .enumerate()
+                .filter(|(index, _)| projection.contains(index))
```
Comment (Dandandan) [inline datafusion/physical-plan/src/common.rs:155]: Might do something like `b.colums()[index]` instead

Comment (Asura7969) [reply datafusion/physical-plan/src/common.rs]: thanks for your advice

File: datafusion/physical-plan/src/common.rs (hunk 2 above)
Comment (alamb) [reply datafusion/physical-plan/src/common.rs:718]: I think this is ok and a nice way to make the code less brittle to future changes in arrow's layout

File: datafusion/sqllogictest/test_files/groupby.slt [hunk 4]
```diff
@@ -2021,14 +2021,15 @@ SortPreservingMergeExec: [col0@0 ASC NULLS LAST]
...
 --------------SortExec: expr=[col0@3 ASC NULLS LAST]
-----------------CoalesceBatchesExec: target_batch_size=8192
-------------------HashJoinExec: mode=Partitioned, join_type=Inner, on=[(col0@0, col0@0)]
---------------------CoalesceBatchesExec: target_batch_size=8192
-----------------------RepartitionExec: partitioning=Hash([col0@0], 4), input_partitions=1
-------------------------MemoryExec: partitions=1, partition_sizes=[3]
---------------------CoalesceBatchesExec: target_batch_size=8192
-----------------------RepartitionExec: partitioning=Hash([col0@0], 4), input_partitions=1
-------------------------MemoryExec: partitions=1, partition_sizes=[3]
+----------------ProjectionExec: expr=[col0@2 as col0, col1@3 as col1, col2@4 as col2, col0@0 as col0, col1@1 as col1]
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/groupby.slt:2024]: Looks to me like the change is due to the fact the join inputs were reordered and this projection puts the columns back the expected way. 

Same thing with the projection below

**Review by alamb — APPROVED** [review]
This makes sense to me -- thank you @Asura7969  and I apologize for the delay in reviewing. cc @Dandandan

File: datafusion/physical-plan/src/common.rs [hunk 5]
```diff
@@ -139,17 +140,22 @@ pub fn compute_record_batch_statistics(
...
+    let total_byte_size = batches
+        .iter()
+        .flatten()
+        .map(|b| {
+            projection
+                .iter()
+                .map(|index| b.column(*index).get_array_memory_size())
+                .sum::<usize>()
+        })
+        .sum();
```
Comment (jackwener) [inline datafusion/physical-plan/src/common.rs:157]: 👍

**Review by jackwener — APPROVED** [review]
Thanks @Asura7969

File: datafusion/physical-plan/src/common.rs (hunk 2 above)
Comment (jackwener) [reply datafusion/physical-plan/src/common.rs:718]: I'm curious as to why the previous code was `Precision::Exact(464)`.

Comment (alamb) [reply datafusion/physical-plan/src/common.rs:718]: I think it happens to be the (current) size of the record batch in the test:

```rust
        let batch = RecordBatch::try_new(
            Arc::clone(&schema),
            vec![
                Arc::new(Float32Array::from(vec![1., 2., 3.])),
                Arc::new(Float64Array::from(vec![9., 8., 7.])),
                Arc::new(UInt64Array::from(vec![4, 5, 6])),
            ],
        )?;
```

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @Asura7969 @

**Comment by Dandandan** [comment]
Thanks @Asura7969 and @alamb @jackwener for the review
