### PR TITLE
Fix can not load parquet table form spark in datafusion-cli.

### LINKED ISSUE #1648: Cannot query parquet files generated by Apache Spark from datafusion-cli
**Describe the bug**

I have a data set created by Apache Spark and I tried to query it from the DataFusion CLI. It failed, saying that a parquet file was corrupt.

```
 CREATE EXTERNAL TABLE store_sales STORED AS PARQUET LOCATION 'store_sales.dat';
0 rows in set. Query took 0.002 seconds.
❯ select count(*) from store_sales;
Parquet reader thread terminated due to error: ParquetError(General("Invalid Parquet file. Corrupt footer"))
```

I added some debug logging and found that it was actually trying to read the following file, which is not a Parquet file.

```
store_sales.dat/.part-00005-5142b177-bacb-499d-b14f-12de4b94d9d9-c000.snappy.parquet.crc
```

**To Reproduce**
Create a non-Parquet file with a non-Parquet extension and put it in a directory along with some valid parquet files.

**Expected behavior**
Should only try and read files with file extension `.parquet`.

**Additional context**
None

### PR DESCRIPTION
**Pull request by Ted-Jiang**
# Which issue does this PR close?

Closes #1648.

 # Rationale for this change
We should filter out some path in list_file method,

like
https://github.com/apache/spark/blob/5b91381b9bcea27b7be6d9cef852efbd6c23d98a/core/src/main/scala/org/apache/spark/util/HadoopFSUtils.scala#L358

# Some question

I am not sure is this situation in same on S3 or other object store?
Should we add a method in struct `ObjectReader` like `should_filter_out `

### CODE REVIEW

**Comment by Ted-Jiang** [comment]
@houqp @andygrove Could you give me some advice?

File: datafusion/src/datasource/object_store/mod.rs [hunk 1]
```diff
@@ -141,7 +141,7 @@ pub trait ObjectStore: Sync + Send + Debug {
         let suffix = suffix.to_owned();
         Ok(Box::pin(file_stream.filter(move |fr| {
             let has_suffix = match fr {
-                Ok(f) => f.path().ends_with(&suffix),
+                Ok(f) => f.path().ends_with(&suffix) && !should_filter_out(f.path()),
```
Comment (Jimexist) [inline datafusion/src/datasource/object_store/mod.rs:144]: can you combine both logic into a more cohesive helper function

Comment (Ted-Jiang) [reply datafusion/src/datasource/object_store/mod.rs]: @Jimexist Thanks, have merged into one func

File: datafusion/src/datasource/object_store/mod.rs [hunk 2]
```diff
@@ -159,6 +159,16 @@ pub trait ObjectStore: Sync + Send + Debug {
     /// Get object reader for one file
     fn file_reader(&self, file: SizedFile) -> Result<Arc<dyn ObjectReader>>;
 }
+/// Checks if we should filter out this path name
+/// https://github.com/apache/spark/blob/5b91381b9bcea27b7be6d9cef852efbd6c23d98a/core/src/main/scala/org/apache/spark/util/HadoopFSUtils.scala#L358
+fn do_path_filter_with_suffix(path: &str, suffix: &str) -> bool {
+    let exclude = path.starts_with('_') && !path.contains('=')
+        || path.starts_with('.')
+        || path.ends_with("._COPYING_");
```
Comment (Jimexist) [inline datafusion/src/datasource/object_store/mod.rs:167]: Conflicting logic with parquet suffix

Comment (Ted-Jiang) [reply datafusion/src/datasource/object_store/mod.rs:167]: > Conflicting logic with parquet suffix

IMHO, when suffix is empty `String::new()` will skip xxx._COPYING_

Comment (Ted-Jiang) [reply datafusion/src/datasource/object_store/mod.rs:167]: Sometimes read parquet file not pass the suffix option

File: datafusion/src/datasource/object_store/mod.rs [hunk 3]
```diff
@@ -141,7 +141,7 @@ pub trait ObjectStore: Sync + Send + Debug {
         let suffix = suffix.to_owned();
         Ok(Box::pin(file_stream.filter(move |fr| {
             let has_suffix = match fr {
-                Ok(f) => f.path().ends_with(&suffix),
+                Ok(f) => do_path_filter_with_suffix(f.path(), &suffix),
```
Comment (houqp) [inline datafusion/src/datasource/object_store/mod.rs:144]: Forcing the filter here will restrict the usefullness of the object store abstraction. for example, I won't be able to use `list_file_with_suffix` in delta-rs to manage delta lake metadata. Object store should be a very generic module that is agnostic of this type of application specific file naming conventions. I think a better place to host this particular logic is in the ListingTable struct.

File: datafusion/src/physical_plan/file_format/parquet.rs [hunk 4]
```diff
@@ -217,6 +217,7 @@ impl ExecutionPlan for ParquetExec {
 
         let file_schema_ref = self.base_config().file_schema.clone();
         let join_handle = task::spawn_blocking(move || {
+            let f = partition.clone();
```
Comment (houqp) [inline datafusion/src/physical_plan/file_format/parquet.rs:220]: perhaps we can pass partition as a reference to `read_partition` to avoid the clone here? I noticed read_partition is already perfoming clone inside.

File: datafusion/src/datasource/object_store/mod.rs [hunk 5]
```diff
@@ -159,6 +159,16 @@ pub trait ObjectStore: Sync + Send + Debug {
...
 }
+/// Checks if we should filter out this path name
+/// https://github.com/apache/spark/blob/5b91381b9bcea27b7be6d9cef852efbd6c23d98a/core/src/main/scala/org/apache/spark/util/HadoopFSUtils.scala#L358
+fn do_path_filter_with_suffix(path: &str, suffix: &str) -> bool {
+    let exclude = path.starts_with('_') && !path.contains('=')
+        || path.starts_with('.')
+        || path.ends_with("._COPYING_");
+    let include = path.starts_with("_common_metadata") || path.starts_with("_metadata");
+    let is_suffix = path.ends_with(suffix);
+    (!exclude || include) && is_suffix
```
Comment (houqp) [inline datafusion/src/datasource/object_store/mod.rs:170]: i recommend changing up the evaluation order so we can perform early exit and avoid unnecessary string operations. For example:

```rust
if !path.ends_with(suffix) {
    return false;
}

let exclude = ....;
if exlude {
    let include = path.starts_with("_common_metadata") || path.starts_with("_metadata");
    if !include {
        return false;
    }
} 

return true;
```

File: datafusion/src/datasource/object_store/mod.rs (hunk 2 above)
Comment (houqp) [reply datafusion/src/datasource/object_store/mod.rs:167]: > Sometimes read parquet file not pass the suffix option

Isn't this a bug we should also fix?

Comment (Ted-Jiang) [reply datafusion/src/datasource/object_store/mod.rs:167]: @houqp  thanks a lot for your kindly advice! i have find the path of `datafusion-cli` read parquet file.
https://github.com/apache/arrow-datafusion/blob/7153fac7d8ff77c71a67cd2ba3ec55d94a4cd794/datafusion/src/execution/context.rs#L227
before:
`
❯ create external table cus stored as PARQUET location '~project/DataFusion/benchmarks/benchmarks/data/tpch-1g-oneFile/customer';

ParquetError(General("Invalid Parquet file. Corrupt footer"))

after fix 
❯ create external table cus stored as PARQUET location '~project/DataFusion/benchmarks/benchmarks/data/tpch-1g-oneFile/customer'
0 rows in set. Query took 0.007 seconds.

File: datafusion/src/datasource/object_store/mod.rs (hunk 3 above)
Comment (Ted-Jiang) [reply datafusion/src/datasource/object_store/mod.rs:144]: @houqp  thanks a lot for your kindly explain!  
i got that object_store should be highly abstract. This filter login from spark is in `HadoopFSUtils`. So i think maybe i will keep the code clean, put this in out customized ObjectStore for hadoop.

File: datafusion/src/physical_plan/file_format/parquet.rs (hunk 4 above)
Comment (Ted-Jiang) [reply datafusion/src/physical_plan/file_format/parquet.rs:220]: fixed

**Comment by Ted-Jiang** [comment]
@houqp  Could please take a look?

**Review by houqp — APPROVED** [review]
LGTM

**Comment by houqp** [comment]
Nice work @Ted-Jiang :+1: @Jimexist @alamb you want to take a final look?

**Review by Jimexist — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @Ted-Jiang
