### PR TITLE
Enforce ambiguity check whilst normalizing columns

### LINKED ISSUE #5211: Dataframe methods don't do ambiguity checks
**Describe the bug**

Following Dataframe methods don't do ambiguity checks, and will usually take the first found column even if it is ambiguous:

- [ ] filter(...)
- [ ] select(...)
- [ ] sort(...)
  - Related, but seems this issue occurs for SQL as well. Raised separate issue: https://github.com/apache/arrow-datafusion/issues/5248
- [ ] aggregate(...)
  - Related issue for SQL: https://github.com/apache/arrow-datafusion/issues/5251

with_column_renamed(...)
  - Will do a no-op
  - Edit: issue seems to stem from with_column_renamed(...) explicitly comparing only qualified names
  - Is a separate issue: https://github.com/apache/arrow-datafusion/issues/4428

**To Reproduce**

Filter example:

```rust
    let schema = Arc::new(Schema::new(vec![
        Field::new("a", DataType::Utf8, false),
        Field::new("b", DataType::Int32, false),
    ]));
    let batch = RecordBatch::try_new(
        schema,
        vec![
            Arc::new(StringArray::from_slice(["a", "b", "c", "d"])),
            Arc::new(Int32Array::from_slice([1, 10, 10, 100])),
        ],
    )?;
    let ctx = SessionContext::new();
    ctx.register_batch("t1", batch.clone())?;
    ctx.register_batch("t2", batch)?;
    ctx.table("t1")
        .await?
        .join(
            ctx.table("t2").await?,
            JoinType::Inner,
            &["a"],
            &["a"],
            None,
        )?
        .filter(col("b").eq(lit(1)))? // ambiguous b
        .explain(false, false)?
        .show()
        .await?;
```

Will execute fine:

```sql
+---------------+--------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                     |
+---------------+--------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Inner Join: t1.a = t2.a                                                                                                  |
|               |   Filter: t1.b = Int32(1)                                                                                                |
|               |     TableScan: t1 projection=[a, b]                                                                                      |
|               |   TableScan: t2 projection=[a, b]                                                                                        |
| physical_plan | CoalesceBatchesExec: target_batch_size=8192                                                                              |
|               |   HashJoinExec: mode=Partitioned, join_type=Inner, on=[(Column { name: "a", index: 0 }, Column { name: "a", index: 0 })] |
|               |     CoalesceBatchesExec: target_batch_size=8192                                                                          |
|               |       RepartitionExec: partitioning=Hash([Column { name: "a", index: 0 }], 12), input_partitions=12                      |
|               |         CoalesceBatchesExec: target_batch_size=8192                                                                      |
|               |           FilterExec: b@1 = 1                                                                                            |
|               |             RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                                        |
|               |               MemoryExec: partitions=1, partition_sizes=[1]                                                              |
|               |     CoalesceBatchesExec: target_batch_size=8192                                                                          |
|               |       RepartitionExec: partitioning=Hash([Column { name: "a", index: 0 }], 12), input_partitions=12                      |
|               |         RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                                            |
|               |           MemoryExec: partitions=1, partition_sizes=[1]                                                                  |
|               |                                                                                                                          |
+---------------+--------------------------------------------------------------------------------------------------------------------------+
```

**Expected behavior**

Should raise error

**Additional context**

For filter, similar has been addressed for SQL queries: https://github.com/apache/arrow-datafusion/issues/4196

### LINKED ISSUE #5248: SQL ORDER BY doesn't do ambiguity check
**Describe the bug**

In SQL when ORDER BY an ambiguous column, it doesn't return an error.

**To Reproduce**

```sql
❯ select * from test1 t1 join test2 t2 using (a) order by b;
+---+---+---+---+---+
| a | b | c | b | c |
+---+---+---+---+---+
| 1 | 2 | 3 | 2 | 3 |
| 4 | 5 | 6 | 5 | 6 |
+---+---+---+---+---+
2 rows in set. Query took 0.016 seconds.
❯ explain select * from test1 t1 join test2 t2 using (a) order by b;
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                          |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: t1.a, t1.b, t1.c, t2.b, t2.c                                                                                                                      |
|               |   Sort: t1.b ASC NULLS LAST                                                                                                                                   |
|               |     Projection: t1.a, t1.b, t1.c, t2.b, t2.c                                                                                                                  |
|               |       Inner Join: Using t1.a = t2.a                                                                                                                           |
|               |         SubqueryAlias: t1                                                                                                                                     |
|               |           TableScan: test1 projection=[a, b, c]                                                                                                               |
|               |         SubqueryAlias: t2                                                                                                                                     |
|               |           TableScan: test2 projection=[a, b, c]                                                                                                               |
| physical_plan | ProjectionExec: expr=[a@0 as a, b@1 as b, c@2 as c, b@3 as b, c@4 as c]                                                                                       |
|               |   SortPreservingMergeExec: [b@1 ASC NULLS LAST]                                                                                                               |
|               |     SortExec: [b@1 ASC NULLS LAST]                                                                                                                            |
|               |       ProjectionExec: expr=[a@0 as a, b@1 as b, c@2 as c, b@4 as b, c@5 as c]                                                                                 |
|               |         CoalesceBatchesExec: target_batch_size=8192                                                                                                           |
|               |           HashJoinExec: mode=Partitioned, join_type=Inner, on=[(Column { name: "a", index: 0 }, Column { name: "a", index: 0 })]                              |
|               |             CoalesceBatchesExec: target_batch_size=8192                                                                                                       |
|               |               RepartitionExec: partitioning=Hash([Column { name: "a", index: 0 }], 12), input_partitions=12                                                   |
|               |                 RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                                                                         |
|               |                   CsvExec: files={1 group: [[home/jeffrey/Code/arrow-datafusion/datafusion-cli/test.csv]]}, has_header=true, limit=None, projection=[a, b, c] |
|               |             CoalesceBatchesExec: target_batch_size=8192                                                                                                       |
|               |               RepartitionExec: partitioning=Hash([Column { name: "a", index: 0 }], 12), input_partitions=12                                                   |
|               |                 RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                                                                         |
|               |                   CsvExec: files={1 group: [[home/jeffrey/Code/arrow-datafusion/datafusion-cli/test.csv]]}, has_header=true, limit=None, projection=[a, b, c] |
|               |                                                                                                                                                               |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set. Query took 0.011 seconds.
```

**Expected behavior**

Should return error

**Additional context**

The same query on latest Postgres raises an error about the ambiguity

### LINKED ISSUE #5251: SQL GROUP BY doesn't do ambiguity check
**Describe the bug**

In SQL when GROUP BY an ambiguous column, it doesn't return an error.

**To Reproduce**

```sql
❯ select * from test1 t1 join test2 t2 using (a);
+---+---+---+---+---+
| a | b | c | b | c |
+---+---+---+---+---+
| 1 | 2 | 3 | 2 | 3 |
| 4 | 5 | 6 | 5 | 6 |
+---+---+---+---+---+
2 rows in set. Query took 0.013 seconds.
❯ select max(a) from test1 t1 join test2 t2 using (a) group by c;
+-----------+
| MAX(t1.a) |
+-----------+
| 1         |
| 4         |
+-----------+
2 rows in set. Query took 0.014 seconds.
❯ explain select max(a) from test1 t1 join test2 t2 using (a) group by c;
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                         |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: MAX(t1.a)                                                                                                                                        |
|               |   Aggregate: groupBy=[[t1.c]], aggr=[[MAX(t1.a)]]                                                                                                            |
|               |     Inner Join: Using t1.a = t2.a                                                                                                                            |
|               |       SubqueryAlias: t1                                                                                                                                      |
|               |         TableScan: test1 projection=[a, c]                                                                                                                   |
|               |       SubqueryAlias: t2                                                                                                                                      |
|               |         TableScan: test2 projection=[a]                                                                                                                      |
| physical_plan | ProjectionExec: expr=[MAX(t1.a)@1 as MAX(t1.a)]                                                                                                              |
|               |   AggregateExec: mode=FinalPartitioned, gby=[c@0 as c], aggr=[MAX(t1.a)]                                                                                     |
|               |     CoalesceBatchesExec: target_batch_size=8192                                                                                                              |
|               |       RepartitionExec: partitioning=Hash([Column { name: "c", index: 0 }], 12), input_partitions=12                                                          |
|               |         AggregateExec: mode=Partial, gby=[c@1 as c], aggr=[MAX(t1.a)]                                                                                        |
|               |           CoalesceBatchesExec: target_batch_size=8192                                                                                                        |
|               |             HashJoinExec: mode=Partitioned, join_type=Inner, on=[(Column { name: "a", index: 0 }, Column { name: "a", index: 0 })]                           |
|               |               CoalesceBatchesExec: target_batch_size=8192                                                                                                    |
|               |                 RepartitionExec: partitioning=Hash([Column { name: "a", index: 0 }], 12), input_partitions=12                                                |
|               |                   RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                                                                      |
|               |                     CsvExec: files={1 group: [[home/jeffrey/Code/arrow-datafusion/datafusion-cli/test.csv]]}, has_header=true, limit=None, projection=[a, c] |
|               |               CoalesceBatchesExec: target_batch_size=8192                                                                                                    |
|               |                 RepartitionExec: partitioning=Hash([Column { name: "a", index: 0 }], 12), input_partitions=12                                                |
|               |                   RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                                                                      |
|               |                     CsvExec: files={1 group: [[home/jeffrey/Code/arrow-datafusion/datafusion-cli/test.csv]]}, has_header=true, limit=None, projection=[a]    |
|               |                                                                                                                                                              |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set. Query took 0.007 seconds.
```

**Expected behavior**

Should return error

**Additional context**

The same query on latest Postgres raises an error about the ambiguity

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #5211, Closes #5248, Closes #5251

# Rationale for this change

Rather than having separate steps for doing ambiguity checks on unqualified columns and then normalizing them, will enforce ambiguity check during normalization (turning into qualified column). This way will not have to keep adding ambiguity checks for different paths (see issues listing which paths were missing these checks)

# What changes are included in this PR?

Introduce new unqualified column normalization methods to enforce ambiguity checks. Change old usages of the normalization method to use this new method.

# Are these changes tested?

Added extra ambiguity tests

# Are there any user-facing changes?

Deprecated some methods (though unsure if they were intended to be user facing in the first place, vs being intended for use in other datafusion crates)

### CODE REVIEW

File: datafusion/common/src/column.rs [hunk 1]
```diff
@@ -102,6 +102,10 @@ impl Column {
     /// In this case, both `t1.id` and `t2.id` will match unqualified column `id`. To express this possibility, use
     /// `using_columns`. Each entry in this array is a set of columns that are bound together via a `USING` clause. So
     /// in this example this would be `[{t1.id, t2.id}]`.
+    #[deprecated(
+        since = "20.0.0",
+        note = "use normalize_with_schemas_and_ambiguity_check instead"
+    )]
```
Comment (Jefffrey) [inline datafusion/common/src/column.rs:108]: ive marked old methods as deprecated as unsure if should remove (breaking api change technically?)

File: datafusion/common/src/column.rs [hunk 2]
```diff
@@ -154,6 +158,105 @@ impl Column {
...
+    /// ```
+    ///
+    /// Will search for a matching field in all schemas in the first level. If a matching field according to above
+    /// mentioned conditions is not found, then will check the next level. If found more than one matching column across
+    /// all schemas in a level, that isn't a USING column, will return an error due to ambiguous column.
+    ///
+    /// If checked all levels and couldn't find field, will return field not found error.
+    pub fn normalize_with_schemas_and_ambiguity_check(
+        self,
+        schemas: &[&[&DFSchema]],
```
Comment (Jefffrey) [inline datafusion/common/src/column.rs:200]: kinda ugly syntax here. it makes the logic work, but maybe could have something better?

File: datafusion/expr/src/logical_plan/plan.rs [hunk 3]
```diff
@@ -174,7 +174,26 @@ impl LogicalPlan {
...
+            | LogicalPlan::Unnest(_)
+            | LogicalPlan::Join(_)
+            | LogicalPlan::CrossJoin(_) => self
+                .inputs()
+                .iter()
+                .map(|input| input.schema().as_ref())
+                .collect(),
+            _ => vec![],
+        }
+    }
```
Comment (Jefffrey) [inline datafusion/expr/src/logical_plan/plan.rs:193]: since previous column normalization depended on all_schemas, which i still dont fully understand, this method extracts the part from all_schemas which returns the self & the child schemas, but only returns child schema

meant to be used as a fallback to the new normalization method

File: datafusion/substrait/src/logical_plan/consumer.rs [hunk 4]
```diff
@@ -505,10 +505,14 @@ pub async fn from_substrait_rex(
...
-                        name: input_schema.field(x.field as usize).name().to_string(),
-                    }))),
+                    None => {
+                        let column =
+                            input_schema.field(x.field as usize).qualified_column();
+                        Ok(Arc::new(Expr::Column(Column {
+                            relation: column.relation,
+                            name: column.name,
+                        })))
+                    }
```
Comment (Jefffrey) [inline datafusion/substrait/src/logical_plan/consumer.rs:515]: this is a separate substrait fix, since it previously wasn't qualifying the column built even if the column itself was qualified

**Comment by alamb** [comment]
I plan to review this carefully tomorrow

File: datafusion/expr/src/logical_plan/plan.rs (hunk 3 above)
Comment (alamb) [reply datafusion/expr/src/logical_plan/plan.rs:193]: maybe @houqp  can provide some historical context about why all schemas is needed (maybe it was for UNIONs or JOINs?)

It may also be for a limitation that no longer exists.

cc @waynexia  who I think may also have hit this recently

File: datafusion/common/src/column.rs (hunk 2 above)
Comment (alamb) [reply datafusion/common/src/column.rs:200]: This syntax is nasty but it makes the callsites better, in my opinion

**Review by alamb — COMMENTED** [review]
Thank you @Jefffrey  -- this look good and well documented / explained to me -- a nice cleanup as well.

cc @mingmwang  @ygf11  and @jackwener  who I think have been working in this code recently and may have some thoughts

**Review by alamb — APPROVED** [review]

File: datafusion/expr/src/logical_plan/builder.rs [hunk 5]
```diff
@@ -947,16 +939,16 @@ impl LogicalPlanBuilder {
...
+                    &[&[self.plan.schema(), right.schema()]],
                     &[left_using_columns],
                 )?;
 
                 let right_using_columns = right_key.to_columns()?;
-                let normalized_right_key = normalize_col_with_schemas(
+                let normalized_right_key = normalize_col_with_schemas_and_ambiguity_check(
                     right_key,
-                    &[self.plan.schema(), right.schema()],
+                    &[&[self.plan.schema(), right.schema()]],
```
Comment (ygf11) [inline datafusion/expr/src/logical_plan/builder.rs:951]: This improvement makes sense to me.

We can replace `join_detailed` with `join_with_expr_keys`, and remove `join_detailed` after this pr.
https://github.com/apache/arrow-datafusion/blob/9587339b0fb060f8d153bbb0f8de6a740195ccea/datafusion/expr/src/logical_plan/builder.rs#L568
https://github.com/apache/arrow-datafusion/blob/9587339b0fb060f8d153bbb0f8de6a740195ccea/datafusion/expr/src/logical_plan/builder.rs#L928

**Comment by alamb** [comment]
Thank you @ygf11  for the review

I plan to merge this PR tomorrow unless anyone else would like more time to review.

**Comment by alamb** [comment]
Thanks again @Jefffrey

File: datafusion/expr/src/utils.rs [hunk 6]
```diff
@@ -96,41 +96,7 @@ pub fn expr_to_columns(expr: &Expr, accum: &mut HashSet<Column>) -> Result<()> {
...
-            | Expr::InList { .. }
-            | Expr::Exists { .. }
-            | Expr::InSubquery { .. }
-            | Expr::ScalarSubquery(_)
-            | Expr::Wildcard
-            | Expr::QualifiedWildcard { .. }
-            | Expr::GetIndexedField { .. }
-            | Expr::Placeholder { .. } => {}
+            _ => {}
         }
```
Comment (mingmwang) [inline datafusion/expr/src/utils.rs:100]: I would suggest keeping the explicit pattern matching instead of a default implementation.  In future someone might add new Expr types and it is safe to use  explicit pattern matching and force the committer to check all the places.

Comment (alamb) [reply datafusion/expr/src/utils.rs:100]: I will prepare a PR

File: datafusion/sql/src/select.rs [hunk 7]
```diff
@@ -241,33 +236,26 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
+
+                let fallback_schemas = plan.fallback_normalize_schemas();
+                let outer_query_schema = if let Some(outer) = outer_query_schema {
                     join_schema.merge(outer);
-                }
-                let x: Vec<&DFSchemaRef> = all_schemas.iter().collect();
+                    vec![outer]
+                } else {
+                    vec![]
+                };
```
Comment (mingmwang) [inline datafusion/sql/src/select.rs:251]: The join schema logic is problematic. I will fix it in other PR.  The filter_expr might contains
