### PR TITLE
Fix a race condition issue on reading spilled file

### LINKED ISSUE #7523: Intermittent Windows CI failure in "physical_plan::sorts::sort::tests::test_sort_fetch_memory_calculation"
### Describe the bug

CI tests begin failing like this on windows

https://github.com/apache/arrow-datafusion/actions/runs/6142807589/job/16665135902

```
---- physical_plan::sorts::sort::tests::test_sort_fetch_memory_calculation stdout ----
Error: Execution("Spawned Task error: IO error: The system cannot find the file specified. (os error 2)")
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

It appears to be intermittent

Here is a failure:
https://github.com/apache/arrow-datafusion/actions/runs/6136441131/job/16651296580

But then it passed on the following run 
https://github.com/apache/arrow-datafusion/actions/runs/6137534894/job/16653912130

An then it failed again on the next run
https://github.com/apache/arrow-datafusion/actions/runs/6142807589/job/16665135902

My suspicion is it is related to https://github.com/apache/arrow-datafusion/pull/7510 from @viirya  that started reporting spill file errors

### LINKED ISSUE #7537: Reading spilled file rarely fails
### Describe the bug

I noticed a test `sort::tests::test_sort_fetch_memory_calculation` fails very rarely (approximately once in hundred times).
```
[2023-09-13T05:07:29Z ERROR datafusion::physical_plan::sorts::sort] Failure while reading spill file: NamedTempFile("/tmp/.tmp9wH6tP/.tmptarqTV"). Error: IO error: No such file or directory (os error 2)
test physical_plan::sorts::sort::tests::test_sort_fetch_memory_calculation ... FAILED

failures:

---- physical_plan::sorts::sort::tests::test_sort_fetch_memory_calculation stdout ----
Error: Execution("Spawned Task error: IO error: No such file or directory (os error 2)")


failures:
    physical_plan::sorts::sort::tests::test_sort_fetch_memory_calculation

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1702 filtered out; finished in 1.04s
```

This seems a kind of race condition issue.

### To Reproduce

You can reproduce this using this script.
```
for i in {1..500}; do
  if ! cargo test sort::tests::test_sort_fetch_memory &> /tmp/err.out; then
    cat /tmp/err.out; break;
fi
done
```

Or, insert a sleep to `sort.rs` like as follows.
```
diff --git a/datafusion/core/src/physical_plan/sorts/sort.rs b/datafusion/core/src/physical_plan/sorts/sort.rs
index 82badb7d8..3feedfd71 100644
--- a/datafusion/core/src/physical_plan/sorts/sort.rs
+++ b/datafusion/core/src/physical_plan/sorts/sort.rs
@@ -616,6 +616,7 @@ fn read_spill_as_stream(
     let sender = builder.tx();
 
     builder.spawn_blocking(move || {
+        std::thread::sleep(std::time::Duration::from_secs(1));
         let result = read_spill(sender, path.path());
         if let Err(e) = &result {
             error!("Failure while reading spill file: {:?}. Error: {}", path, e);
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sarutak**
## Which issue does this PR close?

Closes #7537, 
Closes #7523
Closes https://github.com/apache/arrow-datafusion/issues/7546

## Rationale for this change
This issue seems a potential race condition issue.
To improve the stability, this issue need to be fixed.

## What changes are included in this PR?
This issue happens when the parent directory of spilled files are deleted before being read.
The root cause is `TempDir` of the parent directory can be dropped if [this async block](https://github.com/apache/arrow-datafusion/blob/561e0d7e87825aba224bf2eb9c3b8b5e1b725597/datafusion/core/src/physical_plan/sorts/sort.rs#L870) exits before [the reading task](https://github.com/apache/arrow-datafusion/blob/561e0d7e87825aba224bf2eb9c3b8b5e1b725597/datafusion/core/src/physical_plan/sorts/sort.rs#L618) starts like as follows.

1. Exit the [async block](https://github.com/apache/arrow-datafusion/blob/561e0d7e87825aba224bf2eb9c3b8b5e1b725597/datafusion/core/src/physical_plan/sorts/sort.rs#L870)
2. `sorter` and it's members are dropped including `DiskManager::local_dirs`.
3. `TempFile` in `local_dirs` are dropped then the corresponding temporary directories are deleted recursively.
4. The [reading task](https://github.com/apache/arrow-datafusion/blob/561e0d7e87825aba224bf2eb9c3b8b5e1b725597/datafusion/core/src/physical_plan/sorts/sort.rs#L618) starts

~~To avoid breaking API compatibility, this change proposes to not use `TempDir` and let the DiskManager directly creates temporary spilled file in `local_dirs`.~~

**UPDATE:** After [the discussion](https://github.com/apache/arrow-datafusion/pull/7538#pullrequestreview-1624316842), I prefer the second solution below.

I have another solution but it breaks the API compatibility of `DiskManager::create_tmp_file`, which returns a pair of `Arc<TempDir>` and `NamedTempFile` to ensure `TempDir` lives long enough.

~~Spilled files are represented as `NamedTempFile` and temporary files are deleted when `NamedTempFile::drop` is called.
So, I think not using `TempDir` is not a problem.~~

## Are these changes tested?
Added new test.

## Are there any user-facing changes?
No.

### CODE REVIEW

File: datafusion/execution/src/disk_manager.rs [hunk 1]
```diff
@@ -71,11 +72,11 @@ impl DiskManagerConfig {
...
 #[derive(Debug)]
 pub struct DiskManager {
-    /// TempDirs to put temporary files in.
+    /// Dirs to put temporary files in.
     ///
-    /// If `Some(vec![])` a new OS specified temporary directory will be created
+    /// If `Some(vec![])` temporary files will be created in the directories.
     /// If `None` an error will be returned (configured not to spill)
-    local_dirs: Mutex<Option<Vec<TempDir>>>,
+    local_dirs: Mutex<Option<Vec<PathBuf>>>,
```
Comment (alamb) [inline datafusion/execution/src/disk_manager.rs:79]: Am I correct in understanding that the implication here is that the directories in `local_dirs` will not be removed (though all the contents will be removed, when the `NamedTempFile` are dropped)?

**Review by alamb — COMMENTED** [review]
Thank you @sarutak . Very excellent debugging ❤️ 

I think this PR will result in DataFusion leaving many temporary directories around, which is likely not ideal for many users. 

I am not sure if you have seen the fix for the test from @viirya  in https://github.com/apache/arrow-datafusion/pull/7534 

> I have another solution but it breaks the API compatibility of DiskManager::create_tmp_file, which returns a pair of Arc<TempDir> and NamedTempFile to ensure TempDir lives long enough.

I think this is the solution that we should pursue as it is the easiest to use long term. Perhaps we can change the API to return something like

```rust
/// A named temporary file and the directory it lives in, which may be cleaned up on drop
struct RefCountedTempFile {
  /// directory in which temporary files are created
  temp_dir: Arc<TempDir>,
  ///  the temporary file
  tempfile: NamedTempFile,
}

impl RefCountedTempFile {
  pub fn path(&self) -> &Path {..}
  pub fn inner(&self) -> &NamedTempFile {...}
...
}

impl DiskManager {

pub fn create_tmp_file(
    &self,
    request_description: &str
) -> Result<RefCountedTempFile, DataFusionError>
...
}

```

Another potential solution I thought of was to pass a reference to the DiskManager to `read_spill_as_stream` to prevent the file from being deleted. However, that seems like a hard API to use and get right as all callers would have to know temp files were only scoped to the lifetime of the DiskManager

**Comment by sarutak** [comment]
Thank you for the comment @alamb .
> I am not sure if you have seen the fix for the test from @viirya in https://github.com/apache/arrow-datafusion/pull/7534

I've seen that PR but I don't think it's just an issue of the test.

> I think this is the solution that we should pursue as it is the easiest to use long term. Perhaps we can change the API to return something like

This is what I implied. If we can change the API, I'll propose the second solution.

> Another potential solution I thought of was to pass a reference to the DiskManager to read_spill_as_stream to prevent the file from being deleted

Yes, I also thought of this solution. But I thought it's too much.

File: datafusion/execution/src/disk_manager.rs (hunk 1 above)
Comment (sarutak) [reply datafusion/execution/src/disk_manager.rs:79]: This solution uses directories specified, or returned by `std::env::temp_dir()`, which is usually `/tmp` on Linux.
So, these directories are not deleted when the `NamedTempFile` are dropped.

**Comment by alamb** [comment]
# Suggested next actions:
1. I think we should merge https://github.com/apache/arrow-datafusion/pull/7534  to get the CI stable again
2. I filed https://github.com/apache/arrow-datafusion/issues/7546 to track the underlying problem
3. We should fix https://github.com/apache/arrow-datafusion/issues/7546 (either using this approach in this PR or some other approach)

Thank you @viirya and @sarutak for all the work

File: datafusion/execution/src/disk_manager.rs [hunk 2]
```diff
@@ -125,32 +126,61 @@ impl DiskManager {
...
-    local_dirs.iter().try_for_each(|root| -> Result<()> {
-        if !std::path::Path::new(root).exists() {
-            std::fs::create_dir(root)?;
-        }
-        Ok(())
-    })
+/// A named temporary file and the directory it lives in, which may be clean up on drop
+#[derive(Debug)]
+pub struct RefCountedTempFile {
+    /// directory in which temporary files are created
```
Comment (alamb) [inline datafusion/execution/src/disk_manager.rs:153]:
```suggestion
    /// directory in which temporary files are created (Arc is held to ensure
    /// it is not cleaned up prior to the NamedTempFile)
```

**Review by alamb — APPROVED** [review]
I think this PR looks good -- thank you @sarutak .

File: datafusion/execution/src/disk_manager.rs [hunk 3]
```diff
@@ -131,18 +134,41 @@ impl DiskManager {
...
+        Ok(RefCountedTempFile {
+            parent_temp_dir: local_dirs[dir_index].clone(),
+            tempfile: Builder::new()
+                .tempfile_in(local_dirs[dir_index].as_ref())
+                .map_err(DataFusionError::IoError)?,
+        })
+    }
+}
+
+/// A wrapper around a [`NamedTemporaryFile`] that also contains a reference
```
Comment (sarutak) [inline datafusion/execution/src/disk_manager.rs:150]: It's `NamedTempFile`, not `NamedTemporaryFile`. I'll fix it.

**Comment by viirya** [comment]
> > I am not sure if you have seen the fix for the test from @viirya in #7534
> 
> I've seen that PR but I don't think it's just an issue of the test.

Thanks @alamb and @sarutak.

Yea, as I commented in #7534 and @alamb's description in #7546, for DataFusion users this is not likely an issue except for the cases like the test that you construct physical query plan (like we did internally also) and execute it. So my idea was to propose a simplest fix to the test. As this doesn't look like a urgent bug to fix, I was thinking to find some time later to propose another fix to avoid `TaskContext` to be dropped in sort execution plan, but not long after I saw this PR was proposed. 😄

**Review by viirya — APPROVED** [review]

File: datafusion/execution/src/disk_manager.rs [hunk 4]
```diff
@@ -131,18 +134,41 @@ impl DiskManager {
...
+        Ok(RefCountedTempFile {
+            parent_temp_dir: local_dirs[dir_index].clone(),
+            tempfile: Builder::new()
+                .tempfile_in(local_dirs[dir_index].as_ref())
+                .map_err(DataFusionError::IoError)?,
+        })
+    }
+}
+
+/// A wrapper around a [`NamedTempFile`] that also contains a reference
```
Comment (viirya) [inline datafusion/execution/src/disk_manager.rs:150]:
```suggestion
/// A wrapper around a [`NamedTempFile`] that also contains a reference to its parent temporary directory
```

**Comment by sarutak** [comment]
> So my idea was to propose a simplest fix to the test. As this doesn't look like a urgent bug to fix, I was thinking to find some time later to propose another fix to avoid TaskContext to be dropped in sort execution plan, but not long after I saw this PR was proposed. 😄

Yeah, thank you for recovering CI quickly!

**Comment by alamb** [comment]
Thanks again @sarutak
