### PR TITLE
fix(9678): short circuiting prevented population of visited stack, for common subexpr elimination optimization

### LINKED ISSUE #9678: Regression: incorrect result for aliased arguments in select list after TreeNode rewrite
### Describe the bug

While updating DataFusion in InfluxDB we found what appears to be a bug in common_subexpr_eliminate that causes incorrect answers that seems to have come in via the `TreeNode` refactor in https://github.com/apache/arrow-datafusion/pull/8891



### To Reproduce


```sql
> create table m(f64 double) as values (10.1);
0 rows in set. Query took 0.038 seconds.


-- This query is correct (note that acos is 1.471623942988976)
❯ select f64, coalesce(1.0 / f64, 0.0), acos(coalesce(1.0 / f64, 0.0)) from m;
+------+-----------------------------------------+-----------------------------------------------+
| f64  | coalesce(Float64(1) / m.f64,Float64(0)) | acos(coalesce(Float64(1) / m.f64,Float64(0))) |
+------+-----------------------------------------+-----------------------------------------------+
| 10.1 | 0.09900990099009901                     | 1.471623942988976                             |
+------+-----------------------------------------+-----------------------------------------------+
1 row in set. Query took 0.001 seconds.

-- However, when I add an alias `as f64_1` to the second argument the query is now incorrect (the acos ...) term now is `0.09900990099009901 which is the same as 1/10.1`)

❯ select f64, coalesce(1.0 / f64, 0.0) as f64_1, acos(coalesce(1.0 / f64, 0.0)) from m;
+------+---------------------+-----------------------------------------------+
| f64  | f64_1               | acos(coalesce(Float64(1) / m.f64,Float64(0))) |
+------+---------------------+-----------------------------------------------+
| 10.1 | 0.09900990099009901 | 0.09900990099009901                           |
+------+---------------------+-----------------------------------------------+
1 row in set. Query took 0.002 seconds.

```



### Expected behavior


The  correct answer is:

```sql
❯ select f64, coalesce(1.0 / f64, 0.0) as f64_1, acos(coalesce(1.0 / f64, 0.0)) from m;
+------+---------------------+-----------------------------------------------+
| f64  | f64_1               | acos(coalesce(Float64(1) / m.f64,Float64(0))) |
+------+---------------------+-----------------------------------------------+
| 10.1 | 0.09900990099009901 | 1.471623942988976                             |
+------+---------------------+-----------------------------------------------+
1 row in set. Query took 0.008 seconds.
```


### Additional context


1. `coalesce` seems to be required to trigger the bug. Removing it from the query results in
```sql
❯ select f64, 1.0/f64  as f64_1, acos(1.0 / f64) from m;
+------+---------------------+--------------------------+
| f64  | f64_1               | acos(Float64(1) / m.f64) |
+------+---------------------+--------------------------+
| 10.1 | 0.09900990099009901 | 1.471623942988976        |
+------+---------------------+--------------------------+
1 row in set. Query took 0.003 seconds.
```

2. It seems to have come in via https://github.com/apache/arrow-datafusion/pull/8891

The bug happens in a84e5f89bd52d59c78f11fffbab89ed1d418538f, but does not happen in 684b4fab75841672aabc4f3c2475e8c232acea20 (the commit right before https://github.com/apache/arrow-datafusion/pull/8891)

```sql
❯ select f64, coalesce(1.0 / f64, 0.0) as f64_1, acos(coalesce(1.0 / f64, 0.0)) from m;
+------+---------------------+-----------------------------------------------+
| f64  | f64_1               | acos(coalesce(Float64(1) / m.f64,Float64(0))) |
+------+---------------------+-----------------------------------------------+
| 10.1 | 0.09900990099009901 | 1.471623942988976                             |
+------+---------------------+-----------------------------------------------+
1 row in set. Query took 0.013 seconds.
```


3. It happens for other functions (like `cos`) even though we only saw it for `acos` in IOx


I tracked the issue down to a problem in common_subexpr_eliminate. You can see the issue via `explain verbose`:

```sql
❯ explain verbose select f64, coalesce(1.0 / f64, 0.0) as f64_1, acos(coalesce(1.0 / f64, 0.0)) from m;
+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type                                                  | plan                                                                                                                                                                                                                                                                              |
+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| initial_logical_plan                                       | Projection: m.f64, coalesce(Float64(1) / m.f64, Float64(0)) AS f64_1, acos(coalesce(Float64(1) / m.f64, Float64(0)))                                                                                                                                                              |
|                                                            |   TableScan: m                                                                                                                                                                                                                                                                    |
...
|
| logical_plan after eliminate_cross_join                    | SAME TEXT AS ABOVE                                                                                                                                                                                                                                                                |
| logical_plan after common_sub_expression_eliminate         | Projection: m.f64, coalesce(Float64(1) / m.f64, Float64(0)) AS f64_1, coalesce(Float64(1) / m.f64, Float64(0)) AS acos(coalesce(Float64(1) / m.f64,Float64(0)))                                                                                                                   |
|                                                            |   Projection: coalesce(Float64(1) / m.f64, Float64(0)) AS coalesce(Float64(1) / m.f64, Float64(0)), m.f64                                                                                                                                                                         |
|                                                            |     TableScan: m                                                                                                                                                                                                                                                                  |
| logical_plan after eliminate_limit                         | SAME TEXT AS ABOVE                                                                                                                                                                                                                                                                |
| logical_plan after propagate_empty_relation                | SAME TEXT AS ABOVE                                                                                                                                                                                                                                                                |
| logical_plan after eliminate_one_union                     | SAME TEXT AS ABOVE
```

You can see `coalesce(Float64(1) / m.f64, Float64(0)) AS acos(coalesce(Float64(1) / m.f64,Float64(0)))` shows clearly the `acos` was removed

### PR DESCRIPTION
**Pull request by wiedld**
## Which issue does this PR close?

Closes #9678 

## Rationale for this change

The TreeNode refactor is awesome, but it seemed to introduce a bug in [common_subexpr_eliminate](https://github.com/apache/arrow-datafusion/issues/9678), specifically for use cases containing short-circuited expressions. The first 2 commits in this PR are the reproducer, and the initial fix.

After the initial fix, we started seeing an error in another test. Reproducer is the third commit.

The remaining commits are a combination of chore, refactor, and fix. The `chore` is where I was figuring out how the parts fit together, and documenting in code & abstractions. The `refactor` is a tweak to the fix for the first bug. Then there is a new `fix` for the second bug (which was introduced in the TreeNode refactor).

## What changes are included in this PR?

1. Fix the bug
2. New regression tests

## Are these changes tested?

Yes. Both fixes are covered by new tests.

## Are there any user-facing changes?

No API changes.

### CODE REVIEW

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 1]
```diff
@@ -719,23 +741,10 @@ impl TreeNodeRewriter for CommonSubexprRewriter<'_> {
...
                     }
 
-                    let (series_number, id) = &self.id_array[self.curr_index];
+                    // incr idx for id_array, when not jumping
                     self.curr_index += 1;
-                    // Skip sub-node of a replaced tree, or without identifier, or is not repeated expr.
-                    let expr_set_item = self.expr_set.get(id).ok_or_else(|| {
-                        internal_datafusion_err!("expr_set invalid state")
-                    })?;
-                    if *series_number < self.max_series_number
```
Comment (wiedld) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:728]: These checks are already done earlier. Remove.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 2]
```diff
@@ -719,23 +741,10 @@ impl TreeNodeRewriter for CommonSubexprRewriter<'_> {
                         ));
                     }
 
-                    let (series_number, id) = &self.id_array[self.curr_index];
```
Comment (wiedld) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:722]: This was one of the bugs. It uses an already incremented `self.curr_index`. Instead, we grab all of the values once (see new line 713), before all the `self.curr_index` shenanigans.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 3]
```diff
@@ -571,66 +580,73 @@ enum VisitRecord {
...
+
         Ok(TreeNodeRecursion::Continue)
     }
 
     fn f_up(&mut self, expr: &Expr) -> Result<TreeNodeRecursion> {
         self.series_number += 1;
 
-        let Some((idx, sub_expr_desc)) = self.pop_enter_mark() else {
-            return Ok(TreeNodeRecursion::Continue);
-        };
```
Comment (wiedld) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:624]: This was one of the bugs. The behavior was changes with the TreeNode visitor. Previously, it was always returning a `sub_expr_desc` => then executing the remaining function code.

The changes I made here was to (1) bring it back closer to the original code, while (2) halting the new Jump contract from the consolidated visitor.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 4]
```diff
@@ -571,66 +580,73 @@ enum VisitRecord {
...
                 }
-                VisitRecord::ExprItem(s) => {
-                    desc.push_str(&s);
+                VisitRecord::ExprItem(id) => {
+                    desc.push_str(&id);
                 }
             }
         }
-        None
+        unreachable!("Enter mark should paired with node number");
```
Comment (wiedld) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:609]: Bring back the pop_enter_mark() contract to the original, while also adding in a new JumpMark.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 5]
```diff
@@ -42,6 +41,15 @@ use datafusion_expr::{col, Expr, ExprSchemable};
...
 type ExprSet = HashMap<Identifier, (Expr, usize, DataType)>;
 
+/// An ordered map of Identifiers encountered during visitation.
+///
+/// Is created in the ExprIdentifierVisitor, which identifies the common expressions.
+/// Is consumed in the CommonSubexprRewriter, which performs mutations.
+///
+/// - series_number. increased in fn_up, start from 1.
+/// - Identifier. is empty ("") if expr should not be considered for common elimation.
+type IdArray = Vec<(usize, Identifier)>;
```
Comment (wiedld) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:51]: This abstraction really helps to understand how the 2 visitors work together. 

The first visitor sets the vector idx used on f_down, whereas the series_number is set on f_up. An empty string for the expr_id means that this expression is not considered for rewrite (is skipped) in the second visitor.
e.g. `[(3, expr_id),(2, expr_id),(1, expr_id)]`

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 6]
```diff
@@ -571,66 +580,73 @@ enum VisitRecord {
...
     EnterMark(usize),
+    /// the node's children were skipped => jump to f_up on same node
+    JumpMark(usize),
     /// Accumulated identifier of sub expression.
     ExprItem(Identifier),
 }
 
 impl ExprIdentifierVisitor<'_> {
-    fn desc_expr(expr: &Expr) -> String {
+    fn node_identifier(expr: &Expr) -> String {
```
Comment (wiedld) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:590]: I renamed this, to make it more explicit that this is the identifier used in the `IdArray` and `ExprSet`.

File: datafusion/sqllogictest/test_files/common_subexpr_eliminate.slt [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+# KIND, either express or implied.  See the License for the
+# specific language governing permissions and limitations
+# under the License.
+
+#############
+## Common Subexpr Eliminate Tests
+#############
+
+statement ok
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/common_subexpr_eliminate.slt:22]: I recommend we move this test out of its own .slt file and into https://github.com/apache/arrow-datafusion/blob/main/datafusion/sqllogictest/test_files/expr.slt so it is eaiser to find

File: datafusion/sqllogictest/test_files/common_subexpr_eliminate.slt [hunk 8]
```diff
@@ -0,0 +1,106 @@
...
+10.1 0.09900990099 1.471623942989
+
+# common subexpr with case (short-circuited)
+query RRR rowsort
+select f64, case when f64 > 0 then 1.0 / f64 else null end, acos(case when f64 > 0 then 1.0 / f64 else null end) from doubles;
+----
+10.1 0.09900990099 1.471623942989
+
+
+statement ok
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/common_subexpr_eliminate.slt:54]: I believe this test is a duplicate of something elsewhere. While it was valuable for debugging I think we should remove the duplication to make the code easier to maintain over the long run

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 9]
```diff
@@ -532,18 +545,18 @@ impl ExprMask {
 /// Go through an expression tree and generate identifier.
 ///
 /// An identifier contains information of the expression itself and its sub-expression.
-/// This visitor implementation use a stack `visit_stack` to track traversal, which
+/// This visitor implementation use a stack `f_down()` to track traversal, which
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:548]: I think the original was correct (the stack was called `visit_stack`) -- it seems like the stack itself is created on `f_down`

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 10]
```diff
@@ -571,66 +584,73 @@ enum VisitRecord {
     /// `usize` is the monotone increasing series number assigned in pre_visit().
     /// Starts from 0. Is used to index the identifier array `id_array` in post_visit().
     EnterMark(usize),
+    /// the node's children were skipped => jump to f_up on same node
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:587]: This is the key fix, as I understand it -- the TreeNodeVisitor rewrite removed the notion of skipping sibling nodes during recursion, so this notion must be explicitly encoded in the subexpression rewrite pass.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 5 above)
Comment (alamb) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:55]: THank you -- I agree introducing a new typedef helps to make the code eaiser to understand

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 11]
```diff
@@ -693,20 +713,26 @@ impl TreeNodeRewriter for CommonSubexprRewriter<'_> {
         if expr.short_circuits() || is_volatile_expression(&expr)? {
             return Ok(Transformed::new(expr, false, TreeNodeRecursion::Jump));
         }
+
+        let (series_number, curr_id) = &self.id_array[self.curr_index];
```
Comment (alamb) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:717]: ❤️

**Review by alamb — APPROVED** [review]
Thank you @wiedld  -- I went through this PR carefully and I think it looks really nice. I really liked how you both fixed the bug, but also left the code better than when you found it (better comments, typedef, etc) 🏆 

 I had some minor comment / style suggestions, but we could do them as a follow on PRs.

Here is a PR that targets your branch with some suggested comment refinements: https://github.com/wiedld/arrow-datafusion/pull/2


cc @waynexia  (CommonSubExpr expert), @peter-toth (TreeNodeRefactor), and @crepererum  who has also worked on this code in the past

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 9 above)
Comment (wiedld) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:563]: nice catch.

File: datafusion/sqllogictest/test_files/common_subexpr_eliminate.slt (hunk 7 above)
Comment (wiedld) [reply datafusion/sqllogictest/test_files/common_subexpr_eliminate.slt]: done.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs (hunk 10 above)
Comment (wiedld) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:602]: For my understanding (please correct here 🙏🏼 ), prior to refactoring the 2 different visitors (`TreeNodeVisitor` and `TreeNodeRewriter`) had different transversal rules, and the semantics of skip vs stop mapped in weird ways (as [nicely described here](https://github.com/apache/arrow-datafusion/pull/8891#issue-2085713028) in the TreeNode refactor's "Rationale for Change").

Prior to the refactor, during the first tree walk (which builds the `visited_stack`) the short-circuited nodes:
1. were [skipped](https://github.com/apache/arrow-datafusion/blob/684b4fab75841672aabc4f3c2475e8c232acea20/datafusion/common/src/tree_node.rs#L242-L243), without adding to the stack
1. the old semantics meant [skipping the post-visit (up) call](https://github.com/apache/arrow-datafusion/blob/684b4fab75841672aabc4f3c2475e8c232acea20/datafusion/common/src/tree_node.rs#L26-L27)
1. it never looked in the stack (since no post-visit on the old semantics)

Whereas with the new TreeNode refactor the jump became a skip-children-but-call-f_up, which meant:
1. prior to the fix in this PR, it was using the old control flow. So it still didn't add to visited_stack.
1. refactor means that it now does perform the f_up on jump
1. f_up checks the stack (in `self.pop_enter_mark()`) and would not find it
1. the original refactor got around this by removing the panic and adding an option

For the changes done in the `TreeNodeVisitor` for the short-circuited nodes, I basically made it work with a jump that does the post-visit f_up by:
* add a placeholder to the id_array so that it exists on f_up
* push into the stack so it exists on the f_up
* make a `VisitRecord::JumpMark` to be used in the stack

Comment (peter-toth) [reply datafusion/optimizer/src/common_subexpr_eliminate.rs:602]: Yes, that's how the API worked before and after https://github.com/apache/arrow-datafusion/pull/8891. I think the issue came in with this https://github.com/peter-toth/arrow-datafusion/pull/1 adjustment.
Thanks @wiedld for fixing it!

**Comment by alamb** [comment]
I plan to merge this later today unless someone else would like more time to review

**Comment by alamb** [comment]
I merged up to main and pushed a commit to this branch

> I plan to give it a review later tomorrow. We can merge this first as there is one approval if the release progress is blocked.

Given I would like to unblock the release I do plan to merge it in later today. We'll plan to address any comments as follow on PRs. 

Thank you very much @waynexia
