### PR TITLE
Fix `DataFrame::cache` errors with `Plan("Mismatch between schema and batches")`

### LINKED ISSUE #8476: DataFrame::cache errors with `Plan("Mismatch between schema and batches")` but query works when not cached
### Describe the bug

`Dataframe::cache` gives an error where an execution that doesn't first cache results succeeds.

I would have expected caching to have no effect on success/failure.

### To Reproduce

```rust
use datafusion::prelude::SessionContext;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let sql = "SELECT CASE WHEN true THEN NULL ELSE 1 END;";
    let ctx = SessionContext::new();
    let plan = ctx.state().create_logical_plan(sql).await?;
    let df = ctx.execute_logical_plan(plan).await?;
    // Comment out the next line to make the error go away.
    let df = df.cache().await?;
    let batches = df.collect().await?;
    let display = datafusion::arrow::util::pretty::pretty_format_batches(&batches).unwrap();
    println!("{}", display);
    Ok(())
}
```

### Expected behavior

Behavior with and without `let df = df.cache().await?` to be functionally same, only changing performance and memory use.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Asura7969**
## Which issue does this PR close?

Closes #8476.

## Rationale for this change

https://github.com/apache/arrow-datafusion/issues/8476#issue-2033547105

## Are these changes tested?

`test_cache_mismatch`

### CODE REVIEW

File: datafusion/core/src/dataframe/mod.rs [hunk 1]
```diff
@@ -1271,8 +1273,13 @@ impl DataFrame {
     /// ```
     pub async fn cache(self) -> Result<DataFrame> {
         let context = SessionContext::new_with_state(self.session_state.clone());
+        // type cast
```
Comment (alamb) [inline datafusion/core/src/dataframe/mod.rs:1276]: Rather than explcilty running (only) coercion (which is also run as part of execution) I suggest you use the schema that comes directly from the output stream

Something like (copied from `Self::collect`): https://docs.rs/datafusion/latest/src/datafusion/dataframe/mod.rs.html#756-760
```
        let task_ctx = Arc::new(self.task_ctx());
        let plan = self.create_physical_plan().await?;
        let schema = plan.schema();
        collect(plan, task_ctx).await
```

**Review by alamb — COMMENTED** [review]
Thank you for this contribution @Asura7969  -- I think we can do this slightly more efficiently / consistenly, but the overall idea is 👍

File: datafusion/core/src/dataframe/mod.rs (hunk 1 above)
Comment (Asura7969) [reply datafusion/core/src/dataframe/mod.rs]: Thanks for your advice

File: datafusion/core/src/dataframe/mod.rs [hunk 2]
```diff
@@ -1271,10 +1271,10 @@ impl DataFrame {
...
     pub async fn cache(self) -> Result<DataFrame> {
         let context = SessionContext::new_with_state(self.session_state.clone());
-        let mem_table = MemTable::try_new(
-            SchemaRef::from(self.schema().clone()),
-            self.collect_partitioned().await?,
-        )?;
+        // The schema is consistent with the output
+        let physical_plan = self.clone().create_physical_plan().await?;
+        let mem_table =
+            MemTable::try_new(physical_plan.schema(), self.collect_partitioned().await?)?;
```
Comment (alamb) [inline datafusion/core/src/dataframe/mod.rs:1277]: FWIW this now runs the planner twice -- we could make it more efficient by calling [`collect_partitioned()`](https://docs.rs/datafusion/latest/datafusion/physical_plan/fn.collect_partitioned.html) directly on the physical plan rather than `Self::collect_partitioned` that will replan (and recollect)

**Review by alamb — APPROVED** [review]
Thanks a lot @Asura7969 !

**Review by alamb — APPROVED** [review]
Thank you @Asura7969
