### PR TITLE
MINOR: fix concat_ws corner bug

### LINKED ISSUE #2100: function 'concat_ws' should ignore NULL in last argument
**Describe the bug**
Function *concat_ws* is not ignoring NULL in last argument and seperator text is added at the end of the result.

**To Reproduce**
```sql
SELECT concat_ws('|', 'a', NULL);
-- Result: a|
```

Tested on master (refs 73ea6e1)

**Expected behavior**
```sql
SELECT concat_ws('|', 'a', NULL);
-- Result: a
```
There should not be spectator added as the end of result.

**Additional context**
There is test case for ignoring NULLs in arguments but only in the middle: https://github.com/apache/arrow-datafusion/blob/master/datafusion/tests/sql/expr.rs#L553=

Function description says NULLs should be ignored: https://github.com/apache/arrow-datafusion/blob/master/datafusion-physical-expr/src/string_expressions.rs#L326=

### PR DESCRIPTION
**Pull request by WinkerDu**
# Which issue does this PR close?

Closes #2100.

 # Rationale for this change

Function concat_ws is not ignoring NULL in last argument and seperator text is added at the end of the result.
To Reproduce
```
SELECT concat_ws('|', 'a', NULL);
-- Result: a|
```
Expected behavior
```
SELECT concat_ws('|', 'a', NULL);
-- Result: a
```

# What changes are included in this PR?

skip adding separator when NULL in last argument.

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by mateuszkj** [comment]
Now it's failing with two NULLs at last arguments.

To Reproduce
```sql
SELECT concat_ws('|','a',NULL, NULL);
-- Result: a|
```
Expected behavior
```sql
SELECT concat_ws('|','a',NULL, NULL);
-- Result: a
```

**Comment by doki23** [comment]
How about
```
  let mut owned_string = Vec::with_capacity(args.len());
  for arg_index in 1..args.len() {
      let arg = &args[arg_index];
      if !arg.is_null(index) {
          owned_string.push(arg.value(index));
      }
  }
  owned_string.join(sep)
```

**Comment by Dandandan** [comment]
> How about
> ```rust
>   let mut owned_string = Vec::with_capacity(args.len()-1);
>   for arg_index in 1..args.len() {
>       let arg = &args[arg_index];
>       if !arg.is_null(index) {
>           owned_string.push(arg.value(index));
>       }
>   }
>   owned_string.join(sep)
> ```

Could also use an iterator + `flat_map` + `collect` (into `Vec<String>`) for a rusty version.

**Comment by WinkerDu** [comment]
@doki23 @Dandandan thanks for the advice, I'd try it

**Comment by WinkerDu** [comment]
@mateuszkj @doki23 @Dandandan PTAL, thanks

File: datafusion/physical-expr/src/string_expressions.rs [hunk 1]
```diff
@@ -343,18 +343,17 @@ pub fn concat_ws(args: &[ArrayRef]) -> Result<ArrayRef> {
...
-                        // if not last push separator
-                        if arg_index != args.len() - 1 {
-                            owned_string.push_str(sep);
+                let string_vec = args[1..]
+                    .iter()
+                    .flat_map(|arg| {
+                        if !arg.is_null(index) {
+                            vec![arg.value(index)]
+                        } else {
+                            vec![]
```
Comment (Dandandan) [inline datafusion/physical-expr/src/string_expressions.rs:352]:
```suggestion
                        if !arg.is_null(index) {
                            Some(arg.value(index))
                        } else {
                            None
                        }
```

**Comment by WinkerDu** [comment]
@Dandandan  @houqp @alamb PTAL

**Review by Dandandan — APPROVED** [review]

**Review by doki23 — APPROVED** [review]
LGTM, thanks @WinkerDu

**Review by yjshen — APPROVED** [review]
