### PR TITLE
fix: account for memory in `RepartitionExec`

### LINKED ISSUE #4816: Unlimited memory consumption in `RepartitionExec`
**Describe the bug**
See https://github.com/apache/arrow-datafusion/blob/5b70e3543f5c10832e43ed25e7d4166cf0c1df78/datafusion/core/src/physical_plan/repartition.rs#L333-L340

**To Reproduce**
\-

**Expected behavior**
The data kept in these channels should be registered with the `MemoryManager`.

**Additional context**
\-

### PR DESCRIPTION
**Pull request by crepererum**
# Which issue does this PR close?
Closes #4816.

# Rationale for this change
Unbounded channels in `RepartitionExec` may easily lead to OOMs, even when the user has a memory manager limit configured.

# What changes are included in this PR?
Memory accounting. Some drive-by clean-ups.

# Are these changes tested?
New test called `oom`.

# Are there any user-facing changes?
Better memory accounting.

### CODE REVIEW

File: datafusion/core/src/physical_plan/aggregates/mod.rs [hunk 1]
```diff
@@ -1210,18 +1210,11 @@ mod tests {
             let err = common::collect(stream).await.unwrap_err();
 
             // error root cause traversal is a bit complicated, see #4172.
-            if let DataFusionError::ArrowError(ArrowError::ExternalError(err)) = err {
```
Comment (crepererum) [inline datafusion/core/src/physical_plan/aggregates/mod.rs:1213]: drive-by clean-up

File: datafusion/core/src/physical_plan/repartition.rs [hunk 2]
```diff
@@ -555,20 +584,35 @@ impl Stream for RepartitionStream {
         mut self: Pin<&mut Self>,
         cx: &mut Context<'_>,
     ) -> Poll<Option<Self::Item>> {
-        match self.input.poll_next_unpin(cx) {
```
Comment (crepererum) [inline datafusion/core/src/physical_plan/repartition.rs:558]: the change here isn't as large as it seems. I've just converted the implicit loop via (tail) recursion into a proper one since I'm kinda afraid that this may explode under certain circumstances. See one of the early commits in this PR. The actual accounting change is in a separate commit.

**Comment by crepererum** [comment]
There is a test bug, I'm working on that (happens when tests use 1000 things at once).

File: datafusion/core/src/physical_plan/repartition.rs [hunk 3]
```diff
@@ -467,11 +488,16 @@ impl RepartitionExec {
             };
 
             partitioner.partition(batch, |partition, partitioned| {
+                let size = partitioned.get_array_memory_size();
```
Comment (alamb) [inline datafusion/core/src/physical_plan/repartition.rs:491]: This doesn't account for sliced data (so if a batch of 1M gets cut up into 1000 pieces, each of the 1000 pieces will be charged the entire underlying size). that being said it is a conservative estimate so that is good 👍

**Review by alamb — APPROVED** [review]
Thank you @crepererum 

In general seeing the unbounded receiver streams here is somewhat terrifying as it will buffer a potentially infinite amount.

Maybe it is worth reviewing this code and ensuring it only buffers inputs when one of the outputs is empty and was polled. 🤔 

At least after this PR we will have more visibility into if/when this is happening 👍

**Comment by crepererum** [comment]
> Maybe it is worth reviewing this code and ensuring it only buffers inputs when one of the outputs is empty and was polled. 🤔

I can try that in a follow up. In general unbounded buffering cannot be avoided though since the output may poll partition 1 while the input only produced data for partition 2 til the very end. We can make buffering less likely though (hence let's try this in a follow up).

**Comment by alamb** [comment]
I plan to merge this later today unless there are any additional comments
