### PR TITLE
Fix homebrew publish script

### LINKED ISSUE #5043: Homebrew release script has the amount of arguments being incorrect
**Describe the bug**
The correct amount of arguments is 4
**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by iajoiner**
# Which issue does this PR close?

Closes #5043.

# Rationale for this change
Fix the homebrew publish script:
1. Change the script so that git parallel fetch works on both Linux and macOS and doesn't error out if the OS is neither.
2. Fix a typo.
3. Add documentation so that everyone can run the script.

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by iajoiner** [comment]
@andygrove

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @iajoiner

**Comment by alamb** [comment]
FYI any "no space left on device" CI errors should be fixed by merging up from master to get https://github.com/apache/arrow-datafusion/pull/5047

File: dev/release/publish_homebrew.sh [hunk 1]
```diff
@@ -41,7 +50,7 @@ if ! git remote | grep -q --fixed-strings ${github_user}; then
 fi
 
 echo "Updating working copy"
-git fetch --all --prune --tags --force -j$(nproc)
+git fetch --all --prune --tags --force -j$(num_processing_units)
```
Comment (andygrove) [inline dev/release/publish_homebrew.sh:53]: For Mac, I had to remove the parentheses here, otherwise I got the error:

```
line 55: num_processing_units: command not found
error: switch `j' requires a value
```

```suggestion
git fetch --all --prune --tags --force -j$num_processing_units
```
