### PR TITLE
Use checked division kernel

### LINKED ISSUE #6791: Inconsistent Divide By Zero Behaviour
### Describe the bug

The behaviour when dividing by zero varies based on if the scalar or non-scalar version of the kernel is used

### To Reproduce

Division by a zero scalar results in an error

```
❯ create table foo as select 5 as v;
❯ select v / 0 from foo;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Divide by zero error
```

Division by a zero array with a nullable column results in a null

```
❯ CREATE TABLE bar(a int, b int) AS VALUES(5, 0),(NULL, NULL);
❯ select a / b from bar;
+---------------+
| bar.a / bar.b |
+---------------+
|               |
|               |
+---------------+
2 rows in set. Query took 0.005 seconds.
```

And if the column is not nullable it results in a very peculiar error

```
❯ create table bar as (select 5 as a, 0 as b);
0 rows in set. Query took 0.003 seconds.
❯ select a / b from bar;
Arrow error: Invalid argument error: Column 'bar.a / bar.b' is declared as non-nullable but contains null values
```

### Expected behavior

We should consistently return a `DivideByZero` error on division by zero

### Additional context

There is upstream work ongoing to improve arithmetic logic:
- https://github.com/apache/arrow-rs/issues/2647
- https://github.com/apache/arrow-rs/issues/3999

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #6791

# Rationale for this change

The current behaviour is inconsistent, can lead to nulls in non-nullable columns, and is pretty surprising.

A future iteration of the upstream arithmetic kernels is also likely to make this the only option - https://github.com/apache/arrow-rs/issues/2647#issuecomment-1612146560

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 1]
```diff
@@ -1670,9 +1670,12 @@ mod tests {
     fn test_simplify_divide_zero_by_zero() {
         // 0 / 0 -> null
         let expr = lit(0) / lit(0);
-        let expected = lit(ScalarValue::Int32(None));
+        let err = try_simplify(expr).unwrap_err();
 
-        assert_eq!(simplify(expr), expected);
+        assert!(
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1675]: This is consistent with postgres 👍 

```sql
postgres=# select 0 / 0;
ERROR:  division by zero
```

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
cc @viirya

**Comment by viirya** [comment]
Hmm, it is inconsistent. We should fix it. But we will prefer default behavior is to get null instead of query error. That is story of Spark but I agree DataFusion doesn't necessarily to follow it at all.

> ... nulls in non-nullable columns, and is pretty surprising.

Is it an issue? In Spark, Divide expression output is nullable always. I think producing null from non-nullable input columns is totally fine if it follows the expression's output type definition.

So the issue is more about inconsistency.

Looks okay to me.
