### PR TITLE
refine: `substr` error

### LINKED ISSUE #7326: Wrong error for `substr` function
### Describe the bug

Passing wrong type into `substr` function causes the `DataFusionError::InternalError`

```
Internal error: The "substr" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### To Reproduce

```sh
# with datafusion-cli
select substr(123, 1);
```

### Expected behavior

I'd expect the error kind to be `DataFusionError::Plan` probably, like these ones: https://github.com/apache/arrow-datafusion/blob/c50268670f8bee2022a9892a0c67073fc360352a/datafusion/expr/src/type_coercion/aggregates.rs#L147-L150

### Additional context

I guess the reason is here: https://github.com/apache/arrow-datafusion/blob/c50268670f8bee2022a9892a0c67073fc360352a/datafusion/expr/src/built_in_function.rs#L1404-L1417
There are several usages of  `InternalError` in the file.

_No response_

### PR DESCRIPTION
**Pull request by Weijun-H**
## Which issue does this PR close?

Closes #7326

### CODE REVIEW

**Review by jackwener — APPROVED** [review]

File: datafusion/expr/src/built_in_function.rs [hunk 1]
```diff
@@ -1395,25 +1395,25 @@ macro_rules! make_utf8_to_return_type {
...
+                            name,
+                            **value_type
+                        );
                     }
-                }
-                _ => {
+                },
+                data_type => {
                     // this error is internal as `data_types` should have captured this.
                     return internal_err!(
```
Comment (jackwener) [inline datafusion/expr/src/built_in_function.rs:1413]:
```suggestion
                    return plan_err!(
```

File: datafusion/expr/src/built_in_function.rs [hunk 2]
```diff
@@ -1395,25 +1395,25 @@ macro_rules! make_utf8_to_return_type {
...
-                                name
-                            );
-                        }
+                DataType::Dictionary(_, value_type) => match **value_type {
+                    DataType::LargeUtf8 => $largeUtf8Type,
+                    DataType::Utf8 => $utf8Type,
+                    DataType::Null => DataType::Null,
+                    _ => {
+                        // this error is internal as `data_types` should have captured this.
+                        return internal_err!(
```
Comment (jackwener) [inline datafusion/expr/src/built_in_function.rs:1404]:
```suggestion
                        return plan_err!(
```
