### PR TITLE
Stream CSV file during schema inference

### LINKED ISSUE #3658: CSV inference reads in the whole file to memory, regardless of row limit
**Describe the bug**
When inferring the schema, the complete CSV will be read into memory even if you leave it at the default 1000 rows to infer from.

**To Reproduce**

```rust
let df = ctx.read_csv("./test/", CsvReadOptions::new()).await?;
```

Happens here:
https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/datasource/file_format/csv.rs#L109

**Expected behavior**
It should read in only as much data as it needs for the given row count to infer data from.

**Additional context**

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #3658.

# Rationale for this change

# What changes are included in this PR?

During CSV schema inference, instead of reading entire object/file into memory before taking as many rows as configured to infer the schema, will instead stream in the CSV (using helper method from object_store) which feeds into newline_delimited_stream to produce the stream of CSV rows, which can be read as needed instead of needing entire file in memory.

Certain adjustments needed for this:

- Only read header for first chunk (if header present)
- As inferring chunks of the file separately, must merge the inferred datatypes of these chunks together akin to what `arrow::csv::reader::infer_reader_schema(...)` already does
- If has header row, and in first chunk only the header row was read (i.e. no data rows) then must ignore the datatype (as will default to Utf8 which can cause issues with merging the schemas of the chunks)

# Are these changes tested?

New test using mocked ObjectStore providing an infinite stream, used to prove inference doesn't depend on consuming entire stream first.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Jefffrey** [comment]
Bit of ugly duplication with code ripped from `arrow-rs` (mainly the `build_schema_helper(...)` method), so maybe could upstream some of this into `arrow-rs` instead?

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 1]
```diff
@@ -120,27 +123,92 @@ impl FileFormat for CsvFormat {
...
+                .await?
+                .into_stream()
+                .map_err(|e| DataFusionError::External(Box::new(e)));
+            let stream = newline_delimited_stream(stream);
+            pin_mut!(stream);
+
+            // first chunk may have header, initialize names & types vec
+            // as use header names, and types vec is used to record all inferred types across chunks
+            let (column_names, mut column_types): (Vec<_>, Vec<_>) =
+                if let Some(data) = stream.next().await.transpose()? {
```
Comment (metesynnada) [inline datafusion/core/src/datasource/file_format/csv.rs:139]: The first chunk does not need to be handled outside of the stream consumer below. I understand what is different from other chunks, but it can be handled with using a state. Merging could reduce the code change significantly.

**Review by metesynnada — COMMENTED** [review]
Thanks for the work. In general, the idea is quite cool and it removes a redundant whole file materialising.

 However, I think you should find a better way to deal with the first chunk of the byte stream. It seems that there is a code duplication that can be handled better.

File: datafusion/core/src/datasource/file_format/csv.rs (hunk 1 above)
Comment (Jefffrey) [reply datafusion/core/src/datasource/file_format/csv.rs:139]: Thanks for the feedback, I was initially back and forth on how to handle this special case. I'll give a shot at refactoring to reduce the duplication here

**Review by alamb — COMMENTED** [review]
Hi @Jefffrey  -- thank you for this contribution

Is there any way to test this code ? Perhaps with a mocked out object store and verify that only the first file is fetched?

Also, I can't help but wonder if we could implement the logic using future::Stream more efficiently , but I haven't studied the logic in detail to really know for sure

**Comment by Jefffrey** [comment]
> Hi @Jefffrey -- thank you for this contribution
> 
> Is there any way to test this code ? Perhaps with a mocked out object store and verify that only the first file is fetched?
> 
> Also, I can't help but wonder if we could implement the logic using future::Stream more efficiently , but I haven't studied the logic in detail to really know for sure

Hi @alamb, I've pushed a test which uses a mocked ObjectStore which returns an infinite stream of bytes, with the test proving that by finishing it won't try to consume the entire stream first before inferring (which was the previous behaviour)

Could you elaborate on the future::Stream part?

**Review by alamb — APPROVED** [review]
Thank you @Jefffrey  -- the test looks great

> Could you elaborate on the future::Stream part?

I guess I was thinking rather than using two nested loops and `break 'iterating  _objects` it would be possible to use future::Streams to do the iteration.

I tried a few ways and nothing really looked all that much better.

**Comment by alamb** [comment]
Here is a follow on PR to reduce the nesting: https://github.com/apache/arrow-datafusion/pull/4717
