### PR TITLE
Insert target columns empty fix

### LINKED ISSUE #5078: `INSERT` statements without target column list are not working
**Describe the bug**
Planning of `INSERT` statements does not allow for omitting target column list in the SQL statement.

**To Reproduce**
```sql
❯ create table test as values (1, 2);
0 rows in set. Query took 0.149 seconds.
❯ insert into test values (3, 4);
Plan("Column count doesn't match insert query!")
❯ insert into test(column1, column2) values (3, 4);
Internal("Unsupported logical plan: Dml")
```
The first error should be the same as the second, which comes from the stubbed out physical planning implementation.

**Expected behavior**
It is [generally accepted](https://www.postgresql.org/docs/current/sql-insert.html) that the target column list is optional, and if omitted the target is assumed to be all the columns in the schema.

**Additional context**
Related to the new `LogicalPlan::Dml` node for `WriteOp::Insert` (handled in `insert_to_plan`).

### PR DESCRIPTION
**Pull request by gruuya**
# Which issue does this PR close?

Closes #5078.

# Rationale for this change

Enable logical planning of `INSERT` statements without the optional target column list.

# What changes are included in this PR?

If there are no parsed target fields in the `INSERT` statement default to using all the fields from the table's schema.

# Are these changes tested?

Yes.

# Are there any user-facing changes?

Only to users that use Datafusion as a framework where write statements are supported.

### CODE REVIEW

File: datafusion/common/src/config.rs [hunk 1]
```diff
@@ -323,7 +323,7 @@ pub struct ConfigOptions {
     pub catalog: CatalogOptions,
     /// Execution options
     pub execution: ExecutionOptions,
-    /// Explain options
+    /// Optimizer options
```
Comment (alamb) [inline datafusion/common/src/config.rs:326]: ❤️ Nice drive by cleanup

File: datafusion/sql/tests/integration_test.rs [hunk 2]
```diff
@@ -165,13 +165,60 @@ fn plan_insert() {
         "insert into person (id, first_name, last_name) values (1, 'Alan', 'Turing')";
     let plan = r#"
 Dml: op=[Insert] table=[person]
-  Projection: CAST(column1 AS id AS UInt32), column2 AS first_name, column3 AS last_name
```
Comment (alamb) [inline datafusion/sql/tests/integration_test.rs:168]: 👍

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
This makes sense to me -- thank you @gruuya

**Review by avantgardnerio — APPROVED** [review]
:+1:
