### PR TITLE
Coerce Dictionary types for scalar functions

### LINKED ISSUE #10076: Coerce dictionary types for scalar functions
### Describe the bug

Found an issue on coercing dictionary types for scalar function at Comet: https://github.com/apache/arrow-datafusion-comet/issues/265

In short, if there are dictionary type and non-dictionary type inputs for scalar function, currently DataFusion cannot coerce the input types, but report an error like:

```
Error during planning: Coercion from [Dictionary(Int32, Utf8), Utf8] to the signature VariadicEqual failed
```

### To Reproduce

_No response_

### Expected behavior

Dictionary types should be coerced for scalar function.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #10076.

### CODE REVIEW

File: datafusion/expr/src/type_coercion/functions.rs [hunk 1]
```diff
@@ -435,15 +437,15 @@ fn coerced_from<'a>(
         // Note that not all rules in `comparison_coercion` can be reused here.
         // For example, all numeric types can be coerced into Utf8 for comparison,
         // but not for function arguments.
-        _ => comparison_binary_numeric_coercion(type_into, type_from).and_then(
-            |coerced_type| {
+        _ => comparison_binary_numeric_coercion(type_into, type_from)
+            .or_else(|| dictionary_coercion(type_into, type_from, true))
```
Comment (jayzhan211) [inline datafusion/expr/src/type_coercion/functions.rs:441]: Should we check the inner data type with `coerced_from` instead of `comparison_coercion` 🤔 ?

Comment (alamb) [reply datafusion/expr/src/type_coercion/functions.rs:441]: I couldn't quite tell the difference. What would be the benefit? 

I always get a little confused with the type coercion logic -- that there are different rules for certain operations I think.

**Review by alamb — APPROVED** [review]
Thanks @viirya  and @jayzhan211  -- this looks like an improvement to me. 

I don't fully understand the comment https://github.com/apache/arrow-datafusion/pull/10077/files#r1564548305 but it seems like something we could refine in a follow on PR as well

File: datafusion/expr/src/type_coercion/functions.rs (hunk 1 above)
Comment (viirya) [reply datafusion/expr/src/type_coercion/functions.rs:441]: Hmm, not sure I understand the comment. What you mean "check inner data type with `coerced_from`"?

Comment (jayzhan211) [reply datafusion/expr/src/type_coercion/functions.rs:441]: > "check inner data type with coerced_from"

Similar to the current implementation of Dict 
```rust
        // coerced dictionary first
        (cur_type, Dictionary(_, value_type)) | (Dictionary(_, value_type), cur_type)
            if coerced_from(cur_type, value_type).is_some() =>
        {
            Some(type_into.clone())
        }
```
The above once checks if the inner type in Dict is coercible by the `coerced_from` function. 
But `dictionary_coercion` checks the inner type of Dict with `comparison_coercion`.

The `coerced_from` and `comparison_coercion` are slightly different. 
`comparison_coercion` cares about the scenario in comparison, so **loss is allowed**. For example, i64 and u64, we return i64, while we get None in `coerced_from` for casting u64 to i64.

I tried to have one coercion for all but ended up not finding a way to cover all the cases in https://github.com/apache/arrow-datafusion/issues/8302.

I suggest we don't mix the logic for `coerce_from` and `comparison_coercion`. It would be nice to avoid `comparison_binary_numeric_coercion ` too.

Comment (viirya) [reply datafusion/expr/src/type_coercion/functions.rs:441]: Ah, I don't notice `coerced_from` is updated to coerce dictionary type. I was working on a branch without update yet. The current update with dictionary coercion looks good now to fix the issue I encountered.

Comment (viirya) [reply datafusion/expr/src/type_coercion/functions.rs]: But I notice that the current implementation has a small issue.

File: datafusion/expr/src/type_coercion/functions.rs [hunk 2]
```diff
@@ -314,8 +314,13 @@ fn coerced_from<'a>(
     // match Dictionary first
     match (type_into, type_from) {
         // coerced dictionary first
-        (cur_type, Dictionary(_, value_type)) | (Dictionary(_, value_type), cur_type)
-            if coerced_from(cur_type, value_type).is_some() =>
```
Comment (viirya) [inline datafusion/expr/src/type_coercion/functions.rs:318]: When coercing into dictionary type, the `type_into` and `type_from` parameters are in incorrect order.

**Review by jayzhan211 — APPROVED** [review]
👍

**Comment by viirya** [comment]
Thank you @alamb @jayzhan211

**Comment by viirya** [comment]
Thank you @andygrove
