### PR TITLE
Preserve casts in rewrite_sort_cols_by_aggs

### LINKED ISSUE #5610: Sort on cast expression removes cast
**Describe the bug**
I have found that under certain conditions casts are lost when there is a sort on expression with cast, and that could result in incorrect query results (for example if cast would be from string to integer).

**To Reproduce**
We hit this when building plan with `LogicalPlanBuilder` directly, but following sql will trigger this as well.

Query `SELECT first_name AS first_name FROM (SELECT first_name AS first_name FROM person) ORDER BY CAST(first_name as INT)` gives us 
```
Sort: first_name AS first_name ASC NULLS LAST
  Projection: first_name AS first_name
      Projection: person.first_name AS first_name
            TableScan: person
```

**Expected behavior**
Query above should give us something like 
```
Sort: CAST(first_name AS Int32) ASC NULLS LAST
  Projection: first_name AS first_name
      Projection: person.first_name AS first_name
            TableScan: person
```

**Additional context**

### PR DESCRIPTION
**Pull request by mpurins-coralogix**
# Which issue does this PR close?

Closes #5610.

# Rationale for this change

I changed `rewrite_in_terms_of_projection` to add casts back, but I honestly have no idea if this is proper way to fix this but it does the trick and would appreciate some direction.

# What changes are included in this PR?

# Are these changes tested?

Added two new tests.

# Are there any user-facing changes?

Bugfix.

### CODE REVIEW

File: datafusion/expr/src/expr_rewriter/order_by.rs [hunk 1]
```diff
@@ -116,7 +116,19 @@ fn rewrite_in_terms_of_projection(
 
         // look for the column named the same as this expr
         if let Some(found) = proj_exprs.iter().find(|a| expr_match(&search_col, a)) {
```
Comment (Dandandan) [inline datafusion/expr/src/expr_rewriter/order_by.rs:118]: `into_iter` might prevent the clone later on?

Comment (mpurins-coralogix) [reply datafusion/expr/src/expr_rewriter/order_by.rs:118]: `into_iter` would consume `proj_exprs` which can not be done here because it is captured in closure which is passed to `rewrite_expr`

Comment (Dandandan) [reply datafusion/expr/src/expr_rewriter/order_by.rs:118]: ok : 👌

**Review by Dandandan — APPROVED** [review]

File: datafusion/expr/src/expr_rewriter/order_by.rs [hunk 2]
```diff
@@ -116,7 +116,19 @@ fn rewrite_in_terms_of_projection(
...
-            return Ok((*found).clone());
+            let found = found.clone();
```
Comment (Dandandan) [inline datafusion/expr/src/expr_rewriter/order_by.rs:119]: The fragile here to me seems to be that the code assumes some naming, and with casting it removes the cast expression. Ideally we wouldn't depend on the naming in the code but on the expressions themselves.

File: datafusion/sql/tests/integration_test.rs [hunk 3]
```diff
@@ -3252,6 +3252,17 @@ fn test_select_distinct_order_by() {
     assert_eq!(err.to_string(), expected);
 }
 
+#[test]
+fn select_order_by_with_cast() {
```
Comment (alamb) [inline datafusion/sql/tests/integration_test.rs:3256]: I verified this test fails without the change in this PR 👍 

---- select_order_by_with_cast stdout ----
thread 'select_order_by_with_cast' panicked at 'assertion failed: `(left == right)`
  left: `"Sort: first_name AS first_name ASC NULLS LAST\n  Projection: first_name AS first_name\n    Projection: person.first_name AS first_name\n      TableScan: person"`,
 right: `"Sort: CAST(first_name AS first_name AS Int32) ASC NULLS LAST\n  Projection: first_name AS first_name\n    Projection: person.first_name AS first_name\n      TableScan: person"`', datafusion/sql/tests/integration_test.rs:2433:5

File: datafusion/expr/src/expr_rewriter/order_by.rs (hunk 2 above)
Comment (alamb) [reply datafusion/expr/src/expr_rewriter/order_by.rs:119]: Yes I agree this is non ideal -- however I can't think of anything better

**Review by alamb — APPROVED** [review]
Thank you @mpurins-coralogix  and @Dandandan  -- I think this PR improves the situation and adds good test coverage. 

I think we can improve the code later over time as well.
