### PR TITLE
Bug fix on DFField to Field conversion: preserve metadata

### LINKED ISSUE #3964: Bug on propagating arrow field metadata
**Describe the bug**
While converting DFSchema to Schema, field metadata is not preserved. It may cause future bugs on methods like `alias`.

**To Reproduce**
Create a `DFSchema` that has fields with metadata. 

```rust
let mut a: DFField = DFField::new(Some("table1"), "a", DataType::Int64, false);
let mut b: DFField = DFField::new(Some("table1"), "b", DataType::Int64, false);
let mut a_metadata = BTreeMap::new();
a_metadata.insert("key".to_string(), "value".to_string());
a.field.set_metadata(Some(a_metadata));
let mut b_metadata = BTreeMap::new();
b_metadata.insert("key".to_string(), "value".to_string());
b.field.set_metadata(Some(b_metadata));
let df_schema = Arc::new(
    DFSchema::new_with_metadata(
        [a, b].to_vec(),
        HashMap::new(),
    )
        .unwrap(),
);
let schema: Schema = df_schema.as_ref().clone().into();
let a_df = df_schema.fields.get(0).unwrap().field();
let a_arrow = schema.fields.get(0).unwrap();
assert_eq!(a_df.metadata(), a_arrow.metadata())
```

**Expected behavior**
Fields preserve the metadata.

**Additional context**
It will be solved by changing `From<DFSchema> for Schema` method.

### PR DESCRIPTION
**Pull request by metesynnada**
# Which issue does this PR close?
Closes #3964.

 # Rationale for this change
While converting `DFSchema` to `Schema`, field metadata is not preserved. It may cause future bugs on methods like `alias`.
# What changes are included in this PR?
Changing `From<DFSchema> for Schema` method.

# Are there any user-facing changes?
NA

### CODE REVIEW

File: datafusion/common/src/dfschema.rs [hunk 1]
```diff
@@ -367,21 +367,7 @@ impl From<DFSchema> for Schema {
...
-                            f.name().as_str(),
-                            f.data_type().to_owned(),
-                            f.is_nullable(),
-                        )
-                    } else {
-                        f.field
-                    }
-                })
-                .collect(),
+            df_schema.fields.into_iter().map(|f| f.field).collect(),
```
Comment (alamb) [inline datafusion/common/src/dfschema.rs:370]: 💯  for fixing a bug by deleting code

**Review by alamb — APPROVED** [review]
Thanks @metesynnada -- this looks great

**Review by andygrove — APPROVED** [review]
