### PR TITLE
[DataFusion] Optimize hash join inner workings, null handling fix

### LINKED ISSUE #44: Optimize hash join inner workings
The hash join algorithm is core

Optimize some hot functions in the hash join algorithm.

* Don't store hashes in hashtable
* Do some more optimization for hashing primitives

### LINKED ISSUE #195: Fix null handling hash join
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-12266

Improve null handling of 

SELECT id1, id2 FROM (SELECT null AS id1) t1
 INNER JOIN (SELECT 0 AS id2) t2 ON id1 = id2

> NULL, NULL

(should be empty result set)

We should filter beforehand to make this result correct. Also this can make things more efficient as the non-null filter can be pushed down which can lead to efficiency gains (making data-set smaller, not having to deal with nullable data, or even entire files could be skipped when they only contain nulls).

### PR DESCRIPTION
**Pull request by Dandandan**
\> 5% speed up for query 5 by speeding up some hot functions

* Don't store hashes in hashtable and allocate capacity upfront (adding some memory usage for non-high cardinality inputs, but this grows at the same rate as the left side input). This avoids re-hashing (copying + calling hash functions) when resizing the hash table
* Do some more optimization for hashing primitives and avoid `.value(i)` which does a bound check.
* Don't call hash_combine on joins with one column
* Fix null equality / enable test

Closes #44 
Fixes #195

PR
```
Query 5 avg time: 88.59 ms
```

Master

```
Query 5 avg time: 95.91 ms
```

### CODE REVIEW

**Comment by Dandandan** [comment]
@alamb @jorgecarleitao FYI if you have time, I am not planning any changes to this PR for now.

I think the more important part of the PR is the fix wrt null handling which turned out to be a one line change.

The other part is some small performance tweaks and prepares it a bit for further improvements down the road.

File: datafusion/src/physical_plan/hash_join.rs [hunk 1]
```diff
@@ -781,58 +846,140 @@ pub fn create_hashes<'a>(
...
                     i64,
                     hashes_buffer,
-                    random_state
+                    random_state,
+                    multi_col
                 );
             }
             DataType::Boolean => {
-                hash_array!(BooleanArray, col, u8, hashes_buffer, random_state);
+                hash_array_primitive!(
```
Comment (jorgecarleitao) [inline datafusion/src/physical_plan/hash_join.rs:955]:
```suggestion
                hash_array!(
```

otherwise this will be an iterator over the bytes of the bitmap, not over the individual bits.

In general, I recommend using generics, as they make it more difficult for these to happen, but I agree that the API is a bit funny on the arrow side. ^_^

File: datafusion/src/physical_plan/hash_join.rs [hunk 2]
```diff
@@ -708,7 +720,6 @@ macro_rules! equal_rows_elem {
         let right_array = $r.as_any().downcast_ref::<$array_type>().unwrap();
 
         match (left_array.is_null($left), left_array.is_null($right)) {
-            (true, true) => true,
```
Comment (jorgecarleitao) [inline datafusion/src/physical_plan/hash_join.rs:711]: this was the line, right? Damm, so many wrong things for this one.

Really great finding, @Dandandan !

**Review by jorgecarleitao — COMMENTED** [review]
Sorry for the delay, @Dandandan and thanks for the nudge.

I went through this. I have a change that I think we should do it, but otherwise looks great. Super cool.

File: datafusion/src/physical_plan/hash_join.rs (hunk 2 above)
Comment (Dandandan) [reply datafusion/src/physical_plan/hash_join.rs:711]: Yep! To be fair I also added this line myself 😆

I think we also should start testing DataFusion more rigorously wrt null handling, but one step at a time.

File: datafusion/src/physical_plan/hash_join.rs (hunk 1 above)
Comment (Dandandan) [reply datafusion/src/physical_plan/hash_join.rs:955]: I am wondering, are the bytee not guaranteed to be the same for the same bitmaps?

File: datafusion/src/physical_plan/hash_join.rs (hunk 2 above)
Comment (Dandandan) [reply datafusion/src/physical_plan/hash_join.rs:711]: Even if it is, I noticed the values method doesn't take offset into account right now, so this is maybe an optimization worth doing once it is in the arrow kernel.

**Review by jorgecarleitao — APPROVED** [review]
💯

**Comment by alamb** [comment]
Sorry for the delay @Dandandan -- I am about out of time today, but I will take a careful look tomorrow morning

File: datafusion/src/physical_plan/hash_join.rs [hunk 3]
```diff
@@ -65,7 +65,7 @@ use log::debug;
 // Maps a `u64` hash value based on the left ["on" values] to a list of indices with this key's value.
 // E.g. 1 -> [3, 6, 8] indicates that the column values map to rows 3, 6 and 8 for hash value 1
 // As the key is a hash value, we need to check possible hash collisions in the probe stage
-type JoinHashMap = HashMap<u64, SmallVec<[u64; 1]>, IdHashBuilder>;
+type JoinHashMap = HashMap<(), SmallVec<[u64; 1]>, IdHashBuilder>;
```
Comment (alamb) [inline datafusion/src/physical_plan/hash_join.rs:68]: I am a little confused about using `()` as the key type for the `HashMap` -- maybe updating the comments would help

File: datafusion/src/physical_plan/hash_join.rs [hunk 4]
```diff
@@ -399,15 +395,23 @@ fn update_hash(
...
-        hash.raw_entry_mut()
-            .from_key_hashed_nocheck(*hash_value, hash_value)
-            .and_modify(|_, v| v.push((row + offset) as u64))
-            .or_insert_with(|| (*hash_value, smallvec![(row + offset) as u64]));
+        match hash.raw_entry_mut().from_hash(*hash_value, |_| true) {
+            hashbrown::hash_map::RawEntryMut::Occupied(mut entry) => {
+                entry.get_mut().push((row + offset) as u64);
+            }
+            hashbrown::hash_map::RawEntryMut::Vacant(entry) => {
+                entry.insert_hashed_nocheck(
```
Comment (alamb) [inline datafusion/src/physical_plan/hash_join.rs:408]: Does this code do the right thing if there are collisions in the hash table (aka the same key column values hash to the same hash value?) I am not enough of an expert on HashBrown to really know, but something feels off to me here.

File: datafusion/src/physical_plan/hash_join.rs (hunk 2 above)
Comment (alamb) [reply datafusion/src/physical_plan/hash_join.rs:711]: The fact we are now worrying about and fixing null handling is a sign, in my mind, of DataFusion's maturation 🤣

File: datafusion/src/physical_plan/hash_join.rs [hunk 5]
```diff
@@ -755,21 +766,75 @@ fn equal_rows(
...
+                for (hash, value) in $hashes.iter_mut().zip(values.iter()) {
+                    *hash = combine_hashes($ty::get_hash(value, $random_state), *hash);
+                }
+            } else {
+                for (hash, value) in $hashes.iter_mut().zip(values.iter()) {
+                    *hash = $ty::get_hash(value, $random_state)
+                }
+            }
+        } else {
+            if $multi_col {
```
Comment (alamb) [inline datafusion/src/physical_plan/hash_join.rs:821]: special casing multi-value join columns is a good one

**Review by alamb — APPROVED** [review]
I am a little confused about the lack of keys in the hash map, but otherwise things look good to me

File: datafusion/src/physical_plan/hash_join.rs (hunk 3 above)
Comment (Dandandan) [reply datafusion/src/physical_plan/hash_join.rs:68]: I will add some comments about it for sure!

Eventually we can get rid of the hashmap entirely, as we check for collisions in a later stage.

File: datafusion/src/physical_plan/hash_join.rs (hunk 4 above)
Comment (Dandandan) [reply datafusion/src/physical_plan/hash_join.rs:408]: The overall algorithm does do the checking for collisions (values with the same hash) in the later stage. There is a unit checking this case too.

File: datafusion/src/physical_plan/hash_join.rs (hunk 3 above)
Comment (Dandandan) [reply datafusion/src/physical_plan/hash_join.rs:77]: Added some extra docs now :)
