### PR TITLE
InList: set/list value must be evaluated to get the values

### LINKED ISSUE #2820: Not evaluate the set expr in the InList for the optimization
**Describe the bug**
From this pr https://github.com/apache/arrow-datafusion/pull/2156, @Ted-Jiang optimize the inlist using the set scalar.

But get the static value from below code：
```
fn cast_static_filter_to_set(list: &[Arc<dyn PhysicalExpr>]) -> HashSet<ScalarValue> {
    HashSet::from_iter(list.iter().map(|expr| {
        if let Some(cast) = expr.as_any().downcast_ref::<expressions::CastExpr>() {
            cast.expr()
                .as_any()
                .downcast_ref::<expressions::Literal>()
                .unwrap()
                .value()
                .clone()
        } else {
            expr.as_any()
                .downcast_ref::<expressions::Literal>()
                .unwrap()
                .value()
                .clone()
        }
    }))
}
```
This will not get the right value for the set expr. 
We should eval the set expr to get the set scalar values.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

Closes #2820 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/in_list.rs [hunk 1]
```diff
@@ -270,37 +270,51 @@ fn not_in_list_utf8<OffsetSize: OffsetSizeTrait>(
 }
 
 //check all filter values of In clause are static.
-//include `CastExpr + Literal` or `Literal`
+//include `TryCastExpr/CastExpr + Literal` or `Literal`
 fn check_all_static_filter_expr(list: &[Arc<dyn PhysicalExpr>]) -> bool {
+    // TODO optimize the checker for constant in datafusion
```
Comment (liukun4515) [inline datafusion/physical-expr/src/expressions/in_list.rs:275]: for datafusion, we need to add interface which is used to identify the expr is constant or  literal or not.
If we have this interface, we can make more optimization.
But the interface should be better in the logical expr not in the physical expr like sprak `fold`

Comment (alamb) [reply datafusion/physical-expr/src/expressions/in_list.rs:275]: I think `ColumnarValue` is one such interface

https://github.com/apache/arrow-datafusion/blob/41b4e491663029f653e491b110d0b5e74d08a0b6/datafusion/expr/src/columnar_value.rs#L29-L34

So if you call `evaluate()` on a `Literal` `PhysicalExpr` the returned value is `ColumnarValue::Scalar`:

https://github.com/apache/arrow-datafusion/blob/master/datafusion/physical-expr/src/expressions/literal.rs#L72

Comment (alamb) [reply datafusion/physical-expr/src/expressions/in_list.rs:275]: One way to make this code more general might be to change the check for all static expressions to *after* `evaluate()` is called. 

Specifically, maybe the  

```rust
        if list.len() > OPTIMIZER_INSET_THRESHOLD && check_all_static_filter_expr(&list) {
```

check could be refactored to call `evaluate` on all the elements of the list and then if all elements were `ColumnarValue::Scalar` and the list was sufficiently larger the set optimization could be invoked 🤔

**Review by alamb — APPROVED** [review]
I think this PR is an improvement. Thank you @liukun4515 

I left a suggestion on how to maybe make the check more general (aka not have to special case different expression types).

**Comment by liukun4515** [comment]
> I think this PR is an improvement. Thank you @liukun4515
> 
> I left a suggestion on how to maybe make the check more general (aka not have to special case different expression types).

Thanks for you suggestion about `evel const value`.
I have changed the code according to your suggestion.
```
let batch = RecordBatch::new_empty(Arc::new(schema.to_owned()));
    list.iter().all(|v| match v.evaluate(&batch) {
        Err(_) | Ok(ColumnarValue::Array(_)) => false,
        Ok(ColumnarValue::Scalar(_)) => true,
    })
```
PTAL @alamb

File: datafusion/physical-expr/src/expressions/in_list.rs [hunk 2]
```diff
@@ -270,37 +270,27 @@ fn not_in_list_utf8<OffsetSize: OffsetSizeTrait>(
...
-                .as_any()
-                .downcast_ref::<expressions::Literal>()
-                .is_some()
-        } else {
-            let cast = v.as_any().downcast_ref::<expressions::Literal>();
-            cast.is_some()
-        }
+//include `TryCastExpr/CastExpr + Literal` or `Literal`
+fn check_all_static_filter_expr(list: &[Arc<dyn PhysicalExpr>], schema: &Schema) -> bool {
+    let batch = RecordBatch::new_empty(Arc::new(schema.to_owned()));
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/in_list.rs:275]: This is looking better -- but now `evaluate()` will be called *twice* on the inputs; Both here as well as in `cast_static_filter_to_set` . Since calling `evaluate` may be quite expensive, what do you think about calling it once and then passing the resulting `Vec<ColumnarValue>` to both `check_all_static_filter_expr` and `cast_static_filter_to_set`?

Comment (liukun4515) [reply datafusion/physical-expr/src/expressions/in_list.rs]: I add a new function `try_cast_static_filter_to_set` to replace these two function in the InLIst.

**Comment by liukun4515** [comment]
Thanks for your review. @alamb 
I think it's ready to be merged.

**Review by alamb — APPROVED** [review]
Looks great to me @liukun4515  -- thank you for sticking with it. I think it is a good sign when there is less code but more functionality 👍
