### PR TITLE
Parse nanoseconds for intervals

### LINKED ISSUE #3204: Interval Literal doesn't work for timeunit less than millisecond
**Describe the bug**

**To Reproduce**

It works for millisecond
```bash
❯ select interval '1 month 0.001 second';
+-------------------------------------------------------+
| IntervalMonthDayNano("79228162514264337593544950336") |
+-------------------------------------------------------+
| 0 years 1 mons 0 days 0 hours 0 mins 0.1000000 secs   |
+-------------------------------------------------------+
1 row in set. Query took 0.001 seconds.
```

but doesn't work while the unit for second less than millisecond 

```bash
❯ select interval '1 month 0.0001 second';
+------------------------------------------------+
| IntervalYearMonth("1")                         |
+------------------------------------------------+
| 0 years 1 mons 0 days 0 hours 0 mins 0.00 secs |
+------------------------------------------------+
1 row in set. Query took 0.002 seconds.
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #3204.

# Rationale for this change

Change parsing granularity of intervals from milliseconds to nanoseconds, to support passing fractions of milliseconds/seconds (down to nanoseconds) as `IntervalMonthDayNano` supports granularity down to nanoseconds.

# What changes are included in this PR?

Accumulating with nanoseconds instead of milliseconds, changing to f64/i128 where necessary to account for shift in range of values.

# Are these changes tested?

Added some unit tests, and fixed others as there is now more precision for seconds fractions.

# Are there any user-facing changes?

### CODE REVIEW

**Review by waynexia — APPROVED** [review]
Looks good to me, thanks @Jefffrey

File: datafusion/common/src/parsers.rs [hunk 1]
```diff
@@ -29,73 +29,74 @@ pub fn parse_interval(leading_field: &str, value: &str) -> Result<ScalarValue> {
...
-            milles_part += (day_part - ((day_part as i32) as f32))
-                * 24_f32
+            nanos_part += (day_part - ((day_part as i64) as f64))
+                * 24_f64
                 * SECONDS_PER_HOUR
-                * MILLIS_PER_SECOND;
+                * NANOS_PER_SECOND;
 
-            (month_part as i32, day_part as i32, milles_part)
+            (month_part as i64, day_part as i64, nanos_part)
```
Comment (waitingkuo) [inline datafusion/common/src/parsers.rs:42]: 👍

**Review by waitingkuo — COMMENTED** [review]
thank you @Jefffrey 

there's a bug while displaying IntervalMonthDayNano
```bash
❯ select interval '0.0001 second';
+----------------------------------------------------+
| IntervalMonthDayNano("100000")                     |
+----------------------------------------------------+
| 0 years 0 mons 0 days 0 hours 0 mins 0.100000 secs |
+----------------------------------------------------+
1 row in set. Query took 0.002 seconds.
```
i checked the underline value it's correct `(month: 0, day: 0, nanos: 100000)`
i think this is the display issue

**Comment by Jefffrey** [comment]
> thank you @Jefffrey
> 
> there's a bug while displaying IntervalMonthDayNano
> 
> ```shell
> ❯ select interval '0.0001 second';
> +----------------------------------------------------+
> | IntervalMonthDayNano("100000")                     |
> +----------------------------------------------------+
> | 0 years 0 mons 0 days 0 hours 0 mins 0.100000 secs |
> +----------------------------------------------------+
> 1 row in set. Query took 0.002 seconds.
> ```
> 
> i checked the underline value it's correct `(month: 0, day: 0, nanos: 100000)` i think this is the display issue

Issue with arrow-rs, has already been addressed: https://github.com/apache/arrow-rs/pull/3093

**Comment by waitingkuo** [comment]
while we have leading zeros after decimal, it displays incorrectly
```bash
❯ select interval '0.01 second';
+------------------------------------------------+
| IntervalDayTime("10")                          |
+------------------------------------------------+
| 0 years 0 mons 0 days 0 hours 0 mins 0.10 secs |
+------------------------------------------------+
1 row in set. Query took 0.000 seconds.

❯ select interval '0.001 second';
+------------------------------------------------+
| IntervalDayTime("1")                           |
+------------------------------------------------+
| 0 years 0 mons 0 days 0 hours 0 mins 0.01 secs |
+------------------------------------------------+
1 row in set. Query took 0.000 seconds.
```

File: datafusion/core/tests/sql/expr.rs [hunk 2]
```diff
@@ -917,19 +917,19 @@ async fn test_interval_expressions() -> Result<()> {
...
     test_expression!(
         "interval '0.49999 day'",
         "0 years 0 mons 0 days 11 hours 59 mins 59.136 secs"
     );
     test_expression!(
         "interval '0.49999999999 day'",
-        "0 years 0 mons 0 days 12 hours 0 mins 0.00 secs"
+        "0 years 0 mons 0 days 11 hours 59 mins 59.999999136 secs"
     );
     test_expression!(
```
Comment (waitingkuo) [inline datafusion/core/tests/sql/expr.rs:934]: i think we can add a test case for this (which will fail in the current version) and wait for the update to arrow 27 #4199
```suggestion
    test_expression!(
        "interval '0.00000000001 day'",
        "0 years 0 mons 0 days 0 hours 0 mins 0.000000864 secs"
    );
    test_expression!(
```

Comment (waitingkuo) [reply datafusion/core/tests/sql/expr.rs:934]: i just found that the arrow-rs fix isn't included in 27.0.0
@tustvold do you have any suggestion for this? should we just merge this first and add some test cases after arrow 28.0.0 merged?

Comment (alamb) [reply datafusion/core/tests/sql/expr.rs:934]: We can also add test cases that are marked as `#[should_fail]`

**Comment by alamb** [comment]
Thanks @Jefffrey  for the fix and @waitingkuo and @waynexia for the reviews!
