### PR TITLE
Eagerly construct PagePruningPredicate

### LINKED ISSUE #4693: PruningPredicate Different Evaluation Context from Query
**Describe the bug**

`PruningPredicate::try_new` creates its own `ExecutionProps::new` which captures `Utc::now` as the current time, this may differ from what the rest of the plan was evaluated against, yielding incorrect results

**To Reproduce**

**Expected behavior**

`PruningPredicate` should evaluate its expressions in the same context as normal query evaluation

**Additional context**

#4629 tracks making ExecutionProps a trait
#4617 is the broader issue around state mutability and inheritance

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Part of #4693 

# Rationale for this change

Eagerly constructing the `PagePruningPredicate` not only saves cycles, but allows it to occur when `ExecutionProps` is in scope. A future PR will update `PruningPredicate` to require this to resolve #4693

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs [hunk 1]
```diff
@@ -99,94 +100,110 @@ use super::metrics::ParquetFileMetrics;
...
+                (columns.len() == 1)
+                    .then(|| PruningPredicate::try_new(predicate.clone(), schema.clone()))
+            })
+            .collect::<Result<Vec<_>>>()?;
+        Ok(Self { predicates })
     }
 
-    let groups = file_metadata.row_groups();
+    /// Returns a [`RowSelection`] for the given file
+    pub fn prune(
```
Comment (tustvold) [inline datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs:123]: I recommend viewing this with whitespace disabled

https://github.com/apache/arrow-datafusion/pull/4713/files?diff=split&w=1

File: datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs [hunk 2]
```diff
@@ -203,35 +220,6 @@ fn combine_multi_col_selection(row_selections: Vec<Vec<RowSelector>>) -> RowSele
         .unwrap()
 }
 
-// Extract single col pruningPredicate from input predicate for evaluating page Index.
-fn extract_page_index_push_down_predicates(
```
Comment (tustvold) [inline datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs:207]: This is reworked into PagePruningPredicate::try_new

File: datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs [hunk 3]
```diff
@@ -99,94 +100,114 @@ use super::metrics::ParquetFileMetrics;
...
-        return Ok(None);
+impl PagePruningPredicate {
+    /// Create a new [`PagePruningPredicate`]
+    pub fn try_new(expr: &Expr, schema: SchemaRef) -> Result<Self> {
+        let predicates = split_conjunction(expr)
+            .into_iter()
+            .filter_map(|predicate| match predicate.to_columns() {
+                Ok(columns) if columns.len() == 1 => {
+                    match PruningPredicate::try_new(predicate.clone(), schema.clone()) {
+                        Ok(p) if !p.allways_true() => Some(Ok(p)),
```
Comment (tustvold) [inline datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs:116]: It is important we filter these out as they cause issues for the pruning logic below as they no longer refer to a single column

File: datafusion/core/src/physical_plan/file_format/parquet.rs [hunk 4]
```diff
@@ -126,14 +127,18 @@ impl ParquetExec {
...
-            .and_then(|pruning_predicate| {
-                // If the pruning predicate can't prune anything, don't try
-                if pruning_predicate.allways_true() {
+            .filter(|p| !p.allways_true());
+
+        let page_pruning_predicate = predicate.as_ref().and_then(|predicate_expr| {
+            match PagePruningPredicate::try_new(predicate_expr, file_schema.clone()) {
+                Ok(pruning_predicate) => Some(Arc::new(pruning_predicate)),
+                Err(e) => {
+                    debug!("Could not create page pruning predicate for: {}", e);
```
Comment (alamb) [inline datafusion/core/src/physical_plan/file_format/parquet.rs:136]: I think it would be worth including the `predicate_expr` in this message too

```suggestion
                    debug!("Could not create page pruning predicate for '{}': {}", predicate_expr, e);
```

File: datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs (hunk 3 above)
Comment (alamb) [reply datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs:116]: Why don't they refer to a single column? isn't this branch protected by a match guard `if columns.len() == 1`?

**Review by alamb — APPROVED** [review]
Looks good to me -- thanks @tustvold 

cc @Ted-Jiang @thinkharderdev

File: datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs (hunk 3 above)
Comment (tustvold) [reply datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs:116]: Because the expression gets simplified down to `true` and therefore now refers to no columns 😅

**Review by thinkharderdev — APPROVED** [review]

File: datafusion/core/src/physical_plan/file_format/parquet.rs (hunk 4 above)
Comment (alamb) [reply datafusion/core/src/physical_plan/file_format/parquet.rs:136]: Proposed change in https://github.com/apache/arrow-datafusion/pull/4736
