### PR TITLE
fix join column handling logic for `On` and `Using` constraints

### LINKED ISSUE #601: Panic while running join datatypes/schema.rs:165:10
**Describe the bug**

> select * from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.3.0/src/datatypes/schema.rs:165:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**To Reproduce**
```shell
echo "1" > /tmp/foo.csv
cargo run -p datafusion-cli 
```

```sql
> CREATE EXTERNAL TABLE foo(bar int)
STORED AS CSV
LOCATION '/tmp/foo.csv';
0 rows in set. Query took 0.000 seconds.
> select * from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.3.0/src/datatypes/schema.rs:165:10
```

**Expected behavior**
Expected output of 1 row, with columns `f1.foo` and `f2.foo` each with value 1

**Additional context**
Likely follow on work from https://github.com/apache/arrow-datafusion/pull/55

### LINKED ISSUE #671: self-join followed by a projection with duplicated names results in panic
**Describe the bug**

this is most likely on how we deal with self-joins

**To Reproduce**

```sql
SELECT
  t1.c9, t2.c9
FROM test t1
INNER JOIN test t2
ON t1.c9 = t2.c9;
```

```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.4.0/src/datatypes/schema.rs:165:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

this would work in Postgres

**Additional context**

### PR DESCRIPTION
**Pull request by houqp**
# Which issue does this PR close?

Follow up for https://github.com/apache/arrow-datafusion/pull/55#pullrequestreview-683118433.

Closes #601.
Closes #671.

Also fixed a bug where `index_of_column` won't error out on duplicated fields.

 # Rationale for this change

In MySQL and Postgres, Join with `On` constraints produces output with join column from both relations preserved. For example:

```sql
SELECT * FROM test t1 JOIN test t2 ON t1.id = t2.id;
```
produces:

| id  | id  |
| --- | --- |
| 1   | 1   |
| 2   | 2   |

While join with `Using` constraints deduplicates the join column:

```sql
SELECT * FROM test t1 JOIN test t2 USING (id);
```

produces:

| id  |
| --- |
| 1   |
| 2   |

However, in our current implementation, join column dedup is applied in all cases. This PR changes the behavior so it's consistent with MySQL and Postgres.

Here comes the annoying part.

Note that for join with `Using` constraint, users can still project join columns using relations from both sides. For example `SELECT t1.id, t2.id FROM test t1 JOIN test t2 USING (id)` produces the same output as `SELECT * FROM test t1 JOIN test t2 ON t1.id = t2.id`.

This means for `Using` joins, we need to model a join column as a single shared column between both relations. Current `DFField` struct only allows a field/column to have a single qualifier, so I ended adding a new `shared_qualifiers` field to `DFField` struct to handle this edge-case. Our logical plan builder will be responsible for setting this field when building join queries with using constraints. During query optimization and planning, the `shared_qualifiers` field is used to look up column by name and qualifier.

Other alternatives include changing the `qualifer` field of `DFField` to an option of enum to account for single qualifier and shared qualifiers. None of these approaches felt elegant to me. I am curious if anyone has ideas or suggestions on how to better implement this behavior.

# What changes are included in this PR?

* Expose JoinConstraints to ballista.proto
* Unify JoinType enum between logical and physical planes
* Added context execution tests to enforce semantics for `On` and `Using` joins
* Refactored dfschema module to use `index_of_column_by_name` in `both index_of_column` and `field_with_qualified_name` methods.

# Are there any user-facing changes?

Join with `On` constraints will now output joined columns from both relations without deduplication. Dedup is only applied to join with `Using` constraints.

### CODE REVIEW

File: datafusion/src/physical_plan/hash_utils.rs [hunk 1]
```diff
@@ -21,25 +21,9 @@ use crate::error::{DataFusionError, Result};
 use arrow::datatypes::{Field, Schema};
 use std::collections::HashSet;
 
+use crate::logical_plan::{JoinConstraint, JoinType};
 use crate::physical_plan::expressions::Column;
 
-/// All valid types of joins.
-#[derive(Clone, Copy, Debug, Eq, PartialEq)]
-pub enum JoinType {
```
Comment (houqp) [inline datafusion/src/physical_plan/hash_utils.rs:28]: reuse the same enum from logical plane.

**Review by alamb — COMMENTED** [review]
Thank you @houqp  -- I think this PR is an improvement.

Also, I did some more testing and there are still cases that don't appear to be working (which I think would be fine to do as a follow on PR) -- they no longer panic :)

```rust
echo "1" > /tmp/foo.csv
cargo run -p datafusion-cli 
```

```sql
> 
CREATE EXTERNAL TABLE foo(bar int)
STORED AS CSV
LOCATION '/tmp/foo.csv';
0 rows in set. Query took 0.000 seconds.
> select * from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
Plan("Schema contains duplicate unqualified field name 'bar'")

> select f1.bar, f2.bar from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
Plan("Schema contains duplicate unqualified field name 'bar'")

> select f1.bar, f2.bar from foo as f1 JOIN foo as f2 USING(bar);
NotImplemented("Unsupported compound identifier '[\"f1\", \"bar\"]'")

> select * from foo as f1 JOIN foo as f2 USING(bar);
+-----+
| bar |
+-----+
| 1   |
+-----+
```

**Comment by alamb** [comment]
@houqp 

The approach we seem to be taking is to try and keep the information about where a column came from in a join -- e.g. that a output DF field could be referred to as either `f1.foo` or `f2.foo` for example, which is getting complicated

It seems like a core challenge is in the semantics of the `*` expansion in `select * from ...` type queries which varies depending on type of join. Have you considered perhaps focusing in that area rather than trying to track the optional qualifiers through the plans?

So for example, in a `f1 JOIN f1` have the output schema contain both `f1.foo` and `f2.foo` but then change the expansion of `*` to have somethign like `f1.foo as foo`?

File: datafusion/src/logical_plan/dfschema.rs [hunk 2]
```diff
@@ -387,6 +402,9 @@ impl Display for DFSchema {
 pub struct DFField {
     /// Optional qualifier (usually a table or relation name)
     qualifier: Option<String>,
+    /// Optional set of qualifiers that all share this same field. This is used for `JOIN USING`
```
[the remark this answers is not in the document]
Comment (houqp) [reply datafusion/src/logical_plan/dfschema.rs:405]: Yeah, this is the part I am not a fan about the current implementation, a field having both shared_qualifiers and single qualifier should never happen. An optional enum type on qualifier field would provide the correct semantic we want to capture here.

**Comment by houqp** [comment]
Good catch on the regressions, I will get them fixed tonight with unit tests.

> It seems like a core challenge is in the semantics of the * expansion in select * from ... type queries which varies depending on type of join.

Yeah, that's exactly the problem.

Initially, I tried the approach of keeping the join columns from both relations (i.e. `f1.foo` and `f2.foo`) in the logical schema. Then I ran into the problem of it breaking the [physical planning invariants](https://github.com/apache/arrow-datafusion/blob/master/docs/specification/invariants.md#the-physical-schema-is-invariant-under-planning). Because for `Using` join, we are only producing a single join column in the output, the physical plan schema can only has a single field for the join column. The schema from the logical plan will need to match that as well in order to honor that invariant.

File: datafusion/src/logical_plan/dfschema.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (houqp) [reply datafusion/src/logical_plan/dfschema.rs:405]: I am going to try the enum approach as an alternative implementation, then we can take a look at it to see which one looks better.

[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/src/logical_plan/dfschema.rs:405]: sounds good

**Comment by alamb** [comment]
> Because for Using join, we are only producing a single join column in the output

is this something we can change (aka update the using join to produce columns and then rely on projection pushdown to prune the uneeded ones out?)

**Comment by houqp** [comment]
> is this something we can change (aka update the using join to produce columns and then rely on projection pushdown to prune the uneeded ones out?)

That's a good point, the single column output semantic doesn't need to be enforced at the join node level. let me give this a try as well :+1:  This could simplify our join handling logic. I will also double check to see if this would result in nontrivial runtime overhead for us.

**Comment by houqp** [comment]
@alamb, I wasn't able to reproduce the errors you showed in https://github.com/apache/arrow-datafusion/pull/605#pullrequestreview-690682368

Here is what I got:

```
> CREATE EXTERNAL TABLE foo(bar int)
STORED AS CSV
LOCATION '/tmp/foo.csv';
0 rows in set. Query took 0.001 seconds.
> select f1.bar, f2.bar from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
+-----+-----+
| bar | bar |
+-----+-----+
| 3   | 3   |
| 1   | 1   |
| 4   | 4   |
| 2   | 2   |
+-----+-----+
4 rows in set. Query took 0.022 seconds.
>  select * from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
+-----+-----+
| bar | bar |
+-----+-----+
| 3   | 3   |
| 1   | 1   |
| 4   | 4   |
| 2   | 2   |
+-----+-----+
4 rows in set. Query took 0.022 seconds.
> select f1.bar, f2.bar from foo as f1 JOIN foo as f2 USING(bar);
+-----+-----+
| bar | bar |
+-----+-----+
| 2   | 2   |
| 3   | 3   |
| 1   | 1   |
| 4   | 4   |
+-----+-----+
4 rows in set. Query took 0.020 seconds.
> 
```

Perhaps you rain those tests with a different build?

**Comment by alamb** [comment]
> Perhaps you rain those tests with a different build?

I am not sure what I tested with, but I re-ran the tests at b8da356a4a07a2733f5b260f763198a114f60fc7 and everything is working -- sorry for the noise.

**Comment by houqp** [comment]
let's wait for my alternative solutions and review them together before the merge unless this is urgent issue in master that this PR addresses. I would like to avoid merging in a premature abstraction to reduce noise :)

**Comment by alamb** [comment]
Marking as draft so it is clearer from the list of PRs that this one is not quite ready to go (and thus I don't merge it accidentally)

File: ballista/rust/core/src/serde/logical_plan/from_proto.rs [hunk 3]
```diff
@@ -257,23 +257,32 @@ impl TryInto<LogicalPlan> for &protobuf::LogicalPlanNode {
...
                         ))
                     })?;
-                let join_type = match join_type {
-                    protobuf::JoinType::Inner => JoinType::Inner,
-                    protobuf::JoinType::Left => JoinType::Left,
-                    protobuf::JoinType::Right => JoinType::Right,
-                    protobuf::JoinType::Full => JoinType::Full,
-                    protobuf::JoinType::Semi => JoinType::Semi,
-                    protobuf::JoinType::Anti => JoinType::Anti,
-                };
```
Comment (houqp) [inline ballista/rust/core/src/serde/logical_plan/from_proto.rs:267]: conversion handled by shared method in `serde/mod.rs`

File: datafusion/src/logical_plan/builder.rs [hunk 4]
```diff
@@ -440,65 +424,19 @@ impl LogicalPlanBuilder {
...
-                    .map(|on| on.1.clone())
-                    .collect::<HashSet<_>>(),
-                // using join requires unique join columns in the output schema, so we mark all
-                // right join keys as duplicate
-                JoinConstraint::Using => {
-                    on.iter().map(|on| on.1.clone()).collect::<HashSet<_>>()
-                }
-            };
-
+        JoinType::Inner | JoinType::Left | JoinType::Full | JoinType::Right => {
```
Comment (houqp) [inline datafusion/src/logical_plan/builder.rs:430]: Join schemas are now consistent across all join types and constraints. We implement the join column "merge" semantic externally in plan builder and optimizer.

File: datafusion/src/logical_plan/dfschema.rs [hunk 5]
```diff
@@ -149,47 +147,80 @@ impl DFSchema {
...
     }
 
-    /// Find the index of the column with the given qualifer and name
-    pub fn index_of_column(&self, col: &Column) -> Result<usize> {
-        for i in 0..self.fields.len() {
-            let field = &self.fields[i];
-            if field.qualifier() == col.relation.as_ref() && field.name() == &col.name {
-                return Ok(i);
-            }
+    fn index_of_column_by_name(
```
Comment (houqp) [inline datafusion/src/logical_plan/dfschema.rs:150]: Refactored this code into its own helper method to reduce duplicated code between `field_with_qualified_name` and `index_of_column`. This should also make `index_of_column` more robust.

File: datafusion/src/logical_plan/expr.rs [hunk 6]
```diff
@@ -1118,36 +1133,56 @@ pub fn columnize_expr(e: Expr, input_schema: &DFSchema) -> Expr {
     }
 }
 
+/// Recursively replace all Column expressions in a given expression tree with Column expressions
+/// provided by the hash map argument.
+pub fn replace_col(e: Expr, replace_map: &HashMap<&Column, &Column>) -> Result<Expr> {
```
Comment (houqp) [inline datafusion/src/logical_plan/expr.rs:1138]: this is used in predicate push down optimizer to push predicates to both sides of the join clause.

File: datafusion/src/logical_plan/expr.rs [hunk 7]
```diff
@@ -1118,36 +1133,56 @@ pub fn columnize_expr(e: Expr, input_schema: &DFSchema) -> Expr {
...
+
+    e.rewrite(&mut ColumnReplacer { replace_map })
+}
+
 /// Recursively call [`Column::normalize`] on all Column expressions
 /// in the `expr` expression tree.
-pub fn normalize_col(e: Expr, schemas: &[&DFSchemaRef]) -> Result<Expr> {
-    struct ColumnNormalizer<'a, 'b> {
-        schemas: &'a [&'b DFSchemaRef],
+pub fn normalize_col(e: Expr, plan: &LogicalPlan) -> Result<Expr> {
```
Comment (houqp) [inline datafusion/src/logical_plan/expr.rs:1161]: Change from schema to logical plan so we can extract join columns for join clauses with using constraints.

File: datafusion/src/physical_plan/hash_utils.rs [hunk 8]
```diff
@@ -104,46 +88,11 @@ fn check_join_set_is_valid(
 
 /// Creates a schema for a join operation.
 /// The fields from the left side are first
-pub fn build_join_schema(
-    left: &Schema,
-    right: &Schema,
-    on: JoinOnRef,
-    join_type: &JoinType,
-) -> Schema {
+pub fn build_join_schema(left: &Schema, right: &Schema, join_type: &JoinType) -> Schema {
```
Comment (houqp) [inline datafusion/src/physical_plan/hash_utils.rs:91]: same schema build simplification as the one we introduced in logical plan builder.

File: datafusion/src/sql/planner.rs [hunk 9]
```diff
@@ -560,7 +560,8 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
                 //   SELECT c1 AS m FROM t HAVING c1 > 10;
                 //   SELECT c1, MAX(c2) AS m FROM t GROUP BY c1 HAVING MAX(c2) > 10;
                 //
-                resolve_aliases_to_exprs(&having_expr, &alias_map)
+                let having_expr = resolve_aliases_to_exprs(&having_expr, &alias_map)?;
+                normalize_col(having_expr, &projected_plan)
```
Comment (houqp) [inline datafusion/src/sql/planner.rs:564]: needed if having expression referenced using join columns with unqualified column name.

**Comment by houqp** [comment]
@alamb reimplemented the logic based on your suggestion in https://github.com/apache/arrow-datafusion/pull/605#issuecomment-866862804.

Turns out there are many more edge-cases that need to be handled for using join other than wildcard expansion:

* predicate push down on join columns
* normalize unqualified column expressions that reference join columns with qualifiers

I have implemented support for all these edge-cases, but decided to leave out the wildcard expansion change as a follow up PR to keep the diff easier to review.

**Review by Jimexist — APPROVED** [review]
LGTM

**Comment by alamb** [comment]
Thanks @houqp  -- I'll try and review this later today but I may run out of time in which case I'll get it done tomorrow

File: datafusion/src/logical_plan/dfschema.rs [hunk 10]
```diff
@@ -149,47 +147,80 @@ impl DFSchema {
...
+            .enumerate()
+            .filter(|(_, field)| match (qualifier, &field.qualifier) {
+                // field to lookup is qualified.
+                // current field is qualified and not shared between relations, compare both
+                // qualifer and name.
+                (Some(q), Some(field_q)) => q == field_q && field.name() == name,
+                // field to lookup is qualified but current field is unqualified.
+                (Some(_), None) => false,
+                // field to lookup is unqualified, no need to compare qualifier
+                _ => field.name() == name,
```
Comment (Jimexist) [inline datafusion/src/logical_plan/dfschema.rs:167]: prefer to write out cases, `(None, None)` and `(None, Some(_)` and union them. this makes it clearer?

File: datafusion/src/logical_plan/expr.rs [hunk 11]
```diff
@@ -89,14 +89,46 @@ impl Column {
...
-        for schema in schemas {
-            if let Ok(field) = schema.field_with_unqualified_name(&self.name) {
-                return Ok(field.qualified_column());
+        let schemas = plan.all_schemas();
+        let using_columns = plan.using_columns()?;
+
+        for schema in &schemas {
+            let fields = schema.fields_with_unqualified_name(&self.name);
+            match fields.len() {
+                0 => continue,
```
Comment (Jimexist) [inline datafusion/src/logical_plan/expr.rs:103]: how would this be possible?

File: datafusion/src/logical_plan/expr.rs (hunk 6 above)
Comment (Jimexist) [reply datafusion/src/logical_plan/expr.rs:1151]: use `pub(crate)`?

File: datafusion/src/logical_plan/plan.rs [hunk 12]
```diff
@@ -354,6 +356,43 @@ impl LogicalPlan {
...
+                    join_constraint: JoinConstraint::Using,
+                    on,
+                    ..
+                } = plan
+                {
+                    self.using_columns.push(
+                        on.iter()
+                            .map(|entry| {
+                                std::iter::once(entry.0.clone())
+                                    .chain(std::iter::once(entry.1.clone()))
```
Comment (Jimexist) [inline datafusion/src/logical_plan/plan.rs:380]: why not just flatmap with a `vec![entry.0.clone(), entry.1.clone()]` - it's cleaner

File: datafusion/src/optimizer/filter_push_down.rs [hunk 13]
```diff
@@ -96,12 +96,21 @@ fn get_join_predicates<'a>(
     let left_columns = &left
         .fields()
         .iter()
-        .map(|f| f.qualified_column())
+        .map(|f| {
+            std::iter::once(f.qualified_column())
+                // we need to push down filter using unqualified column as well
+                .chain(std::iter::once(f.unqualified_column()))
```
Comment (Jimexist) [inline datafusion/src/optimizer/filter_push_down.rs:102]: same as https://github.com/apache/arrow-datafusion/pull/605/files#r664543206

File: datafusion/src/optimizer/filter_push_down.rs [hunk 14]
```diff
@@ -96,12 +96,21 @@ fn get_join_predicates<'a>(
...
+        })
+        .flatten()
         .collect::<HashSet<_>>();
     let right_columns = &right
         .fields()
         .iter()
-        .map(|f| f.qualified_column())
+        .map(|f| {
+            std::iter::once(f.qualified_column())
```
Comment (Jimexist) [inline datafusion/src/optimizer/filter_push_down.rs:110]: same as https://github.com/apache/arrow-datafusion/pull/605/files#r664543206

File: datafusion/src/logical_plan/plan.rs (hunk 12 above)
Comment (houqp) [reply datafusion/src/logical_plan/plan.rs:380]: i wanted to avoid an extra memory allocation incurred by `Vec::new`, but i will double check to see if once chain is actually generating the optimal code without memory allocations.

File: datafusion/src/logical_plan/expr.rs (hunk 11 above)
Comment (houqp) [reply datafusion/src/logical_plan/expr.rs:103]: We are iterating through schemas from all plan nodes in the provided plan tree, each plan node could have different schemas, so when we do the `fields_with_unqualified_name` look up, some of these plan nodes will no contain a field that matches `self.name`. We just pick the first one that matches the unqualified name.

File: datafusion/src/logical_plan/dfschema.rs [hunk 15]
```diff
@@ -149,47 +147,80 @@ impl DFSchema {
...
+            })
+            .map(|(idx, _)| idx)
+            .collect();
+
```
Comment (alamb) [inline datafusion/src/logical_plan/dfschema.rs:171]: it probably doesn't matter but you could avoid the Vec allocation by something like:

```rust
        let matches = self....; 
        match matches.next() {
        let name = matches.next() {
          None => // error about no field
          Some(name) { 
            if matches.next().is_some() => // error about ambiguous reference
            else name
          }
```

File: datafusion/src/logical_plan/expr.rs (hunk 7 above)
Comment (alamb) [reply datafusion/src/logical_plan/expr.rs:1174]: Note I wrote some tests that will need to be adjusted in https://github.com/apache/arrow-datafusion/pull/689 but that is no big deal

File: datafusion/src/logical_plan/plan.rs [hunk 16]
```diff
@@ -354,6 +356,43 @@ impl LogicalPlan {
             | LogicalPlan::CreateExternalTable { .. } => vec![],
         }
     }
+
+    /// returns all `Using` join columns in a logical plan
+    pub fn using_columns(&self) -> Result<Vec<HashSet<Column>>, DataFusionError> {
```
Comment (alamb) [inline datafusion/src/logical_plan/plan.rs:361]: FWIW this function feels like it might better belong in some sort of utils rather than a method on `LogicalPlan` -- perhaps https://github.com/houqp/arrow-datafusion/blob/qp_join/datafusion/src/optimizer/utils.rs#L50

File: datafusion/src/optimizer/filter_push_down.rs [hunk 17]
```diff
@@ -232,6 +241,38 @@ fn split_members<'a>(predicate: &'a Expr, predicates: &mut Vec<&'a Expr>) {
     }
 }
 
+fn optimize_join(
```
Comment (alamb) [inline datafusion/src/optimizer/filter_push_down.rs:244]: Nice

File: datafusion/src/optimizer/filter_push_down.rs [hunk 18]
```diff
@@ -901,20 +979,61 @@ mod tests {
             format!("{:?}", plan),
             "\
             Filter: #test.a LtEq Int64(1)\
-            \n  Join: #test.a = #test.a\
+            \n  Join: #test.a = #test2.a\
```
Comment (alamb) [inline datafusion/src/optimizer/filter_push_down.rs:982]: 👍

File: datafusion/src/physical_plan/hash_join.rs [hunk 19]
```diff
@@ -1996,16 +1992,16 @@ mod tests {
...
 
         let expected = vec![
-            "+----+----+----+----+----+",
-            "| a1 | c1 | a2 | b1 | c2 |",
-            "+----+----+----+----+----+",
-            "|    |    | 30 | 6  | 90 |",
-            "| 1  | 7  | 10 | 4  | 70 |",
-            "| 2  | 8  | 20 | 5  | 80 |",
-            "+----+----+----+----+----+",
+            "+----+----+----+----+----+----+",
```
Comment (alamb) [inline datafusion/src/physical_plan/hash_join.rs:1998]: these changes make sense to me

**Review by alamb — APPROVED** [review]
I think this looks good @houqp  -- I went through the test changes and code carefully and I think this is good to go. 

@Dandandan  I am not sure if you want to take a look at this given it changes how the Join relations are encoded.

**Comment by alamb** [comment]
Not sure if this will conflict with https://github.com/apache/arrow-datafusion/pull/660

**Comment by alamb** [comment]
I am going to merge this PR in (as it conflicts with https://github.com/apache/arrow-datafusion/pull/689) -- I think we can make additional improvements as follow on PRs.

**Comment by alamb** [comment]
Thanks again @houqp

**Comment by alamb** [comment]
I also merge `apache/master` into this branch locally on my machine and re-ran the tests to verify there were no conflicts

**Comment by alamb** [comment]
Aaand it looks like I forgot to fetch `apache/master` on my machine prior to testing -- fixed in https://github.com/apache/arrow-datafusion/pull/694

**Comment by houqp** [comment]
Apologize for being too busy last week and haven't had the time to update my PR, I am going to send a new PR to address all the feedbacks shortly.

File: datafusion/src/logical_plan/plan.rs (hunk 16 above)
Comment (houqp) [reply datafusion/src/logical_plan/plan.rs:361]: @alamb this is used outside of the optimizers as well, for example, the logical plan builder. With that context, do you still think it should live in optimizer utils module?

File: datafusion/src/logical_plan/dfschema.rs (hunk 15 above)
Comment (houqp) [reply datafusion/src/logical_plan/dfschema.rs:171]: Good suggestion, fixed in https://github.com/apache/arrow-datafusion/pull/703.

File: datafusion/src/logical_plan/plan.rs (hunk 12 above)
Comment (houqp) [reply datafusion/src/logical_plan/plan.rs:380]: @Jimexist sent https://github.com/apache/arrow-datafusion/pull/704 to address this. I found a comprise that's more readable and avoids the extra memory allocation.

Here is my test to compare the code gen with different approaches: https://godbolt.org/z/j3dcjbnvM.
