### PR TITLE
Fix panic in TopK

### LINKED ISSUE #7608: Panic in TopK aggregation when grouping by multiple values
### Describe the bug

When grouping by multiple values, datafusion crashes and the users sees the error: `Exactly 1 group value required`

### To Reproduce

Group by multiple values in a TopK style query (see sqllogictest in PR)

### Expected behavior

Short term: fall back to regular hash aggregation
Long term: use `OwnedRow` to optimize for multiple values as well

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by avantgardnerio**
## Which issue does this PR close?

Closes #7608.

## Rationale for this change

Resolve a panic for specific types of TopK queries.

## What changes are included in this PR?

- a fix
- a test

## Are these changes tested?

2/4... still trying to figure out how to test the last case. Maybe 3/4 is the best I can do.

## Are there any user-facing changes?

More queries should work

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]

File: datafusion/core/src/physical_optimizer/topk_aggregation.rs [hunk 1]
```diff
@@ -51,7 +52,7 @@ impl TopKAggregation {
         if desc != order.options.descending {
             return None;
         }
-        let group_key = aggr.group_expr().expr().first()?;
+        let group_key = aggr.group_expr().expr().iter().exactly_one().ok()?;
```
Comment (Dandandan) [inline datafusion/core/src/physical_optimizer/topk_aggregation.rs:55]: 😎😎😎

Comment (alamb) [inline datafusion/core/src/physical_optimizer/topk_aggregation.rs:55]: TIL `exactly_one`  👍  makes sense to me. 

Another way to write this that is more verbose but perhaps clearer might be:

```rust
if agg.group_expr().len() != 1 {
  return None;
}
```

**Review by alamb — APPROVED** [review]
Makes sense to me -- than you @avantgardnerio
