### PR TITLE
fix: type coercion ignore prevent  `Interval - Date`

### LINKED ISSUE #6176: type coercion forgot prevent `Interval - Date`
### Describe the bug

type coercion just consider `Timestamp - Interval` but ignore `Date - Interval`

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #6176.

# Rationale for this change

# What changes are included in this PR?

add type coercion for Date - Interval

# Are these changes tested?

add sqllogicaltest.

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/expr/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -147,14 +150,12 @@ pub fn coerce_types(
...
-            if (is_date(lhs_type)
-                || is_date(rhs_type)
-                || is_timestamp(lhs_type)
-                || is_timestamp(rhs_type)
+            if (is_datetime(lhs_type)
+                || is_datetime(rhs_type)
                 || is_interval(lhs_type)
                 || is_interval(rhs_type))
                 && (!is_interval(lhs_type)
-                    || !is_timestamp(rhs_type)
```
Comment (jackwener) [inline datafusion/expr/src/type_coercion/binary.rs:157]: Here don't consider `DateType`

**Review by alamb — COMMENTED** [review]
The code looks good to me -- thank you @jackwener 

How can we test this change? 

I tried this on master:

```
❯ select  '2023-05-01'::date - interval '1 month';
+----------------------------------------------------------------------------+
| Utf8("2023-05-01") - IntervalMonthDayNano("79228162514264337593543950336") |
+----------------------------------------------------------------------------+
| 2023-04-01                                                                 |
+----------------------------------------------------------------------------+
1 row in set. Query took 0.005 seconds.
❯ select  '2023-05-01'::date - '1 month';
Error during planning: Date32 - Utf8 can't be evaluated because there isn't a common type to coerce the types to
```

But the I get the same results on this branch 🤔

**Comment by jackwener** [comment]
@alamb thanks you.

Your case forgot `interval`.

I have test it.
```sql
❯ select  '2023-05-01'::date - interval '1 month';
+----------------------------------------------------------------------------+
| Utf8("2023-05-01") - IntervalMonthDayNano("79228162514264337593543950336") |
+----------------------------------------------------------------------------+
| 2023-04-01                                                                 |
+----------------------------------------------------------------------------+
```

**Comment by alamb** [comment]
> Your case forgot interval.


The thing is, this seems to work fine on main 😕 

```
DataFusion CLI v23.0.0
❯ select  '2023-05-01'::date - interval '1 month';
+----------------------------------------------------------------------------+
| Utf8("2023-05-01") - IntervalMonthDayNano("79228162514264337593543950336") |
+----------------------------------------------------------------------------+
| 2023-04-01                                                                 |
+----------------------------------------------------------------------------+
1 row in set. Query took 0.002 seconds.
```

File: datafusion/core/tests/sqllogictests/test_files/type_coercion.slt [hunk 2]
```diff
@@ -29,3 +29,21 @@ query B
...
 ----
 true
+
+# date - interval
+query D
+select  '2023-05-01'::date - interval '1 month';
+----
+2023-04-01
+
+# date - interval
```
Comment (alamb) [inline datafusion/core/tests/sqllogictests/test_files/type_coercion.slt:39]: this seems identical to the test above it (maybe it was supposed to be `date + interval`?)

Comment (jackwener) [reply datafusion/core/tests/sqllogictests/test_files/type_coercion.slt:39]: I copied twice🥲

**Comment by jackwener** [comment]
I find more problem, make this PR draft

File: datafusion/expr/src/type_coercion/binary.rs [hunk 3]
```diff
@@ -147,16 +150,16 @@ pub fn coerce_types(
...
-            if (is_date(lhs_type)
-                || is_date(rhs_type)
-                || is_timestamp(lhs_type)
-                || is_timestamp(rhs_type)
+            if is_datetime(lhs_type)
+                || is_datetime(rhs_type)
                 || is_interval(lhs_type)
-                || is_interval(rhs_type))
-                && (!is_interval(lhs_type)
-                    || !is_timestamp(rhs_type)
```
Comment (jackwener) [inline datafusion/expr/src/type_coercion/binary.rs:157]: We can't match this condition (interval - date) because it will continue match.

So we should match them, and add judge check.

**Review by alamb — APPROVED** [review]
Thanks @jackwener

**Comment by alamb** [comment]
hmm, the tests seems to be failing now

**Comment by jackwener** [comment]
> hmm, the tests seems to be failing now

Forgot modify a `!=` into `==`.
Have fixed it.

File: datafusion/expr/src/type_coercion/binary.rs [hunk 4]
```diff
@@ -147,16 +150,16 @@ pub fn coerce_types(
...
-                    || *op != Operator::Minus) =>
+                || is_interval(rhs_type) =>
         {
+            if is_interval(lhs_type) && is_datetime(rhs_type) && *op == Operator::Minus {
+                return Err(DataFusionError::Plan(
```
Comment (alamb) [inline datafusion/expr/src/type_coercion/binary.rs:159]: 👍

**Review by alamb — APPROVED** [review]
Thank you @jackwener  -- this is much clearer now
