### PR TITLE
Bugfix: Remove df-cli specific SQL statment options before executing with DataFusion

### LINKED ISSUE #8421: cretae s3 fialed
### Describe the bug

datafusion-cli
❯ CREATE EXTERNAL TABLE test
STORED AS PARQUET
OPTIONS(
    'region' 'xxx',
    'access_key_id' 'xxxx',
    'secret_access_key' 'xxxx'
)
LOCATION 'xxxxx';
Invalid or Unsupported Configuration: Found unsupported option access_key_id with value xxxx for Parquet format!
❯ 

### To Reproduce

datafusion-cli  
```
datafusion-cli
❯ CREATE EXTERNAL TABLE test
STORED AS PARQUET
OPTIONS(
    'region' 'xxx',
    'access_key_id' 'xxxx',
    'secret_access_key' 'xxxx'
)
LOCATION 'xxxxx';
Invalid or Unsupported Configuration: Found unsupported option access_key_id with value xxxx for Parquet format!
❯ 
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devinjdangelo**
## Which issue does this PR close?

Closes #8421

## Rationale for this change

See issue (PR in datafusion caused regression in datafusion-cli when using datafusion-cli specific SQL statement options)

## What changes are included in this PR?

Any arbitrary SQL statement option parsed in datafusion-cli is removed if found before executing the plan.

## Are these changes tested?

Yes, modified existing datafusion-cli unit test to make sure FileTypeWriterOptions::build will not throw an error when passing ObjectStore related datafusion-cli options.

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion-cli/src/object_storage.rs [hunk 1]
```diff
@@ -30,20 +30,21 @@ use url::Url;
...
-    cmd: &CreateExternalTable,
+    cmd: &mut CreateExternalTable,
 ) -> Result<AmazonS3Builder> {
     let bucket_name = get_bucket_name(url)?;
     let mut builder = AmazonS3Builder::from_env().with_bucket_name(bucket_name);
 
     if let (Some(access_key_id), Some(secret_access_key)) = (
-        cmd.options.get("access_key_id"),
-        cmd.options.get("secret_access_key"),
+        cmd.options.remove("access_key_id"),
```
Comment (alamb) [inline datafusion-cli/src/object_storage.rs:39]: This is a very subtle change -- maybe we can add a comment explaining why these options are removed

Likewise below

**Review by alamb — COMMENTED** [review]
I like this approach -- thank you @devinjdangelo

File: datafusion-cli/src/object_storage.rs (hunk 1 above)
Comment (devinjdangelo) [reply datafusion-cli/src/object_storage.rs:41]: Added some comments explaining why the keys are removed/plan made mutable within datafusion-cli.

I also updated one of the unit tests to invoke FileTypeWriterOptions::build to test for this issue in the future.

File: datafusion-cli/src/exec.rs [hunk 2]
```diff
@@ -221,10 +221,12 @@ async fn exec_and_print(
                 | LogicalPlan::Analyze(_)
         );
 
-        if let LogicalPlan::Ddl(DdlStatement::CreateExternalTable(cmd)) = &plan {
+        // Note that cmd is a mutable reference so that create_external_table function can remove all
```
Comment (alamb) [inline datafusion-cli/src/exec.rs:224]: ❤️

File: datafusion-cli/src/object_storage.rs (hunk 1 above)
Comment (alamb) [reply datafusion-cli/src/object_storage.rs:41]: Thank you

**Review by alamb — APPROVED** [review]
Looks great to me -- thank you @devinjdangelo
