### PR TITLE
Fix incorrect results in COUNT(*) queries with LIMIT

### LINKED ISSUE #8048: Incorrect results in COUNT(*) queries involving LIMIT
### Describe the bug

While testing #8038, I ran into some incorrect results cases in LIMIT queries.

### To Reproduce

```sql
❯ CREATE TABLE IF NOT EXISTS t1 (a INT) AS VALUES(1),(2),(3),(4),(5),(6),(7),(8),(9),(10);
0 rows in set. Query took 0.009 seconds.

❯ EXPLAIN
SELECT COUNT(*) FROM (SELECT a FROM t1 WHERE a > 3 LIMIT 3 OFFSET 6);
+---------------+---------------------------------------------------------------+
| plan_type     | plan                                                          |
+---------------+---------------------------------------------------------------+
| logical_plan  | Aggregate: groupBy=[[]], aggr=[[COUNT(UInt8(1)) AS COUNT(*)]] |
|               |   Limit: skip=6, fetch=3                                      |
|               |     Filter: t1.a > Int32(3)                                   |
|               |       TableScan: t1 projection=[a]                            |
| physical_plan | ProjectionExec: expr=[9 as COUNT(*)]                          |
|               |   EmptyExec: produce_one_row=true                             |
|               |                                                               |
+---------------+---------------------------------------------------------------+
2 rows in set. Query took 0.015 seconds.

-- The correct answer is 1.
❯ SELECT COUNT(*) FROM (SELECT a FROM t1 WHERE a > 3 LIMIT 3 OFFSET 6);
+----------+
| COUNT(*) |
+----------+
| 9        |
+----------+

❯ CREATE EXTERNAL TABLE sales(customer_id VARCHAR, revenue BIGINT) STORED AS CSV location '/home/ms/git/arrow-datafusion/datafusion/core/tests/data/customer.csv';
0 rows in set. Query took 0.002 seconds.

-- The correct answer is 1.
❯  SELECT COUNT(*) FROM (SELECT customer_id FROM sales LIMIT 10000000000);
+-------------+
| COUNT(*)    |
+-------------+
| 10000000000 |
+-------------+
1 row in set. Query took 0.009 seconds.

❯ explain  SELECT COUNT(*) FROM (SELECT customer_id FROM sales LIMIT 10000000000);
+---------------+---------------------------------------------------------------+
| plan_type     | plan                                                          |
+---------------+---------------------------------------------------------------+
| logical_plan  | Aggregate: groupBy=[[]], aggr=[[COUNT(UInt8(1)) AS COUNT(*)]] |
|               |   Limit: skip=0, fetch=10000000000                            |
|               |     TableScan: sales projection=[], fetch=10000000000         |
| physical_plan | ProjectionExec: expr=[10000000000 as COUNT(*)]                |
|               |   EmptyExec: produce_one_row=true                             |
|               |                                                               |
+---------------+---------------------------------------------------------------+
2 rows in set. Query took 0.015 seconds.
```

### Expected behavior

Correct results from query execution

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by msirek**
## Which issue does this PR close?

Closes #8048.

## Rationale for this change

While testing #8038, I ran into some incorrect results cases in `COUNT(*)` queries
from a `LIMIT`ed relation, related to [exact statistics](https://github.com/apache/arrow-datafusion/pull/7793).

The issue is due to use of the `fetch` value plus the `skip` value in
stats for `GlobalLimitExec` as the output stats `num_rows`, plus use of `Exact`
statistics for the output in cases where the input has `Inexact` statistics.

#### Fix incorrect results in COUNT(*) queries with LIMIT

This commit reworks the cases in `GlobalLimitExec::statistics` to cap output
stats `num_rows` at the `fetch` value instead of the `fetch+skip` value.

Also, the following cases are modified:

- Output stats are copied from input stats when # of input rows is less than fetch rows, and `skip` is 0
- if (# of input rows - skip) <= fetch, output `num_rows` = input `num_rows` - `skip`
- if input stats are `Inexact` or `Absent`, output stats are `Inexact`
- if (# of input rows - skip) > usize::MAX and `fetch` value is `None`, output stats are `Inexact`

## Are these changes tested?

- [x] unit tests for `GlobalLimitExec` statistics, both `Exact` and `Inexact`.
- [x] sqllogictests for `GlobalLimitExec` statistics

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by msirek** [comment]
@berkaysynnada Does this change look OK to you?

File: datafusion/physical-plan/src/limit.rs [hunk 1]
```diff
@@ -188,21 +188,11 @@ impl ExecutionPlan for GlobalLimitExec {
     fn statistics(&self) -> Result<Statistics> {
```
Comment (berkaysynnada) [inline datafusion/physical-plan/src/limit.rs:188]: Thanks for noticing the error and fixing it. I think the new logic here is quite reasonable.

File: datafusion/physical-plan/src/limit.rs [hunk 2]
```diff
@@ -748,7 +773,58 @@ mod tests {
...
+
+        let row_count =
+            row_number_statistics_for_global_limit(0, Some(usize::MAX)).await?;
+        assert_eq!(row_count, Precision::Exact(400));
+
+        let row_count =
+            row_number_statistics_for_global_limit(398, Some(usize::MAX)).await?;
+        assert_eq!(row_count, Precision::Exact(2));
+
+        let row_count =
```
Comment (alamb) [inline datafusion/physical-plan/src/limit.rs:798]:
```suggestion
        // test inexact input statistics
        let row_count =
```

This threw me for quite a while while trying to figure out why a fetch of 10 resulted in inexact statistics. Now that I see the difference is the input statistics are inexact it makes much more sense

**Review by alamb — APPROVED** [review]
Thank you @msirek and @berkaysynnada  -- I reviewed the tests quite carefully and this looks really nice. Thank you again for the contribution
