### PR TITLE
fix: avro_to_arrow: Handle avro nested nullable struct (union)

### LINKED ISSUE #7662: avro_to_arrow: Nested nullable struct (union)
### Describe the bug

A nullable struct field represented as a Union(Null, Record) in Avro is not currently handled correctly when converting from Avro to Arrow. I have a small fix in a fork I can make a PR.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Samrose-Ahmed**
Corrects handling of a nullable struct union.

## Which issue does this PR close?

Closes #7662.

## Rationale for this change

Bug fix

### CODE REVIEW

**Comment by alamb** [comment]
@Samrose-Ahmed  -- is it possible to add a test to ensure this functionality is not broken in the future?

**Comment by alamb** [comment]
(Thank you for the contribution, BTW)

**Comment by Samrose-Ahmed** [comment]
Of course I can add a test.

**Comment by Samrose-Ahmed** [comment]
I have added a test to verify this behavior.

**Comment by alamb** [comment]
I don't think the CI failures are related to your work

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @Samrose-Ahmed

**Comment by alamb** [comment]
I took the liberty of merging up from main to get the CI to pass cleanly.

**Comment by sarutak** [comment]
@Samrose-Ahmed Thank you for catching this issue! I should have fixed this in #7525 .
@alamb Do we need end-to-end test for this change?

**Comment by alamb** [comment]
> @alamb Do we need end-to-end test for this change?

Hi @sarutak  -- end to end test coverage would definitely be better ❤️  --  I am not familiar enough with the avro spec to know how hard/easy that would be to create. Is it something you can help with?

**Comment by sarutak** [comment]
>  Is it something you can help with?

@alamb 
Of course! I'll update `nested_record.avro` in `arow-testing` to add nullable record schema.

@Samrose-Ahmed 
After I have finished the change, could you add end-to-end test to `avro.slt`?

**Comment by Samrose-Ahmed** [comment]
Sure I can do that

**Comment by sarutak** [comment]
@Samrose-Ahmed Or, do you want to change the test data too?
If you want to do it, [this PR](https://github.com/apache/arrow-testing/pull/91) might help you.

**Comment by Samrose-Ahmed** [comment]
I would appreciate if you can do it.

**Comment by sarutak** [comment]
@Samrose-Ahmed 
OK, let me do it.

**Comment by sarutak** [comment]
I've opened a PR to update the test data.
https://github.com/apache/arrow-testing/pull/94

File: datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs [hunk 1]
```diff
@@ -775,14 +775,20 @@ impl<'a, R: Read> AvroArrowArrayReader<'a, R> {
                         let len = rows.len();
                         let num_bytes = bit_util::ceil(len, 8);
                         let mut null_buffer = MutableBuffer::from_len_zeroed(num_bytes);
+                        let empty_vec = vec![];
                         let struct_rows = rows
                             .iter()
                             .enumerate()
                             .map(|(i, row)| (i, self.field_lookup(field.name(), row)))
                             .map(|(i, v)| {
+                                let v = v.map(maybe_resolve_union);
```
Comment (sarutak) [inline datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs:784]: I think we need to care about array of union of `null` and records as well.

**Comment by alamb** [comment]
https://github.com/apache/arrow-testing/pull/94 is merged

**Comment by Samrose-Ahmed** [comment]
I've updated the PR. 

I've fixed a correctness issue needed for this PR with mapping the Avro and Arrow schema as well, the Avro Record name should not be used in Arrow (the code that was doing `&format!("{}.{}", name.fullname(None), field.name)`, only the field names should be used, the record name is an Avro concept used for schema merging/references. I've added a test for that as well.

**Comment by Samrose-Ahmed** [comment]
Actually this code is a bit weird I found more issues with nested types... will have to fix.

**Comment by alamb** [comment]
>  Actually this code is a bit weird I found more issues with nested types... will have to fix.


It might make sense to get this PR in as it improves things, even if it doesn't fix everything completely. 

Also, note that @tustvold  I think is planning to work on adding upstream support in https://github.com/apache/arrow-rs/issues/4886 arrow-rs (which might automatically handle nested types), though that won't land in datafusion for a week or two

**Comment by Samrose-Ahmed** [comment]
Oh that's great, let me make another revision and see if theirs something improving we can get in.

File: datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs [hunk 2]
```diff
@@ -97,15 +97,15 @@ impl<'a, R: Read> AvroArrowArrayReader<'a, R> {
...
         match schema {
-            AvroSchema::Record(RecordSchema {
-                name,
-                fields,
-                lookup,
-                ..
-            }) => {
+            AvroSchema::Union(union_schema) => {
+                if union_schema.is_nullable() {
+                    let rec_schema = &union_schema.variants()[1];
```
Comment (sarutak) [inline datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs:102]: This part seems incorrect. The second variants is not always non-null, but the first one can be.

Comment (sarutak) [reply datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs:102]: Also, it's better to check if the number of variants is 2 because this logic only consider nullable types, not general union types which contains 3 or more variants.

**Comment by Samrose-Ahmed** [comment]
I have made another revision, I had to edit some of the schema lookup logic to handle nested fields, didn't want to change the code too much.

File: datafusion/core/Cargo.toml [hunk 3]
```diff
@@ -109,6 +109,8 @@ rand_distr = "0.4.3"
 regex = "1.5.4"
 rstest = "0.18.0"
 rust_decimal = { version = "1.27.0", features = ["tokio-pg"] }
+serde = "1"
```
Comment (sarutak) [inline datafusion/core/Cargo.toml:112]: I think `serde` is not necessary.

**Review by sarutak — COMMENTED** [review]
This change looks good to me except one minor comment!

**Comment by sarutak** [comment]
Oh, wait. Clippy raises some warnings.
```
error: this expression creates a reference which is immediately dereferenced by the compiler
   --> datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs:115:29
    |
115 | ...                   &parent_field_name,
    |                       ^^^^^^^^^^^^^^^^^^ help: change this to: `parent_field_name`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
    = note: `-D clippy::needless-borrow` implied by `-D warnings`

error: redundant closure
   --> datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs:595:38
    |
595 | ...                   .map(|v| maybe_resolve_union(v))
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace the closure with the function itself: `maybe_resolve_union`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure
    = note: `-D clippy::redundant-closure` implied by `-D warnings`

error: could not compile `datafusion` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: the borrowed expression implements the required traits
    --> datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs:1189:40
     |
1189 |           let r1 = apache_avro::to_value(&serde_json::json!({
     |  ________________________________________^
1190 | |             "headers": [
1191 | |                 {
1192 | |                     "name": "a",
...    |
1195 | |             ]
1196 | |         }))
     | |__________^
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
help: change this to
     |
1189 ~         let r1 = apache_avro::to_value(serde_json::json!({
1190 +             "headers": [
1191 +                 {
1192 +                     "name": "a",
1193 +                     "value": "b"
1194 +                 }
1195 +             ]
1196 ~         }))
     |

error: the borrowed expression implements the required traits
    --> datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs:1407:40
     |
1407 |         let r1 = apache_avro::to_value(&jv1)
     |                                        ^^^^ help: change this to: `jv1`
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: could not compile `datafusion` (lib test) due to 4 previous errors
```

@Samrose-Ahmed  Could you fix them? Also you can check the style locally by running `ci/scripts/rust_clippy.sh` and `ci/scripts/rust_fmt.sh`.

**Comment by sarutak** [comment]
@alamb Could you trigger GA workflows?

**Review by alamb — APPROVED** [review]
Thanks @Samrose-Ahmed  and @sarutak 

BTW @tustvold is working on porting / implementing this upstream: https://github.com/apache/arrow-rs/pull/4888

**Comment by sarutak** [comment]
@alamb Thank you for letting me know. I'll check it out.

**Comment by alamb** [comment]
In the interim, I think this PR makes DataFusion demonstrably better, and increases test coverage so I think we should merge it in. Thanks again everyone who was involved

**Comment by sarutak** [comment]
@alamb 
BTW, will this project still open for changes related to Avro?
Actually, I'm working on a type conversion feature currently marked as `todo!()`.

**Comment by alamb** [comment]
> BTW, will this project still open for changes related to Avro?
> Actually, I'm working on a type conversion feature currently marked as todo!().

Absolutely -- I view what @tustvold  is doing as complementary (even if somewhat duplicative). I would expect that DataFusion will continue to support avro for reading / processing, and that all end to end tests (e.g. `slt` tests) would pass without modification, even if the internals of how avro reading / processing move upstream

Does that make sense @sarutak ?

**Comment by sarutak** [comment]
@alamb 
I understand. Thank you!
