### PR TITLE
fix: Enhance case expression type coercion

### LINKED ISSUE #5538: Cannot compare two arrays of different types is thrown on a simple two-statement query comparing floats and ints
**Problem Statement**

This statement works:
```
select CASE 10.5 WHEN 0 THEN null ELSE 10 END as col;
```

This list of two statements don't:

```
create table res as 
   select CASE 10.5 WHEN 0 THEN null ELSE 10 END as col;

select * from res
```

And produce the following error:
```sql
Arrow error: Cast error: Cannot compare two arrays of different types (Int64 and Float64)
```

**To Reproduce**
Place the above statements into any of the .sql files in datafusion/core/tests/tpc-ds/ (e.g. 1.sql). Run the corresponding test (e.g. tpcds_logical_q1. 

**Expected behavior**
According to SQL semantics any coercion and comparison between numeric types (including Float and Int) should work. Hence expected behavior is for the statement(s) above to succeed.

**Additional context**
This example is a variation of the TPC-DS query 39. It currently passes, but if you stick "create table xxx as " on the first line, it will exhibit the same error.

We hit this in SDF because we tend to generate multi-statement queries in which all dependent tables are explicitly "create"-d in a statement.

Note: I tried this in the current main, and in this branch https://github.com/apache/arrow-datafusion/pull/5343, hoping that the latter might be addressing related concerns. Both result in the same behavior.

### LINKED ISSUE #5828: case when expressions that aren't boolean data type cause panic
### Describe the bug

Given case expression in following form:

```sql
CASE
  WHEN x1 THEN y1
  WHEN x2 THEN y2
  ELSE y3
END
```

Then all `xN` (`x1`, `x2`) should be boolean expressions and should be coerced to a boolean type if not, otherwise throw an error without causing a panic.

### To Reproduce

On latest main:

```bash
jeffrey:~/Code/arrow-datafusion/datafusion-cli$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `/media/jeffrey/1tb_860evo_ssd/.cargo_target_cache/debug/datafusion-cli`
DataFusion CLI v21.0.0
❯ select CASE WHEN 1 THEN null ELSE 10 END as col;
thread 'main' panicked at 'WHEN expression did not return a BooleanArray: Internal("could not cast value to arrow_array::array::boolean_array::BooleanArray")', /home/jeffrey/Code/arrow-datafusion/datafusion/physical-expr/src/expressions/case.rs:199:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
jeffrey:~/Code/arrow-datafusion/datafusion-cli$
```

### Expected behavior

Should either succeed, or throw error without panic

### Additional context

Will be fixed in https://github.com/apache/arrow-datafusion/pull/5820

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #5538

Closes #5828

# Rationale for this change

Given following:

```sql
SELECT
  CASE a
    WHEN b THEN 0
    WHEN c THEN 1
    ELSE 2
  END;
```

Should attempt to coerce `a`, `b` and `c` to common type.

And for:

```sql
SELECT
  CASE
    WHEN a THEN 0
    WHEN b THEN 1
    ELSE 2
  END;
```

Should coerce `a` and `b` to boolean type.

# What changes are included in this PR?

Ensure `case` and `when` expressions are coerced to common type, similar to how currently `then` and `else` expressions are coerced to common type.

Also ensure `when` expressions for when `case` expression isn't provided to coerce to boolean type.

# Are these changes tested?

Added to sqllogictest

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/optimizer/src/type_coercion.rs [hunk 1]
```diff
@@ -330,8 +330,35 @@ impl TreeNodeRewriter for TypeCoercionRewriter {
...
+                //
+                // or:
+                //
+                // CASE
+                //   WHEN x1 THEN b1
+                //   WHEN x2 THEN b2
+                //   ELSE b3
+                // END
+                //
+                // Then all aN (a1, a2, a3) must be converted to a common data type in the first example
```
Comment (alamb) [inline datafusion/optimizer/src/type_coercion.rs:349]: ❤️

File: datafusion/optimizer/src/type_coercion.rs [hunk 2]
```diff
@@ -330,8 +330,35 @@ impl TreeNodeRewriter for TypeCoercionRewriter {
...
+                // And all bN (b1, b2, b3) must be converted to a common data type in both examples
+                // (then-else expression coercion)
+                //
+                // If either fail to find a common data type, will return error
+
+                // prepare types
+                let case_type = match &case.expr {
+                    None => Ok(None),
+                    Some(expr) => expr.get_type(&self.schema).map(Some),
+                }?;
```
Comment (alamb) [inline datafusion/optimizer/src/type_coercion.rs:361]: You can write this more concisely / functionally using `transpose` like this if you want

```suggestion
                // prepare types
                let case_type = case.expr.as_ref()
                    .map(|expr| expr.get_type(&self.schema))
                    .transpose()?;
```

The same basic transformation applies to the other `match` statements below -- I don't think it is a big deal I just figured I would point it out to you

File: datafusion/core/tests/sqllogictests/test_files/select.slt [hunk 3]
```diff
@@ -214,3 +214,9 @@ select * from (select 1 a union all select 2) b order by a limit null;
 query I
 select * from (select 1 a union all select 2) b order by a limit 0;
 ----
+
+# select case when type coercion
+query I
+select CASE 10.5 WHEN 0 THEN 1 ELSE 10 END as col;
+----
+10
```
Comment (alamb) [inline datafusion/core/tests/sqllogictests/test_files/select.slt:222]: Could you add some additional tests?

1. Alternate Syntax:
```
select CASE 
  WHEN 10 = 5 THEN 1 
  WHEN 'true' THEN 1 
  ELSE 10 
END as col;
```


Also negative cases like

```sql
select CASE 10.5 WHEN 'not a number' THEN 1 ELSE 10 END as col;
```

```sql
select CASE 
  WHEN 10 = 5 THEN 1 
  WHEN 'not boolean' THEN 1 
  ELSE 10 
END as col;
```

```sql
select CASE 
  WHEN 10 = 5 THEN 1 
  WHEN 5 THEN 'not a number'
  ELSE 10 
END as col;
```

```sql
select CASE 
  WHEN 10 = 5 THEN 1 
  WHEN 5 THEN 0
  ELSE 'goo' 
END as col;
```

**Review by alamb — COMMENTED** [review]
Thank you @Jefffrey  -- the code looks good to me

Prior to merge I think some additional tests are needed in this PR. 

I also left some small code style suggestions, but I don't think they are required.

File: datafusion/core/tests/sqllogictests/test_files/select.slt (hunk 3 above)
Comment (Jefffrey) [reply datafusion/core/tests/sqllogictests/test_files/select.slt:222]: Is there a way in sqllogictests to change the config of DataFusion? Since for negative cases to produce error, would need to set `datafusion.optimizer.skip_failed_rules` to false, unless you mean for the negative case to fail as in the original issue?

Otherwise can add the negative case as a unit test in actual code

File: datafusion/optimizer/src/type_coercion.rs (hunk 2 above)
Comment (Jefffrey) [reply datafusion/optimizer/src/type_coercion.rs:361]: Thanks that does look cleaner, will apply it

**Comment by Jefffrey** [comment]
I've found another bug related to case expression casting, will raise issue and also fix as part of this PR since will be affecting similar code

File: datafusion/core/tests/sqllogictests/test_files/select.slt (hunk 3 above)
Comment (alamb) [reply datafusion/core/tests/sqllogictests/test_files/select.slt]: Yes, you can use the `SET` command to change config values. For example https://github.com/apache/arrow-datafusion/blob/7b90474adf6c1afbb4a5988a5677834b07347321/datafusion/core/tests/sqllogictests/test_files/information_schema.slt#L30

File: datafusion/physical-expr/src/expressions/case.rs [hunk 4]
```diff
@@ -195,8 +195,12 @@ impl CaseExpr {
                 _ => when_value,
             };
             let when_value = when_value.into_array(batch.num_rows());
-            let when_value = as_boolean_array(&when_value)
-                .expect("WHEN expression did not return a BooleanArray");
+            let when_value = as_boolean_array(&when_value).map_err(|e| {
+                DataFusionError::Context(
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:199]: 🤔

**Review by alamb — COMMENTED** [review]
I just think we need a few more tests and this PR will be ready to go

File: datafusion/core/tests/sqllogictests/test_files/select.slt (hunk 3 above)
Comment (Jefffrey) [reply datafusion/core/tests/sqllogictests/test_files/select.slt]: Testing with sqllogictests turned out to be kinda finicky, as this PR is meant to enhance the type coercion, but not actually testing the actual casting itself (since some of those negative cases would pass the type coercion but fail at execution time due to actual contents of the data). So I figured it'd be easier to add more tests as unit tests for proper testing.

File: datafusion/physical-expr/src/expressions/case.rs (hunk 4 above)
Comment (Jefffrey) [reply datafusion/physical-expr/src/expressions/case.rs:199]: Yeah figured better to wrap in Context to hopefully provide more informative error message
