### PR TITLE
Fix avro tests (#2570)

### LINKED ISSUE #2570: Avro Tests Fail To Compile
**Describe the bug**

Currently the avro test suite fails to compile

**To Reproduce**

```
cargo test --package datafusion --features avro
```

**Expected behavior**

It should compile and this should be being verified by CI

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2570

 # Rationale for this change

See ticket

# What changes are included in this PR?

* Fix compilation of tests
* Fix a mistake in avro -> arrow conversion that was being caught by the new arrow-rs validation logic :tada:
* Adds avro feature to CI

# Are there any user-facing changes?

The previous logic was likely broken for lists

### CODE REVIEW

File: datafusion/core/src/avro_to_arrow/arrow_array_reader.rs [hunk 1]
```diff
@@ -861,6 +861,7 @@ fn flatten_string_values(values: &[&Value]) -> Vec<Option<String>> {
     values
         .iter()
         .flat_map(|row| {
+            let row = maybe_resolve_union(row);
```
Comment (tustvold) [inline datafusion/core/src/avro_to_arrow/arrow_array_reader.rs:864]: We must do this here, to match the logic used to deduce the offsets. Without this the offsets would not match the flattened values.

**Review by alamb — APPROVED** [review]
Thanks @tustvold  -- I thought these were tested, but it looks like just the example is:

https://github.com/alamb/arrow-datafusion/blob/alamb%2Fmerge_benchmark/.github/workflows/rust.yml#L123

So while that is better than nothing, testing via `cargo test --features avro` is even better

cc @Igosuki
