### PR TITLE
fix: cast literal to timestamp

### LINKED ISSUE #5507: `try_cast_literal_to_type` doesn't respect timestamp precision
**Describe the bug**

In the function `try_cast_literal_to_type`: https://github.com/apache/arrow-datafusion/blob/928662bb12d915aef83abba1312392d25770f68f/datafusion/optimizer/src/unwrap_cast_in_comparison.rs#L295

Converting from `Timestamp(Nanosecond, _)` to `Timestamp(Microsecond, _)` doesn't actually return the correct value. It simply interchanges the inner integer.

**To Reproduce**

Running the following:

```rs
#[test]
fn test_repro() {
    let new_scalar = try_cast_literal_to_type(
        &ScalarValue::TimestampNanosecond(Some(123456), None),
        &DataType::Timestamp(TimeUnit::Microsecond, None)
    ).unwrap().unwrap();

    // This passes which is wrong
    assert_eq!(new_scalar, ScalarValue::TimestampMicrosecond(Some(123456), None));

    // This fails!
    // assert_eq!(new_scalar, ScalarValue::TimestampMicrosecond(Some(123), None));
}
```

**Expected behavior**

```rs
// This should be the correct result
assert_eq!(new_scalar, ScalarValue::TimestampMicrosecond(Some(123), None));
```

**Additional context**

### PR DESCRIPTION
**Pull request by Weijun-H**
# Which issue does this PR close?

Closes #5507

# Rationale for this change
When converting between different timestamps, reduce the precision by truncating excess digits.

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/optimizer/src/unwrap_cast_in_comparison.rs [hunk 1]
```diff
@@ -1070,4 +1119,19 @@ mod tests {
             }
         }
     }
+
+    #[test]
+    fn test_try_cast_literal_to_timestamp() {
```
Comment (comphead) [inline datafusion/optimizer/src/unwrap_cast_in_comparison.rs:1124]: please add more tests between timestamps

File: datafusion/optimizer/src/unwrap_cast_in_comparison.rs [hunk 2]
```diff
@@ -428,6 +452,31 @@ fn try_cast_literal_to_type(
     }
 }
 
+/// Cast a timestamp value from one unit to another
+fn cast_between_timestamp(from: DataType, to: DataType, value: i128) -> Option<i64> {
+    let seconds = match from {
```
Comment (comphead) [inline datafusion/optimizer/src/unwrap_cast_in_comparison.rs:457]: I think it can be improved. if the cast Second to Second, then the code will do unneccessary mul by 1m and then div  by 1m

**Review by comphead — COMMENTED** [review]
Thanks @Weijun-H for the contribution, please check some minor comments

File: datafusion/optimizer/src/unwrap_cast_in_comparison.rs [hunk 3]
```diff
@@ -1070,4 +1118,162 @@ mod tests {
...
+        );
+
+        // overflow
+        let new_scalar = try_cast_literal_to_type(
+            &ScalarValue::TimestampSecond(Some(i64::MAX), None),
+            &DataType::Timestamp(TimeUnit::Millisecond, None),
+        )
+        .unwrap()
+        .unwrap();
+        assert_eq!(new_scalar, ScalarValue::TimestampMillisecond(None, None));
```
Comment (alamb) [inline datafusion/optimizer/src/unwrap_cast_in_comparison.rs:1277]: 👍

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @Weijun-H
