### PR TITLE
fix: failed to create ValuesExec with non-nullable schema

### LINKED ISSUE #8763: Cannot insert with DMLStatement into a table with non-nullable fields
### Describe the bug

When a table is created with a non-nullable `Field`, executing a `DMLStatement` logical plan to write to that table always fails with the error `Column [name] is declared as non-nullable but contains null values`. This happens no matter what values I try to insert.

### To Reproduce

The following snippet creates a table called `t1` with a non-nullable int32 `Field` called `a`. When we try to add an integer into this table, it errors.

```rust
use async_std::task;
use datafusion::arrow::datatypes::{DataType, Field, Schema};
use datafusion::arrow::record_batch::RecordBatch;
use datafusion::common::{DFSchema, ScalarValue};
use datafusion::datasource::MemTable;
use datafusion::logical_expr::{DmlStatement, Expr, LogicalPlan, Values};
use datafusion::logical_expr::WriteOp::InsertInto;
use datafusion::prelude::SessionContext;
use std::sync::Arc;

fn main() {
    let table_name = "t1";
    let field = Field::new("a", DataType::Int32, false);

    let ctx = SessionContext::new();
    let schema = Schema::new(vec![field]);
    let df_schema = DFSchema::try_from(schema.clone()).unwrap();

    match MemTable::try_new(schema.clone().into(), vec![Vec::<RecordBatch>::new()]).ok() {
        Some(mem_table) => {
            let _ = ctx.register_table(table_name.clone(), Arc::new(mem_table));
        }
        None => panic!("An unexpected error occured creating the table"),
    };

    let values = vec![vec![Expr::Literal(ScalarValue::Int32(Some(1)))]];

    let values_plan = LogicalPlan::Values(Values {
        schema: df_schema.clone().into(),
        values: values.clone(),
    });

    let dml_plan = LogicalPlan::Dml(DmlStatement {
        table_name: table_name.into(),
        table_schema: df_schema.clone().into(),
        op: InsertInto,
        input: values_plan.into(),
    });

    // This step always errors out
    // Error:
    // ArrowError(InvalidArgumentError("Column 'a' is declared as non-nullable but        
    // contains null values"))'
    let dataframe = task::block_on(ctx.execute_logical_plan(dml_plan.clone()))
        .expect("Could not execute plan");
    let _ = task::block_on(dataframe.collect()).expect("Could not collect dataframe");

    println!("Success!");
}
```

### Expected behavior

We would expect this insert to succeed, as the values we are inserting are not null.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?
Closes #8763.

## Rationale for this change
In `ValuesExec::try_new`, we use the schema of `ValuesExec` and **null arrays** to construct a placeholder batch. 
https://github.com/apache/arrow-datafusion/blob/dd4263f843e093c807d63edf73a571b1ba2669b5/datafusion/physical-plan/src/values.rs#L56-L64
This batch placeholder is used to evaluate the physical expressions in Values.

But users can define a schema containing non-nullable fields for `ValuesExec` just like issue #8763, which is in conflict with null arrays.
```rust
let field = Field::new("a", DataType::Int32, false);
let schema = Schema::new(vec![field]);
let df_schema = DFSchema::try_from(schema.clone()).unwrap();
let values = vec![vec![Expr::Literal(ScalarValue::Int32(Some(1)))]];
let values_plan = LogicalPlan::Values(Values {
        schema: df_schema.clone().into(),
        values: values.clone(),
})
```
In this case, an ArrowError ‘InvalidArgumentError("Column 'a' is declared as non-nullable but contains null values"))' will be raised.

Since `ValuesExec` has no input, I think the schema for this placeholder batch can be empty, rather than using the schema from `ValuesExec`.

## What changes are included in this PR?
Use correct schema to build the placeholder batch in `ValuesExec::try_new`.

## Are these changes tested?
Yes

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/physical-plan/src/values.rs [hunk 1]
```diff
@@ -71,7 +69,7 @@ impl ValuesExec {
                         match r {
                             Ok(ColumnarValue::Scalar(scalar)) => Ok(scalar),
                             Ok(ColumnarValue::Array(a)) if a.len() == 1 => {
-                                Ok(ScalarValue::List(a))
+                                ScalarValue::try_from_array(&a, 0)
```
Comment (jonahgao) [inline datafusion/physical-plan/src/values.rs:72]: Returning `ScalarValue::List(a)` makes the following query fail.
```sh
DataFusion CLI v34.0.0
❯ select * from (values(random()));
Internal error: Inconsistent types in ScalarValue::iter_to_array. Expected Float64, got List(0.5174512019067328).
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```
Related to pr #7629. I think it's a bug, so I fixed it.

File: datafusion/sqllogictest/test_files/select.slt [hunk 2]
```diff
@@ -114,6 +114,14 @@ VALUES (1,2,3,4,5,6,7,8,9,10,11,12,13,NULL,'F',3.5)
 ----
 1 2 3 4 5 6 7 8 9 10 11 12 13 NULL F 3.5
 
+# Test non-literal expressions in VALUES
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/select.slt:117]: 👍

File: datafusion/physical-plan/src/values.rs [hunk 3]
```diff
@@ -53,15 +52,14 @@ impl ValuesExec {
...
         let n_col = schema.fields().len();
-        // we have this single row, null, typed batch as a placeholder to satisfy evaluation argument
-        let batch = RecordBatch::try_new(
-            schema.clone(),
-            schema
-                .fields()
-                .iter()
-                .map(|field| new_null_array(field.data_type(), 1))
-                .collect::<Vec<_>>(),
+        // we have this single row batch as a placeholder to satisfy evaluation argument
```
Comment (alamb) [inline datafusion/physical-plan/src/values.rs:55]: 👍  this code to use a null array probably pre-dates the ability to create zero column record batches

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @jonahgao

**Comment by alamb** [comment]
Also thank you for:
1. The very clear PR description
2. The drive by cleanups to comments
3. The fix of the other bug you found (and the clear comments and tests) 🙏 

Very much appreciated

**Comment by jonahgao** [comment]
Thank you for reviewing  @alamb .
