### PR TITLE
fix: disallow interval - timestamp

### LINKED ISSUE #7084: Interval - Timestamp should error, but succeeds
### Describe the bug

Trying to compute Interval - Timestamp should raise an error, as it does not make any semantic sense

### To Reproduce

This is from timestamp.slt

```sql
create table foo (val int, ts1 timestamp, ts2 timestamp, i interval) as values
(1, '2023-03-15T15:00:20.000000123'::timestamp, '2023-01-20T23:00:00.000000099'::timestamp, '1 day'::interval),
(2, '2023-02-28T12:01:55.000123456'::timestamp, '2000-02-23T11:00:00.123000001'::timestamp, '2 months'::interval),
(3, '2033-11-02T23:22:13.000123456'::timestamp, '1990-03-01T00:00:00.333000001'::timestamp, '1 day 3 hours'::interval),
(4, '2003-07-11T01:31:15.000123456'::timestamp, '2045-04-11T15:00:00.000000001'::timestamp, '1 day 7 nanoseconds'::interval);

SELECT i - ts1 from FOO;
----
2023-03-14T15:00:20.000000123
2022-12-28T12:01:55.000123456
2033-11-01T20:22:13.000123456
2003-07-10T01:31:15.000123449

```

### Expected behavior

```
SELECT i - ts1 from FOO;
```

Should raise an error about unsupported operation

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #7085 
Closes #7084.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

Yes

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/expr/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -169,19 +169,22 @@ fn signature(lhs: &DataType, op: &Operator, rhs: &DataType) -> Result<Signature>
...
 
     match (lhs_type, rhs_type) {
         // datetime +/- interval
-        (Interval(_), Timestamp(_, _)) => Some(rhs_type.clone()),
-        (Timestamp(_, _), Interval(_)) => Some(lhs_type.clone()),
-        (Interval(_), Date32) => Some(rhs_type.clone()),
-        (Date32, Interval(_)) => Some(lhs_type.clone()),
-        (Interval(_), Date64) => Some(rhs_type.clone()),
-        (Date64, Interval(_)) => Some(lhs_type.clone()),
+        (Timestamp(_, _) | Date32 | Date64, Interval(_)) => Some(lhs_type.clone()),
```
Comment (alamb) [inline datafusion/expr/src/type_coercion/binary.rs:180]: I didn't realize it was possible to do a match on a subfield of a tuple. TIL 🤯

**Review by alamb — APPROVED** [review]
Thank you @jackwener  -- this looks perfect to me

cc @tustvold

**Review by ozankabak — APPROVED** [review]
LGTM as well, thank you!

**Review by Dandandan — APPROVED** [review]
