### PR TITLE
Fix update_expr for projection pushdown

### LINKED ISSUE #9091: Regression: incorrect order on a joined table column (without selecting its fields)
### Describe the bug

I observe that the query result is not sorted correctly. And it worked before (datafusion 31.0.0 at least)

### To Reproduce

```sql
CREATE TABLE companies(name VARCHAR, employees INT) AS VALUES ('Jeyork', 150),('Shalk', 350),('ShuttlP', 75);
CREATE TABLE leads(name VARCHAR, company VARCHAR) AS VALUES ('Alex F', 'Jeyork'),('John B', 'Shalk'),('Samanta J', 'ShuttlP'),('Trevor R', 'Jeyork'),('Alice B', 'ShuttlP');

SELECT l.* FROM leads l LEFT JOIN companies c ON c."name" = l."company" ORDER BY c."name", l."name";
+-----------+---------+
| name      | company |
+-----------+---------+
| Alex F    | Jeyork  |
| Alice B   | ShuttlP |
| John B    | Shalk   |
| Samanta J | ShuttlP |
| Trevor R  | Jeyork  |
+-----------+---------+
5 rows in set. Query took 0.002 seconds.


```
<details>
<summary>EXPLAIN</summary>

```
+---------------+-------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                |
+---------------+-------------------------------------------------------------------------------------+
| logical_plan  | Projection: l.name, l.company                                                       |
|               |   Sort: c.name ASC NULLS LAST, l.name ASC NULLS LAST                                |
|               |     Left Join: l.company = c.name                                                   |
|               |       SubqueryAlias: l                                                              |
|               |         TableScan: leads projection=[name, company]                                 |
|               |       SubqueryAlias: c                                                              |
|               |         TableScan: companies projection=[name]                                      |
| physical_plan | SortPreservingMergeExec: [name@0 ASC NULLS LAST,name@0 ASC NULLS LAST]              |
|               |   SortExec: expr=[name@0 ASC NULLS LAST,name@0 ASC NULLS LAST]                      |
|               |     ProjectionExec: expr=[name@1 as name, company@2 as company]                     |
|               |       CoalesceBatchesExec: target_batch_size=8192                                   |
|               |         HashJoinExec: mode=Partitioned, join_type=Right, on=[(name@0, company@1)]   |
|               |           CoalesceBatchesExec: target_batch_size=8192                               |
|               |             RepartitionExec: partitioning=Hash([name@0], 10), input_partitions=1    |
|               |               MemoryExec: partitions=1, partition_sizes=[1]                         |
|               |           CoalesceBatchesExec: target_batch_size=8192                               |
|               |             RepartitionExec: partitioning=Hash([company@1], 10), input_partitions=1 |
|               |               MemoryExec: partitions=1, partition_sizes=[1]                         |
|               |                                                                                     |
+---------------+-------------------------------------------------------------------------------------+
2 rows in set. Query took 0.009 seconds.

```
</details>

It should be sorted by `name` of table `company`, but we can see it's mixed.

Interesting behavior is that **if I add `c.name` to the query, it will be sorted correctly!**

```sql
SELECT l.*, c.name FROM leads l LEFT JOIN companies c ON c."name" = l."company" ORDER BY c."name", l."name";
+-----------+---------+---------+
| name      | company | name    |
+-----------+---------+---------+
| Alex F    | Jeyork  | Jeyork  |
| Trevor R  | Jeyork  | Jeyork  |
| John B    | Shalk   | Shalk   |
| Alice B   | ShuttlP | ShuttlP |
| Samanta J | ShuttlP | ShuttlP |
+-----------+---------+---------+
5 rows in set. Query took 0.002 seconds.
```

<details>
<summary>EXPLAIN</summary>

```
+---------------+-------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                |
+---------------+-------------------------------------------------------------------------------------+
| logical_plan  | Sort: c.name ASC NULLS LAST, l.name ASC NULLS LAST                                  |
|               |   Left Join: l.company = c.name                                                     |
|               |     SubqueryAlias: l                                                                |
|               |       TableScan: leads projection=[name, company]                                   |
|               |     SubqueryAlias: c                                                                |
|               |       TableScan: companies projection=[name]                                        |
| physical_plan | SortPreservingMergeExec: [name@2 ASC NULLS LAST,name@0 ASC NULLS LAST]              |
|               |   SortExec: expr=[name@2 ASC NULLS LAST,name@0 ASC NULLS LAST]                      |
|               |     ProjectionExec: expr=[name@1 as name, company@2 as company, name@0 as name]     |
|               |       CoalesceBatchesExec: target_batch_size=8192                                   |
|               |         HashJoinExec: mode=Partitioned, join_type=Right, on=[(name@0, company@1)]   |
|               |           CoalesceBatchesExec: target_batch_size=8192                               |
|               |             RepartitionExec: partitioning=Hash([name@0], 10), input_partitions=1    |
|               |               MemoryExec: partitions=1, partition_sizes=[1]                         |
|               |           CoalesceBatchesExec: target_batch_size=8192                               |
|               |             RepartitionExec: partitioning=Hash([company@1], 10), input_partitions=1 |
|               |               MemoryExec: partitions=1, partition_sizes=[1]                         |
|               |                                                                                     |
+---------------+-------------------------------------------------------------------------------------+
2 rows in set. Query took 0.002 seconds.
```
</details>

### Expected behavior

Order should be correct, regardless of selected fields

### Additional context

Probably should be a part of #8398

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #9091.

## Rationale for this change

`projection_pushdown` rule uses function `update_expr` to check if a plan's expressions could be updated with projection expressions. The function only checks column name so if there are columns with same name, the check will return incorrect `RewrittenValid` state. Column index should be checked too in the function `update_expr`.

### CODE REVIEW

File: datafusion/core/src/physical_optimizer/projection_pushdown.rs [hunk 1]
```diff
@@ -916,7 +916,9 @@ fn update_expr(
                     .find_map(|(index, (projected_expr, alias))| {
                         projected_expr.as_any().downcast_ref::<Column>().and_then(
                             |projected_column| {
-                                column.name().eq(projected_column.name()).then(|| {
+                                (column.name().eq(projected_column.name())
```
Comment (alamb) [inline datafusion/core/src/physical_optimizer/projection_pushdown.rs:919]: There is another similar check a bit further down in the file in `new_columns_for_join_on`

https://github.com/apache/arrow-datafusion/blob/c9049eda85683d958a39eca5fd3a382943ee7fa6/datafusion/core/src/physical_optimizer/projection_pushdown.rs#L1046

Likewise in new_indices_for_join_filter

https://github.com/apache/arrow-datafusion/blob/c9049eda85683d958a39eca5fd3a382943ee7fa6/datafusion/core/src/physical_optimizer/projection_pushdown.rs#L1132

I wonder if those checks need to extended to check the index as well? Maybe we could extract the "find matching projection column" logic as a function 🤔

**Review by alamb — APPROVED** [review]
Thank you very much @viirya  -- super sluthing 🕵️ 


FYI @DDtKey

File: datafusion/sqllogictest/test_files/join.slt [hunk 2]
```diff
@@ -614,8 +614,8 @@ query TI
 SELECT t1.a, t1.b FROM t1 JOIN t2 ON t1.a = t2.a ORDER BY t1.a, t2.b;
 ----
 Alice 50
-Alice 50
 Alice 100
+Alice 50
```
Comment (DDtKey) [inline datafusion/sqllogictest/test_files/join.slt:618]: Seems that after this PR the results matches expected ones, in comment above.
Should we update the comment? 

> the current query results **are incorrect**, becuase the query was incorrectly rewritten as:

Comment (DDtKey) [reply datafusion/sqllogictest/test_files/join.slt:618]: Probably we should have both test-cases (just in case):

- `SELECT t1.a, t1.b FROM t1 JOIN t2 ON t1.a = t2.a ORDER BY t1.a, t1.b;`
```
Alice 	50
Alice 	50
Alice 	100
Alice 	100
```

- `SELECT t1.a, t1.b FROM t1 JOIN t2 ON t1.a = t2.a ORDER BY t1.a, t2.b;`
```
Alice 	50
Alice 	100
Alice 	50
Alice 	100
```

**Comment by DDtKey** [comment]
@viirya huge thanks for such a reactive response to the issue! 🚀

File: datafusion/core/src/physical_optimizer/projection_pushdown.rs (hunk 1 above)
Comment (berkaysynnada) [reply datafusion/core/src/physical_optimizer/projection_pushdown.rs:919]: I am working on a new, more comprehensive and less error-prone projection optimizer. I plan to open a PR after our internal review. Just so you know, all these utils will be removed in the new version.

File: datafusion/core/src/physical_optimizer/projection_pushdown.rs [hunk 3]
```diff
@@ -1407,29 +1409,29 @@ mod tests {
...
                 ],
                 Some(Arc::new(BinaryExpr::new(
-                    Arc::new(Column::new("a", 3)),
+                    Arc::new(Column::new("a", 0)),
                     Operator::Modulo,
-                    Arc::new(Column::new("e", 5)),
+                    Arc::new(Column::new("e", 4)),
                 ))),
             )?),
         ];
```
Comment (berkaysynnada) [inline datafusion/core/src/physical_optimizer/projection_pushdown.rs:1437]: Rather than changing this test like that, 
```suggestion
            let projected_exprs: Vec<(Arc<dyn PhysicalExpr>, String)> = vec![
            (Arc::new(Column::new("a", 3)), "a".to_owned()),
            (Arc::new(Column::new("b", 1)), "b_new".to_owned()),
            (Arc::new(Column::new("c", 0)), "c".to_owned()),
            (Arc::new(Column::new("d", 2)), "d_new".to_owned()),
            (Arc::new(Column::new("e", 5)), "e".to_owned()),
            (Arc::new(Column::new("f", 4)), "f_new".to_owned()),
        ];

```
these changes will be simpler and greater coverage

File: datafusion/sqllogictest/test_files/join.slt (hunk 2 above)
Comment (viirya) [reply datafusion/sqllogictest/test_files/join.slt:619]: Nice catch. Yea, this existing test now matches correct behaviors after this PR. Actually it is same issue (order by with same column name in joined sides).

Updated the test case.

File: datafusion/core/src/physical_optimizer/projection_pushdown.rs (hunk 3 above)
Comment (viirya) [reply datafusion/core/src/physical_optimizer/projection_pushdown.rs:1437]: Yea, updated.

File: datafusion/core/src/physical_optimizer/projection_pushdown.rs (hunk 1 above)
Comment (viirya) [reply datafusion/core/src/physical_optimizer/projection_pushdown.rs:919]: If so, then I don't touch other places like `new_columns_for_join_on`, but only address the reported issue.

Comment (viirya) [reply datafusion/core/src/physical_optimizer/projection_pushdown.rs:919]: ditto for `new_indices_for_join_filter`.

Comment (alamb) [reply datafusion/core/src/physical_optimizer/projection_pushdown.rs:919]: If another rewrite is imminent, it is all the more important that we thoroughly test for this behavior

File: datafusion/sqllogictest/test_files/join.slt (hunk 2 above)
Comment (alamb) [reply datafusion/sqllogictest/test_files/join.slt:619]: > It seems it would be useful to have a set of tests that can fail, but do not block CI, etc (something like TDD, we know it fails and we can make it work)

I agree this would be useful -- we can do it in the rust tests with `#[ignore]`. Maybe we need to add something similar to sqllogictests


> It will be much easier to find test-cases that don't work right now. The tests won't even have to be changed, except perhaps excluded from the "expectedly fail" category.

One way to do this is to search for issue links `https://github.com...`

File: datafusion/core/src/physical_optimizer/projection_pushdown.rs (hunk 1 above)
Comment (viirya) [reply datafusion/core/src/physical_optimizer/projection_pushdown.rs:919]: I think for `new_columns_for_join_on` and `new_indices_for_join_filter`, you won't hit a similar issue like this. The reason is https://github.com/apache/arrow-datafusion/pull/9096#discussion_r1474725804.

**Comment by viirya** [comment]
Thank you @alamb @DDtKey @berkaysynnada

**Comment by alamb** [comment]
BTW https://github.com/apache/arrow-datafusion/issues/9111 tracks the work @berkaysynnada  is doing for ProjectionPushdown in case anyone has thoughts they would like to share
