### PR TITLE
Bug/union wrong casting

### LINKED ISSUE #5212: Upcast types during union schema creation.
**Describe the bug**
When I run the query below on postgre
```sql
SELECT c1, c9 FROM aggregate_test_100 
UNION ALL 
SELECT c1, c3 FROM aggregate_test_100
```
where c9 has type `Bigint` and c3 has type `smallint`. It produces a valid result. However, when I run the above query on datafusion where c9 has type `Uint32` and c3 has type `Int8`.
It gives the error `ArrowError(CastError("Can't cast value 1491205016 to type Int8"))`.
The physical plan of the query above in DataFusion is as follows
```sql
"UnionExec",
"  ProjectionExec: expr=[c1@0 as c1, c3@1 as c3]",
"    CsvExec: files={1 group: [[Users/akurmustafa/projects/synnada/arrow-datafusion-tmp/testing/data/csv/aggregate_test_100.csv]]}, has_header=true, limit=None, projection=[c1, c3]",
"  ProjectionExec: expr=[c1@0 as c1, CAST(c9@1 AS Int8) as c3]",
"    CsvExec: files={1 group: [[Users/akurmustafa/projects/synnada/arrow-datafusion-tmp/testing/data/csv/aggregate_test_100.csv]]}, has_header=true, limit=None, projection=[c1, c9]",
```

Datafusion coerces the types `DataType::Uint32` and `DataType::Int8` to `DataType::Int8`. For instance we may choose to upcast types to `DataType::Int64` for this specific case.

**To Reproduce**
One can run query above

**Expected behavior**
I expect above query to work

**Additional context**

### PR DESCRIPTION
**Pull request by berkaysynnada**
# Which issue does this PR close?

Closes #5212.

# Rationale for this change

When we try to use "UNION" on columns having differently signed or sized integer types, we get a cast error for some cases (explained in the issue), which can be handled accurately. 

# What changes are included in this PR?

Previous casting matches are modified such that the resulting type of the column will be the smallest unit that will not cause to any error.

  | Int64 | Int32 | Int16 | Int8 | UInt64 | UInt32 | UInt16 | UInt8
-- | -- | -- | -- | -- | -- | -- | -- | --
Int64 | Int64 | Int64 | Int64 | Int64 | Int64 | Int64 | Int64 | Int64
Int32 | Int64 | Int32 | Int32 | Int32 | Int64 | Int64 | Int32 | Int32
Int16 | Int64 | Int32 | Int16 | Int16 | Int64 | Int64 | Int32 | Int16
Int8 | Int64 | Int32 | Int16 | Int8 | Int64 | Int64 | Int32 | Int16
UInt64 | Int64 | Int64 | Int64 | Int64 | UInt64 | UInt64 | UInt64 | UInt64
UInt32 | Int64 | Int64 | Int64 | Int64 | UInt64 | UInt32 | UInt32 | UInt32
UInt16 | Int64 | Int32 | Int32 | Int32 | UInt64 | UInt32 | UInt16 | UInt16
UInt8 | Int64 | Int32 | Int16 | Int16 | UInt64 | UInt32 | UInt16 | UInt8

# Are these changes tested?

Yes, `test_union_upcast_types` test function is added showing the error is solved in the issue.

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by iajoiner** [comment]
@berkaysynnada Really thanks for your work! I wonder what the type of the union of an Int64 and an UInt64 should be though.

**Comment by ozankabak** [comment]
Once you hit the widest fixed-size type, information loss becomes inevitable unless you have `bigint` or arbitrary-precision types at your disposal (for integral and floating point types, respectively). AFAIK Datafusion does not do such types at this time. If this is indeed true, we need to choose between losing very high numbers (by casting to `Int64`), or lose negative numbers (by casting to `UInt64`).

**Comment by jackwener** [comment]
cc @liukun4515

File: datafusion/expr/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -238,13 +238,32 @@ fn comparison_binary_numeric_coercion(
         (_, Decimal128(_, _)) => get_comparison_common_decimal_type(rhs_type, lhs_type),
         (Float64, _) | (_, Float64) => Some(Float64),
         (_, Float32) | (Float32, _) => Some(Float32),
-        (Int64, _) | (_, Int64) => Some(Int64),
-        (Int32, _) | (_, Int32) => Some(Int32),
-        (Int16, _) | (_, Int16) => Some(Int16),
-        (Int8, _) | (_, Int8) => Some(Int8),
+        // start checking from Int64, that is the most inclusive integer type
```
Comment (alamb) [inline datafusion/expr/src/type_coercion/binary.rs:241]: Could we express the same logic more concisely with something like:

```
      (Int64, _) | (_, Int64) => Some(Int64),
        (Int32, _) | (_, Int32) => Some(Int64),
        (Int16, _) | (_, Int16) => Some(Int32),
        (Int8, _) | (_, Int8) => Some(Int16),
```

File: datafusion/expr/src/type_coercion/binary.rs [hunk 2]
```diff
@@ -238,13 +238,32 @@ fn comparison_binary_numeric_coercion(
...
+        | (Int32, UInt64)
+        | (UInt32, Int8)
+        | (Int8, UInt32)
+        | (UInt32, Int16)
+        | (Int16, UInt32)
+        | (UInt32, Int32)
+        | (Int32, UInt32) => Some(Int64),
         (UInt64, _) | (_, UInt64) => Some(UInt64),
+        (Int32, _)
+        | (_, Int32)
```
Comment (alamb) [inline datafusion/expr/src/type_coercion/binary.rs:258]: If one of the arguments is Int32, doesn't that mean the output should be Int64? 
(as in `(_, Int32)` should not be in the same match arm.

File: datafusion/expr/src/type_coercion/binary.rs (hunk 1 above)
Comment (alamb) [reply datafusion/expr/src/type_coercion/binary.rs:241]: Likewise I think the same pattern could be used for `UInt*` variants

**Review by alamb — COMMENTED** [review]
Thank you @berkaysynnada  -- sorry for the delay in review. This is looking good

File: datafusion/expr/src/type_coercion/binary.rs (hunk 1 above)
Comment (ozankabak) [reply datafusion/expr/src/type_coercion/binary.rs:241]: Wouldn't that map (`Int32`, `Int16`) to `Int64`? I think @berkaysynnada's intent is to map to the narrowest correct type, which in this case would be `Int32`.

I am not sure if the `match` pattern is the most succinct representation of the table in the PR text though.

Comment (alamb) [reply datafusion/expr/src/type_coercion/binary.rs:241]: > Wouldn't that map (Int32, Int16) to Int64? 

Yes.

I guess I was thinking of the more general case for arithmetic where  `i32::MAX + i16::MAX` requires a `i64` to store

Comment (ozankabak) [reply datafusion/expr/src/type_coercion/binary.rs:241]: I am confused by the sum. Aren't we just "merging" the schemas? In that case, the narrowest type that can represent both sides should be chosen, no? Am I missing something here?

Comment (alamb) [reply datafusion/expr/src/type_coercion/binary.rs:241]: I think I am just confused 

For example this PR adds this rule:

```
(Int8, UInt16) => Some(Int32),
```

Which isn't just merging the schema (e.g. UInt16) in my mind, but is extending it in some way. In this case, so that the entire range of `Int8` and `UInt16` can be represented -- which now makes sense

I think what would help me would be:
1. Add some comments explaining the rationale for these rules
2. (maybe) add test coverage (ideally looking like your beautiful table from the PR description) that helps to illustrate the point

However, I don't think this is needed prior to merging this PR

**Review by alamb — APPROVED** [review]

File: datafusion/expr/src/type_coercion/binary.rs (hunk 1 above)
Comment (ozankabak) [reply datafusion/expr/src/type_coercion/binary.rs]: Just added comments to explain the reasoning of the `match` patterns. Also took note to add some tests in a follow-on PR. Thanks for the review!

**Comment by alamb** [comment]
Thank you!
