### PR TITLE
fix: Support Dict types in `in_list` physical plans

### LINKED ISSUE #9530: in_list doesn't handle value being a Dictionary type when check data type matches
### Describe the bug

When I'm working on https://github.com/apache/arrow-datafusion-comet/pull/184, I notice that some tpc-ds queries failing when trying to convert the static list into the set.

The error message is something like:
```
Error from DataFusion Internal error: The data type inlist should be same, the value type is Dictionary(Int32, Utf8), one of list expr type is Utf8.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker..
```

### To Reproduce

Create in input schema with a Dictionary type and then try to convert the in_list expression should easily reproduce this one.

### Expected behavior

When using `in_list` to create a `InListExpr`, it should handle value type being Dictionary Type.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by advancedxy**
## Which issue does this PR close?
Closes #9530.

## Rationale for this change
Dictionary types are already supported in the `InListExpr`, however, the `in_list` func doesn't handle types being 
mixed in with Dictionary types.

## What changes are included in this PR?
Relax type check in the `in_list` function.

## Are these changes tested?
Added new test

## Are there any user-facing changes?
No

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @advancedxy  -- would it be possible to add some end to end tests as well in https://github.com/apache/arrow-datafusion/tree/main/datafusion/sqllogictest?

Perhaps we could extend https://github.com/apache/arrow-datafusion/blob/main/datafusion/sqllogictest/test_files/dictionary.slt

File: datafusion/physical-expr/src/expressions/in_list.rs [hunk 1]
```diff
@@ -415,6 +415,18 @@ impl PartialEq<dyn Any> for InListExpr {
     }
 }
 
+/// Checks if two types are logically equal, dictionary types are compared by their value types.
+fn is_logically_eq(lhs: &DataType, rhs: &DataType) -> bool {
```
Comment (comphead) [inline datafusion/physical-expr/src/expressions/in_list.rs:419]: hm, I think we have a similar method in https://github.com/apache/arrow-datafusion/blob/f55c1d90215614ce531a4103c7dbebf318de1cfd/datafusion/common/src/dfschema.rs#L643 basically the schema struct has a lot of equal checks between datatypes. may want to move them into separate utils struct as they mostly working with datatypes rather than schema

Comment (alamb) [reply datafusion/physical-expr/src/expressions/in_list.rs:419]: I agree we could use `datatype_is_logically_equal` instead here. It also seems like a good idea to make that function more discoverable -- I also think it would be fine to do as a follow on PR

**Review by alamb — COMMENTED** [review]
The tests don't seem to cover the new code. 

When I reverted the code change locally like this:
```diff
diff --git a/datafusion/physical-expr/src/expressions/in_list.rs b/datafusion/physical-expr/src/expressions/in_list.rs
index ad2da57b5..5d9fb19af 100644
--- a/datafusion/physical-expr/src/expressions/in_list.rs
+++ b/datafusion/physical-expr/src/expressions/in_list.rs
@@ -415,18 +415,6 @@ impl PartialEq<dyn Any> for InListExpr {
     }
 }

-/// Checks if two types are logically equal, dictionary types are compared by their value types.
-fn is_logically_eq(lhs: &DataType, rhs: &DataType) -> bool {
-    match (lhs, rhs) {
-        (DataType::Dictionary(_, v1), DataType::Dictionary(_, v2)) => {
-            v1.as_ref().eq(v2.as_ref())
-        }
-        (DataType::Dictionary(_, l), _) => l.as_ref().eq(rhs),
-        (_, DataType::Dictionary(_, r)) => lhs.eq(r.as_ref()),
-        _ => lhs.eq(rhs),
-    }
-}
-
 /// Creates a unary expression InList
 pub fn in_list(
     expr: Arc<dyn PhysicalExpr>,
@@ -438,7 +426,7 @@ pub fn in_list(
     let expr_data_type = expr.data_type(schema)?;
     for list_expr in list.iter() {
         let list_expr_data_type = list_expr.data_type(schema)?;
-        if !is_logically_eq(&expr_data_type, &list_expr_data_type) {
+        if !expr_data_type.eq(&list_expr_data_type) {
             return internal_err!(
                 "The data type inlist should be same, the value type is {expr_data_type}, one of list expr type is {list_expr_data_type}"
             );
```

The tests still pass 🤔 
```shell
$ cargo test -p datafusion-physical-expr -- in_list_utf8_with_dict_types
    Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running unittests src/lib.rs (target/debug/deps/datafusion_physical_expr-671316f98d0b9705)

running 1 test
test expressions::in_list::tests::in_list_utf8_with_dict_types ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1574 filtered out; finished in 0.00s
```
 
I worry that this means we might break this feature in the future but not know...

File: datafusion/physical-expr/src/expressions/in_list.rs [hunk 2]
```diff
@@ -1314,4 +1340,96 @@ mod tests {
...
+        // expression: "a in ("a", "b")"
+        let lists = [
+            vec![lit("a"), lit("b")],
+            vec![
+                dict_lit(DataType::Int8, "a"),
+                dict_lit(DataType::UInt16, "b"),
+            ],
+        ];
+        for list in lists.iter() {
+            in_list_raw!(
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/in_list.rs:1379]: I don't understand this change -- the tests now call `in_list_raw` directly. But there is no way that `in_list_raw` will be called outside of this module 🤔

**Review by alamb — COMMENTED** [review]
Thanks @advancedxy  -- I still think there is something not right about this PR

I don't think this PR will change any external behavior (see my comments)

Also the `sqllogictest`s still pass without the code change

I am beginning to wonder if we really understand the problem or not.

I would suggest starting at this problem from the other end -- can we write a test that causes the error seen in comet (aka do whatever comet is doing). Once we have that then we can change to code to fix it

File: datafusion/physical-expr/src/expressions/in_list.rs (hunk 2 above)
Comment (alamb) [reply datafusion/physical-expr/src/expressions/in_list.rs:1379]: Got it -- what I don't understand is how these validate the Comet use case. I expect them to call `in_list` (instead they calling the `in_list_raw!` macro)

What I was expected to see was a test that mirrors what comet does: call `in_list` with a Dictionary column but string literals (that haven't ben type cerced).

Given this case current errors, we have no test coverage, even if the `in_list` implementation does actually support it. 

Sorry to be so pedantic about this, but I think it is somewhat subtle so making sure we get it right (and don't accidentally break it in the future) I think is important

Comment (alamb) [reply datafusion/physical-expr/src/expressions/in_list.rs:1379]: > There might be some misunderstanding here. in_list and in_list_raw are both test macros, the main difference is that the former performs type coercion first and the latter does not.

Ahh! Yes I was missing exactly this point. Sorry about that. Makes total sense.

**Review by alamb — APPROVED** [review]
Thank you @advancedxy  -- yes I was confused about the macro. Thanks for bearing with me !
