### PR TITLE
CaseWhen: coerce the all then and else data type to a common data type

### LINKED ISSUE #2818: CASE When: result type should be coercible to a common type
**Describe the bug**

```
❯ select case when 1=1 then true else 1 end;
+--------------------------------------------------------------------+
| CASE WHEN Int64(1) = Int64(1) THEN Boolean(true) ELSE Int64(1) END |
+--------------------------------------------------------------------+
| true                                                               |
+--------------------------------------------------------------------+
1 row in set. Query took 0.042 seconds.
❯ explain select case when 1=1 then true else 1 end;
+---------------+---------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                              |
+---------------+---------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: Boolean(true) AS CASE WHEN Int64(1) = Int64(1) THEN Boolean(true) ELSE Int64(1) END   |
|               |   EmptyRelation                                                                                   |
| physical_plan | ProjectionExec: expr=[true as CASE WHEN Int64(1) = Int64(1) THEN Boolean(true) ELSE Int64(1) END] |
|               |   EmptyExec: produce_one_row=true                                                                 |
|               |                                                                                                   |
+---------------+---------------------------------------------------------------------------------------------------+
2 rows in set. Query took 0.003 seconds.
❯ explain select case when 1>1 then true else 1 end;
+---------------+---------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                              |
+---------------+---------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: Boolean(true) AS CASE WHEN Int64(1) > Int64(1) THEN Boolean(true) ELSE Int64(1) END   |
|               |   EmptyRelation                                                                                   |
| physical_plan | ProjectionExec: expr=[true as CASE WHEN Int64(1) > Int64(1) THEN Boolean(true) ELSE Int64(1) END] |
|               |   EmptyExec: produce_one_row=true                                                                 |
|               |                                                                                                   |
+---------------+---------------------------------------------------------------------------------------------------+
2 rows in set. Query took 0.004 seconds.
❯  select case when 1>1 then true else 1 end;
+--------------------------------------------------------------------+
| CASE WHEN Int64(1) > Int64(1) THEN Boolean(true) ELSE Int64(1) END |
+--------------------------------------------------------------------+
| true                                                               |
+--------------------------------------------------------------------+
```
One case when sql has two diff result data type.

From other system, case when should have the common data type, but now the result type is the first non-null data type.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

Closes #2818 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/case.rs [hunk 1]
```diff
@@ -76,7 +77,7 @@ impl CaseExpr {
     /// Create a new CASE WHEN expression
     pub fn try_new(
         expr: Option<Arc<dyn PhysicalExpr>>,
-        when_then_expr: &[WhenThen],
+        when_then_expr: Vec<WhenThen>,
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:80]: 👍

File: datafusion/physical-expr/src/expressions/case.rs [hunk 2]
```diff
@@ -291,12 +292,67 @@ impl PhysicalExpr for CaseExpr {
...
+            Ok((left, right))
+        }
+    }?;
+
     Ok(Arc::new(CaseExpr::try_new(expr, when_thens, else_expr)?))
 }
 
+fn get_case_common_type(
+    when_thens: &[WhenThen],
+    else_expr: Option<Arc<dyn PhysicalExpr>>,
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:329]:
```suggestion
    else_expr: Option<&PhysicalExpr>,
```

I wonder if there is a reason it needs to get a copy, or would a reference work too?

File: datafusion/physical-expr/src/expressions/case.rs [hunk 3]
```diff
@@ -291,12 +292,67 @@ impl PhysicalExpr for CaseExpr {
...
+            // case when then exprs must have one then value
+            thens_type[0].clone()
+        }
+        Some(else_phy_expr) => else_phy_expr.data_type(input_schema).unwrap(),
+    };
+    thens_type
+        .iter()
+        .fold(Some(else_type), |left, right_type| match left {
+            None => None,
+            // TODO: now just use the `equal` coercion rule for case when. If find the issue, and
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:350]: 👍

File: datafusion/physical-expr/src/expressions/case.rs [hunk 4]
```diff
@@ -291,12 +292,67 @@ impl PhysicalExpr for CaseExpr {
...
+        ))),
+        Some(data_type) => {
+            // cast then expr
+            let left = when_thens
+                .into_iter()
+                .map(|(when, then)| {
+                    let then = try_cast(then, input_schema, data_type.clone()).unwrap();
+                    (when, then)
+                })
+                .collect::<Vec<WhenThen>>();
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:315]: Are we sure this will always return without error (aka that this will not panic)?

Since this function can return an `Result` anyways, would it be better to return it. Something like (untested):

 ```suggestion
            let left = when_thens
                .into_iter()
                .map(|(when, then)| {
                    let then = try_cast(then, input_schema, data_type.clone())?
                    Ok((when, then))
                })
                .collect::<Result<Vec<WhenThen>>>()?;
```

File: datafusion/physical-expr/src/expressions/case.rs [hunk 5]
```diff
@@ -635,4 +704,67 @@ mod tests {
...
+        // 1 then is int64
+        // 2 then is boolean
+        let batch = case_test_batch()?;
+        let schema = batch.schema();
+
+        // CASE WHEN a = 'foo' THEN 123 WHEN a = 'bar' THEN true END
+        let when1 = binary(
+            col("a", &schema)?,
+            Operator::Eq,
+            lit(ScalarValue::Utf8(Some("foo".to_string()))),
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/case.rs:719]: It would be nice if the the `lit` in the physical expr could use `lit("foo")` as well. But I tried it and it doesn't work 

```suggestion
            lit("foo"),
```

**Review by alamb — APPROVED** [review]
Looks good to me -- I had some style suggestions but nothing major. Thank you @liukun4515

**Comment by alamb** [comment]
I accidentally pushed commits to this branch -- I think I have removed them now. My apologies

File: datafusion/physical-expr/src/expressions/case.rs (hunk 5 above)
Comment (alamb) [reply datafusion/physical-expr/src/expressions/case.rs:719]: https://github.com/apache/arrow-datafusion/pull/2828

Comment (liukun4515) [reply datafusion/physical-expr/src/expressions/case.rs:719]: I will rebase this pr after https://github.com/apache/arrow-datafusion/pull/2828 merged

File: datafusion/physical-expr/src/expressions/case.rs (hunk 4 above)
Comment (liukun4515) [reply datafusion/physical-expr/src/expressions/case.rs:315]: good catch

File: datafusion/physical-expr/src/expressions/case.rs (hunk 2 above)
Comment (liukun4515) [reply datafusion/physical-expr/src/expressions/case.rs:330]: The reference is not work for this.

File: datafusion/physical-expr/src/expressions/case.rs (hunk 5 above)
Comment (liukun4515) [reply datafusion/physical-expr/src/expressions/case.rs]: changed the code to use `lit("foo")` with merged https://github.com/apache/arrow-datafusion/pull/2828
