### PR TITLE
Change `ScalarValue::{List, LargeList, FixedSizedList}` to take specific types rather than `ArrayRef`

### LINKED ISSUE #8472: `ScalarValue::List` not working as expected in UDAF state
### Describe the bug

I am trying to use `ScalarValue::List` to store `f64` values for the `state` in a UDAF. It was working well in datafusion version 32, but I upgraded to datafusion 33, only to find that the API had changed for `ScalarValue::List` to accept an `ArrayRef` rather than an `Option<Vec<ScalarValue>>`. I thought I had converted my code correctly, but I'm getting the following error:
```
Error: External(Internal("Inconsistent types in ScalarValue::iter_to_array. Expected Float64, got List([PrimitiveArray<Float64>\n[\n  43.0,\n  1.0,\n  43.0,\n  1.0,\n  43.0,\n  1.0,\n  43.0,\n  1.0,\n  43.0,\n  3.0,\n  ...180 elements...,\n  62.0,\n  3.0,\n  62.0,\n  2.0,\n  63.0,\n  1.0,\n  63.0,\n  1.0,\n  63.0,\n  1.0,\n]])"))
```
First of all, I can't tell exactly where this error is coming from (and RUST_BACKTRACE=1 doesn't do anything), even after adding some log statements at the beginning and end of each `Accumulator` function (what I mean by this is that this error doesn't seem to be occurring "in the middle" of any of the `Accumulator` functions I've implemented).

I am serializing my list via `ScalarValue::List(Arc::new(Float64Array::from(floats)))` where `floats: Vec<f64>`
And deserializing my list via something like this:
```
if let ScalarValue::List(float_vals) = &v[0] {
  let floats: Vec<f64> = float_vals
    .as_any()
    .downcast_ref::<Float64Array>()
    .expect("Failed to downcast")
    .values()
    .collect()
}
```
Finally, my `state_type` in the `create_udaf` function is:
```
Arc::new(vec![
    DataType::List(Field::new(
        "item",
        DataType::Float64,
        true
    ).into())
```

Via logging, I seem to get successful calls to `state` and `update_batch` (`update_batch` doesn't concern itself with the serialized state and probably isn't part of the issue). If the issue was in the state deserialization I'd expect to see a log statement from the beginning of `merge_batch` but not one from the end, but I'm not seeing any of my `merge_batch` log statements.

I'm not sure if I'm making a mistake somewhere, or if this is a bug. But it seems like somewhere in the guts of the `Accumulator`, something is not working correctly. Happy to help fix the bug if one can be identified.

### To Reproduce

Define a UDAF `Accumulator` that uses `ScalarValue::List` to serialize its state, and use the aggregate function.

### Expected behavior

Successful aggregation of the values into a new dataframe column.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rspears74**
## Which issue does this PR close?

Closes #8472 

## Rationale for this change

It's much preferable to constrain `ScalarValue::List` to accept only an `Arc<ListArray>` rather than any `ArrayRef` and fail randomly. Similar for `ScalarValue::LargeList` and `ScalarValue::FixedSizeList`.

## What changes are included in this PR?

Changed the type signature of `ScalarValue::List`, `ScalarValue::LargeList`, and `ScalarValue::FixedSizedList` and any cascading changes that follow from this. One test compared a `ListArray` passed to `ScalarValue::List` to a `LargeListArray` passed to `ScalarValue::List` - because `ScalarValue::List` only accepts `ListArray` now, this test was changed to compare two `ListArray`s instead.

## Are these changes tested?

Tests have been updated where needed.

## Are there any user-facing changes?

Users are now only allowed to pass a `ListArray` to `ScalarValue::List`, a `LargeListArray` to `ScalarValue::LargeList`, and a `FixedSizeListArray` to `ScalarValue::FixedSizeList`.

### CODE REVIEW

File: datafusion/common/src/scalar.rs [hunk 1]
```diff
@@ -3300,33 +3409,6 @@ mod tests {
         assert_eq!(result, &expected);
     }
 
-    #[test]
```
Comment (jayzhan211) [inline datafusion/common/src/scalar.rs:3303]: Is ScalarValue::eq_array test for List elsewhere? Otherwise, we can add the test for it.

File: datafusion/proto/src/logical_plan/to_proto.rs [hunk 2]
```diff
@@ -1159,13 +1160,105 @@ impl TryFrom<&ScalarValue> for protobuf::ScalarValue {
...
+                let schema: protobuf::Schema = batch.schema().try_into()?;
+
+                let scalar_list_value = protobuf::ScalarListValue {
+                    ipc_message: encoded_message.ipc_message,
+                    arrow_data: encoded_message.arrow_data,
+                    schema: Some(schema),
+                };
+
+                match val {
+                    ScalarValue::List(_) => Ok(protobuf::ScalarValue {
```
Comment (jayzhan211) [inline datafusion/proto/src/logical_plan/to_proto.rs:1192]: I think val is already matched to ScalarValue::List in this block, just process it.

File: datafusion/proto/src/logical_plan/to_proto.rs [hunk 3]
```diff
@@ -1159,13 +1160,105 @@ impl TryFrom<&ScalarValue> for protobuf::ScalarValue {
...
+                        value: Some(protobuf::scalar_value::Value::ListValue(
+                            scalar_list_value,
+                        )),
+                    }),
+                    ScalarValue::LargeList(_) => Ok(protobuf::ScalarValue {
```
Comment (jayzhan211) [inline datafusion/proto/src/logical_plan/to_proto.rs:1244]: Same

File: datafusion/proto/src/logical_plan/to_proto.rs [hunk 4]
```diff
@@ -1159,13 +1160,105 @@ impl TryFrom<&ScalarValue> for protobuf::ScalarValue {
...
+                    }),
+                    ScalarValue::FixedSizeList(_) => Ok(protobuf::ScalarValue {
+                        value: Some(protobuf::scalar_value::Value::FixedSizeListValue(
+                            scalar_list_value,
+                        )),
+                    }),
+                    _ => unreachable!(),
+                }
+            }
+            ScalarValue::FixedSizeList(arr) => {
```
Comment (jayzhan211) [inline datafusion/proto/src/logical_plan/to_proto.rs:1257]: Same for this

**Review by jayzhan211 — CHANGES_REQUESTED** [review]

File: datafusion/proto/src/logical_plan/to_proto.rs (hunk 2 above)
Comment (rspears74) [reply datafusion/proto/src/logical_plan/to_proto.rs:1192]: Ah good catch on these!

File: datafusion/common/src/scalar.rs (hunk 1 above)
Comment (jayzhan211) [reply datafusion/common/src/scalar.rs]: Sure!

**Review by jayzhan211 — APPROVED** [review]
LGTM

**Comment by jayzhan211** [comment]
@alamb It seems you forget to trace this PR in https://github.com/apache/arrow-datafusion/issues/8704?

File: datafusion/common/src/scalar.rs [hunk 5]
```diff
@@ -2936,13 +3026,33 @@ impl fmt::Display for ScalarValue {
...
+                assert_eq!(arr.len(), 1);
+                let options = FormatOptions::default().with_display_error(true);
+                let formatter =
+                    ArrayFormatter::try_new(arr.as_ref() as &dyn Array, &options)
+                        .unwrap();
+                let value_formatter = formatter.value(0);
+                write!(f, "{value_formatter}")?
+            }
+            ScalarValue::LargeList(arr) => {
+                // ScalarValue List should always have a single element
```
Comment (Weijun-H) [inline datafusion/common/src/scalar.rs:3040]:
```suggestion
                // ScalarValue LargeList should always have a single element
```

File: datafusion/common/src/scalar.rs [hunk 6]
```diff
@@ -2936,13 +3026,33 @@ impl fmt::Display for ScalarValue {
...
+                assert_eq!(arr.len(), 1);
+                let options = FormatOptions::default().with_display_error(true);
+                let formatter =
+                    ArrayFormatter::try_new(arr.as_ref() as &dyn Array, &options)
+                        .unwrap();
+                let value_formatter = formatter.value(0);
+                write!(f, "{value_formatter}")?
+            }
+            ScalarValue::FixedSizeList(arr) => {
                 // ScalarValue List should always have a single element
```
Comment (Weijun-H) [inline datafusion/common/src/scalar.rs:3050]:
```suggestion
                // ScalarValue FixedSizeList should always have a single element
```

File: datafusion/proto/src/logical_plan/to_proto.rs [hunk 7]
```diff
@@ -1189,24 +1188,79 @@ impl TryFrom<&ScalarValue> for protobuf::ScalarValue {
...
+                })
+            }
+            ScalarValue::LargeList(arr) => {
+                // Wrap in a "field_name" column
+                let batch = RecordBatch::try_from_iter(vec![(
+                    "field_name",
+                    arr.to_owned() as ArrayRef,
+                )])
+                .map_err(|e| {
+                   Error::General( format!("Error creating temporary batch while encoding ScalarValue::List: {e}"))
```
Comment (Weijun-H) [inline datafusion/proto/src/logical_plan/to_proto.rs:1204]:
```suggestion
                   Error::General( format!("Error creating temporary batch while encoding ScalarValue::LargeList: {e}"))
```

File: datafusion/proto/src/logical_plan/to_proto.rs [hunk 8]
```diff
@@ -1189,24 +1188,79 @@ impl TryFrom<&ScalarValue> for protobuf::ScalarValue {
...
+                })
+            }
+            ScalarValue::FixedSizeList(arr) => {
+                // Wrap in a "field_name" column
+                let batch = RecordBatch::try_from_iter(vec![(
+                    "field_name",
+                    arr.to_owned() as ArrayRef,
+                )])
+                .map_err(|e| {
+                   Error::General( format!("Error creating temporary batch while encoding ScalarValue::List: {e}"))
```
Comment (Weijun-H) [inline datafusion/proto/src/logical_plan/to_proto.rs:1238]:
```suggestion
                   Error::General( format!("Error creating temporary batch while encoding ScalarValue::FixedSizeList: {e}"))
```

**Review by Weijun-H — APPROVED** [review]
LGTM! Thanks @rspears74 👍

**Comment by alamb** [comment]
I will try and find time to review this PR later this week . Sorry for the delay

File: datafusion/proto/src/logical_plan/to_proto.rs [hunk 9]
```diff
@@ -1189,24 +1188,79 @@ impl TryFrom<&ScalarValue> for protobuf::ScalarValue {
...
-                    }),
-                    _ => unreachable!(),
-                }
+                Ok(protobuf::ScalarValue {
+                    value: Some(protobuf::scalar_value::Value::ListValue(
+                        scalar_list_value,
+                    )),
+                })
+            }
+            ScalarValue::LargeList(arr) => {
```
Comment (alamb) [inline datafusion/proto/src/logical_plan/to_proto.rs:1197]: Would it be possible to avoid the copy/paste in this method by making a function? Something like the following?

```rust
fn encode_scalar_list_value(array: &Array) -> Result<protobuf::ScalarListValue> {
...
}
```

File: datafusion/common/src/scalar.rs [hunk 10]
```diff
@@ -359,29 +359,77 @@ impl PartialOrd for ScalarValue {
...
-                fn first_array_for_list(arr: &ArrayRef) -> ArrayRef {
-                    if let Some(arr) = arr.as_list_opt::<i32>() {
-                        arr.value(0)
-                    } else if let Some(arr) = arr.as_list_opt::<i64>() {
-                        arr.value(0)
-                    } else if let Some(arr) = arr.as_fixed_size_list_opt() {
-                        arr.value(0)
-                    } else {
-                        unreachable!("Since only List / LargeList / FixedSizeList are supported, this should never happen")
+                fn first_array_for_list(arr: &Arc<ListArray>) -> ArrayRef {
```
Comment (alamb) [inline datafusion/common/src/scalar.rs:371]: It would be really nice here to avoid the redundant copy/paste code, perhaps by making a function with signature like this

```
fn cmp_list_array(arr1: &dyn Array, arr2: &dyn Array) -> Option<Ordering> {
..
}
```

Which then you can call with `Arc<ListArray>` and `Arc<LargeListArray>` types

**Review by alamb — COMMENTED** [review]
Thank you for this PR @rspears74  - I think it is looking quite close. There are a few places where code gets repeated 3 times that I think we can avoid by refactoring code into  specific functions. I left some more specific suggestions below. 

Also thank you @jayzhan211  and @Weijun-H  for the reviews

File: datafusion/proto/src/logical_plan/to_proto.rs (hunk 9 above)
Comment (rspears74) [reply datafusion/proto/src/logical_plan/to_proto.rs:1197]: This one was easy enough to implement.

File: datafusion/common/src/scalar.rs (hunk 10 above)
Comment (rspears74) [reply datafusion/common/src/scalar.rs:371]: This one is a little tougher, because if the args to the function are "generic" (i.e. ArrayRef instead of a specific `Arc<ListArray>` type), the `arr1.value(0)` method is not available. The `first_array_for_list` function needs to be able to convert the `ArrayRef` into the specific type to then get the value out. So I'm struggling a bit coming up with a way here.

**Comment by rspears74** [comment]
Welp, I had a merge conflict, and upon fixing it, there's some new code that's incompatible with these changes, so I'm gonna have to do a little more involved work to fix those. Will try to make that happen ASAP.

**Comment by rspears74** [comment]
> Welp, I had a merge conflict, and upon fixing it, there's some new code that's incompatible with these changes (not compiling), so I'm gonna have to do a little more involved work to fix those. Will try to make that happen ASAP.

Alright that wasn't so bad. Fixed and passing tests.

**Review by jayzhan211 — APPROVED** [review]
LGTM

File: datafusion/common/src/scalar.rs (hunk 10 above)
Comment (alamb) [reply datafusion/common/src/scalar.rs:373]: Here is a proposal of how to do it: https://github.com/rspears74/arrow-datafusion/pull/1 (that targets this PR)

File: datafusion/common/src/scalar.rs [hunk 11]
```diff
@@ -2937,13 +3015,33 @@ impl fmt::Display for ScalarValue {
...
             },
-            ScalarValue::List(arr)
-            | ScalarValue::LargeList(arr)
-            | ScalarValue::FixedSizeList(arr) => {
+            ScalarValue::List(arr) => {
                 // ScalarValue List should always have a single element
                 assert_eq!(arr.len(), 1);
                 let options = FormatOptions::default().with_display_error(true);
-                let formatter = ArrayFormatter::try_new(arr, &options).unwrap();
+                let formatter =
```
Comment (alamb) [inline datafusion/common/src/scalar.rs:3022]: The same pattern could be applied here as in https://github.com/rspears74/arrow-datafusion/pull/1 (use `first_array_for_list`)

**Review by alamb — APPROVED** [review]
Thank you @rspears74   -- I think this is looking good.

cc @wjones127  since I think you are interested in FixedSizedList in general

I think there is still some repetition that could be avoided (I left my suggestions on how to do so) but we could potentially do that as a follow on PR as well

File: datafusion/common/src/scalar.rs (hunk 11 above)
Comment (rspears74) [reply datafusion/common/src/scalar.rs:2977]: I'll take care of this one too. I went through my changes looking for any larger duplication sections but missed this one.

File: datafusion/common/src/scalar.rs [hunk 12]
```diff
@@ -942,9 +958,9 @@ impl ScalarValue {
             ScalarValue::Binary(_) => DataType::Binary,
             ScalarValue::FixedSizeBinary(sz, _) => DataType::FixedSizeBinary(*sz),
             ScalarValue::LargeBinary(_) => DataType::LargeBinary,
-            ScalarValue::List(arr)
-            | ScalarValue::LargeList(arr)
-            | ScalarValue::FixedSizeList(arr) => arr.data_type().to_owned(),
+            ScalarValue::List(arr) => arr.data_type().to_owned(),
+            ScalarValue::LargeList(arr) => arr.data_type().to_owned(),
+            ScalarValue::FixedSizeList(arr) => arr.data_type().to_owned(),
```
Comment (wjones127) [inline datafusion/common/src/scalar.rs:963]: This seems like a unnecessary change.

File: datafusion/common/src/scalar.rs [hunk 13]
```diff
@@ -1147,9 +1163,9 @@ impl ScalarValue {
             ScalarValue::LargeBinary(v) => v.is_none(),
             // arr.len() should be 1 for a list scalar, but we don't seem to
             // enforce that anywhere, so we still check against array length.
-            ScalarValue::List(arr)
-            | ScalarValue::LargeList(arr)
-            | ScalarValue::FixedSizeList(arr) => arr.len() == arr.null_count(),
+            ScalarValue::List(arr) => arr.len() == arr.null_count(),
+            ScalarValue::LargeList(arr) => arr.len() == arr.null_count(),
+            ScalarValue::FixedSizeList(arr) => arr.len() == arr.null_count(),
```
Comment (wjones127) [inline datafusion/common/src/scalar.rs:1168]: Similar unnecessary change here.

File: datafusion/common/src/scalar.rs [hunk 14]
```diff
@@ -2433,11 +2455,14 @@ impl ScalarValue {
...
-                let right = array.slice(index, 1);
-                arr == &right
+            ScalarValue::List(arr) => {
+                Self::eq_array_list(&(arr.to_owned() as ArrayRef), array, index)
+            }
+            ScalarValue::LargeList(arr) => {
+                Self::eq_array_list(&(arr.to_owned() as ArrayRef), array, index)
+            }
+            ScalarValue::FixedSizeList(arr) => {
+                Self::eq_array_list(&(arr.to_owned() as ArrayRef), array, index)
```
Comment (wjones127) [inline datafusion/common/src/scalar.rs:2465]: nit: this could be combined to avoid repeated code. (This is the last comment I'll make about this, but it applies to several more parts of your changeset)

```suggestion
            ScalarValue::List(arr)
            | ScalarValue::LargeList(arr)
            | ScalarValue::FixedSizeList(arr) => {
                Self::eq_array_list(&(arr.to_owned() as ArrayRef), array, index)
```

File: datafusion/common/src/scalar.rs [hunk 15]
```diff
@@ -142,13 +143,13 @@ pub enum ScalarValue {
     /// Fixed size list scalar.
     ///
     /// The array must be a FixedSizeListArray with length 1.
-    FixedSizeList(ArrayRef),
+    FixedSizeList(Arc<FixedSizeListArray>),
```
Comment (wjones127) [inline datafusion/common/src/scalar.rs:146]: I know I'm coming in a little late, but have we considered instead making the type `Scalar<Arc<FixedSizeListArray>>`? ([Scalar being the one in arrow-rs](https://docs.rs/arrow/latest/arrow/array/struct.Scalar.html)) This would enforce that the length is 1, which might be nice. I could also understand if that makes it too awkward to work with.

**Review by wjones127 — COMMENTED** [review]
This seems acceptable. Like Andrew said I think we could avoid some repetition.

I do think it's worth quickly considering whether wrapping in [Scalar](https://docs.rs/arrow/latest/arrow/array/struct.Scalar.html) might be useful, as right now there isn't any strong enforcement that the array values in these scalars is length 1.

File: datafusion/common/src/scalar.rs (hunk 14 above)
Comment (rspears74) [reply datafusion/common/src/scalar.rs:2465]: Yeah, I tried this, but the args to `List`, `LargeList`, and `FixedSizeList` are all different, so they can't be put in the same match arm.

File: datafusion/common/src/scalar.rs (hunk 15 above)
Comment (rspears74) [reply datafusion/common/src/scalar.rs:146]: Personally I like the enforcement of length 1 (I mentioned this problem initially in the issue I opened), but it does seem to be a bit cumbersome to deal with.

File: datafusion/common/src/scalar.rs (hunk 14 above)
Comment (wjones127) [reply datafusion/common/src/scalar.rs:2465]: Ah I see now. They are now distinct data types. Nevermind.

**Comment by rspears74** [comment]
Not sure why the MSRV check is failing?

File: datafusion/common/src/scalar.rs (hunk 15 above)
Comment (jayzhan211) [reply datafusion/common/src/scalar.rs:146]: I think it is a good idea.

**Comment by alamb** [comment]
> Not sure why the MSRV check is failing?

You may need to merge up from main -- I think this was fixed on main recently

File: datafusion/common/src/scalar.rs (hunk 15 above)
Comment (alamb) [reply datafusion/common/src/scalar.rs:146]: Let's file a follow on ticket for continuing improving the representation of list constants

**Comment by alamb** [comment]
I merged up from main to resolve a merge conflict. Thank you everyone

**Comment by rspears74** [comment]
Thanks @alamb @jayzhan211 @wjones127 for working through this with me!
