### PR TITLE
parquet: Add tests for pruning on Int8/Int16/Int64 columns

### LINKED ISSUE #9777: core/tests/parquet/row_group_pruning.rs is missing tests for Int8/Int16/Int64 columns
### Describe the bug

Only for Int32

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by progval**
[Do not merge this PR, it highlights a bug in Int8 and Int16 columns, through `correct_bloom_filters: false`. See #9779 for a discussion]

## Which issue does this PR close?

Closes #9777.

## What changes are included in this PR?

Generalizes the Int32 tests, using a macro.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you @progval 

> [Do not merge this PR, it highlights a bug in Int8 and Int16 columns, through correct_bloom_filters: false. See https://github.com/apache/arrow-datafusion/issues/9779 for a discussion]

What would you think about merging this PR (but keeping https://github.com/apache/arrow-datafusion/issues/9779  open)?

Then the fix for https://github.com/apache/arrow-datafusion/issues/9779  could just update the tests to set `correct_bloom_filters`?

File: datafusion/core/tests/parquet/row_group_pruning.rs [hunk 1]
```diff
@@ -285,105 +285,187 @@ async fn prune_disabled() {
...
-        .with_expected_errors(Some(0))
-        .with_matched_by_stats(Some(0))
-        .with_pruned_by_stats(Some(0))
-        .with_matched_by_bloom_filter(Some(0))
-        .with_pruned_by_bloom_filter(Some(0))
-        .with_expected_rows(3)
-        .test_row_group_prune()
-        .await;
+macro_rules! int_tests {
+    ($bits:expr, correct_bloom_filters: $correct_bloom_filters:expr) => {
```
Comment (alamb) [inline datafusion/core/tests/parquet/row_group_pruning.rs:289]: It would be nice to add documentation about what these parameters mean, especially correct_bloom_filters

**Comment by progval** [comment]
> What would you think about merging this PR

Makes sense, I guess. I was hoping you would find how to solve #9779, because I can't :)

> (but keeping https://github.com/apache/arrow-datafusion/issues/9779 open)?

Well, it should be removed when fixed, there is no point to keeping it.

**Comment by alamb** [comment]
> > What would you think about merging this PR
> 
> Makes sense, I guess. I was hoping you would find how to solve #9779, because I can't :)
> 
> > (but keeping #9779 open)?
> 
> Well, it should be removed when fixed, there is no point to keeping it.

Agreed. 

For others following along, the issue is upstream in parquet-rs: https://github.com/apache/arrow-datafusion/issues/9779#issuecomment-2016913617

I think what we should do with this PR is to update the comments explaining that the tests now demonstrate there is a bug in DataFusion and link to the upstream issue.

Once the upstream issue is fixed, we can then update the tests / close the false nagatives bug https://github.com/apache/arrow-datafusion/issues/9779

**Comment by alamb** [comment]
As a follow up here, I plan to add the comments explaining what is going on here (and that there are tests that show incorrect results, that are tracked by a ticket) and then merge it in.

**Review by alamb — APPROVED** [review]
Thank you @progval  -- I somehow missed that you had updated this PR. It looks really good to me.

Thanks again. Very much appreciated

**Comment by alamb** [comment]
I merged up from main to make sure we have a clean CI run and then I think we can merge this one in

**Comment by alamb** [comment]
Thanks again @progval
