### PR TITLE
Fix Left join implementation is incorrect for 0 or multiple batches on the right side

### LINKED ISSUE #143: More efficient LEFT join implementation
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11116

Currently, the left join implementation keeps a HashSet<Vec<u8>> to mark each key as visited.

However, a more efficient choice would be to keep a bitmap or a boolean marker for each key or index and mark the row as visited, avoiding unnecessary hashing, copying / memory usage.

This bitmap / marker can be visited at the end of the join, efficiently adding the remaining left rows with no match.

### LINKED ISSUE #235: Failing tests in master: left_join_using and left_join
**Describe the bug**
```
---- left_join_using stdout ----
thread 'left_join_using' panicked at 'assertion failed: `(left == right)`
  left: `[["11", "a", "z"], ["22", "b", "y"], ["33", "c", "NULL"], ["44", "d", "x"]]`,
 right: `[["11", "a", "z"], ["22", "b", "y"], ["44", "d", "x"]]`', datafusion/tests/sql.rs:1252:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- left_join stdout ----
thread 'left_join' panicked at 'assertion failed: `(left == right)`
  left: `[["11", "a", "z"], ["22", "b", "y"], ["33", "c", "NULL"], ["44", "d", "x"]]`,
 right: `[["11", "a", "z"], ["22", "b", "y"], ["44", "d", "x"]]`', datafusion/tests/sql.rs:1221:5
```

**To Reproduce**
Checkout commit `c945b03f3a459a5c15f481f9d52819df56e1090c` and run `cargo test`.

**Expected behavior**
Tests should pass.

**Additional context**
`rustc 1.51.0 (2fd73fabe 2021-03-23)`
Running on my 24 core desktop so perhaps this uncovers a race condition?

### LINKED ISSUE #239: Left join implementation is incorrect for 0 or multiple batches on the right side
**Describe the bug**
Currently the left join generates a null for every row that is not present in the right batch.

However, this is wrong, as there should be no match in all of the right batches.

The current implementation generates extra (left, none) tuples for every batch when there is no match against a left key, and generates no left-side rows if the right side is empty.

To fix it, we need to mark the keys or indexes on the left side as visited and scan the items once at the end to generate the rows without any match. 

**To Reproduce**

Run LEFT join against more 0 or multiple batches. 

**Expected behavior**
The left-side rows are included only once if there is no match.

**Additional context**

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?
Closes #235
Closes #239
Closes #143

 # Rationale for this change
Fixes behavior of left join with regard to multiple batches on the right side and 0 right side batches.

This way it also also likely much faster as it avoids keeping generating / keeping / indexing into a `HashSet` for each right side batch.

# What changes are included in this PR?

* We add a `Vec<bool>` to keep track of left-side rows that didn't match with the right side. (number o left rows bytes extra memory usage for left joins, not that much compared to storing the left side data and hashmap + indices. It could be more memory-efficient by using a bitmap instead.
* Generate rows for any item that is not marked as visited.
* Add some tests for 0 / multiple batches on the right

# Are there any user-facing changes?

Only correctness improvements

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
LGTM. I pulled this branch locally and confirmed that this fixes the failing tests. Thanks,  @Dandandan!

**Review by jorgecarleitao — APPROVED** [review]
Yap, the implementation makes a lot of sense. Thanks a lot @Dandandan !

File: datafusion/src/physical_plan/hash_join.rs [hunk 1]
```diff
@@ -1025,14 +1053,42 @@ impl Stream for HashJoinStream {
                     );
                     self.num_input_batches += 1;
                     self.num_input_rows += batch.num_rows();
-                    if let Ok(ref batch) = result {
+                    if let Ok((ref batch, ref left_side)) = result {
                         self.join_time += start.elapsed().as_millis() as usize;
                         self.num_output_batches += 1;
                         self.num_output_rows += batch.num_rows();
+
+                        if self.join_type == JoinType::Left {
```
Comment (houqp) [inline datafusion/src/physical_plan/hash_join.rs:1061]: nit, I think it would be better to do an explicit match on the join type enum here to exhaust all cases. that way, when we add outer join in the future, the compiler will remind us to update the check here.

**Review by houqp — APPROVED** [review]

File: datafusion/src/physical_plan/hash_join.rs (hunk 1 above)
Comment (Dandandan) [reply datafusion/src/physical_plan/hash_join.rs]: Thanks @houqp I agree, updated the code!

**Comment by Dandandan** [comment]
Merging this when it's green
