### PR TITLE
Partitioning fixes

### LINKED ISSUE #9206: `ExecutionOptions::ignore_subdirectory` skipping hive style partitions
### Describe the bug

In the [documentation](https://docs.rs/datafusion/latest/datafusion/common/config/struct.ExecutionOptions.html#structfield.listing_table_ignore_subdirectory) `ignore_subdirectory` defaults to true, meaning sub directories are skipped, but only if they are not hive partitions. Currently all subdirectories including hive partitions are skipped.

### To Reproduce

```rust
let url = ListingTableUrl::parse("file:///var/data/mytable/").unwrap();

assert!(url.contains(
    &Path::parse("/var/data/mytable/year=2024/data.parquet").unwrap(),
    true
));

```

### Expected behavior

the assertion should pass, but it currently does not

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by esheppa**
## Which issue does this PR close?

Closes #9206.

## Rationale for this change

* Aligns the code behaviour with the documentation

## What changes are included in this PR?

* Altering the `ListingTableUrl::contains` method to skip hive partitions where they appear as a segment in the url
* Makes the `list_all_files` method public to allow users to more easily see what files are being included with the `ListingTableUrl`

## Are these changes tested?

Yes a new test is added to ensure that the changes continue to behave as expected

## Are there any user-facing changes?

* An additional public function on `ListingTableUrl`
* Extra files may be listed for a given `ListingTableUrl` which previously were not included. This could cause query results to change

### CODE REVIEW

**Comment by alamb** [comment]
cc @devinjdangelo

File: datafusion/core/src/datasource/listing/url.rs [hunk 1]
```diff
@@ -234,7 +239,7 @@ impl ListingTableUrl {
     }
 
     /// List all files identified by this [`ListingTableUrl`] for the provided `file_extension`
-    pub(crate) async fn list_all_files<'a>(
+    pub async fn list_all_files<'a>(
```
Comment (comphead) [inline datafusion/core/src/datasource/listing/url.rs:242]: is it related to the PR?

**Comment by alamb** [comment]
Sorry I didn't make it to this PR today -- I plan to review it tomorrow if no one beats me to it

File: datafusion/core/src/datasource/listing/url.rs (hunk 1 above)
Comment (esheppa) [reply datafusion/core/src/datasource/listing/url.rs:242]: I'm happy to separate this out if preferred. I made this change because it allows easier debugging for future users who are unsure which files the `ListingTableUrl` will actually list. This means one can see whether the issue is with the url itself, or another issue

File: datafusion/core/src/datasource/listing/url.rs [hunk 2]
```diff
@@ -189,28 +189,33 @@ impl ListingTableUrl {
...
-                    } else {
-                        let stripped = segments.join("/");
-                        glob.matches(&stripped)
-                    }
+        let Some(all_segments) = self.strip_prefix(path) else {
+            return false;
+        };
+
+        // remove any segments that contain `=` as they are allowed even
+        // when ignore subdirectories is `true`
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/url.rs:197]:
```suggestion
        // when ignore subdirectories is `true`.
        // For example  a directory like `"year=2024"` is a hive
        // partition containing data for the year 2024.
```

**Review by alamb — APPROVED** [review]
Thank you for the contribution @esheppa  --  this change makes sense to me. I think it is well documented and well tested. Nice work.

I had one small comment suggestion but I don't think it is required and we can merge this PR without it. 

Thanks again

File: datafusion/core/src/datasource/listing/url.rs [hunk 3]
```diff
@@ -189,34 +190,39 @@ impl ListingTableUrl {
...
+        let mut segments = all_segments.filter(|s| !s.contains('='));
+
+        match &self.glob {
+            Some(glob) => {
+                if ignore_subdirectory {
+                    segments
+                        .next()
+                        .map_or(false, |file_name| glob.matches(file_name))
+                } else {
+                    let stripped = segments.join(DELIMITER);
```
Comment (esheppa) [inline datafusion/core/src/datasource/listing/url.rs:208]: updated this to use the `DELIMITER` as elsewhere

File: datafusion/core/src/datasource/listing/url.rs (hunk 2 above)
Comment (esheppa) [reply datafusion/core/src/datasource/listing/url.rs]: good call, easy fix

File: datafusion/core/src/datasource/listing/url.rs [hunk 4]
```diff
@@ -189,34 +190,39 @@ impl ListingTableUrl {
...
-                    } else {
-                        true
-                    }
+            }
+            None => {
+                if ignore_subdirectory {
+                    let has_subdirectory = segments.count() > 1;
+                    !has_subdirectory
+                } else {
+                    true
```
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/core/src/datasource/listing/url.rs:217]: Now that you have added the unit test coverage I think it would be fine to change. You could also do as a follow on PR if you prefer

[the remark this answers is not in the document]
Comment (esheppa) [reply datafusion/core/src/datasource/listing/url.rs]: excellent, I've added one more commit

**Comment by alamb** [comment]
Thanks again @esheppa
