### PR TITLE
fix: make `write_csv/json/parquet` cancel-safe

### LINKED ISSUE #5178: `write_csv/json/parquet` isn't cancel safe
**Describe the bug**

`DataFrame::write_csv/json/parquet` isn't cancelling safe due to spawned tasks. See these lines: https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/physical_plan/file_format/csv.rs#L300-L307

It's actually bad because impossible to wrap such functions to `timeout` or `select!` for example.

**To Reproduce**
Wrap it to `select` or `timeout` and check that spawned tasks are still working after cancelling by another branch.

**Expected behavior**

It should be safe-to-cancel these methods.

**Additional context**

Possible ways to fix: 
1) Use stop/cancel token/channel to stop spawned task on drop of outside variable. Like these: [CancellationToken](https://docs.rs/tokio-util/latest/tokio_util/sync/struct.CancellationToken.html)(with drop-guard) or [stop-token](https://crates.io/crates/stop-token)
2) Wrap spawned tasks(i.e `JoinHandle`) to future with `Drop` and call `abort` for them. 

Not sure if there are any other `spawns` which should be covered as well.

### PR DESCRIPTION
**Pull request by DDtKey**
# Which issue does this PR close?

Closes #5178

# Rationale for this change

Currently interruption from outside of datafusion don't stop spawned tasks and it continue to execute query.
It's very helpful to be able to restrict these methods by `timeout` or `select` for example.

# What changes are included in this PR?

# Are these changes tested?

It's quite hard to cover with union-tests and such test could be too flaky (any ideas are welcome). 
However all existed tests are passing successfully. 

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/physical_plan/file_format/csv.rs [hunk 1]
```diff
@@ -286,38 +288,44 @@ pub async fn plan_to_csv(
...
+    if let Err(e) = fs::create_dir(fs_path) {
+        return Err(DataFusionError::Execution(format!(
             "Could not create directory {path}: {e:?}"
-        ))),
+        )));
     }
+
+    let mut tasks = vec![];
+    // Create cancellation-token to interrupt background execution on drop.
+    let cancellation_token = CancellationToken::new();
```
Comment (DDtKey) [inline datafusion/core/src/physical_plan/file_format/csv.rs:299]: Another way is to use abort-on-drop wrapper, I see this pattern is used in datafusion and there are built-in wrapper already. Let me know if you think it would be better

Comment (DDtKey) [reply datafusion/core/src/physical_plan/file_format/csv.rs]: I've decided not to introduce a new pattern here and changed it to `AbortOnDropSingle` per task. 
You still can check how it looked like before: https://github.com/apache/arrow-datafusion/pull/5196/commits/3918d49bf9f130989a61391a3bc45fbe5318a14c

**Comment by DDtKey** [comment]
Another place with similar issue: https://github.com/apache/arrow-datafusion/pull/5197

**Review by alamb — APPROVED** [review]
Thanks @DDtKey  -- I found whitespace blind diff easier to understand what had changed

https://github.com/apache/arrow-datafusion/pull/5196/files?w=1
