### PR TITLE
Ballista: Shuffle write bug fix

### LINKED ISSUE #713: Ballista: ShuffleWriterExec writing to wrong partition
**Describe the bug**
ShuffleWriterExec writes all output partitions to the same file due to a simple bug where the wrong variable is used for the partition number.

**To Reproduce**
Implement a unit test

**Expected behavior**
Use the correct partition number and produce multiple files

**Additional context**
None

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Closes #713 .

 # Rationale for this change

Simple bug fix. Wrong variable was being used for partition number.

# What changes are included in this PR?

# Are there any user-facing changes?

No

### CODE REVIEW

File: ballista/rust/core/src/execution_plans/shuffle_writer.rs [hunk 1]
```diff
@@ -254,13 +254,13 @@ impl ExecutionPlan for ShuffleWriterExec {
...
                         // write batch out
                         let start = Instant::now();
-                        match &mut writers[num_output_partition] {
+                        match &mut writers[output_partition_num] {
                             Some(w) => {
                                 w.write(&output_batch)?;
                             }
                             None => {
                                 let mut path = path.clone();
-                                path.push(&format!("{}", partition));
```
Comment (andygrove) [inline ballista/rust/core/src/execution_plans/shuffle_writer.rs:263]: This is the fix

**Review by alamb — APPROVED** [review]
LGTM
