### PR TITLE
fix: null handling of `ScalarValue::Struct`

### LINKED ISSUE #6083: `ScalarValue::Struct::to_array` has broken NULL handling
### Describe the bug

`ScalarValue::to_array` cannot create true NULL arrays for structs. Instead it creates a struct where all fields are NULL (which is not the same).

### To Reproduce

`ScalarValue::Struct(None, ...).to_array()`

### Expected behavior

The value should be null.

### Additional context

This should just create a NULL array:

https://github.com/apache/arrow-datafusion/blob/26bf31ebbc1274d0f2680d4b944145e794406188/datafusion/common/src/scalar.rs#L2779-L2790

### PR DESCRIPTION
**Pull request by crepererum**
# Which issue does this PR close?
Fixes #6083.

# Rationale for this change
I should be possible to create a truly NULL struct, not only a struct w/ all-NULL members.

# What changes are included in this PR?
Fix NULL handling for `ScalarValue::Struct(None, ...)`.

# Are these changes tested?
1. existing tests pass
2. new test that checks `ScalarValue::to_array` and `ScalarValue::iter_to_array`

# Are there any user-facing changes?
`ScalarValue::Struct(None, ...)` now produces true NULL values that also pass the arrow `is_null` kernel.

### CODE REVIEW

File: datafusion/common/src/scalar.rs [hunk 1]
```diff
@@ -5584,6 +5584,87 @@ mod tests {
         }
     }
 
+    #[test]
```
Comment (comphead) [inline datafusion/common/src/scalar.rs:5587]: That looks good, I checked current impl

```
 select struct(1, 2);
+---------------------------+
| struct(Int64(1),Int64(2)) |
+---------------------------+
| {c0: 1, c1: 2}            |
+---------------------------+
1 row in set. Query took 0.002 seconds.
❯ select struct(null, 2);
+-----------------------+
| struct(NULL,Int64(2)) |
+-----------------------+
| {c0: , c1: 2}         |
+-----------------------+
1 row in set. Query took 0.003 seconds.
❯ select null::struct;
This feature is not implemented: Unsupported SQL type Custom(ObjectName([Ident { value: "struct", quote_style: None }]), [])
```

@crepererum will this fix also address the exception above?

Comment (alamb) [reply datafusion/common/src/scalar.rs:5587]: I ran the same commands on this branch:

```
❯ select struct(1, 2);
+---------------------------+
| struct(Int64(1),Int64(2)) |
+---------------------------+
| {c0: 1, c1: 2}            |
+---------------------------+
1 row in set. Query took 0.002 seconds.
❯ select struct(null, 2);
+-----------------------+
| struct(NULL,Int64(2)) |
+-----------------------+
| {c0: , c1: 2}         |
+-----------------------+
1 row in set. Query took 0.002 seconds.
❯ select null::struct;
This feature is not implemented: Unsupported SQL type Custom(ObjectName([Ident { value: "struct", quote_style: None }]), [])
```

And the results seem the same

**Review by alamb — APPROVED** [review]
Thank you @crepererum
