### PR TITLE
Add support for correlated subqueries & fix all related TPC-H benchmark issues

### LINKED ISSUE #159: TPC-H Query 2
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11520

{{Missing subquery support.}}

{{Full error:}}

{{Error: NotImplemented("Unsupported ast node Subquery(Query \{ with: None, body: Select(Select { distinct: false, top: None, projection: [UnnamedExpr(Function(Function { name: ObjectName([Ident { value: \"min\", quote_style: None }]), args: [Unnamed(Identifier(Ident \{ value: \"ps_supplycost\", quote_style: None }))], over: None, distinct: false }))], from: [TableWithJoins \{ relation: Table { name: ObjectName([Ident { value: \"partsupp\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }, TableWithJoins \{ relation: Table { name: ObjectName([Ident { value: \"supplier\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }, TableWithJoins \{ relation: Table { name: ObjectName([Ident { value: \"nation\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }, TableWithJoins \{ relation: Table { name: ObjectName([Ident { value: \"region\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }], selection: Some(BinaryOp \{ left: BinaryOp { left: BinaryOp { left: BinaryOp { left: BinaryOp { left: Identifier(Ident { value: \"p_partkey\", quote_style: None }), op: Eq, right: Identifier(Ident \{ value: \"ps_partkey\", quote_style: None }) }, op: And, right: BinaryOp \{ left: Identifier(Ident { value: \"s_suppkey\", quote_style: None }), op: Eq, right: Identifier(Ident \{ value: \"ps_suppkey\", quote_style: None }) } }, op: And, right: BinaryOp \{ left: Identifier(Ident { value: \"s_nationkey\", quote_style: None }), op: Eq, right: Identifier(Ident \{ value: \"n_nationkey\", quote_style: None }) } }, op: And, right: BinaryOp \{ left: Identifier(Ident { value: \"n_regionkey\", quote_style: None }), op: Eq, right: Identifier(Ident \{ value: \"r_regionkey\", quote_style: None }) } }, op: And, right: BinaryOp \{ left: Identifier(Ident { value: \"r_name\", quote_style: None }), op: Eq, right: Value(SingleQuotedString(\"EUROPE\")) } }), group_by: [], having: None }), order_by: [], limit: None, offset: None, fetch: None }) in sqltorel")}}

### LINKED ISSUE #160: TPC-H Query 4
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11521

Intervals expressions not yet supported.

See https://github.com/apache/arrow/pull/9434

Error:

Error: NotImplemented("Unsupported Interval Expression with leading_field Some(Month)")

### LINKED ISSUE #163: TPC-H Query 11
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11525

Needs subquery support.

{{Error: NotImplemented("Unsupported ast node Subquery(Query \{ with: None, body: Select(Select { distinct: false, top: None, projection: [UnnamedExpr(BinaryOp { left: Function(Function { name: ObjectName([Ident { value: \"sum\", quote_style: None }]), args: [Unnamed(BinaryOp \{ left: Identifier(Ident { value: \"ps_supplycost\", quote_style: None }), op: Multiply, right: Identifier(Ident \{ value: \"ps_availqty\", quote_style: None }) })], over: None, distinct: false }), op: Multiply, right: Value(Number(\"0.0001\")) })], from: [TableWithJoins \{ relation: Table { name: ObjectName([Ident { value: \"partsupp\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }, TableWithJoins \{ relation: Table { name: ObjectName([Ident { value: \"supplier\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }, TableWithJoins \{ relation: Table { name: ObjectName([Ident { value: \"nation\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }], selection: Some(BinaryOp \{ left: BinaryOp { left: BinaryOp { left: Identifier(Ident { value: \"ps_suppkey\", quote_style: None }), op: Eq, right: Identifier(Ident \{ value: \"s_suppkey\", quote_style: None }) }, op: And, right: BinaryOp \{ left: Identifier(Ident { value: \"s_nationkey\", quote_style: None }), op: Eq, right: Identifier(Ident \{ value: \"n_nationkey\", quote_style: None }) } }, op: And, right: BinaryOp \{ left: Identifier(Ident { value: \"n_name\", quote_style: None }), op: Eq, right: Value(SingleQuotedString(\"GERMANY\")) } }), group_by: [], having: None }), order_by: [], limit: None, offset: None, fetch: None }) in sqltorel")}}

### LINKED ISSUE #168: TPC-H Query 17
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11530

Subquery in (WHERE) expression support is missing.

{{Error: NotImplemented("Unsupported ast node Subquery(Query \{ with: None, body: Select(Select { distinct: false, top: None, projection: [UnnamedExpr(BinaryOp { left: Value(Number(\"0.2\")), op: Multiply, right: Function(Function { name: ObjectName([Ident { value: \"avg\", quote_style: None }]), args: [Unnamed(Identifier(Ident \{ value: \"l_quantity\", quote_style: None }))], over: None, distinct: false }) })], from: [TableWithJoins \{ relation: Table { name: ObjectName([Ident { value: \"lineitem\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }], selection: Some(BinaryOp \{ left: Identifier(Ident { value: \"l_partkey\", quote_style: None }), op: Eq, right: Identifier(Ident \{ value: \"p_partkey\", quote_style: None }) }), group_by: [], having: None }), order_by: [], limit: None, offset: None, fetch: None }) in sqltorel")}}

### LINKED ISSUE #171: TPC-H Query 20
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11533

IN (Subquery) in (WHERE) expression

Error: NotImplemented("Unsupported ast node InSubquery { expr: Identifier(Ident { value: \"s_suppkey\", quote_style: None }), subquery: Query { with: None, body: Select(Select { distinct: false, top: None, projection: [UnnamedExpr(Identifier(Ident { value: \"ps_suppkey\", quote_style: None }))], from: [TableWithJoins { relation: Table { name: ObjectName([Ident { value: \"partsupp\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }], selection: Some(BinaryOp { left: InSubquery { expr: Identifier(Ident { value: \"ps_partkey\", quote_style: None }), subquery: Query { with: None, body: Select(Select { distinct: false, top: None, projection: [UnnamedExpr(Identifier(Ident { value: \"p_partkey\", quote_style: None }))], from: [TableWithJoins { relation: Table { name: ObjectName([Ident { value: \"part\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }], selection: Some(BinaryOp { left: Identifier(Ident { value: \"p_name\", quote_style: None }), op: Like, right: Value(SingleQuotedString(\"forest%\")) }), group_by: [], having: None }), order_by: [], limit: None, offset: None, fetch: None }, negated: false }, op: And, right: BinaryOp { left: Identifier(Ident { value: \"ps_availqty\", quote_style: None }), op: Gt, right: Subquery(Query { with: None, body: Select(Select { distinct: false, top: None, projection: [UnnamedExpr(BinaryOp { left: Value(Number(\"0.5\")), op: Multiply, right: Function(Function { name: ObjectName([Ident { value: \"sum\", quote_style: None }]), args: [Unnamed(Identifier(Ident { value: \"l_quantity\", quote_style: None }))], over: None, distinct: false }) })], from: [TableWithJoins { relation: Table { name: ObjectName([Ident { value: \"lineitem\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }], selection: Some(BinaryOp { left: BinaryOp { left: BinaryOp { left: BinaryOp { left: Identifier(Ident { value: \"l_partkey\", quote_style: None }), op: Eq, right: Identifier(Ident { value: \"ps_partkey\", quote_style: None }) }, op: And, right: BinaryOp { left: Identifier(Ident { value: \"l_suppkey\", quote_style: None }), op: Eq, right: Identifier(Ident { value: \"ps_suppkey\", quote_style: None }) } }, op: And, right: BinaryOp { left: Identifier(Ident { value: \"l_shipdate\", quote_style: None }), op: GtEq, right: TypedString { data_type: Date, value: \"1994-01-01\" } } }, op: And, right: BinaryOp { left: Identifier(Ident { value: \"l_shipdate\", quote_style: None }), op: Lt, right: BinaryOp { left: Value(SingleQuotedString(\"date 1994-01-01\")), op: Plus, right: Value(Interval { value: \"1\", leading_field: Some(Year), leading_precision: None, last_field: None, fractional_seconds_precision: None }) } } }), group_by: [], having: None }), order_by: [], limit: None, offset: None, fetch: None }) } }), group_by: [], having: None }), order_by: [], limit: None, offset: None, fetch: None }, negated: false } in sqltorel")

### LINKED ISSUE #172: TPC-H Query 21
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11534

Fails with error:

Error: NotImplemented("Unsupported compound identifier \'[\"l1\", \"l_suppkey\"]\'")

### LINKED ISSUE #175: TPC-H Query 22
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11543

Fails with parser error for the syntax SUBSTRING(col FROM 1)

### PR DESCRIPTION
**Pull request by avantgardnerio**
# Which issue does this PR close?

Closes #159 
Closes #160 
Closes #163 
Closes #168 
Closes #171 
Closes #172 
Closes #175

 # Rationale for this change

Getting the TPC-H queries to work allows Datafusion users and potential users to compare standard benchmarks to decide if Datafusion is the correct choice for their use case.

# What changes are included in this PR?

3 new query optimizers:

1. decorrelate_scalar_subquery
2. decorrelate_where_exists
3. decorrelate_where_in

pros
- all TPC-H queries pass but 15 (create view, multiple statements) and 21 (error in filter push down)
- it appears to be a generaliz(ed/able) approach to de-correlating subqueries
- it handles things like multiple subqueries per filter, recusive subqueries, correlated and uncorrelated, etc
- with the date stuff merged, it now largely works out of the box

cons
- there is insufficient unit testing - update: I've added a bunch of unit tests, but fuzzing may be required to merge something like this
- ~~the code is verbose,~~ and duplicated - update: it's definitely less verbose, and less duplicated, thoughts on the new methods?
- ~~variables names are hard to understand~~
- it overlaps with `filter_to_join`

# Are there any user-facing changes?

Correlated subqueries should work ~~, but likely some will break or return incorrect results (thus the "draft" status).~~

### CODE REVIEW

File: datafusion/core/tests/sql/subqueries.rs [hunk 1]
```diff
@@ -0,0 +1,398 @@
+use super::*;
```
Comment (andygrove) [inline datafusion/core/tests/sql/subqueries.rs:1]: Need ASF header here

File: datafusion/optimizer/src/optimizer.rs [hunk 2]
```diff
@@ -44,15 +44,23 @@ pub struct OptimizerConfig {
...
         Self {
             query_execution_start_time: chrono::Utc::now(),
+            next_id: 1,
         }
     }
+
+    pub fn next_id(&mut self) -> usize {
+        let id = self.next_id;
+        self.next_id += 1;
+        id
```
Comment (Dandandan) [inline datafusion/optimizer/src/optimizer.rs:62]:
```suggestion
        self.cur_id += 1;
        self.cur_id
```
And start cur_id at 0?

File: datafusion/optimizer/src/optimizer.rs [hunk 3]
```diff
@@ -44,15 +44,23 @@ pub struct OptimizerConfig {
...
     pub query_execution_start_time: DateTime<Utc>,
+    next_id: usize,
 }
 
 impl OptimizerConfig {
     /// Create optimizer config
     pub fn new() -> Self {
         Self {
             query_execution_start_time: chrono::Utc::now(),
+            next_id: 1,
```
Comment (Dandandan) [inline datafusion/optimizer/src/optimizer.rs:55]: This is used for creating a unique alias nr. right? Maybe we can add a comment that it serves this purpose.

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs [hunk 4]
```diff
@@ -0,0 +1,360 @@
...
+                    };
+                    let r_query = match &**right {
+                        Expr::ScalarSubquery(subquery) => Some(subquery.clone()),
+                        _ => None,
+                    };
+                    if l_query.is_none() && r_query.is_none() {
+                        others.push((*it).clone());
+                        continue;
+                    }
+                    for (idx, subquery) in vec![l_query, r_query].iter().enumerate() {
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/decorrelate_scalar_subquery.rs:65]: Since I had to do the same logic to both of them, my IDE was complaining about duplicated code. Perhaps a lambda function is the correct solution here (combined with matching on a tuple - I never thought of that :slightly_smiling_face: )

File: datafusion/optimizer/src/utils.rs [hunk 5]
```diff
@@ -82,6 +85,127 @@ pub fn add_filter(plan: LogicalPlan, predicates: &[&Expr]) -> LogicalPlan {
...
+
+    let right_cols: Vec<_> = joins
+        .iter()
+        .map(|it| &it.1)
+        .map(|it| Column::from(it.as_str()))
+        .collect();
+    let left_cols: Vec<_> = joins
+        .iter()
+        .map(|it| &it.0)
+        .map(|it| Column::from(it.as_str()))
```
Comment (Dandandan) [inline datafusion/optimizer/src/utils.rs:202]: Something like this shoud be possible:
```suggestion
    let (left_cols, right_cols): (Vec<_>, Vec<_>) = joins.into_iter().map(|(l, r)| (l.as_str(), r.as_str())).unzip();
```

File: datafusion/optimizer/src/utils.rs [hunk 6]
```diff
@@ -82,6 +85,127 @@ pub fn add_filter(plan: LogicalPlan, predicates: &[&Expr]) -> LogicalPlan {
...
+    exprs: Vec<&Expr>,
+    schema: &DFSchemaRef,
+) -> (Vec<Expr>, Vec<Expr>) {
+    let fields: HashSet<_> = schema
+        .fields()
+        .iter()
+        .map(|it| it.qualified_name())
+        .collect();
+
+    let (joins, others): (Vec<_>, Vec<_>) = exprs.iter().partition_map(|filter| {
```
Comment (Dandandan) [inline datafusion/optimizer/src/utils.rs:109]: I think it's smart/elegant, but in this case it might be more readable (and avoids the extra dependency) to push into two vecs for the j`oins` / `other` than use `partition_map` + `Either::Right` / `Either::Left`..

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs [hunk 7]
```diff
@@ -0,0 +1,360 @@
...
+    /// Test for correlated scalar subquery filter
+    #[test]
+    fn exists_subquery_correlated() -> Result<()> {
+        let sq = Arc::new(
+            LogicalPlanBuilder::from(test_table_scan_with_name("sq")?)
+                .filter(Expr::BinaryExpr {
+                    left: Box::new(Expr::Column(Column::from("test.a"))),
+                    op: Operator::Eq,
+                    right: Box::new(Expr::Column(Column::from("sq.a"))),
+                })?
```
Comment (andygrove) [inline datafusion/optimizer/src/decorrelate_scalar_subquery.rs:325]: This can be written more concisely:

```suggestion
                .filter(col("test.a").eq(col("sq.a")))?
```

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs [hunk 8]
```diff
@@ -0,0 +1,360 @@
...
+                .project(vec![min(col("c"))])?
+                .build()?,
+        );
+
+        let plan = LogicalPlanBuilder::from(test_table_scan_with_name("test")?)
+            .filter(Expr::BinaryExpr {
+                left: Box::new(Expr::Column(Column::from("test.c"))),
+                op: Operator::Lt,
+                right: Box::new(scalar_subquery(sq))
+            })?
```
Comment (andygrove) [inline datafusion/optimizer/src/decorrelate_scalar_subquery.rs:336]:
```suggestion
            .filter(col("test.c").lt(scalar_subquery(sq)))?
```

File: datafusion/optimizer/src/decorrelate_where_exists.rs [hunk 9]
```diff
@@ -0,0 +1,256 @@
...
+    /// Test for correlated EXISTS subquery filter
+    #[test]
+    fn exists_subquery_correlated() -> Result<()> {
+        let sq = Arc::new(
+            LogicalPlanBuilder::from(test_table_scan_with_name("sq")?)
+                .filter(Expr::BinaryExpr {
+                    left: Box::new(Expr::Column(Column::from("test.a"))),
+                    op: Operator::Eq,
+                    right: Box::new(Expr::Column(Column::from("sq.a")))
+                })?
```
Comment (andygrove) [inline datafusion/optimizer/src/decorrelate_where_exists.rs:230]:
```suggestion
                .filter(col("test.a").eq(col("sq.a")))?
```

File: datafusion/optimizer/src/decorrelate_where_in.rs [hunk 10]
```diff
@@ -0,0 +1,329 @@
...
+    /// Test for correlated IN subquery filter
+    #[test]
+    fn in_subquery_correlated() -> Result<()> {
+        let sq = Arc::new(
+            LogicalPlanBuilder::from(test_table_scan_with_name("sq")?)
+                .filter(Expr::BinaryExpr {
+                    left: Box::new(Expr::Column(Column::from("test.a"))),
+                    op: Operator::Eq,
+                    right: Box::new(Expr::Column(Column::from("sq.a")))
+                })?
```
Comment (andygrove) [inline datafusion/optimizer/src/decorrelate_where_in.rs:252]:
```suggestion
                .filter(col("test.a").eq(col("sq.a")))?
```

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/decorrelate_scalar_subquery.rs]: How does the new version look?

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs (hunk 8 above)
Comment (avantgardnerio) [reply datafusion/optimizer/src/decorrelate_scalar_subquery.rs]: Thanks!!

**Comment by andygrove** [comment]
I think this is looking really good and would be supportive of getting this merged. It adds significant new functionality that we did not have before. If we have any concerns about the new functionality, we could always consider putting it behind a feature flag before we release 11.0.0.

**Comment by alamb** [comment]
I restarted https://github.com/apache/arrow-datafusion/runs/7411688842?check_suite_focus=true which had failed due to "no space left on device"

File: benchmarks/queries/q20.sql [hunk 11]
```diff
@@ -28,7 +28,7 @@ where
                     l_partkey = ps_partkey
               and l_suppkey = ps_suppkey
               and l_shipdate >= date '1994-01-01'
-              and l_shipdate < 'date 1994-01-01' + interval '1' year
+              and l_shipdate < date '1994-01-01' + interval '1' year
```
Comment (alamb) [inline benchmarks/queries/q20.sql:31]: I don't understand what changed here 🤷

File: datafusion/common/src/error.rs [hunk 12]
```diff
@@ -83,6 +83,30 @@ pub enum DataFusionError {
     #[cfg(feature = "jit")]
     /// Error occurs during code generation
     JITError(ModuleError),
+    /// Error with context
```
Comment (alamb) [inline datafusion/common/src/error.rs:86]:
```suggestion
    /// Error with additional context
```

I am +0 on this change (as in I don't oppose it but I also would be fine without it) 

I can see the usecase (to keep the structure of nested errors), however there are other more structured approaches to Error handling (e.g https://crates.io/crates/snafu or https://crates.io/crates/thiserror), but so far DataFusion just uses string handling (aka `format!("Error processing subqueries: {}", inner_error)`);

Other libraries have quite sophisticated  `Error` hierarchies which theoretically allow the errors to be programmatically handled in different ways.  It adds non trivial maintenance and contribution overhead,  and I haven't seen anyone ask for this yet in DataFusion so I don't think it is worth adding yet.

File: datafusion/common/src/error.rs [hunk 13]
```diff
@@ -83,6 +83,30 @@ pub enum DataFusionError {
...
+    ($desc:expr, $err:expr) => {
+        datafusion_common::DataFusionError::Context(
+            format!("{} at {}:{}", $desc, file!(), line!()),
+            Box::new($err),
+        )
+    };
+}
+
+#[macro_export]
+macro_rules! plan_err {
```
Comment (alamb) [inline datafusion/common/src/error.rs:101]: This is a nice improvement

File: datafusion/core/tests/sql/subqueries.rs [hunk 14]
```diff
@@ -0,0 +1,461 @@
...
+
+use super::*;
+use crate::sql::execute_to_batches;
+use datafusion::assert_batches_eq;
+use datafusion::prelude::SessionContext;
+use log::debug;
+
+#[cfg(test)]
+#[ctor::ctor]
+fn init() {
```
Comment (alamb) [inline datafusion/core/tests/sql/subqueries.rs:26]: TIL `ctor`. That is quite cool 👍

File: datafusion/core/tests/sql/mod.rs [hunk 15]
```diff
@@ -499,6 +537,77 @@ async fn register_tpch_csv(ctx: &SessionContext, table: &str) -> Result<()> {
     Ok(())
 }
 
+async fn register_tpch_csv_data(
+    ctx: &SessionContext,
+    table_name: &str,
+    data: &str,
+) -> Result<()> {
+    let schema = Arc::new(get_tpch_table_schema(table_name));
```
Comment (alamb) [inline datafusion/core/tests/sql/mod.rs:545]: What do you think about using `SessionContext::register_csv` here instead? Is there some reason we need to explicitly parse the CSV file and build in memory tables?


https://docs.rs/datafusion/10.0.0/datafusion/execution/context/struct.SessionContext.html#method.register_csv

File: datafusion/core/tests/sql/subqueries.rs [hunk 16]
```diff
@@ -0,0 +1,461 @@
...
+    let actual = format!("{}", plan.display_indent());
+    let expected = r#"Sort: #customer.c_custkey ASC NULLS LAST
+  Projection: #customer.c_custkey
+    Filter: #customer.c_acctbal < #__sq_2.__value
+      Inner Join: #customer.c_custkey = #__sq_2.o_custkey
+        TableScan: customer projection=[c_custkey, c_acctbal]
+        Projection: #orders.o_custkey, #SUM(orders.o_totalprice) AS __value, alias=__sq_2
+          Aggregate: groupBy=[[#orders.o_custkey]], aggr=[[SUM(#orders.o_totalprice)]]
+            Filter: #orders.o_totalprice < #__sq_1.__value
+              Inner Join: #orders.o_orderkey = #__sq_1.l_orderkey
```
Comment (alamb) [inline datafusion/core/tests/sql/subqueries.rs:61]: 👍  for this plan. Very cool @avantgardnerio

File: benchmarks/queries/q20.sql (hunk 11 above)
Comment (avantgardnerio) [reply benchmarks/queries/q20.sql:31]: There was a syntax error regarding placement of the quotation mark.

File: datafusion/core/tests/sql/subqueries.rs [hunk 17]
```diff
@@ -0,0 +1,461 @@
...
+    let sql = r#"select o_orderkey from orders
+inner join lineitem on o_orderkey = l_orderkey
+where l_partkey in ( select ps_partkey from partsupp where ps_suppkey = l_suppkey );"#;
+
+    // assert plan
+    let plan = ctx.create_logical_plan(sql).unwrap();
+    let plan = ctx.optimize(&plan).unwrap();
+    let actual = format!("{}", plan.display_indent());
+    let expected = r#"Projection: #orders.o_orderkey
+  Semi Join: #lineitem.l_partkey = #__sq_1.ps_partkey, #lineitem.l_suppkey = #__sq_1.ps_suppkey
```
Comment (alamb) [inline datafusion/core/tests/sql/subqueries.rs:88]: 👍

File: datafusion/core/tests/sql/subqueries.rs [hunk 18]
```diff
@@ -0,0 +1,461 @@
...
+      TableScan: orders projection=[o_orderkey]
+      TableScan: lineitem projection=[l_orderkey, l_partkey, l_suppkey]
+    Projection: #partsupp.ps_partkey AS ps_partkey, #partsupp.ps_suppkey AS ps_suppkey, alias=__sq_1
+      TableScan: partsupp projection=[ps_partkey, ps_suppkey]"#
+        .to_string();
+    assert_eq!(actual, expected);
+
+    // assert data
+    let results = execute_to_batches(&ctx, sql).await;
+    let expected = vec!["++", "++"];
```
Comment (alamb) [inline datafusion/core/tests/sql/subqueries.rs:99]: Is it correct that there is no data?

File: datafusion/core/tests/sql/subqueries.rs [hunk 19]
```diff
@@ -0,0 +1,461 @@
...
+    )
+order by s_acctbal desc, n_name, s_name, p_partkey;"#;
+
+    // assert plan
+    let plan = ctx.create_logical_plan(sql).unwrap();
+    let plan = ctx.optimize(&plan).unwrap();
+    let actual = format!("{}", plan.display_indent());
+    let expected = r#"Sort: #supplier.s_acctbal DESC NULLS FIRST, #nation.n_name ASC NULLS LAST, #supplier.s_name ASC NULLS LAST, #part.p_partkey ASC NULLS LAST
+  Projection: #supplier.s_acctbal, #supplier.s_name, #nation.n_name, #part.p_partkey, #part.p_mfgr, #supplier.s_address, #supplier.s_phone, #supplier.s_comment
+    Filter: #partsupp.ps_supplycost = #__sq_1.__value
```
Comment (alamb) [inline datafusion/core/tests/sql/subqueries.rs:131]: So cool to see this query planned ❤️

File: datafusion/core/tests/sql/subqueries.rs [hunk 20]
```diff
@@ -0,0 +1,461 @@
...
+        group by o_orderpriority
+        order by o_orderpriority;
+        "#;
+
+    // assert plan
+    let plan = ctx.create_logical_plan(sql).unwrap();
+    let plan = ctx.optimize(&plan).unwrap();
+    let actual = format!("{}", plan.display_indent());
+    let expected = r#"Sort: #orders.o_orderpriority ASC NULLS LAST
+  Projection: #orders.o_orderpriority, #COUNT(UInt8(1)) AS order_count
```
Comment (alamb) [inline datafusion/core/tests/sql/subqueries.rs:194]: 👍

File: datafusion/core/tests/sql/subqueries.rs [hunk 21]
```diff
@@ -0,0 +1,461 @@
...
+        .create_logical_plan(sql)
+        .map_err(|e| format!("{:?} at {}", e, "error"))
+        .unwrap();
+    let plan = ctx
+        .optimize(&plan)
+        .map_err(|e| format!("{:?} at {}", e, "error"))
+        .unwrap();
+    let actual = format!("{}", plan.display_indent());
+    let expected = r#"Sort: #supplier.s_name ASC NULLS LAST
+  Projection: #supplier.s_name, #supplier.s_address
```
Comment (alamb) [inline datafusion/core/tests/sql/subqueries.rs:311]: 👍

File: datafusion/core/tests/sql/subqueries.rs [hunk 22]
```diff
@@ -0,0 +1,461 @@
...
+        .unwrap();
+    let actual = format!("{}", plan.display_indent());
+    let expected = r#"Sort: #custsale.cntrycode ASC NULLS LAST
+  Projection: #custsale.cntrycode, #COUNT(UInt8(1)) AS numcust, #SUM(custsale.c_acctbal) AS totacctbal
+    Aggregate: groupBy=[[#custsale.cntrycode]], aggr=[[COUNT(UInt8(1)), SUM(#custsale.c_acctbal)]]
+      Projection: #custsale.cntrycode, #custsale.c_acctbal, alias=custsale
+        Projection: substr(#customer.c_phone, Int64(1), Int64(2)) AS cntrycode, #customer.c_acctbal, alias=custsale
+          Filter: #customer.c_acctbal > #__sq_1.__value
+            CrossJoin:
+              Anti Join: #customer.c_custkey = #orders.o_custkey
```
Comment (alamb) [inline datafusion/core/tests/sql/subqueries.rs:376]: looks good

File: datafusion/core/tests/sql/subqueries.rs [hunk 23]
```diff
@@ -0,0 +1,461 @@
...
+        .unwrap();
+    println!("before:\n{}", plan.display_indent());
+    let plan = ctx
+        .optimize(&plan)
+        .map_err(|e| format!("{:?} at {}", e, "error"))
+        .unwrap();
+    let actual = format!("{}", plan.display_indent());
+    println!("after:\n{}", actual);
+    let expected = r#"Sort: #value DESC NULLS FIRST
+  Projection: #partsupp.ps_partkey, #SUM(partsupp.ps_supplycost * partsupp.ps_availqty) AS value
```
Comment (alamb) [inline datafusion/core/tests/sql/subqueries.rs:434]: 👍

File: datafusion/expr/src/expr.rs [hunk 24]
```diff
@@ -452,6 +452,13 @@ impl Expr {
             nulls_first,
         }
     }
+
+    pub fn try_into_col(&self) -> Result<Column> {
+        match self {
+            Expr::Column(it) => Ok(it.clone()),
+            _ => plan_err!("Could not coerce into Column!"),
```
Comment (alamb) [inline datafusion/expr/src/expr.rs:459]: it might help to include `self` in this error so it is clear what expr is causing issues

like:

```suggestion
            _ => plan_err!("Could not coerce '{}' into Column", self),
```

File: datafusion/expr/src/logical_plan/plan.rs [hunk 25]
```diff
@@ -1074,6 +1074,13 @@ impl Projection {
             alias,
         })
     }
+
+    pub fn try_from_plan(plan: &LogicalPlan) -> datafusion_common::Result<&Projection> {
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:1078]: For what it is worth, I think a more rust idiomatic way would be to `impl std::convert::TryInto`

https://doc.rust-lang.org/std/convert/trait.TryInto.html

However, I think this way is also fine

**Review by alamb — COMMENTED** [review]
Nice work @avantgardnerio  -- I think this PR is looking quite fine. 

I reviewed the plans carefully. They look good to me 👌 

I haven't had a chance to completely review the rest of this PR (aka the meat of the optimizer decorrelations) but I will try and finish today sometime

File: datafusion/common/src/error.rs (hunk 12 above)
Comment (avantgardnerio) [reply datafusion/common/src/error.rs:86]: I would +1 any solution that allows nested errors (our own, or off-the-shelf). This was inspired by heavily commented code like:

```
    let subqry_input = only_or_err(subqry_inputs.as_slice()); // correlated where in subqueries must project a single expression
```

Turning into something that also benefits the user when it breaks like:

```
    let subqry_input = only_or_err(subqry_inputs.as_slice())
        .map_err(|e| context!("single expression projection required", e))?;
```

With the `context!` macro providing the relevant information about which optimizer was being run, and turned the error from `more than one item found in list!` into `"single expression projection required in decorrelate_where_in line 123" caused by "more than one item found in list!"` which seemed like a much better user experience.

File: datafusion/common/src/error.rs (hunk 13 above)
Comment (avantgardnerio) [reply datafusion/common/src/error.rs:101]: Thanks! Think we should add file and line? or leave as it is?

File: datafusion/core/tests/sql/subqueries.rs (hunk 14 above)
Comment (avantgardnerio) [reply datafusion/core/tests/sql/subqueries.rs:26]: Logging has been a challenge:
1. need to add `--nocapture` to tests to see log statements
2. need to add `RUST_LOG=debug` environment variable
3. need to init the logger

This prevented me from accidentally checking in `println!()` statements.

File: datafusion/expr/src/logical_plan/plan.rs (hunk 25 above)
Comment (avantgardnerio) [reply datafusion/expr/src/logical_plan/plan.rs:1078]: I started with that, but ran into borrow checker / trait issues with returning a reference, vs cloning the underlying data (I'm sure I could have gotten it to work with a clone). I was thinking that maybe this method should be called `try_from_plan_ref` in order to differentiate it from any future non-ref version. 50% of this PR was just trying to de-verbosify those plan re-writers into something that was readable and fit on a page.

**Comment by avantgardnerio** [comment]
> I haven't had a chance to completely review the rest of this PR (aka the meat of the optimizer decorrelations) but I will try and finish today sometime

Thanks so much @alamb ! It's really reassuring to get feedback on this :raised_hands:

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs [hunk 26]
```diff
@@ -0,0 +1,704 @@
...
+    }
+
+    fn name(&self) -> &str {
+        "decorrelate_scalar_subquery"
+    }
+}
+
+/// Takes a query like:
+///
+/// ```select id from customers where balance > (select avg(total) from orders)```
```
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/optimizer/src/decorrelate_scalar_subquery.rs:138]: and in fact I think that is what the code below does (handles correlated queries)

File: datafusion/optimizer/src/decorrelate_where_exists.rs [hunk 27]
```diff
@@ -0,0 +1,558 @@
...
+                .filter(col("customer.c_custkey").eq(col("orders.o_custkey")))?
+                .build()?,
+        );
+
+        let plan = LogicalPlanBuilder::from(scan_tpch_table("customer"))
+            .filter(exists(sq))?
+            .project(vec![col("customer.c_custkey")])?
+            .build()?;
+
+        let expected = r#"Could not coerce into Filter!"#;
```
Comment (alamb) [inline datafusion/optimizer/src/decorrelate_where_exists.rs:422]: I think this error would be hard to understand as a user, for what it is worth

**Review by alamb — APPROVED** [review]
Thanks again @avantgardnerio  -- I basically think this PR is good enough to go in and we can iterate from there. I can't claim to have reviewed every line in exacting detail but I have reviewed the tests carefully and the structure of the code looks solid to me. 

Thus I recommend merging it and fixing any items as a follow on because:

1. This PR is extremely well tested in my opinion (which makes follow on changes much easier to evaluate and get in)
2. This PR is already pretty massive and long lived.
3. Supporting the full breadth of TPCH is awesome
4. any potential bugs in the implementation will only affect queries with correlated subqueries (which don't run today), which seems like a reasonable improvement to me (as in this PR does not introduce any regressions

Items I think are worth considering in follow on PRs:
1. Removing `DataFusionError::Context`
2. Fixing check for `has_disjunction`

I also left some various suggestions which I think are worth checking out but also not strictly necessary to fix prior to merge. 

Let me know what you want to do. And thanks again!

**Comment by alamb** [comment]
BTW I have filed https://github.com/apache/arrow-datafusion/issues/2947 for the CI failure and am looking into it

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs (hunk 26 above)
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/decorrelate_scalar_subquery.rs:138]: Correct, uncorrelated scalar subqueries were a TODO, unless you think it's out of scope for these optimizers. (certainly we should rename them if so).

Full disclosure, `decorrelate_where_in.rs` does some uncorrelated queries as well: https://github.com/spaceandtimelabs/arrow-datafusion/blob/563d87d1c6413e611894619c2bc472b396d75c3d/datafusion/optimizer/src/decorrelate_where_in.rs#L166

(I ran into TPC-H errors before I extended it).

File: datafusion/optimizer/src/decorrelate_where_exists.rs (hunk 27 above)
Comment (avantgardnerio) [reply datafusion/optimizer/src/decorrelate_where_exists.rs:422]: `DataFusionError::Context` told the user that it was in `decorrelate_where_exists.rs` and some other helpful info, but I'm happy to remove it and update the expectations. I'll go ahead and do that.

File: datafusion/optimizer/src/utils.rs [hunk 28]
```diff
@@ -65,6 +67,41 @@ pub fn split_conjunction<'a>(predicate: &'a Expr, predicates: &mut Vec<&'a Expr>
...
+                if has_disjunction(&[&**left, &**right]) {
+                    return true;
+                }
+            }
+            Expr::Alias(expr, _) => {
+                if has_disjunction(&[&**expr]) {
+                    return true;
+                }
+            }
+            _ => {}
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/utils.rs:99]: Thanks! I was worried I'd miss something with that code, and I didn't know about `ExpressionVisitor`... I'll switch over :+1:

**Comment by alamb** [comment]
I think if you rebase from master to pick up https://github.com/apache/arrow-datafusion/pull/2948 your CI should pass cleanly

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs (hunk 26 above)
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/optimizer/src/decorrelate_scalar_subquery.rs:138]: I was just pointing out that the comment seemed incorrect. The code looked great

File: datafusion/common/src/error.rs (hunk 13 above)
Comment (alamb) [reply datafusion/common/src/error.rs:101]: I think the macro adding file and line is good

File: datafusion/expr/src/logical_plan/plan.rs (hunk 25 above)
Comment (alamb) [reply datafusion/expr/src/logical_plan/plan.rs:1078]: I think it is fine as is

File: datafusion/optimizer/src/decorrelate_where_exists.rs (hunk 27 above)
Comment (alamb) [reply datafusion/optimizer/src/decorrelate_where_exists.rs:422]: This way is fine too

Comment (avantgardnerio) [reply datafusion/optimizer/src/decorrelate_where_exists.rs]: The assertion matches any subset of the error message. I updated it to `cannot optimize non-correlated subquery`, the full message is:

```
cannot optimize non-correlated subquery at datafusion/optimizer/src/decorrelate_where_exists.rs:141
caused by
Error during planning: Could not coerce into Filter! at datafusion/expr/src/logical_plan/plan.rs:1117
```

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs [hunk 29]
```diff
@@ -0,0 +1,704 @@
...
+                                self.optimize(&*subquery.subquery, optimizer_config)?;
+                            let subquery = Arc::new(subquery);
+                            let subquery = Subquery { subquery };
+                            let res = SubqueryInfo::new(subquery, expr, *op, lhs);
+                            subqueries.push(res);
+                            Ok(())
+                        };
+                    recurse(l_query, (**right).clone(), false)?;
+                    recurse(r_query, (**left).clone(), true)?;
+                    // TODO: if subquery doesn't get optimized, optimized children are lost
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/decorrelate_scalar_subquery.rs:80]: It is... that was one of the big things I was wondering if we should address before merging or not. Honestly, the recursiveness here is both hard to keep in my head, and difficult to follow in the debugger, much less create the right test cases for.

It's excellent that @andygrove 's change allows us to just `?` out on a failure, but cases like this where some recursive optimization has _already_ occurred prevent it's use in every situation.

File: datafusion/optimizer/src/decorrelate_where_in.rs [hunk 30]
```diff
@@ -0,0 +1,695 @@
...
+                    negated,
+                } => {
+                    let subquery =
+                        self.optimize(&*subquery.subquery, optimizer_config)?;
+                    let subquery = Arc::new(subquery);
+                    let subquery = Subquery { subquery };
+                    let subquery =
+                        SubqueryInfo::new(subquery.clone(), (**expr).clone(), *negated);
+                    subqueries.push(subquery);
+                    // TODO: if subquery doesn't get optimized, optimized children are lost
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/decorrelate_where_in.rs:70]: To be clear, what will happen is:

1. a recursive subquery was optimized (or not)
2. it returned up the call stack to this parent `Filter`
3. this one couldn't figure out what to do, so returns an `Err`
4. the `Err` is caught by @andygrove 's recent change
5. this optimizer is ignored
6. either another one down the chain _does_ handle it, or we are no worse off than we were before the PR and the query fails to plan

What should really happen is that if any recursive optimization _may_ have succeeded, then the parent should at minimum return that plan - it's a bit of a testing nightmare.

File: datafusion/optimizer/src/utils.rs [hunk 31]
```diff
@@ -82,6 +119,199 @@ pub fn add_filter(plan: LogicalPlan, predicates: &[&Expr]) -> LogicalPlan {
...
+        }
+        if !fields.contains(&left.flat_name()) && !fields.contains(&right.flat_name()) {
+            others.push((*filter).clone());
+            continue; // neither column present (syntax error?)
+        }
+        match op {
+            Operator::Eq => {}
+            Operator::NotEq => {}
+            _ => {
+                plan_err!(format!("can't optimize {} column comparison", op))?;
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/utils.rs:179]: I left this in because there were tests for the `Eq` and `NotEq` cases, and since errors just skip the optimization, I thought better to fail until we have clearer test cases... You're probably right? To make it harder, this code is shared across all three new optimization rules. It's probably fine for `SEMI` and `ANTI` join, but I do worry about accidentally expanding row count or worse with the scalar `inner` and `outer` joins.

File: datafusion/core/tests/sql/subqueries.rs (hunk 18 above)
Comment (avantgardnerio) [reply datafusion/core/tests/sql/subqueries.rs:99]: BTW, that is super easy to do now, with the `register_tpch_csv_data()` methods.

Comment (avantgardnerio) [reply datafusion/core/tests/sql/subqueries.rs:107]: Correction, you found a bug, thank you! I've pushed a test that catches it and I'll fix it tomorrow.

File: datafusion/optimizer/src/utils.rs [hunk 32]
```diff
@@ -82,6 +119,199 @@ pub fn add_filter(plan: LogicalPlan, predicates: &[&Expr]) -> LogicalPlan {
...
+/// # Arguments
+///
+/// * `a` - A slice of Columns
+/// * `b` - A slice of Columns
+///
+/// # Return value
+///
+/// The deduplicated union of the two slices
+pub fn merge_cols(a: &[Column], b: &[Column]) -> Vec<Column> {
+    let a: Vec<_> = a.iter().map(|it| it.flat_name()).collect();
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/utils.rs]: Updated. It's efficient now, but ugly.

**Comment by alamb** [comment]
Any last thoughts @Dandandan @andygrove ?

**Comment by Dandandan** [comment]
Thanks for the implementation @avantgardnerio awesome addition to DataFusion 😎

File: datafusion/optimizer/src/utils.rs [hunk 33]
```diff
@@ -82,6 +119,199 @@ pub fn add_filter(plan: LogicalPlan, predicates: &[&Expr]) -> LogicalPlan {
...
+///
+/// * `slice` - The slice to extract from
+///
+/// # Return value
+///
+/// The first element, or an error
+pub fn only_or_err<T>(slice: &[T]) -> Result<&T> {
+    match slice {
+        [it] => Ok(it),
+        [] => Err(DataFusionError::Plan("Empty slice!".to_string())),
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/utils.rs]: This could be user facing in cases like:

```
select * from customer where balance < (select subtotal, total from orders where XXX)
```

Which would result in the error:

```
exactly one expression should be projected at decorrelate_scalar_subquery.rs:168 caused by More than one item found!
```
(updated inner error on my last commit)

If there's disagreement I can break this PR in two and return a generic error for now, and a separate PR with the context added back in. In the future I will try harder to keep PRs smaller.

File: datafusion/optimizer/src/utils.rs [hunk 34]
```diff
@@ -82,6 +119,199 @@ pub fn add_filter(plan: LogicalPlan, predicates: &[&Expr]) -> LogicalPlan {
...
+                    others.push((*filter).clone());
+                    continue;
+                }
+            }
+            _ => plan_err!("Invalid expression!".to_string())?,
+        }
+        let left = match left {
+            Expr::Column(c) => c,
+            _ => plan_err!("Invalid expression!".to_string())?,
+        };
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/utils.rs]: I've updated to a better error message. I don't think we can panic here, since this could be a valid query but one we just don't know how to optimize (yet).

File: datafusion/optimizer/src/utils.rs [hunk 35]
```diff
@@ -82,6 +119,199 @@ pub fn add_filter(plan: LogicalPlan, predicates: &[&Expr]) -> LogicalPlan {
...
+        let right = match right {
+            Expr::Column(c) => c,
+            _ => plan_err!("Invalid expression!".to_string())?,
+        };
+        let sorted = if fields.contains(&left.flat_name()) {
```
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/utils.rs:230]: I believe them to be, based upon my knowledge of the system, but I agree we can get this merged and if we encounter failing cases we can add tests and resolve, as the PR has already grown quite long-lived (apologies).

File: datafusion/optimizer/src/utils.rs (hunk 28 above)
[the remark this answers is not in the document]
Comment (avantgardnerio) [reply datafusion/optimizer/src/utils.rs:99]: Resolved by latest commit.

**Comment by avantgardnerio** [comment]
I think all the items listed as critical are now resolved.

File: datafusion/optimizer/src/utils.rs [hunk 36]
```diff
@@ -75,31 +76,30 @@ pub fn split_conjunction<'a>(predicate: &'a Expr, predicates: &mut Vec<&'a Expr>
...
-                }
-            }
-            Expr::Alias(expr, _) => {
-                if has_disjunction(&[&**expr]) {
-                    return true;
+/// A PlanError if a disjunction is found
+pub fn verify_not_disjunction(predicates: &[&Expr]) -> Result<()> {
+    struct DisjunctionVisitor {}
+
+    impl ExpressionVisitor for DisjunctionVisitor {
```
Comment (alamb) [inline datafusion/optimizer/src/utils.rs:83]: 👍

**Review by alamb — APPROVED** [review]
Unless there are any other comments, I'll plan to merge this PR tomorrow

File: datafusion/optimizer/src/decorrelate_scalar_subquery.rs (hunk 29 above)
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/optimizer/src/decorrelate_scalar_subquery.rs:81]: I think in the general case it is unavoidable that if an optimization errors after succeeding only part way it has to bail out entirely. Some rewrites such as this one might be able to proceed, but some maintain state (e.g. FilterPushDown)

File: datafusion/optimizer/src/decorrelate_where_in.rs (hunk 30 above)
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/optimizer/src/decorrelate_where_in.rs:70]: I see what you are saying now -- that on error we potentially lose some work we might have been able to salvage. 

I agree that trying to handle this case gracefully is somewhat unecessary (as it shouldn't be happening anyways -- so we can perhaps focus our efforts on fixing the real issue)

File: datafusion/core/tests/sql/subqueries.rs (hunk 18 above)
Comment (alamb) [reply datafusion/core/tests/sql/subqueries.rs]: 🎉 🦜

**Comment by alamb** [comment]
Thanks again @avantgardnerio
