### PR TITLE
Extended datatypes & signatures support for `NULLIF` function

### LINKED ISSUE #4205: Nullif func states support for Boolean type, but fails if this is attempted
**Describe the bug**
The nullif() reports that it supports Boolean arguments, but calling it with boolean arguments results in an internal error.

The message here suggests that Boolean is supported (When nullif is called with different unsupported types):
```
execute sql "select nullif('A', 'B')"
>> Error during planning: Coercion from [Utf8, Utf8] to the signature Uniform(2, [Boolean, UInt8, UInt16, UInt32, UInt64, Int8, Int16, Int32, Int64, Float32, Float64]) failed.
```

**To Reproduce**
evaluate:  `SELECT nullif(1=2, FALSE)`

```
execute sql "select nullif(1 = 2, FALSE)"
>> External error: Internal error: Unsupported data type Boolean for NULLIF/primitive/boolean operator. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

**Expected behavior**
Either Boolean is not listed as supported argument type, or the nullif() function performs as expected.

**Additional context**

So, it seems like Boolean is included in this list:

https://github.com/apache/arrow-datafusion/blob/d72b4f04cf12424a54b22bf376b87065d5fcb6aa/datafusion/expr/src/nullif.rs#L23

But in the match pattern here: 

https://github.com/apache/arrow-datafusion/blob/d72b4f04cf12424a54b22bf376b87065d5fcb6aa/datafusion/physical-expr/src/expressions/nullif.rs#L46

It's not.

The underlying Arrow function does not support non-primitive array types in 0.26, but has recently been updated and in 0.27 now appears to:

https://github.com/apache/arrow-rs/commit/3a90654f4cb98ac7fe278991a6cbc11384664e2e

So I guess it's a case of waiting for the arrow dependency version to be bumped, but then the additional type(s) should probably be added in the datafusion files.

### PR DESCRIPTION
**Pull request by korowa**
# Which issue does this PR close?

Closes #4205 .

# Rationale for this change

Adding more options to call `NULLIF` in terms of signatures and inputs.

# What changes are included in this PR?

1) Calling arrow `compute::nullif` without intermediate type checking
2) String typed inputs now allowed as `NULLIF` arguments
3) Added support for literal as first argument for both Scalar-Array and Scalar-Scalar cases

# Are these changes tested?

Unit tests for nullif_func added

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/nullif.rs [hunk 1]
```diff
@@ -15,52 +15,14 @@
...
 use arrow::compute::eq_dyn;
 use arrow::compute::nullif::nullif;
-use arrow::datatypes::DataType;
-use datafusion_common::{cast::as_boolean_array, DataFusionError, Result};
+use datafusion_common::{cast::as_boolean_array, DataFusionError, Result, ScalarValue};
 use datafusion_expr::ColumnarValue;
 
 use super::binary::array_eq_scalar;
 
-/// Invoke a compute kernel on a primitive array and a Boolean Array
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/nullif.rs:30]: 😍 

Thank you for this cleanup!

File: datafusion/physical-expr/src/expressions/nullif.rs [hunk 2]
```diff
@@ -88,17 +50,34 @@ pub fn nullif_func(args: &[ColumnarValue]) -> Result<ColumnarValue> {
...
+
+            let array = nullif(&lhs, as_boolean_array(&cond_array)?)?;
             Ok(ColumnarValue::Array(array))
         }
-        _ => Err(DataFusionError::NotImplemented(
-            "nullif does not support a literal as first argument".to_string(),
-        )),
+        (ColumnarValue::Scalar(lhs), ColumnarValue::Scalar(rhs)) => {
+            let val = match lhs.eq(rhs) {
+                true => ScalarValue::Null,
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/nullif.rs:66]: I wonder if this should actually be `ScalarValue::Boolean(None)` (aka a typed boolean null, rather than `DataType::Null` 🤔 )

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @korowa 

One thing that might be helpful is to add some sql level tests, perhaps in the new sqllogictest
Or in new https://github.com/apache/arrow-datafusion/tree/master/datafusion/core/tests/sqllogictests

perhaps in https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/tests/sqllogictests/test_files/select.slt?

File: datafusion/physical-expr/src/expressions/nullif.rs (hunk 2 above)
Comment (korowa) [reply datafusion/physical-expr/src/expressions/nullif.rs]: Nice catch, thank you!

Fixed scalar-scalar case to return empty value with data type inherited from first argument, also added .slt for nullif

File: datafusion/core/tests/sqllogictests/test_files/nullif.slt [hunk 3]
```diff
@@ -0,0 +1,98 @@
+# Licensed to the Apache Software Foundation (ASF) under one
```
Comment (alamb) [inline datafusion/core/tests/sqllogictests/test_files/nullif.slt:1]: ❤️

**Review by alamb — APPROVED** [review]
