### PR TITLE
change the input_type parameter of the create_udaf function from DataType to Vec<DataType>

### LINKED ISSUE #7094: change the input_type parameter of the create_udaf function from DataType to Vec<DataType>
### Describe the bug

For someone who is new to DataFusion and is trying to write a custom UDAF, it may be a little confusing to understand why `create_udaf` only takes one `DataType` for the input_type. Additionally, I did not find any examples demonstrating how to create a UDAF with multiple input arguments.

https://github.com/apache/arrow-datafusion/blob/52cf58b46133d448e067455baab0faf8a50e565a/datafusion/expr/src/expr_fn.rs#L802-L809

### To Reproduce

_No response_

### Expected behavior

change `input_type: DataType` to `input_type: Vec<DataType>`
```
pub fn create_udaf(
    name: &str,
    
    return_type: Arc<DataType>,
    volatility: Volatility,
    accumulator: AccumulatorFactoryFunction,
    state_type: Arc<Vec<DataType>>,
) -> AggregateUDF {
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jiangzhx**
# Which issue does this PR close?
Closes #7094 .

# Rationale for this change

For someone who is new to DataFusion and is trying to write a custom UDAF, it may be a little confusing to understand why create_udaf only takes one DataType for the input_type. Additionally, I did not find any examples demonstrating how to create a UDAF with multiple input arguments.

# What changes are included in this PR?

change `input_type: DataType` to `input_type: Vec<DataType>`
```
pub fn create_udaf(
    name: &str,
    return_type: Arc<DataType>,
    volatility: Volatility,
    accumulator: AccumulatorFactoryFunction,
    state_type: Arc<Vec<DataType>>,
) -> AggregateUDF {
```

# Are these changes tested?

Yes

# Are there any user-facing changes?

yes

### CODE REVIEW

File: datafusion/expr/src/expr_fn.rs [hunk 1]
```diff
@@ -811,7 +811,7 @@ pub fn create_udaf(
     let state_type: StateTypeFunction = Arc::new(move |_| Ok(state_type.clone()));
     AggregateUDF::new(
         name,
-        &Signature::exact(vec![input_type], volatility),
+        &Signature::exact(input_type, volatility),
```
Comment (alamb) [inline datafusion/expr/src/expr_fn.rs:814]: 👍  makes sense to me

**Review by alamb — APPROVED** [review]
Thank you @jiangzhx
