### PR TITLE
Continuing Work of [PR9127]: improved using existing orderings

### LINKED ISSUE #8838: Eliminating multi-column sort when major column is a one-to-one and monotonic expression
### Describe the bug

DataFusion is unable to eliminate multi-column sorts when the major column is a one-to-one and monotonic expression of a sorted input column:
* In certain cases when the expression is not one-to-one, eliminating the sort is invalid (e.g. sorting by `floor(x), y` is not equivalent to sorting by `x, y`, even though `floor` is monotonic). 
* However, casting from `Int32` to `Int64` is one-to-one and monotonic, so DataFusion should be able to avoid sorting in such a case. See below. 

### To Reproduce

Data acquired from [`parquet_testing/data/delta_encoding_required_column_expect.csv`](https://github.com/apache/parquet-testing/blob/4cb3cff24c965fb329cdae763eabce47395a68a0/data/delta_encoding_required_column_expect.csv) (I couldn't get `datafusion-cli` to work with the parquet file for some reason).

```sql
CREATE EXTERNAL TABLE delta_encoding_required_column (
    c_customer_sk INT NOT NULL,
    c_current_cdemo_sk INT NOT NULL
)
STORED AS CSV WITH HEADER ROW
WITH ORDER (
    c_customer_sk DESC,
    c_current_cdemo_sk DESC
)
LOCATION 'delta_encoding_required_column_expect.csv';
```

```sql
-- sort required here
EXPLAIN
SELECT 
    CAST(c_customer_sk AS BIGINT) AS c_customer_sk_big,
    c_current_cdemo_sk
FROM delta_encoding_required_column
ORDER BY c_customer_sk_big DESC, c_current_cdemo_sk DESC;
```
Resulting physical plan has a `SortExec`:
```
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                            |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Sort: c_customer_sk_big DESC NULLS FIRST, delta_encoding_required_column.c_current_cdemo_sk DESC NULLS FIRST                                                                                                                                    |
|               |   Projection: CAST(delta_encoding_required_column.c_customer_sk AS Int64) AS c_customer_sk_big, delta_encoding_required_column.c_current_cdemo_sk                                                                                               |
|               |     TableScan: delta_encoding_required_column projection=[c_customer_sk, c_current_cdemo_sk]                                                                                                                                                    |
| physical_plan | SortPreservingMergeExec: [c_customer_sk_big@0 DESC,c_current_cdemo_sk@1 DESC]                                                                                                                                                                   |
|               |   SortExec: expr=[c_customer_sk_big@0 DESC,c_current_cdemo_sk@1 DESC]                                                                                                                                                                           |
|               |     ProjectionExec: expr=[CAST(c_customer_sk@0 AS Int64) as c_customer_sk_big, c_current_cdemo_sk@1 as c_current_cdemo_sk]                                                                                                                      |
|               |       RepartitionExec: partitioning=RoundRobinBatch(32), input_partitions=1                                                                                                                                                                     |
|               |         CsvExec: file_groups={1 group: [[home/suremarc/rust-app-atlas/delta_encoding_required_column.csv]]}, projection=[c_customer_sk, c_current_cdemo_sk], output_ordering=[c_customer_sk@0 DESC, c_current_cdemo_sk@1 DESC], has_header=true |
|               |                                                                                                                                                                                                                                                 |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
```sql
-- sort NOT required here
-- notice we have a single sorting column
EXPLAIN
SELECT 
    CAST(c_customer_sk AS BIGINT) AS c_customer_sk_big
FROM delta_encoding_required_column
ORDER BY c_customer_sk_big DESC;
```
Resulting physical plan has no `SortExec`:
```
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                           |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Sort: c_customer_sk_big DESC NULLS FIRST                                                                                                                                                       |
|               |   Projection: CAST(delta_encoding_required_column.c_customer_sk AS Int64) AS c_customer_sk_big                                                                                                 |
|               |     TableScan: delta_encoding_required_column projection=[c_customer_sk]                                                                                                                       |
| physical_plan | SortPreservingMergeExec: [c_customer_sk_big@0 DESC]                                                                                                                                            |
|               |   ProjectionExec: expr=[CAST(c_customer_sk@0 AS Int64) as c_customer_sk_big]                                                                                                                   |
|               |     RepartitionExec: partitioning=RoundRobinBatch(32), input_partitions=1                                                                                                                      |
|               |       CsvExec: file_groups={1 group: [[home/suremarc/rust-app-atlas/delta_encoding_required_column.csv]]}, projection=[c_customer_sk], output_ordering=[c_customer_sk@0 DESC], has_header=true |
|               |                                                                                                                                                                                                |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```


### Expected behavior

The first query provided above should not require a sort

### Additional context

I encountered this bug when trying to re-cast the timezone of a table ordered by both `timestamp` and a secondary `ticker` column.

### PR DESCRIPTION
**Pull request by mustafasrepo**
## Which issue does this PR close?

Closes #8838.

## What changes are included in this PR?
@Lordworms [PR](https://github.com/apache/arrow-datafusion/pull/9127) did a great job in solving the issue [#8838]. However, there were some minor issues in that PR
- The table and and csv file it refers were not consistent
- Substitution couldn't generate more than 1 valid ordering from an existing ordering. See [comment](https://github.com/apache/arrow-datafusion/pull/9127#issuecomment-1945936404)

## Are these changes tested?
Yes,

### CODE REVIEW

File: datafusion/physical-expr/src/equivalence/properties.rs [hunk 1]
```diff
@@ -1054,8 +1118,8 @@ impl DependencyNode {
     }
 }
 
-type DependencyMap = HashMap<PhysicalSortExpr, DependencyNode>;
-type Dependencies = HashSet<PhysicalSortExpr>;
+type DependencyMap = IndexMap<PhysicalSortExpr, DependencyNode>;
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/properties.rs:1121]: Maybe we can add a comment or two explaining *why* this uses an IndexMap and not a HashMap presumably because the order matters? Or it is required to get consistent plans?

File: datafusion/physical-expr/src/expressions/cast.rs [hunk 2]
```diff
@@ -76,6 +76,26 @@ impl CastExpr {
     pub fn cast_options(&self) -> &CastOptions<'static> {
         &self.cast_options
     }
+    pub fn is_bigger_cast(&self, src: DataType) -> bool {
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/cast.rs:79]: I think this is similar to what is in the coercion logic. Maybe we can consolidate it at some point

File: datafusion/sqllogictest/test_files/monotonic_projection_test.slt [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+CREATE EXTERNAL TABLE multiple_ordered_table (
+  a0 INTEGER,
+  a INTEGER,
+  b INTEGER,
+  c INTEGER,
+  d INTEGER
+)
+STORED AS CSV
+WITH HEADER ROW
+WITH ORDER (a ASC, b ASC)
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/monotonic_projection_test.slt:29]: Neat

File: datafusion/sqllogictest/test_files/monotonic_projection_test.slt [hunk 4]
```diff
@@ -0,0 +1,133 @@
...
+Sort: multiple_ordered_table.a ASC NULLS LAST, multiple_ordered_table.b ASC NULLS LAST
+--Projection: multiple_ordered_table.a, CAST(multiple_ordered_table.a AS Int64) AS a_big, multiple_ordered_table.b
+----TableScan: multiple_ordered_table projection=[a, b]
+physical_plan
+SortPreservingMergeExec: [a@0 ASC NULLS LAST,b@2 ASC NULLS LAST]
+--ProjectionExec: expr=[a@0 as a, CAST(a@0 AS Int64) as a_big, b@1 as b]
+----RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
+------CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a, b], output_ordering=[a@0 ASC NULLS LAST, b@1 ASC NULLS LAST], has_header=true
+
+# TODO: Should generate without SortExec
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/monotonic_projection_test.slt:68]: The plan doesn't seem to have a `SortExec` to me -- maybe the comment is out of date 🤔

File: datafusion/sqllogictest/test_files/monotonic_projection_test.slt [hunk 5]
```diff
@@ -0,0 +1,133 @@
...
+logical_plan
+Sort: multiple_ordered_table.a ASC NULLS LAST, multiple_ordered_table.b ASC NULLS LAST
+--Projection: multiple_ordered_table.a, multiple_ordered_table.a AS a_big, multiple_ordered_table.b
+----TableScan: multiple_ordered_table projection=[a, b]
+physical_plan
+ProjectionExec: expr=[a@0 as a, a@0 as a_big, b@1 as b]
+--CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a, b], output_ordering=[a@0 ASC NULLS LAST, b@1 ASC NULLS LAST], has_header=true
+
+
+# test for cast Utf8
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/monotonic_projection_test.slt:115]:
```suggestion
# test for cast Utf8
# (must actually sort as the sort order for a number cast to utf8 is different than for int)
```

File: datafusion/physical-expr/src/equivalence/properties.rs [hunk 6]
```diff
@@ -426,6 +426,71 @@ impl EquivalenceProperties {
...
+                    .cloned()
+                    .collect();
+                let mut res = vec![sort_expr.clone()];
+                // TODO: Add one-to-ones analysis for ScalarFunctions.
+                for r_expr in referring_exprs {
+                    // we check whether this expression is substitutable or not
+                    if let Some(cast_expr) = r_expr.as_any().downcast_ref::<CastExpr>() {
+                        // we need to know whether the Cast Expr matches or not
+                        let expr_type = sort_expr.expr.data_type(&self.schema)?;
+                        if cast_expr.expr.eq(&sort_expr.expr)
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/properties.rs:458]: I wonder why this is checking for `cast` explicitly and not for `expr.is_monotonic`? It seems the logic holds as long as the expression is monotonic, and is more general than just casting

File: datafusion/sqllogictest/test_files/monotonic_projection_test.slt [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+logical_plan
+Sort: a_str ASC NULLS LAST, multiple_ordered_table.b ASC NULLS LAST
+--Projection: CAST(multiple_ordered_table.a AS Utf8) AS a_str, multiple_ordered_table.b
+----TableScan: multiple_ordered_table projection=[a, b]
+physical_plan
+SortPreservingMergeExec: [a_str@0 ASC NULLS LAST,b@1 ASC NULLS LAST]
+--SortExec: expr=[a_str@0 ASC NULLS LAST,b@1 ASC NULLS LAST]
+----ProjectionExec: expr=[CAST(a@0 AS Utf8) as a_str, b@1 as b]
+------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
+--------CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a, b], output_ordering=[a@0 ASC NULLS LAST, b@1 ASC NULLS LAST], has_header=true
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/monotonic_projection_test.slt:133]: I suggest two more negative tests:
*  `ORDER BY a + b`  
* `ORDER BY CAST(a + b AS BIGINT)`

To show that `+` if a column is not order preserving

**Review by alamb — APPROVED** [review]
Thank you @mustafasrepo  -- this looks good to me

File: datafusion/physical-expr/src/expressions/cast.rs (hunk 2 above)
Comment (mustafasrepo) [reply datafusion/physical-expr/src/expressions/cast.rs]: I can imagine this util would be useful in another context.

File: datafusion/sqllogictest/test_files/monotonic_projection_test.slt (hunk 4 above)
Comment (mustafasrepo) [reply datafusion/sqllogictest/test_files/monotonic_projection_test.slt:68]: Exactly, out of date. Fixed it and added a comment why generated plan is correct.

File: datafusion/sqllogictest/test_files/monotonic_projection_test.slt (hunk 5 above)
Comment (mustafasrepo) [reply datafusion/sqllogictest/test_files/monotonic_projection_test.slt:119]: Added it. Thanks

File: datafusion/physical-expr/src/equivalence/properties.rs (hunk 6 above)
Comment (mustafasrepo) [reply datafusion/physical-expr/src/equivalence/properties.rs:458]: For substitution, we need one-to-one ness condition as well as monotonicity condition. One we have one-to-oneness support for ScalarFunctions we can add this support. See my counter example in the [discussion](https://github.com/apache/arrow-datafusion/pull/9127#issuecomment-1945936404).

However, given `[a ASC, b ASC]` is satisfied `[monotonic_fn(a) ASC]` is still satisfied. (However, `[monotonic_fn(a) ASC, b ASC]` is not unless monotonic_fn is not one-to-one function.) 
And as far as I know, Datafusion can determine `[monotonic_fn(a) ASC]` is satisfied currently.

**Comment by mustafasrepo** [comment]
Thanks @alamb as always for your detailed review.
