### PR TITLE
Cache common plan properties to eliminate recursive calls in physical plan

### LINKED ISSUE #9084: Exponential nature of `ExecutionPlan`s `output_partitioning` and `equivalence_properties`
### Describe the bug

I have been troubleshooting the TPCH-DS query 64, and have found some performance issues, seemingly stemming from `ExecutionPlan::output_partitioning`, `ExecutionPlan::equivalence_properties` and their inherent branching nature throughout various `ExecutionPlan` implementations.

In particular the problem manifests by the process pinning the CPU at 100%, and getting stuck in the `EnforceDistribution` physical optimizer, which aggravates the underlying problem by inter-leaving `RepartitionExec` into the existing plan tree.

#### Setup
You can use the existing `tpcds_physical_q64` test, just un-ignore it and set `env_logger::init()` somewhere to capture the logs. You'll also need to set `RUST_MIN_STACK=3000000` to alleviate an unrelated problem described in https://github.com/apache/arrow-datafusion/issues/4786.

#### Flamegraph
Next you can optionally capture the flamegraph to get an initial sense of what's happening
```bash
sudo cargo flamegraph --dev -v --test tpcds_planning -- tpcds_physical_q64
```
I see something like [flamegraph.svg.zip](https://github.com/apache/arrow-datafusion/files/14112252/flamegraph.svg.zip).

Notably, there is a large build-up of (likely under-sampled) `output_partitioning` and `equivalence_properties` calls.

#### Investigation
I used some counters
```rust
pub struct Counter {
    count: std::sync::Mutex<u32>,
}

impl Counter {
    pub fn new() -> Counter {
        Counter {
            count: std::sync::Mutex::new(0),
        }
    }

    pub fn reset(&self) {
        let mut counter = self.count.lock().unwrap();
        *counter = 0;
    }

    pub fn increment(&self) {
        let mut counter = self.count.lock().unwrap();
        *counter += 1;
    }

    pub fn get(&self) -> u32 {
        let counter = self.count.lock().unwrap();
        *counter
    }
}

use once_cell::sync::Lazy;

pub static OUT_PART_COUNTER: Lazy<Arc<Counter>> = Lazy::new(|| Arc::new(Counter::new()));
pub static EQ_PROP_COUNTER: Lazy<Arc<Counter>> = Lazy::new(|| Arc::new(Counter::new()));
```

and then sprinkled `crate::OUT_PART_COUNTER.increment()` and `crate::EQ_PROP_COUNTER.increment()` at the begining of `fn output_partitioning(&self)` and `fn equivalence_properties(&self)` respectively, for `MemoryExec`, `RepartitionExec`, `HashJoinExec`, `ProjectionExec` and `AggregateExec`.

I also added the following
```diff
diff --git a/datafusion/core/src/physical_optimizer/enforce_distribution.rs b/datafusion/core/src/physical_optimizer/enforce_distribution.rs
index 0c5c2d78b..d4c0ddc22 100644
--- a/datafusion/core/src/physical_optimizer/enforce_distribution.rs
+++ b/datafusion/core/src/physical_optimizer/enforce_distribution.rs
@@ -208,9 +208,16 @@ impl PhysicalOptimizerRule for EnforceDistribution {
         };
 
         let distribution_context = DistributionContext::new_default(adjusted);
+        use datafusion_physical_plan::{OUT_PART_COUNTER, EQ_PROP_COUNTER};
+        OUT_PART_COUNTER.reset();
+        EQ_PROP_COUNTER.reset();
         // Distribution enforcement needs to be applied bottom-up.
         let distribution_context =
             distribution_context.transform_up(&|distribution_context| {
+                log::warn!("output_partitioning {}, equivalence_properties {}", OUT_PART_COUNTER.get(), EQ_PROP_COUNTER.get());
+                OUT_PART_COUNTER.reset();
+                EQ_PROP_COUNTER.reset();
+
                 ensure_distribution(distribution_context, config)
             })?;
         Ok(distribution_context.plan)
```

#### Results
Soon enough after starting the test you'll notice these numbers reach values on the order of 100K and then millions and more as the slowdown in the iterations becomes appreciable
```bash
[2024-01-31T13:58:01Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 40955, equivalence_properties 58363
[2024-01-31T13:58:01Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 0, equivalence_properties 0
[2024-01-31T13:58:03Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 245749, equivalence_properties 350184
[2024-01-31T13:58:03Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 81915, equivalence_properties 116731
[2024-01-31T13:58:03Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 0, equivalence_properties 0
[2024-01-31T13:58:06Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 491509, equivalence_properties 700392
[2024-01-31T13:58:07Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 163835, equivalence_properties 233467
[2024-01-31T13:58:07Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 0, equivalence_properties 0
[2024-01-31T13:58:12Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 983029, equivalence_properties 1400808
[2024-01-31T13:58:14Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 327675, equivalence_properties 466939
[2024-01-31T13:58:14Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 0, equivalence_properties 0
[2024-01-31T13:58:25Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 1966069, equivalence_properties 2801640
[2024-01-31T13:58:29Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 655355, equivalence_properties 933883
[2024-01-31T13:58:29Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 0, equivalence_properties 0
[2024-01-31T13:58:29Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 0, equivalence_properties 1
[2024-01-31T13:58:29Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 0, equivalence_properties 1
[2024-01-31T13:58:51Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 3932157, equivalence_properties 5603310
[2024-01-31T13:59:13Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 3932151, equivalence_properties 5603324
[2024-01-31T13:59:50Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 6553589, equivalence_properties 9338876
[2024-01-31T14:02:12Z WARN  datafusion::physical_optimizer::enforce_distribution] output_partitioning 24903668, equivalence_properties 35487723
```

#### Explanation
WARNING: A lot of gritty details below
Taking a look at one of the plans that appears early in the optimization process:
```bash
[
    "AggregateExec: mode=Partial, gby=[cs_item_sk@0 as cs_item_sk], aggr=[SUM(catalog_sales.cs_ext_list_price), SUM(catalog_returns.cr_refunded_cash + catalog_returns.cr_reversed_charge + catalog_returns.cr_store_credit)]",
    "  ProjectionExec: expr=[cs_item_sk@0 as cs_item_sk, cs_ext_list_price@2 as cs_ext_list_price, cr_refunded_cash@5 as cr_refunded_cash, cr_reversed_charge@6 as cr_reversed_charge, cr_store_credit@7 as cr_store_credit]",
    "    HashJoinExec: mode=Partitioned, join_type=Inner, on=[(cs_item_sk@0, cr_item_sk@0), (cs_order_number@1, cr_order_number@1)]",
    "      RepartitionExec: partitioning=Hash([cs_item_sk@0, cs_order_number@1], 12), input_partitions=0",
    "        MemoryExec: partitions=0, partition_sizes=[]",
    "      RepartitionExec: partitioning=Hash([cr_item_sk@0, cr_order_number@1], 12), input_partitions=0",
    "        MemoryExec: partitions=0, partition_sizes=[]",
]
```
and exploring the relevant implementations of `output_partitioning` and `equivalence_properties`, you can see that they have the potential to branch off into calling two methods on the input, thus leading to a exponential call tree.

In particular calling just `output_partitioning()` on the top-most plan leads to:
- in [`AggregateExec::output_partitioning`](https://github.com/apache/arrow-datafusion/blob/15f59d9861082a4d5d39bddce63d81cc7b9fb299/datafusion/physical-plan/src/aggregates/mod.rs#L601-L608) 
    ```rust
    1 x out_part() + 2 x input.out_part() + input.eq_prop()
    ```
- for the `ProjectionExec` node below [this gets expanded](https://github.com/apache/arrow-datafusion/blob/15f59d9861082a4d5d39bddce63d81cc7b9fb299/datafusion/physical-plan/src/projection.rs#L175-L176) to 
    ```rust
    1 x out_part() + 2 x (out_part() + input.out_part() + input.eq_prop()) + (eq_prop() + input.eq_prop()) = 
    3 x out_part() + eq_prop() + 2 x input.out_part() + 3 x input.eq_prop()
    ```
- Subsequently, `HashJoinExec` will [expand](https://github.com/apache/arrow-datafusion/blob/15f59d9861082a4d5d39bddce63d81cc7b9fb299/datafusion/physical-plan/src/joins/symmetric_hash_join.rs#L398-L412) these calls to left and right inputs
    ```rust
    3 x out_part() + eq_prop() + 2 x (out_part() + left.out_part() + right.out_part()) + 3 x (eq_prop() + left.eq_prop() + right.eq_prop()) = 
    5 x out_part() + 4 x eq_prop() + 2 x (left.out_part() + right.out_part()) + 3 x (left.eq_prop() + right.eq_prop())
    ```
- Next, given that both left and right inputs above are `RepartitionExec`s which are [leaf call-nodes for `out_part()`](https://github.com/apache/arrow-datafusion/blob/15f59d9861082a4d5d39bddce63d81cc7b9fb299/datafusion/physical-plan/src/repartition/mod.rs#L449), but also expand `eq_prop` into [2 of inputs](https://github.com/apache/arrow-datafusion/blob/15f59d9861082a4d5d39bddce63d81cc7b9fb299/datafusion/physical-plan/src/repartition/mod.rs#L465-L472) methods we get
    ```rust
    5 x out_part() + 4 x eq_prop() + 2 x (out_part() + out_part()) + 3 x (eq_prop() + l_input.eq_prop() + l_input.out_part() + eq_prop() + r_input.eq_prop() + r_input.out_part()) =
    9 x out_part() + 10 x eq_prop() + 6 x input.eq_prop() + 6 x input.eq_prop() =
    ```
- Lastly the bottom plan nodes are `MemoryExec`s which [terminate the `eq_prop()` call chain](https://github.com/apache/arrow-datafusion/blob/15f59d9861082a4d5d39bddce63d81cc7b9fb299/datafusion/physical-plan/src/memory.rs#L125) as well
    ```rust
    9 x out_part() + 10 x eq_prop() + 6 x eq_prop() + 6 x eq_prop() =
    15 x out_part() + 16 x eq_prop()
    ```

So for computing 1 thing (`Partitioning`), from a total of 7 plans the total invocation count for the above two methods was 31, thus with some overlapping. Note that some of these calls involve allocating stuff on the heap as well as some other computations, which can add up when the invocation count grows substantially.

Finally, given that these 2 methods are liberally called inside `ensure_distribution` and its sub-routines, I think this explains the enormous call count and ultimately the slow-down.

### Expected behavior

Some potential mitigations:

- [Delay calling and re-use results](https://github.com/apache/arrow-datafusion/blob/15f59d9861082a4d5d39bddce63d81cc7b9fb299/datafusion/physical-plan/src/aggregates/mod.rs#L606-L613) from `output_partitioning` and `equivalence_properties` within methods. For instance in `AggregateExec` the second call to `input.output_partitioning` is redundant and the call to `input.equivalence_properties()` can also be delayed only in case of a match (and [likewise](https://github.com/apache/arrow-datafusion/blob/15f59d9861082a4d5d39bddce63d81cc7b9fb299/datafusion/physical-plan/src/projection.rs#L176-L181) for `ProjectionExec`).
- A proper solution would probably involve `EnforceDistribution` interleaving some helper plans alongside with RepartitionExec` which serve to cache/short-circuit the `output_partitioning` and `equivalence_properties` already computed for the input below.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mustafasrepo**
## Which issue does this PR close?

Closes #9084 .

## Rationale for this change
In great analysis by @gruuya  at the issue [9084](https://github.com/apache/arrow-datafusion/issues/9084). @gruuya  recognized that stack usage (depth) increases a lot during logical and physical planning. The root cause of aggressive stack usage is 
- In the logical planning is excessive use of `.clone` of `LogicalPlan` enum. 
- In physical planning is the recursive function calls in the getter `API`s of the `Arc<dyn ExecutionPlan>`, such as `EquivalenceProperties`, `output_partitioning`, `output_ordering`, etc. 

In the [PR9084](https://github.com/apache/arrow-datafusion/issues/9084), @gruuya  could reduce physical plan stack usage by caching `equivalence_properties` for `ProjectionExec`. 

This PR introduces a new struct to cache PlanProperties (`PlanPropertiesCache`). With this struct, `schema`, `output_partitioning`, `equivalence_properties`, `output_ordering` is cached. This caching mechanism removes recursive calls during getter methods. Also, given `.cache` method is implemented, default implementations of the `.output_partitioning`, `.equivalence_properties`, `output_ordering` works out of the box.

With these changes stack depth decreases  considerably, Since recursive calls are eliminated in the `PhysicalPlan`. 
As an example Flame graph for the query 54 is converted from following graph
flamegraph_main_q54

to following graph

flamegraph_branch_q54.

## Are these changes tested?

Existing tests should work

## Are there any user-facing changes?

`api change`

### CODE REVIEW

**Comment by ozankabak** [comment]
Super excited!

File: datafusion/core/src/test_util/mod.rs [hunk 1]
```diff
@@ -55,6 +55,7 @@ use tempfile::TempDir;
 #[cfg(feature = "parquet")]
 pub use datafusion_common::test_util::parquet_test_data;
 pub use datafusion_common::test_util::{arrow_test_data, get_data_dir};
+use datafusion_physical_expr::EquivalenceProperties;
```
Comment (ozankabak) [inline datafusion/core/src/test_util/mod.rs:58]: Let's move this import statement up so it doesn't get mixed up with the backwards compatibility imports.

File: datafusion/core/tests/user_defined/user_defined_plan.rs [hunk 2]
```diff
@@ -91,6 +91,7 @@ use datafusion::{
 };
 
 use async_trait::async_trait;
+use datafusion_physical_expr::EquivalenceProperties;
```
Comment (ozankabak) [inline datafusion/core/tests/user_defined/user_defined_plan.rs:94]: Let's move this up next to other DataFusion imports

File: datafusion/physical-plan/src/filter.rs [hunk 3]
```diff
@@ -115,32 +115,76 @@ impl FilterExec {
         self.default_selectivity
     }
 
-    fn with_cache(mut self) -> Self {
+    fn statistics_helper(
```
Comment (ozankabak) [inline datafusion/physical-plan/src/filter.rs:118]: Let's write a docstring for this function.

File: datafusion/physical-plan/src/joins/hash_join.rs [hunk 4]
```diff
@@ -65,6 +65,7 @@ use datafusion_execution::TaskContext;
 use datafusion_physical_expr::equivalence::join_equivalence_properties;
 use datafusion_physical_expr::PhysicalExprRef;
 
+use crate::joins::utils::JoinOnRef;
```
Comment (ozankabak) [inline datafusion/physical-plan/src/joins/hash_join.rs:68]: Let's move this next to other relative (`crate`) imports

File: datafusion/physical-plan/src/repartition/mod.rs [hunk 5]
```diff
@@ -611,27 +607,49 @@ impl RepartitionExec {
...
+    fn maintains_input_order_helper(
+        input: &Arc<dyn ExecutionPlan>,
+        preserve_order: bool,
+    ) -> Vec<bool> {
+        if preserve_order {
+            vec![true]
+        } else {
+            // We preserve ordering when input partitioning is 1
+            vec![input.output_partitioning().partition_count() <= 1]
         }
```
Comment (ozankabak) [inline datafusion/physical-plan/src/repartition/mod.rs:624]: Why not write it as `vec![preserve_order || input.output_partitioning().partition_count() <= 1]`

**Review by ozankabak — APPROVED** [review]
Did another round of review and LGTM except a few minor things (whose comments I left inline).

One general comment is to add a succinct, single line docstring comment to `create_cache` functions. Something like:

```
This function creates the cache object that stores plan properties such as equivalence properties, output ordering etc.
```

Looking forward to getting some eyes on this from the community!

File: datafusion/physical-plan/src/lib.rs [hunk 6]
```diff
@@ -121,21 +121,23 @@ pub trait ExecutionPlan: Debug + DisplayAs + Send + Sync {
     fn as_any(&self) -> &dyn Any;
 
     /// Get the schema for this execution plan
-    fn schema(&self) -> SchemaRef;
+    fn schema(&self) -> SchemaRef {
+        self.cache().schema().clone()
+    }
+
+    fn cache(&self) -> &PlanPropertiesCache;
```
[the remark this answers is not in the document]
Comment (ozankabak) [reply datafusion/physical-plan/src/lib.rs:128]: Agreed, I like `properties` and `property_cache`

**Comment by alamb** [comment]
I plan to review this PR today

File: datafusion/physical-plan/src/lib.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/physical-plan/src/lib.rs:128]: I also like `properties` and `PlanProperties` 

I agree that the term `Cache` could be confusing, for the reason that @gruuya  mentioned as well as the fact that the `PlanPropertiesCache` doesn't do any caching itself, but rather it **used** as a cache.

File: datafusion-examples/examples/custom_datasource.rs [hunk 7]
```diff
@@ -199,11 +200,23 @@ impl CustomExec {
...
+        let cache = Self::create_cache(projected_schema.clone());
         Self {
             db,
             projected_schema,
+            cache,
         }
     }
+
+    /// This function creates the cache object that stores the plan properties such as schema, equivalence properties, ordering, partitioning, etc.
+    fn create_cache(schema: SchemaRef) -> PlanPropertiesCache {
```
Comment (alamb) [inline datafusion-examples/examples/custom_datasource.rs:212]: As mentioned above, calling this like 

```suggestion
    fn compute_properties(schema: SchemaRef) -> PlanProperties {
```

I think would make its use and intent more clear

File: datafusion-examples/examples/custom_datasource.rs [hunk 8]
```diff
@@ -217,16 +230,8 @@ impl ExecutionPlan for CustomExec {
...
-    }
-
-    fn output_partitioning(&self) -> datafusion::physical_plan::Partitioning {
-        datafusion::physical_plan::Partitioning::UnknownPartitioning(1)
-    }
-
-    fn output_ordering(&self) -> Option<&[PhysicalSortExpr]> {
-        None
+    fn cache(&self) -> &PlanPropertiesCache {
+        &self.cache
```
Comment (alamb) [inline datafusion-examples/examples/custom_datasource.rs:234]:
```suggestion
    fn properties(&self) -> &PlanProperties {
        &self.cache
```

File: datafusion/physical-plan/src/lib.rs [hunk 9]
```diff
@@ -446,6 +450,123 @@ pub trait ExecutionPlan: Debug + DisplayAs + Send + Sync {
     }
 }
 
+/// Describes the execution mode of an operator's resulting stream with respect
```
Comment (alamb) [inline datafusion/physical-plan/src/lib.rs:453]: This is a much nicer API 👍

File: datafusion/physical-plan/src/lib.rs [hunk 10]
```diff
@@ -446,6 +450,123 @@ pub trait ExecutionPlan: Debug + DisplayAs + Send + Sync {
...
+/// to its size and behavior. There are three possible execution modes: `Bounded`,
+/// `Unbounded` and `PipelineBreaking`.
+#[derive(Clone, Copy, PartialEq, Debug)]
+pub enum ExecutionMode {
+    /// Represents the mode where generated stream is bounded, e.g. finite.
+    Bounded,
+    /// Represents the mode where generated stream is unbounded, e.g. infinite.
+    /// Even though the operator generates an unbounded stream of results, it
+    /// works with bounded memory and execution can still continue successfully.
```
Comment (alamb) [inline datafusion/physical-plan/src/lib.rs:462]:
```suggestion
    /// works with bounded memory and execution can still continue successfully.
    ///
    /// The stream that results from calling `execute` on an `ExecutionPlan` that is `Unbounded` 
    /// will never be done (return `None`), except in case of error.
```

File: datafusion/physical-plan/src/lib.rs [hunk 11]
```diff
@@ -446,6 +450,123 @@ pub trait ExecutionPlan: Debug + DisplayAs + Send + Sync {
...
+    Unbounded,
+    /// Represents the mode where some of the operator's input stream(s) are
+    /// unbounded; however, the operator cannot generate streaming results from
+    /// these streaming inputs. In this case, the execution mode will be pipeline
+    /// breaking, e.g. the operator requires unbounded memory to generate results.
+    PipelineBreaking,
```
Comment (alamb) [inline datafusion/physical-plan/src/lib.rs:468]: What is the usecase of `PipelineBreaking` ? I didn't see it used anywhere in the code differently than `ExecutionMode::Bounded` (though I may have missed)

I guess I am wondering what is (practical)  difference between `Bounded` and `PipelineBreaking`?

File: datafusion/physical-plan/src/lib.rs [hunk 12]
```diff
@@ -446,6 +450,123 @@ pub trait ExecutionPlan: Debug + DisplayAs + Send + Sync {
...
+
+    /// Check whether the execution is pipeline friendly. If so, operator can
+    /// execute safely.
+    pub fn pipeline_friendly(&self) -> bool {
+        matches!(self, ExecutionMode::Bounded | ExecutionMode::Unbounded)
+    }
+}
+
+/// Conservatively "combines" execution modes of a given collection of operators.
+fn exec_mode_flatten<'a>(
```
Comment (alamb) [inline datafusion/physical-plan/src/lib.rs:485]: I found this name confusing as it isn't flattening a nested structure but more like computing something from its children.

How about a name related to children? (I don't feel strongly)

```suggestion
fn execution_mode_from_children<'a>(
```

File: datafusion/physical-plan/src/lib.rs [hunk 13]
```diff
@@ -446,6 +450,123 @@ pub trait ExecutionPlan: Debug + DisplayAs + Send + Sync {
...
+            (ExecutionMode::Bounded, ExecutionMode::Bounded) => {
+                // When both modes are bounded, so is the result:
+                result = ExecutionMode::Bounded;
+            }
+        }
+    }
+    result
+}
+
+/// Represents a cache for plan properties used in query optimization.
```
Comment (alamb) [inline datafusion/physical-plan/src/lib.rs:509]:
```suggestion
/// Represents plan properties used in query optimization.
///
/// These properties are in a single structure to permit this information to be computed
/// once and then those cached results used multiple times without recomputation (aka a cache)
```

File: datafusion/physical-plan/src/lib.rs [hunk 14]
```diff
@@ -121,21 +121,23 @@ pub trait ExecutionPlan: Debug + DisplayAs + Send + Sync {
...
+    fn schema(&self) -> SchemaRef {
+        self.cache().schema().clone()
+    }
+
+    fn cache(&self) -> &PlanPropertiesCache;
 
     /// Specifies how the output of this `ExecutionPlan` is split into
     /// partitions.
-    fn output_partitioning(&self) -> Partitioning;
+    fn output_partitioning(&self) -> &Partitioning {
```
Comment (alamb) [inline datafusion/physical-plan/src/lib.rs:132]: Given that `fn cache()` is required, it seems to me there is a potential in the API for conflicting implementations (e.g. a user could return a default `PlanProperties` but forget to remove `output_partitioning`

This I suggest removing the functions like `output_partitioning` from the `ExecutionPlan` trait.

You could probably avoid having to make a bunch of changes by moving the functions into a new trait like

```rust
pub trait ExecutionPlanExt {
    fn execution_mode(&self) -> ExecutionMode;
...
}

// implement so current call sites of plan.execution_mode() still work:
impl ExecutionPlanExt for &dyn ExecutionPlan {
    fn execution_mode(&self) -> ExecutionMode;
       self.cache().exec_mode
    }
 
```

**Review by alamb — COMMENTED** [review]
Thank you for this PR @mustafasrepo  -- I agree with @ozankabak and @gruuya  that the use of the term "cache" is confusing. 

I also think we should remove the existing methods like `ExecutionPlan::execution_mode` to avoid potential bugs due to inconsistent implementations. 

In addition to improving the stack depth, I think this PR may also significantly improve planning speed (as it avoids redundant calculations)

Otherwise I think this PR looks good to me

File: datafusion/physical-plan/src/lib.rs (hunk 11 above)
Comment (mustafasrepo) [reply datafusion/physical-plan/src/lib.rs:471]: Some physical optimizer rules such as `replace_with_order_preserving_variants` behaves differently for `PipelineBreaking` and `PipelineFriendly` modes. (Such as choosing `SortPreservingRepartition` instead of `Repartition` to resolve `PipelineBreaking` plan).

File: datafusion/physical-plan/src/lib.rs (hunk 14 above)
Comment (ozankabak) [reply datafusion/physical-plan/src/lib.rs:132]: I think @mustafasrepo addressed all the reviews including naming, this is the only one left. I don't think I fully understand your point, can you explain a little more?

Specifically, the only difference I see with @mustafasrepo's design (i.e. default implementations) and using a new extension trait is that the former leaves the door open for a `ExecutionPlan` implementation to override the simple "get the property from cache" behavior for any of the functions like `output_partitioning`. I think this was by design, in case a downstream requirement forces implementors to add some custom behavior there.

Do you think that may be undesirable (or have some possibly harmful results)?

Comment (alamb) [reply datafusion/physical-plan/src/lib.rs:132]: > Specifically, the only difference I see with @mustafasrepo's design (i.e. default implementations) and using a new extension trait is that the former leaves the door open for a `ExecutionPlan` implementation to override the simple "get the property from cache" behavior for any of the functions like `output_partitioning`. I think this was by design, in case a downstream requirement forces implementors to add some custom behavior there.
> 
> Do you think that may be undesirable (or have some possibly harmful results)?

The problem I see is that it would be possible for `plan.properties().execution_mode` to be inconsistent with
 `plan.execution_mode()`. 

What I was imagining was the upgrade scenario of existing implementation of `ExecutionPlan` such as we have in `InfluxDB` 

1. The person doing the upgrade sees "I have to implement a new function named `properties()`"
2. Simply implements it by returning a default `PlanProperties()` function but leaves the `execution_mode` impl unchanged

Now I can imagine some code in the future assumes that since all `ExecutionPlan` impls in DataFusion correctly implement `properties()` that it is safe to assume that `plan.properties().execution_mode` matches `plan.execution_mode()`.

Maybe this would have been less likely when the name was cache() 

I don't feel super strongly about this issue but I do think it is a "foot gun" in the API

File: .github/workflows/docs.yaml [hunk 15]
```diff
@@ -1,64 +0,0 @@
-on:
```
Comment (alamb) [inline .github/workflows/docs.yaml:1]: Why was the docs test deleted? this seems like it may be unintended

**Review by alamb — COMMENTED** [review]
I think this PR is looking quite good now. I'll try and give it another careful look tomorrow.  Maybe we can wait to see if @gruuya  has any additional comments before merging. 

I do think it would be better to make it impossible for the API's to be inconsistent (aka https://github.com/apache/arrow-datafusion/pull/9346#discussion_r1505211396) but I think it would be ok to leave the API as it is currently in this PR

File: datafusion/physical-plan/src/lib.rs (hunk 14 above)
Comment (ozankabak) [reply datafusion/physical-plan/src/lib.rs:132]: I see. This makes sense -- @mustafasrepo, let's create an extension trait like @alamb described

**Comment by gruuya** [comment]
No further comments from me, aside from thanks once again @mustafasrepo for handling this!

Perhaps just a side note that even `RUST_MIN_STACK=300000` is insufficient for the original source of the issue now (`tpcds_physical_q64`), and seems to need a couple of orders more. Not sure whether https://github.com/apache/arrow-datafusion/issues/8837 is still active, but definitely worth tracking somewhere, and eventually un-ignoring the test.

File: datafusion/physical-plan/src/lib.rs (hunk 14 above)
Comment (mustafasrepo) [reply datafusion/physical-plan/src/lib.rs:132]: I have applied your suggesion @alamb. Thanks for the suggestion. It is very neat. I thought about this possibility, However couldn't come up with a way to prevent it.

File: .github/workflows/docs.yaml (hunk 15 above)
Comment (mustafasrepo) [reply .github/workflows/docs.yaml:1]: It is by mistake (the original branch this branch created had that commit. Re-introduced it. Thanks for catching it)

**Comment by mustafasrepo** [comment]
> No further comments from me, aside from thanks once again @mustafasrepo for handling this!
> 
> Perhaps just a side note that even `RUST_MIN_STACK=300000` is insufficient for the original source of the issue now (`tpcds_physical_q64`), and seems to need a couple of orders more. Not sure whether #8837 is still active, but definitely worth tracking somewhere, and eventually un-ignoring the test.

@metesynnada did some debugging of `tpcds_physical_q64` why stack overflow occurs. It seems that overflow occurs in `create_intial_plan` stage of planner (It is the place, where `LogicalPlan` is converted to the `PhysicalPlan`. Not during any physical rule or logical plan creation).  Examining code structure, it seems that `recursive` futures are used by constructed `create_initial_plan` recursively on the `LogicalPlan`. I am not familiar with its implications, However the problem might be related to this behavior.

**Comment by gruuya** [comment]
> Seems like there are quite big regressions in physical planning.

Perhaps it's the eager computation of plan properties now, as opposed to lazy computation before (meaning some props were not computed/needed)?

**Comment by mustafasrepo** [comment]
> I was curious on how this affected planning performance. Here are my results comparing [0c46d7f](https://github.com/apache/arrow-datafusion/commit/0c46d7fa105fddc4a35a4c99e4aa2a063d967abb) (parent of first commit in this PR) with [a8fac85](https://github.com/apache/arrow-datafusion/commit/a8fac85429f519ea5ae258a2a6425eaa9ab333c8).
> 
> Seems like there are quite big regressions in physical planning. But I may have messed up.
> 
> Results

I re-ran benchmarks in my machine. The results are below
<details>

<summary>Results</summary>

```
Gnuplot not found, using plotters backend
logical_select_one_from_700
                        time:   [482.54 µs 484.25 µs 487.11 µs]
                        change: [-4.6292% -2.1797% +0.0154%] (p = 0.08 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) low severe
  2 (2.00%) low mild
  3 (3.00%) high mild
  1 (1.00%) high severe

physical_select_one_from_700
                        time:   [3.0204 ms 3.0227 ms 3.0250 ms]
                        change: [-2.3949% -2.0254% -1.7849%] (p = 0.00 < 0.05)
                        Performance has improved.

logical_trivial_join_low_numbered_columns
                        time:   [452.55 µs 453.30 µs 454.05 µs]
                        change: [-3.4288% -1.6448% -0.6310%] (p = 0.02 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  2 (2.00%) high severe

logical_trivial_join_high_numbered_columns
                        time:   [495.26 µs 498.76 µs 505.52 µs]
                        change: [-0.4885% +0.0379% +0.7595%] (p = 0.93 > 0.05)
                        No change in performance detected.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) low severe
  1 (1.00%) high mild
  1 (1.00%) high severe

logical_aggregate_with_join
                        time:   [769.12 µs 769.87 µs 770.62 µs]
                        change: [-18.781% -12.487% -6.5679%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) low mild
  3 (3.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q1   time:   [4.8582 ms 4.8620 ms 4.8663 ms]
                        change: [-17.477% -11.210% -6.1042%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  2 (2.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q2   time:   [7.5602 ms 7.5707 ms 7.5822 ms]
                        change: [-30.715% -30.328% -30.007%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  6 (6.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q3   time:   [2.5096 ms 2.5143 ms 2.5196 ms]
                        change: [-25.111% -24.050% -23.386%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 12 outliers among 100 measurements (12.00%)
  9 (9.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q4   time:   [1.9527 ms 1.9591 ms 1.9711 ms]
                        change: [-14.387% -14.094% -13.679%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  2 (2.00%) high mild
  5 (5.00%) high severe

physical_plan_tpch_q5   time:   [3.8057 ms 3.8091 ms 3.8127 ms]
                        change: [-57.720% -57.662% -57.601%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q6   time:   [1.3063 ms 1.3080 ms 1.3099 ms]
                        change: [-5.6737% -5.1326% -4.7813%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) low mild
  3 (3.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q7   time:   [5.4017 ms 5.4307 ms 5.4840 ms]
                        change: [-44.042% -43.729% -43.180%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  6 (6.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q8   time:   [7.9176 ms 7.9289 ms 7.9414 ms]
                        change: [-71.699% -71.653% -71.598%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  1 (1.00%) low mild
  5 (5.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q9   time:   [5.9427 ms 5.9797 ms 6.0430 ms]
                        change: [-47.161% -46.493% -45.740%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) high mild
  7 (7.00%) high severe

physical_plan_tpch_q10  time:   [3.8350 ms 3.8388 ms 3.8430 ms]
                        change: [-31.229% -31.025% -30.862%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q11  time:   [2.9252 ms 2.9415 ms 2.9715 ms]
                        change: [-16.985% -15.900% -14.659%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q12  time:   [2.6822 ms 2.6845 ms 2.6870 ms]
                        change: [-13.733% -13.572% -13.424%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild

physical_plan_tpch_q13  time:   [1.5018 ms 1.5033 ms 1.5048 ms]
                        change: [-24.810% -24.629% -24.402%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  1 (1.00%) low mild
  5 (5.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q14  time:   [2.1145 ms 2.1264 ms 2.1480 ms]
                        change: [-4.5956% -3.8425% -2.7007%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q16  time:   [3.1242 ms 3.1278 ms 3.1319 ms]
                        change: [-17.445% -17.334% -17.217%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q17  time:   [2.8500 ms 2.8705 ms 2.8990 ms]
                        change: [-8.0314% -7.2135% -6.2413%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q18  time:   [3.0984 ms 3.1064 ms 3.1175 ms]
                        change: [-10.790% -10.508% -10.196%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q19  time:   [7.8895 ms 7.9316 ms 8.0083 ms]
                        change: [-2.4917% -1.9490% -0.7408%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 7 outliers among 100 measurements (7.00%)
  6 (6.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q20  time:   [3.7943 ms 3.7987 ms 3.8037 ms]
                        change: [-19.417% -17.933% -16.538%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q21  time:   [5.7239 ms 5.7279 ms 5.7320 ms]
                        change: [-37.177% -36.725% -36.397%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild

physical_plan_tpch_q22  time:   [2.6413 ms 2.6610 ms 2.6942 ms]
                        change: [-14.662% -13.905% -12.725%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  5 (5.00%) high mild
  4 (4.00%) high severe

physical_plan_tpch_all  time:   [9.3429 ms 9.3899 ms 9.4571 ms]
                        change: [-2.7310% -1.5545% -0.5941%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) low mild
  2 (2.00%) high mild
  2 (2.00%) high severe

```
</details>
According to these results, new mechanism mostly improves planning performance (especially for complex queries). since our results are contradicting. I re-ran the same benchmark in main branch twice, and in new branch twice. Then compared these results with themselves to see how much variance benchmark run produces at different runs. Below results for the different benchmarks for the same branch can be found

<details>
<summary>Main Run 2 vs Main Run 1</summary>

```
Gnuplot not found, using plotters backend
logical_select_one_from_700
                        time:   [490.30 µs 505.86 µs 525.48 µs]
                        change: [-2.4316% +0.6167% +3.2873%] (p = 0.71 > 0.05)
                        No change in performance detected.
Found 5 outliers among 100 measurements (5.00%)
  5 (5.00%) high severe

physical_select_one_from_700
                        time:   [3.0782 ms 3.0852 ms 3.0962 ms]
                        change: [+1.0064% +1.2946% +1.6436%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) high mild
  1 (1.00%) high severe

logical_trivial_join_low_numbered_columns
                        time:   [457.67 µs 458.60 µs 459.94 µs]
                        change: [+0.3580% +1.3982% +3.7624%] (p = 0.06 > 0.05)
                        No change in performance detected.
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) low mild
  2 (2.00%) high mild
  1 (1.00%) high severe

logical_trivial_join_high_numbered_columns
                        time:   [496.65 µs 497.61 µs 498.80 µs]
                        change: [-0.2179% +0.0540% +0.3247%] (p = 0.70 > 0.05)
                        No change in performance detected.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) low severe
  1 (1.00%) high mild
  1 (1.00%) high severe

logical_aggregate_with_join
                        time:   [826.96 µs 908.94 µs 1.0125 ms]
                        change: [+6.3560% +14.209% +23.294%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 15 outliers among 100 measurements (15.00%)
  2 (2.00%) high mild
  13 (13.00%) high severe

physical_plan_tpch_q1   time:   [5.1788 ms 5.4759 ms 5.8885 ms]
                        change: [+1.3260% +7.2118% +15.244%] (p = 0.02 < 0.05)
                        Performance has regressed.
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) high mild
  7 (7.00%) high severe

physical_plan_tpch_q2   time:   [10.819 ms 10.866 ms 10.924 ms]
                        change: [-0.1234% +1.1456% +2.1468%] (p = 0.04 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q3   time:   [3.2836 ms 3.3104 ms 3.3553 ms]
                        change: [-2.3241% -0.9046% +0.8137%] (p = 0.29 > 0.05)
                        No change in performance detected.
Found 14 outliers among 100 measurements (14.00%)
  6 (6.00%) high mild
  8 (8.00%) high severe

physical_plan_tpch_q4   time:   [2.2800 ms 2.2830 ms 2.2862 ms]
                        change: [-1.4797% -1.0937% -0.7281%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q5   time:   [8.9876 ms 8.9969 ms 9.0067 ms]
                        change: [-1.4174% -0.7961% -0.2552%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild

physical_plan_tpch_q6   time:   [1.3748 ms 1.3814 ms 1.3940 ms]
                        change: [-9.3756% -5.6928% -2.5053%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  1 (1.00%) low mild
  3 (3.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q7   time:   [9.6410 ms 9.6510 ms 9.6617 ms]
                        change: [-0.9565% -0.4781% -0.0663%] (p = 0.03 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q8   time:   [27.948 ms 27.971 ms 27.993 ms]
                        change: [-0.2163% +0.0701% +0.3352%] (p = 0.62 > 0.05)
                        No change in performance detected.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

physical_plan_tpch_q9   time:   [11.114 ms 11.176 ms 11.285 ms]
                        change: [-0.2915% +0.4000% +1.4525%] (p = 0.49 > 0.05)
                        No change in performance detected.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high severe

physical_plan_tpch_q10  time:   [5.5536 ms 5.5655 ms 5.5812 ms]
                        change: [-0.6752% -0.3443% +0.0157%] (p = 0.04 < 0.05)
                        Change within noise threshold.
Found 6 outliers among 100 measurements (6.00%)
  4 (4.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q11  time:   [3.4787 ms 3.4976 ms 3.5313 ms]
                        change: [-1.3654% -0.6526% +0.4886%] (p = 0.18 > 0.05)
                        No change in performance detected.
Found 9 outliers among 100 measurements (9.00%)
  3 (3.00%) high mild
  6 (6.00%) high severe

physical_plan_tpch_q12  time:   [3.1018 ms 3.1061 ms 3.1110 ms]
                        change: [-0.7425% -0.4918% -0.2454%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q13  time:   [1.9962 ms 1.9986 ms 2.0010 ms]
                        change: [-0.4561% -0.2516% -0.0440%] (p = 0.02 < 0.05)
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q14  time:   [2.2037 ms 2.2113 ms 2.2203 ms]
                        change: [-0.4389% +0.0583% +0.5657%] (p = 0.82 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  5 (5.00%) high mild
  7 (7.00%) high severe

physical_plan_tpch_q16  time:   [3.7811 ms 3.7837 ms 3.7864 ms]
                        change: [-0.4859% -0.3382% -0.1973%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild

physical_plan_tpch_q17  time:   [3.0798 ms 3.0936 ms 3.1076 ms]
                        change: [+0.5410% +1.5036% +2.2740%] (p = 0.00 < 0.05)
                        Change within noise threshold.

physical_plan_tpch_q18  time:   [3.4659 ms 3.4712 ms 3.4769 ms]
                        change: [-0.1817% +0.0928% +0.3386%] (p = 0.50 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q19  time:   [8.0817 ms 8.0892 ms 8.0969 ms]
                        change: [-0.7482% -0.4924% -0.2533%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild

physical_plan_tpch_q20  time:   [4.5514 ms 4.6288 ms 4.7138 ms]
                        change: [+5.5386% +7.4224% +9.4528%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 9 outliers among 100 measurements (9.00%)
  5 (5.00%) high mild
  4 (4.00%) high severe

physical_plan_tpch_q21  time:   [9.0060 ms 9.0524 ms 9.1166 ms]
                        change: [-0.0386% +0.5447% +1.3691%] (p = 0.12 > 0.05)
                        No change in performance detected.
Found 17 outliers among 100 measurements (17.00%)
  11 (11.00%) high mild
  6 (6.00%) high severe

physical_plan_tpch_q22  time:   [3.0796 ms 3.0908 ms 3.1033 ms]
                        change: [-0.0510% +0.3826% +0.7615%] (p = 0.08 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  2 (2.00%) high mild
  10 (10.00%) high severe

physical_plan_tpch_all  time:   [9.4791 ms 9.5382 ms 9.6367 ms]
                        change: [+0.6728% +1.7514% +2.8703%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 6 outliers among 100 measurements (6.00%)
  1 (1.00%) low mild
  3 (3.00%) high mild
  2 (2.00%) high severe

```
</details>

<details>
<summary>Branch Run 2 vs Branch Run 1</summary>

```
Gnuplot not found, using plotters backend
logical_select_one_from_700
                        time:   [482.54 µs 484.25 µs 487.16 µs]
                        change: [+0.1199% +1.0534% +2.4753%] (p = 0.06 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) low severe
  2 (2.00%) low mild
  3 (3.00%) high mild
  1 (1.00%) high severe

physical_select_one_from_700
                        time:   [3.0204 ms 3.0227 ms 3.0250 ms]
                        change: [-1.9446% -1.8220% -1.6973%] (p = 0.00 < 0.05)
                        Performance has improved.

logical_trivial_join_low_numbered_columns
                        time:   [452.55 µs 453.30 µs 454.05 µs]
                        change: [-1.7532% -1.1174% -0.6057%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  2 (2.00%) high severe

logical_trivial_join_high_numbered_columns
                        time:   [495.25 µs 498.76 µs 505.57 µs]
                        change: [-1.0315% -0.4986% +0.3472%] (p = 0.15 > 0.05)
                        No change in performance detected.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) low severe
  1 (1.00%) high mild
  1 (1.00%) high severe

logical_aggregate_with_join
                        time:   [769.12 µs 769.87 µs 770.63 µs]
                        change: [-0.7240% -0.4668% -0.2220%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) low mild
  3 (3.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q1   time:   [4.8582 ms 4.8620 ms 4.8663 ms]
                        change: [-1.5189% -1.3731% -1.2333%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  2 (2.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q2   time:   [7.5602 ms 7.5707 ms 7.5822 ms]
                        change: [-1.4182% -1.1973% -0.9798%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 8 outliers among 100 measurements (8.00%)
  6 (6.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q3   time:   [2.5095 ms 2.5143 ms 2.5196 ms]
                        change: [-1.1784% -0.7929% -0.4292%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 12 outliers among 100 measurements (12.00%)
  9 (9.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q4   time:   [1.9527 ms 1.9591 ms 1.9711 ms]
                        change: [-20.849% -15.072% -9.8504%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  2 (2.00%) high mild
  5 (5.00%) high severe

physical_plan_tpch_q5   time:   [3.8057 ms 3.8091 ms 3.8127 ms]
                        change: [-1.1569% -0.9889% -0.8191%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q6   time:   [1.3063 ms 1.3080 ms 1.3099 ms]
                        change: [-3.3001% -2.3030% -1.4936%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) low mild
  3 (3.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q7   time:   [5.4017 ms 5.4307 ms 5.4840 ms]
                        change: [-0.8280% -0.1612% +0.8696%] (p = 0.81 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  6 (6.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q8   time:   [7.9177 ms 7.9289 ms 7.9413 ms]
                        change: [-1.5994% -1.2327% -0.9253%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 9 outliers among 100 measurements (9.00%)
  1 (1.00%) low mild
  5 (5.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q9   time:   [5.9426 ms 5.9797 ms 6.0429 ms]
                        change: [-0.3560% +0.2891% +1.2648%] (p = 0.67 > 0.05)
                        No change in performance detected.
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) high mild
  7 (7.00%) high severe

physical_plan_tpch_q10  time:   [3.8351 ms 3.8388 ms 3.8430 ms]
                        change: [-0.5106% -0.3235% -0.1468%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q11  time:   [2.9252 ms 2.9415 ms 2.9717 ms]
                        change: [-2.8743% -1.1814% +0.3357%] (p = 0.17 > 0.05)
                        No change in performance detected.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q12  time:   [2.6821 ms 2.6845 ms 2.6870 ms]
                        change: [-0.4900% -0.3172% -0.1498%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild

physical_plan_tpch_q13  time:   [1.5018 ms 1.5033 ms 1.5048 ms]
                        change: [-2.7994% -1.2002% -0.2305%] (p = 0.07 > 0.05)
                        No change in performance detected.
Found 9 outliers among 100 measurements (9.00%)
  1 (1.00%) low mild
  5 (5.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q14  time:   [2.1146 ms 2.1264 ms 2.1480 ms]
                        change: [-0.6216% +0.0295% +1.0359%] (p = 0.96 > 0.05)
                        No change in performance detected.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q16  time:   [3.1242 ms 3.1278 ms 3.1318 ms]
                        change: [-0.7674% -0.3833% -0.0720%] (p = 0.02 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q17  time:   [2.8501 ms 2.8705 ms 2.8994 ms]
                        change: [-0.1687% +0.6001% +1.6077%] (p = 0.22 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q18  time:   [3.0984 ms 3.1064 ms 3.1174 ms]
                        change: [-0.3335% -0.0200% +0.3375%] (p = 0.92 > 0.05)
                        No change in performance detected.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q19  time:   [7.8894 ms 7.9316 ms 8.0084 ms]
                        change: [-0.1952% +0.3957% +1.3828%] (p = 0.54 > 0.05)
                        No change in performance detected.
Found 7 outliers among 100 measurements (7.00%)
  6 (6.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q20  time:   [3.7943 ms 3.7987 ms 3.8037 ms]
                        change: [-0.4696% -0.2517% -0.0323%] (p = 0.02 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q21  time:   [5.7238 ms 5.7279 ms 5.7321 ms]
                        change: [-0.3685% -0.2011% -0.0428%] (p = 0.02 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild

physical_plan_tpch_q22  time:   [2.6413 ms 2.6610 ms 2.6939 ms]
                        change: [-0.2031% +0.5955% +1.8973%] (p = 0.34 > 0.05)
                        No change in performance detected.
Found 9 outliers among 100 measurements (9.00%)
  5 (5.00%) high mild
  4 (4.00%) high severe

physical_plan_tpch_all  time:   [9.3429 ms 9.3899 ms 9.4570 ms]
                        change: [-0.5264% +0.0285% +0.7099%] (p = 0.95 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) low mild
  2 (2.00%) high mild
  2 (2.00%) high severe

```
</details>
according to these results, there is definitely some noise across different runs. However, they are generally within 10%.

**Comment by simonvandel** [comment]
> I re-ran benchmarks in my machine. The results are below

Sorry for the noise, I must have somehow messed up. I also get green numbers now.

I wanted to merge main into this PR to get a direct comparison, but there are some conflicts.
So this is only comparing the PR head with the main head.
Baseline: b220f03fffda22c70f03fa84e244cf04f0e6644c
This PR commit: a8fac85429f519ea5ae258a2a6425eaa9ab333c8

I guess it would be good to do a final run when this PR merges cleanly with main.

<details>
<summary>Results</summary>

```
logical_select_one_from_700
                        time:   [571.99 µs 573.71 µs 575.87 µs]
                        change: [-2.3965% -1.9565% -1.5211%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
  1 (1.00%) low mild
  4 (4.00%) high mild
  5 (5.00%) high severe

physical_select_one_from_700
                        time:   [4.0660 ms 4.0824 ms 4.1013 ms]
                        change: [-2.8819% -1.9879% -1.1440%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe

logical_trivial_join_low_numbered_columns
                        time:   [591.08 µs 593.13 µs 595.76 µs]
                        change: [-6.5247% -2.7512% -0.3801%] (p = 0.09 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) high mild
  6 (6.00%) high severe

logical_trivial_join_high_numbered_columns
                        time:   [633.10 µs 634.01 µs 634.98 µs]
                        change: [-3.4749% -2.6612% -1.9606%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low mild
  1 (1.00%) high mild
  2 (2.00%) high severe

Benchmarking logical_aggregate_with_join: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.5s, enable flat sampling, or reduce sample count to 60.
logical_aggregate_with_join
                        time:   [1.0910 ms 1.0924 ms 1.0939 ms]
                        change: [-3.0224% -2.1454% -1.3335%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe

physical_plan_tpch_q1   time:   [7.8388 ms 7.8798 ms 7.9215 ms]
                        change: [-5.4862% -4.6508% -3.8017%] (p = 0.00 < 0.05)
                        Performance has improved.

physical_plan_tpch_q2   time:   [11.599 ms 11.660 ms 11.732 ms]
                        change: [-29.491% -28.931% -28.370%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe

physical_plan_tpch_q3   time:   [3.8482 ms 3.8557 ms 3.8645 ms]
                        change: [-22.953% -22.571% -22.194%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) high mild
  3 (3.00%) high severe

physical_plan_tpch_q4   time:   [2.9394 ms 2.9436 ms 2.9481 ms]
                        change: [-13.579% -13.302% -13.037%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q5   time:   [5.7565 ms 5.7768 ms 5.7990 ms]
                        change: [-58.072% -57.831% -57.580%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  4 (4.00%) high mild
  4 (4.00%) high severe

Benchmarking physical_plan_tpch_q6: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 9.3s, enable flat sampling, or reduce sample count to 50.
physical_plan_tpch_q6   time:   [1.8326 ms 1.8348 ms 1.8373 ms]
                        change: [-4.3461% -3.8854% -3.3835%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  3 (3.00%) high mild
  5 (5.00%) high severe

physical_plan_tpch_q7   time:   [8.1415 ms 8.1731 ms 8.2058 ms]
                        change: [-45.628% -45.283% -44.930%] (p = 0.00 < 0.05)
                        Performance has improved.

physical_plan_tpch_q8   time:   [11.600 ms 11.647 ms 11.697 ms]
                        change: [-72.389% -72.217% -72.048%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

physical_plan_tpch_q9   time:   [8.7531 ms 8.7829 ms 8.8135 ms]
                        change: [-47.833% -47.538% -47.232%] (p = 0.00 < 0.05)
                        Performance has improved.

physical_plan_tpch_q10  time:   [5.9565 ms 5.9761 ms 5.9972 ms]
                        change: [-31.327% -30.949% -30.571%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  5 (5.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q11  time:   [4.7788 ms 4.7900 ms 4.8030 ms]
                        change: [-23.407% -20.882% -18.549%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe

physical_plan_tpch_q12  time:   [3.8070 ms 3.8132 ms 3.8200 ms]
                        change: [-13.715% -13.448% -13.212%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  4 (4.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q13  time:   [2.4866 ms 2.4904 ms 2.4944 ms]
                        change: [-21.541% -21.256% -20.973%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild

physical_plan_tpch_q14  time:   [3.2541 ms 3.2599 ms 3.2664 ms]
                        change: [-2.6579% -2.3979% -2.1429%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  5 (5.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q16  time:   [4.9112 ms 4.9275 ms 4.9454 ms]
                        change: [-18.165% -17.709% -17.242%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 12 outliers among 100 measurements (12.00%)
  6 (6.00%) high mild
  6 (6.00%) high severe

physical_plan_tpch_q17  time:   [4.7187 ms 4.7405 ms 4.7678 ms]
                        change: [-6.2345% -5.6606% -5.0112%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  4 (4.00%) high mild
  5 (5.00%) high severe

physical_plan_tpch_q18  time:   [5.1662 ms 5.1835 ms 5.2024 ms]
                        change: [-10.562% -10.086% -9.5753%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

physical_plan_tpch_q19  time:   [9.6546 ms 9.6977 ms 9.7416 ms]
                        change: [-3.6676% -3.0457% -2.4012%] (p = 0.00 < 0.05)
                        Performance has improved.

physical_plan_tpch_q20  time:   [6.1156 ms 6.1346 ms 6.1554 ms]
                        change: [-12.986% -12.532% -12.057%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_q21  time:   [9.0939 ms 9.1482 ms 9.2128 ms]
                        change: [-34.273% -33.805% -33.250%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high severe

physical_plan_tpch_q22  time:   [4.3380 ms 4.3443 ms 4.3512 ms]
                        change: [-14.344% -14.025% -13.729%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

physical_plan_tpch_all  time:   [12.851 ms 12.870 ms 12.890 ms]
                        change: [-0.5789% -0.3165% -0.0670%] (p = 0.02 < 0.05)
                        Change within noise threshold.
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) high mild
  1 (1.00%) high severe
```

</details>

**Comment by ozankabak** [comment]
@alamb, I did one final review to make sure all looks good. Since this will attract a lot of merge conflicts, it'd be a good idea to merge this sooner rather than later.

Given the benchmark confusion is out of the way too, are you OK with merging?

**Comment by alamb** [comment]
I am running benchmark numbers now

**Review by alamb — APPROVED** [review]
I compared this branch with  b220f03fffda22c70f03fa84e244cf04f0e6644c (the merge base)

```shell
git checkout b220f03fffda22c70f03fa84e244cf04f0e6644c
cargo bench --bench sql_planner
git checkout feature/remove_default_cache 
cargo bench --bench sql_planner
```

All the performance seems to be faster or the same. Results:  [results.txt](https://github.com/apache/arrow-datafusion/files/14438522/results.txt)


Thanks again everyone

**Comment by alamb** [comment]
I have a follow on PR proposal https://github.com/apache/arrow-datafusion/pull/9389 to improve the documentation

**Comment by ozankabak** [comment]
Thanks everyone for the awesome collaboration!
