### PR TITLE
Remove input schema from PhysicalExpr, move the validation logic to physical expression planner

### LINKED ISSUE #6117: Remove input schema from PhysicalExpr, move the validation logic to phyiscal expression planner
### Describe the bug

https://github.com/apache/arrow-datafusion/pull/6114

The `input_schema` was added to the `InListExpr` by mistake, it cause issues during `transform()` rewrite process, should remove it.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mingmwang**
# Which issue does this PR close?

Closes #6117.

# Rationale for this change

FollowUp after https://github.com/apache/arrow-datafusion/pull/6114

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by mingmwang** [comment]
@crepererum

**Review by crepererum — APPROVED** [review]
This is sooo much cleaner, thank you!

File: datafusion/physical-expr/src/expressions/datetime.rs [hunk 1]
```diff
@@ -37,45 +37,16 @@ pub struct DateTimeIntervalExpr {
     lhs: Arc<dyn PhysicalExpr>,
     op: Operator,
     rhs: Arc<dyn PhysicalExpr>,
-    // TODO: move type checking to the planning phase and not in the physical expr
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/datetime.rs:40]: 🎉

File: datafusion/physical-expr/src/expressions/in_list.rs [hunk 2]
```diff
@@ -172,36 +171,36 @@ where
 }
 
 /// Creates a `Box<dyn Set>` for the given list of `IN` expressions and `batch`
-fn make_set(array: &dyn Array) -> Result<Box<dyn Set>> {
+fn make_set(array: &dyn Array) -> Result<Arc<dyn Set>> {
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/in_list.rs:174]: This is a clever idea -- to avoid cloning the set over and over again 👍

File: datafusion/physical-expr/src/utils.rs [hunk 3]
```diff
@@ -586,28 +586,7 @@ pub fn reassign_predicate_columns(
                 column.name(),
                 index,
             ))));
-        } else if let Some(in_list) = expr_any.downcast_ref::<InListExpr>() {
```
Comment (alamb) [inline datafusion/physical-expr/src/utils.rs:589]: 🎉

File: datafusion/physical-expr/src/expressions/datetime.rs [hunk 4]
```diff
@@ -220,6 +190,36 @@ impl PartialEq<dyn Any> for DateTimeIntervalExpr {
     }
 }
 
+/// create a DateIntervalExpr
+pub fn date_time_interval_expr(
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/datetime.rs:194]: 👍  this also follows the model of the other creation functions in physical expr.

File: datafusion/physical-expr/src/expressions/mod.rs [hunk 5]
```diff
@@ -78,7 +78,7 @@ pub use cast::{
     cast, cast_column, cast_with_options, CastExpr, DEFAULT_DATAFUSION_CAST_OPTIONS,
 };
 pub use column::{col, Column, UnKnownColumn};
-pub use datetime::DateTimeIntervalExpr;
+pub use datetime::{date_time_interval_expr, DateTimeIntervalExpr};
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/mod.rs:81]: 👍

**Review by alamb — APPROVED** [review]
This looks great to me -- thank you @mingmwang 

cc @crepererum I think @mingmwang  has fixed the root cause of the inlist discrepancy you fixed in https://github.com/apache/arrow-datafusion/pull/6114
