### PR TITLE
preserve array type / timezone in `date_bin` and `date_trunc` functions

### LINKED ISSUE #5976: `date_trunc` drops timezone
### Describe the bug

`date_trunc` drops timezone while the input is timestamptz

### To Reproduce

```bash
❯ select date_trunc('hour', timestamptz '2000-01-01T00:00:00Z');
+------------------------------------------------------+
| datetrunc(Utf8("hour"),Utf8("2000-01-01T00:00:00Z")) |
+------------------------------------------------------+
| 2000-01-01T00:00:00                                  |
+------------------------------------------------------+
1 row in set. Query took 0.002 seconds.
```

### Expected behavior

2000-01-01T00:00:00Z

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mhilton**
## Which issue does this PR close?

Closes #5976. N.B. this issue is already closed, but I don't think the issue was completely fixed.

## Rationale for this change

Elliding timezone information in these functions makes the data harder to process downstream. It would have been sufficient for the purposes of not losing information to normalize all timezones to "+00" (UTC), however if the trouble has been taken to convert a time to a particular timezone it is friendlier to preserve that.

## What changes are included in this PR?

The result type of date_bin and date_trunc never includes any timezone information. Change this such that the timezone of the resulting array from these functions is copied from the input array.

## Are these changes tested?

Yes

## Are there any user-facing changes?

I don't think this would be considered user facing.

### CODE REVIEW

File: datafusion/expr/src/built_in_function.rs [hunk 1]
```diff
@@ -618,13 +618,20 @@ impl BuiltinScalarFunction {
...
-                    Timestamp(Nanosecond, _) | Utf8 | Null => {
+                match &input_expr_types[1] {
+                    Timestamp(Nanosecond, None) | Utf8 | Null => {
                         Ok(Timestamp(Nanosecond, None))
                     }
-                    Timestamp(Microsecond, _) => Ok(Timestamp(Microsecond, None)),
-                    Timestamp(Millisecond, _) => Ok(Timestamp(Millisecond, None)),
-                    Timestamp(Second, _) => Ok(Timestamp(Second, None)),
+                    Timestamp(Nanosecond, Some(tz)) => {
+                        Ok(Timestamp(Nanosecond, Some(Arc::clone(tz))))
```
Comment (Weijun-H) [inline datafusion/expr/src/built_in_function.rs:626]:
```suggestion
                    Timestamp(Nanosecond, tz_opt) => {
                        Ok(Timestamp(Nanosecond, tz_opt.clone())))
```

**Comment by alamb** [comment]
I am sorry @mhilton  -- I ran out of time today to review this PR. I plan to do so tomorrow

**Review by alamb — APPROVED** [review]
Thank you @mhilton  -- this makes sense to me.

I wonder if we could add at least one end to end sql test in https://github.com/apache/arrow-datafusion/blob/main/datafusion/sqllogictest/test_files/timestamps.slt that shows the timezone being preserved (to something other than UTC)?

File: datafusion/physical-expr/src/datetime_expressions.rs [hunk 2]
```diff
@@ -1051,6 +1077,91 @@ mod tests {
         });
     }
 
+    #[test]
+    fn test_date_trunc_timezones() {
+        let cases = vec![
+            (
+                vec![
+                    "2020-09-08T00:00:00Z",
```
Comment (alamb) [inline datafusion/physical-expr/src/datetime_expressions.rs:1085]: Given the usecase is preseving timezones, it may make sense to also check with timezones other than `Z` (like maybe +5 or +8 🤔

**Review by Weijun-H — COMMENTED** [review]
LGTM! Thanks @mhilton 👍

**Review by Weijun-H — APPROVED** [review]

File: datafusion/physical-expr/src/datetime_expressions.rs (hunk 2 above)
Comment (mhilton) [reply datafusion/physical-expr/src/datetime_expressions.rs:1085]: I think the test I had for the "-02" zone was sufficient. The way times are stored is always as a UTC offset, the zone information really just indicates how the offset needs to be interpretted. These strings are only used to derive th offset and therefore the specified zone is ignored when creating the array. However, more tests don't hurt so I've added the ones you suggested for clarity.

Comment (alamb) [reply datafusion/physical-expr/src/datetime_expressions.rs:1085]: Thanks -- sorry for my confusion

**Review by alamb — APPROVED** [review]
Thank you @mhilton

**Comment by alamb** [comment]
(thank you for the review, BTW @Weijun-H 🙏 )
