### PR TITLE
Change input for `to_timestamp` function to be seconds rather than nanoseconds, add `to_timestamp_nanos`

### LINKED ISSUE #7802: `to_timestamp` for negative values gives wrong result
### Describe the bug

In Datafusion `to_timestamp` builtin scalar function gives wrong result for negative values 
```

❯ select to_timestamp(-62125747200);
+-----------------------------------+
| to_timestamp(Int64(-62125747200)) |
+-----------------------------------+
| 1969-12-31T23:58:57.874252800     |
+-----------------------------------+
1 row in set. Query took 0.035 seconds.
```

PG gives correct result 
```
0001-04-25T00:00:00.000Z
```

### To Reproduce

Run 
```
❯ select to_timestamp(-62125747200);
```

### Expected behavior

Query results should match

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #7802.
Closes https://github.com/apache/arrow-datafusion/issues/2979

## Rationale for this change

`to_timestamp()` builtin function had an input in nanoseconds whereas other SQL engines has input in seconds and as the result the function output gives unexpected result.
 

## What changes are included in this PR?
Changed signature to `to_timestamp` function from nanoseconds to seconds, also introduced `to_timestamp_nano` to create timestamp value from nanoseconds

## Are these changes tested?
Yes

## Are there any user-facing changes?

The user might expect that `to_timestamp` function will return other values if the input still in nanoseconds

### CODE REVIEW

**Review by Weijun-H — APPROVED** [review]
LGTM! Thanks @comphead

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 1]
```diff
@@ -1534,10 +1537,10 @@ mod tests {
         let expr = cast_to_int64_expr(now_expr()) + lit(100_i64);
         test_evaluate_with_start_time(expr, lit(ts_nanos + 100), &time);
 
-        //  CAST(now() as int64) < cast(to_timestamp(...) as int64) + 50000_i64 ---> true
+        //  CAST(now() as int64) < cast(to_timestamp(...) as int64) + 50000_i64 ---> false
         let expr = cast_to_int64_expr(now_expr())
             .lt(cast_to_int64_expr(to_timestamp_expr(ts_string)) + lit(50000i64));
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1542]: maybe we can adjust the literal so it still evaluates to true so that we don't lose coverage 🤔

**Review by alamb — APPROVED** [review]
I think this makes sense and aligns DataFusion with postgres. Thank you @comphead  and @Weijun-H 

https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TABLE

**Comment by alamb** [comment]
cc @gruuya  @Dandandan and @waitingkuo and @waynexia  as other people I know who might be using the timestamp functionality of DataFusion and be affected by this change

**Comment by waitingkuo** [comment]
Thank you @comphead @alamb 

This looks great, this closes #2979 as well.

To align with Postgrseql, perhaps we could fire another ticket for supporting more inputs like floating number & string.
i.e. in postgresql
```bash
willy=# select to_timestamp('1.1');
       to_timestamp       
--------------------------
 1970-01-01 08:00:01.1+08
(1 row)

willy=# select to_timestamp(1.1);
       to_timestamp       
--------------------------
 1970-01-01 08:00:01.1+08
```

**Comment by alamb** [comment]
> To align with Postgrseql, perhaps we could fire another ticket for supporting more inputs like floating number & string.

Great idea @waitingkuo.  This is now tracked by two tickets:
* https://github.com/apache/arrow-datafusion/issues/7868
* https://github.com/apache/arrow-datafusion/issues/5398

File: datafusion/expr/src/built_in_function.rs [hunk 2]
```diff
@@ -745,9 +748,10 @@ impl BuiltinScalarFunction {
                     return plan_err!("The to_hex function can only accept integers.");
                 }
             }),
-            BuiltinScalarFunction::ToTimestamp => Ok(Timestamp(Nanosecond, None)),
+            BuiltinScalarFunction::ToTimestamp => Ok(Timestamp(Second, None)),
```
Comment (alamb) [inline datafusion/expr/src/built_in_function.rs:751]: while writing up https://github.com/apache/arrow-datafusion/issues/7868 it occured to me this signature prevents implementing something like `to_timestamp(1.234)` reasonably, as it can't represent sub-second precison

What would you think about leaving the return type the same (`Timestamp(Nanosecond, None)`) so that we can add support for floating point argments as a follow on?

Comment (waitingkuo) [reply datafusion/expr/src/built_in_function.rs:751]: Return `Timestamp(Nanosecond, None)` seems reasonable to me since most of the time related functions in datafusion return nanosecond based timestamp i.e. `timestamp '2000-01-01T00:00:00'`, `now()`, ...

Comment (comphead) [reply datafusion/expr/src/built_in_function.rs:751]: In PG 
```
select pg_typeof(to_timestamp(1.234))
```
the return type is `timestamp with time zone` which has minimum resolution as a microsecond

https://www.postgresql.org/docs/current/datatype-datetime.html

In light of this, having the return type as nanos or micros makes more sense for me.
What do you think is better? microseconds like in PG or nanos like it was in DF before the PR?

Comment (alamb) [reply datafusion/expr/src/built_in_function.rs:751]: I don't have any preference now that we have coercion rules that can automatically coerce between timestamp resolution

Comment (comphead) [reply datafusion/expr/src/built_in_function.rs:751]: got it, I'll do micros as a return type as it is in PG, will update the PR soon

Comment (comphead) [reply datafusion/expr/src/built_in_function.rs]: set return type to nanos as it was before.

**Review by alamb — APPROVED** [review]

File: datafusion/physical-expr/src/functions.rs [hunk 3]
```diff
@@ -74,15 +74,20 @@ pub fn create_physical_expr(
...
-                        )
-                    }
-                }
+                Ok(DataType::Int64) => |col_values: &[ColumnarValue]| {
+                    cast_column(
+                        &col_values[0],
+                        &DataType::Timestamp(TimeUnit::Second, None),
+                        None,
+                    )
+                },
```
Comment (waitingkuo) [inline datafusion/physical-expr/src/functions.rs:83]: it still returns Timestamp(second, None) while the input is Int64
```bash
❯ select arrow_typeof(to_timestamp(0));
+--------------------------------------+
| arrow_typeof(to_timestamp(Int64(0))) |
+--------------------------------------+
| Timestamp(Second, None)              |
+--------------------------------------+
1 row in set. Query took 0.003 seconds.
```

File: datafusion/expr/src/built_in_function.rs [hunk 4]
```diff
@@ -748,6 +751,7 @@ impl BuiltinScalarFunction {
             BuiltinScalarFunction::ToTimestamp => Ok(Timestamp(Nanosecond, None)),
```
Comment (waitingkuo) [inline datafusion/expr/src/built_in_function.rs:751]: @alamb  @comphead 
any idea why the function  could return `Timestamp(Second, None)` even though we set the return type here as `Timestamp(Nanosecond, None)`?

**Review by waitingkuo — CHANGES_REQUESTED** [review]

File: datafusion/expr/src/built_in_function.rs (hunk 4 above)
Comment (comphead) [reply datafusion/expr/src/built_in_function.rs:751]: Thanks @waitingkuo for raising it.
I suppose for bunch of functions the return type gets changed  in `create_physical_expr` because `functions.rs` is on physical expr layer and rewrites the return type defined on logical layer. 

For ints I would think the second is probably better return type
If you try to present 0004-01-01 year in nanoseconds it will require higher value than `i64::MAX/MIN`
https://doc.rust-lang.org/src/core/num/mod.rs.html#366

```
make_type!(
    TimestampNanosecondType,
    i64,
    DataType::Timestamp(TimeUnit::Nanosecond, None),
    "A timestamp nanosecond type with an optional timezone."
);
```
But you are right we need to clean up builtin functions configuration in multiple places.

**Review by Dandandan — APPROVED** [review]

File: datafusion/expr/src/built_in_function.rs [hunk 5]
```diff
@@ -748,6 +751,7 @@ impl BuiltinScalarFunction {
...
             BuiltinScalarFunction::ToTimestampMillis => Ok(Timestamp(Millisecond, None)),
             BuiltinScalarFunction::ToTimestampMicros => Ok(Timestamp(Microsecond, None)),
+            BuiltinScalarFunction::ToTimestampNanos => Ok(Timestamp(Nanosecond, None)),
```
Comment (Dandandan) [inline datafusion/expr/src/built_in_function.rs:754]: We  could map `to_timestamp` to `ToTimestampSeconds` as well durig planing.

**Review by waitingkuo — APPROVED** [review]

**Comment by comphead** [comment]
@alamb should we merge the PR?

**Comment by alamb** [comment]
I think so @comphead  -- it has had plenty of review by now and no objections.
