### PR TITLE
fix: DataFusion suggests invalid functions

### LINKED ISSUE #8082: DataFusion suggests invalid functions
### Describe the bug

```sh
DataFusion CLI v33.0.0
❯ select covaria(1,1);
Error during planning: Invalid function 'covaria'.
Did you mean 'COVARIANCE'?

❯ select COVARIANCE(1,1);
Error during planning: Invalid function 'covariance'.
Did you mean 'COVARIANCE'?
```
The function `COVARIANCE` in this suggestion is invalid.

### To Reproduce

As mentioned above.

### Expected behavior

All suggested functions should be valid.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #8082.

## Rationale for this change
DataFusion use the `name()` method to generate suggestions for aggregate functions.
 https://github.com/apache/arrow-datafusion/blob/f3c9009e50fdb5811c522bfb07ba29ac04cd1d22/datafusion/expr/src/function.rs#L91-L91
https://github.com/apache/arrow-datafusion/blob/f3c9009e50fdb5811c522bfb07ba29ac04cd1d22/datafusion/expr/src/aggregate_function.rs#L148-L152

We need to ensure that the `name()` method returns valid SQL function names.

## Are these changes tested?
Yes
## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/expr/src/aggregate_function.rs [hunk 1]
```diff
@@ -411,3 +411,23 @@ impl AggregateFunction {
...
+mod tests {
+    use super::*;
+    use strum::IntoEnumIterator;
+
+    #[test]
+    // Test for AggregateFuncion's Display and from_str() implementations.
+    // For each variant in AggregateFuncion, it converts the variant to a string
+    // and then back to a variant. The test asserts that the original variant and
+    // the reconstructed variant are the same.
+    fn test_display_and_from_str() {
```
Comment (jonahgao) [inline datafusion/expr/src/aggregate_function.rs:425]: This test is mostly copied from the test for `BuiltinScalarFunction`.
https://github.com/apache/arrow-datafusion/blob/f3c9009e50fdb5811c522bfb07ba29ac04cd1d22/datafusion/expr/src/built_in_function.rs#L1625

**Review by alamb — APPROVED** [review]
Thank you @jonahgao  -- this is great. 

I tried out master:
```
❯ select COVARIANCE(y) from x;
Error during planning: Invalid function 'covariance'.
Did you mean 'COVARIANCE'?
```

I wonder if we need to do something similar for window functions?

The one I tried seemed to work well:

```
❯ select FIRST_V(y) from x;
Error during planning: Invalid function 'first_v'.
Did you mean 'FIRST_VALUE'?
❯ select FIRST_VALUE(y) from x;
+------------------+
| FIRST_VALUE(x.y) |
+------------------+
| 1                |
+------------------+
```

**Comment by jonahgao** [comment]
> I wonder if we need to do something similar for window functions?

I added the same test to check the `BuiltInWindowFunction`.

**Review by alamb — APPROVED** [review]
Thanks again @jonahgao
