### PR TITLE
Removes Bloom filter for Int8/Int16/Uint8/Uint16

### LINKED ISSUE #9914: Disable parquet bloom filters for `UInt8`, `Int8`, `UInt16` and `Int16` columns
### Describe the bug

As @progval discovered, bloom filters on these types return no results (incorrect answers): https://github.com/apache/arrow-datafusion/issues/9779

Technically I think this is a regression as previously bloom filters on these column types would be ignored

### To Reproduce

Not sure (see unit tests for parquet filters, eg. that were added in https://github.com/apache/arrow-datafusion/pull/9770)

### Expected behavior

I think we should disable bloom filters for these types on parquet for now (and maybe update the tests) until we have fixed https://github.com/apache/arrow-datafusion/issues/9779

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edmondop**
Closes #9914 .

related to https://github.com/apache/arrow-datafusion/issues/9779

I also removed the possibility to writing tests that pass and confirm that "something doesn't work, as expected". I suppose this could be confusing and was the reason why broken bloom filters for int8/int16/uint8/uint16 slipped in a previous PR, but it's a separate commit so I can rollback if necessary

### CODE REVIEW

File: datafusion/core/tests/parquet/row_group_pruning.rs [hunk 1]
```diff
@@ -447,17 +447,15 @@ macro_rules! int_tests {
     };
 }
 
-int_tests!(8, correct_bloom_filters: false);
-int_tests!(16, correct_bloom_filters: false);
-int_tests!(32, correct_bloom_filters: true);
-int_tests!(64, correct_bloom_filters: true);
+int_tests!(32);
```
Comment (alamb) [inline datafusion/core/tests/parquet/row_group_pruning.rs:450]: I think it would help to give future readers a hint here about why 8/16 aren't supported (rather than just an oversight):

```suggestion
// int8/int16 are incorrect: https://github.com/apache/arrow-datafusion/issues/9779
int_tests!(32);
```

File: datafusion/core/tests/parquet/row_group_pruning.rs [hunk 2]
```diff
@@ -585,10 +583,8 @@ macro_rules! uint_tests {
     };
 }
 
-uint_tests!(8, correct_bloom_filters: false);
-uint_tests!(16, correct_bloom_filters: false);
-uint_tests!(32, correct_bloom_filters: true);
-uint_tests!(64, correct_bloom_filters: true);
+uint_tests!(32);
```
Comment (alamb) [inline datafusion/core/tests/parquet/row_group_pruning.rs:586]: Likewise here

```suggestion
// uint8/uint16 are incorrect: https://github.com/apache/arrow-datafusion/issues/9779
uint_tests!(32);
```

**Review by alamb — APPROVED** [review]
Thank you @edmondop  -- this makes sense. Keeping the code correct 💯 . 

cc @progval 

I'll leave a note on https://github.com/apache/arrow-datafusion/issues/9779 that we can revert the changes in this PR when the issue is fixed.
