### PR TITLE
Fix limit when size of batch to poll == skip/fetch value

### LINKED ISSUE #5064: Limit doesn't drop on first batch when limit size == fetch size.
**Describe the bug**
In the When batch size equals the fetch size, datafusion doesn't drop the input.
It will poll for another batch from the input rather than dropping immediately.

**To Reproduce**

**Expected behavior**
It should drop the input directly instead of polling for a second.

**Additional context**

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #5064

# Rationale for this change
Bug fix. I found this when working with the Coralogix which pushes down limits to fully to the scan (so the batch size almost always equals the limit).

# What changes are included in this PR?

Change `<=` to `<` 🥳 

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/core/src/physical_plan/limit.rs [hunk 1]
```diff
@@ -571,6 +572,36 @@ mod tests {
...
+            LimitStream::new(Box::pin(input), 0, Some(6), baseline_metrics);
+        assert_eq!(index.value(), 0);
+
+        let results = collect(Box::pin(limit_stream)).await.unwrap();
+        let num_rows: usize = results.into_iter().map(|b| b.num_rows()).sum();
+        // Only 6 rows should have been produced
+        assert_eq!(num_rows, 6);
+
+        // Only the first batch should be consumed
+        assert_eq!(index.value(), 1);
```
Comment (Dandandan) [inline datafusion/core/src/physical_plan/limit.rs:600]: This returns `2` on master

**Review by thinkharderdev — APPROVED** [review]
