### PR TITLE
fix: Do not panic on invalid placeholders

### LINKED ISSUE #5856: `LogicalPlan::replace_params_with_values` panics if a placeholder with id `$0` is present
### Describe the bug

`LogicalPlan::replace_placeholders_with_values` subtracts one from a parsed `usize` value, which may result in a panic due to integer overflow.

<https://github.com/apache/arrow-datafusion/blob/fd350fa176b11ae6dc82d7813ed57290ac026c26/datafusion/expr/src/logical_plan/plan.rs#L617-L623>

### To Reproduce

_No response_

### Expected behavior

Returning an `Err(_)` value to indicate the problem, like it does in other error cases.

### Additional context

Similar to #5786 but concerns a later stage.

### PR DESCRIPTION
**Pull request by Weijun-H**
# Which issue does this PR close?

Closes #5856

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by r4ntix — APPROVED** [review]

File: datafusion/expr/src/logical_plan/plan.rs [hunk 1]
```diff
@@ -605,6 +605,11 @@ impl LogicalPlan {
         expr.transform(&|expr| {
             match &expr {
                 Expr::Placeholder { id, data_type } => {
+                    if id.is_empty() {
+                        return Err(DataFusionError::Internal(
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:609]: What do you think about making this a `DataFusion::Plan` error rather than `Internal` -- it seems to me this isn't a bug in datafusion (which is what `Internal` represents) but rather a bug in the code that called DataFusion.

File: datafusion/expr/src/logical_plan/plan.rs [hunk 2]
```diff
@@ -2330,4 +2335,22 @@ mod tests {
...
     }
+
+    #[test]
+    fn test_replace_invalid_placeholder_empty() {
+        let schema = Schema::new(vec![Field::new("id", DataType::Int32, false)]);
+
+        let plan = table_scan(TableReference::none(), &schema, None)
+            .unwrap()
+            .filter(col("id").eq(Expr::Placeholder {
+                id: "".into(),
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:2346]: https://github.com/apache/arrow-datafusion/issues/5856 also reports an issue if `"$0"` is provided in addition to `""`. Can you please add a test for that as well?

**Review by alamb — APPROVED** [review]

**Review by yjshen — APPROVED** [review]
